### ISSUE TITLE
Should we use an 'enum' type for enumerated values?

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#1031]
E.g., wherever the back-end takes a string value, but requires that it be one of a set of known values?  Likewise for integers which map protobuf `enum` values.

@dhermes [suggested](https://github.com/GoogleCloudPlatform/gcloud-python/pull/1022#discussion_r35886493) using https://pypi.python.org/pypi/enum.

I [favor](https://github.com/GoogleCloudPlatform/gcloud-python/pull/1022#discussion_r36201550) using the PEP-435-compatible https://pypi.python.org/pypi/enum34/, which backports the `enum` from the Python 3.4 stdlib.

**Comment by dhermes** [comment]
I meant `enum34`, just was in a hurry when getting the link.

**Comment by tseaver** [comment]
Cool.

**Comment by dhermes** [comment]
@tseaver Can we move forward with this or close it out?

**Comment by daspecster** [comment]
@tseaver @dhermes bump!

I would like to use this in Vision if that's ok?

**Comment by dhermes** [comment]
Our dependencies already pull in `enum34` so that's totally fine with me.

**Comment by daspecster** [comment]
Spiffy, I'll closet this then and proceed!
