### ISSUE TITLE
Query.next_page() should produce a null cursor if not set on response

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#1054]
Currently it returns an empty string.

**Comment by dhermes** [comment]
Noticed this during #1055

**Comment by dhermes** [comment]
OK, [checking][1] `response.batch.HasField('end_cursor')` is always `True`, even when the cursor is `''`.

@tseaver WDYT we should do here? I think returning `''` and [setting it][2] as the `_start_cursor` value on an `Iterator` is not the right move.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/2d017def36a2f8985d54aff1cc2984b64a922c74/gcloud/datastore/connection.py#L267
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/2d017def36a2f8985d54aff1cc2984b64a922c74/gcloud/datastore/query.py#L421

**Comment by tseaver** [comment]
@dhermes While investigating, it just seemed easier to make the change (to ensure I didn't break anything).

**Comment by dhermes** [comment]
No worries.

**Comment by dhermes** [comment]
@tseaver Turns out this issue still open.

Remaining concern: Should `Connection.run_query` check if the `end_cursor` is set on the `response.batch`?

**Comment by dhermes** [comment]
@tseaver Bump

**Comment by tseaver** [comment]
I assume you are worried about [this line](https://github.com/GoogleCloudPlatform/gcloud-python/blob/f3933181603f58ecd32a905a06ace939dafc3099/gcloud/datastore/connection.py#L265).  If the response protobuf doesn't have a value set, we get a `None` there, right?  That seems like the right sentinel to me.

**Comment by dhermes** [comment]
See what I said [above][1]:

> checking `response.batch.HasField('end_cursor')` is always True, even when the cursor is `''`.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/issues/1054#issuecomment-130108551
