### ISSUE TITLE
Add support for Datastore Statistics

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#1067]
See https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/62

```
SELECT * FROM __Stat_Total__
```

is an example for adding some support.

**Comment by dhermes** [comment]
More general doc:
https://cloud.google.com/datastore/docs/concepts/stats

**Comment by dhermes** [comment]
There are 9 properties which can be used both for non-namespace stats and namespace stats:

```
__Stat_(Ns_|)PropertyName_Kind__
__Stat_(Ns_|)PropertyType_PropertyName_Kind__
__Stat_(Ns_|)Kind__
__Stat_(Ns_|)Kind_IsRootEntity__
__Stat_(Ns_|)Kind_NotRootEntity__
__Stat_(Ns_|)PropertyType_Kind__
__Stat_(Ns_|)Kind_CompositeIndex__
__Stat_(Ns_|)PropertyType__
__Stat_(Ns_|)Total__
```

In addition there is a 10th (or 19th, depending on how you are counting) property

```
'__Stat_Namespace__',
```

**Comment by dhermes** [comment]
Performing queries like

```python
query = client.query(kind='__Stat_PropertyName_Kind__')
query_iter = query.fetch(limit=11)
entities, more_results, cursor = query_iter.next_page()
```

seem to indicate that there are only 10 entities for some kinds and the key names corresponds to the actual data in the datastore

----

For the `'__Stat_Total__'` kind, it seems there is only one key

```python
total_key = client.key('__Stat_Total__', 'total_entity_usage')
total_key = client.key('__Stat_Ns_Total__', 'total_entity_usage',
                       namespace='some-namespace')
```

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!

**Comment by sungmoring** [comment]
total_key = client.key('__Stat_Total__', 'total_entity_usage')
total_key = client.key('__Stat_Ns_Total__', 'total_entity_usage',
                       namespace='some-namespace')

How to do this in C# ?

**Comment by chemelnucfin** [comment]
Does this help?
[dotnet-docs-samples](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/datastore/api/TaskListTest/DatastoreTest.cs)

You might have better luck [here](https://github.com/GoogleCloudPlatform/google-cloud-dotnet)?
