### ISSUE TITLE
Add examples to resource_manager functions

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-python#1102]

**Comment by dhermes** [comment]
@tseaver This is a continuation of the discussion from #1083 (and I believe, partially in #911, but may be misremembering that one)

**Comment by jgeewax** [comment]
Yep. Bottom line:

- People like narrative documentation when it's short. When it's long, it's a really long read, and people don't like really long reads. (This is long. Useful, but long: https://googlecloudplatform.github.io/gcloud-python/stable/pubsub-usage.html)

- Examples next to every method got great feedback -- people seemed to prefer "jumping into the code" over reading before writing. Over eager? Sure. But people really appreciated seeing examples next to the methods: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.20.0/search/index?method=createDocument

**Comment by lukesneeringer** [comment]
A quick scan suggests to me that the examples now exist.
