### ISSUE TITLE
System tests for resource manager

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#1105]
After #1083, we now need system tests for the Resource Manager API.

Since the API requires using a user account (not a service account), this is a bit hairy.

For `oauth2client`'s system tests, we ended up just using a simple refresh token for my personal GMail account. The token is only authorized with the `email` scope, so it's not a very big deal, but for this one, it may be a bigger deal?

**Comment by jgeewax** [comment]
Later this yea, I hear that service accounts will be able to own (and therefore create) projects -- and then this problem goes away.

In the meantime, we could always make the choice to punt on this and just "not have system tests for RM" ...? I suspect this isn't going to be a frequently used API...

**Comment by dhermes** [comment]
OK.

**Comment by dhermes** [comment]
@jgeewax Any kind of update on this?

**Comment by tseaver** [comment]
Apparently #1614 is due to a similar policy (sinks can only be created by user accounts).  @jgeewax can you lean on the teams responsible to fix that issue?

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
