### ISSUE TITLE
Publish a downloadable windows installer?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-python#1124]
Is this worthwhile? Lots of people want the MSI....

**Comment by dhermes** [comment]
...which people? These people must not be GitHub users? (FWIW we've seen #1009, which reports an issue with `PyCrypto`. But we don't strictly need to rely on `PyCrypto`.)

@tseaver Do you have any experience building an MSI? @jgeewax Do you (or know anyone, maybe on the `gcloud` CLI team) that does?

I Googled around for a bit and found [`pynsist`][1] and [`pyinstaller`][2] but they don't really seem to do the trick.

[1]: https://github.com/takluyver/pynsist
[2]: https://github.com/pyinstaller/pyinstaller

**Comment by tseaver** [comment]
@dhermes My experience is limited to supporting the folks who manage `winbot.zope.org`, which builds the Windows binaries (`.egg` and `.exe`) for the Zope-related packages.  I can dig into how that machine is configured, if desired, but I haven't run Windows *anywhere* for more than fifteen years.

**Comment by dhermes** [comment]
It seems someone is trying to solve this problem in a big way:

https://packaging.python.org/en/latest/appveyor.html
http://www.appveyor.com/

**Comment by dhermes** [comment]
Seems we could have Appveyor only build on tags: http://www.appveyor.com/docs/branches

@tseaver Do you know if it's easy to add a file (i.e. a Windows MSI) to an existing PyPI upload? Or maybe we should stop pushing new versions from Travis and just do it from Appveyor?

**Comment by tseaver** [comment]
@dhermes You can upload additional dists to an already-registered and uploaded release, even from different machines / accounts (as long as the uploading account has the `maintainer` role):  `winbot.zope.org` polls for new `sdist` releases to its package set and builds/uploads the Windows-specific binary distributions.

E.g.:

```bash
$ python setup.py register sdist upload
$ python setup.py bdist_whatever upload
```

**Comment by dhermes** [comment]
Working on this today

**Comment by dhermes** [comment]
@jgeewax and I just discussed. Since we don't have any native code, our wheels and MSI can be built on any platform, so we just need to add XXX to the Travis [`distributions`][1].

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/2323e1a110d240545bf2950e18e5ccefb75d01f1/.travis.yml#L30
[2]:

**Comment by dhermes** [comment]
Update: Running `python setup.py bdist_msi` completely fails 

```
error: invalid command 'bdist_msi'
```

and `python setup.py bdist_wininst` runs but fails to complete with

```
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules _winreg, win32api or win32con are installed.
error: [Errno 2] No such file or directory: '/usr/lib/python2.7/distutils/command/wininst-6.0.exe', /usr/lib/python2.7/distutils/command/wininst-6.0.exe not included in the Debian packages.
```

This seems to contradict a comment from the [docs][1]:

> These installers can even be created on Unix platforms or Mac OS X.

[1]: https://docs.python.org/2/distutils/builtdist.html
