### ISSUE TITLE
Consolidate _Client and _Connection test shims

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#1147]
See https://github.com/GoogleCloudPlatform/gcloud-python/pull/1145/files#r40022552

Running `git grep -l _Client` and `git grep -l _Connection` turns up a lot of results.

In keeping with @tseaver philosophy, we should avoid added more than the basic functionality common to all tests using this pattern.

**Comment by lukesneeringer** [comment]
This seems obselete. Reopen if not.
