### ISSUE TITLE
Split out APIs into separately-installable distributions?

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#1159]
- `gcloud` on PyPI would include "core" modules.
- `gcloud` would (maybe) become a namespace package
- Each API would have a separate PyPI "project"/releases

Cons (mostly for maintainers):
- separate release cycles
- More complicated CI
- Might need to split repos?

Pros (mostly for users):
- "Hard" dependencies for each API (`gRPC`, I'm looking at you)
- Separately updateable distributions
- "Pay only for what you eat"

**Comment by dhermes** [comment]
Comments on cons:

- **separate release cycles**: I think this is a good thing, but a tiny bit problematic if updates to core break the service-specific packages
- **More complicated CI**: Yup, we'd need to kick off a run of Travis every time a downstream dependency is updated
- **Might need to split repos?**: I see this is a positive (outside of the CI stuff)

Another potential con:

- Building unified docs becomes harder

**Comment by jgeewax** [comment]
The one I'm concerned about is unified docs -- that's something that could actually be a show-stopper we'd have to sort out first...

**Comment by dhermes** [comment]
Yeah this could be a lot of work. The flipside though is that the library is becoming too big and its a dis-service to developers to make them buy the whole house when the only want the kitchen (or a single lightswitch).

**Comment by jgeewax** [comment]
> its a dis-service to developers to make them buy the whole house when they only want the kitchen

This is actually tricky. The majority of people in UX studies want the whole house. The more advanced users eventually run into a problem and decide they only want the kitchen -- but only after trying out lots of things and using gcloud for a while...

So, we have a bit of an issue: do we optimize for the advanced folks? If we do, we might alienate and frustrate users, effectively reducing the number of people entering the funnel who could eventually become those advanced folks...

My thought here is still that we need to make both possible, but make the common case the simplest: `pip install gcloud` gives me the house. If I want just the kitchen, or just the light switch, this should be *possible* but not necessarily something we optimize for. Does that make sense?

**Comment by dhermes** [comment]
Yeah that'd have to be supported by **also** have a `gcloud-core` PyPI package and then using each of the `gcloud-SERVICENAME` packages.

**Comment by dhermes** [comment]
So we'd need (as of right now) the following PyPI packages:

- [`gcloud`][1]
- [`gcloud-core`][2]
- [`gcloud-bigquery`][3]
- [`gcloud-bigtable`][4]
- [`gcloud-datastore`][5]
- [`gcloud-dns`][6]
- [`gcloud-pubsub`][7]
- [`gcloud-resource-manager`][8]
- [`gcloud-search`][9]
- [`gcloud-storage`][10]

[1]: https://pypi.python.org/pypi/gcloud
[2]: https://pypi.python.org/pypi/gcloud-core
[3]: https://pypi.python.org/pypi/gcloud-bigquery
[4]: https://pypi.python.org/pypi/gcloud-bigtable
[5]: https://pypi.python.org/pypi/gcloud-datastore
[6]: https://pypi.python.org/pypi/gcloud-dns
[7]: https://pypi.python.org/pypi/gcloud-pubsub
[8]: https://pypi.python.org/pypi/gcloud-resource-manager
[9]: https://pypi.python.org/pypi/gcloud-search
[10]: https://pypi.python.org/pypi/gcloud-storage

**Comment by jgeewax** [comment]
I have no objection to this layout. Sounds to me like...

- `gcloud` depends on `gcloud-*` ("The whole house")
- `gcloud-*` (except `gcloud-core`) all depend on `gcloud-core` ("The kitchen and the foundation")

This means that if I install any of the individual services, I get the service I want, and the core library. If I install `gcloud` I just get everything.

The trouble (just a wild guess here) will be in the namespace issues... That is... 

```
$ pip install gcloud-pubsub
$ python
>>> from gcloud import pubsub  # Can we make this work?
$ pip install gcloud
$ python
>>> from gcloud import pubsub  # This should (still) work.
```

**Comment by tseaver** [comment]
Yes, that pattern will work.  We will need to:

- Move the code which is now directly in `gcloud/*.py` down into a `gcloud/core/*.py`, updating all the affected imports.
- Declare `gcloud` as a namespace package in all the distributions (in their calls to `setup()` in `setup.py`),
-  Make `gcloud/__init__.py` contain only the following::

```python
__import__('pkg_resources').declare_namespace(__name__)
```

- If we don't split the repository, then we will need to update `setup.py` to call `setup()` once for `gcloud-core`, once for each API, and once for the omnibus metapackage.

**Comment by tbetbetbe** [comment]
:+1: modularization

FYI googleapis folks: @anthm, @vsubramani@, @rok987
