### ISSUE TITLE
How should we represent 'geoValue' field values in Search?

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#1161]
The [Search docs for `geoValue`](https://cloud.google.com/search/reference/rest/google/cloudsearch/v1/FieldValue#fields.oneof_value.google.cloudsearch.v1.FieldValue.geo_value) don't specify acceptable formats:  they link to a Wiki page of what is basically all known ways humans have ever spelled latitude and longitude.

Strawman: we expect a tuple of two floats, where positive/negative represent degrees North / South of the equator (for latitude) and  East / West of Greenwich (for longitude).  Or else we take any string, require the user to pass in a `field_type` argument to use `geoValue`, and just let the server barf if it doesn't like the string.

**Comment by dhermes** [comment]
We can just use our own type? And make simple assumption initially for `OurType.from_string()` and then gradually build up behavior as needed. `OurType.to_string()` would just do the "obvious" thing.

**Comment by jgeewax** [comment]
Might be worthwhile to explore using something similar to what NDB/DB use for geo-points?

**Comment by dhermes** [comment]
@tseaver When will this be resolved? FWIW `ndb` / `db` just use a nested entity with `x` and `y` set for geo-points. In `v1beta3` a [native][1] protobuf [message type][2] is used.

[1]: https://github.com/google/googleapis/blob/12dd2eafc6ba6d011c4079cbfb246b60f9fdc28d/google/datastore/v1beta3/entity.proto#L152
[2]: https://github.com/google/googleapis/blob/12dd2eafc6ba6d011c4079cbfb246b60f9fdc28d/google/type/latlng.proto#L30-L36

**Comment by tseaver** [comment]
There are really two issues here:

- The API docs don't specify the acceptable formats for `geoValue` (see #1163).

- Do we need to be able to *detect* when users have passed us a `geoValue` without an explicit flag?  If so, we have to define what they are to pass.

**Comment by dhermes** [comment]
Since `GeoPoint` is no officially supported in datastore `v1beta3` we could just put our own `GeoPoint` class in core and then do the conversion for users.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
