### ISSUE TITLE
Saving datetime objects to Datastore - no documentation?

### ISSUE THREAD

**Issue by thesandlord** [GoogleCloudPlatform/google-cloud-python#1200]
Can the documentation be updated to show the right way to save timestamps to datastore? It took some trial and error to find the right way to do it.

Or is this just something obvious that I missed?

Example:

``` python
import time
import datetime
client = datastore.Client()

entity = datastore.Entity( key = client.key("Foo") )
entity["time"] = time.gmtime()
client.put( entity )
#does not work

entity = datastore.Entity( key = client.key("Foo") )
entity["time"] = datetime.datetime.now().date()
client.put( entity )
#does not work

entity = datastore.Entity( key = client.key("Foo") )
entity["time"] = datetime.datetime.now()
client.put( entity )
#works
```

**Comment by tseaver** [comment]
Thanks for reporting this issue!  What you've found is that we only accept actual `datetime.datetime` instances.  The first example fails because `time.gmtime()` returns a 'time.struct_time` instance;  the second example returns a `datetime.date`.

The [entity docs](https://googlecloudplatform.github.io/gcloud-python/stable/datastore-entities.html) should describe the types of fields we support, and the constraints on them.

**Comment by igama** [comment]
I'm also looking in to this. For example, 

record_entity['last_updated'] = datetime.datetime.fromtimestamp(unix_timestamp).strftime('%Y-%m-%d %H:%M:%S')

Via console.developers.google.com the property appears as string.

**Comment by thesandlord** [comment]
@tseaver yup it would be awesome if the docs / examples explained what types were accepted (string, bytes, int, float, datetime, etc). 

@igama The issue is you are converting to a string with the strftime method call. If you remove that part it should save as a timestamp.

**Comment by igama** [comment]
@thesandlord thanks, think I miss read the documentation somewhere.

**Comment by patitonav** [comment]
I found another related issue:

When i try:
`entity = datastore.Entity( key = client.key("Foo") )
entity["time"] = datetime.datetime.now()
client.put( entity )`
Works fine, but affter when i look in the datastore dashboard i see 3 hours difference.
Any idea?

**Comment by dhermes** [comment]
@patitonav You should use `datetime.datetime.utcnow()`

The [underlying value][1] is stored as a [`Timestamp`][2], which

> Represents seconds of UTC time since Unix epoch

When our code receives a "naive" timestamp (i.e. one without a timezone) it [assumes][4] the timestamp is UTC ([via][3]).

[1]: https://github.com/googleapis/googleapis/blob/5c6df0cd18c6a429eab739fb711c27f6e1393366/google/datastore/v1/entity.proto#L138-L141
[2]: https://github.com/google/protobuf/blob/b28617b813b4ba4845164a1f5190f762f5b91832/src/google/protobuf/timestamp.proto#L121-L133
[3]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/5b6eb55e016422b36dfe7d6bbcf765dff18389a4/datastore/google/cloud/datastore/helpers.py#L303
[4]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/5b6eb55e016422b36dfe7d6bbcf765dff18389a4/core/google/cloud/_helpers.py#L219-L220

**Comment by patitonav** [comment]
Yes. You were right thanks

**Comment by lukesneeringer** [comment]
This seems resolved.
