### ISSUE TITLE
Add system tests for Storage ACLs

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#1221]
@thobrla Do you have any suggestions for which sorts of things to test?

**Comment by thobrla** [comment]
Unit tests on your basic functions.  Integration tests (using a user-provided test project) to make sure those functions work on real objects.

**Comment by dhermes** [comment]
Ha thanks for the insights :grinning: 

I meant what kind of integration tests would you make against the ACL API? Just being exhaustive against the 18 ACL API methods may not be sufficient.

I figured you'd have some insight into what is tricky about those methods.

**Comment by thobrla** [comment]
Sorry, the question was somewhat vague.

Probably the biggest issue you run into with integration tests is finding valid actors to assign the ACLs to.  You really need the actor running the test to retain access, but if you want to test ACL semantics, you need to be able to act as a second actor who may lose/gain access as part of the test.  If the user provides their own test project, statically defined actors likely do not have access to that project, etc.

**Comment by dhermes** [comment]
My bad, I figured the title + the text would be sufficient.

We use a dedicated Cloud Console project for our system tests and use only one service account. In theory, we could accomplish the two actor behavior by adding a second service account.

Would we need it to be attached to a different project or could it be from the same project? (Seems it would be possible to just make an object private to a single service account and test this kind of access.)

**Comment by thobrla** [comment]
As long as all contributors have access to the dedicated project, this should work.

**Comment by dhermes** [comment]
Good to know. Thanks.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
