### ISSUE TITLE
Move remaining 'streaming' exceptions to 'gcloud.exceptions'

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#1234]
Once the cleanups for #1227 are merged via PR #1232, some exceptions remain:  they are tangled up with the exception-handling rewrite for #1223.  If any remain after closing #1223, move them "up" to `gcloud.exceptions`.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
