### ISSUE TITLE
BigQuery Table.create() doesn't update the local data

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#1258]
The code [does the right thing](https://github.com/GoogleCloudPlatform/gcloud-python/blob/13f8693d6bd135ec4a9e6289ce46f2e89bc185fc/gcloud/bigquery/table.py#L434) but the response from the server does not contain the necessary information.

The [docs](https://cloud.google.com/bigquery/docs/reference/v2/tables/insert) don't mention anything about this. I expect this comes from some `projection` default as with the GCS API but don't see anything in the docs.

@jgeewax Who can we ask about BigQuery API responses? (Maybe @fhoffa can say.)

**Comment by tseaver** [comment]
The docs for `tables.insert` say specifically:

> If successful, this method returns a Tables resource in the response body.

**Comment by dhermes** [comment]
It does return a resource, just an incomplete one.

**Comment by tseaver** [comment]
FTR, the ["Try It" for `tables/insert`](https://cloud.google.com/bigquery/docs/reference/v2/tables/insert#try-it) does allow for specifying fields, but the fields entered there are ignored.

**Comment by dhermes** [comment]
Yeah `fields` is always there in the Google APIs Explorer

**Comment by tseaver** [comment]
@fhoffa Reviewing open BQ issues:  can you add any clarification?  Or loop in a better contact?

**Comment by tseaver** [comment]
@dhermes Can you recall which fields you were expecting to be set on the `Table` instance but which were missing?  As of today, it appears that `table._properties` is identical after `table.create()` and `table.reload()`.

**Comment by dhermes** [comment]
I cannot, past the 1 year mark :grinning:

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
