### ISSUE TITLE
[Documentation Issue] Datastore client docs don't indicate what dataset ID is

### ISSUE THREAD

**Issue by raggi** [GoogleCloudPlatform/google-cloud-python#1416]
Page Name: datastore-client
Release: 0.8.0

User could not identify what `dataset_id` was supposed to be. The docs for the argument to `Client` are not useful to end users. They need to be pointed to docs like these: https://cloud.google.com/datastore/docs/activate#accessing_an_existing_app_engine_datastore_from_another_platform

**Comment by dhermes** [comment]
@raggi I take it you're filing this on behalf of another user? The [doc][1] on a client isn't particularly useful, thanks for pointing it out.

I'm trying to understand a bit more. You're saying the user didn't know what the Google Cloud Datastore API was, but they were reading our library docs to try to learn that while they learn they library?

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/896044579b5dfaddb75e8c7cbf72b614b0d04c5e/gcloud/datastore/client.py#L159-L177

**Comment by raggi** [comment]
See https://botbot.me/freenode/appengine/2016-01-23/?tz=America/Los_Angeles

They wanted to run a quick one-off standalone process to query some data from their appengine datastore. They felt that deploying a task or an app was too heavy. Initially they were trying to use the appengine sandbox libs, but of course those won't work out. I pointed them to gcloud and they begun reading the docs. The docs sample code all contains setup like so `datastore.Client()` which unfortunately, while it handles most configuration by convention using gcloud auth, they still needed to provide a dataset id. They simply got an opaque error from their sample derived code that said `EnvironmentError: Dataset ID could not be inferred. when I try to use datastore.Query()`

They found the docs for the client initializer, and saw dataset_id there, but did not know what it was supposed to be set to. The pydocs were not helpful in this regard.

**Comment by dhermes** [comment]
Thanks for the feedback! I totally agree it can be better.

**Comment by raggi** [comment]
Thanks Danny :)

**Comment by lukesneeringer** [comment]
@dhermes I do not know the ins and outs of this -- is this something you could document in 15 minutes? If so, could you do it and send a PR? If not, let's bankruptcy this one.

**Comment by lukesneeringer** [comment]
Actually going to assume that a bankruptcy is correct. Reopen if it is trivial (with a PR).

**Comment by dhermes** [comment]
@lukesneeringer I think closing this is fine. I'm not really sure how I'd document this, though I think users should come to the library with a basic understanding of what the API does
