### ISSUE TITLE
API unmapped:  storage.buckets.update

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#1430]
Noted in #1420: https://github.com/GoogleCloudPlatform/gcloud-python/pull/1420/files#diff-50dad309c06e8edd83f86b8e40b32a85R287

**Comment by dhermes** [comment]
@tseaver The point of the comment is that we don't need to implement it since `patch` exists.

**Comment by tseaver** [comment]
The `storageClass` property can apparently be set via `update` but not `patch`, but we expose a custom API which does that now via a rewrite.
