### ISSUE TITLE
Document / automate(?) building generated files from protobuf specs

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#1482]
See discussion in #1476.  It would be good to have a clean way to refresh protobufs from their upstream sources and rebuild generated files, without relying on lots of hand-rolled environment setup.

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle What is the easiest way to get `grpc_python_plugin` installed?

**Comment by nathanielmanistaatgoogle** [comment]
@dhermes at the moment it's still to build and install all of gRPC from source but @soltanmm is soon going to be working on bundling it as its own Python package (or bundling it into the one Python package we already have).

**Comment by dhermes** [comment]
:+1: We wouldn't really care if #1384 became a thing.
