### ISSUE TITLE
Remove pylint disable once we can put grpcio in setup.py

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#1526]
pylint was not happy about our imports in #1525

```
E:211, 8: No name 'interfaces' in module 'grpc.beta' (no-name-in-module)
E:212, 8: No name 'face' in module 'grpc.framework.interfaces.face' (no-name-in-module)
```

**Comment by tseaver** [comment]
This is actually a defect in pylint:  it tries to sniff at imports without letting the actual Python import machinery run, and whiffs.

We could add `grpc` to the `ignore-modules` list (as I did with `six` and `google.protobuf` today).

**Comment by dhermes** [comment]
I'd be fine with `ignore-modules`, but I'd want to read a bit more about it.

**Comment by dhermes** [comment]
No longer relevant. The referenced pylint disable was `no-name-in-module`, but now it's globally disabled:

```
$ git log -1 --pretty=%H
e927026374b5147268467f47d16157d7fbcf7bf9
$ git grep -n 'no-name-in-module'
scripts/pylintrc_default:91:# - no-name-in-module: Error gives a lot of false positives for names which
scripts/pylintrc_default:106:    no-name-in-module,
```
