### ISSUE TITLE
Update iterator to take a method and **kwargs

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#1554]
`gcloud.iterator.Iterator` is a base class, relying on a `path` for the API method.  I think it would be clearer if it wrapped around a method of a client (or other domain object), where that method takes `page_token`, `page_size`, etc., along with other named arguments in `**kw`.  We could then ditch all the derived classes, and just use the one, common implementation.  E.g.:

``` python
from gcloud.iterator import Iterator
from gcloud.pubsub import Client

client = Client()
topics = list(Iterator(client.list_topics))
subs = list(Iterator(client.list_subscriptions, topic_name='my-topic'))
```

**Comment by dhermes** [comment]
SGTM in spirit. `Iterator` was something we inherited, so it never really had an encompassing design discussion.

Also :+1: to making it no longer public.

**Comment by tseaver** [comment]
It needs to be public:  we expect client code to instantiate the `Iterator` class directly.  We would likely be removing the various subclasses, however.

**Comment by dhermes** [comment]
Ahh I didn't realize we'd use the class directly. Works for me.

**Comment by rimey** [comment]
There are really two points here:

1. Client code could request "infiniscrolling" by wrapping a paging-aware `list_*` bound method in a `MethodIterator`. This proposal and others are being discussed in #895.
2. Having to subclass `Iterator` is burdensome and unnecessary.

The second point is worthy of attention independently of the first. For example, the current `list_projects` method could be implemented more concisely in terms of `MethodIterator`.

For infiniscrolling, a simple generator would do the job as well as a class:

    def chain_pages(function, **kwargs):
        token = None
        while True:
            items, token = function(page_token=token, **kwargs)
            for item in items:
                yield item
            if token is None:
                break

**Comment by dhermes** [comment]
FWIW: We've got a pending issue (#1467) which points out that a bit more logic is needed when `max_results` is used.

**Comment by tseaver** [comment]
Obsoleted by #2531 and subsequent PRs.
