### ISSUE TITLE
Framework out how '_ClientProjectMixin' checks environment vars

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#1647]
See: https://github.com/GoogleCloudPlatform/gcloud-python/pull/1638#discussion_r56734847

Rather than requiring subclasses to override `_determine_default`, allow them to spell an ordered list of environment vars to be checked for the default project.

**Comment by jonparrott** [comment]
This is no longer relevant, as `google-auth` now handles project detection.
