### ISSUE TITLE
Should we ask the PyKube author if they want to merge into gcloud?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-python#1695]
See https://github.com/eldarion-gondor/pykube

Maybe we should ask @eldarion-gondor if they'd be interested in merging into gcloud-python ? It's not really a _perfect_ fit, because k8s is its own open-source project... but maybe there's something worth discussing?

**Comment by dhermes** [comment]
I don't know much about Kubernetes so don't know that I can offer much insight here. Asking them to merge in before any other discussion seems a bit quick.
