### ISSUE TITLE
PubSub Topic.subscribe doesn't exist?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-python#1819]
Page Name: pubsub-topic
Release: 0.14.0

Seems weird that we don't have this. I'd expect it to be...

``` python
from gcloud import pubsub
client = pubsub.Client()
topic = client.topic('my-new-topic')
topic.subscribe()
```

**Comment by tseaver** [comment]
The pattern is:

```python
subscription = topic.subscription('my-subscription')
subscription.create()   # API request
```

then:

```python
subscription.pull()  # API request
```

**Comment by jgeewax** [comment]
Yep. Why not `topic.subscribe()` ?

**Comment by tseaver** [comment]
It is a factory, so we use the noun form.  We do this consistently throughout, e.g. `Client.topic`, `Bucket.blob`, `logging.client.Client.sink`, etc.

**Comment by jgeewax** [comment]
It seems like when there's a verb that's useful on an object like this (ie, you want to subscribe to a topic), we expose a verb to do ti (ie, table.fetch_data in bigquery). 

Can we show a clear example why topic.subscribe shouldn't exist?

**Comment by lukesneeringer** [comment]
The Pub/Sub team and I are working on a significant rehash to this API, and among other things, I proposed a verb form for `topic.subscribe()`.
