### ISSUE TITLE
[Documentation Issue] Public properties are not listed in documentation

### ISSUE THREAD

**Issue by ngelinas** [GoogleCloudPlatform/google-cloud-python#1835]
Page Name: pubsub-subscription
Release: 0.14.0

Though the `name`, `topic`, `ack_deadline` and `push_endpoint` properties are public properties of the `subscription` object, this is not shown anywhere in the documentation. It is very **_Pythonic**_ to expose constructor properties as public properties but notating as such in the documentation would be helpful.

The same can be said for `topic` objects.

**Comment by dhermes** [comment]
@tseaver What's the cause here? Are these properties just data attributes, or do they have `@property`? Also, if they are just data attributes, does Sphinx have an `Attributes` section we could use in the `class` doc?

**Comment by tseaver** [comment]
Defined via `@property`:  the docstrings for the resulting descriptors are copied from their getters.

**Comment by tseaver** [comment]
Oops, I spoke in haste/error:  `name`, `topic`, `ack_deadline`, and `push_endpoint` are not properties.  To fix this, we would need to do one of two things:

- Make them properties, backed by private attributes.
- Give them class-level default values with their own docstrings.

**Comment by dhermes** [comment]
Sphinx provides a directive for instance attributes as well: http://stackoverflow.com/a/8659919/1068170

**Comment by tseaver** [comment]
There is also [`auto-attribute` syntax](http://www.sphinx-doc.org/en/stable/ext/autodoc.html#directive-autoattribute), which feels nicer than embedding it in the class' docstring.

**Comment by dhermes** [comment]
Wow I didn't realize we could even provide instance attribute docstrings in `__init__`!

**Comment by ensonic** [comment]
Friendly ping.
```python
dir(topic)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_client', '_require_client', '_timestamp_message', 'batch', 'check_iam_permissions', 'create', 'delete', 'exists', 'from_api_repr', 'full_name', 'get_iam_policy', 'list_subscriptions', 'name', 'project', 'publish', 'set_iam_policy', 'subscription', 'timestamp_messages']
```
but still not covered in https://googlecloudplatform.github.io/google-cloud-python/stable/pubsub-topic.html

**Comment by lukesneeringer** [comment]
We are in the process of working on a pretty significant change to this API, so for now I would prefer not shore up docs that we are about to need to change anyway.

**Comment by dhermes** [comment]
@lukesneeringer We should probably re-open a "sub-issue" here, namely the idea that class **attributes** should be documented (especially if they aren't `@property`-s or constructor arguments)
