### ISSUE TITLE
CORS documentation missing setter

### ISSUE THREAD

**Issue by pdknsk** [GoogleCloudPlatform/google-cloud-python#1838]
https://googlecloudplatform.github.io/gcloud-python/stable/storage-buckets.html#gcloud.storage.bucket.Bucket.cors

> Retrieve CORS policies configured for this bucket.

It doesn't mention that it can also be set.

**Comment by pdknsk** [comment]
(I think this also applies to a few other properties.)

**Comment by daspecster** [comment]
@tseaver https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/storage/bucket.py#L509 is it just not showing up in the docs because of the decorator?

**Comment by tseaver** [comment]
@daspecster Docstrings for `@property` objects are derived from their getters:

```python
>>> class Foo(object):
...     @property
...     def bar(self):
...         """bar getter"""
...     @bar.setter
...     def bar(self, value):
...         """bar setter"""
...     @bar.deleter
...     def bar(self):
...         """bar deleter"""
... 
>>> Foo.bar
<property object at 0x7f8fe9a856d8>
>>> Foo.bar.__doc__
'bar getter'
```

**Comment by daspecster** [comment]
Cool, what if we just combine the docs in some way that makes sense in the getter?

```python
 @property
    def cors(self):
        """Get/Set CORS policies configured for this bucket.
        See: http://www.w3.org/TR/cors/ and
             https://cloud.google.com/storage/docs/json_api/v1/buckets

        :setter: Set CORS policies for this bucket.
        :getter: Gets the CORS policies for this bucket.

        """
        return [copy.deepcopy(policy)
                for policy in self._properties.get('cors', ())]

    @cors.setter
    def cors(self, entries):
        """Set CORS policies configured for this bucket.
        See: http://www.w3.org/TR/cors/ and
             https://cloud.google.com/storage/docs/json_api/v1/buckets
        :type entries: list of dictionaries
        :param entries: A sequence of mappings describing each CORS policy.
        """
        self._patch_property('cors', entries)
```

**Comment by mlissner** [comment]
I filed #2610 where the same issue applies to the setter for `lifecycle_rules`. Seems like a very simple solution here is what @daspecster proposed. It's not perfect, but if it had been done back in June when it was proposed, I would have been a happier customer.

**Comment by daspecster** [comment]
@mlissner, sorry you lost cycles on this.

I made https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2623 to hopefully resolve this for future users.

Thanks for reporting as well.
