### ISSUE TITLE
on error, error occurs in the error processing

### ISSUE THREAD

**Issue by mdmiller53** [GoogleCloudPlatform/google-cloud-python#1840]
i am using the gcloud package to download files from google cloud storage, python 2.7 from a google compute engine.  i am launching multiple processes using the multiprocessing package.  there is an occasional error, but the actual error message is obscured because an error occurs getting that message.  here is the stack trace:

```
Traceback (most recent call last):
  File "mirna_isoform_matrix/download_isoform.py", line 39, in download_file
    bucket = client.get_bucket(bucket_name)
  File "/usr/local/lib/python2.7/dist-packages/gcloud/storage/client.py", line 167, in get_bucket
    bucket.reload(client=self)
  File "/usr/local/lib/python2.7/dist-packages/gcloud/storage/_helpers.py", line 77, in reload
    _target_object=self)
  File "/usr/local/lib/python2.7/dist-packages/gcloud/connection.py", line 343, in api_request
    error_info=method + ' ' + url)
InternalServerError: 500 Internal Error (GET https://www.googleapis.com/storage/v1/b/2016-05-03-isb-cgc-open?projection=noAcl)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/process.py", line 208, in _queue_management_worker
    result_item = result_queue.get(block=True)
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
TypeError: ('__init__() takes at least 2 arguments (1 given)', <class 'gcloud.exceptions.InternalServerError'>, ())
```

when i trace down into gcloud/connection.py, it looks like the error occurs in this block:

```
        if not 200 <= response.status < 300:
            raise make_exception(response, content,
                                 error_info=method + ' ' + url)
```

**Comment by daspecster** [comment]
Thanks for reporting @mdmiller53!

@dhermes, @tseaver would #1214 possibly be related?

**Comment by mdmiller53** [comment]
@daspecster thanks for taking a look.  it probably isn't related to #1214, i've actually seen that error.  but that was in the context of launching multiple threads, this issue is from launching multiple processes where each process has its own http2 package instantiated.

**Comment by dhermes** [comment]
@mdmiller53 The stacktrace is a bit strange to me. It seems like it succeeded in the thread, but the parent had an issue.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
