### ISSUE TITLE
Add support for the App Engine Admin API

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-python#1852]
We have an Admin API (service management) for App Engine here:
https://cloud.google.com/appengine/docs/admin-api/reference/rest/

It's a pretty basic CRUD / REST style API, but it would be great to have wrappers that make it easier to use.

**Comment by dhermes** [comment]
@jgeewax WDYT?

**Comment by jgeewax** [comment]
I'm all for doing this, but it's definitely not "top priority"...
