### ISSUE TITLE
Add Error Reporting Library

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/google-cloud-python#1921]
This issue is to separately track some of the scope creep from #1881. 

We need:
- A client to talk to the Error Reporting API. Currently this API does not seem public yet, so until then, we can create Error Reports by talking to the Logging API in a [specific structured format.](https://cloud.google.com/error-reporting/docs/formatting-error-messages) Once Error Reporting API exists we migrate the implementation from Logging API to Error Reporting API ( so it has its own quota, auth, etc).
- A logging handler that, for messages of severity error, gets the stacktrace/function context and reports to Error Reporting API
- A hook that lets you setup a global Python exception handler to catch exceptions and properly report the context.
- A similar hook for Django/Flask apps that will report the exception context and also include HTTP context.

**Comment by waprin** [comment]
For the first bullet point, you want something like:

gcloud.error_handler.error('message'), and then it uses the traceback module to actually include file/line number/stack trace in the message

**Comment by daspecster** [comment]
@waprin I think this is 90% done right? Just the Django piece left?

We could close this and just make the Django issue?

**Comment by waprin** [comment]
Yep, that and some maintenance (need to keep GAPIC up to date). But yeah I think we can close this and replace with Django error reporting (which I think is pretty low-priority anyway). Will make new issue.

**Comment by daspecster** [comment]
Thanks @waprin!
