### ISSUE TITLE
Provide a way to retrieve gcloud config programmatically

### ISSUE THREAD

**Issue by nikhilk** [GoogleCloudPlatform/google-cloud-python#1934]
especially things like default project id.

**Comment by daspecster** [comment]
@nikhilk, You can get the current client project ID via `client.project`

Was there something else you're trying to access?

**Comment by nikhilk** [comment]
I must be missing something obvious. I tried the following two:

pip install gcloud

import gcloud
gcloud.client.project

-- as well as --

import gcloud.client
gcloud.client.project

-- then tried to instantiate Client --
c = gcloud.client.Client()
but get an error about no app default credentials being available.

Can you help with the exact code I need to use?

**Comment by dhermes** [comment]
This project is distinct from the `gcloud` SDK. You'd want to ask that team for such an API. @jgeewax @jonparrott who would be the person to reach out to for that?

**Comment by nikhilk** [comment]
The desire was to use a programmatic API rather than calling gcloud as a subprocess (which is what we do right now). Yes, ideally this would be functionality gcloud would expose as a library, but gcloud-python seemed like the next logical thing.

So from the example above, it seems if you create a client for a particular service, you can get the project off of it. I guess I would be expected there be a way to get the project without needing to first create a client instance for a specific service, but I suppose that is a possible workaround that could work.

**Comment by tseaver** [comment]
`gcloud._helpers._determine_default_project` is the function the various `Client` classes use to sniff a project (the `datastore` client tweaks it a bit to deal with the emulator).  It isn't public, but we could look at making it so.  Note that the logic there is not related (directly) to the `gcloud` CLI's notion of determining the project.

**Comment by daspecster** [comment]
@nikhilk do you think that @tseaver's answer will work for you?

**Comment by jgeewax** [comment]
I'm not sure this has been settled... It seems like we have a way to do it that is private and not documented, and we should look at potentially exposing this... Re-opening for discussion, feel free to re-close if there was an off-line conversation that was omitted here.

**Comment by dhermes** [comment]
@jgeewax That is outside our purview. If people want to use what we do it is all in public surfaces provided by https://github.com/GoogleCloudPlatform/google-auth-library-python/

**Comment by timonbimon** [comment]
hey do i understand correctly that there is no way currently to access the currently active account (that i could get with 'gcloud auth list' on the command line) programmatically via python?

**Comment by tseaver** [comment]
@timonbimon Unlike the `gcloud` CLI, the `google-cloud-*` libraries do not keep any persistent store of credentials:  we use the service account credentials file explicitly set in the environment (`GOOGLE_APPLICATION_CREDENTIALS`), or passed explicitly to the client's `from_service_account_json` method.

If you have a client instance, you can query its `project` attribute to get the named project associated with the client's credentials.  Two of the API clients (`bigquery` and `storage`) expose a `get_service_account_email` method which returns the e-mail address associated with the client.

While we don't currently expose the `_credentials` attribute of client instances as a public API for any client except spanner's:  you could use the private attribute to get information using the interface provided by [`google.auth.credentials.Signing.signer_email`](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/a10b15e34447a35cedd0f73654b13404999141b5/google/auth/credentials.py#L311).
