### ISSUE TITLE
Cloud storage rewrite with GCloud?

### ISSUE THREAD

**Issue by hohaichi** [GoogleCloudPlatform/google-cloud-python#1960]
Does GCloud support Google Cloud Storage rewrite?

**Comment by daspecster** [comment]
I don't believe we do at this time.

**Comment by hohaichi** [comment]
Do you have any plan to add rewrite?  It is hard for the user to rotate their encryption key without rewrite.

**Comment by daspecster** [comment]
That's a great use case!

@tseaver & @dhermes WDYT? I can start this today or tomorrow if there are not blockers.

**Comment by jonparrott** [comment]
@tseaver @dhermes @jjg this is also a blocking issue for us to be able to re-write storage usage samples using this library.

**Comment by tseaver** [comment]
Based on the [`rewrite` API docs](https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite), it seems like this should be a method on `Bucket`, parallel to `Bucket.copy_blob`.  Something like:

```python

    def rewrite_blob(self, blob, destination_bucket, new_name, client=None):
        """Rewrite the given blob to the given bucket, with a new name.

        :type blob: :class:`gcloud.storage.blob.Blob`
        :param blob: The blob to be copied.

        :type destination_bucket: :class:`gcloud.storage.bucket.Bucket`
        :param destination_bucket: The bucket into which the blob should be
                                   copied.

        :type new_name: string
        :param new_name: (optional) the new name for the copied file.

        :type client: :class:`gcloud.storage.client.Client` or ``NoneType``
        :param client: Optional. The client to use.  If not passed, falls back
                       to the ``client`` stored on the current bucket.

        :rtype: bytes
        :returns: The new Blob.
        """
        client = self._require_client(client)
        if new_name is None:
            new_name = blob.name
        new_blob = Blob(bucket=destination_bucket, name=new_name)
        api_path = blob.path + '/rewriteTo' + new_blob.path
        resource = dict(blob._properties)
        result = client.connection.api_request(
            method='POST', path=api_path, data=resource,
            _target_object=new_blob)
        token = result.get('rewriteToken')
        while token not in (None, ''):
            query_params = {'rewriteToken': token}
            result = client.connection.api_request(
                method='POST', path=api_path, query_params=query_params,
                _target_object=new_blob)
            token = result.get('rewriteToken')
        new_blob._set_properties(result['resource'])
        return new_blob
```

**Comment by jonparrott** [comment]
That would be fine, alternatively `blob.rewrite_to(destination_name, source_encryption_key=..., encryption_key=...)` would be acceptable as well.

*N.B.* this method *must* take two encryption key parameters, one for the source and one for the destination. This is the primary use case of the rewrite method.

**Comment by tseaver** [comment]
@jonparrott Where in the [`rewrite` request](https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite#request) are the keys passed?  I see fields in the `Object` resource which are *metadata* about the encryption, but not the key itself.

**Comment by jonparrott** [comment]
In the headers, hilariously enough.

See the currently sample [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/storage/api/customer_supplied_keys.py#L105).

**Comment by tseaver** [comment]
@jonparrott Why are those values not part of the payload? Worse, why is that not documented?

**Comment by jonparrott** [comment]
@tseaver I have no idea - this API predates me joining and I'm not part of the API review team. My hunch is that it was a way to get around releasing a new API version. Maybe @Capstan can provide some background.

**Comment by tseaver** [comment]
/me grumbles This is exactly the kind of thing that is *supposed* to make you release a new API version.

**Comment by jonparrott** [comment]
@tseaver don't shoot the messenger. I thought it was whack when I had to write the samples for it using google-api-python-client, because it's awkward to add headers using that library.

**Comment by tseaver** [comment]
@jonparrott I'm grumbling about that (hypothetical) motive, which predates you. New API release or not, the API docs should still be updated to define the (added?) behaviors:  how did you learn about those headers in the first place?

**Comment by jonparrott** [comment]
https://cloud.google.com/storage/docs/encryption

**Comment by Capstan** [comment]
tseaver@ I've filed an internal bug about Rewrite docs not saying enough about how to use it with customer-supplied encryption keys. I'm not entirely sure why it couldn't have been added to the post body, but I do know that ensuring that no key is ever persisted anywhere is of paramount importance and may have guided that decision.

**Comment by jonparrott** [comment]
Bump, any update on this?

**Comment by daspecster** [comment]
It looks like it was last updated August 19th,
And now it talks about the headers. I'm not sure if that was there before or if that's what we were looking for?

https://cloud.google.com/storage/docs/encryption#request

**Comment by hohaichi** [comment]
Re: object resource having encryption key metadata but not key materials:  It is a little bit confusing in the first glance, as object resources can appear in both requests and responses.  But if you look more closely, the table denotes which fields are "writable".  Only those fields can be updated.  Key metadata cannot be updated, they are only helpful in responses.

Re: why the keys are passed in as headers rather than the post body:  Actually adding the keys to the request body is not as straightforward as it seems.  In our current API, a request body either contains object data or object metadata.  And key materials are neither.

**Comment by jonparrott** [comment]
@tseaver @dhermes can I get a release of the storage client so I can update the sample?

**Comment by tseaver** [comment]
@dhermes I'm not quite sure how you've made sub-project releases after the `umbrella-0.20.0` tag.  I just ran `$ git log umbrella-0.20.0..HEAD -- storage/` and got the following:

- Making max_results part of the base Iterator class. (Fixing #1467)
- Add 'Blob.compose' API wrapper method. (Closing #1982)
- Add 'Blob.rewrite' API wrapper method. (Closing #1960)
- Add new storage classes. (PR #2571)
- Your iterator work.

**Comment by dhermes** [comment]
@tseaver I think it's more robust just to use the GitHub UI (since people can merge PRs however they like now, and we haven't disabled the other two options, though we can):

https://github.com/GoogleCloudPlatform/google-cloud-python/commits/master/storage?since=2016-09-27

**Comment by tseaver** [comment]
@dhermes FWIW, I wasn't grepping for "Merged" commits:  I looked at the whole history for `/storage` since that tag.

**Comment by dhermes** [comment]
Haha DERP. I should've read closely.

**Comment by jonparrott** [comment]
Bump - I can has release?

**Comment by dhermes** [comment]
@jonparrott It's not as easy as it seems. It requires a core release as well, which has implications on all packages.

**Comment by jonparrott** [comment]
The core change being the iterator work? If so, I can wait.

**Comment by dhermes** [comment]
> The core change being the iterator work? 

Yes
