### ISSUE TITLE
Monitoring gRPC Support

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/google-cloud-python#1963]
I'm trying to better understand the roadmap of gRPC clients.

Monitoring team really wants gRPC support for their API. However rather than compiling protos and distributing separate Python packages ([like Pub/Sub did](https://cloud.google.com/pubsub/grpc-python)) I am recommending we hold off until we get gRPC support in here.

However I'm unclear 
- What works needs to be done to get the existing client working on gRPC
- Whether that work is already planned on a roadmap 
- Any other gotchas/general status with gRPC and this library 

/cc @rimey

**Comment by sharbison3** [comment]
I have not yet heard that the monitoring team "really wants gRPC support." Did I miss a memo?

**Comment by tseaver** [comment]
@waprin we'd really prefer not to be wedging any more generated code into the project:  the process of generating / maintaining it is a serious burden.  Getting the *existing* proto-generated stuff distributed as separate libraries is already a goal (see #1384).

The https://github.com/googleapis/ team has been working on automating builds of such libraries:  maybe they could help?

**Comment by waprin** [comment]
@tseaver ok I have misunderstood the goals of what's going on. My understanding was that the Google APIs team was generating libraries for the express purpose of being included in this library.

**Comment by bjwatson** [comment]
@omaray What do you think?

**Comment by waprin** [comment]
@bjwatson I think there was a small miscommunication here, because I wasn't asking to merge in generated code but how we can rebase the handwritten to duplex between HTTP or VTK once it is generated like is currently done for Logging/Pubsub. Omar is out this week and wasn't sure if/when it would get on official roadmap, he wanted to hear from @jgeewax.

**Comment by bjwatson** [comment]
@waprin Sorry, I was chiming in on an issue I only partially understood. :/

I'm happy to hear that Omar is already in the loop, and it sounds like this is definitely a question of the roadmap for gcloud.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
