### ISSUE TITLE
Tear httplib2 out of google-cloud

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#1998]
I plan to tackle this soon-ish.

This is so we can move to a better-maintained (or allow BYO) transport layer.

**Comment by jonparrott** [comment]
This should know be possible since `oauth2client` has been replaced with `google-auth`.

**Comment by dhermes** [comment]
`google.cloud.streaming` needs fixin' first (I seem to recall @jonparrott volunteering for that one, but can't confirm it because our chat history gets deleted!)

**Comment by jonparrott** [comment]
Have we a bug for `streaming`?

My chat history gets deleted to prevent me from volunteering for dumb things.

**Comment by dhermes** [comment]
I don't think so, it's part of the "ditch `httplib2` bug"

**Comment by daspecster** [comment]
@dhermes @jonparrott is [`google_auth_httplib2.py`](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/master/httplib2_transport/google_auth_httplib2.py) what should be used instead of directly using `httplib2`?

**Comment by jonparrott** [comment]
That's already the case. We should stop using httplib2 completely and
switch to urllib3.

**Comment by dhermes** [comment]
Here is what remains:

- Stop using `google.cloud.streaming` in BigQuery. I've already [done this][1] in the source, but don't have the bandwidth to update the unit/system tests
- Delete `google.cloud.streaming` from `google-cloud-core`
- Change the [default `http` object][2] to a `requests` object
- Deal with the fall out of the previous change (i.e. broken tests and broken code paths)
- Do a `git grep` for `httplib2` and get rid of **all** of it

[1]: https://github.com/dhermes/google-cloud-python/tree/bigquery-remove-streaming
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/214aba604fbcaa9e4936fa1798efde050389992a/core/google/cloud/client.py#L157-L160

**Comment by bmabey** [comment]
@dhermes Do you have a timeline for when this will be completed?

**Comment by dhermes** [comment]
@bmabey Much closer right now (because #3555 is done, w00t!) then we were 24 days ago.

**Comment by jonparrott** [comment]
I am bumping this to a p1 and assigning to myself, it's critical that we remove usage of httplib2 before we GA any more libraries.

**Comment by lukesneeringer** [comment]
Copy that. Thank you for the effort.

**Comment by lukesneeringer** [comment]
Note: Translate is NOT pushed to PyPI yet; do I need to hold it?

**Comment by jonparrott** [comment]
@lukesneeringer translate is probably okay. All of the other current GA libraries accept an http parameter that has to be an httplib2 instance, so I'm not sure how we want to deal with that yet.

**Comment by dhermes** [comment]
Ahhhhhhh! :raised_hands: :confetti_ball: :1st_place_medal: :tada: :taco:

**Comment by tseaver** [comment]
GOOOOOOOOOOOOOOOOOOOOOAL!!!

**Comment by daspecster** [comment]
Congrats guys!
