### ISSUE TITLE
Can't `pip install gcloud` with Python 3.4 and pip 6.x

### ISSUE THREAD

**Issue by fdr** [GoogleCloudPlatform/google-cloud-python#2013]
I was porting WAL-E to Python 3.4 and things were working well (perhaps because of newer versions of pip on my Fedora Linux installation), however, an older version of pip seen in the wild on servers (the 6.x series) doesn't seem to work. Is there an adjustment that would allow even 6.x era pip to function?

A transcript follows:

```
$ sudo pip-3.4 install gcloud
You are using pip version 6.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting gcloud
  Using cached gcloud-0.17.0.tar.gz
Collecting httplib2>=0.9.1 (from gcloud)
  Using cached httplib2-0.9.2.zip
Collecting googleapis-common-protos (from gcloud)
  Using cached googleapis-common-protos-1.2.0.tar.gz
Collecting oauth2client>=2.0.1 (from gcloud)
  Using cached oauth2client-2.2.0.tar.gz
Collecting protobuf!=3.0.0.b2.post1,>=3.0.0b2 (from gcloud)
  Could not find a version that satisfies the requirement protobuf!=3.0.0.b2.post1,>=3.0.0b2 (from gcloud) (from versions: 2.0.0b0, 2.0.3, 2.3.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 3.0.0a2, 3.0.0a3, 3.0.0b1, 3.0.0b1.post1, 3.0.0b1.post2, 3.0.0b2, 3.0.0b2.post1, 3.0.0b2.post2, 3.0.0b3, 3.0.0b4)
  No matching distribution found for protobuf!=3.0.0.b2.post1,>=3.0.0b2 (from gcloud)
```

**Comment by waleedka** [comment]
I got this issue as well, yesterday, on Python 3.5, but today it's working. Looks like there is a new version on pip. Thank you. 

I wanted to point out, though, that the gcloud home page still states the Py2.7 is required, and specifically asks the user to verify that they have 2.7 before continuing. 
https://cloud.google.com/sdk/docs/quickstart-mac-os-x

**Comment by dhermes** [comment]
@waleedka RE: "the gcloud home page", `gcloud-python` != `gcloud`, but thanks for the heads up

**Comment by waleedka** [comment]
Thanks for the clarification. I realized that as well when I tried to install the gcloud sdk on py3 and it didn't work :(

**Comment by dhermes** [comment]
@fdr Please LMK if this is still an issue.
