### ISSUE TITLE
Helper Functions Partitioning

### ISSUE THREAD

**Issue by dwmclary** [GoogleCloudPlatform/google-cloud-python#2018]
It would be useful to have a function which, given a timestamp key, creates a partitioned version of a table.  A number of users struggle to do with with minimum cost, so having the client handle it, even though it would be a series of async jobs, would be useful.

**Comment by tseaver** [comment]
@dwmclary I'm not sure what a "partitioned version" would look like.  AFAIK, we could create a new table with `partition_type = 'DAY' and the same schema, and then copy the source table into it.  I don't know how that ties in with a specific timestamp key, though.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
