### ISSUE TITLE
Update datastore example for put then key-get operation

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/google-cloud-python#2023]
the [gcloud datastore sample](https://github.com/GoogleCloudPlatform/gcloud-python#google-cloud-datastore) does not persist/put() the entity.   It also describes a put  followed by query (better to put followed by consistent key-get operation)

suggest updating

```
from gcloud import datastore
# Create, populate and persist an entity
entity = datastore.Entity(key=datastore.Key('EntityKind'))
entity.update({
    'foo': u'bar',
    'baz': 1337,
    'qux': False,
})
# Then query for entities
query = datastore.Query(kind='EntityKind')
for result in query.fetch():
    print result
```

perhaps  something like

```
from gcloud import datastore
ds = datastore.client.Client(dataset_id='YOUR_DATASET_ID')
# Create, populate and persist an entity
entity = datastore.Entity(key=ds.key('EntityKind'))
entity.update({
    'foo': u'bar',
    'baz': 1337,
    'qux': False,
})
ds.put(entity)
# Then get by key for this entity
result = ds.get(entity.key)
print result
```

**Comment by tseaver** [comment]
@salrashid123 Thanks for the report!  It certainly is a bug that the entity does not get persisted.  Maybe the example should show both the `ds.get()` mechanism and the query.

**Comment by salrashid123** [comment]
Its bit of a minor nit though...if you insert then immediately query, its eventually consistent (i.e you may not get the entity back that you just inserted)....but a [key-get is consistent](https://cloud.google.com/datastore/docs/articles/balancing-strong-and-eventual-consistency-with-google-cloud-datastore/#h.tf76fya5nqk8)

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
