### ISSUE TITLE
Storage API too complex to extract file path

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/google-cloud-python#2034]
Datalab API examples: https://github.com/googledatalab/datalab/blob/f52335fe7bc596aa63f61230717c473caf6047de/dev/notebooks/Cloud%20Storage%20-%20Reading%20and%20Writing%20Files.ipynb

``` python
items = shared_bucket.items()
keys = map(lambda item: item.key, items)
keys
```

What it is the equivalent in gcloud-python?

``` python
items = shared_bucket.list_blobs()
keys = ['/'.join(item.id.split('/')[1:-1]) for item in items]
```

**Comment by pdknsk** [comment]
```item.name```

**Comment by VelizarVESSELINOV** [comment]
Is it documented somewhere? https://googlecloudplatform.github.io/gcloud-python/stable/storage-blobs.html

**Comment by dhermes** [comment]
@VelizarVESSELINOV it sounds like a request for classes to document their defined attributes?

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
