### ISSUE TITLE
Consider using tox-travis

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2070]
https://pypi.python.org/pypi/tox-travis

**Comment by tseaver** [comment]
:+1: It parallelizes the test environments, which is a good thing.

**Comment by dhermes** [comment]
If it uses the Travis build matrix it's both good and bad. The Travis build matrix counts each env. as a separate build so we might get throttled.

**Comment by dhermes** [comment]
> If it uses the Travis build matrix

I just confirmed it does.
