### ISSUE TITLE
[Documentation Issue] Links to previous versions are missing.

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#2073]
I mentioned this in https://github.com/GoogleCloudPlatform/gcloud-python/pull/2069.

The links to previous versions of the documentation are now missing. http://googlecloudplatform.github.io/gcloud-python/0.17.0/ versus http://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud

**Comment by dhermes** [comment]
Thanks for the report!

**Comment by daspecster** [comment]
I think this is an error in logic in my generate shell script. I'll check this out tonight.

**Comment by daspecster** [comment]
Also closed by #2267.
