### ISSUE TITLE
Pubsub system test: test_fetch_delete_subscription_w_deleted_topic does not see orphan w/o topic

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#2080]
From:  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/151011241#L822

```python
======================================================================
FAIL: test_fetch_delete_subscription_w_deleted_topic (pubsub.TestPubsub)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/system_tests/pubsub.py", line 273, in test_fetch_delete_subscription_w_deleted_topic
    self.assertTrue(orphaned.topic is None)
AssertionError: False is not true
----------------------------------------------------------------------
```

**Comment by tseaver** [comment]
Again [yesterday](https://travis-ci.org/GoogleCloudPlatform/gcloud-python#L635).

**Comment by tseaver** [comment]
Still [failing](https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/152767748#L822-L828) on one of two runs after the merge of #2086.

**Comment by tseaver** [comment]
W00t!  We have two passing post-merge builds after the merge of #2106:

- https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/153004550
- https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/153028304

**Comment by dhermes** [comment]
w00t!

**Comment by tseaver** [comment]
[Ugh](https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/155569740#L851-L877)

**Comment by tseaver** [comment]
@tmatsuo Has there been some recently-deployed change to the Pubsub API which would cause this failure to go from "flaky" to "fails routinely"?  Our current backoff ends up polling for *four minutes*, trying to get the `deleted-topic` response after deleting our "orphan" subscription's topic.

@dhermes, @daspecster If @tmatsuo doesn't know / suspect any back-end change which would explain the failures, I propose we drop this particular testcase:  we have unittests in place which cover the oddball case, and we *need* to have our build stay green.

**Comment by dhermes** [comment]
> I propose we drop this particular testcase

I'm unclear on how important this test case is, though hope we can sort out the backend's issues without having to ditch the system test (the more the merrier).

**Comment by dhermes** [comment]
@tseaver shouldn't we leave this open?

**Comment by dhermes** [comment]
@tseaver As of the [latest build][1] the error has stopped occurring, which has led to "unexpected success". To make this more hilarious, in Python 2 vs. 3, that means a different status code with `unittest`.

I've tried to repro the `FAILED (unexpected successes=1)` vs. `OK (unexpected successes=1)` but can't

```python
import unittest


class TestNothing(unittest.TestCase):

    @unittest.expectedFailure
    def test_it(self):
        self.assertTrue(False)


def main():
    suite = unittest.TestSuite()
    tests = unittest.defaultTestLoader.loadTestsFromTestCase(
        TestNothing)
    suite.addTest(tests)
    test_result = unittest.TextTestRunner(verbosity=2).run(suite)
    print('test_result.wasSuccessful():')
    print(test_result.wasSuccessful())


if __name__ == '__main__':
    main()
```

[1]: https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/157205950

**Comment by dhermes** [comment]
Same fail but not really fail again: https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/157238601

**Comment by tseaver** [comment]
I'm in favor of just dropping the test altogether (as #2215 did originally).

**Comment by tmatsuo** [comment]
Sorry for the late reply. What does the test do? Maybe I can ask a core engineer if something has changed.

**Comment by tseaver** [comment]
@tmatsuo it creates a topic, and a subscription to it, then deletes the topic.  It then tries to verify that the same subscription (when returned from `Client.list_subscriptions`) has `None` as its topic, i.e., that resource as listed contained the special `_deleted-topic_` value for its topic.

What we see is that the orphaned subscription is *not* showing that special value, even after an extremely long retry/backoff cycle (up to four minutes or so).

**Comment by tmatsuo** [comment]
Does it always fail now, or it is still flaky (flakier than before)?

**Comment by dhermes** [comment]
It failed for like 10 days straight and now has succeeded for about 5 days straight

**Comment by tmatsuo** [comment]
Thanks, asked the engineering team about it

**Comment by tseaver** [comment]
If we merge #2248, we can still have the back-end guys experiment with the test by setting the appropriate environment variable.  E.g.:

```bash
$ git clone git@github.com:GoogleCloudPlatform/google-cloud-python
$ cd google-cloud-python
$ GOOGLE_CLOUD_RUN_FLAKY_TESTS=1 tox -e system-tests
```

**Comment by dhermes** [comment]
I did some sleuthing and found out why the unexpected success causes a failure in [Python 3][1] but not [Python 2][2].

```python
def wasSuccessful(self):
    return len(self.failures) == len(self.errors) == 0
```

became

```python
def wasSuccessful(self):
    return ((len(self.failures) == len(self.errors) == 0) and
            (not hasattr(self, 'unexpectedSuccesses') or
             len(self.unexpectedSuccesses) == 0))
```

[1]: https://github.com/python/cpython/blob/3.4/Lib/unittest/result.py#L159-L166
[2]: https://github.com/python/cpython/blob/2.7/Lib/unittest/result.py#L144-L146

**Comment by dhermes** [comment]
Potential "fix"

```diff
diff --git a/system_tests/run_system_test.py b/system_tests/run_system_test.py
index 4ee50f9..4bb752c 100644
--- a/system_tests/run_system_test.py
+++ b/system_tests/run_system_test.py
@@ -70,6 +70,8 @@ def run_module_tests(module_name, ignore_requirements=False):

     # Run tests.
     test_result = unittest.TextTestRunner(verbosity=2).run(suite)
+    # NOTE: Erase the unexpected successes.
+    test_result.unexpectedSuccesses[:] = []
     # Exit if not successful.
     if not test_result.wasSuccessful():
         raise FailedSystemTestModule(module_name)
```

Though it seems like the test succeeds to frequently now we should just remove `@unittest.expectedFailure`.

**Comment by dhermes** [comment]
When running `.tox/system-tests/bin/nosetests system_tests/pubsub.py` I was confused by

```
/usr/lib/python2.7/unittest/case.py:340: RuntimeWarning: TestResult has no addExpectedFailure method, reporting as passes
  RuntimeWarning)
```

since `unittest.TestResults` [implements `addExpectedFailure`][1]. This was due to https://github.com/nose-devs/nose/issues/33, so I feel somewhat happy with the move to `py.test`, where issues won't live on unfixed for 5 years. (Thanks @jonparrott for pointing out the stagnancy of `nose`.)

[1]: https://github.com/python/cpython/blob/2.7/Lib/unittest/result.py#L134-L137

**Comment by tseaver** [comment]
PR #2248 deleted the flaky test.
