### ISSUE TITLE
Basic polling helper function for long running operations/jobs

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/google-cloud-python#2117]
Several libraries with long running operation are lacking basic helper functions for polling

Considering that implementing exponential backoff properly is a 15 line affair which clutters up code it might be good to have a util function that properly implements exponential backoff and then allow things to call it, like in `bigquery.job.Jobs`

```
def wait(self):
    utils.exponential_backoff(self.begin, self.reload, self.status)
```

**Comment by dhermes** [comment]
I've also suggested this for things like long-running operations

**Comment by tseaver** [comment]
@elibixby We have a [utility like that](https://github.com/GoogleCloudPlatform/gcloud-python/blob/a9891abdd9a8fb83194d67c01ae0980ae395fbe9/system_tests/retry.py#L142) now for system testing.  We could move it (and maybe the error-based and result-based ones) into the library itself, which might look like:


```python
from gcloud.retry import RetryInstanceState

def _job_done(job):
    return job.state.lower() == 'done'

until_done = RetryInstanceState(_job_done)

class _BaseJob(object):
    ...
    @until_done
    def wait(self):
        self.reload()
```

@dhermes We need to factor out the `google.longrunning.operations` bit, including making the name pattern and metadata lookup bits less smelly.  If we did, then we could add an `Operation.wait` method.

**Comment by dhermes** [comment]
@tseaver Good point. We could even return an `Operation` instance from async uploads for BigQuery and have the concept map across packages.

**Comment by tseaver** [comment]
@bjwatson Another grpc / GAX request:  can you release wrappers for `google.longrunning`?  We have a [hacky self-generated version](https://github.com/GoogleCloudPlatform/gcloud-python/blob/9a7da8fc007f96c5daddd26746cf86fd7dff2638/gcloud/bigtable/_generated/operations_grpc_pb2.py), but would be much better off using one "from the horse's mouth."

**Comment by tseaver** [comment]
Note that this is just the gRPC bits:  we are already using the "bare" proto-generated stuff from `googleapis_common_protos`.

**Comment by bjwatson** [comment]
@tseaver That's currently a WIP for us at the GAX level. @garrettjonesgoogle is leading this effort.

If you just need the GRPC generated code, then I think we can do that for you quickly.

**Comment by tseaver** [comment]
@bjwatson We can use the stub-based approach without GAX for now:  basically, all we need is a way to call [`GetOperation`](https://github.com/googleapis/googleapis/blob/e82b5e05fe631911acb2c987f32b64710f47d36f/google/longrunning/operations.proto#L43) for polling purposes.  Later on, it would be good if `DeleteOperation` and `CancelOperation` were possible (I don't think we have a usecase for `ListOperations`).

**Comment by bjwatson** [comment]
@tseaver I tried doing that today using an internal build server we setup to introduce more controllability into our release process (previously done on dev workstations with varying environments). Unfortunately, I hit a few issues. I'll try again tomorrow with help from @ethanbao and @geigerj.

**Comment by geigerj** [comment]
gRPC longrunning package available here: https://pypi.python.org/pypi/grpc-google-longrunning-v2/

I think the VKit team is still working out the full story for "meta-APIs" like longrunning, so I'll hold off the GAX package if you guys don't need it now.

**Comment by tseaver** [comment]
@geigerj Thanks!  I'll work on folding it in.  One thing I note is that the `0.8.1` release doesn't have the `v2` in the path:  is that intentional?

**Comment by geigerj** [comment]
@tseaver [The protos are unversioned](https://github.com/googleapis/googleapis/tree/master/google/longrunning), and the lack of version in the path is a direct consequence.

**Comment by tseaver** [comment]
@geigerj OK, WFM.

**Comment by tseaver** [comment]
Hmm, looks like the new distribution clashes with `googlapis-common-protos-1.2.0`:

```bash
$ grep "operations_pb2.py\>" .tox/py27/lib/python2.7/site-packages/*.dist-info/RECORD 
.tox/py27/lib/python2.7/site-packages/googleapis_common_protos-1.2.0.dist-info/RECORD:google/longrunning/operations_pb2.py,sha256=SOUv_2E4dyO0andxMae0Ce2LYjysFCMEvjS6HbP25o0,14161
.tox/py27/lib/python2.7/site-packages/grpc_google_longrunning_v2-0.8.1.dist-info/RECORD:google/longrunning/operations_pb2.py,sha256=na0U-_LrfCX7_G6thyTkWalgp_FFL6CguljKrPg5G98,27703
```
so "last one installed" wins. :(

**Comment by geigerj** [comment]
Ah, shoot. Didn't realize `operations` was already included in `googleapis_common_protos`. I will discuss with @bjwatson about how best to proceed.

**Comment by bjwatson** [comment]
Sorry, I didn't notice that either.

@tseaver Are you okay with the version of LRO in `googleapis-common-protos`, or did you need them packaged separately for some reason?

**Comment by geigerj** [comment]
AFAIK `googleapis-common-protos` does not use the grpc plugin, so there will be no grpc stub.

**Comment by geigerj** [comment]
@tseaver Sorry for the confusion. If you were already rolling your own solution for the `Operations` service, please continue to use that -- I think we're going to abandon `grpc-google-longrunning-v2` for now. We'll keep thinking about how longrunning integrates with Veneer Toolkit and update when we know more.

**Comment by garrettjonesgoogle** [comment]
FYI for Java, my plan was to roll this into the Java equivalent of googleapis-common-protos, and I was going to use the grpc plugin on `Operations`. I think it would be best to make a simple rule that protos with no major version go into the common protos package.

**Comment by geigerj** [comment]
SGTM. If that's the plan for Java, we can do the same for Python.

**Comment by tseaver** [comment]
@garrettjonesgoogle I thought about that idea, but worried about adding the extra dependencies to `googlapis-common-protos` (which is currently blissfully unaware of `grpcio` and `oauth2client`:  it only depends on `grpcio`).

**Comment by garrettjonesgoogle** [comment]
@tseaver but are the common protos useful outside of the context of using them in grpc?

**Comment by tseaver** [comment]
@garrettjonesgoogle Until recently, `gcloud.datastore` spoke protobufs-over-HTTPS, rather than protobufs-over-gRPC.  We originally picked up the `googleapis-common-protos` dependency in order to use stuff from `google.rpc. status_pb2` and `google.type.latlng_pb2`.

**Comment by garrettjonesgoogle** [comment]
This might suggest a packaging scheme where we have the message types from Operations in googleapis-common-protos, but create a new googleapis-common-grpc for the non-versioned grpc-generated `Interface`s in googleapis, which for now would be just Operations.

**Comment by geigerj** [comment]
@bjwatson and I discussed that last scheme (separating `Services` from other proto types in the common protos), but that would require modifying the protos (undesirable because we'd need to maintain the restriction that all future common protos have services and types in separate files) or the gRPC codegen (difficult because we do not maintain `protoc`).

**Comment by garrettjonesgoogle** [comment]
Oh yeah, I forgot that multiple non-Java languages stick the types & operations in a single file.

So, it sounds like this is the choice to make: do we want to (1) be backwards-incompatible (operation messages get moved out into their own package), or (2) have the grpc dependency foisted on everyone? Or maybe (3), update protoc & gRPC codegen for all languages to put types & operations in distinct files, so that we actually have the ability to separate them.

**Comment by bjwatson** [comment]
So we decided on option (2). The LRO service methods are now in https://pypi.python.org/pypi/googleapis-common-protos.

@tseaver Can I remove the https://pypi.python.org/pypi/grpc-google-longrunning-v2/ project, since we don't need it?

**Comment by jonparrott** [comment]
Please don't delete anything from PyPI unless absolutely necessary (e.g., legal issues). Just update the trove classifiers and mark it as deprecated and possibly publish a new version that warns about deprecation.

**Comment by jonparrott** [comment]
Forcing grpc on everyone also seems like a bad choice, and would immediately rule out any usage of this library on GAE Standard for the foreseeable future. /cc @omaray

**Comment by garrettjonesgoogle** [comment]
But does adding a grpc dependency (without using it) actually break consumers?

**Comment by jonparrott** [comment]
It's very possible.  Even if that's not the case today, it could easily
change underneath us. I won't feel comfortable with grpc being a hard
requirement until gae has first class support for it.

**Comment by garrettjonesgoogle** [comment]
Can it be a soft requirement, with the intent of grpc working on gae as a first class citizen down the road? It becomes a painful package explosion if we have to maintain everything in pairs of packages (message types, grpc service types).

**Comment by jonparrott** [comment]
How do you propose it being a "soft" requirement?

**Comment by garrettjonesgoogle** [comment]
Python team members - @bjwatson @geigerj - any ideas?

**Comment by jonparrott** [comment]
So as it stands today grpc is an `extra` on this library. Using this library without grpc means that the hand-written clients will work over HTTP. These versions are compatible with GAE Standard.

I know the grpc revolution is coming and essentially all generated APIs will not work without them, so I understand the desire to move toward having grpc installed by default, however, we will leave GAE standard behind.

@omaray I feel like this is ultimately your decision. If you're okay with us essentially dropping GAE standard support until the GAE team can add grpc support, then I suppose I am as well.

**Comment by omaray** [comment]
We need to ensure our Python libraries work on GAE Standard. The current setup was great because it allowed to default back to http in case something was wrong with gRPC. And this applies to other environments too.

So is there another solution?

**Comment by bjwatson** [comment]
I've already released 1.3.x of https://pypi.python.org/pypi/googleapis-common-protos with grpcio as a `install_requires`. @jonparrott if I change this to an `extras_require`, does that satisfy the needs of our GAE Standard clients?

The alternative is extra engineering work to separate the `longrunning` messages and services into two separate packages, which is a bit of a fragile post-processing hack we would have to do to the gRPC output (unless they added a feature to explicitly support this mode).

**Comment by bjwatson** [comment]
FYI @jmuk. I know you've had similar conversations on the Ruby side.

**Comment by jonparrott** [comment]
@bjwatson that *could* work, this library would have to update the grpc extra to require `googleapi-common-protos[grpc]`. I'm not 100% sure this will work, so it probably needs to be tested before we go and publish the packages.

(Note: users are [already](https://github.com/GoogleCloudPlatform/gcloud-python/issues/2238#issuecomment-244411824) having fun with grpc).

**Comment by jonparrott** [comment]
btw testpypi exists for the purposes of testing: https://testpypi.python.org/pypi

**Comment by bjwatson** [comment]
thanks @jonparrott. we'll try this out with testpypi

**Comment by bjwatson** [comment]
@tseaver @jonparrott The updated package with an optional `[grpc]` dependency is available at https://testpypi.python.org/pypi/googleapis-common-protos (version 1.3.2).

`pip install googleapis-common-protos`
 -or-
`pip install googleapis-common-protos[grpc]`

**Comment by bjwatson** [comment]
FYI, the test package has long since been published on regular PyPI. We are currently at `1.3.4`.

**Comment by jonparrott** [comment]
This exists in gax now, I'm gonna close this.

**Comment by asandeep** [comment]
Apologies for resurrecting this thread. 

I am trying to implement longrunning operation interface for one of my APIs. I tried installing apis-common-protos using `googleapis-common-protos` and `googleapis-common-protos[grpc]`. The `operations_grpc_pb2.py` from installed package does contain client stub, but no `servicer` interface is available.

Am I missing anything here or are there any specific instructions to generate the same?

**Comment by asandeep** [comment]
I am bit stuck on this. @bjwatson @theacodes any pointers would be really appreciated.
