### ISSUE TITLE
Support reading API key from an environment variable

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#2123]
To make using the Translate client more like the other clients, let it sniff for the key.  Per discussion in https://github.com/GoogleCloudPlatform/gcloud-common/issues/164:

``` bash
$ export GOOGLE_API_KEY="AB123CD456EF7890==="
$ python
```

``` python
>>> from gcloud.translate import Client
>>> client = Client()
>>> client.api_key
'AB123CD456EF7890==='
```

System tests would then do a similar environment variable name swap for translate as for the other APIs.

**Comment by lukesneeringer** [comment]
We do not support API keys anymore.
