### ISSUE TITLE
Support generic Batch HTTP requests

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/google-cloud-python#2125]
All OnePlatform APIs support bundled http requests, apiary client libraries implement this, described here: https://developers.google.com/api-client-library/python/guide/batch

It would be nice if client came with a batch implementation. I'm not sure how this would interact with API specific batching protocols, but it would be nice if the surface could be unified across APIs.

**Comment by dhermes** [comment]
That's really good to know! Thanks for the heads up.

**Comment by tswast** [comment]
+1 We got feedback about this issue on the https://cloud.google.com/bigquery/batch page. Since we are using this library for all samples now, there are no code samples on that page.

**Comment by tswast** [comment]
Closing this since batch is considered a legacy feature. It is not supported in new gRPC-native APIs.

**Comment by daspecster** [comment]
@tswast is that just for Bigquery or all gRPC APIs?

What is the alternate strategy?

**Comment by tswast** [comment]
All gRPC, but HTTP endpoints still support batch. Many APIs support both HTTP and gRPC. I think since gRPC is based on HTTP v2 batch is more-or-less built into the protocol.

@louiscryan Can you clarify why batch should not be exposed for new APIs?

**Comment by louiscryan** [comment]
Batching provides two features today:
a - hard routing affinity, i.e. all requests end up at the same backend
b - some transport efficiencies over vanilla HTTP/1.1

If all you cared about was (b) then that is solved more thoroughly with GRPC/HTTP2 without the need for additional APIs to be exposed.

(a) can provide cache-locality benefits but it can also reduce your SLA if you're not careful so the choice to leverage this behavior should be carefully made by individual APIs.

We generally recommend APIs that need batching to make it part of the API itself e.g.
https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.proto#L186
or to start using streams. If you want hard routing affinity across a set of temporally spaced API calls you should use some kind of affinity key in a header. A 'batch' library method is not the right mechanism to expose these semantics.

**Comment by dhermes** [comment]
Thanks for the great explanation @louiscryan!
