### ISSUE TITLE
LoadTableFromStorageJob:  allow adding sources from blobs, bucket + glob

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#2126]
Default the initial `source_uris` to an empty list, then add methods to add extra sources.  E.g.:

``` python
class LoadTableFromStorageJob(_AsyncJob):

    ...

    def __init__(self, name, destination, source_uris=(), client, schema=()):
        super(LoadTableFromStorageJob, self).__init__(name, client)
        self.destination = destination
        self.source_uris = list(source_uris)
        # Let the @property do validation.
        self.schema = schema
        self._configuration = _LoadConfiguration()

    ...

    def add_bucket_source(self, bucket, glob):
        """Add a source URI for blobs matching 'glob' in 'bucket'.

        :type bucket: string or :class:`~gcloud.storage.bucket.Bucket`
        :param bucket: bucket or bucket name

        :type glob: string
        :param glob: blob name or name prefix with '*'
        """
        if isinstance(bucket, Bucket):
            bucket = bucket.name
        self.source_uris.append('gs://%s/%s/' % (bucket, glob))

    def add_blob_source(self, blob):
        """Add a source URI for a single blob.

        :type blob: :class:`~gcloud.storage.blob.Blob`
        :param blob: blob
        """
        bucket = blob.bucket.name
        self.source_uris.append('gs://%s/%s/' % (bucket, blob.name))
```

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
