### ISSUE TITLE
Use GAX generated libraries for Datastore and Bigtable

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2128]
@bjwatson WDYT of this? We are currently generating via `protoc` with our own `Makefile`s ([datastore](https://github.com/GoogleCloudPlatform/gcloud-python/blob/a9891abdd9a8fb83194d67c01ae0980ae395fbe9/Makefile.datastore) and [bigtable](https://github.com/GoogleCloudPlatform/gcloud-python/blob/a9891abdd9a8fb83194d67c01ae0980ae395fbe9/Makefile.bigtable_v2)).

**Comment by bjwatson** [comment]
@dhermes You sure can. Do you mind if I complete this after https://github.com/GoogleCloudPlatform/gcloud-python/issues/2117#issuecomment-240834648?

BTW, we won't be able to do much more than wrap these calls in our Pythonic surface. My understanding is that we can't do much of our value-add stuff like page streaming with custom methods, and both of these services are full of custom methods (e.g. URLs ending in `:<custom_something>`).

**Comment by tseaver** [comment]
@bjwatson From our perspective, dropping the generated code is a pure win, even if we don't gain the other benefits.  Even just having the `grpc-google-datastore-v1` and `grpc-google-bigtable-v2` releases available (no GAX wrappers at all) would be great.

**Comment by dhermes** [comment]
No rush at all, just wanted to create a formal issue so we don't forget. Good to know `:<custom_something>` means custom!

Of the 28 methods in datastore/bigtable, 14 are custom, but the true number is 12/12 since the other 16 Bigtable admin methods will have many orders of magnitude fewer requests.

----

## BigtableTableAdmin (2/6 custom)

1. `CreateTable` -> `"v2/{parent=projects/*/instances/*}/tables"`
1. `ListTables` -> `"v2/{parent=projects/*/instances/*}/tables"`
1. `GetTable` -> `"v2/{name=projects/*/instances/*/tables/*}"`
1. `DeleteTable` -> `"v2/{name=projects/*/instances/*/tables/*}"`
1. `ModifyColumnFamilies` -> `"v2/{name=projects/*/instances/*/tables/*}:modifyColumnFamilies"`
1. `DropRowRange` -> `"v2/{name=projects/*/instances/*/tables/*}:dropRowRange"`

## Bigtable (6/6 custom)

1. `ReadRows` -> `"v2/{table_name=projects/*/instances/*/tables/*}:readRows"`
1. `SampleRowKeys` -> `"v2/{table_name=projects/*/instances/*/tables/*}:sampleRowKeys"`
1. `MutateRow` -> `"v2/{table_name=projects/*/instances/*/tables/*}:mutateRow"`
1. `MutateRows` -> `"v2/{table_name=projects/*/instances/*/tables/*}:mutateRows"`
1. `CheckAndMutateRow` -> `"v2/{table_name=projects/*/instances/*/tables/*}:checkAndMutateRow"`
1. `ReadModifyWriteRow` -> `"v2/{table_name=projects/*/instances/*/tables/*}:readModifyWriteRow"`

## BigtableInstanceAdmin (0/10 custom)

1. `CreateInstance` -> `"v2/{parent=projects/*}/instances"`
1. `GetInstance` -> `"v2/{name=projects/*/instances/*}"`
1. `ListInstances` -> `"v2/{parent=projects/*}/instances"`
1. `UpdateInstance` -> `"v2/{name=projects/*/instances/*}"`
1. `DeleteInstance` -> `"v2/{name=projects/*/instances/*}"`
1. `CreateCluster` -> `"v2/{parent=projects/*/instances/*}/clusters"`
1. `GetCluster` -> `"v2/{name=projects/*/instances/*/clusters/*}"`
1. `ListClusters` -> `"v2/{parent=projects/*/instances/*}/clusters"`
1. `UpdateCluster` -> `"v2/{name=projects/*/instances/*/clusters/*}"`
1. `DeleteCluster` -> `"v2/{name=projects/*/instances/*/clusters/*}"`

## Datastore (6/6 custom)

1. `Lookup` -> `"v1/projects/{project_id}:lookup"`
1. `RunQuery` -> `"v1/projects/{project_id}:runQuery"`
1. `BeginTransaction` -> `"v1/projects/{project_id}:beginTransaction"`
1. `Commit` -> `"v1/projects/{project_id}:commit"`
1. `Rollback` -> `"v1/projects/{project_id}:rollback"`
1. `AllocateIds` -> `"v1/projects/{project_id}:allocateIds"`

**Comment by bjwatson** [comment]
Good analysis! At least we can provide extra help with methods like `ListTables` and `ListClusters`, even if they are low QPS.

**Comment by dhermes** [comment]
> dropping the generated code is a pure win

Exactly this! That was the point of #1384

**Comment by bjwatson** [comment]
@dhermes I'm now in a position in which I can deliver GAPIC for these APIs, but I want to make sure that you can use them in the near future.

I can now deliver Datastore without much effort, but Bigtable is prone to change in the coming weeks since we're still nailing down our LRO and streaming designs. Nevertheless, I can deliver both if you're planning to layer your code on ours soon after I deliver it (and then give you an update for Bigtable in a few weeks).

Please let me know.

**Comment by dhermes** [comment]
How do you mean "can use them"? Like we block you somehow from generating them?

**Comment by bjwatson** [comment]
I mean will you use them sometime in the next week if I spend time on generating them now?

I'm trying not to spend more time on generating APIs than necessary right now, and instead focus on doing things to finalize our surfaces and improve our efficiency at generating APIs. I will do this if you have the bandwidth to consume it.

**Comment by lukesneeringer** [comment]
This is still on the "would be nice" list, as I just saw the `_generated` directory in BigTable, but I do not think keeping this issue open is worthwhile tracking at this point.

**Comment by dhermes** [comment]
@lukesneeringer It's also a bit moot since you **want** the generated source in our source tree
