### ISSUE TITLE
Calling 'job.begin' on job returned from 'Table.upload_from_file' raises a 400

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#2133]
Trying to load data into bigquery with `upload_from_file` returns a 400.

Sample code:

```python
def load_data_from_file(dataset_name, table_name, source_file_name):
    bigquery_client = bigquery.Client()
    dataset = bigquery_client.dataset(dataset_name)
    table = dataset.table(table_name)

    # Reload the table to get the schema.
    table.reload()

    with open(source_file_name, 'rb') as source_file:
        # This example uses CSV, but you can use other formats.
        # See https://cloud.google.com/bigquery/loading-data
        job = table.upload_from_file(
            source_file, source_format='text/csv')

    job.begin()

    wait_for_job(job)

    print('Loaded {} rows into {}:{}.'.format(
        job.output_rows, dataset_name, table_name))
```

Error:

```
Traceback (most recent call last):
  File "load_data_from_file.py", line 77, in <module>
    args.source_file_anme)
  File "load_data_from_file.py", line 45, in load_data_from_file
    job.begin()
  File "/Users/jonwayne/workspace/python-docs-samples/bigquery/cloud-client/env/lib/python3.4/site-packages/gcloud/bigquery/job.py", line 364, in begin
    method='POST', path=path, data=self._build_resource())
  File "/Users/jonwayne/workspace/python-docs-samples/bigquery/cloud-client/env/lib/python3.4/site-packages/gcloud/connection.py", line 347, in api_request
    error_info=method + ' ' + url)
gcloud.exceptions.BadRequest: 400 Load configuration must specify at least one source URI (POST https://www.googleapis.com/bigquery/v2/projects/python-docs-samples-tests/jobs)
```

**Comment by matheuspatury** [comment]
Any updates on this issue? My project is stuck because of it...

**Comment by jgeewax** [comment]
Do we know what the problem is yet ? @tseaver 

/cc @omaray

**Comment by tseaver** [comment]
There is a workaround:  first upload the file to Storage, and then load the table from there.  E.g., see [this system test](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/system_tests/bigquery.py#L291-L360).

I will look into reproducing the issue with a new system test.

**Comment by tseaver** [comment]
@jonparrott, @matheuspatury Note that it is an error to call `job.begin()`, because the job returned from `table.upload_from_file` is a) already started, and b) lacks information needed to start (the error it reports).  #2313 shows that the job completes fine without that call.

**Comment by jonparrott** [comment]
Strange, why does the API start this job for you but doesn't do so for
other things? We should be consistent.

**Comment by tseaver** [comment]
In this mode, we start by uploading a file:  the back-end spools the uploaded file off somewhere in secret, and has begun to process it before ever returning to the client.  Other jobs are created locally on the client first.  Given how the back-end works, the only way to be "consistent" would be to remove this feature, and require that users upload files to Storage before loading them.

We could raise a more informative error from `Job.begin` if we could detect this case (`self.state != None` would do it), or we could make it a no-op instead.

**Comment by jonparrott** [comment]
Weird.

An informative error from `begin` would be okay with me, as long as there isn't strong feelings that it should no-op.

It would also be nice to update the docstring to indicate that the job is already started.

**Comment by Etiennepi** [comment]
>  Note that it is an error to call job.begin()
Might want to edit the example at https://cloud.google.com/bigquery/loading-data-post-request#bigquery-import-file-python then, as it's telling us to do exactly that when uloading a file from a local machine.

**Comment by tseaver** [comment]
@jonparrott Can you fix that snippet?

**Comment by jonparrott** [comment]
Weird, that snippet is tested. Did we make `begin()` idempotent?

**Comment by jonparrott** [comment]
Nevermind, I see. I had the test marked as xfail. Fixing now. Thanks!
