### ISSUE TITLE
Add OS X to Travis (or other) CI

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2136]
/cc @omaray

**Comment by dhermes** [comment]
Looks easy to turn on:
https://docs.travis-ci.com/user/multi-os/

Toying around with it now

**Comment by omaray** [comment]
I think this was done, right? Anything else we should do here? 

To my knowledge, we should now be able to have support for Unit and System tests on all 3 OS environments. Is that correct?

**Comment by tseaver** [comment]
@omaray We closed #2138 without merging it because of the problems we were seeing with Travis' flaky Mac support at the time:  it was backlogged for *days* at one point.  Even before then, the Mac builds are super slow, compared to the Linux VM builds.

**Comment by dhermes** [comment]
Speed wasn't the main issue, the main issue was that they don't have a system Python installed on their Mac VMs.

**Comment by omaray** [comment]
Oh right, Travis has little love for Python and OS X.

**Comment by dhermes** [comment]
@lukesneeringer No longer a priority to run CI for OS X?

**Comment by lukesneeringer** [comment]
Correct.
