### ISSUE TITLE
Should we run system tests in more than one CI environment?

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2137]
Right now we [only run unit tests](https://github.com/GoogleCloudPlatform/gcloud-python/blob/6896144def9d0c8acd532451766ee293d5fb627a/appveyor.yml#L95) on AppVeyor (our Windows CI) and limit the system tests to Travis (our linux CI).

/cc @omaray

**Comment by omaray** [comment]
Sorry for the delay on this. Ideally yes, that would be great. Running all tests in all OS environments. Any reasons to not do so?
