### ISSUE TITLE
Bigquery client doesn't implement list_projects

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#2143]
Seems weird, but the bigquery client should also be able to list projects:

https://cloud.google.com/bigquery/docs/managing_jobs_datasets_projects#projects

**Comment by tseaver** [comment]
@jonparrott I left the API out because I couldn't imagine a use-case for it.  It seems like the purview of [ResourceManager](https://github.com/GoogleCloudPlatform/gcloud-python/blob/fd0e6bf7aac1f4373c64d8e76552d395a1dbf279/gcloud/resource_manager/client.py#L96), not BigQuery.

**Comment by jonparrott** [comment]
There are many users of bigquery that don't use any other APIs. I think
this is important, and its needed for our documentation.

**Comment by tseaver** [comment]
@jonparrott I can add this, but wonder why we don't have it in all the other APIs, too?

**Comment by jonparrott** [comment]
@tseaver it's just an artifact of how bigquery is setup. There are multiple "public" projects containing public bigquery datasets. BigQuery kind of exists on its own for historical reasons, so it makes sense for this to be here. (BigQuery was the 3rd cloud platform service - after GAE and GCS).
