### ISSUE TITLE
Make sure all snippets are in snippets files

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2154]
Related: #1141 and #1744

**Comment by dhermes** [comment]
@lukesneeringer This never got done and we currently have stale snippets in `docs/*_snippets.py`.

**Comment by lukesneeringer** [comment]
Sold. Reopening.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!

**Comment by dhermes** [comment]
@lukesneeringer You were sold once upon a time on this.

FWIW I'd prefer we use `doctest` over snippets files.

**Comment by tseaver** [comment]
We could certainly add support for exercising the snippets just as easily as adding doctest support.  Note that the doctests are currently used only in `datastore`, and only in docstrings (there are no narrative docs at all for datastore), so the use-cases may be different.

**Comment by lukesneeringer** [comment]
> You were sold once upon a time on this.

And in four months, none of us touched it. I am skeptical that another four months would change it.

In the Node.js reorganization, we are handling some conversion of tests; I could see the Python equivalent as a good venue for that.
