### ISSUE TITLE
Make the ad-hoc copy of logging `Client` less ad-hoc in background thread impl.

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2160]
A [client is copied](https://github.com/GoogleCloudPlatform/gcloud-python/blob/0bf3b686764ba7758dc47a7e783d11839e068f3b/gcloud/logging/handlers/transports/background_thread.py#L152-L159) to avoid re-using the same `httplib2.Http` object in different threads. This is crucial because `httplib2` is not threadsafe.

/cc @waprin

**Comment by tseaver** [comment]
#2208 suggests that making a clean copy of a client instance might be a broader requirement.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
