### ISSUE TITLE
test_create_and_delete_metric_descriptor gives 500 failure

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2176]
Done while creating a descriptor

POST https://monitoring.googleapis.com/v3/projects/precise-truck-742/metricDescriptors/

- https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154552669
- https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154561565
- https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154598135

/cc @supriyagarg

**Comment by rimey** [comment]
Thank you! I believe you spotted a problem in an ongoing rollout. We're taking action to fix it.

You just happened to be hitting our canary server instances.

**Comment by rimey** [comment]
This should now be resolved.

Occasional, rare 500s are always possible, but if you see something that appears not to be transient, please let us know.

**Comment by dhermes** [comment]
I mostly agree with you but want to discuss a little before hastily closing. Is there an SLA for the service?

The whole point of the `flaky` label is that we don't want to have to have 1/4 of our merges to master fail. Brittle system tests are no fun and the more services we support, the worse it gets.

> rare 500s are always possible

I somewhat agree (depending on the SLA). However, we got two runs of 500s in a row (4 requests in total) spaced out over several minutes.

The real question is, should we wrap the API calls in a retry for a 500?

**Comment by rimey** [comment]
Whether to retry API calls in the system tests on 500s is completely up to you. I don't have further advice for you about that.

**Comment by dhermes** [comment]
@tseaver WDYT about this?

**Comment by tseaver** [comment]
If it isn't an "expected" error from the point of view of the back-end team, I'd say leave out the retries.

**Comment by dhermes** [comment]
:+1:

**Comment by dhermes** [comment]
@rimey We saw 3 more 500s:

https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154939849
https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154939849

Is there an ongoing service issue?

**Comment by tseaver** [comment]
Worse, they are the only ones blocking us from green.

**Comment by tseaver** [comment]
@dhermes I'm changing my mind about the retries:  I *really* want green.

**Comment by rimey** [comment]
There's no ongoing service issue that I know of.

**Comment by rimey** [comment]
In what GCE zone are you running the system tests?

**Comment by tseaver** [comment]
> In what GCE zone are you running the system tests?

I don't know the answer to that question.  On Travis, the tests run with a system account for project `precise-truck-747`.  On the monitoring console, that appears to be wired up to  GAE module `omega-moonlight-697`.

**Comment by dhermes** [comment]
@rimey The Travis CI system might run on GCE but we have no way of knowing. That shouldn't matter though?

**Comment by tseaver** [comment]
@rimey, @dhermes I realized that one difference between running the system tests on Travis and on our local machines is that `unique_resource_id()` returns a much longer string when `TRAVIS_BUILD_ID` is present in the environment:  in fact, with current build IDs, the type name is a suspicious 41 characters in length.  #2213 shortens the type name prefix, allowing the test which failed on my box with `TRAVIS_BUILD_ID="155516883"` to pass with that envvar set.

**Comment by rimey** [comment]
This is interesting. I'll look into it.

The maximum length of a metric type is supposed to be 100 bytes.

**Comment by tseaver** [comment]
I looked for a limit in the [docs](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors#MetricDescriptor.FIELDS.type), and didn't find one.

**Comment by rimey** [comment]
The limit is mentioned on a [different page](https://cloud.google.com/monitoring/api/v3/metrics#label_names).

**Comment by tseaver** [comment]
@rimey thanks for that pointer.  Note that shortening the `MetricDescriptor.type` value did allow the system test, which had previously been failing consistently on Travis, to pass after merging #2213.

- https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/155569740#L938
- https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/155569740#L1187

**Comment by dhermes** [comment]
@rimey What is the status here? Can we close this out?

**Comment by rimey** [comment]
The 500s that you were getting when deleting metric descriptors were due to a bug, the fix for which finished rolling out today.

You can now create and delete metric descriptors with a type name of up to exactly 100 characters.

**Comment by dhermes** [comment]
Thanks.
