### ISSUE TITLE
Don't reference ISO-639-1 language codes for language API

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2184]
https://github.com/GoogleCloudPlatform/gcloud-python/pull/2062/files/d36ad4db94666450786d4f667aea0607ff2113cb#r76032913

@jgeewax Please advise. You've asked to only include BCP-47 but the [official docs](https://cloud.google.com/natural-language/reference/rest/v1beta1/Document) still refer to both.

**Comment by jgeewax** [comment]
Yep - they will accept both, but we should only talk about BCP-47 which will be the standard.

**Comment by dhermes** [comment]
@jgeewax Can you comment on why we should contradict / subset what's in the official docs?

**Comment by dhermes** [comment]
This is stale?
