### ISSUE TITLE
Auto-detect GCS URI that ends in .html or .htm

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2185]
See https://github.com/GoogleCloudPlatform/gcloud-python/pull/2062/files/d36ad4db94666450786d4f667aea0607ff2113cb#r76033629

**Comment by lukesneeringer** [comment]
Hello! 
We have done a less-than-great job of dealing with issues in this repository. Sorry about that. :-(

In this case, we have released an entirely different version of `google-cloud-language`, which is very likely to have solved this issue, so I am going and closing language-related issues _en masse_ to try and regain sanity and ability to tackle things.

Please upgrade to the newest version of `google-cloud-language` and use `LanguageServiceClient`. Note that this will require a code change. If your issue persists, feel free to reopen. :-)
