### ISSUE TITLE
Duplicate code between resource classes

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/google-cloud-python#2186]
There are numerous reimplemented duplicate pattern in resources. 

For example `_require_client` is reimplemented on every resource. It would be nice if these were gathered up into a parent `Resource` class which only provided things guaranteed to be available in all cloud resources... e.g. a resource path. 

Implementing iam #2031 all that's required to implement in supporting APIs is a correct `self.path` and `self._require_client`. I suspect there will be other common interfaces e.g. Batching which will want similar guarantees.

**Comment by dhermes** [comment]
I am hesitant to say that's a good idea. The cloud APIs vary widely and so there isn't much they share between them. `_require_client` is just sugar for access. Any other examples?

**Comment by elibixby** [comment]
They all share a path attribute, and even if `_require_client` is just sugar it seems strange that it's reimplemented... 

But I understand that this is a slippery slope towards a complex and messy class hierarchy. Up to you ultimately.
