### ISSUE TITLE
Add system test that uses an HTML document instead of a plaintext doc

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2190]

**Comment by lukesneeringer** [comment]
Hello! 
We have done a less-than-great job of dealing with issues in this repository. Sorry about that. :-(

In this case, we have released an entirely different version of `google-cloud-language`, which is very likely to have solved this issue, so I am going and closing language-related issues _en masse_ to try and regain sanity and ability to tackle things.

Please upgrade to the newest version of `google-cloud-language` and use `LanguageServiceClient`. Note that this will require a code change. If your issue persists, feel free to reopen. :-)
