### ISSUE TITLE
Travis-CI nearly unusable due to extremely long queuing.

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#2200]
For gcloud-python and other languages, Travis-CI has been taking many hours to run builds.

We should address this in order to maintain gcloud-python quality and reliability.

**Comment by jonparrott** [comment]
This is the case across the GoogleCloudPlatform org.

**Comment by daspecster** [comment]
@jonparrott, hopefully things can get sorted out in the GoogleCloudPlatform travis account. If not I guess we'll need to get a secondary plan together.

**Comment by waprin** [comment]
Some options our team is considering: 

1) Figure out if Travis can fix it

2) I have an internal Jenkins instance. It's firewall off but it can upload build output and build history to GCS buckets  as comments on the PRs. Take a look at github.com/kubernetes/minikube PRs to see what it could look like. If you're interested happy to set it up but I'm on vacation next 2 weeks though I'm sure Jon could figure it out too.  

3) CircleCI

4) Turn your test into a Docker build and then use Cloud Container Builder.

**Comment by daspecster** [comment]
@waprin, 2 & 4 sound really cool. I think having the badge for a public project is valuable though.
I'm not sure what other people think?

I did notice that sometime this weekend, things with travis have seemed to speed up. If this holds out for a few days(September 1st) then I'll close this.

**Comment by tseaver** [comment]
I wonder if the huge backlog was due to [Travis OSX problem](https://www.traviscistatus.com/incidents/4mvp857qx8bw).

**Comment by daspecster** [comment]
I really hope they don't have an architecture that is tightly coupled enough to have one platform cause issues with other platforms.
I guess if they had a bunch of backed up OSX builds and needed to swing vm resources over to OSX to catch back up?

**Comment by dhermes** [comment]
Closing this out because Travis seems to have sped back up. Maybe not though? Feel free to re-open.
