### ISSUE TITLE
JSON serialization should include key and url_safe_key ?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-python#2206]
Apparently the entity default JSON serialization excludes the key and url_safe key. 

According to a customer "Both of those are super useful, and IMO are parts of the datastructure, not internal. "

**Comment by tseaver** [comment]
AFAIK, datastore doesn't use / render / speak JSON:  the API is either protobuf-over-HTTP or protobuf-over-gRPC.

```bash
$ git grep -i json gcloud/datastore/
gcloud/datastore/_generated/_entity.proto:    // In JSON requests, must be base64-encoded.
gcloud/datastore/connection.py:            raise make_exception(headers, error_status.message, use_json=False)
```

Even if we *were* speaking JSON, the [`Entity` representation would have the key](https://cloud.google.com/datastore/reference/rest/v1/Entity).

**Comment by tseaver** [comment]
I wonder if the user is talking about the fact that `Entity` inherits from `dict`, and accesses the properties via `__getitem__`, but also has its `key` as an attribute.  That is a deliberate design choice (see that JSON representation in the docs, which also separates the key from the properties.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
