### ISSUE TITLE
Write a Datastore Overview doc

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-python#2207]
We don't have a summary doc on rtd.org... It'd be really nice ot have an overview for Datastore.

**Comment by dhermes** [comment]
@lukesneeringer This still doesn't exist

**Comment by lukesneeringer** [comment]
I know, but I am going to be doing a larger rehash of docs with @omaray, so do not need an issue to track Datastore specifically.

**Comment by dhermes** [comment]
:+1:
