### ISSUE TITLE
'test_list_files':  eventual consistency failure

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#2216]
From https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/155830290#L813-L830:

``` python
======================================================================
FAIL: test_list_files (storage.TestStorageListFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/system_tests/storage.py", line 238, in test_list_files
    sorted(self.FILENAMES))
AssertionError: Lists differ: [u'CloudLogo1', u'CloudLogo2'] != ['CloudLogo1', 'CloudLogo2', '...
Second list contains 1 additional elements.
First extra element 2:
CloudLogo3
- [u'CloudLogo1', u'CloudLogo2']
?  -              -
+ ['CloudLogo1', 'CloudLogo2', 'CloudLogo3']
?                            ++++++++++++++
```

**Comment by dhermes** [comment]
Fixed in #2181.

**Comment by tseaver** [comment]
Just saw this failure again:

https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/165570717#L4150

**Comment by dhermes** [comment]
@tseaver Looks like it needs more retries?

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
