### ISSUE TITLE
Remove all sleep() statements from unit tests

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2220]
Without the sleeps, the unit tests are "fast", i.e. they just run without any pauses and take ~1.5 seconds. With the sleeps from the three offending test cases, the unit tests take ~4.5 seconds.

@waprin these are all in `gcloud.logging.handlers.transport.test_background_thread`. Wanted to assign this to you but can't for some reason? (Never sure how org. vs. project permissions matter for issue assignment.)

**Comment by tseaver** [comment]
Another option is to shorten the sleeps drastically (e.g., `time.sleep(0.05)` vs. `time.sleep(1)`.

**Comment by dhermes** [comment]
@tseaver In a perfect world we'd just have a check which says "really human? you want your unit tests to be non-deterministic?". In other words, the "simple check" just disallows all sleeps and doesn't differentiate / allow for nuance (this is more scalable across all devs).

**Comment by lukesneeringer** [comment]
Confirmed that `sleep` no longer appears in this file. I also verified the three places it does appear in our unit tests and ensured it was mocked.
