### ISSUE TITLE
Add informational headers to gRPC requests sent for datastore

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2230]
See https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1542

We need to modify the headers [being sent to](https://github.com/GoogleCloudPlatform/gcloud-python/blob/6ce152cc097a113874a7713cceb99ce2eda13818/gcloud/_helpers.py#L572-L575):

``` python
headers = [
    ('authorization', 'Bearer ' + access_token),
    ('user-agent', self._user_agent),
    ('google-cloud-resource-prefix', 'projects/my-project-id'),
]
```

Though we may want to do this on a per-request basis. Probably not, since `self._user_agent` doesn't change after the `MetadataPlugin` object is created, even if the user agent on the original `Client` has changed.

**Comment by tseaver** [comment]
#2221 is broader than this issue would suggest.

**Comment by dhermes** [comment]
@tseaver Focusing on the datastore case, this is a bit awkward even as-is. The `Connection` doesn't have access to the project, since the `Client` handles that.

But the `Connection` is essentially a dumb wrapper around `_DatastoreAPIOverHttp` / `_DatastoreAPIOverGRPC` combined with some helpers for constructing the protobufs to be sent off.

WDYT about removing the `datastore.connection` module all together?

**Comment by tseaver** [comment]
The `Connection` class is still responsible for managing the low-leve REST bits:  I guess you could gut those parts into the `_DatastoreAPIOverHttp` class, and have the client just hold an instance of it (or the gRPC variant).  They still need somewhere to live, which makes trashing the module problematic.

**Comment by dhermes** [comment]
>  is still responsible for managing the low-leve REST bits

[Not really][1]

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/891b0603d76082c1b8f7085d00534f021d1b8b3e/google/cloud/datastore/connection.py#L67-L125

**Comment by tseaver** [comment]
That example delgates to the connection's `_build_api_url` method, uses its `USER_AGENT`, an calls into its `http` attr to make the actual request.  Those were the bits I was talking about moving into `_DatastoreAPIOverHttp`.

**Comment by dhermes** [comment]
Gotcha! That was just "laziness" to get the implementation to fit. I've got a speculative PR in the works, coming soon. We can chat about that?

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!

**Comment by eddavisson** [comment]
@lukesneeringer, could we re-open this?

We are still interested in having this header added to gRPC requests:

`google-cloud-resource-prefix: projects/my-project-id`

(This functionality is already in place for Spanner and Firestore.)

This is may not be relevant for _all_ APIs, so I think this is the right issue to re-open as opposed to https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2221.

Thanks!
