### ISSUE TITLE
Broken links abound in SD docs

### ISSUE THREAD

**Issue by mattbnz** [GoogleCloudPlatform/google-cloud-python#2246]
I'm trying to read the docs for the SD monitoring API. Broken links abound.

I'm starting at: https://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud/monitoring

I click on the link for details about "Monitored Resource Descriptors" which hover says will go to https://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud/monitoring/index/resourcedescriptor but my browser actually ends up at https://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud which has no content.

I hit back and figure I'll just look at the source since the docs are broken, so I hit "Source Code" down the bottom of the original page, which takes me to https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/ which is a complete 404 served by github.

**Comment by rimey** [comment]
You might have a better time at [Read the Docs](https://gcloud-python.readthedocs.io/en/latest/monitoring-usage.html).

**Comment by mattbnz** [comment]
How would I find that link you supplied?

The links I pasted above are what is linked off the front page of https://github.com/GoogleCloudPlatform/gcloud-python for "API documentation" - readthedocs.io is nowhere to be found as a link from here... 

The docs on github are also where the big read "Read the Docs" link from https://googlecloudplatform.github.io/gcloud-python/#/ takes you, which is doubly confusing given the name of the link doesn't actually link to readthedocs.io... :)

Searching for [gcloud python docs] or [gcloud python documentation] doesn't provide any hint of readthedocs.io either. 

I appreciate the pointer in the meantime, it does help, but it also means the situation is even worse than I thought initially!

**Comment by daspecster** [comment]
Thanks for reporting @mattbnz!

I think we should put the readthedocs link in the README.md.

The googlecloudplatform.github.io/gcloud-python docs are currently a work inprogress. They were just converted to an auto generated platform and there are edge cases that continue to pop up.

I'll see if I can figure this one out and I'll post back if I find the issue.

**Comment by daspecster** [comment]
I'm going to close this for now since we switched back to sphinx documentation.
