### ISSUE TITLE
GCloud Python Doc Incomplete - Master Branch

### ISSUE THREAD

**Issue by iAmAnkeeta** [GoogleCloudPlatform/google-cloud-python#2256]
The documentation for gcloud python is incomplete.
https://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud
https://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud/datastore
If you go to source code you get 404.

**Comment by daspecster** [comment]
@iAmAnkeeta thanks for reporting! Sorry about the late response.

The docs are now at https://googlecloudplatform.github.io/gcloud-python.

I'm going to close this for now, but if those link are still up somewhere that we can change, feel free to reopen!

**Comment by iAmAnkeeta** [comment]
@daspecster Thank you! :)

**Comment by daspecster** [comment]
No problem! Let us know if you have any other questions!
