### ISSUE TITLE
Travis build broken due to GCLOUD --> GOOGLE_CLOUD rename

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2259]
I broke it with #2223: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/158235243

All of the env. vars. need to be updated:
https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/settings

I have to teach from 11am-2pm Pacific but will try to fix it ASAP after that.

We are starting to see the 90% of the iceberg in the water on this rename.

**Comment by tseaver** [comment]
Issues so far:

- Need to get the env vars copied (@daspecster is working on that).
- Namespace packages  (`pubsub` / `logging`) break the client construction in system tests (see #2260)
- `logging`: expanded names for buckets / topics are too long (see #2260).
- `bigtable`: expanded instance ID too long (see #2261).

**Comment by tseaver** [comment]
The post-merge tests after #2260 and #2261 show only the #2280 "unexpected success" error.

**Comment by dhermes** [comment]
@daspecster Thanks for handling. How did the copy work?
