### ISSUE TITLE
Source Code links return 404 and no documentation provided

### ISSUE THREAD

**Issue by ngelinas** [GoogleCloudPlatform/google-cloud-python#2266]
**Source Code** links found on the [`gcloud.datastore.client.Client`](https://googlecloudplatform.github.io/google-cloud-python/#/docs/master/gcloud/datastore/client/client) documentation page are broken returning `404`s.  For instance, the `#put` method contains no documentation, not a huge deal, but the **Source Code** link goes to [https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/datastore/client.py#L317](https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/datastore/client.py#L317).  Perhaps the projects, directories or files were renamed since generating these documentation pages, thus breaking links?

**Comment by daspecster** [comment]
Thanks for reporting @ngelinas, this is from the recent repository rename.

@dhermes we should make the switch today if we can.
