### ISSUE TITLE
[Documentation Issue] Stackdriver Logging Client list_entries() filter_ parameter referred to as filter in apidocs

### ISSUE THREAD

**Issue by swegner** [GoogleCloudPlatform/google-cloud-python#2278]
Page Name: _modules/gcloud/logging/client
Release: 0.17.0

The API docs for list_entries() refer to the `filter_` parameter as `filter` in multiple places. In python, the correct name seems to be `filter_`.

Correct: https://googlecloudplatform.github.io/google-cloud-python/stable/_modules/gcloud/logging/client.html#Client.list_entries

Incorrect references I've noticed:

* https://googlecloudplatform.github.io/google-cloud-python/stable/logging-client.html#gcloud.logging.client.Client.list_entries
* https://googlecloudplatform.github.io/google-cloud-python/stable/logging-usage.html

**Comment by tseaver** [comment]
@swegner Thanks for the report!
