### ISSUE TITLE
copy_blob calls have started to fail in system tests (400 no file found in request)

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2289]
@thobrla Any idea why these requests would start to become flaky?

Some recent examples:

- https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/158783443
- https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/158777834
- https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/158764459
- https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/158717892
- https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/158645485

**Comment by thobrla** [comment]
Do you have a example of the full request / response for this error case?  I'm not aware of anything that would lead to a 400 like this.  Possibly the request had a connection drop and was only partially sent, but I would expect that to be quite rare.

**Comment by dhermes** [comment]
@thobrla The whole response was just `No file found in request.` (not a JSON or HTML response, just text) with a 400 status code (I don't have any of the other headers, sorry).

The request is a POST with no body to

```
https://www.googleapis.com/storage/v1/b/{BUKCET}/o/{FILE1}/copyTo/b/{BUCKET}/o/{FILE2}
```

**Comment by dhermes** [comment]
@thobrla It happened consistently for several days (see the Travis failures linked above). I checked some recent test runs and it doesn't seem to be triggering anymore, so that's good.

**Comment by thobrla** [comment]
Thanks.  I wonder if there was a bug in the service during this time.  Please let me know if it resurfaces.

**Comment by dhermes** [comment]
Will do. We may not detect it, right now we [are retrying][1] on the failure [up to 4 times][2].

CONTEXT: We have been sprinkling lots of retries in our system tests to get them to go green. Talking to 14 Google services at once (in 2 different Python environments) essentially guarantees a failure if no retries are used.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/67578df16a9feea3bfb22d02d916639ac5e0cf10/system_tests/storage.py#L214-L215
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/67578df16a9feea3bfb22d02d916639ac5e0cf10/system_tests/retry.py#L20

**Comment by thobrla** [comment]
That's understandable but 400 is not intended to be a retryable error, so you really shouldn't retry a 400 as in theory it will never succeed.

**Comment by dhermes** [comment]
@thobrla Indeed. We added a special [error predicate check][1] to make sure it wasn't any old 400, but it was the specific 400 we're discussing here.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/67578df16a9feea3bfb22d02d916639ac5e0cf10/system_tests/storage.py#L34-L38
