### ISSUE TITLE
[Documentation Issue] 

### ISSUE THREAD

**Issue by lucasduffey** [GoogleCloudPlatform/google-cloud-python#2296]
Page Name: index
Release: 0.18.1

you write "from gcloud import datastore" at https://googlecloudplatform.github.io/google-cloud-python/stable/

but write "from google.cloud import datastore" at https://googlecloudplatform.github.io/google-cloud-python/

docs need to be consistent

**Comment by dhermes** [comment]
https://googlecloudplatform.github.io/google-cloud-python/stable/ is an alias for https://googlecloudplatform.github.io/google-cloud-python/0.18.1/ and will be an alias for the next (stable) release.

If you want the docs for what's been checked into `master` check out:
https://googlecloudplatform.github.io/google-cloud-python/latest/

**Comment by dhermes** [comment]
Thanks for taking the time to file an issue though!
