### ISSUE TITLE
Can we enable "Require pull request reviews before merging"

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2317]
GitHub [recently added](https://help.github.com/articles/about-pull-request-reviews/) the ability to "approve" a PR (instead of typing LGTM). From the [branch settings](https://github.com/GoogleCloudPlatform/google-cloud-python/settings/branches/master) UI:

![screen_shot_001](https://cloud.githubusercontent.com/assets/520669/18535040/b184d032-7aa5-11e6-8a1f-bc1f463ea2e1.png)

Can we check the box? Though not sure how this works in two situations
- An owner "approves" their own PR when that is "bad"
- An owner needs to "approve" their own PR when they need to do an emergency merge

**Comment by dhermes** [comment]
This answers the bullet about emergency merges:

![screen_shot_002](https://cloud.githubusercontent.com/assets/520669/18535324/2d5b69ee-7aa8-11e6-8685-ed86e6e0a1c5.png)

**Comment by lukesneeringer** [comment]
I intend to turn this on very soon.
