### ISSUE TITLE
Dataset exists (409) / dataset still in use (DELETE --> 400)

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2318]
`python2`:

- Still in use: `precise-truck-742:system_tests_160041019_1473898532`
- Exists: `precise-truck-742:system_tests_160041019_1473898532`

then `python3`:

- Still in use: `precise-truck-742:system_tests_160041019_1473898730`
- Exists: `precise-truck-742:system_tests_160041019_1473898730`

From https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/160041019

Two proposed fixes:

- Make sure the 400 is caught and retried for "still in use"
- Use dataset IDs unique to each test (if possible)

**Comment by tseaver** [comment]
Big :+1:  for avoiding shared dataset IDs.

**Comment by dhermes** [comment]
@tseaver It's unclear if #2323 (double Michael Jordan) actually will fix the 400 "still in use". But it's not worth leaving this open forever.

**Comment by tseaver** [comment]
Because testcases no longer share dataset names, there isn't going to be a case where the eventual-consistency window for one testcase deleting its dataset overlaps the creation during setup of another testcase.

**Comment by dhermes** [comment]
But the clean-up of each dataset will be a delete and the "still in use" on DELETE is where the issue came from.

**Comment by dhermes** [comment]
@tseaver Let's leave it closed until the "still in use" shows up again in the wild?

**Comment by tseaver** [comment]
Hmm, I just kicked in #2333 to address it.

**Comment by dhermes** [comment]
Oh gotcha. SGTM.
