### ISSUE TITLE
Incorrect google cloud client pip package name in docs

### ISSUE THREAD

**Issue by georgegiovanni** [GoogleCloudPlatform/google-cloud-python#2340]
Page Name: index
Release: 0.18.1

The google cloud python [documentation](https://googlecloudplatform.github.io/google-cloud-python/) lists a non-existent package name of `google-cloud` for the python client library.

Current install instructions:
`pip install --upgrade google-cloud`

Should be:
`pip install --upgrade gcloud`

**Comment by dhermes** [comment]
Thanks for the heads up. We really need to get #2270 merged so that `google-cloud` has a valid package in it.

**Comment by jpatokal** [comment]
+1.  I see #2270 is still unmerged, so please fix the docs until it's ready.

**Comment by dhermes** [comment]
#2270 will be going in today. Thanks for the concern.
