### ISSUE TITLE
Pub/Sub subscriptions don't bind to the specified topic as stated in documentation

### ISSUE THREAD

**Issue by georgegiovanni** [GoogleCloudPlatform/google-cloud-python#2341]
Page Name: pubsub-topic
Release: 0.18.1

Can a helper `subscription` method be added in the `gcloud.pubsub.client.Client` class to facilitate subscribing to subscriptions similar to how there's a `topic` method to facilitate creating topics. Current [instructions](https://cloud.google.com/pubsub/docs/subscriber#receiving-pull-messages) for receiving pull messages suggest invoking the `gcloud.pubsub.topic.Topic.subscription` method which creates a subscription bound to the specified topic as follows:

```
pubsub_client = pubsub.Client()
topic = pubsub_client.topic(topic_name)
subscription = topic.subscription(subscription_name)

results = subscription.pull(return_immediately=True)
```

However a non-existent topic name can be supplied for `topic_name` and messages can still be received from the `results`.

The following code also works without having to specify a topic:

```
pubsub_client = pubsub.Client()
subscription = pubsub.subscription.Subscription(subscription_name, client=pubsub_client)
```

The `gcloud.pubsub.topic.Topic.subscription` documentation stating _"Creates a subscription bound to the current topic"_ is misleading because it seems it binds to all topics.

**Comment by tseaver** [comment]
@georgegiovanni Thanks for the report!

**Comment by ensonic** [comment]
It doesn't really work:

```python
#!/usr/bin/python3

from google.cloud import pubsub

ps = pubsub.Client()
subscription = pubsub.subscription.Subscription('all', client=ps)
if not subscription.exists():
  subscription.create()

print("waiting for messages")
while True:
  with pubsub.subscription.AutoAck(subscription, max_messages=10) as ack:
    for ack_id, message in ack.items():
      print('msg-id: %s, ts: %s, %s' % (
          message.message_id, message.service_timestamp,
          message.data.decode('utf-8')))
```

if you do this you get:
```
Traceback (most recent call last):
  File "./suball.py", line 8, in <module>
    subscription.create()
  File "/usr/local/lib/python3.4/dist-packages/google/cloud/pubsub/subscription.py", line 185, in create
    self.full_name, self.topic.full_name, self.ack_deadline,
AttributeError: 'NoneType' object has no attribute 'full_name'
```

If you leave out the subscription.create() part your get:
```
Traceback (most recent call last):
  File "./suball.py", line 16, in <module>
    results = subscription.pull(return_immediately=True, max_messages=10)
  File "/usr/local/lib/python3.4/dist-packages/google/cloud/pubsub/subscription.py", line 328, in pull
    self.full_name, return_immediately, max_messages)
  File "/usr/local/lib/python3.4/dist-packages/google/cloud/pubsub/_gax.py", line 418, in subscription_pull
    raise NotFound(subscription_path)
google.cloud.exceptions.NotFound: 404 projects/<project>/subscriptions/all
```

Having a subscription for *all* topics would be nice to work around the performance issues with pulling from many topics.

**Comment by tseaver** [comment]
The back-end does not provide an API method for creating a subscription which binds to multiple topics.

Not passing a topic to the `Subscription` constructor (or passing `None`) [indicates that the topic for the subscription no longer exists](https://googlecloudplatform.github.io/google-cloud-python/stable/pubsub-subscription.html#google.cloud.pubsub.subscription.Subscription).  The only useful thing one can do with such an instance is to call its `delete()` method.

Creating a `Topic` instance with a non-existent name and then using it to create a `Subscription` instance is a pointless exercise:  its `create()` and `pull()` method will raise `NotFound` (the first for the non-existent topic, the second for the non-existent subscription).
