### ISSUE TITLE
[QUESTION] How does GAX send through a user agent for us?

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2349]
I realized this was worth asking since the helpers in #2286 don't get used by the APIs that use GAX.

**Comment by bjwatson** [comment]
This is something that @omaray and I have started discussing. We definitely need to figure out how this works for all combinations of google-cloud and GAPIC.

**Comment by dhermes** [comment]
For reference [this is our current implementation][1]

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/75835c867b4a9b979d5af421e257ccfa5de8f9c5/google/cloud/_helpers.py#L649-L653

**Comment by omaray** [comment]
Yes, Brian and I will come up with a solution for this that works across the board: with only auto-gen, with auto-gen + hanwritten in same package, auto-gen + handwritten in a different package, multiplexing gRPC and REST, etc.
