### ISSUE TITLE
Add JSON Documentation

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#2352]
This issue is for tracking the requirements, issues and solutions in generating JSON for the [gcloud-common Angular site](https://github.com/GoogleCloudPlatform/gcloud-common/blob/5a0d68a68a51df16e6fac3da2c84b02a3ae299e8/site/README.md).
## Known Requirements
- [ ] Extracting sphinx code examples and place them in `methods[{examples:[]}]`.
- [ ] Generate table of contents from sphinx toc. (index.rst).
- [ ] Class linking should be added. i.e. support :class:`gcloud.datastore._generated.query_pb2.Query`, this is partially done through [types.json](https://github.com/GoogleCloudPlatform/gcloud-common/blob/5a0d68a68a51df16e6fac3da2c84b02a3ae299e8/site/README.md#types).
- [ ] Source code links (base on relative repo path. i.e. `/google/cloud/datastore/client.py#L25`).
- [ ] "Getting Started" and "Guide" type pages need to be ported.
- [ ] Ensure that snippets are pulled in properly from `docs/*_snippets.py`.
- [ ] Turn on auto `gcloud-common/site` [deployments](https://github.com/GoogleCloudPlatform/gcloud-common/blob/5a0d68a68a51df16e6fac3da2c84b02a3ae299e8/deploy-docs.sh#L80).
## Discussions
- How much data is available in Writers https://groups.google.com/forum/#!topic/sphinx-users/-J1IOOBd-0g
## Resources
- http://www.arnebrodowski.de/blog/write-your-own-restructuredtext-writer.html
- https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/
- https://github.com/sphinx-doc/sphinx
- https://bitbucket.org/birkenfeld/sphinx-contrib

**Comment by dhermes** [comment]
@daspecster Did you mean to use `gcloud.datastore._generated.query_pb2.Query` as an example? Those generated files don't have any docs.

**Comment by daspecster** [comment]
Actually yes I did.

We would need to do one of two things with a reference to generated code.

1. Strip the directive and just not link it anywhere.
2. Just link it to that file/line in the repo (which is what I did/tried to do before since I generated JSON for everything under `gcloud/`, now `google/cloud`).

The bigger thing is generating `types.json`, I just used that one to illustrate this case.

**Comment by dhermes** [comment]
I am :-1: on linking into the source. Those `protoc` generated files are not meant for human eyes and are very nasty to look at.

**Comment by daspecster** [comment]
Sorry, I wasn't very clear on that.

Not linking to the source in this case(however that is a required feature for documented modules,classes,methods,params,variables. 

I was generating a JSON file for the _generated files as well since I was doing all python files under `gcloud` at the time. So the JSON representation was there, but not linked in the TOC. So it just means when there's a reference to one of those in a docstring, the `:class:` directive works as expected.

**Comment by dhermes** [comment]
@lukesneeringer is this project still in some long-term "TODO"?

**Comment by lukesneeringer** [comment]
I had no idea this was even a thing.

**Comment by lukesneeringer** [comment]
Denied.
