### ISSUE TITLE
[QUESTION] What is the point of `google.cloud.vision._fixtures`

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2356]
Sorry for being a little out of the loop on this one. 

Running `git grep _fixtures` it looks like `google.cloud.vision._fixtures` meant to be content in `unit_tests.vision._fixtures`

**Comment by daspecster** [comment]
Looks like I missed this when I was rebasing. #2362 should do the trick.

**Comment by dhermes** [comment]
Thanks
