### ISSUE TITLE
It should be possible to upload files in read+write mode

### ISSUE THREAD

**Issue by sebbacon** [GoogleCloudPlatform/google-cloud-python#2358]
`upload_from_file` insists that a file be opened with the binary flag.

However the, [test for this](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/1779/files#diff-c56e349a3e511bfabb4e8dfcfe686bc8R825) does not allow for files opened in mode `r+b`.

**Comment by daspecster** [comment]
Hello @sebbacon thanks for asking and for the PR!

Can I ask what scenario would you need to use read/write mode to read and then upload the file?
I'm probably just lacking in creativity, but it seems like you would only need to read the file to upload it.

Also, the `b` part is mostly for [Windows support](https://docs.python.org/2/tutorial/inputoutput.html#reading-and-writing-files).

**Comment by sebbacon** [comment]
Hi @daspecster! It's something of a edge case, but I want to write a temporary file and then upload it. It's useful to keep the same file handle open so I can use a context manager with tempfile. Something like this:

```python
with tempfile.TemporaryFile(mode='r+b') as csv_file:
    with open(source_file_name, 'rb') as source_file:
        writer = csv.writer(csv_file)
        reader = csv.reader(source_file)
        for row in reader:
            row = _transform(row)
            writer.writerow(row)
    job = table.upload_from_file(csv_file)
```

**Comment by tseaver** [comment]
Via #2360.  Thanks again to @sebbacon for the patch!
