### ISSUE TITLE
Dependency conflict when running `setup.py develop`

### ISSUE THREAD

**Issue by sebbacon** [GoogleCloudPlatform/google-cloud-python#2359]
When installing a development checkout per [the documentation](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/CONTRIBUTING.rst#using-a-development-checkout), there is a dependency conflict:

```bash
$ $VENV/bin/python setup.py develop
running develop
<snip>
Installed /tmp/google-cloud-python/lib/python2.7/site-packages/oauth2client-2.0.0-py2.7.egg
error: oauth2client 2.0.0 is installed but oauth2client<2.0.0,>=1.4.11 is required by set(['gapic-google-logging-v2', 'gapic-google-pubsub-v1'])

```

**Comment by daspecster** [comment]
Thanks for reporting @sebbacon!

I just tested this and it happened to me as well, except it pulled in `oauth2client 3.0.0`.

```python
error: oauth2client 3.0.0 is installed but oauth2client<2.0.0,>=1.4.11 is required by 
set(['gapic-google-logging-v2', 'gapic-google-pubsub-v1'])
```

@dhermes @bjwatson, we have `'oauth2client >= 2.0.1'` as a requirement.  Can gapic bump it's `oauth2client` versions?

**Comment by dhermes** [comment]
1. Definitely need to upgrade @bjwatson, as we're very quickly approaching 4.0 in `oauth2client` (finally getting rid of some really bad old stuff, e.g. `httplib2`). I'm happy to help upgrade.
1. See the discussion in #2316, essentially using development / editable mode won't really work any more with namespace packages. We should just remove that from `CONTRIBUTING`. @tseaver WDYT?

**Comment by bjwatson** [comment]
I ran into this also, and removed the upper-bound from our oauth2client dependencies. We'll review later and bound it to `>=3.0.0, <4.0.0dev`.

This issue should be fixed for now.

**Comment by daspecster** [comment]
Thanks @bjwatson!
I'm seeing a different but related issue now.

```bash
error: google-gax 0.14.1 is installed but google-gax<0.14.0,>=0.13.0
is required by set(['gapic-google-logging-v2', 'gapic-google-pubsub-v1'])
```

**Comment by daspecster** [comment]
@bjwatson, @dhermes just pointed out to me that `pip install -e .` doesn't throw this `google-gax` error. I'm not sure what the difference in handling between `setup.py` and `pip` are though.

**Comment by dhermes** [comment]
I was actually trying to point out that using `-e` should no longer be done. But that also seems true.

**Comment by daspecster** [comment]
@dhermes sorry yeah I was getting this for `python setup.py install` as well.

**Comment by bjwatson** [comment]
@daspecster @dhermes This is due to inconsistent bounds in https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/setup.py#L58

`gapic-google-* 0.9.x` packages are intended to work with `google-gax 0.13.x`. For example, see `setup.py` in [`gapic-google-pubsub-v1 0.9.3`](https://pypi.python.org/packages/d5/c1/e428db130b5858dfe53c5dcfe5666561b5c1b1a66a28162c322cc39021b1/gapic-google-pubsub-v1-0.9.3.tar.gz).

**Comment by bjwatson** [comment]
FYI, we are finalizing the `0.10.x` packages which will depend on `google-gax 0.14.x`: https://github.com/googleapis/api-client-staging/pull/24.

**Comment by dhermes** [comment]
Thanks @bjwatson. It'll be important for us to keep from cutting a release with the breakage. We will probably have 15 releases next week, of which 3 (`google-cloud-pubsub`, `google-cloud-logging` and `google-cloud`) will be impacted by this inconsistency.

**Comment by bjwatson** [comment]
@dhermes What can we do to help with this? `google-gax` and `gapic-google-*` are tightly coupled, so the version bounds make sense (to avoid surprises like we have had before with things spontaneously breaking), but I understand that you need to know what the pairing is. Is looking at the `setup.py` in any `gapic-google-*` of a particular 0.x version good enough to see what its matching version of `google-gax` is?

**Comment by dhermes** [comment]
@bjwatson It's been resolved as of the `iam` push to PyPI this morning.

**Comment by bjwatson** [comment]
Ok, great!
