### ISSUE TITLE
Error fetching results from a BigQuery asynchronous call in 0.19.0

### ISSUE THREAD

**Issue by georgegiovanni** [GoogleCloudPlatform/google-cloud-python#2368]
Referring to the [doc](https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-usage.html#querying-data-asynchronous), calling `QueryResults.fetch_data` raises an exception since `self.name` is `None`:

```python
if self.name is None:
    raise ValueError("Query not yet executed:  call 'run()'")
```

However, if `QueryResults.run` is called, an exception is also raised since `self._job` already exists:

```python
if self._job is not None:
    raise ValueError("Query job is already running.")
```

**Comment by tseaver** [comment]
@georgegiovanni Thanks for the report!
