### ISSUE TITLE
Automate the checking for proper licensing on files

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#2371]
From #2370.

> Should the script be extended to incorporate more than just Python files?

---

(From @dhermes): Relating to this

I wrote a [script](https://gist.github.com/dhermes/cdae55fa7eed44bd18492d2320afd020) for #2390 to check all the extensions we have (and extension-less files): The output is
- `.cmd`
- `.enc`
- `.gitignore`
- `.html`
- `.ico`
- `.in`
- `.ini`
- `.json`
- `.md`
- `.png`
- `.proto`
- `.ps1`
- `.py`
- `.rst`
- `.sample`
- `.sh`
- `.txt`
- `.yaml`
- `.yml`
- `.zip`

Not extensions:
- `.bigtable_v2` (not an extension, actually `Makefile.bigtable_v2`)
- `.coveragerc`
- `.datastore` (not an extension, actually `Makefile.datastore`)
- `LICENSE`
- `docs/Makefile`
- `scripts/pylintrc_default`

**Comment by dhermes** [comment]
ISTM this issue is about

> Maybe we should incorporate the script into our build rule to prevent files checked in with bad or missing license headers?

and the other point is just an also-ran.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
