### ISSUE TITLE
Add support for "external" tables

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#2372]
See the [`Table` resource field](https://cloud.google.com/bigquery/docs/reference/v2/tables#externalDataConfiguration) and the [federated data sources narrative docs](https://cloud.google.com/bigquery/federated-data-sources).

External tables can be one of:
- Files in Cloud Storage
- Google Sheets
- Bigtable tables
- Datastore backup sets

@jgeewax I'm pretty sure those fields were not in the resource when I first implement `v2` last August.  Are the back-end team pushing out new features without bumping the API version?

**Comment by lukesneeringer** [comment]
@tswast I need guidance on this one. Can this be either moved to an overall BigQuery feature doc (either in the pre-beta or post-beta section) or closed if no longer needed?

**Comment by tswast** [comment]
Should be moved to the doc probably. Definitely still relevant.

**Comment by gealvare** [comment]
+1 Definitely still relevant.

**Comment by LFischerstrom** [comment]
I manage to query Avro by doing this:
```
class QueryJob(bigquery.query.QueryJob):    
    def _build_resource(self):
        return self._properties
```

**Comment by tswast** [comment]
Fixed by https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4193, to be merged to master in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4245.
