### ISSUE TITLE
Expose "streamingBuffer" for tables

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#2374]
See:
- https://cloud.google.com/bigquery/streaming-data-into-bigquery#dataavailability
- https://cloud.google.com/bigquery/docs/reference/v2/tables#streamingBuffer

**Comment by 1mentat** [comment]
I'm interested in this feature. Going to have to use the older python API just for this.

**Comment by tseaver** [comment]
@1mentat:  as a workaround until the feature lands, you could peek into the `_properties` attribute of the table.  E.g.:

```python
    table.reload()
    while table._properties.get('streamingBuffer') is not None:
        print('Oldest entry time: %g' % (
            table._properties['streamingBuffer']['oldestEntryTime'],))
        table.reload()
```

**Comment by 1mentat** [comment]
@tseaver ah, great, thanks so much for that!

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
