### ISSUE TITLE
'_AsyncQuery.cancel' fails to update from returned resource

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#2377]
E.g.:

```python
Traceback (most recent call last):
  File ...
    job.cancel()
  File ".../google/cloud/bigquery/job.py", line 378, in cancel
    self._set_properties(api_response)
  File ".../google/cloud/bigquery/job.py", line 262, in _set_properties
    self._scrub_local_properties(cleaned)
  File ".../google/cloud/bigquery/job.py", line 1050, in _scrub_local_properties
    configuration = cleaned['configuration']['query']
KeyError: 'configuration'
```

The [docs for `job.cancel`](https://cloud.google.com/bigquery/docs/reference/v2/jobs/cancel#response) show that the job resource is in a `job` subkey of the response.

**Comment by dhermes** [comment]
@tseaver Germane to this change, I've run the following before to get a sense of our actual usage of `streaming`:

```python
nosetests system_tests/storage.py system_tests/bigquery.py \
  --with-coverage  \
  --cover-branches  \
  --cover-tests  \
  --cover-package=gcloud.streaming  \
  --cover-package=gcloud.bigquery  \
  --cover-package=gcloud.storage  \
  --nocapture
```

Could be worthwhile to do it and see what code paths we aren't testing against the backend?

(**NOTE**: I'm aware this is using the old `gcloud` package and `nosetests`, sorry I am in a hurry and didn't update for the `py.test` equivalent.)

**Comment by tseaver** [comment]
@dhermes I don't think that is germane to this PR, which doesn't mess with streaming at all.  Maybe you meant #1431?

**Comment by dhermes** [comment]
No I just meant that if you got a sense for lines uncovered during system tests then an error like this would be detectable. The streaming bit was just an example so you could do the same locally.

Essentially this error is due to the fact that our code and unit tests make a bad assumption about the payload.

**Comment by tseaver** [comment]
OK.  We don't have any system test which exercises `_AsyncJob.cancel()`:  I found the problem while reproducing #2368.

I'm not convinced that we need to get to 100% coverage for system tests, but we should at least have "garden path" coverage for all the API requests.

**Comment by dhermes** [comment]
Ha. Never heard "garden path" before! I agree having full coverage in system tests isn't necessary (or possible, since error cases may never occur), just wanted to share a script I had used before
