### ISSUE TITLE
Pub/Sub Topic batch auto commit?

### ISSUE THREAD

**Issue by tcroiset** [GoogleCloudPlatform/google-cloud-python#2382]
Hi,
I would appreciate a batch to auto commit when it reaches its max number of messages.
Does that make sense?

bests,

**Comment by daspecster** [comment]
By committing do you mean publishing a message?

```python
    with topic.batch() as batch:
        batch.publish(PAYLOAD1)
        batch.publish(PAYLOAD2, extra=EXTRA)
```

From https://googlecloudplatform.github.io/google-cloud-python/stable/pubsub-usage.html#publish-messages-to-a-topic

@tseaver could you do something like this?
```python
    with topic.batch() as batch:
        for msg in xrange(100):
            if len(batch.messages) > 10:
                 batch.commit()
            batch.publish(PAYLOAD1)
```

**Comment by dhermes** [comment]
@tcroiset It makes sense, though in this case you probably would rather use it outside of a context manager, e.g.

```python
batch = topic.batch()
for msg in messages:
    batch.publish(msg)

batch.commit()
```

**NOTE**: There is no `batch.begin()` to call, as can be seen by the [context manager][1] implementation.

**NOTE**: Calling `batch.commit()` at the end is to do any clean-up if necessary, but if there are no unpublished messages `commit()` will [do nothing][2].

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/b60d498b8dbf3e548de1a9fd196ac9cd6d077f41/google/cloud/pubsub/topic.py#L431-L432
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/b60d498b8dbf3e548de1a9fd196ac9cd6d077f41/google/cloud/pubsub/topic.py#L463-L464

**Comment by tseaver** [comment]
ISTM that @tcroiset was asking for something like:

```python
from google.cloud.pubsub.topic import Batch

class MaxMessagesBatch(Batch):

    def __init__(self, topic, client, max_messages):
        super(MaxMessagesBatch, self).__init__(topic, client)
        self._max_messages = max_messages

    def publish(self, message, **attrs):
        super(MaxMessagesBatch, self).publish(message, **attrs)
        if len(self.messages) >= self._max_messages:
            self.commit()

```

**Comment by tcroiset** [comment]
Indeed.

If i'm not mistaken, there's a limit (1000?) on the api side for the number of messages published in a single call.
I have implemented a class like MaxMessagesBatch but I was thinking it could be directly implemented in gcloud.

**Comment by tseaver** [comment]
@tcroiset FWIW the API docs ([JSON](https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.topics/publish) | [gRPC](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#google.pubsub.v1.PublishRequest)) don't mention any limit.

**Comment by tcroiset** [comment]
@tseaver It is mentioned here: https://cloud.google.com/pubsub/quotas

> Publish request
> Total size must be no more than 10MB .
> Must contain no more than 1,000 messages.
