### ISSUE TITLE
storage.bucket.Bucket.copy_blob missing option to preserve ACL

### ISSUE THREAD

**Issue by pdknsk** [GoogleCloudPlatform/google-cloud-python#2389]
[Unlike](https://cloud.google.com/storage/docs/gsutil/commands/cp) ```gsutil```.

> Note that by default, the gsutil cp command does not copy the object ACL to the new object, and instead will use the default bucket ACL. You can override this behavior with the -p option.

**Comment by pdknsk** [comment]
```Diff
--- a/bucket.py
+++ b/bucket.py
@@ -431,7 +431,7 @@
                     raise
 
     def copy_blob(self, blob, destination_bucket, new_name=None,
-                  client=None):
+                  client=None, preserve_acl=False):
         """Copy the given blob to the given bucket, optionally with a new name.
 
         :type blob: :class:`gcloud.storage.blob.Blob`
@@ -459,6 +459,8 @@
         copy_result = client.connection.api_request(
             method='POST', path=api_path, _target_object=new_blob)
         new_blob._set_properties(copy_result)
+        if preserve_acl is True:
+            new_blob.acl.save(blob.acl)
         return new_blob
 
     def rename_blob(self, blob, new_name, client=None):

```

**Comment by daspecster** [comment]
@pdknsk thanks for letting us know!

I have a PR for this at #2409.

**Comment by pdknsk** [comment]
I've noticed that ```acl.save``` issues a separate request. Below is a better patch that sets the ACL with the same request.
```diff
--- a/bucket.py
+++ b/bucket.py
@@ -431,7 +431,7 @@
                     raise
 
     def copy_blob(self, blob, destination_bucket, new_name=None,
-                  client=None):
+                  client=None, preserve_acl=False):
         """Copy the given blob to the given bucket, optionally with a new name.
 
         :type blob: :class:`gcloud.storage.blob.Blob`
@@ -456,8 +456,12 @@
             new_name = blob.name
         new_blob = Blob(bucket=destination_bucket, name=new_name)
         api_path = blob.path + '/copyTo' + new_blob.path
+        data = None
+        if preserve_acl:
+            data = blob._properties
+            data.update({'acl': list(blob.acl)})
         copy_result = client.connection.api_request(
-            method='POST', path=api_path, _target_object=new_blob)
+            method='POST', path=api_path, _target_object=new_blob, data=data)
         new_blob._set_properties(copy_result)
         return new_blob
 
```

**Comment by tseaver** [comment]
@pdknsk The new patch saves an API call only if the source blob's `_properties` and its `acl` are already loaded:  if `_properties` aren't loaded, then it would zero them out in the copied blob, while `list(blob.acl)` will actually trigger an API request if the `acl` isn't loaded.

**Comment by pdknsk** [comment]
Ah right, I missed some of those finer details.

I don't understand how ```_properties``` cannot be loaded. I think only when you manually make a ```Blob```, with the same name as the file to be copied, and then use it to copy. In that case, you get what you asked for (even though it may not necessarily be what you wanted.)

I think there is still in advantage in only issuing a single request, for the case of a connection failure between both requests.
