### ISSUE TITLE
[QUESTION] What values should we use for our user agent?

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2391]
This came up in #2367. In [node](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/d24209a660706b70fee7d18ece9ca7a26d2f0403/packages/common/src/util.js#L624-L630), they use `gcloud-node-{SERVICE}/{SERVICE_VERSION}`. So for example, [bigtable](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/d24209a660706b70fee7d18ece9ca7a26d2f0403/packages/bigtable/package.json#L2-L3) would be `gcloud-node-bigtable/0.3.1`.

/cc @callmehiphop @stephenplusplus

**Comment by jonparrott** [comment]
google-api-python client [uses](https://github.com/google/google-api-python-client/blob/c6425a00e3c16268b101703c45f2a3e53154a372/googleapiclient/model.py#L147) `google-api-python-client/{version} (gzip)`, we should use similar:

```python
google-cloud-python-{service}/{version} ({transport})
```

``transport`` could, for example, be ``grpc``, ``protobuf-over-http``, ``json``.

**Comment by dhermes** [comment]
@jonparrott See https://github.com/GoogleCloudPlatform/gcloud-common/issues/179#issuecomment-244605266 and https://github.com/GoogleCloudPlatform/gcloud-common/issues/179#issuecomment-244967800

**Comment by tseaver** [comment]
Should we update the `USER_AGENT` header to include the new `__version__` headers added in #3046?

**Comment by dhermes** [comment]
@lukesneeringer Seemed to indicate that it wasn't as relevant. It might be a non-trivial code change? I'm not sure if the individual packages allow over-riding the user agent. At the very least it'd be a breaking change if we moved from `self.USER_AGENT` to a key-value pair in `_EXTRA_HEADERS`.

**Comment by lukesneeringer** [comment]
Doing nothing is fine here.

**Comment by lukesneeringer** [comment]
Also, oh hey, I bet this ticket is close-able. :-) #3046 pretty clearly supercedes it.

Closing. Re-open if there are any concerns.
