### ISSUE TITLE
Figure out a way to share common pieces of `setup.py` across subpackages

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2395]
See https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2367#discussion_r80120973

**Comment by daspecster** [comment]
I _may_ have figured out a solution to this.

I very well could be wrong on the causation of this solution but it appears that setuptools will only follow symlinks of directories [Commit 1](https://github.com/pypa/setuptools/commit/606b8fb55059ad29d1d31709686f43f17e03642c#diff-6b59155d3acbddf6010c0f20482d4eea), [Commit 2](https://github.com/pypa/setuptools/commit/439f6f846869c8266954adfedad232933caaa813#diff-6b59155d3acbddf6010c0f20482d4eea).

See #2439 for an example.
