### ISSUE TITLE
ReadTheDocs broken by moving subpackages

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2405]
https://readthedocs.org/projects/google-cloud-python/builds/4436621/

**Comment by dhermes** [comment]
1.  Succeeds

    ```
    python -mvirtualenv \
      --no-site-packages \
      --no-download \
      .../google-cloud-python/envs/latest
    ```

1.  Succeeds

    ```
    python .../pip install \
      --use-wheel \
      -U \
      --cache-dir .../google-cloud-python/.cache/pip \
      sphinx==1.3.5 Pygments==2.1.3 setuptools==20.1.1 docutils==0.12
      mkdocs==0.15.0 mock==1.0.1 pillow==2.6.1
      git+https://github.com/rtfd/readthedocs-sphinx-ext.git@0.6-alpha#egg=readthedocs-sphinx-ext
      sphinx-rtd-theme==0.1.9 alabaster>=0.7,<0.8,!=0.7.5
      commonmark==0.5.4 recommonmark==0.1.1
    ```

1.  Fails

    ```
    python setup.py install --force
    ```

Maybe we can get away specifying dependencies with a [`git+...`][1] or with a relative directory in `requirements.txt`

[1]: https://pip.readthedocs.io/en/stable/reference/pip_install/#git

**Comment by dhermes** [comment]
Mostly fixed by #2444 and #2445. The remaining issue is that we depend on `google-gax 0.14.1` in `logging` and `pubsub` but `google-gax<0.14.0,>=0.13.0` is required by `gapic-google-logging-v2` and `gapic-google-pubsub-v1` (both 0.9.x).

@bjwatson hopes to have 0.10.0 of each released soon.

If the release doesn't happen by this afternoon, I'll just revert #2388 for the purposes of this release.

**Comment by dhermes** [comment]
Blerg! https://readthedocs.org/projects/google-cloud-python/builds/4449511/ b0rken because

```
error: oauth2client 2.2.0 is installed but oauth2client<4.0.0dev,>=3.0.0
is required by
set(['gapic-google-logging-v2', 'grpc-google-logging-v2',
     'gapic-google-pubsub-v1', 'grpc-google-pubsub-v1'])
```

**Comment by dhermes** [comment]
Starting to see some really strange RTD failures that seem to be different than the referenced HEAD commit (94a596e643572aa3875082baf921f866d52cc0c3):

- https://readthedocs.org/projects/google-cloud-python/builds/4449568/ (grpc-google-iam-v1 missing, never heard of it)
- https://readthedocs.org/projects/google-cloud-python/builds/4449565/ (google-gax<0.14.0,>=0.13.0 is required, though not true for latest versions)
- https://readthedocs.org/projects/google-cloud-python/builds/4449546/ (oauth2client 2.2.0 somehow gets installed)

**Comment by dhermes** [comment]
[This][1] at least shows that `grpc-google-iam-v1` comes from `gapic-google-pubsub-v1`, so that is comforting. But then the [`oauth2client`][2] upper bound on that package contradicts the one from `gapic-google-pubsub-v1`.

[1]: https://github.com/googleapis/api-client-staging/blob/82ffe47ae78e6a23ab02ee9e3de097cec37a5639/generated/python/gapic-google-pubsub-v1/setup.py#L15
[2]: https://github.com/googleapis/api-client-staging/blob/82ffe47ae78e6a23ab02ee9e3de097cec37a5639/generated/python/grpc-google-iam-v1/setup.py#L13

**Comment by dhermes** [comment]
Pushed a fake branch with a fake fix to see if this will work: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/fake-out-rtd

It did: https://readthedocs.org/projects/google-cloud-python/builds/4449660/

**Comment by bjwatson** [comment]
@landrito Can you push an updated version of Python `grpc-google-iam-v1` with the bounds currently in `packman`? (e.g. `oauth2client >=3.0.0, <4.0.0`)

**Comment by Landrito** [comment]
Will do!

**Comment by Landrito** [comment]
[Pushed](https://pypi.python.org/pypi/grpc-google-iam-v1)

**Comment by Landrito** [comment]
[Pushed](https://pypi.python.org/pypi/grpc-google-iam-v1/0.10.1)

**Comment by dhermes** [comment]
Thanks!
