### ISSUE TITLE
Implement multi-row mutations for python Bigtable

### ISSUE THREAD

**Issue by destijl** [GoogleCloudPlatform/google-cloud-python#2411]
It would be great if you could add multi-row mutations to the Bigtable python client library. AFAICS it doesn't exist yet.

The RPC API supports it:
https://cloud.google.com/bigtable/docs/reference/data/rpc/google.bigtable.v2#mutaterowsrequest

It just isn't implemented for python. The first use case I ran into is I have a bunch of rows to delete and a want to make a single RPC to do that, but I'm sure there will be more.

**Comment by tseaver** [comment]
See #1546.

**Comment by destijl** [comment]
Thanks, I'm not using happybase but the context manager approach suggested in that bug looks good.

**Comment by garye** [comment]
Good news: @skyfox is currently working on implementing this

**Comment by skyfox** [comment]
n my current solution, I added mutation class and the new multi rows mutation function as a method of the Table class.
Pros: 1) Easy to use - mutations can be specified outside of rows; 2) No need to construct Row instances. Original RPC call works on a level of row keys.
Cons: 1) new abstraction 2) The Row class should be refactored and work with mutations 3) Mutations for every row should be the same.

Alternative solution. Same new table method. In a method body - extract rows keys/mutations and build request. 
Pros: 1) No new abstractions
Cons: 1) Extracting row key from row object 2) Not so easy to use - Rows should be constructed first.

The second way, from my point of view, is closer to the current  implementation and would prefer to extended Row class a little. Even with a small overhead for extracting keys from rows.

Any cons?

**Comment by garye** [comment]
@tseaver , any thoughts on this?

**Comment by skyfox** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3401

**Comment by mbrukman** [comment]
@garye, @skyfox: since PR #3401 was merged, can we close this issue, or is there more work left?

**Comment by tseaver** [comment]
AFAICT, the merge of #3401 should have closed this issue.
