### ISSUE TITLE
No installation links for installing from source

### ISSUE THREAD

**Issue by emilyhoughkovacs** [GoogleCloudPlatform/google-cloud-python#2437]
I followed instructions to download from source [here](https://googlecloudplatform.github.io/google-cloud-python/stable/) and received the error:

`No local packages or working download links found for google-cloud-storage`
`error: Could not find suitable distribution for Requirement.parse('google-cloud-storage')`
which you can verify on
https://pypi.python.org/simple/google-cloud-storage/ which it was it was trying to read.

I think it should be here instead: [https://pypi.python.org/pypi/google-cloud](https://pypi.python.org/pypi/google-cloud)

**Comment by dhermes** [comment]
@emilyhoughkovacs Thanks for filing! We'll definitely need to update that document.

That's some really bad timing. We are in the middle of a crazy rename / re-packaging sprint (#2404) and that won't quite work that way.

The "easiest" way to install from source right now would be to use `tox`:


```
tox -e py27 --recreate --notest
```

and then  `source .tox/py27/bin/activate` to activate the virtual environment where everything has been installed.

**Comment by dhermes** [comment]
@emilyhoughkovacs Is this still relevant after #2440 has been filed?

**Comment by emilyhoughkovacs** [comment]
Not to me but I filed the ticket just so you would be aware of it for anyone trying to use source

**Comment by dhermes** [comment]
Ah right. I still need to update that instruction.
