### ISSUE TITLE
Manually cut releases of each package

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2441]
@tseaver Can you sign off on my current plan (mostly run from the command line)

1.  First, upgrade all packages from `0.20dev` to `0.20.0` and solidify bounds for dependencies.
1.  Then get a fresh checkout

    ```
    mkdir ${HOME}/tmp-release
    cd ${HOME}/tmp-release
    git clone https://github.com/GoogleCloudPlatform/google-cloud-python
    ```
1.  Make sure I have `gcloudpypi` credentials in `${HOME}/.pypirc`
1.  Then go into each package and do a release

    ```
    # core
    cd ${HOME}/tmp-release/google-cloud-python/core
    python setup.py sdist bdist_wheel
    twine upload dist/*
    # Similar for the 14 packages: 
    # bigquery, bigtable, datastore, dns, error_reporting, language,
    # logging, monitoring, pubsub, resource_manager, storage,
    # translate, vision
    ```

    **NOTE**: `speech` is not in here, it isn't ready to release
1.  Then release the umbrella package

    ```
    cd ${HOME}/tmp-release/google-cloud-python
    python setup.py sdist bdist_wheel
    twine upload dist/*    
    ```

**Comment by tseaver** [comment]
Confirming discussion offline:  this plan looks good to me.

**Comment by daspecster** [comment]
@dhermes @tseaver did you want streaming in Speech before releasing it?

**Comment by dhermes** [comment]
@daspecster See above:

> **NOTE**: `speech` is not in here, it isn't ready to release

**Comment by dhermes** [comment]
Thanks @tseaver. Just waiting to hear from @bjwatson about 0.10.x versions of the gapic pieces.

https://pypi.python.org/pypi/gapic-google-pubsub-v1
https://pypi.python.org/pypi/gapic-google-logging-v2

**Comment by daspecster** [comment]
@dhermes that's what I was responding too. Just curious what the checkboxes for speech were on this.

**Comment by bjwatson** [comment]
@daspecster Speech should be today. We're actually going to cut 0.11.0 releases of everything, but it shouldn't affect you apart from bumping the version bounds. This is due to refining our model for how to represent enums, which is a new feature in Python GAPIC, so I'm guessing you're not using our enums yet anyway.

**Comment by dhermes** [comment]
Just pushed the [`umbrella-0.20.0`][1] tag at 5a0e492b4098fe3c2df4d1821a432cbaee15edd6. Working on release notes now, but will do the upload first.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/umbrella-0.20.0

**Comment by dhermes** [comment]
@tseaver @jonparrott Everything went really well, **except** the umbrella package:

```
$ twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Uploading google_cloud-0.20.0-cp27-none-linux_x86_64.whl
[================================] 17242/17242 - 00:00:02
HTTPError: 400 Client Error: Binary wheel 'google_cloud-0.20.0-cp27-none-linux_x86_64.whl' has an unsupported platform tag 'linux_x86_64'. for
url: https://upload.pypi.org/legacy/
$ rm dist/google_cloud-0.20.0-cp27-none-linux_x86_64.whl
rm: remove regular file 'dist/google_cloud-0.20.0-cp27-none-linux_x86_64.whl'? y
$ twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Uploading google-cloud-0.20.0.tar.gz
[================================] 14013/14013 - 00:00:02
```

Any idea why it generated `cp27-none-linux_x86_64.whl` instead of `py2.py3-none-any.whl`?

**Comment by dhermes** [comment]
Here are all the releases just pushed at 5a0e492b4098fe3c2df4d1821a432cbaee15edd6

https://pypi.python.org/pypi/google-cloud-core/0.20.0
https://pypi.python.org/pypi/google-cloud-bigquery/0.20.0
https://pypi.python.org/pypi/google-cloud-bigtable/0.20.0
https://pypi.python.org/pypi/google-cloud-pubsub/0.20.0
https://pypi.python.org/pypi/google-cloud-storage/0.20.0
https://pypi.python.org/pypi/google-cloud-datastore/0.20.0
https://pypi.python.org/pypi/google-cloud-logging/0.20.0
https://pypi.python.org/pypi/google-cloud-monitoring/0.20.0
https://pypi.python.org/pypi/google-cloud-language/0.20.0
https://pypi.python.org/pypi/google-cloud-dns/0.20.0
https://pypi.python.org/pypi/google-cloud-error-reporting/0.20.0
https://pypi.python.org/pypi/google-cloud-resource-manager/0.20.0
https://pypi.python.org/pypi/google-cloud-translate/0.20.0
https://pypi.python.org/pypi/google-cloud-vision/0.20.0
https://pypi.python.org/pypi/google-cloud/0.20.0

I'm now going to make a fake `google-cloud-natural-language` package to shadow `google-cloud-language`

**Comment by dhermes** [comment]
I just used https://gist.github.com/dhermes/a4e097f2f80fd490b256fc3aa2b4a46b to generate https://pypi.python.org/pypi/google-cloud-natural-language/0.20.0

This had the same problem of `cp27-none-linux_x86_64.whl`

**Comment by dhermes** [comment]
It's worth noting that the following PRs were left out of the release notes:

#2455, #2453, #2452, #2499, #2445, #2444, #2351, #2362, #2355, #2363, #2364, #2369, #2380, #2381, #2370, #2388, #2386, #2387, #2424, #2392, #2393, #2396, #2394, #2399, #2407, #2403, #2408, #2412, #1702, #2449

In addition, the few Speech related PRs were also left out, since `speech` is half-baked and was not included in the release:

#2344, #2376, #2426, #2438

**Comment by dhermes** [comment]
Figured out the wheel issue. On my machine I had `wheel==0.24.0`, but the latest is `0.29.0`. Tada!
