### ISSUE TITLE
Can not install google-cloud-monitoring via pip

### ISSUE THREAD

**Issue by liujiongxin** [GoogleCloudPlatform/google-cloud-python#2448]
_sudo pip install --upgrade google-cloud-monitoring_ returns error:
Could not find a version that satisfies the requirement google-cloud-monitoring (from versions: )
No matching distribution found for google-cloud-monitoring

I noticed that there was file moving yesterday, not sure if it's related to this issue.

**Comment by dhermes** [comment]
We have yet to make a release to `google-cloud-monitoring`, sorry you got caught in the weird transitional state this library is in. I plan on cutting a release some time today.

Follow along in #2441.

Closing this since it is equivalent to #2441 (and the known issue, that release is needed ASAP)

**Comment by dhermes** [comment]
Hooray!

https://pypi.python.org/pypi/google-cloud-monitoring
