### ISSUE TITLE
Datastore API key.Key.id() throws TypeError: 'long' object is not callable

### ISSUE THREAD

**Issue by theoschao** [GoogleCloudPlatform/google-cloud-python#2456]
As part of a datastore query, I get back entities that have a KeyProperty.  When trying to call a .id() on the KeyProperty, I get the following TypeError thrown:

TypeError: 'long' object is not callable

Upon examining the particular key, I see this (obfuscated):

<Key[{'kind': u'xxxx', 'id': 1234567890L}], project=xxxx>

Not sure exactly where the TypeError is being thrown, but it looks like the 'id' is being interpreted as a long somehow, when it's actually a standard integer.

I've had to workaround this by doing the following:
Key._path[0].get('id')

**Comment by dhermes** [comment]
@theoschao Can you give a snippet of the code you're using to invoke the error? A Key Property may come from the low-level protobuf interface, but it's unclear if you've used that or the more user-friendly high-level interface.

**Comment by theoschao** [comment]
sure, I've stripped the code down to what's relevant to understand:

`
from google.cloud import datastore
from oauth2client.service_account import ServiceAccountCredentials

svc_account_credentials = ServiceAccountCredentials._from_p12_keyfile_contents(
  service_account_email=self.client_email,
  private_key_pkcs12=self.private_key_string,
  scopes=datastore.SCOPE
)

client = datastore.Client(credentials=svc_account_credentials, project='xxx')

# Let's say Account has a KeyProperty named kprop
query_obj = client.query(kind='Account')

query_iterator = query_obj.fetch(limit=1000)
# btw, it's unfortunate that we can only get up to 300 results per batch of results now :(
entities, more_results, next_cursor = query_iterator.next_page()

for entity in entities:
  for field in entity:
    # this is one of a few cases written to handle different data types, assume getType() gets the type of a given property
    if getType(field) == KEYPROPERTY:
      value = field.id()  # see https://googlecloudplatform.github.io/google-cloud-python/stable/datastore-keys.html#google.cloud.datastore.key.Key.id
  
`
it's at the value = field.id() line that I see this error, and it's here where I replaced it with value = field._path[0].get('id') from looking at the source code

**Comment by dhermes** [comment]
What is `KEYPROPERTY`? ISTM that it is just a [`Key`][1]. If that's the case, [`id` is a `@property`][2] which means you need to call `field.id` not `field.id()`. Since a `@property`, `field.id` will return an integer, which can't be called. For example:

```python
>>> n = 1
>>> n()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object is not callable
>>>
>>> n = 1L
>>> n()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'long' object is not callable
```

Please re-open if I'm mistaken.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/5a0e492b4098fe3c2df4d1821a432cbaee15edd6/datastore/google/cloud/datastore/key.py#L23
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/5a0e492b4098fe3c2df4d1821a432cbaee15edd6/datastore/google/cloud/datastore/key.py#L306

**Comment by theoschao** [comment]
@dhermes  bingo! you're right. I was in the process of upgrading our gcloud library from a super old version (0.3.0) to something more recent and it looks like that @property decorator was added and I hadn't noticed.  Thanks!

**Comment by dhermes** [comment]
Sure thing!
