### ISSUE TITLE
Split up 'system_tests/' by package?

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#2458]
As already done with `unit_tests/`.

This would require moving the "importable" code into a shared location (maybe a new `core/google/cloud/_testing` package?), and refactoring the current driver (maybe into a `console_script` in `core`?).

**Comment by dhermes** [comment]
I have this in #2404 but no associated issue. I think it'd be best just to have a local package (`setup.py` and all) for system test helpers
