### ISSUE TITLE
Datastore Query should work when no Client is passed

### ISSUE THREAD

**Issue by vikkyrk** [GoogleCloudPlatform/google-cloud-python#2465]
We are trying to use gcloud-python Datastore in Apache Beam python SDK to provide a Datastore connector. For our use case, the user will just provide a 'com.google.datastore.query.Query' and the connector will take care of reading data from Datastore. We do not want the user to deal with 'datastore.Client' directly. The way we plan to implement is something like this,

User Pseudo Code

``` python
project = 'myproject'
namespace = 'mynamespace'
query = Query(client=None, project, namespace )
query.add_filter(...)
DatastoreConnector.read(query, project, namespace)
```

SDK Connector Pseudo Code

``` python
def DatastoreConnector.read(query, project, namespace):
  client = datastore.Client(project, namespace)
  return query.fetch(client=client)
```

Note that we are passing the client to the query at fetch time. All this works fine when the `namespace` is not empty but when `namespace` is `None`, the code fails with an exception, `AttributeError: 'NoneType' object has no attribute 'namespace'`. This is because the `Query` tries to get the `namespace` from `Client` even though `Client` is empty. Specifically fails [here](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/938ac216646c62acab8e5aef7dab33c911dbef1b/datastore/google/cloud/datastore/query.py#L89) and [here](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/938ac216646c62acab8e5aef7dab33c911dbef1b/datastore/google/cloud/datastore/query.py#L115)

Could these checks be changed to,

```
if not namespace:
  self._namespace = namespace
elif not client:
  self._namespace = client.namespace
```

Or is there any workaround for us?

**Comment by dhermes** [comment]
@vikkyrk It's something we had never considered. I suppose it would be just fine. Rather than using the `if` statement it'd be easier to just use

```python
getattr(client, 'namespace', None)
```

in place of `client.namespace`.

Would you like to send a patch? (It'll need one or two new unit tests but not much else.)

**Comment by vikkyrk** [comment]
@dhermes PTAL, https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2467
