### ISSUE TITLE
Change title of tab from google-cloud to google-cloud-python

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-python#2470]
When opening the [Client Library Reference page for Python](https://googlecloudplatform.github.io/google-cloud-python/) we can notice that the tab title says `google-cloud`:

![image](https://cloud.githubusercontent.com/assets/6609430/18977400/ce1f8b36-866e-11e6-9267-c79b7d495e84.png)

Even though that's not wrong at all - we are however seeing a mix where some languages use `google-cloud` and others `google-cloud-{lang}`. 

So let's stay consistent and stick to one approach. 

[Expected Result]
Let's change the tab title to `google-cloud-python` so that users can know exactly that it's the Python docs.

**Comment by dhermes** [comment]
On it

**Comment by dhermes** [comment]
FWIW the "title of the tab" isn't a thing, in HTML it's the `<title>` tag which goes in the `<head>` section of the page.
