### ISSUE TITLE
'Table.insert_data()' fails when schema is not loaded

### ISSUE THREAD

**Issue by rishsriv** [GoogleCloudPlatform/google-cloud-python#2472]
I tried to insert data using the google cloud python client but seem to get rows where every field has a null value. I used the [code in the latest documentation](https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-usage.html).

Using Debian 7.11 with Python 2.7.3 and google-cloud-python 0.20.

**Comment by rishsriv** [comment]
For clarity: [this stackoverflow question](http://stackoverflow.com/questions/39678654/uploading-empty-data-to-bigquery-using-gcloud-python) refers to the same problem.

If I insert rows using the following code:

```
client = bigquery.Client()
dataset = client.dataset('test')
table = dataset.table("test_table")
rows = [("foo", "bar"), ("foo2", "bar2")]
result = table.insert_data(rows)
```

and then query the latest upload, I get 

```
[(None, None), (None, None)]
```

**Comment by dhermes** [comment]
@rishsriv Thanks for filing!

**Comment by tseaver** [comment]
@rishsriv We have a working [system test which exercises `Table.insert_data`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/938ac216646c62acab8e5aef7dab33c911dbef1b/system_tests/bigquery.py#L263).  Does that example help?

Do the dataset and table already exist before your start?  If so, does the table's schema match the data you are inserting?

**Comment by rishsriv** [comment]
@tseaver Yes they do. And yes, the table's schema matches the data exactly.

**Comment by tseaver** [comment]
```python
>>> from google.cloud.bigquery import Client
>>> from google.cloud.bigquery.schema import SchemaField
>>> client = Client()
>>> dataset = client.dataset('gcp_2472')
>>> dataset.exists()
False
>>> dataset.create()
>>> left = SchemaField('left', 'STRING', 'REQUIRED')
>>> right = SchemaField('right', 'STRING', 'REQUIRED')
>>> table = dataset.table('test_table', schema=[left, right])
>>> table.create()
>>> rows = [("foo", "bar"), ("foo2", "bar2")]
>>> table.insert_data(rows); fetched, total, token = table.fetch_data()
[]
>>> fetched
[]
>>> fetched, total, token = table.fetch_data()
>>> fetched
[('foo', 'bar'), ('foo2', 'bar2')]
```
So, the rows weren't present at all for me when querying immediately after the call to `insert_data`, but they became available shortly thereafter.  The [BigQuery docs](https://cloud.google.com/bigquery/streaming-data-into-bigquery#dataavailability) say:

> Streamed data is available for real-time analysis within a few seconds of the first streaming insertion into a table.
>
> Data can take up to 90 minutes to become available for copy and export operations

**Comment by rishsriv** [comment]
@tseaver Thank you for the super quick response. The problem for me was that the response (`fetched`) was not an empty list, but rather a list like this 
```
[(None, None), (None, None)]
```

Will try again to make sure I did not do something wrong.

**Comment by rishsriv** [comment]
@tseaver: Resolved! I had created the table using the webview, and simply used `table = dataset.table("test_table")` when declaring the table.

Explicitly declaring the schema (i.e., using the following lines)
```
left = SchemaField('left', 'STRING', 'REQUIRED')
right = SchemaField('right', 'STRING', 'REQUIRED')
table = dataset.table('test_table', schema=[left, right])
```

helped fix the problem.

Thank you very much for your time.

**Comment by tseaver** [comment]
@rishsriv In your case, calling `table.reload()` (to fetch the schema) before `table.insert_data(rows)` would have worked as well. I have reopened the issue because `Table.insert_rows` should detect that `self._schema` is not populated, and raise an exception.

**Comment by patitonav** [comment]
Hello, i have a question :  Inserting ('foo', 'bar'), ('foo2', 'bar2') is ok, but when you want to insert a Json File, it doesnt work.

`with open('infobae.json') as json_data:
    dic = json.load(json_data)
    json_str = json.dumps(dic)
    errors = table.insert_data([json_data])`

BQ doesnt recognize the JSON structure?

Thanks

**Comment by dhermes** [comment]
@patitonav Can you

1. [File a new issue][1]
1. Include a stacktrace (and some setup code)

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/new
