### ISSUE TITLE
Environment Variable `GAE_APPENGINE_HOSTNAME` not working

### ISSUE THREAD

**Issue by travisoneill** [GoogleCloudPlatform/google-cloud-python#2477]
Points to an empty string not `your-app-id.appspot.com` as stated in the docs: https://cloud.google.com/appengine/docs/flexible/python/runtime#environment_variables

**Comment by tseaver** [comment]
@travisoneill Thanks for the report.  Where do you see the docs for `google-cloud-python` referring to that environment variable?

```bash
$ cd ~/path/to/google-cloud-python
$ git grep GAE_
$ git grep appspot
```

Is this from the docs for the `gcloud` command-line tool?  If so, this library is not that thing.

**Comment by travisoneill** [comment]
@tseaver It's from the App Engine docs linked above my previous comment for the Python flexible environment runtime:

```
https://cloud.google.com/appengine/docs/flexible/python/runtime#environment_variables
The following environment variables are set by the runtime environment:

PORT is set to the port that will receive HTTP requests.
GAE_LONG_APP_ID is set to the Project ID associated with your application, which is visible in the Google Cloud Platform Console.
GAE_MODULE_NAME is set to the module name specified in your application's app.yaml, or default.
GAE_APPENGINE_HOSTNAME is set to the hostname for your application, typically your-app-id.appspot.com.
```

 When I print `os.environ` the key is there `'GAE_APPENGINE_HOSTNAME': ''` but just an empty string value.  If this is, in fact, intended behavior, I think the docs should be clarified on that point, as they seem to suggest it is available by default.

**Comment by dhermes** [comment]
@travisoneill This project is not App Engine related (though most / all of our code can be used in an App Engine project). This is a library for interacting with Google Cloud APIs in Python.

The App Engine issue tracker is here: https://code.google.com/p/googleappengine/issues/list

Sorry we couldn't be more help.

**Comment by jonparrott** [comment]
To be slightly more helpful, we are changing some of the environment variables in GAE flexible, so we'll update the documentation shortly. :)
