### ISSUE TITLE
Expose SQL query in QueryJob API

### ISSUE THREAD

**Issue by aaronkavlie-wf** [GoogleCloudPlatform/google-cloud-python#2511]
I had a need to reference the original SQL query from a job. After running `job.reload()` it's available on a `QueryJob` instance, but only by reaching into `_properties` directly:

```python
query = job._properties['configuration']['query']['query']
```

it should be exposed under a more direct public property.

**Comment by tseaver** [comment]
The job actually has a `query` attribute, holding the query text:  we need to surface it to the documentation side, however.

**Comment by dhermes** [comment]
@tseaver Similar to https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1835#issuecomment-224346445

**Comment by tseaver** [comment]
@dhermes I knew there was another issue about those kind of public-but-undocumented attrs.

**Comment by dhermes** [comment]
There's also https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2034

**Comment by aaronkavlie-wf** [comment]
@tseaver 

> The job actually has a query attribute, holding the query text

Yes, that's the first thing I tried. It's `None` for me. I'm initializing the `QueryJob` from a job ID:

```python
    job = bigquery.job.QueryJob(job_id, None, bigquery.Client())
    job.reload()
```

It doesn't seem like that class is intended for API users to call directly (especially since it takes the query string as an *input*), so if there's a better way to do this let me know.

**Comment by tseaver** [comment]
Thanks for the followup:  `job.query` should definitely be populated after `job.reload()`.
