### ISSUE TITLE
google-cloud-speech pip install not working

### ISSUE THREAD

**Issue by puneith** [GoogleCloudPlatform/google-cloud-python#2515]
pip is unable to find google-cloud-speech 

$ pip install --upgrade google-cloud-speech
Collecting google-cloud-speech
  Could not find a version that satisfies the requirement google-cloud-speech (from versions: )
No matching distribution found for google-cloud-speech

Same is true when I try to install google-cloud

$ python -c "from google.cloud import speech"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name speech

**Comment by dhermes** [comment]
@puneith We have not yet released a version of `speech` yet nor is it yet included in the umbrella `google-cloud` package (notice it is not listed on https://pypi.python.org/pypi/google-cloud/0.20.0). @daspecster may have more to say there?

**Comment by daspecster** [comment]
@puneith I've been working on adding the `stream_recognize()` method and implementing GRPC support for `sync_recognize()` and `async_recognize()` before it's fully released.

You could play with speech by installing the library from source. If you have any questions just let me know!

Thanks @dhermes!

**Comment by gw00207** [comment]
@dhermes In the [docs](https://googlecloudplatform.github.io/google-cloud-python/stable/speech-usage.html) there is a Speech API section which does say you can use:

```
>>> from google.cloud import speech
>>> client = speech.Client()
```

However I get the same error as puneith.  @daspecster do you know how soon Speech will be implemented in google-cloud-python? Thanks :-)

**Comment by dhermes** [comment]
@gw00207 It's alread (partially) "implemented in google-cloud-python". You can install from source and play with the current implementation:

```
$ git clone https://github.com/GoogleCloudPlatform/google-cloud-python
$ cd google-cloud-python/speech
$ python setup.py install
```

**Comment by daspecster** [comment]
@gw00207, we have a list of things to do for speech before we release. You can follow along on #2522.

**Comment by mlissner** [comment]
Can we please remove this from the docs until #2522 is done or put a loud note to this effect? I just spent time:
 - trying to figure out why the import in the docs was failing
 - realizing that I needed to install a special package
 - learning that that package was failing to install
 - finding my way here after googling.

A simple notice would have prevented all this.

**Comment by gw00207** [comment]
@dhermes I'm trying to run the speech API inside a GCE VM, can I run those commands from the Cloud Shell? Thanks.
