### ISSUE TITLE
Issues about Google Cloud Speech API (Service)

### ISSUE THREAD

**Issue by geekoala** [GoogleCloudPlatform/google-cloud-python#2518]
Hi, I'm using Google Cloud Speech API. I found an issue and it easy to reproducing. Here is one of my test case, and my test audio file is [abc_rural_2.wav](https://storage.googleapis.com/first-vision-api-example.appspot.com/abc_rural_2.wav).

I tried to recognise using whole .wav file, and it will only translate the first segment (the following segment is speak by another guy in different environment). But if I trim the audio and skip the first segment it perform well. Likewise for the following segments.

## Test Result

1. abc_rural_2.wav
imagine a world of being able to use the latest agricultural technology even if you live in a mobile and Internet black spot that could be a reality for horticulturalist very soon according to Professor Salah sacaria leads the University of Sydney robotic centre he said earlier Dr fruit and veggie growers could start using robots to monitor manage and Harvester crops within a couple of years and the Internet reputation to be able to be one of the last night

2. abc_rural_2.trim23.wav
computational can you put in a robot is sufficient to be able to do all the processing and has been one of the unique advantages that you have with robotic system so if you're someone who lives in a black spot area that's not necessarily going to be in the show

3. abc_rural_2.trim23.trim14.wav
2014 Gold SA Farmers being crowned the Royal Agricultural Society new rural ambassador Jeremy shoots won the title from 7 competitors last night right at same time his town Pinnaroo in The Mallee celebrated it's 100 show

4. abc_rural_2.trim23.trim14.trim14.wav
helping one day you really do you work at 4 but off the whole year

**Comment by daspecster** [comment]
Hello @geekoala!

Which speech method are you using? `sync_recognize` or `async_recognize`?
Also, are you passing in a language code?

**Comment by geekoala** [comment]
Hi @daspecster, I use async_recognize method and the language code is en-AU.

**Comment by daspecster** [comment]
@geekoala, my guess is that it is due to the change in the audio recording since the trimming worked.

I'm working on the streaming api for Speech right now and I'll use your audio clip to test it. 
Streaming has a [`single_utterance`](https://cloud.google.com/speech/reference/rpc/google.cloud.speech.v1beta1#google.cloud.speech.v1beta1.StreamingRecognitionConfig) parameter that might be able to help with this.

I'll let you know what I find out!

**Comment by geekoala** [comment]
@daspecster thank you. But single_utterance seems to be only available for streaming recognition. I'm working on automatically trimming the audio when speakers or environment changed, but I think that would be not a good solution (audio will be split into small chunks). If this API could process a whole audio file, it would be great. Thanks again.

**Comment by daspecster** [comment]
@geekoala, I agree.

@omaray and @bjwatson, do you know anyone involved on the backend that could chime in here?

I have a feeling that the backend algorithm sets a baseline from the first few seconds of the audio and may not handle multiple speakers/environments well? i.e. A conversation that moves from a quiet environment to an environment with a lot of background noise.

**Comment by bjwatson** [comment]
@daspecster I'm checking internally.

**Comment by bjwatson** [comment]
@pbogle is in charge of the back-end. A member of his team will respond here.

**Comment by geekoala** [comment]
Great, thanks @daspecster @bjwatson and @pbogle

**Comment by pbogle** [comment]
Thanks, daharon@ will reply to the thread.  (He's currently on a plane so
response may be slightly delayed.)

To be precise, the Cloud Speech team is really the frontend;  the true
backend is greco <https://sites.google.com/a/google.com/mighty-mouse/> and
that's what controls accuracy.  However, the Cloud Speech team
is responsible for collecting test data for Cloud Speech use cases (like
multi-speaker) that the backend hasn't been traditionally used for and for
helping to evaluate accuracy on those use cases.

**Comment by daspecster** [comment]
@pbogle did you have a chance to take a look at this?

**Comment by pbogle** [comment]
The model is currently intentionally optimized for single-speaker scenarios and will tend treat secondary/background speakers as background noise, especially if they are lower in volume than the initial speaker.  Improved support for multiple speakers is something we will consider in future versions of the product.

**Comment by daspecster** [comment]
Thanks @pbogle!

@geekoala I think that is the answer to your question. If not feel free to reopen!
