### ISSUE TITLE
support versioning options when fetching cloud storage buckets and objects

### ISSUE THREAD

**Issue by jcjones1515** [GoogleCloudPlatform/google-cloud-python#2538]
The [bucket](https://cloud.google.com/storage/docs/json_api/v1/buckets/get) and [object](https://cloud.google.com/storage/docs/json_api/v1/objects/get) REST APIs allow for fetching or at least checking for specific generations/metagenerations of buckets and objects, but these are not supported by the python client.

**Comment by pdknsk** [comment]
This is basically a more generic duplicate of https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2463.

**Comment by tseaver** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2463#issuecomment-250479449 notes that the `generation` option should be used for the whole range of Object APIs which support it.  I have updated the title to indicate its broader scope.
