### ISSUE TITLE
Python Code to Create New Google Project

### ISSUE THREAD

**Issue by naveensinghal** [GoogleCloudPlatform/google-cloud-python#2539]
Hi @daspecster 

I am trying to create a new Project using the below Code. 
Can you please suggest the correction required for making this code work ?

```
from google.cloud import resource_manager
client = resource_manager.Client()

for project in client.list_projects():
    print("%s, %s" % (project.project_id, project.status))    # Works Fine

project = client.new_project('testProjectXXXXXXXXX')
project.create()          # Fails
```

Getting this as Error:

```
Forbidden: 403 The caller does not have permission (POST https://cloudresourcemanager.googleapis.com/v1beta1/projects)
```

Is there any work around for this ? 

Thanks,

**Comment by daspecster** [comment]
Hello @naveensinghal!

I think that you might be running into the issue outlined [here](https://googlecloudplatform.github.io/google-cloud-python/stable/resource-manager-api.html#authentication).

>Unlike the other APIs, the Resource Manager API is focused on managing your various projects inside Google Cloud Platform. What this means (currently, as of August 2015) is that you can’t use a Service Account to work with some parts of this API (for example, creating projects).
>
>The reason is actually pretty simple: if your API call is trying to do something like create a project, what project’s Service Account can you use? Currently none.
>
>This means that for this API you should always use the credentials provided by the Google Cloud SDK, which you can get by running gcloud auth login.

Let me know if running `$ gcloud auth login` before creating the project changes anything?

**Comment by naveensinghal** [comment]
Yes, I think that this might be the issue. But How can I create a project using python code then ?

I am currently trying to run this python code from my local system(Credentials: User Account). And its not working. And I am quite sure, this code won't work from GCE VM(Credentials: Service Account) too. But I need this code to work from both Local & GCE VM.

Any work-around ? 
(`gcloud auth login` with User Credentials might not be a good idea on GCE VM)

**Comment by daspecster** [comment]
@naveensinghal, you might be able to setup application default credentials for this.

https://googlecloudplatform.github.io/google-cloud-python/stable/google-cloud-auth.html#overview
https://googlecloudplatform.github.io/google-cloud-python/stable/google-cloud-auth.html
https://developers.google.com/identity/protocols/application-default-credentials

@dhermes do you know the proper way to go about this?

**Comment by naveensinghal** [comment]
@daspecster 

If I try to use this code:
```
from oauth2client.client import GoogleCredentials
credentials = GoogleCredentials.get_application_default()
```

Then how to proceed from here to create a new Project ? (from Local Machine with User Account Credentials Active)

**Comment by dhermes** [comment]
@naveensinghal You won't be able to use the API until you are whitelisted. As far as I know, they aren't currently taking more people on the whitelist.

**Comment by naveensinghal** [comment]
@dhermes I am able to use list_projects() from the API.
I am facing Issue while creating a new Project.

How can I check if My account whitelisted or not ?

**Comment by daspecster** [comment]
@dhermes Looks like they removed the whitelisting and took it out of beta?

Then...
https://webcache.googleusercontent.com/search?q=cache:58iAe2jqxxQJ:https://cloud.google.com/resource-manager/docs/+&cd=2&hl=en&ct=clnk&gl=us

Now...
https://cloud.google.com/resource-manager/docs/

**Comment by naveensinghal** [comment]
@dhermes , @daspecster Any Suggestions please ?

**Comment by daspecster** [comment]
@naveensinghal, you can pass the credentials from your previous comment via...
```python
client = resource_manager.Client(credentials=credentials)
project = client.new_project('testProjectXXXXXXXXX')
project.create()
```

**Comment by naveensinghal** [comment]
Tried this Code(from Local Machine with User Account):
```
from google.cloud import resource_manager
from oauth2client.client import GoogleCredentials
credentials = GoogleCredentials.get_application_default()
client = resource_manager.Client(credentials=credentials)

project = client.new_project('testProjectXXXXXXXXX')
project.create()
```

Still got the same Error:
```
Forbidden: 403 The caller does not have permission (POST https://cloudresourcemanager.googleapis.com/v1beta1/projects)
```

**Comment by daspecster** [comment]
@naveensinghal, it must still be restricted access.

Maybe @omaray can confirm?

**Comment by eyalev** [comment]
I'm having the same problem. Can't create a new project.

Error:
````
google.cloud.exceptions.Forbidden: 403 The caller does not have permission (POST https://cloudresourcemanager.googleapis.com/v1beta1/projects)
````

**Comment by daspecster** [comment]
@lukesneeringer do you know if this is available to use or is it restricted/unavailable?

**Comment by eyalev** [comment]
@daspecster maybe it's related to the `v1beta1` part? 
`https://cloudresourcemanager.googleapis.com/v1beta1/projects`

Shouldn't the lib use the stable API?

**Comment by daspecster** [comment]
@eyalev, that endpoint depends on what is available from the services upstream.
It looks like [projects are only at `v1beta1`](https://cloud.google.com/resource-manager/reference/rpc/google.cloudresourcemanager.projects.v1beta1) upstream.

Currently 4 of the services in this library are Beta and the rest are still in [Alpha](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/c090fb5f0b68d5ac165b633f55ac47d96d169329/resource_manager/setup.py#L38).

**Comment by sharpstef** [comment]
@eyalev Try forcing the endpoint to use v1 like in the documentation examples here:
[](https://cloud.google.com/resource-manager/reference/rest/v1/projects/create)

**Comment by eyalev** [comment]
@sharpstef works, thanks!

Would be nice if there was documentation for the request body, which entries are required (e.g `projectId`) and which are optional (e.g `name`).

**Comment by gargpankaj83** [comment]
I was facing this issue because I had not enabled the APIs in the Google Cloud Console https://console.developers.google.com/apis/api/cloudresourcemanager

**Comment by lukesneeringer** [comment]
As best as I can tell, this issue is resolved, and I am going to close it. Please reopen if necessary.

**Comment by Abdul-Rehman-yousaf** [comment]
I have successfully created gcp project using google cloud api python client:

**Working Code**
   ```
from googleapiclient import discovery
    from oauth2client.client import GoogleCredentials
    ...
    
    
    credentials = GoogleCredentials.get_application_default()
        service = discovery.build('cloudresourcemanager', 'v1', credentials=credentials)
                project_body = {
                    'name': 'Api Project',
                    'projectId': 'api-9837'
                }
                request = service.projects().create(body=project_body)
                request.execute()
                pprint(request)
```
