### ISSUE TITLE
cloud storage: download_to_filename slower than gsutil cp

### ISSUE THREAD

**Issue by tcroiset** [GoogleCloudPlatform/google-cloud-python#2540]
Hi,
I need to regularly download a "heavy" (~600MB) file from storage, from a compute engine instance.

Using the command line tool gsutil it takes ~20s
Using a python script with my_blob.download_to_filename() it takes ~120s

Is it expected?

**Comment by tseaver** [comment]
@tcroiset The default chunk size is 1 Mb:  does your download go faster if you bump it up?  E.g.:

```python
from google.cloud.storage import Client
client = Client()
bucket = client.bucket('my-bucket-name')
blob = bucket.blob('my-object-name')
blob.chunk_size = 4 * 1024 * 1024
blob.download_to_file('my-file-name')
```

**Comment by daspecster** [comment]
Sounds related to #2222 as well.

**Comment by tseaver** [comment]
I would say it is identical.  @tcroiset, the chunk size suggested in that issue is `1 << 30` (a gigabyte).

**Comment by tcroiset** [comment]
Thanks, it works great!
