### ISSUE TITLE
Broken link in PyPI README

### ISSUE THREAD

**Issue by bjwatson** [GoogleCloudPlatform/google-cloud-python#2541]
Go to https://pypi.python.org/pypi/google-cloud-pubsub and click on the "Pub/Sub API docs" links. It points at https://cloud.google.com/pubsub/reference/rest/, which returns a 404.

A similar issue might exist for other APIs.

**Comment by dhermes** [comment]
Gotcha: moved to https://cloud.google.com/pubsub/docs/reference/rest/ (wonder why they didn't do redirects)
