### ISSUE TITLE
Figure out the right level of abstraction for iterators.

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#2548]
(From #2545)

We need to determine how users will interact with our iterators and what level of abstraction is expected.

Right now @dhermes has implemented an iterator that iterates through items but exposes page information by setting state on the iterator itself.

```python
iterator = MyIterator(...)

for item in iterator:
     print(item)
     print(iterator.page)
     print(iterator.next_page_token)
```

I'm not the biggest fan of this for two reasons: it combines the `iterable` and the `iterator` interfaces, it merges the item-level and page-level abstractions.

In my opinion, we should work at well-defined abstraction levels and keep the `iterable` and `iterator` separate.

The first level is the page level:

```python
iterator = MyIterator(...)

# You could also specify arguments to pages, such as page_token
for page in iterator.pages():
    print(page.number)
    print(page.items)
    print(page.next_page_token)
```

The second level yields items but also page context:

```python
for item, current_page in iterator.items_by_page():
     print(item)
     print(page.number)
     print(page.next_page_token)
```

The final level yields only items and completely abstracts away the concept of pages:

```python
for item in iterator.items():
    print(item)
```

**Comment by jonparrott** [comment]
@dhermes updated, PTAL when you get a chance.

**Comment by dhermes** [comment]
The `Iterator` is already the response, so people want to be able to say:

```python
for project in client.list_projects():
    do_something(project)
```

where `client.list_projects()` is an instance of an `Iterator` subclass.

Also, by using indirection via punting to `iterator.pages()` and `iterator.items()`, does the `Iterator` instance hold any state? Does it know where it is in the iteration process? What happens if someone does this:

```python
page_iter = iterator.pages()
items_iter = iterator.items()
page = next(page_iter)
items = list(page)
next_item = next(items_iter)
```

Rather than get in the "What if?", the current implementation says: "we only iterate through items, but if you want to know about (the current page / the current place in the current page / the current page number / etc.) then we will tell you".

---


> it combines the `iterable` and the `iterator` interfaces...In my opinion, we should work at well-defined abstraction levels and keep the `iterable` and `iterator` separate.

Python doesn't come down one way or another on this, e.g.:

```python
>>> file_obj = open('a.txt', 'w')
>>> iter(file_obj)
<open file 'a.txt', mode 'w' at 0x7f719a76c540>
>>> iter(file_obj) is file_obj
True
>>> list_obj = [1, 2, 3]
>>> iter(list_obj)
<listiterator object at 0x7f719a72a210>
>>> iter(list_obj) is list_obj
False
```

**Comment by jonparrott** [comment]
> The Iterator is already the response, so people want to be able to say

You can still do that with the proposal I have, just map the iterable to return the item iterator by default.

> does the Iterator instance hold any state? Does it know where it is in the iteration process?

The `Iterator` class we have now is actually the `Iterable` in my proposal, so no, it has no state.

> What happens if someone does this:

```python
# New iterator over pages
page_iter = iterator.pages()
# New iterator over all items.
items_iter = iterator.items()
# Returns the first page.
page = next(page_iter)
# Returns all of the items on the first page.
items = list(page)
# Returns the very first item.
next_item = next(items_iter)
```

> Python doesn't come down one way or another on this

Indeed it doesn't, but I think in the case where there are multiple ways of iterating over an iterable it makes sense to return a separate iterator (dict does this).
