### ISSUE TITLE
When Passing in HTTP Object To Datastore Client Get Error

### ISSUE THREAD

**Issue by patrick-ogrady** [GoogleCloudPlatform/google-cloud-python#2549]
Exception AttributeError: AttributeError("'NoneType' object has no attribute 'get_access_token'",) in 'grpc._cython.cygrpc.plugin_get_metadata' ignored

**Comment by patrick-ogrady** [comment]
This is on a GCE machine

**Comment by tseaver** [comment]
@patrick-ogrady Thanks for the report! Can you paste in the full traceback, and show the code which is setting up the datastore client?

**Comment by dhermes** [comment]
@patrick-ogrady Sorry you had to come across this weird corner case. We are working hard to get a better credentials / transport story (see dev at https://github.com/GoogleCloudPlatform/google-auth-library-python/)

A custom HTTP object will only be used the the HTTP implementation of datastore. When using the gRPC implementation (which is the default) the credentials object must be present to help the gRPC client get an access token. You can disable gRPC by setting the `GOOGLE_CLOUD_DISABLE_GRPC=true` env. var.

**Comment by patrick-ogrady** [comment]
Is there any way to check this variable has been set correctly?

**Comment by dhermes** [comment]
Run

``
echo ${GOOGLE_CLOUD_DISABLE_GRPC}
```

from the CLI? Or check the type of

```python
client.connection._datastore_api
```

**Comment by maysamemadi** [comment]
I'm encountering the same issue on a worker running in a Docker container on AWS Elastic Beanstalk. The Datastore client was created from a service account key json file.

Disabling gRPC did not fix it and resulted instead in:

``AttributeError: 'dict' object has no attribute 'authorize'``

After disabling gRPC, the `client.connection._datastor_api` type is `google.cloud.datastore.connection._DatastoreAPIOverHttp`.

**Comment by dhermes** [comment]
It looks like you are using a dictionary (likely a keyfile dictionary) where you should be using a `credentials` object.

**Comment by maysamemadi** [comment]
Right. Of course! Thanks for your quick response. During one of my trial and errors I was reading in the service account key json file and passing the resulting dict as credentials.

The error in my previous comment of course goes away if I create the client using
``client = datastore.Client.from_service_account_json('keyfile.json')``. Though, for completeness I should mention that I now get ``Forbidden: 403 Missing or insufficient permissions.`` Which is probably no longer relevant to this particular issue.

**Comment by dhermes** [comment]
Indeed @maysamemadi, the 403 indicates you need to enable the API in the Cloud Console.

**Comment by maysamemadi** [comment]
@dhermes: the API is enabled. I can interact with Datastore from my local machine using service accounts and from GCE and Cloud Shell using the preset environment variables. Only having issues when running Docker on Elastic Beanstalk.

**Comment by dhermes** [comment]
This issue seems to be un-fix-able because the "internals" have changed so much.

@patrick-ogrady LMK if you're still having this issue and I'm happy to re-open.
