### ISSUE TITLE
Sporadic Missing Credentials on GCE

### ISSUE THREAD

**Issue by patrick-ogrady** [GoogleCloudPlatform/google-cloud-python#2550]
stat("/root/.config/gcloud/application_default_credentials.json", 0x7fffca9515f0) = -1 ENOENT (No such file or directory)

**Comment by tseaver** [comment]
@patrick-ogrady Thanks for the report!  I'm not sure it is germane to `google-cloud-python`:  nothing in our code attempts to open such a file.  We *do* look for `~/.config/gcloud/configurations/config_default`, but wouldn't fail due to its absence.  Are you running into this issue when using the `gcloud` CLI?  That tool isn't developed here.

**Comment by patrick-ogrady** [comment]
This is the error I get when I strace a few processes that get stuck when using google.cloud.datastore to upload some entities...any idea what the issue could be?

**Comment by dhermes** [comment]
I'd guess it's showing internals of how the GCE metadata server works, but have no way of knowing. @jonparrott

**Comment by patrick-ogrady** [comment]
Wondering how to proceed?

**Comment by daspecster** [comment]
@patrick-ogrady, can you tell us a little more about the environment that you're having this issue on?

Are you making many requests? Is this a threaded application?

**Comment by patrick-ogrady** [comment]
This is single threaded on an ubuntu GCE image. I created the image and use
it for all of my instances and haven't run into any problems until 2 weeks
ago (I didn't update or anything). Can images/credentials stored in them
get stale?

**Comment by daspecster** [comment]
I don't think the credentials can go stale unless the token is revoked.

You're running a python application correct?

**Comment by patrick-ogrady** [comment]
Yep! I'm thinking I should just create a fresh image and give that a try?

**Comment by daspecster** [comment]
Could, there are a lot of implementation details here that may be the cause which we wouldn't know.

If you think you can write a python example that reproduces the issue then I can give that try and maybe gain more insight.

**Comment by jonparrott** [comment]
Is the `stat` a red herring? oauth2client checks for gcloud's credentials before attempting to use the GCE metadata server's credentials.

At any rate, a Python script that can reproduce this would be really helpful, especially if there is an issue with the metadata server - it'll help me find the bug and report it properly internally.

**Comment by daspecster** [comment]
@jonparrott, I think that's plausible. The script may not exit cleanly for some reason and hang, and the memory location pointing to the file could have changed.

**Comment by jonparrott** [comment]
If it does actually reach gce credentials then there should be a `connect` call in strace.

**Comment by patrick-ogrady** [comment]
The weird thing is it will usually work for any query calls on Datastore
but then fail when trying to write? Is there any limit on the number of
clients you can invoke in a given program? datastore.client()

**Comment by patrick-ogrady** [comment]
I create a client for each write instead of just using the same client I
used to query with.

**Comment by jonparrott** [comment]
> Is there any limit on the number of
clients you can invoke in a given program? datastore.client()

There shouldn't be, but in general you should create one client per thread in your application.

**Comment by patrick-ogrady** [comment]
But just to confirm it is not thread-safe correct? Also, one client per
service (storage, datastore, pubsub) or one client for all (don't know if
that is possible)?

**Comment by daspecster** [comment]
Each service has it's own client.
So you can not use a datastore client for bigquery for example.

This library is not thread safe, mostly due to httplib2.

**Comment by jonparrott** [comment]
Our clients are not currently threadsafe. And yes, one client per service per thread.

**Comment by patrick-ogrady** [comment]
I'll give it a try and respond with an update...thank you!

**Comment by patrick-ogrady** [comment]
Now I am getting this issue:

select(0, NULL, NULL, NULL, {9, 556264}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {10, 0})    = 0 (Timeout)
select(0, NULL, NULL, NULL, {10, 0})    = 0 (Timeout)
select(0, NULL, NULL, NULL, {10, 0})    = 0 (Timeout)
select(0, NULL, NULL, NULL, {10, 0})    = 0 (Timeout)

Where the upload is just hanging?

**Comment by patrick-ogrady** [comment]
I also see a bunch of jfscommits spawn in ps if that helps?:

root     19094  0.0  0.0      0     0 ?        S<   06:55   0:00 [xfs_mru_cache]
root     19100  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsIO]
root     19101  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]
root     19102  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]
root     19103  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]
root     19104  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]
root     19105  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]
root     19106  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]
root     19107  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]
root     19108  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]
root     19109  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]
root     19110  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]
root     19111  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]
root     19112  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]
root     19113  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]
root     19114  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]
root     19115  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]
root     19116  0.0  0.0      0     0 ?        S    06:55   0:00 [jfsCommit]

**Comment by patrick-ogrady** [comment]
I am also using anaconda2-4.2 if you think that would have any affect?

**Comment by jonparrott** [comment]
@patrick-ogrady that's somewhat helpful, but it would be great to have the code you're using to reproduce this.

**Comment by patrick-ogrady** [comment]
This is the section where it gets stuck:
`while i < len(this_result["prediction"]):

                today_target_value = raw_finance_data[key][str(all_trading_days[i])][target_term]
                to_upload.append(add_today_prediction_to_datastore(datastore_client, this_result["prediction"][i], str(all_trading_days[i]), res, sr, sp, PCA_VALUE, prediction_type,
                        target_term, ticker, noise, input_scale, multiplication_factor, this_result["stored_vol"][i]))
                i += 1
                
                if len(to_upload) > 400:
                    
                    while True:
                        try:
                            with timeout(seconds=60):
                                print("ATTEMPTING TO UPLOAD DAYS")
                                datastore_client.put_multi(to_upload)
                                print("UPLOADED DAYS")
                            break
                        except:
                            print("UPLOAD ERROR")
                            send_alert_message("HUNG COMMAND UPLOAD DAILY")
                            time.sleep(10)
                            datastore_client = datastore.Client()
                    to_upload = []
            while True:
                try:
                    with timeout(seconds=60):
                        datastore_client.put_multi(to_upload)
                        print("UPLOADED DAYS")
                    break
                except:
                    print("UPLOAD ERROR")
                    send_alert_message("HUNG COMMAND UPLOAD DAILY")
                    time.sleep(10)
                    datastore_client = datastore.Client()`

**Comment by patrick-ogrady** [comment]
where add_today_prediction_to_datastore is 
`def add_today_prediction_to_datastore(datastore_client, prediction, today_date, reservoir, spectral_radius, spacity, principal_components, prediction_type,
                        target_term, ticker, noise, input_scale, multiplication_factor, today_vol):
    
    while True:
        try:
            
            key = datastore_client.key(ticker + '_BACKTEST_DAILY_' + str(multiplication_factor))

            test_result = datastore.Entity(
                key)
            fast_lookup_key = str(reservoir) + ":" + str(spectral_radius) + ":" + str(spacity) + ":" + str(principal_components) + ":" + str(prediction_type) + ":" + str(target_term) + ":" + str(ticker) + ":" + str(noise) + ":" + str(input_scale) + ":" + str(multiplication_factor)
            test_result.update({
                'today_prediction':prediction,
                'today_date':today_date,
                'fast_lookup': fast_lookup_key,
                'today_vol':today_vol
            })

            return test_result
        except:
            time.sleep(10)`

**Comment by patrick-ogrady** [comment]
where timeout is
`import signal

class TimeoutError(Exception):
    pass

class timeout:
    def __init__(self, seconds=1, error_message='Timeout'):
        self.seconds = seconds
        self.error_message = error_message
    def handle_timeout(self, signum, frame):
        raise TimeoutError(self.error_message)
    def __enter__(self):
        signal.signal(signal.SIGALRM, self.handle_timeout)
        signal.alarm(self.seconds)
    def __exit__(self, type, value, traceback):
        signal.alarm(0)`

**Comment by patrick-ogrady** [comment]
where timeout is:
`import signal

class TimeoutError(Exception):
    pass

class timeout:
    def __init__(self, seconds=1, error_message='Timeout'):
        self.seconds = seconds
        self.error_message = error_message
    def handle_timeout(self, signum, frame):
        raise TimeoutError(self.error_message)
    def __enter__(self):
        signal.signal(signal.SIGALRM, self.handle_timeout)
        signal.alarm(self.seconds)
    def __exit__(self, type, value, traceback):
        signal.alarm(0)`

**Comment by patrick-ogrady** [comment]
where clients are initialized:
`#Initialize Clients
from google.cloud import pubsub
from google.cloud import datastore
from google.cloud import storage
pubsub_client = pubsub.Client()
datastore_client = datastore.Client()
storage_client = storage.Client()`

**Comment by patrick-ogrady** [comment]
I added timeouts to try and kick it out of a hang where the process went into that loop noted earlier but didn't help

**Comment by daspecster** [comment]
At first glance, I see that you're redeclaring `datastore_client` several times.  You shouldn't need to do that. You can just use the clients that you defined in your `#Initialize Clients` example.

**Comment by patrick-ogrady** [comment]
I only do that if the upload fails

**Comment by patrick-ogrady** [comment]
should I just retry the upload without reinitialization?

**Comment by daspecster** [comment]
What exception does it throw when the client(s) fail?

**Comment by patrick-ogrady** [comment]
So far, it either gets stuck and does: `stat("/root/.config/gcloud/application_default_credentials.json", 0x7fffca9515f0) = -1 ENOENT (No such file or directory)` 

or it gets stuck and does:
`select(0, NULL, NULL, NULL, {10, 0}) = 0 (Timeout)`

**Comment by patrick-ogrady** [comment]
i'm on the newest version right now

**Comment by patrick-ogrady** [comment]
I just built a fresh image and am testing now

**Comment by patrick-ogrady** [comment]
Alright got a new error: @jonparrott 
`UPLOAD ERROR(<class 'grpc._channel._Rendezvous'>, <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE,
 {"created":"@1476811838.872765094","description":"Secure read failed","file":"src/core/lib/security/transport/secu
re_endpoint.c","file_line":157,"grpc_status":14,"referenced_errors":[{"created":"@1476811838.872723741","descriptio
n":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235}]})>, <traceback object at 0x7fea8b6c0d40>)`

**Comment by dhermes** [comment]
@patrick-ogrady That's just the gRPC equivalent of a 404.

**Comment by patrick-ogrady** [comment]
This happens each time I try to upload

**Comment by patrick-ogrady** [comment]
currently trying the HTTP version using 'GOOGLE_CLOUD_DISABLE_GRPC=true' to see if this alleviates any errors

**Comment by patrick-ogrady** [comment]
now get : `UPLOAD ERROR(<class 'socket.error'>, error(32, 'Broken pipe'), <traceback object at 0x7f30108c1098>)`

**Comment by patrick-ogrady** [comment]
Should I just disregard these errors eventhough they happen on the first call of every time?

**Comment by patrick-ogrady** [comment]
@jonparrott I decreased the size from 400 to 100 and the error went away

**Comment by patrick-ogrady** [comment]
Alright in summary:

- Get Errors on Both gRPC and HTTP if size of upload is 400
- Only Get Error on gRPC if size of upload is 70

Thoughts:

Because there is a long time between subsequent calls, anaconda may be doing something to end the gRPC connection?

**Comment by patrick-ogrady** [comment]
Scratch that...after running for 15 minutes, I get the hanging loop error again:

`select(0,NULL, NULL, NULL, {0, 932688}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {10, 0}`

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
