### ISSUE TITLE
BigQuery: Add support for query parameters

### ISSUE THREAD

**Issue by jlowin** [GoogleCloudPlatform/google-cloud-python#2551]
The CLI command `bq query` now supports query parameters for Standard SQL queries and the API does as well (https://cloud.google.com/bigquery/docs/reference/v2/jobs/query#request-body). It would be great to be able to provide these via google.cloud.

**Comment by tseaver** [comment]
@jlowin Thanks for the report!  Except for the API reference page you linked, I can't find any other docs (especially narrative ones with samples) which explain how query parameters should be used.  Do you know of any?

**Comment by jlowin** [comment]
I wish there were but so far I've just been figuring it out via trial and error. For example:

```
bq query --use_legacy_sql=False --parameter param1:INTEGER:5 --parameter param2:INTEGER:100 "select @param1 + @param2 as result"

Waiting on bqjob_r665b4bfadeedbee9_00000157ce6674a0_1 ... (0s) Current status: DONE
+--------+
| result |
+--------+
|    105 |
+--------+
```

**Comment by tswast** [comment]
@tseaver It's on my TODO list to document this feature better.

**Comment by tswast** [comment]
@tseaver I found the docs on this:

https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query

Search for `queryParameters`.

Depending on what `parameterMode` is set to, the parameter can be positional `?` or names `@somename`

**Comment by c0b** [comment]
+1 on request of this, even reading that reference didn't help a lot, because it didn't give a working example I was researching on how to pass an array and struct value, but see https://github.com/GoogleCloudPlatform/google-cloud-go/issues/390#issuecomment-260262753 what I found from reading /opt/google-cloud-sdk/platform/bq/bq.py source code.

what I found parameterMode is `optional` because bq tool doesn't send that at all.

**Comment by tseaver** [comment]
@tswast Working on this now.  I note that the feature is still documented as "experimental," which makes it a bit odd to have as "blocking beta" for us.

**Comment by danoscarmike** [comment]
Hi @tseaver, are you actively working this one?  If you have any blockers or need input from BQ team please let me know ASAP.  Otherwise, do you have a sense for remaining effort, ETC?  Thanks!

**Comment by tseaver** [comment]
@danoscarmike PR #2776 implements the feature.

**Comment by danoscarmike** [comment]
Great stuff.  Thanks Tres!
