### ISSUE TITLE
Please update examples BigQuery API docs to use this library

### ISSUE THREAD

**Issue by tehranian** [GoogleCloudPlatform/google-cloud-python#2557]
Thanks for writing this library. Looks like it'll be very useful, once I switch to it from `google-api-python-client`...

Question: Why do all of the Python examples in the BigQuery API docs (ex: https://cloud.google.com/bigquery/docs/reference/v2/jobs/get) use the low-level client library https://github.com/google/google-api-python-client ?

As far as I can tell, there's no mention in any of the BigQuery docs about this `google-cloud-python` library, even though this is "the recommended way". Very frustrated the the docs did not point us to the better library in the first place, and now we have to re-write our apps.

**Comment by jonparrott** [comment]
/cc @omaray 

Hi @tehranian, we're in the process of updating documentation for several products to point to this library over `google-api-python-client`. Keep in mind that this library is currently in beta and hasn't yet reached 1.0 so we want to make sure that this library is mature enough and the proper support is in place before making this the recommended way to access our services.

**Comment by tehranian** [comment]
Hi @jonparrott,

Thanks for the quick reply. I was not aware that this library was still in beta. Any ETA on when it might go for a 1.0 release? Calendar month or quarter would be good to know.

I'll hold off on migrating our apps until then. Thanks, Dan.

**Comment by jonparrott** [comment]
@tehranian typically we don't speak toward timelines, but perhaps @omaray can fill in any gaps.
