### ISSUE TITLE
Network Status Tracker Error

### ISSUE THREAD

**Issue by wakahiu** [GoogleCloudPlatform/google-cloud-python#2559]
I've added google cloud (StackDriver) as one of my [logging handlers](https://docs.python.org/3.4/library/logging.html#module-logging). Logging happens fine, however my python scripts always end with the following message.

```
network_status_tracker.c:48] Memory leaked as all network endpoints were not shut down
```

Here's a snipet of code for how I'm logging.
```
from __future__ import absolute_import
from google.cloud import logging as gclogging
import logging as pylogging

defaultHandlersAdded = False

# A class based on of google stackdriver logger.
class GSDHandler(pylogging.Handler):
  gcclient = gclogging.Client()
  gcLogger = gcclient.logger('behold-ai-learning')
  def __init__(self, level=pylogging.NOTSET):
    pylogging.Handler.__init__(self, level)
  
  def emit(self, record):
    msg = self.format(record)
    self.gcLogger.log_struct(
      info = {
        'message': msg
      })
```

Any idea why the google cloud SDK is not shutting down the network endpoints?

**Comment by daspecster** [comment]
@wakahiu Thanks for reporting!

I think this is actually some debug logging that should be removed from one of the c plugins.

@jonparrott or @bjwatson, do you know who would be good to mention this too?

**Comment by wakahiu** [comment]
This debug message originates from gRPC based on [this issue](https://github.com/grpc/grpc/issues/7849).

**Comment by daspecster** [comment]
@wakahiu thanks for finding it! I'll close this issue and we can track it there.

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle Note this is a user confounded by the memory leak

**Comment by jonparrott** [comment]
I've also started seeing this in the tests for python-docs-samples.
