### ISSUE TITLE
Serve Static files from Google Cloud Storage Bucket (for Django App hosted on GCE)

### ISSUE THREAD

**Issue by naveensinghal** [GoogleCloudPlatform/google-cloud-python#2567]
Hi @dhermes 

I am trying to serve the static Files for my django App from Cloud Storage Bucket but don't know the exact process. Can you please suggest a proper way to do so ?

Steps done:

1. Uploaded all the static files on Google Cloud Storage Bucket(www.example.com) using gsutil command.
2. Edited /etc/apache2/sites-available/default-ssl.conf File.

File Content:
```
<VirtualHost *:443>
        ServerName example.com
        ServerAdmin admin@example.com

 #       Alias /static /opt/projects/example-google/example_static
        Alias /static https://storage.googleapis.com/www.example.com/static
        <Directory /opt/projects/example-google/example_static>
           Require all granted
        </Directory>

        <Directory /opt/projects/example-google/example/example>
            <Files wsgi.py>
                Require all granted
            </Files>
        </Directory>

        WSGIDaemonProcess example python-path=/opt/projects/example-google/example:/opt/projects/example-google/venv/lib/python2.7/site-packages
        WSGIProcessGroup example
WSGIApplicationGroup %{GLOBAL}
        WSGIScriptAlias / /opt/projects/example-google/example/example/wsgi.py

        SSLEngine on
        SSLCertificateFile  /etc/apache2/ssl/example.com.crt
        SSLCertificateKeyFile /etc/apache2/ssl/example.com.key
        SSLCertificateChainFile /etc/apache2/ssl/intermediate.crt
</VirtualHost>
```

Settings.py File:
```
# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
# STATIC_URL = 'https://storage.googleapis.com/www.example.com/static/'
STATIC_ROOT = os.path.join(BASE_DIR, '../example_static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, '../example_media')
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'), MEDIA_ROOT,)
```

Any suggestion on what all additional changes are required for this task ?

Thanks,

**Comment by daspecster** [comment]
@naveensinghal, do you have the files in the bucket set to public visibility?

Also, I _don't_ think apache's `alias` directive is what you want here.
https://httpd.apache.org/docs/current/mod/mod_alias.html#alias is used to reference local filesystem resources.

You probably want to read up on https://httpd.apache.org/docs/current/mod/mod_proxy.html.

**Comment by naveensinghal** [comment]
Yes, I have the bucket files set to public visibility. The issue should be with the settings only.

**Comment by dhermes** [comment]
@naveensinghal Check out the storage docs: https://cloud.google.com/storage/docs/collaboration

Once you have made a file public, you can serve it at the static URL:

```
https://storage.googleapis.com/YOUR-BUCKET/BLOB-NAME-QUOTED-FOR-URL
```

Questions like this that are about the service itself, rather than our library, are better suited for StackOverflow. (We aren't necessarily experts on the Storage API and even if we were, that is not really the goal of the Python library.)
