### ISSUE TITLE
using datastore (+pubsub?) emulator requires credentials

### ISSUE THREAD

**Issue by tinyhydra** [GoogleCloudPlatform/google-cloud-python#2573]
There may be a way to do this that I'm not aware of, but from hunting around for documentation, consulting slack, and stepping through the code, it appears that this library requires live gcp credentials to use the emulator. This wouldn't be a problem, except that I can't think of a reason it would require the credentials, and if there's a problem using the emulator no notice is given, it simply falls back to using the live account. 

I would like to configure my dev/test environments to not have access to a live account at all, and ideally I would like to be able to toggle 'force emulator use' on my dev machine just in case. Is this possible?
1. OS type and version
   Win10/macOS Sierra
2. Python version and virtual environment information `python --version`
   python 3.5.2
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
   0.20.0

**Comment by dhermes** [comment]
Thanks for filing. The connection [can tell][3] if it is in an emulator, but just uses the default credential checking behavior. In our system test, we manually [pass in][4] some [do-nothing credentials][5].

Have you seen the `tox -e pubsub-emulator` [environment][1] or [`run_emulator.py`][2]?

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/85a0c1a74af0fa9af9b33b3e57b0e562c4ed80a5/tox.ini#L254-L259
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/85a0c1a74af0fa9af9b33b3e57b0e562c4ed80a5/system_tests/run_emulator.py
[3]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/85a0c1a74af0fa9af9b33b3e57b0e562c4ed80a5/pubsub/google/cloud/pubsub/connection.py#L51-L61
[4]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/85a0c1a74af0fa9af9b33b3e57b0e562c4ed80a5/system_tests/pubsub.py#L53-L56
[5]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/85a0c1a74af0fa9af9b33b3e57b0e562c4ed80a5/system_tests/system_test_utils.py#L32-L41

**Comment by nabilm** [comment]
Please any updates on this ? passing empty credentials didn't fix the problem ? please advice !

**Comment by daspecster** [comment]
@nabilm can you give a code example of how you passed in the credentials?

**Comment by hoootsli** [comment]
@dhermes we used the same approach as you suggested to avoid that default credentials have to be set in emulator mode:

> In our system test, we manually [pass in](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/85a0c1a74af0fa9af9b33b3e57b0e562c4ed80a5/system_tests/pubsub.py#L53-L56) some [do-nothing credentials](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/85a0c1a74af0fa9af9b33b3e57b0e562c4ed80a5/system_tests/system_test_utils.py#L32-L41).

However, we recently updated to the version that contains [this code](https://github.com/GoogleCloudPlatform/google-cloud-python/blame/master/core/google/cloud/client.py#L119-L122) which checks that the credentials are either `None` or an instance of `google.auth.credentials.Credentials`. Just passing in `credentials=None` (and also adding `projects=<PROJECT_NAME>` to avoid that it tries to derive the project name from the non-existing default credentials) seems to work.

I was wondering if there is a better approach? Also, is it possible that the test is not up to date anymore?

**Comment by JasonMWhite** [comment]
I also found it very inconvenient to pass in real credentials just to run unit tests on an emulator in my CI environment. That requires encrypting the credentials, managing secrets, etc. I tried editing the credential files to not include real keys, but it appears the creds need to actually load correctly to connect to the emulator.

In the end, this worked well. I subclassed `Credentials` and passed those in:
```
class DoNothingCreds(credentials.Credentials):
    def refresh(self, request):
        pass

client = google_datastore.Client('gitlawca', credentials=DoNothingCreds())
```

**Comment by lukesneeringer** [comment]
Hello! :-)
First, a _mea culpa_; I have not done as good of a job at keeping up with issues as I should have. If you are getting this (I admit it) cut and paste, it is likely because your issue sat for too long.

In this case, I have been in the process of making a radical update to the PubSub library (#3637) to add significant performance improvements and a new surface, which we hope to launch soon. As such, I am clearing out issues on the old library. It is my sincere goal to do a better job of being on top of issues in the future.

As the preceding paragraph implies, I am closing this issue. If the revamped library does not solve your issue, however, please feel free to reopen.

Thanks!
