### ISSUE TITLE
Core: `google.cloud._helpers._default_service_project_id()` does not use project ID from active configuration

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#2588]
# Problem (steps to reproduce)

Run `gcloud init`. Instead of updating the default configuration, make a new configuration (in my case, I called it "kittenbot"). Use a different project than you have for the default configuration. Note, you can switch between configurations using a command like: `gcloud config configurations activate kittenbot`.

Now, try to run any google-cloud-python library, notice that the paths it hit use project from the default configuration, not the active configuration. https://github.com/GoogleCloudPlatform/google-cloud-python/blob/ec781b6e8afc0b27599ddc69848571e1abf412ff/core/google/cloud/_helpers.py#L64 I noticed this problem because my GETs were failing in the RuntimeConfig, but it would be a worse problem with something like Datastore, where data could get written to the wrong project.

See similar issue in google-cloud-java: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/827

This was fixed with: https://github.com/GoogleCloudPlatform/google-cloud-java/pull/831
# Expected behavior

The default project should use the active configuration, not the default configuration.

**Comment by dhermes** [comment]
Ick! I think @jonparrott is putting this all in https://github.com/GoogleCloudPlatform/google-auth-library-python/

**Comment by jonparrott** [comment]
Move this over to google-auth, it's getting closer and closer to ready.

**Comment by dhermes** [comment]
w00t!

**Comment by jonparrott** [comment]
Filed over at https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/53

**Comment by dhermes** [comment]
@jonparrott Is this
