### ISSUE TITLE
Is it possible to provide a list of logos for detection using LOGO_DETECTION (vision)

### ISSUE THREAD

**Issue by geekoala** [GoogleCloudPlatform/google-cloud-python#2595]
Hi,

When I did a test on LOGO_DETECTION, I used an [image full of logos](https://storage.googleapis.com/first-vision-api-example.appspot.com/logo_collection_0.png), and even I set maxResult to 10, it will return only 5 results. When I trim out several logos from the image, and generated [a new image](https://storage.googleapis.com/first-vision-api-example.appspot.com/logo_collection_1.png) and run again, it will return some more results.

Image_0:
![img0](https://storage.googleapis.com/first-vision-api-example.appspot.com/logo_collection_0.png)

Image_1:
![img1](https://storage.googleapis.com/first-vision-api-example.appspot.com/logo_collection_1.png)

Result for these two images are:

```python
['Buffalo Wild Wings', 'Bahama Breeze', "Moe's Southwest Grill", 'Quiznos', "Jason's Deli"]
```
and

```python
['Chipotle', 'Chick-fil-A', 'Burger King', 'Applebees']
```

Obviously, Vision API could recognise more than 5 logos in the first image above (and I never doubt that).

This seems a very extream example, but it really happened in my realistic scenario. Not a well-ordered logo list, but a scenario contains a lot of logos, just like logos around a football pitch or a racing lane. When this happen, I will not get the logo I want (by directly calling vision API).

I understand that search for a large amount of logos could be difficult for a single request. **So my question is that can we pass a candidate logo list to LOGO_DETECTION API, and expect result only in this list**.

**Comment by daspecster** [comment]
@geekoala, this is a good question. Maybe @omaray can direct us to someone that works on Vision  upstream?

Also, based on the recommended image size for LOGO_DETECTION it appears that one logo is detected at a time.
See: https://cloud.google.com/vision/docs/best-practices#image_sizing

**Comment by dhermes** [comment]
@geekoala Thanks for the question. We're happy to help but this question is more appropriate for StackOverflow or for the [vision forum][1]. Check out https://cloud.google.com/vision/support for how the backend folks recommend you ask questions.

We're here to implement an interface for that API and are happy to help with bugs, explain usage or add features to our implementation.

[1]: https://groups.google.com/forum/#!forum/cloud-vision-discuss

**Comment by geekoala** [comment]
Thanks, @dhermes @daspecster
