### ISSUE TITLE
Sink creation fails with error StatusCode.PERMISSION_DENIED

### ISSUE THREAD

**Issue by Fkawala** [GoogleCloudPlatform/google-cloud-python#2596]
Hello, 

I try to create a bigquery logging sink with the code below:

``` python
from google.cloud import logging

client = logging.Client()

sink = client.sink("pull-logs", 
                   'severity >= DEBUG', 
                   'bigquery.googleapis.com/projects/karos-api/datasets/custom')

if not sink.exists():
    print(vars(client.connection.credentials))  
    sink.create()
```

It fails with the error:

``` bash
Traceback (most recent call last):
  File "do_sink.py", line 12, in <module>
    sink.create()
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/sink.py", line 119, in create
    self.project, self.name, self.filter_, self.destination)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/_gax.py", line 200, in sink_create
    self._gax_api.create_sink(parent, sink_pb, options=options)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/gapic/logging/v2/config_service_v2_api.py", line 303, in create_sink
    return self._create_sink(request, options)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 481, in inner
    return api_caller(api_call, this_settings, request)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 469, in base_caller
    return api_call(*args)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 434, in inner
    errors.create_error('RPC failed', cause=exception))
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 430, in inner
    return a_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 64, in inner
    return a_func(*updated_args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 481, in __call__
    return _end_unary_response_blocking(state, False, deadline)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 432, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
google.gax.errors.GaxError: GaxError(RPC failed, caused by <_Rendezvous of RPC that terminated with (StatusCode.PERMISSION_DENIED, The caller does not have permission)>)
```

I verified that: 
- the big-query dataset exists
- cloud-logs@google.com as sufficient rights for big-query https://cloud.google.com/logging/docs/export/configure_export#manual-access-bq 
- the scopes seems ok with `print(vars(client.connection.credentials))` : 

``` python
{'token_uri': 'https://www.googleapis.com/oauth2/v4/token', 'token_response': None, 'token_expiry': None, '_kwargs': {}, 'invalid': False, 'assertion_type': None, '_scopes': 'https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/logging.write https://www.googleapis.com/auth/logging.admin https://www.googleapis.com/auth/cloud-platform' }
```

Have you any ideas about what is going on ?

**Comment by dhermes** [comment]
It seems like it's an access issue, not a scopes issue. You're seeing the gRPC equivalent of a 403. Can you confirm that the BigQuery dataset exists and `cloud-logs@google.com` has "sufficient rights" programmatically?

**Comment by tseaver** [comment]
@Fkawala see the [docs for configuring permissions on BigQuery sinks].

**Comment by tseaver** [comment]
@Fkawala can you verify the grants in Python?  E.g.:

```python
from google.cloud import bigquery
from google.cloud.bigquery.dataset import AccessGrant
bigquery_client = bigquery.Client()
dataset = bigquery_client.dataset('custom')
dataset.reload()
for grant in dataset.access_grants:
    print(grant)
```

It should include:

```
<AccessGrant: role=WRITER, groupByEmail=cloud-logs@google.com>
```

**Comment by Fkawala** [comment]
@tseaver thanks for the tips, cloud-logs@google.com does appear in the grants:
```
<AccessGrant: role=WRITER, groupByEmail=cloud-logs@google.com>
<AccessGrant: role=OWNER, specialGroup=projectWriters>
<AccessGrant: role=OWNER, userByEmail=francois@domain.fr>
```

**Comment by Fkawala** [comment]
I can create the sink using my own account and this [test form](https://cloud.google.com/logging/docs/api/reference/rest/v2/projects.sinks/create). In the python script the service account is a project EDITOR, while I'm a project OWNER, could that explain the different results ?

The error log (from google cloud console) does not provides much information.

```javascript
{
 metadata: {
  severity: "ERROR"    
  projectId: "my-project-id"    
  serviceName: "logging.googleapis.com"    
  labels: {
   logging.googleapis.com/resource_id: "service-name"     
   logging.googleapis.com/resource_type: "sink"     
  }
  timestamp: "2016-10-25T06:57:03.275705878Z"    
 }
 protoPayload: {
  @type: "type.googleapis.com/google.cloud.audit.AuditLog"    
  status: {
   code: 7     
  }
  authenticationInfo: {
   principalEmail: "account@my-project-id.iam.gserviceaccount.com"     
  }
  requestMetadata: {
   callerIp: "92.154.18.143"     
   callerSuppliedUserAgent: "Python-gRPC-1.0.0 grpc-c/1.0.0 (manylinux; chttp2),gzip(gfe)"     
  }
  serviceName: "logging.googleapis.com"    
  methodName: "google.logging.v2.ConfigService.CreateSink"    
  authorizationInfo: [
   0: {
    resource: "projects/my-project-id"      
    permission: "logging.sinks.create"      
   }
  ]
  resourceName: "projects/my-project-id/service-name"    
  request: {
   sink: {
    filter: "severity >= DEBUG"      
    destination: "bigquery.googleapis.com/projects/my-project-id/datasets/logging"      
    name: "service-name"      
   }
   @type: "type.googleapis.com/google.logging.v2.CreateSinkRequest"     
   parent: "projects/my-project-id"     
  }
 }
 insertId: "2016-10-24|23:57:03.275742-07|10.106.17.68|470165258"   
 log: "cloudaudit.googleapis.com/activity"   
}
```

**Comment by tseaver** [comment]
@Fkawala Your hunch sounds plausible, even though the docs refer only to scopes, rather than roles.  One thing to check:  Is the logging client configured using the same project as the Bigquery table?

**Comment by cmac4603** [comment]
I have a possibly related issue with permissions in BQ and service account JSON file. Correct permissions are with the service account, and I can do the creation of datasets/tables with default client when signed in using the CLI. I'd like to pick this issue up if they are related and no one has any objections? I have been in contact with GCP support already. @Fkawala, are you seeing this issue with other BQ calls?

**Comment by Fkawala** [comment]
@cmac4603 The only other BQ call I do is for data insertion (as described below). It worth mentioning  that I did not try any further to get the sink creation working.

```python
# google-cloud-bigquery>=0.24.0
client = bigquery.Client()
data_set = client.dataset(self._bq_dataset)
bq_table = data_set.table(self._bq_table)
bq_table.reload()
errors = bq_table.insert_data(rows=self._measures)
```

**Comment by cmac4603** [comment]
@Fkawala I think I was getting an error even trying to reload(), which is a GET request, so the two may not be related. But permissions seem fine, I'll keep digging my end and if I find some error will get back in touch

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
