### ISSUE TITLE
Authentication auto Refresh with bigquery access 

### ISSUE THREAD

**Issue by vrcs** [GoogleCloudPlatform/google-cloud-python#2598]
Hi
recently i am having issues with the google cloud python with Authentication refresh Error each time its doing any access operation.

It has been working fine previously , but now it get
```
[transport.py:new_request] Attempting refresh to obtain initial access_token
[client.py:_do_refresh_request] Refreshing access_token
```

and any subsequent action to access with the gcloud object fails, did any one face the same issue or any know fix for this. 

Thanks  

1. OS type and version
OS - 4.4.19-29.55.amzn1.x86_64
2. Python version and virtual environment information `python --version`
Python 2.7.12
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`

```
gax-google-logging-v2==0.8.3
gax-google-pubsub-v1==0.8.3
gcloud==0.18.3
google-api-python-client==1.5.4
google-gax==0.12.5
googleapis-common-protos==1.3.5
grpc-google-logging-v2==0.8.1
grpc-google-pubsub-v1==0.8.1
```

4. Stacktrace if available
5. Steps to reproduce
6. Code example

```python
def check_if_table_exist(dataset_name, table_name):
    client = bigquery.Client()
    dataset = client.dataset(dataset_name)
    table = dataset.table(name=table_name)
    return table.exists()
standard_tables_list=['sample1','sample2']
for dump_table_name in standard_tables_list:
  table_exists = check_if_table_exist(google_dataset_name, dump_table_name)
  if table_exists:
     print "the table exists"
 else:
    print "the table doesnt exist" 
```

**Comment by dhermes** [comment]
@vrcs Any reason you haven't upgraded from `gcloud` --> `google-cloud` (renamed after version 0.18.3)

**Comment by vrcs** [comment]
i am using this in python 
from gcloud import bigquery

**Comment by vrcs** [comment]
gcloud components list

Your current Cloud SDK version is: 131.0.0
The latest available version is: 131.0.0

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                  Components                                                 │
├───────────────┬──────────────────────────────────────────────────────┬──────────────────────────┬───────────┤
│     Status    │                         Name                         │            ID            │    Size   │
├───────────────┼──────────────────────────────────────────────────────┼──────────────────────────┼───────────┤
│ Not Installed │ App Engine Go Extensions                             │ app-engine-go            │  47.3 MiB │
│ Not Installed │ Cloud Datastore Emulator                             │ cloud-datastore-emulator │  15.4 MiB │
│ Not Installed │ Cloud Datastore Emulator (Legacy)                    │ gcd-emulator             │  38.1 MiB │
│ Not Installed │ Cloud Pub/Sub Emulator                               │ pubsub-emulator          │  16.3 MiB │
│ Not Installed │ Google Container Registry's Docker credential helper │ docker-credential-gcr    │   2.2 MiB │
│ Not Installed │ gcloud Alpha Commands                                │ alpha                    │   < 1 MiB │
│ Not Installed │ gcloud Beta Commands                                 │ beta                     │   < 1 MiB │
│ Not Installed │ gcloud app Java Extensions                           │ app-engine-java          │ 132.0 MiB │
│ Not Installed │ gcloud app Python Extensions                         │ app-engine-python        │   7.2 MiB │
│ Not Installed │ kubectl                                              │ kubectl                  │  15.9 MiB │
│ Installed     │ BigQuery Command Line Tool                           │ bq                       │   < 1 MiB │
│ Installed     │ Cloud SDK Core Libraries                             │ core                     │   4.9 MiB │
│ Installed     │ Cloud Storage Command Line Tool                      │ gsutil                   │   2.8 MiB │
│ Installed     │ Default set of gcloud commands                       │ gcloud                   │           │
└───────────────┴──────────────────────────────────────────────────────┴──────────────────────────┴───────────┘

**Comment by vrcs** [comment]
i have this in different version as well on other server 
gcloud components list
Your current Cloud SDK version is: 127.0.0
The latest available version is: 131.0.0

Still it fails after the first iteration to access any objects, the initial access works fine and does the job but when it tries to check again in the loop for other object it treats it as fresh access, and it fails to get the credentials some how with the refresh_token.

**Comment by dhermes** [comment]
@vrcs To get the latest version you want to do this:

```
pip install --upgrade google-cloud
```

but you want to import like this

```python
from google.cloud import bigquery
```

**Comment by vrcs** [comment]
installed the google-cloud 
and gave a try , it still fails to get the authentication after the first iteration as before

pip freeze 
gapic-google-logging-v2==0.10.1
gapic-google-pubsub-v1==0.10.1
gax-google-logging-v2==0.8.3
gax-google-pubsub-v1==0.8.3
gcloud==0.18.3
google-api-python-client==1.5.3
google-cloud==0.20.0
google-cloud-bigquery==0.20.0
google-cloud-bigtable==0.20.0
google-cloud-core==0.20.0
google-cloud-datastore==0.20.1
google-cloud-dns==0.20.0
google-cloud-error-reporting==0.20.0
google-cloud-language==0.20.0
google-cloud-logging==0.20.0
google-cloud-monitoring==0.20.0
google-cloud-pubsub==0.20.0
google-cloud-resource-manager==0.20.0
google-cloud-storage==0.20.0
google-cloud-translate==0.20.0
google-cloud-vision==0.20.0
google-gax==0.14.1
googleapis-common-protos==1.3.4
grpc-google-iam-v1==0.10.1
grpc-google-logging-v2==0.10.1
grpc-google-pubsub-v1==0.10.1

**Comment by daspecster** [comment]
@vrcs, can you give us some simple example code that creates this error for you?

Also, these docs have the latest way to use bigquery with `google-cloud`.
https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-usage.html

**Comment by vrcs** [comment]
I have followed the  document and then
exporting the data to GC storage for the list of tables  in a loop 
https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-usage.html?highlight=extract_table_to_storage#exporting-data-async

the logic that i have is a list of tables, loop though them and before extracting , check for the existence  in bigquery and export and store in GC Storage using , later download the exported csv from GC Storage to my local machine

def export_data_to_gcs(dataset_name, table_name, destination):
    bigquery_client = bigquery.Client()
    dataset = bigquery_client.dataset(dataset_name)
    table = dataset.table(table_name)
    job_name = str(uuid.uuid4())
    logger.info("Created Job id for Big query : %s" %(job_name))
    job = bigquery_client.extract_table_to_storage(job_name, table, destination)
    job.destination_format = 'CSV'
    job.Compression = 'GZIP'
    job.print_header = False
    job.begin()
    wait_for_job(job)
    logger.info(" Exported %s : %s  to %s "  % (dataset_name, table_name, destination))

def wait_for_job(job):
    logger.info("Waiting for the job :%s to Finish" %(job.name))
    logger.info(" job %s created at %s " %(job.name, job.created))
    while True:
        job.reload()
        if job.state == 'DONE':
            logger.info("Job %s started at :%s  and ended at: %s " %(job.name, job.started, job.ended))
            if job.error_result:
                raise RuntimeError(job.error_result)
            return
        time.sleep(1)



The first table in the list succeeds and for the next iteration in the loop it gets a refresh for authentication and then fails to access or check if the table exists in the big query.
