### ISSUE TITLE
Adding fluentd hander

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/google-cloud-python#2599]
This is pretty overdue but one of the transports for the logging handler should be to write to a file that the google-fluentd agent knows how to pickup. This is how we recommend using logging on GAE Flex/GKE. [This handler](https://github.com/GoogleCloudPlatform/python-compat-runtime/blob/master/appengine-vmruntime/vmruntime/cloud_logging.py) is from the compat runtime and is roughly what we want to copy paste in here. 

I've realized I've made a slight design mistake, since the handler we wants inherits from `logging.handlers.RotatingFileHandler`, but I already created a Handler class that inherits from `logging.handlers.StreamHandler` and I'm splitting the different ways to send to the API by a Transport class that the Handler uses.

I think it's still important that users can write a few lines of code, and have it do something reasonable both locally and on GAE Flex (i.e. locally write using the API transport, on Flex write to fluentd).

So alternatives are:
- Just break the current API and make a factory return different types of handlers instead of 1 handler with different types of transports. So instead of:

```

        import google.cloud.logging
        from google.cloud.logging.handlers import CloudLoggingHandler

        client = google.cloud.logging.Client()
        handler = CloudLoggingHandler(client)
```

something like 

```

        import google.cloud.logging
        from google.cloud.logging.handlers import get_logging_handler

        client = google.cloud.logging.Client()
        handler = get_logging_handler(client)
```

Then you can dynamically return the right type of handler.
- Use metaclasses somehow to do the above without breaking the current API (think this could be done but I know metaclasses are generally best avoided)
- Handroll my own file rotation code. Besides it being unnecessary code, it would also be nice if we kept the handler as close as possible to the compat one above.

I am thinking the first option might be best, since all this code is still pretty immature and it's better to just get things right/clean instead of maintaining perfect compatibility.  Thoughts? @jonparrott @dhermes @tseaver

**Comment by dhermes** [comment]
Instead of `get_logging_handler(client)` you could have `client.get_default_handler()` or similar name. We already have precedent for this with ADC.

**Comment by jonparrott** [comment]
I think it's a good idea to keep the existing ability to use a particular handler type and then have a helper function to return a 'default' one for the current environment. This matches the ADC approach.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
