### ISSUE TITLE
Circle CI discussion

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2605]
Should we use Circle CI? It seems pretty great (e.g. they allow SSH access to VMs after jobs complete)

I can disable the webhook in https://github.com/GoogleCloudPlatform/google-cloud-python/settings/hooks. The Payload URL is https://circleci.com/hooks/github, content-type is `application/x-www-form-urlencoded`, the Secret is a secret and the events used are

![screen_shot_001](https://cloud.githubusercontent.com/assets/520669/19695727/269dcb90-9a99-11e6-8bea-f99d94afaaae.png)

I'm also not sure why it's a webhook instead of in https://github.com/GoogleCloudPlatform/google-cloud-python/settings/installations (it shows up in the list of services to add)

---

From @tseaver in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2602#issuecomment-256055599

Can we disable the Circle CI bit until we fix its config?  Issues with it:
- The bit which skips `system-tests` for PRs is Travis-specific.
- It is barfing trying to find the correct Python 3.4 / 3.5 interpreter.

**Comment by daspecster** [comment]
So Circle has been finishing first half the time and Travis has been finishing first the other half of the time.  Travis is last during peak hours and circle is last during off-peak hours.

My vote at this point would be to drop Travis at this point just because circleci is more consistent.

**Comment by dhermes** [comment]
@daspecster That is the plan, but I need to get some spare cycles to finish porting our tooling.
