### ISSUE TITLE
Drop Connection classes (or at least make them non-public)

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2606]
The Logging / Pub/Sub / Datastore packages all have custom `API` objects that do that actual communication with the server. Now `Connection` is just a container for some members that those API objects require. Should we remove these base classes and make any shared behavior from the core `Connection` into helper **functions** instead of a shared base?

**Comment by dhermes** [comment]
Just chatted with @tseaver about this and we both seem to agree, the answer is "yes" to "Should we...".

Sending a PR for BigQuery, Datastore, Logging, Pub/Sub and Storage ASAP.

**Comment by jonparrott** [comment]
With the switch to google-auth, there is even less code in the `Connection` class - more fuel for this fire.
