### ISSUE TITLE
TimestampRange should allow customization of inclusive/exclusive

### ISSUE THREAD

**Issue by destijl** [GoogleCloudPlatform/google-cloud-python#2608]
Currently TimestampRange supports only inclusive lower, exclusive upper:
https://googlecloudplatform.github.io/google-cloud-python/stable/bigtable-row-filters.html#google.cloud.bigtable.row_filters.TimestampRange

My application expects inclusive upper timestamp bounds. The super hacky workaround I currently have to make it work with bigtable is adding 1ms (minimum timestamp resolution) onto all end timestamps.

It would be great if I could control this behavior, just as for the value range filter:
https://googlecloudplatform.github.io/google-cloud-python/stable/bigtable-row-filters.html#google.cloud.bigtable.row_filters.ValueRangeFilter

**Comment by dhermes** [comment]
We are at the mercy of [the spec][1]

```
// Specified a contiguous range of microsecond timestamps.
message TimestampRange {
  // Inclusive lower bound. If left empty, interpreted as 0.
  int64 start_timestamp_micros = 1;

  // Exclusive upper bound. If left empty, interpreted as infinity.
  int64 end_timestamp_micros = 2;
}
```

For now, your workaround is what I would recommend, but we can certainly consider adding this feature.

[1]: https://github.com/googleapis/googleapis/blob/6c1d6d4067364a21f8ffefa3401b213d652bf121/google/bigtable/v2/data.proto#L146-L153
