### ISSUE TITLE
Working on storage snippets

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#2609]
Reference: https://github.com/daspecster/google-cloud-python/blob/add-storage-snippets/docs/storage_snippets.py

A few questions I have...
1. Should I make a PR to merge in at this point since we're not currently running snippets AFAICT?
2. If we're running these as system tests(which makes sense to me), I'm not sure how to handle things like email addresses for users and other account information([example](https://github.com/daspecster/google-cloud-python/blob/42e40cfc5b1bc8b91ecdcf603ae16485f09618ab/docs/storage_snippets.py#L71)).
3. If I should make mocks instead of hitting the service, it seems like that defeats the purpose unless I can inherit from the real class and just override the methods or some similar strategy?

**Comment by dhermes** [comment]
1. Yes
1. "If we're running these as system tests" --> then run them like the storage system tests. Does adding a "fake address" like `'me@example.org'` work? If not, create a variable `user_address` outside the snippet and then just put `acl.user(user_address).grant_read()` inside the snippet.
1. @tseaver Has more opinions on this than I do.

**Comment by daspecster** [comment]
>"If we're running these as system tests" --> then run them like the storage system tests. Does adding a "fake address" like 'me@example.org' work? If not, create a variable user_address outside the snippet and then just put acl.user(user_address).grant_read() inside the snippet.

I looked at the storage system tests and those didn't seem to test the ACL settings.  The fake address didn't work as it's not a valid user when testing against live data. 

Wouldn't making the `user_address` variable make the snippet less readable?

**Comment by dhermes** [comment]
> Wouldn't making the `user_address` variable make the snippet less readable?

I don't think so, but maybe. If you think it does, you could 

- modify the grant that was added **after the snippet** to make sure you use a valid email address
- find a valid email address that is "public domain", e.g. `cloud-logs@google.com`
