### ISSUE TITLE
Bigtable and float values

### ISSUE THREAD

**Issue by dmitry-saritasa** [GoogleCloudPlatform/google-cloud-python#2614]
tried to store 0.73 as numeric value in bigtable cell and got this error:

``` python
TypeError: 0.67 could not be converted to bytes
```

**Trace**

``` python
/home/dmitry/Projects/demo/storm/libs/db/models.py in save(self, record, instance_id)
    205             for col in columns:
    206                 row.set_cell(
--> 207                     column_family, col, getattr(record, col, None)
    208                 )
    209         row.commit()
/home/dmitry/Projects/experiments/storm/petrel/chapter3/example1/petrel/lib/python2.7/site-packages/gcloud/bigtable/row.pyc in set_cell(self, column_family_id, column, value, timestamp)
    300         """
    301         self._set_cell(column_family_id, column, value, timestamp=timestamp,
--> 302                        state=None)
    303 
    304     def delete(self):

/home/dmitry/Projects/experiments/storm/petrel/chapter3/example1/petrel/lib/python2.7/site-packages/gcloud/bigtable/row.pyc in _set_cell(self, column_family_id, column, value, timestamp, state)
    126         if isinstance(value, six.integer_types):
    127             value = _PACK_I64(value)
--> 128         value = _to_bytes(value)
    129         if timestamp is None:
    130             # Use -1 for current Bigtable server time.

/home/dmitry/Projects/experiments/storm/petrel/chapter3/example1/petrel/lib/python2.7/site-packages/gcloud/_helpers.pyc in _to_bytes(value, encoding)
    457         return result
    458     else:
--> 459         raise TypeError('%r could not be converted to bytes' % (value,))
    460 
    461 
```

Checked the source code and see that only int or bytes are allowed to be stored. Therefore I have to convert float value into INT *i.e. 0.63 *100 = 63 and store that as a value

Am I correct and why only ints/bytes are allowed?

thanks,
Dmitry

**Comment by dhermes** [comment]
@dmitry-saritasa Thanks for filing.

1. Can you provide the code you used to trigger this error?
1. The backend allows **only** `bytes` but has special methods for counters, which are [stored][3] as `>q` (i.e. a [`long long` / 64-bit signed integer][1] in [big-endian][2] byte order).
1. If you'd like to store a Python `float` (`double`), you'd need to convert to `bytes` e.g. `struct.pack('>d', 0.75)`

----

@jonparrott WDYT of supporting types other than bytes or integers? It'd be easy enough to do, but may go against the spirit of the API.

[1]: https://docs.python.org/2/library/struct.html#format-characters
[2]: https://docs.python.org/2/library/struct.html#byte-order-size-and-alignment
[3]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/0f8fdb6d2360e937dfba395b142de42c618eb228/bigtable/google/cloud/bigtable/row.py#L31

**Comment by dmitry-saritasa** [comment]
clear - thanks @dhermes

**Comment by jonparrott** [comment]
@dhermes I think it affords discussion - Python's representation of other types may not work if the data is read in another language.

**Comment by lukesneeringer** [comment]
I am going to declare bankruptcy on this issue.
