### ISSUE TITLE
pubsub throws when listing topics when there are no topics

### ISSUE THREAD

**Issue by BrandonY** [GoogleCloudPlatform/google-cloud-python#2616]
Steps to reproduce:

1. Create a project and enable it for Cloud Pub/Sub
2. Set up your application default credentials to grant access.
3. Call gcloud.pubsub.Client(project='your-project').list_topics()

What should happen:

Function returns []

What happens:

Traceback (most recent call last):
  File "example.py", line 61, in Main
    topics, token = client.list_topics()
  File "gcloud/pubsub/client.py", line 80, in list_topics
    for resource in resp['topics']]
KeyError: 'topics'

Why:

It seems that Cloud Pub/Sub returns {} when listing topics instead of {"topics":[]}

**Comment by dhermes** [comment]
@BrandonY This has most likely been fixed for a while, can you upgrade from `gcloud` to `google-cloud` and then check if it fails:

```
pip install google-cloud
```

You'll need your imports like `gcloud.pubsub` to change to `google.cloud.pubsub`

**Comment by dhermes** [comment]
Discussed off-thread. Closing.
