### ISSUE TITLE
max_bad_records not being set

### ISSUE THREAD

**Issue by mghamsar** [GoogleCloudPlatform/google-cloud-python#2622]
I'm importing an entire folder from Google Cloud Storage into BigQuery. I set the max_bad_records = 10000 but I still get an error even though I had 3 lines in my entire folder that didn't match the BigQuery Schema 
1. OS type and version

Ubuntu 16 running from a docker image 
1. Python version and virtual environment information `python --version`

Python 2.7.12
1. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
## pip show gcloud

Metadata-Version: 2.0
Name: gcloud
Version: 0.18.3
Summary: API Client library for Google Cloud
Home-page: https://github.com/GoogleCloudPlatform/gcloud-python
Author: Google Cloud Platform
Author-email: jjg+gcloud-python@google.com
Installer: pip
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: grpc-google-logging-v2, six, protobuf, oauth2client, googleapis-common-protos, grpcio, grpc-google-pubsub-v1, google-gax, gax-google-logging-v2, gax-google-pubsub-v1, httplib2
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  License :: OSI Approved :: Apache Software License
  Operating System :: OS Independent
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Topic :: Internet
1. Code example

``` python
for hour in get_hour_codes():
    prefix = data_set_name+'/v1/'+hour
    bucket = storage_client.bucket(bucket_name)

    if(bucket.exists()):
      blobs = bucket.list_blobs(prefix=prefix)

      job_name = str(uuid.uuid4())
      has_data = False
      for blob in blobs:
            has_data = True

      if(has_data):
        job = bigquery_client.load_table_from_storage(job_name, table, 'gs://'+bucket_name+'/'+prefix+'/*')
        job.source_format = 'NEWLINE_DELIMITED_JSON'
        job.encoding = 'UTF-8'
        job.create_disposition = 'CREATE_IF_NEEDED'
        job.write_disposition = 'WRITE_APPEND'
        job.schema = schema
        job.max_bad_records = 10000

        job.begin()
```
1. Errors : 

```
[{u'reason': u'invalid', u'message': u'JSON parsing error in row starting at position 11535600 at file: gs://vm-hb-landscape/live/v1/2016-10-25-03/91-1477368068-vm-0.106.250.48-hour-landscape-2016102503.json.gz. Unexpected token'}, {u'reason': u'invalid', u'message': u'JSON parsing error in row starting at position 11184655 at file: gs://vm-hb-landscape/live/v1/2016-10-25-03/19-1477368068-vm-0.22.85.81-hour-landscape-2016102503.json.gz. Unexpected token'}, {u'reason': u'invalid', u'message': u'JSON parsing error in row starting at position 11189417 at file: gs://vm-hb-landscape/live/v1/2016-10-25-03/19-1477368068-vm-0.22.85.81-hour-landscape-2016102503.json.gz. Unexpected token'}]
```

**Comment by tseaver** [comment]
@mghamsar Can you print the result of calling `job._build_resource` here?  It appears to me that we are writing it correctly into the job configuration.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
