### ISSUE TITLE
Bigtable support for microsecond timestamp precision

### ISSUE THREAD

**Issue by destijl** [GoogleCloudPlatform/google-cloud-python#2626]
Currently Bigtable only supports millisecond timestamp precision:
https://cloud.google.com/bigtable/docs/reference/admin/rpc/google.bigtable.admin.v2#google.bigtable.admin.v2.Table.TimestampGranularity

My application expects microseconds, and I've had to make some clunky bug-prone adjustments to shoehorn it into working with milliseconds. It would be great to have microsecond precision.

**Comment by jgeewax** [comment]
I think this is a request for the Bigtable team-- not the Python client library, right?

We can support it once the Bigtable service supports it -- so we'll make sure to pass this feedback along to the core team, but nothing more that we can do for the Python client until then.

**Comment by destijl** [comment]
Is there a different github project I should file it in? I really just want an open bug reference to put in my code so the next maintainer has somewhere to look to see if they can undo the millisecond hacks. Now this is closed it will probably never get updated even if the feature is added.

**Comment by dhermes** [comment]
@jgeewax We **can** support it in our code, and we already [have precedent][1] for switching between inclusive or exclusive. (That's not to say the backend couldn't make this a feature).

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/b2662c1ac0e91b4c2193f4ac0b929aa957b8cfc4/bigtable/google/cloud/bigtable/row_filters.py#L331-L341

**Comment by dhermes** [comment]
DERP misread the issue. NVM

**Comment by mbrukman** [comment]
@destijl, thank you for your feedback!

You can submit feature requests for Google Cloud Bigtable via [UserVoice](https://googlecloudplatform.uservoice.com/forums/302607-cloud-bigtable), along with any other Google Cloud Platform products. You can also discuss the product via [`google-cloud-bigtable-discuss@`](https://groups.google.com/group/google-cloud-bigtable-discuss). This GitHub repo is for the Python libraries specifically, not the product itself.

I'm the product manager for Bigtable, so your request has been heard, but feel free to still submit it via the forum above and others will vote it up if they would also find it useful.

I will endeavor to update this bug if/when this feature is implemented in the service, at which point we can update the client libraries accordingly.

**Comment by destijl** [comment]
@mbrukman thanks, done!
https://googlecloudplatform.uservoice.com/forums/302607-cloud-bigtable/suggestions/16844260-support-microsecond-timestamp-precision
