### ISSUE TITLE
'ImportError: No module named gcloud' error with Dataproc Service and pip: command not found

### ISSUE THREAD

**Issue by vinayakagrawal88** [GoogleCloudPlatform/google-cloud-python#2635]
I am trying the example for Google dataproc Spark/Bigquery listed [here](https://cloud.google.com/dataproc/docs/tutorials/bigquery-sparkml).

When I run the first python script I get the error:

```
ImportError: No module named gcloud
```

Based on google results, I thought of installing `gcloud` with `pip` but my master server doesnt have pip installed either. 

```
pip: command not found
```

Environment : 

```
Google Cloud DataProc - 1 Master, 2 Worker nodes with Debian/Linux
Google Cloud SDK [130.0.0]

Platform: [Linux, x86_64]
Python Version: [2.7.9 (default, Jun 29 2016, 13:08:31)  [GCC 4.9.2]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]
Installation Root: [/usr/lib/google-cloud-sdk]
Installed Components:
  core: [2016.10.07]
  core-nix: [2016.10.07]
  gcloud: []
  gsutil-nix: [4.21]
  beta: [2016.10.07]
  gsutil: [4.21]
  bq: [2.0.24]
  alpha: [2016.10.07]
  bq-nix: [2.0.24]
System PATH: [/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games]
Cloud SDK on PATH: [False]

Installation Properties: [/usr/lib/google-cloud-sdk/properties]
User Config Directory: [/home/vinayak.cmu/.config/gcloud]
Active Configuration Name: [default]
Active Configuration Path: [/home/vinayak.cmu/.config/gcloud/configurations/config_default]
```

Running 

```
try:
    import gcloud
except ImportError
    import sys
    print(sys.path)
```

I found that there is no gcloud.pyc in /usr/lib/python2.7.

Please help.

**Comment by vinayakagrawal88** [comment]
[UPDATE]:
Solved the pip issue using 
`wget get-pip.py` 
as documented [https://packaging.python.org/installing/](here). 
Ran 
`sudo pip install gcloud`

This resolved the above issue. However now when I run the python script from the example, I get this error 
`vinayak.cmu@cluster-1-m:~/google-cloud-spark-bigquery$ ./gen_regression_input.py`
`Traceback (most recent call last):`
  `File "./gen_regression_input.py", line 24, in <module>
    bq = bigquery.Client()`
  `File "/usr/local/lib/python2.7/dist-packages/gcloud/client.py", line 185, in __init__
    _ClientProjectMixin.__init__(self, project=project)`
  `File "/usr/local/lib/python2.7/dist-packages/gcloud/client.py", line 141, in __init__
    project = self._determine_default(project)`
`  File "/usr/local/lib/python2.7/dist-packages/gcloud/client.py", line 154, in _determine_default
    return _determine_default_project(project)`
 ` File "/usr/local/lib/python2.7/dist-packages/gcloud/_helpers.py", line 273, in _determine_default_project
    project = _default_service_project_id()`
`  File "/usr/local/lib/python2.7/dist-packages/gcloud/_helpers.py", line 206, in _default_service_project_id
    return config.get('core', 'project')`
 ` File "/usr/lib/python2.7/ConfigParser.py", line 340, in g
    raise NoOptionError(option, section)`
`ConfigParser.NoOptionError: No option 'project' in section: 'core'`

I checked my project configuration and project has the correct value in core as show below 
`vinayak.cmu@cluster-1-m:~/google-cloud-spark-bigquery$ gcloud config list`
`Your active configuration is: [default]`

`[core]`
`account = XXXXXXXXXX-compute@developer.gserviceaccount.com`
`disable_usage_reporting = True`
`project = vin-compute-engine-1-oct26`

**Comment by dhermes** [comment]
@jonparrott Do you know who owns that sample? It recommends installing `google-cloud` but then imports from `gcloud`

**Comment by jonparrott** [comment]
Maybe @elibixby knows? (I'm not very involved in bigtable/machine learning stuff)

**Comment by elibixby** [comment]
Yeah the dataproc team owns it but it needs to be updated badly. That connector doesn't even work well (better to just use google-cloud-python to query bigquery directly).
