### ISSUE TITLE
Allow logging metrics to be created with LogEntry V1 syntax

### ISSUE THREAD

**Issue by micolous** [GoogleCloudPlatform/google-cloud-python#2662]
At present, it is [only possible to create a new Log metric with V2 syntax](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging/metric.py#L41).

The [default behaviour of the API is to use version="V2" when version is not specified](https://cloud.google.com/logging/docs/api/reference/rest/Shared.Types/LogMetric).

As a result, a user who tries to create a metric using the old syntax will encounter an error:

```python
from google.cloud import logging
client = logging.Client(project='my-example-project')
metric = client.metric('my-example-metric', 'metadata.serviceName="compute.googleapis.com"', 'All GCE logs')
metric.create()
```

```
ValueError: RPC failed: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Field not found: 'metadata'.)>
```

Given that this behaviour persists with the [API Explorer](https://cloud.google.com/logging/docs/api/reference/rest/v2/projects.metrics/create) when not specifying version, the cause is that my filter is in V1 syntax, but the server expects V2.

This is made more confusing as the Cloud Console [still uses the V1 syntax](https://cloud.google.com/logging/docs/api/v2/migration-to-v2#logs_viewer), so a user who is trying to copy a filter they have crafted in the Console will be greeted by this error when using `google-cloud-python`.

`google-cloud-python` should add the parameter `version` to the `Metric` class in order to resolve this issue.

Workarounds:
- [Migrate filters to V2 syntax.](https://cloud.google.com/logging/docs/api/v2/migration-to-v2#v2-logentry-changes)
- Use `google-apis-client-python` instead of `google-cloud-python`.

Package version:
- google-cloud==0.20.0
- google-cloud-logging==0.20.0

**Comment by dhermes** [comment]
@waprin Can you weigh in here? This is beyond my expertise

**Comment by waprin** [comment]
Logging is moving to v2, v1 is deprecated, so just use the v2 syntax. The console is really overdue to migrate but it should be coming soon. No reason to add a bunch of code to support a deprecated version. Apologies for any pain the migration has caused.

**Comment by micolous** [comment]
All the existing log entries are V1 -- so right now it's impossible to copy metrics from one project to another using the `google-cloud-python` library.

There's also no way to explicitly detect that an existing metric is using V1, short of trying to look for the old syntax, as that field is also dropped by the library.

As a result, you have a bunch of metrics that get silently broken, that you can only fix by manually migrating them to the new syntax.
