### ISSUE TITLE
Please update README with Alpha->Beta->GA timelines for each library

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/google-cloud-python#2667]
gcloud-java lists alpha/beta status for each library but not timelines to GA:
  https://github.com/GoogleCloudPlatform/google-cloud-java
also see
 https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1369

**Comment by dhermes** [comment]
@omaray Assigned to you so you can weigh in here.

**Comment by omaray** [comment]
Not in the plans to add an exact timeline. Would something "more ball parky" make sense?

**Comment by salrashid123** [comment]
Yes, i'd say quarter-level would help (it'll atleast give some indication on planning if GA label is a hard requirement)  [issue#1363](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1369#issuecomment-288846182)
