### ISSUE TITLE
vision API manual detection documented but not implemented

### ISSUE THREAD

**Issue by ptone** [GoogleCloudPlatform/google-cloud-python#2697]
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/docs/vision-usage.rst#manual-detection

wah?

https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/vision/google/cloud/vision/image.py#L88

documentation written by @daspecster
https://github.com/GoogleCloudPlatform/google-cloud-python/commit/95a55c145bd2e16e80e34e180682932c8a16199a

**Comment by daspecster** [comment]
@ptone, sorry about that. There was a lot of froth in deciding the surface and this slipped by me.

In the meantime you can use [`client.annotate`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/15eb09183333f4c3cebc59bd9600a43ae6c3715c/vision/google/cloud/vision/client.py#L85) to do multiple detections.  I will get a PR to correct this ASAP!
