### ISSUE TITLE
google-cloud-storage==0.20.0 on GAE will get ImportError

### ISSUE THREAD

**Issue by brian1125** [GoogleCloudPlatform/google-cloud-python#2739]
1.  OS type and version: GAE (debian?)
1.  Python version : python 3.4  to run Flask
1.  google-cloud-python version:
    - google-api-python-client (1.5.5)
    - google-cloud-core (0.21.0)
    - google-cloud-storage (0.20.0)
    - googleapis-common-protos (1.5.0)
1.  Stacktrace
    ```python
    /env/lib/python3.4/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
      .format(x=modname), ExtDeprecationWarning
    Traceback (most recent call last):
      File "main.py", line 1, in <module>
        from activation import app
      File "/home/vmagent/app/activation/__init__.py", line 10, in <module>
        from google.cloud import storage
      File "/env/lib/python3.4/site-packages/google/cloud/storage/__init__.py", line 42, in <module>
        from google.cloud.storage.batch import Batch
      File "/env/lib/python3.4/site-packages/google/cloud/storage/batch.py", line 30, in <module>
        from google.cloud.storage.connection import Connection
      File "/env/lib/python3.4/site-packages/google/cloud/storage/connection.py", line 17, in <module>
        from google.cloud import connection as base_connection
    ImportError: cannot import name 'connection'
    ```

1.  Steps to reproduce:
    deploy app engine on flexible environment
1.  Code example
    ```python
    from flask import Flask
    from flask.ext.sqlalchemy import SQLAlchemy
    from google.cloud import storage   # <== ImportError 
    # ... other code ...
    ```

----

one week ago, it's work to deploy the same code for me, but today it's always show there is possible a unhealthy code...
therefore, i deep into check why it dosen't work, so i found that google-cloud-storage (0.20.0) should be upgraded to 0.21.0, but i don't know why it was work for google-cloud-storage (0.20.0)

requirements.txt with ImportError after running as following:
Flask==0.11.1
Flask-SQLAlchemy==2.1
gunicorn==19.6.0
PyMySQL==0.7.9
requests==2.11.1
azure==1.0.3
pymemcache==1.3.7
google-cloud-storage==0.20.0
google-api-python-client==1.5.5 

requirements.txt without ImportError after running as following:
Flask==0.11.1
Flask-SQLAlchemy==2.1
gunicorn==19.6.0
PyMySQL==0.7.9
requests==2.11.1
azure==1.0.3
pymemcache==1.3.7
google-cloud-storage==0.21.0
google-api-python-client==1.5.5

**Comment by dhermes** [comment]
@brian1125 We did a release of `0.21.0` yesterday both for `google-cloud-storage` and `google-cloud-core` (storage depends on core).

The import

```
 from google.cloud import connection as base_connection
```

comes from core and moved between releases.

So the error is because you have a version of core (`0.21.0`) that is not meant to work with the previous version of storage (`0.20.0`). Please upgrade.

----

It's worth noting that this is partially our "fault" for not putting an upper bound on the `google-cloud-core` dependency in the storage `setup.py` file

**Comment by brian1125** [comment]
@dhermes  Thank you for your explanation.
