### ISSUE TITLE
Update to Language v1

### ISSUE THREAD

**Issue by bjwatson** [GoogleCloudPlatform/google-cloud-python#2747]
### What
Update the hand-written code to Language v1, which was publicly announced yesterday (11/15). The new GAPIC code is in a [PR](https://github.com/googleapis/api-client-staging/pull/104), which will be published to PyPI as soon as its approved.

### Why
Language v1beta1 has been replaced by v1 as of Tuesday 11/15. It has some additional features we want to support.

This should be done soon, so that we can update the public documentation and samples to reference the `google-cloud-language` library.

**Comment by jmdobry** [comment]
Friendly 🐶  notification, this is blocking GoogleCloudPlatform/python-docs-samples#668

**Comment by bjwatson** [comment]
Thanks for the heads up @jmdobry. Once I get LGTM on https://github.com/googleapis/api-client-staging/pull/106, I'll publish Python GAPIC for Language v1, and then @dhermes can take a look at what's needed in the hand-written code.

**Comment by dhermes** [comment]
@bjwatson FWIW the current implementation is JSON-over-HTTP only, so an update isn't blocked on the GAPIC release. (To check if a given API is using GAPIC yet, just [check the deps][1].)

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/a10cf56445b51750c4d9bc1f3b5bde2522f92caf/language/setup.py#L52-L54

**Comment by bjwatson** [comment]
Ok, thanks @dhermes. At least you'll have it when you add the gRPC path. :)

**Comment by gguuss** [comment]
Friendly ping, we're still waiting on this.

**Comment by jmdobry** [comment]
To switch to NL V1 does google-cloud-python also need to switch to using the GAPIC code, or can just the JSON-over-HTTP stuff get updated?

**Comment by dhermes** [comment]
Just the JSON-over-HTTP stuff can get updated. What is the delta between the old and new versions? Is it as simple as changing [one line][1]?

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/f0950ca479e2fe78a055e207d97da69e84956fd3/language/google/cloud/language/connection.py#L26

**Comment by jmdobry** [comment]
Seems there was at least one breaking change (from the google-cloud-node PR updating to NL V1):

* New rcp `AnalyzeSyntax` in the form of `document#detectSyntax`
* Sentences can now contain sentiments
* `sentiment.polarity` was renamed to sentiment.score
* partOfSpeech received 11 new attributes
* English, Japanese and Spanish now supported for all features.

See GoogleCloudPlatform/google-cloud-node#1783
