### ISSUE TITLE
BigQuery authentication error while using from_service_account_p12 method

### ISSUE THREAD

**Issue by tuanavu** [GoogleCloudPlatform/google-cloud-python#2752]
I have issues while trying to authenticate to BigQuery using the `from_service_account_p12()` method

1. Mac (OSX El Capitan) Version 10.11.6
2. Anaconda Python 2.7.11 :: Continuum Analytics, Inc. in virtual environment
3. google-cloud==0.20.0
4. Steps to reproduce

```python
from google.cloud import bigquery
from oauth2client.client import GoogleCredentials

path_to_p12_keyfile = "my_path_to_p12_keyfile"
client_email  = "my_client_email"

client = bigquery.Client.from_service_account_p12(client_email, path_to_p12_keyfile)
```

5. Errors

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-10-c0083c5cfc71> in <module>()
----> 1 client = bigquery.Client.from_service_account_p12(client_email, path_to_p12_keyfile)
      2 
      3 # print client.project

/Users/tvu/anaconda/envs/test-env/lib/python2.7/site-packages/google/cloud/client.pyc in from_service_account_p12(cls, client_email, private_key_path, *args, **kwargs)
     92             raise TypeError('credentials must not be in keyword arguments')
     93         credentials = ServiceAccountCredentials.from_p12_keyfile(
---> 94             client_email, private_key_path)
     95         kwargs['credentials'] = credentials
     96         return cls(*args, **kwargs)

/Users/tvu/anaconda/envs/test-env/lib/python2.7/site-packages/oauth2client/service_account.pyc in from_p12_keyfile(cls, service_account_email, filename, private_key_password, scopes, token_uri, revoke_uri)
    333             service_account_email, private_key_pkcs12,
    334             private_key_password=private_key_password, scopes=scopes,
--> 335             token_uri=token_uri, revoke_uri=revoke_uri)
    336 
    337     @classmethod

/Users/tvu/anaconda/envs/test-env/lib/python2.7/site-packages/oauth2client/service_account.pyc in _from_p12_keyfile_contents(cls, service_account_email, private_key_pkcs12, private_key_password, scopes, token_uri, revoke_uri)
    288             private_key_password = _PASSWORD_DEFAULT
    289         if crypt.Signer is not crypt.OpenSSLSigner:
--> 290             raise NotImplementedError(_PKCS12_ERROR)
    291         signer = crypt.Signer.from_string(private_key_pkcs12,
    292                                           private_key_password)

NotImplementedError: 
This library only implements PKCS#12 support via the pyOpenSSL library.
Either install pyOpenSSL, or please convert the .p12 file
to .pem format:
    $ cat key.p12 | \
    >   openssl pkcs12 -nodes -nocerts -passin pass:notasecret | \
    >   openssl rsa > key.pem

```

**Comment by jonparrott** [comment]
I would highly suggest downloading a new private key in `.json` format.

Alternatively, you'll need to install `pyopenssl` in order for `oauth2client` to read p12 files.

(Note that p12 support is deprecated and will be removed "soon").

**Comment by dhermes** [comment]
@tuanavu We are happy to help you transition over to a new key, but supporting the PKCS12 keys is no longer a priority.

**Comment by tuanavu** [comment]
Hi @dhermes,

I am taking this issue seriously as my current company is using P12 key for authentication to Google service. I have another question from my colleague:

"Is this issue only apply to Python? Or also other languages Google support like Java, PHP, ..? Since we currently have a lot of Java back-end services using P12 key authentication".

Thanks,
Tuan

**Comment by jonparrott** [comment]
@tuanavu the cloud console has long preferred using the `json` key format over `p12`. It's still possible to generate a `p12` file using the console and it's even possible to convert the `json` key to `p12` (and vice-versa) if necessary.

As far as I know, Java will continue to support both, while Python will not support p12 (directly) in the near future.

**Comment by tuanavu** [comment]
Hi @jonparrott,

First of all, thanks for the info. Can you direct me to page of how to convert p12 to json (and vice-versa)?

**Comment by dhermes** [comment]
I recommend you download a new key (no conversion) necessary. To convert to a PCKS8 / PEM key:
https://github.com/google/oauth2client/blob/f7f656d6aa0ac111a6692ded3eaaa7b1caf1fedc/oauth2client/_pure_python_crypt.py#L32-L39

But the JSON key has lots more data in it (I recommend you create and download a JSON key and inspect the contents).

**Comment by jonparrott** [comment]
Echoing @dhermes, it's highly recommended to just download a new `json` key for an existing service account if needed.
