### ISSUE TITLE
Cannot get table schema

### ISSUE THREAD

**Issue by tuanavu** [GoogleCloudPlatform/google-cloud-python#2756]
I want to get the schema of any tables in BigQuery in json format.

However, I cannot get the table schema of a table using the gcloud api. It just returns an empty list.

1. Mac (OSX El Capitan) Version 10.11.6
2. Anaconda Python 2.7.11 :: Continuum Analytics, Inc. in virtual environment
3. google-cloud==0.20.0
4. Code example

```python
dataset = client.dataset(my_dataset)
table = dataset.table(my_table)

print table.schema
```

5. Output

```
[]
```

**Comment by daspecster** [comment]
@tuanavu, you may need to create the dataset first with `dataset.create()`.

See: https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-usage.html#dataset-operations

You could also call `datasets, token = client.list_datasets()   # API request` to see your available datasets.

**Comment by tuanavu** [comment]
Hi @daspecster,

The dataset and table is already existed in BigQuery. I can print out the table name and description. Only the table schema returns an empty list. That is weird.

```python
print table.dataset_name
print table.name
print table.schema
```

Output
```
my_dataset_name
my_table_name
[]
```

Tuan

**Comment by ahogit** [comment]
i am also having the same issue on 0.21

**Comment by tuanavu** [comment]
Thanks @ahogit,

I was able to get the schema after running `table.reload()`. It feels like a bug to me.

**Comment by tseaver** [comment]
@tuanavu Creating a `Table` instance on the client side does not automagically fetch any server-side data, even if the table already exists on the server.  The call to `reload()` is exactly how you are supposed to fetch that information.

**Comment by ahogit** [comment]
@tseaver 

I have the same issue with `Table` objects that I get back from `list_tables()`, is that also expected?

**Comment by mdmiller53** [comment]
@tseaver i've also just run into this problem.  the (documentation)[https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-table.html#google.cloud.bigquery.table.Table] says 'API call: refresh table properties via a GET request'.  to me, refresh means that the information is already fetched and it needs to be refreshed because something else has updated it.  and a call that needs server side information should then go to the server and get it, without an additional call (which, if needed for some reason, should be called something like 'get_serverside_data()'

**Comment by tseaver** [comment]
@ahogit Unfortunately, the items returned by the [`tables/list` API](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/list#response) do not contain the full `Table` resource:  they have only the barest identifying fields for the table.  The call to `reload()` is thus necessary.

@mdmiller53 I'm sorry that the docs aren't as helpful as we would like.  I think we could tweak the docstring to clarify, but we're unlikely to rename the `reload()` method at this point.

**Comment by mdmiller53** [comment]
@tseaver thanks!  update to docs would be great, i wouldn't have thought of trying the reload() method
