### ISSUE TITLE
Is google.cloud.datastore.query.Iterator#next_page() no longer supported?

### ISSUE THREAD

**Issue by getumen** [GoogleCloudPlatform/google-cloud-python#2759]
I have a question.

In v0.21.0, Iterator#_next_page() is private method.
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/datastore/google/cloud/datastore/query.py#L482

Until v0.20.0, Iterator#next_page() is public method.
Is google.cloud.datastore.query.Iterator#next_page() no longer supported?

**Comment by dhermes** [comment]
@getumen The implementation has changed, we moved to the base iterator class: http://google-cloud-python.readthedocs.io/en/latest/iterators.html

You can use it as follows:

```python
iterator = query.fetch(...)
pages = iterator.pages
page = next(pages)
entities = list(page)
print(iterator.next_page_token)
```

**Comment by dhermes** [comment]
Let me know if there are other concerns, and I'm happy to re-open.

**Comment by getumen** [comment]
thx
