### ISSUE TITLE
Memory leaked as all network endpoints were not shut down

### ISSUE THREAD

**Issue by HaipengSu** [GoogleCloudPlatform/google-cloud-python#2760]
I got an interesting scenario when using google-cloud-pubsub.

I would like to get all the topics in the pubsub, and my code is,
```
from google.cloud import pubsub
def list_topics(pubsub_client):
  """Lists all Pub/Sub topics in the current project."""
  topics= pubsub_client.list_topics()
  for topic in topics:
    print topic.name

pubsub_client=pubsub.Client()
list_topics(pubsub_client)
```
I keep getting message ` E1121 09:40:01.036257519 10741 network_status_tracker.c:48] Memory leaked as all network endpoints were not shut down `.

However, if I use `pubsub_client=pubsub.Client()` inside the function,
```
from google.cloud import pubsub
def list_topics():
   """Lists all Pub/Sub topics in the current project."""
  pubsub_client=pubsub.Client()
  topics= pubsub_client.list_topics()
  for topic in topics:
     print topic.name

list_topics()
```
Then, the message disappeared.

I noticed that there are similar questions before, but couldn't figure it out.

Python Version --2.7.12   Google-cloud Version --0.21.0

Thank you.

**Comment by daspecster** [comment]
Thanks @HaipengSu for reporting!

I believe this issue is actually being tracked in https://github.com/grpc/grpc/issues/7849.

That is interesting that the message goes away when in the function. This probably has something to do with the scope and how the logging message is configured.

**Comment by HaipengSu** [comment]
@daspecster 
thx, hopefully this will help to find the issue.

**Comment by samskillman** [comment]
I ran into this as well. I'm working around it until the grpc bug is fixed by adding an atexit deletion of any client/subscription/topics that I've created. Something like this:
```
import atexit
from google.cloud import pubsub

client = pubsub.Client()
for topic in client.list_topics():
    print topic.name

def cleanup():
    global client, topic
    del client, topic
atexit.register(cleanup)
```

**Comment by HaipengSu** [comment]
@samskillman Thank you, I will try this out.

**Comment by dhermes** [comment]
@samskillman @HaipengSu `grpcio==1.0.2` has fixed the problem
