### ISSUE TITLE
0.21.0 documentation is missing

### ISSUE THREAD

**Issue by micolous** [GoogleCloudPlatform/google-cloud-python#2763]
0.21.0 was released recently (~1 week ago).  It introduces several backward-incompatible changes, which are only mentioned in the release notes.

However the documentation has not been updated, and still references 0.20.0 and the old API:

https://googlecloudplatform.github.io/google-cloud-python/stable/

It is also unclear what version of the library the documentation is for by reading the docs, because the Sphinx flags for version numbering have not been used.

**Comment by dhermes** [comment]
That's 100% my fault, I canceled the build: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/175876145

Will send a PR to update the docs right meow.

Sorry for the confusion @micolous and big ups for filing the issue!

**Comment by dhermes** [comment]
Docs updated, closing out issue. @micolous LMK if I should re-open.
