### ISSUE TITLE
maximum_billing_tier is not supported for synchronous jobs

### ISSUE THREAD

**Issue by Temikus** [GoogleCloudPlatform/google-cloud-python#2766]
This leads to inability to execute synchronous High Performance queries with this library, as the jobs will have the default maximum_billing_tier of the project (which is usually 1).

Relevant code:
```
class _SyncQueryConfiguration(object):
    """User-settable configuration options for synchronous query jobs.
    Values which are ``None`` -> server defaults.
    """
    _default_dataset = None
    _dry_run = None
    _max_results = None
    _timeout_ms = None
    _preserve_nulls = None
    _use_query_cache = None
    _use_legacy_sql = None
```

```
λ pip show gcloud                                                                                                                                               (1)
Name: gcloud
Version: 0.18.3
Summary: API Client library for Google Cloud
Home-page: https://github.com/GoogleCloudPlatform/gcloud-python
Author: Google Cloud Platform
Author-email: jjg+gcloud-python@google.com
License: Apache 2.0
Location: /Users/temikus/Code/python/lib/python2.7/site-packages
Requires: httplib2, grpc-google-pubsub-v1, google-gax, six, gax-google-logging-v2, protobuf, grpcio, oauth2client, googleapis-common-protos, grpc-google-logging-v2, gax-google-pubsub-v1
```

**Comment by daspecster** [comment]
@Temikus, I noticed that you're using `gcloud` instead of `google-cloud` and you may want to update to solve this problem.

In the newer version you can see how the `maximum_billing_tier` is handled.
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/115748814bf6a59d99c13e070dfdcfbdec5e865d/bigquery/google/cloud/bigquery/job.py#L1030

Let us know if that doesn't resolve the issue!

**Comment by daspecster** [comment]
Digging into this more, I see that upgrading probably won't help your specific issue, but it would be a good idea to upgrade anyway.

**Comment by tseaver** [comment]
@Temikus The [back-end docs for `jobs.query`](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query) don't have a field for `maximumBillingTier` (there is no "job configuration" structure at all, only a few top-level parameters).  Please reopen if you can point us to docs which show support for the feature on the back-end.

**Comment by Temikus** [comment]
Indeed, raw API doesn't support it either.
This is a backend issue then, I will follow-up internally.
