### ISSUE TITLE
Missing __init__.py

### ISSUE THREAD

**Issue by JimyRyan** [GoogleCloudPlatform/google-cloud-python#2767]
Hello,

I install google-cloud Python SDK 0.21.0 using the following command:

```
$ pip install \
> --no-cache-dir --upgrade --ignore-installed \
> --install-option="--prefix=$APP_PYTHON_VENDOR" \
> -r $APP_ROOT_PATH/requirements.txt
```

I got an error when I use the Google SDK like this:

```
python -c "import sys; sys.path.insert(1, '$VENDOR_ROOT_PATH'); print(sys.path); from google.cloud import bigquery;"
```

Bellow, the error message:

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named cloud
```

When I check the installed files, I see that `google` and `google/cloud` folders don't have any `__init__.py` files. 

My previous test work well if I have 2 `__init__.py` files on each folders.

1. OS: Linux Ubuntu 16.04 LTS x64
2. Python: 2.7.12 on fresh empty virtual environment
3. google-cloud-python: 0.21.0

**Comment by daspecster** [comment]
@JimyRyan thanks for reporting!

The reason there are no `__init__.py` files is because the library was switched to namespace packages (https://www.python.org/dev/peps/pep-0420).

Are you using a fresh environment? If not, I would recommend starting with a new virtualenv and see if the issue persists.

**Comment by JimyRyan** [comment]
Yes, it's a fresh virtual environment. But in my case, I don't install the google SDK inside the virtual env but one a specific path using the --install-option="--prefix=..." pip install option. On my application, I add the path where I have installed the SDK (.../lib/site-packages) to the sys.path

**Comment by dhermes** [comment]
Maybe our local packaging expert @jonparrott can chime in here?

**Comment by jonparrott** [comment]
Modifying sys.path isn't sufficient when namespace packages are involved.
In general, I highly recommend avoiding doing anything like this unless
completely necessary.

But, if you must, then use site.addsitedir instead.

**Comment by dhermes** [comment]
This issue seems stale?
