### ISSUE TITLE
Support for GCS Cloud Pub/Sub Notifications

### ISSUE THREAD

**Issue by BrandonY** [GoogleCloudPlatform/google-cloud-python#2768]
GCS has a new feature (currently in private alpha) wherein buckets can be configured to send object change notifications to Cloud Pub/Sub topics, rather than as push notifications to HTTPS endpoints.

For gcloud-python, I imagine such a feature might look like this:

    from gcloud import pubsub
    from gcloud import storage

    storage_client = storage.Client()
    pubsub_client = pubsub.Client()
    bucket = storage_client.get_bucket(BUCKET_ID)
    topic = pubsub_client.topic(TOPIC_ID)
    notification_config = bucket.send_notifications_to(topic)

**Comment by lukesneeringer** [comment]
I would prefer not update the client libraries to reflect private alpha features. If the feature is publicly available, feel free to raise a new issue.
