### ISSUE TITLE
Vision API should allow detecting multiple "feature types" in a single request

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#2769]
See: https://cloud.google.com/vision/pricing

Running "Explicit Content Detection" is free if done in the same request as "Label Detection". It appears from https://googlecloudplatform.github.io/google-cloud-python/stable/vision-usage.html that running `image.detect_safe_search()` immediately runs the request without having the chance to say I also want to run `image. detect_labels()` in the same HTTP request (to save money and an HTTP round-trip).

**Comment by daspecster** [comment]
Thanks for letting me know!

@tswast, we generally call this "batching" in the library. It should be in shortly after a refactor for adding manual `detect()`.

This can be tracked in https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2753.

I actually should have the PR for `detect()` tonight and then I think I have a good plan for batching as well.

**Comment by daspecster** [comment]
I guess I used the wrong syntax for `Closes` in the PR.

https://help.github.com/articles/closing-issues-via-commit-messages/#closing-multiple-issues

**Comment by ilsePit** [comment]
Is this also possible in the new version (v0.25.1 and up)? I cannot find this functionality in the documentation.
