### ISSUE TITLE
Datastore Key does not infer project

### ISSUE THREAD

**Issue by dmho418** [GoogleCloudPlatform/google-cloud-python#2772]
Minor issue in [https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/datastore/google/cloud/datastore/key.py#L386][1]
Documentation says something, but code does something else. Also nowhere in the documentation and examples it is stated that the Key must have a project set.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/8001d45c2f6cb3fcf583280874b141c83541c50a/datastore/google/cloud/datastore/key.py#L386

**Comment by dhermes** [comment]
@dmho418 Can you provide a code snippet with an error / unexpected behavior?

The primary / intended way of creating a key is via a `Client`: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/8001d45c2f6cb3fcf583280874b141c83541c50a/datastore/google/cloud/datastore/client.py#L425-L435

Would you like to see that made clearer in the `Key` docstring(s)?

**Comment by dmho418** [comment]
Oh so that's how it works.
At least for me it was not obvious that I should create the key from the Client instance.
Also in the docstring for Key, there are keys being created without naming the project (which throws an exception) https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/datastore/google/cloud/datastore/key.py#L30

**Comment by tseaver** [comment]
The example snippets should definitely show the explicit `project="foo"` keyword arg.  @dhermes how are they passing in your runner?

**Comment by dhermes** [comment]
@tseaver They aren't `doctest`-ed yet, but soon, soon, soon :grinning:

**Comment by lukesneeringer** [comment]
@dhermes Is this a problem with the docs, or the example snippets?

**Comment by jonparrott** [comment]
The samples all use `client_instance.key()` not `datastore.Key()`.

**Comment by lukesneeringer** [comment]
So, problem with internal docs, got it. Thanks.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
