### ISSUE TITLE
Pubsub message encoding performance could be improved?

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#2774]
See: #2773

I'm not sure on the data size limits for pubsub, but if they're significantly large then there are probably more performant message encoding strategies that could be implemented.

**Comment by daspecster** [comment]
Per https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2773#discussion_r89964329 and https://cloud.google.com/pubsub/quotas

```
Publish request	Total size must be no more than 10MB .
Must contain no more than 1,000 messages.
Message	The maximum number of attributes per message is 100.
The maximum size of an attribute key is 256 bytes.
The maximum size of an attribute value is 1024 bytes.
```

**Comment by danoscarmike** [comment]
Batching code is an elegant solution and is already in master and latest release
