### ISSUE TITLE
Bigquery Export split / break records sometime when exporting to gs

### ISSUE THREAD

**Issue by vrcs** [GoogleCloudPlatform/google-cloud-python#2781]
Hi

Noticed some strange issues since some days, that the python'-google-cloud-module "extract_table_to_storage" is behaving oddly, it sometimes it splits the records randomly into 2 lines, and its would be difficult to process the exported for because of the column mismatch /wrong data type or mostly with un-enclosed quotes. 

But when queried from Bigquery the actual row looks perfect .
Exampl :-  data from the exported CSV file with WEB UI
```
"iPad5,3",2016-11-29 00:00:00 UTC,2,2,0,5,1,UnitedXXXXXX,2016-11-24 00:00:00 UTC,2016-11-11 00:00:00 UTC,0,,181252
"iPad2,5",2016-11-29 00:00:00 UTC,3,0,3,4,0,AUSxxxxx,2016-10-27 00:00:00 UTC,2016-10-19 00:00:00 UTC,0,,167900
<<BROKEN RECORD WITH NOT CLOSING QUOTES AND BREAKS in to 2 LINES and it appears our application to look as 2 records>>
"iPhone7,1
",2016-11-29 00:00:00 UTC,1,1,0,0,1,UnitedXXXXXXXX,2016-11-25 00:00:00 UTC,2016-11-25 00:00:00 UTC,0,Icon,192445
"iPad5,3",2016-11-29 00:00:00 UTC,8,3,5,13,0,AUSXXXXX,2016-11-14 00:00:00 UTC,2016-09-01 00:00:00 UTC,0,Google (unknown),124291
```

This started to happen since 26th Nov 2016, before that it has been working properly and no issues. Not sure what has changed and 
# Thank you for reporting an issue to google-cloud-python!

If you can provide us with as much of the following information as possible it
will help us identify the cause of your issue more quickly.

1. OS type and version
    Linux 4.4.19-29.55.amzn1.x86_64
2. Python version and virtual environment information `python --version`
     Python 2.7.12
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`

Metadata-Version: 2.0
Name: google-cloud
Version: 0.20.0
Summary: API Client library for Google Cloud
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: jjg+google-cloud-python@google.com
License: Apache 2.0
Location: /usr/local/lib64/python2.7/site-packages
Requires: google-cloud-monitoring, google-cloud-datastore, google-cloud-logging, google-cloud-storage, google-cloud-error-reporting, google-cloud-vision, google-cloud-language, google-cloud-bigtable, google-cloud-resource-manager, google-cloud-translate, google-cloud-dns, google-cloud-pubsub, google-cloud-bigquery, google-cloud-core
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  License :: OSI Approved :: Apache Software License
  Operating System :: OS Independent
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Topic :: Internet

4. Stacktrace if available
    No Errors logged.
5. Steps to reproduce
    Login Bigquery on export one of the date partitioned table to Google Cloud Storage CVS format no compression single file(as in my case the data is not yet huge enough only ~ 9MB, so there is no change that export is spliting the record when it reached the size limit and start to write to the next one.
6. Code example  
   tried with code and BigQuery UI 

```python
    credentials = GoogleCredentials.get_application_default()
    bigquery_client = bigquery.Client(project='<SOME-PROJECT-NAME>',credentials=credentials)
    dataset = bigquery_client.dataset(<<DATA-SET-NAME>>)
    table = dataset.table(<<TABLE-NAME-TO-EXPORT>>)
    destination='test-bucket/TABLE_NAME_TO_EXPORT*'
    job_name = str(uuid.uuid4())
    logger.info("Created Job id for Big query : %s" %(job_name))
    job = bigquery_client.extract_table_to_storage(job_name, table, destination)
    job.destination_format = 'CSV' 
    job.print_header = False
    job.begin()
    wait_for_job(job)
    logger.info(" Exported %s : %s  to %s "  % (dataset_name, table_name, destination))

def wait_for_job(job):
    logger.info("Waiting for the job :%s to Finish" %(job.name))
    logger.info(" job %s created at %s " %(job.name, job.created))
    while True:
        job.reload()
        if job.state == 'DONE':
            logger.info("Job %s started at :%s  and ended at: %s " %(job.name, job.started, job.ended))
            if job.error_result:
                raise RuntimeError(job.error_result)
            return
        time.sleep(1)
```

Br
Chandu

**Comment by vrcs** [comment]
oh i checked the data to see if there is any line feed with the json format the line feed is quoted and with CSV export format its not 

Here is just the row which breaks exported it from Bigquery Web UI .
JSON FORMAT

[results-20161130-134656.json.zip](https://github.com/GoogleCloudPlatform/google-cloud-python/files/621742/results-20161130-134656.json.zip)

CVS Format 
[results-20161130-134656.csv.zip](https://github.com/GoogleCloudPlatform/google-cloud-python/files/621743/results-20161130-134656.csv.zip)


Br
Chandu

**Comment by daspecster** [comment]
Just to make sure I'm clear on this, are you saying the web UI is also exporting as broken JSON?

**Comment by nikut** [comment]
No, the JSON looks good, line feeds show up as \n there, however in the CSV exported from the web UI linefeeds are not escaped so they break the format.

**Comment by tseaver** [comment]
@nikut Given that the same data breaks the CSV export when invoked from the Web UI, the issue is with the BigQuery back-end, rather than with the `google-cloud-bigquery` Python library.  The [BigQuery support docs](https://cloud.google.com/bigquery/support) point to the [BigQuery issue tracker](https://code.google.com/p/google-bigquery/):  can you please report the issue there?

**Comment by vrcs** [comment]
Thanks for the suggestion , opened a bug in the Bigquery 
https://code.google.com/p/google-bigquery/issues/detail?id=825
