### ISSUE TITLE
How to experiment with local changes

### ISSUE THREAD

**Issue by jcoatgoogle** [GoogleCloudPlatform/google-cloud-python#2786]
My goal is simple: be able to make local changes, and then use veneer with those local changes. Per the contributor documents, I'm trying to use tox, but not really succeeding.

If I do `tox -e py27 --recreate --notest` from the root directory, then it doesn't pick up any changes.

If I do `tox -e py27 --recreate --notest` from datastore/ (this is the code I am changing), then my changes _are_ picked up, but they don't work

```
$ .tox/py27/bin/python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import datastore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/oss/git/google-cloud-python/datastore/.tox/py27/local/lib/python2.7/site-packages/google/cloud/datastore/__init__.py", line 53, in <module>
    from google.cloud.datastore.client import Client
  File ~/oss/git/google-cloud-python/datastore/.tox/py27/local/lib/python2.7/site-packages/google/cloud/datastore/client.py", line 23, in <module>
    from google.cloud.datastore._http import Connection
  File "~/oss/git/google-cloud-python/datastore/.tox/py27/local/lib/python2.7/site-packages/google/cloud/datastore/_http.py", line 24, in <module>
    from google.cloud import connection as connection_module
ImportError: cannot import name connection
```

I would appreciate any guidance on how to make this work!

**Comment by waprin** [comment]
I'm still trying to understand everything as well, but what I usually do is just

`cd datastore`
`pip install .`

To just install the package into my local virtualenv. Maybe there are hidden gotchas but it usually works for me.

**Comment by daspecster** [comment]
@jcoatgoogle, it looks like you have multiple versions of the library installed and the wrong one is getting picked up.

The `ImportError: cannot import name connection` issue is actually from a switch that was made in the last release I believe.  A simple thing to try would be to delete your `.tox` directories in root as well as in the sub-packages and then run `tox -e py27 --recreate --notest`.

**Comment by jcoatgoogle** [comment]
Merging master and deleting all the .tox's seems to have worked. Thank you both. Will reopen if I run into any more issues! <3

**Comment by daspecster** [comment]
Glad to hear!

If you run `.tox/py27/bin/pip freeze` in the root and in the sub-package you can probably see the library versions that are fighting.

**Comment by dhermes** [comment]
@jcoatgoogle Thanks a lot for reporting and for slogging through to the finish line. Sorry you ran into this, we're still smoothing out sharp corners after we switching from `gcloud` to `google.cloud` and now are in the land of Python namespace packages.

**Comment by jcoatgoogle** [comment]
I tried to reopen this but it won't let me :S

**Comment by jcoatgoogle** [comment]
oh wait now it will. I think github was having issues...

**Comment by dhermes** [comment]
@jcoatgoogle Resolving #2785 should cover this, no? Can we close this and just move over there?

**Comment by jcoatgoogle** [comment]
Happy to move this conversation there
