### ISSUE TITLE
String are saved as Blob in Datastore

### ISSUE THREAD

**Issue by JacopoDaeli** [GoogleCloudPlatform/google-cloud-python#2791]
Hello,

for some reasons with the following python code, the datastore entity `firstname` property is stored as a Blob instead of String.

```python
from google.cloud import datastore

client = datastore.Client()
key = client.key('TestSTG')

entity = datastore.Entity()
entity["firstname"] = "Jacopo" # STRING
client.put(entity)
```

As you can see from the console:
![image](https://cloud.githubusercontent.com/assets/6058569/20813299/edecc7ee-b7c9-11e6-9247-04188a70c775.png)

Any idea?  I do not have the same problem when I use the Node.js SDK.

I am using MAC OS X Sierra, Python 2.7.12 and google-cloud v0.21.0.

**Comment by JacopoDaeli** [comment]
[UPDATE]

Using 
```python
entity["firstname"] = u'Jacopo'
```

solve the problem. Closing the issue.

**Comment by tseaver** [comment]
@JacopoDaeli Thanks for following up.  FWIW, your original example would have worked as you expected on Python3.  The issue is that "native" strings in Python2 are actually bytes, rather than text, and so you have to mark them explicitly as unicode literals to allow them to be stored as text.

**Comment by JacopoDaeli** [comment]
Thanks to clarify @tseaver !

**Comment by spjatin4** [comment]
u'Jacopo' works when we are passing values individually. However, if you want to transfer as an object, you are expected to convert into string and then use put entity.
Here is sample code.

from google.cloud import datastore
first_name = 'Jacopo'
client = datastore.Client()
key = client.key('TestSTG')

entity = datastore.Entity()
entity["firstname"] = str(first_name)
client.put(entity)

This should work!
