### ISSUE TITLE
Unify default credentials and default project logic to avoid duplicate calls to google.auth.default

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#2796]
Context: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2726/files#r87670774

**Comment by dhermes** [comment]
#3667 and #3668 will go most of the way here

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!

**Comment by dhermes** [comment]
@lukesneeringer 

- This should be done
- This should be easy to do (i.e. ~1 hour)

**Comment by jonparrott** [comment]
I will do this in google.api.core (it's already in my prototype)
