### ISSUE TITLE
[Discussion] oauth2client credentials in a post-oauth2client world.

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#2814]
We recently switched `core` to use [`google-auth`](https://google-auth.readthedocs.io) in #2639 and completely removed support for `oauth2client`.

It is possible that some users are explicitly passing `oauth2client` credentials into `Client` constructors, e.g.:

```python
credentials = oauth2client.contrib.gce.AppAppsertionCredentials()
storage_client = storage.Client(credentials=credentials)
```

After `google-cloud-core==0.22.0` is released this code will no longer work. Only credentials from `google-auth` will work. There is a potential that we could break some user code and there may be some valid reasons for sticking with oauth2client in the near-term (user credentials and storage, for example).

`google-auth` offers a way to [`convert`](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/443df66cb6e7960205c1d2108e67220d27408efe/google/auth/_oauth2client.py#L136) credentials:

```python
import google.auth._oauth2client

new_credentials = google.auth._oauth2client.convert(old_credentials)
```

We have two options:

1. Tell users who still want to use oauth2client to use `google.auth._oauth2client` to convert their credentials.
2. Add code in our `Client` base class to automatically convert credentials and issue a warning.

I strongly prefer (1) so that we do not prolong oauth2client's lifetime and so that we can more quickly free ourselves to switch http libraries.

**Comment by dhermes** [comment]
I also (somewhat strongly) prefer (1) but am worried about stepping on the toes of users.

**Comment by daspecster** [comment]
I'm not entirely sure what the criteria for Google Cloud Platform's alpha, beta, GA...etc...(I really would like that link if anyone knows where that's defined.), but I feel like 2 would only be required for a Beta or higher release...possibly only GA.

I prefer 1, as it would give a clean break before the beta release.  How many people are really doing this though? I wish there was a way to figure that out.

**Comment by tseaver** [comment]
:+1: from me for option 1, as well.  Let's just document the `google-auth` conversion method (maybe it should be a public API?) and go on.

**Comment by jgeewax** [comment]
Can we have a friendly error message with a link to a page saying to use the `.convert()` method ? I don't mind telling people "You're using old shit. Stop it." I do mind telling them "Error. You figure it out :P"

If the error is "Those credentials aren't valid anymore. Call .convert on them or use new creds. Check github.com/..../some-page-somewhere for more details on this" then I'm happy.

/cc @omaray

**Comment by dhermes** [comment]
Great, thanks @jgeewax!
