### ISSUE TITLE
Error reporting instrumentation and SIGTERM handling

### ISSUE THREAD

**Issue by karan** [GoogleCloudPlatform/google-cloud-python#2819]
Dependent on #1921, we need to add a SIGTERM handler that can publish thread trace and heap info to Error Reporting.

Example interface:

```
from google.cloud import error_reporting
client = error_reporting.Client(project='my-project',
                                               credentials=creds,
                                               shutdownLogs={threadDump: True, heapInfo: False})
```

**Comment by dhermes** [comment]
@waprin thoughts?

**Comment by waprin** [comment]
yes @karan has already asked for it, I said I would plan to get it done this quarter, I still have a month left!! Was going to start this week, already did some preliminary research, but need to do a bit more to totally understand what we want and what we can get.

**Comment by karan** [comment]
Thanks Bill. Just creating this as an external tracker! Let me know what I can do to help. Really excited for this work.

**Comment by lukesneeringer** [comment]
@waprin I think we have this now, correct? (If so, let me know so I can close this; if not, what is the priority on it?)

**Comment by waprin** [comment]
Yes, I will still need to add some memory stats but that will also be a small change.

**Comment by waprin** [comment]
I think priority is probably P2 or P3 hence the chipping away in free cycles but it's close to done, will close after.

**Comment by duggelz** [comment]
Can we just use the standard [`faulthandler`](https://docs.python.org/3/library/faulthandler.html) module from Python 3 (and backported to Python 2 on PyPI)?

I worked a lot on the C++ crash handling inside Google, and it's tremendously difficult to get everything right in a robust and portable way.  And there is a direct correlation where the more elaborate you make the crash handler, the less reliable it is.  Writing to files other than stdout/stderr is iffy, let alone making RPC calls.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
