### ISSUE TITLE
Should be able to have authenticated local non-TLS traffic

### ISSUE THREAD

**Issue by jcoatgoogle** [GoogleCloudPlatform/google-cloud-python#2838]
I have a PR that very coarsely seeks to do this https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2825, but @dhermes and @jonparrott said that, if this is my goal, there is an easier way to configure how we use the AuthMetadataPlugin to do this.

There are cases where you want to do this... I'm happy restricted it just to traffic to localhost, as that is lower risk.

**Comment by dhermes** [comment]
@jcoatgoogle FWIW, there is "no such thing" as `localhost`. It's just a convenient alias that's typically in a local hosts file in most OSes. It's typically an alias the very special loopback IP, but doesn't have to be.

**Comment by jcoatgoogle** [comment]
Then it doesn't have to have the restriction. I guess that was just more handholding, but if someone sets VENEER_HTTP_AUTH_NO_REALLY or whatever, then it gets it...or whatever configuration, really.

**Comment by jcoatgoogle** [comment]
Ok, so, separately, I was finally able to get a pure java HTTP2 reverse proxy... this _may_ allow me to avoid having to do this, which I think would make everyone involved happy.

@jonparrott, you had mentioned that the reverse proxy could do authentication. I actually have that working with application default credentials, but what I'm wondering is if that is always valid? I'm trying to think of cases where the user might have more complicated authentication that this issue would meet (since the auth token would be the same), but just grabbing the default credentials on the proxy wouldn't.

**Comment by jonparrott** [comment]
> I'm trying to think of cases where the user might have more complicated authentication ...

I would just recommend making your proxy respect the `GOOGLE_APPLICATION_CREDENTIALS` command, or otherwise have a way to specify authentication, e.g.:

```
$ your-proxy --use-gce-auth
$ your-proxy --use-service-account /path/to/service_account.json
$ your-proxy --use-bearer-token "bearer_token"
$ env GOOGLE_APPLICATION_CREDENTIALS=/path/to/service_account.json your-proxy
```
