### ISSUE TITLE
BigQuery: fetch_data() should return a core iterator

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#2840]
See: [https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/query.py#L363][1]

```python
def fetch_data(...):
    """...
     :returns: ``(row_data, total_rows, page_token)``
    ...
    """
```

I would expect it to return some kind of [Iterator](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/core/google/cloud/iterator.py) to be consistent with the other cloud APIs.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/2d9c109211331c6cfc59a2a9acbda4c4e3609509/bigquery/google/cloud/bigquery/query.py#L363

**Comment by dhermes** [comment]
I'll defer to @tseaver. We discussed this for `QueryResults.fetch_data` and one other method?

**Comment by tseaver** [comment]
`Table.fetch_data` already returns an iterator.  I will work on a PR to make `QueryResults.fetch_data` do likewise (I thought it was already done).

**Comment by nprogers-WPE** [comment]
Docs need to be updated: https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery/query.html

**Comment by dhermes** [comment]
@nprogers-WPE Check out the `latest` docs: https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/query.html

@lukesneeringer I'm kind of at a loss with what to do with our `stable` docset (which is the default that people land in from https://googlecloudplatform.github.io/google-cloud-python/)
