### ISSUE TITLE
Error in Natural Language docs example - "'Sentiment' object has no attribute 'polarity'"

### ISSUE THREAD

**Issue by polleyg** [GoogleCloudPlatform/google-cloud-python#2854]
https://googlecloudplatform.github.io/google-cloud-python/stable/language-usage.html#analyze-sentiment

`print(sentiment.polarity)`

should be:

`print(sentiment.score)`

<img width="284" alt="screen shot 2016-12-12 at 9 31 18 pm" src="https://cloud.githubusercontent.com/assets/5554342/21096058/5ad5934a-c0b2-11e6-8d83-a8bc0e96ebb9.png">

**Comment by daspecster** [comment]
Thanks for reporting @polleyg!

I have a PR to update these.
