### ISSUE TITLE
Python 3.5: setuptools currently broken

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#2856]
Root cause: `setuptools==28.8.0` utterly falls apart when namespace packages are involved: https://github.com/pypa/setuptools/issues/870

----

Original report:
Now sure why but there is something wrong with Python 3.

- https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/182873372#L2256
- https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2851#issuecomment-266485097

Installing the packages works fine under Python 3.5 though.

`python3.5 setup.py install`.

**Comment by tseaver** [comment]
@jaraco is chasing this down in https://github.com/pypa/setuptools/issues/870

**Comment by tseaver** [comment]
W00t!  setuptools 31.0.1 gets the tests passing for me on Python 3.5!

**Comment by daspecster** [comment]
Ditto! Closing!
