### ISSUE TITLE
Add support for generating storage upload policies and signatures

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#2861]
[Details](https://cloud.google.com/storage/docs/xml-api/post-object#policydocument)

A policy (and its associated signature) allows a web application to create a form that allows user agents to *directly upload* to Google Cloud Storage. This is a pretty useful feature and it would be great if this client library could make that easier.

A rough idea:

```python
storage = google.cloud.storage.Client()

policy = storage.policy(
    bucket='my-bucket',
    acl='bucket-owner-read',
    succes_action_redirection=url_for('upload_success'),
    content_type='image/jpeg',
    content_length_range=(0, 1024*10))

encoded = policy.encoded
signature = policy.signature

for field_name, field_value in policy:
    # HTML field names and values
```

**Comment by EverWinter23** [comment]
@theacodes Hey, how does this method accommodate for `CORS` policy if the origin is restricted to a particular domain? I'm trying to upload a bunch of images to the prefix, and my policy looks exactly like this apart from the origin: 

```json
[
    {
        "responseHeader": ["Access-Control-Allow-Origin", "Content-Type", "Authorization"],

        "method": [
            "GET",
            "POST",
            "PUT",
            "DELETE",
            "OPTIONS"
        ],
        "origin": [
            "sampledomain.com"
        ],
        "exposedHeaders": [
            "ETag"
        ],
        "maxAgeSeconds": 3000
    }
]
```
Getting `CORS` errors while upload, am I missing something or does this method not allow restrictions on the origin at all?
