### ISSUE TITLE
Branding updates required for Translate API client libraries

### ISSUE THREAD

**Issue by danoscarmike** [GoogleCloudPlatform/google-cloud-python#2863]
On November 15, 2016, Google launch a rebranding of Google Translate API to Google Cloud Translation API. This does not impact the method names but the URLbase as well as readmes, samples and comments.

URLbase has been already updated to translation.googleapis.com

We need to have update the Client library, the readme, client library docs, samples and code comments to use "Google Cloud Translation API" instead of Google Translate API. The short version of the new name is "Cloud Translation API" or "Translation API"

Note: the product Google Translate still exists. It is the API Google Translate API that has been re-branded.

**Comment by daspecster** [comment]
Thanks @danoscarmike! This will get resolved in #2865.
