### ISSUE TITLE
Update logging.list_entries to use the `resourceNames` field

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-python#2864]
It looks like `projectIds` was deprecated -- not sure when, but appears so (see https://cloud.google.com/logging/docs/api/reference/rest/v2/entries/list). It'll still work, so we're not in any major time crunch here, but we should swap out to using the `resourceNames` field when sending stuff to the API.

Ideally, this method would accept both `projects`, `organizations`, and generic `resources`. `projects` would just be prefixed with `projects/`, same for organizations, and resources just appended to the list of resource names where we assume that the person understands the format.

If we're going to swap the order of the parameters (ie, put `organizations` after `projects`) then this might be considered a breaking change :(

**Comment by dhermes** [comment]
@jgeewax [Here][1] is the current user-facing impl., [here][2] is the JSON-over-HTTP impl. (not user-facing) and [here][3] is the gRPC impl. (also not user facing).

I actually ran into this issue in #2795, and @waprin indicated that the following "fix" would at least get us off the deprecated argument:

```python
resource_names = ['projects/' + project for project in projects]
```

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/6bc1f8b9d6265957d2da44446913838349d18a15/logging/google/cloud/logging/client.py#L154-L155
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/6bc1f8b9d6265957d2da44446913838349d18a15/logging/google/cloud/logging/_http.py#L105
[3]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/6bc1f8b9d6265957d2da44446913838349d18a15/logging/google/cloud/logging/_gax.py#L94-L96

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
