### ISSUE TITLE
Docs: "Go doesn't appear in the drop down for Python"

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-python#2868]
SCENARIO
Please see this issue in the Go repo: https://github.com/GoogleCloudPlatform/google-cloud-go/issues/455

Seems like we need to refresh the docs for Python perhaps? 

Either way, "Go" is missing from the drop-down:

![image](https://cloud.githubusercontent.com/assets/6609430/21210803/083ed29a-c233-11e6-8a8a-7d4ae95412d7.png)

**Comment by daspecster** [comment]
@omaray, this should get updated on the next docs push.
