### ISSUE TITLE
No http_context information reported in Stack driver error reporting.

### ISSUE THREAD

**Issue by walter-liu** [GoogleCloudPlatform/google-cloud-python#2877]
I had tried to use error reporting module to trace my errors of my system. I found that http_context is not reported. After I check the document of stack driver error reporting, I found there is a bug there. The fix is simple. Just modify file at
<pre>google/cloud/error_reporting/client.py:174</pre>
from
```python
            payload['context']['httpContext'] = {
```
to
```python
            payload['context']['httpRequest'] = {
```
The code to reproduce is list below,
```python
from google.cloud import error_reporting
cli = error_reporting.Client(service='python_test')
context = error_reporting.client.HTTPContext(
    method='GET',
    url='http://test.com',
    user_agent='Chrome',
    referrer='http://referer.com',
    response_status_code=400,
    remote_ip= '8.8.8.8',
)
cli.report('error report test', http_context=context)
```

Environment
<pre>OS: MAC
Python 2.7.10
google-cloud-error-reporting==0.22.0</pre>

**Comment by dhermes** [comment]
Thanks a lot for the report!

**Comment by justinwp** [comment]
Any update on this? Would prefer not dropping back to making rest calls.

**Comment by dhermes** [comment]
@waprin WDYT?
