### ISSUE TITLE
If AutoAck pull returns empty then exception raised on context exit

### ISSUE THREAD

**Issue by quom** [GoogleCloudPlatform/google-cloud-python#2878]
If the subscription pull returns 0 messages in the __enter__ method in the AutoAck class then on __exit__ the acknowledge call raises an exception on the HTTP call: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/pubsub-0.22.0/pubsub/google/cloud/pubsub/subscription.py#L512

Currently the way a deal with this is to wrap the context manager in try/except or override __exit__ to check for an empty list. The former is messy and the latter can just be fixed at source.

**Comment by tseaver** [comment]
@quom Thanks for the report!  It looks as though you are [working on a fix](https://github.com/quom/google-cloud-python/commit/9f917b97669bb27a50537f4adeacd260a3111e0d).  Can you also add a test which fails without your patch?

**Comment by quom** [comment]
@tseaver There you go :)

**Comment by tseaver** [comment]
@quom Looking good.  PR forthcoming?
