### ISSUE TITLE
'Dataset.list_tables' returns incomplete 'Table' instances

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#2883]

**Comment by dhermes** [comment]
@tseaver What is the proposed fix here? I personally wouldn't classify this as a backend bug. The fact that we return table instances (rather than just the string table names) is a convenience for users, but it comes with trade-offs.

**Comment by tseaver** [comment]
From #2756:

> The items returned by the [tables/list API](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/list#response) do not contain the full Table resource: they have only the barest identifying fields for the table. The call to reload() is thus necessary.

Ideally, the back-end would offer an option to get the whole resource (`selfLink` and `schema` fields).

**Comment by tseaver** [comment]
Without such a back-end change, we should probably update the docs for `Dataset.list_tables` to highlight the fact that users need to call `reload()` on any `Table` instance before making some API calls through it.

**Comment by tseaver** [comment]
We could also sharpen the docstring for `Table.reload` to make it more obvious when / why to use it.

**Comment by tseaver** [comment]
@dhermes 

> I personally wouldn't classify this as a backend bug

It might not be a bug, but not returning the full resource in a list operation (or at least offering the option to get it) is poor REST practice:  it makes the users perform extra API calls in order to get schema for the tables, without which they cannot load or dump data, for instance.

**Comment by lukesneeringer** [comment]
I am going to declare bankruptcy on this ticket, because:

  * It is a backend issue.
  * If the backend issue has been solved, this will be addressed in the rehash of this library naturally. IUf not, it is not a client library issue.
