### ISSUE TITLE
Add deprecation notice to old pypi page for gcloud

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/google-cloud-python#2885]
Would you be so kind as to add a deprecation notice on the gcloud homepage on PyPi: https://pypi.python.org/pypi/gcloud/0.8.0, pointing to the google-cloud-libs page?  The page currently offers no clues about how to upgrade to the next version of the code  since the package name changed,  I had a couple of fairly sophisticated user stuck at a year old version of gcloud, running into problems, with no evident path forward.

**Comment by daspecster** [comment]
This kind of ties in with #2748 as well.

**Comment by daspecster** [comment]
Sounds like this is actually a duplicate.

**Comment by dhermes** [comment]
@kir-titievsky Though a duplicate, it's definitely important to resolve. Thanks for poking us
