### ISSUE TITLE
How To Set Range

### ISSUE THREAD

**Issue by quasiben** [GoogleCloudPlatform/google-cloud-python#2888]
I am trying to download a range of bytes with the `storage` library.  Apparently, this is done by setting the [range in the header](https://cloud.google.com/storage/docs/xml-api/reference-headers#range) .  Is this functionality *easily* exposed ?

**Comment by quasiben** [comment]
Apologies if this is not the the appropriate place to post this issue.  I also posted on SO: http://stackoverflow.com/questions/41233937/how-to-use-pythong-google-cloud-client-for-storage-with-range

**Comment by dhermes** [comment]
@quasiben Thanks for looking into this. This issue tracker is definitely an appropriate place (and your PR very much appreciated).

**Comment by danoscarmike** [comment]
This issue may no longer be relevant due to its age.  If you are still experiencing this issue and are reasonably certain that it is a bug, please feel free to re-open this it with enough information to help us reproduce it.  

BTW, #1998 referenced in pull #2890 was closed late last month.
