### ISSUE TITLE
bigquery.StructQueryParameter should be able to contain structs and arrays

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#2905]
I [commented](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2892#discussion_r93489645) that structs can contain structs and arrays, but the client library does not support it yet.

I'm testing this on the master branch.

Sample code:

```python
from google.cloud import bigquery

client = bigquery.Client()
query = 'SELECT @struct_value AS s;'
query_results = client.run_sync_query(
    query,
    query_parameters=[
        bigquery.StructQueryParameter(
            'struct_value',
            bigquery.StructQueryParameter(
                'x',
                bigquery.ScalarQueryParameter('a', 'INT64', 42),
                bigquery.ScalarQueryParameter('b', 'STRING', 'what is the answer?')))
    ])
```

<details>
<summary>Stacktrace</summary>
<pre>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-97d23efb85a5> in <module>()
      9                 'x',
     10                 bigquery.ScalarQueryParameter('a', 'INT64', 42),
---> 11                 bigquery.ScalarQueryParameter('b', 'STRING', 'what is the answer?')))
     12     ])

/Users/swast/venvs/google-cloud-python/lib/python3.5/site-packages/google_cloud_bigquery-0.22.1-py3.5.egg/google/cloud/bigquery/_helpers.py in __init__(self, name, *sub_params)
    532         self.name = name
    533         self.struct_types = OrderedDict(
--> 534             (sub.name, sub.type_) for sub in sub_params)
    535         self.struct_values = {sub.name: sub.value for sub in sub_params}
    536 

/Users/swast/venvs/google-cloud-python/lib/python3.5/site-packages/google_cloud_bigquery-0.22.1-py3.5.egg/google/cloud/bigquery/_helpers.py in <genexpr>(.0)
    532         self.name = name
    533         self.struct_types = OrderedDict(
--> 534             (sub.name, sub.type_) for sub in sub_params)
    535         self.struct_values = {sub.name: sub.value for sub in sub_params}
    536 

AttributeError: 'StructQueryParameter' object has no attribute 'type_'
</pre>
</details>

Ditto for a struct that contains an array:

```python
query_results = client.run_sync_query(
    query,
    query_parameters=[
        bigquery.StructQueryParameter(
            'struct_value',
            bigquery.ArrayQueryParameter(
                'y',
                'STRING',
                ['hello', 'world']))
    ])
```

<details>
<summary>Stacktrace</summary>
<pre>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-be6f219adb88> in <module>()
      8                 'y',
      9                 'STRING',
---> 10                 ['hello', 'world']))
     11     ])

/Users/swast/venvs/google-cloud-python/lib/python3.5/site-packages/google_cloud_bigquery-0.22.1-py3.5.egg/google/cloud/bigquery/_helpers.py in __init__(self, name, *sub_params)
    532         self.name = name
    533         self.struct_types = OrderedDict(
--> 534             (sub.name, sub.type_) for sub in sub_params)
    535         self.struct_values = {sub.name: sub.value for sub in sub_params}
    536 

/Users/swast/venvs/google-cloud-python/lib/python3.5/site-packages/google_cloud_bigquery-0.22.1-py3.5.egg/google/cloud/bigquery/_helpers.py in <genexpr>(.0)
    532         self.name = name
    533         self.struct_types = OrderedDict(
--> 534             (sub.name, sub.type_) for sub in sub_params)
    535         self.struct_values = {sub.name: sub.value for sub in sub_params}
    536 

AttributeError: 'ArrayQueryParameter' object has no attribute 'type_'
</pre>
</details>

**Comment by tseaver** [comment]
Fixed in #3180.
