### ISSUE TITLE
BigQuery: expose numDmlAffectedRows in query results

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#2920]
See: https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query#numDmlAffectedRows

It is marked as experimental. This is because DML statements are currently in beta for BigQuery.

This will be needed to correctly implement [cursor.rowcount](https://www.python.org/dev/peps/pep-0249/#rowcount) for DB-API support https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2434

**Comment by lukesneeringer** [comment]
Hey Tim,
Has this come out of the experimental phase yet?

**Comment by tseaver** [comment]
DML Docs still show beta status.

**Comment by tswast** [comment]
DML is GA now (for non-partitioned tables), by the way.
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-manipulation-language
