### ISSUE TITLE
Receiving KeyError: u'fullTextAnnotation'

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/google-cloud-python#2923]
> 1. OS type and version
OSX 10.11

> 2. Python version and virtual environment information `python --version`
Python 2.7.12

> 3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
google-cloud-core==0.22.1
google-cloud-vision==0.22.0

> 4. Stacktrace if available
Traceback (most recent call last):
  File "snippets.py", line 203, in <module>
    run_snippets()
  File "snippets.py", line 201, in run_snippets
    detect_text(file_name)
  File "snippets.py", line 161, in detect_text
    texts = image.detect_text()
  File "/Users/class/code/cloud/samples/python-docs-samples/vision/cloud-client/env/lib/python2.7/site-packages/google/cloud/vision/image.py", line 221, in detect_text
    annotations = self._detect_annotation(features)
  File "/Users/class/code/cloud/samples/python-docs-samples/vision/cloud-client/env/lib/python2.7/site-packages/google/cloud/vision/image.py", line 113, in _detect_annotation
    return Annotations.from_api_repr(results)
  File "/Users/class/code/cloud/samples/python-docs-samples/vision/cloud-client/env/lib/python2.7/site-packages/google/cloud/vision/annotations.py", line 91, in from_api_repr
    curr_feature = annotations.setdefault(_KEY_MAP[feature_type], [])
KeyError: u'fullTextAnnotation'

> 5. Steps to reproduce

1. instantiate client
2. load image (e.g. Google Cloud Platform logo)
3. Try to show text from png image
4. error

> 6. Code example
```
def detect_text(path):
    # Instantiates a client
    vision_client = vision.Client()

    # Loads the image into memory
    with io.open(path, 'rb') as image_file:
        content = image_file.read()
        image = vision_client.image(
            content=content)

    # Performs label detection on the image file
    texts = image.detect_text()
    for text in texts:
      print text.description
```

**Comment by gguuss** [comment]
If I use library version 0.21, the same code works.

**Comment by daspecster** [comment]
Thanks for reporting @gguuss!

Do you have an example image that I could use to test with?

The [system test](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/10c64d9951968c0b4dff414f6484e10ea330736d/system_tests/vision.py#L424-L431) for this is nearly identical to your example and it's passing.

Also, `fullTextAnnotation` doesn't seem to be documented in the JSON API documentation, so I'm a little confused about that.

**Comment by gguuss** [comment]
I'm using logos.png from [this branch folder](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/vision_cloud_client_snippets/vision/cloud-client/resources). I'm pretty sure it's my configuration at this point, I'll create new credentials and will close if I can't repro.

**Comment by daspecster** [comment]
@gguuss, I'll try with your image. Let me know if there's anything I can do to help!

**Comment by gguuss** [comment]
There was an experiment associated with my credential object that changes the response bodies from the API backend for vision, this breaks the client library in some circumstances.

**Comment by gguuss** [comment]
Not sure I should be assigned as I am no longer in cloud.
