### ISSUE TITLE
Code snippet for vision properties does not reflect changes in library

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/google-cloud-python#2924]
>OS type and version

OSX 10.11

>Python version and virtual environment information `python --version`

Python 2.7.12

>3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`

google-cloud-core==0.22.1
google-cloud-vision==0.22.0

> Stacktrace if available

N/A

> Steps to reproduce

1. See [Vision usage page image properties](https://googlecloudplatform.github.io/google-cloud-python/stable/vision-usage.html#image_properties)
2. Copy / paste code
3. Y U no work, code? ¯\_(ツ)_/¯

> Code example
From docs:
```
>>> from google.cloud import vision
>>> client = vision.Client()
>>> with open('./image.jpg', 'rb') as image_file:
...     image = client.image(content=image_file.read())
>>> results = image.detect_properties()
>>> colors = results[0]
>>> first_color = colors[0]
>>> first_color.red
244
>>> first_color.blue
134
>>> first_color.score
0.65519291
>>> first_color.pixel_fraction
0.758658
```

Should be:
```
>>> from google.cloud import vision
>>> client = vision.Client()
>>> with open('./image.jpg', 'rb') as image_file:
...     image = client.image(content=image_file.read())
>>> results = image.detect_properties()
>>> first_color = results[0].colors[0]
>>> first_color.color.red
244
>>> first_color.color.blue
134
>>> first_color.color.score
0.65519291
>>> first_color.color.pixel_fraction
0.758658
```

Let me know if you'd prefer I PR the fix.

**Comment by daspecster** [comment]
Thanks @gguuss!

I have a [PR](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2925) for this, I changed it a little bit from what you have though.

```python
>>> results = image.detect_properties()
>>> colors = results[0].colors
>>> first_color = colors[0]
>>> first_color.red
```

TBH I'm not sure why I have `results[0]` in this case. I will look into that as I add the GAPIC support for Image Properties.  So just FYI, that could change soon.
