### ISSUE TITLE
Speech-api (Transcribe.py) returning unicode

### ISSUE THREAD

**Issue by jello2545** [GoogleCloudPlatform/google-cloud-python#2928]
Hi There,

Having some issue using the google speech-API for Python. Canadian french here, using accented characters (à é è o û). Whenever transcribe.py returns an accented characters, it prints it in unicode like :
é = \u00e9  è = \u00e8  à = \u00e0

Knowing the script decode his content in UTF-8 ( 'content': speech_content.decode('utf-8')) it shouldn't have any problem with these characters. I am a very  "amateur" programmer and since this script also uses "import json" and mixes javascript in it, I'm not sure on what I should be focusing. 

The script usage is as follow (this is run from the console directly):
/usr/bin/python transcribe.py myaudiorecording.flac

So let's say I record an audio file in which i say "Les éléphants"  and transcribe it through google, transcribe.py will return: "Les \u00e9l\u00e9phants". 

I use stock transcribe.py file which can be found here: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/api-client/transcribe.py

I tried adding **# -*- coding: utf-8 -*-** to the code but that didn't help. I'm pretty sure this has nothing to do with Python itself since with this line added I can print any accented characters to the console without issue.

So, not sure if Google actually returns the incorrect format, if Python just can't handle the function return or if its something about json.

Thank you very much for your assistance.

**Comment by daspecster** [comment]
@jello2545 thanks for reporting!

The example you mentioned is actually part of a different [repository](https://github.com/GoogleCloudPlatform/python-docs-samples/issues).

I'm not entirely sure offhand how encoding is handled for that. But I would guess that if you used Python 3, it would probably resolve itself.

```python
>>> a = '\u00e0'
>>> a
'à'
```

@jonparrott, do you have any suggestions?

**Comment by jello2545** [comment]
Hi @daspecster,

Thanks you very much for your answer, I actually did try to run transcribe.py with python2 but it looks like googleapiclient isnt available for it (or I didnt install it properly).

However, your second suggestion for Python 2.7 looks pretty interesting. I added the decode option to the print line so it looks like:

 print(json.dumps(response)).decode('unicode-espace') 

Looks like python codec doesnt like it much since it returns this: 

**UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 75: ordinal not in range(128)**

**Comment by daspecster** [comment]
Try:

```python
print(json.dumps(response).decode('unicode-escape'))
```

You have `espace` instead of `escape`, and also you're `decode` is on the `print()` instead of the `response.

**Comment by jello2545** [comment]
Oops, my bad about the escape and I wasent indeed decoding the response. Corrected it to **print(json.dumps(response).decode('unicode-escape'))** but still I receive the same UnicodeEncodeError.

Looks like there's a bunch of frustration about this issue on https://pythonhosted.org/kitchen/unicode-frustrations.html . Will need to dig into that.

**Comment by daspecster** [comment]
Ok, there may be an option for `json.dumps` to handle it better.
Since this is more of a Python thing than a `google-cloud` thing, I'm going to close this.

You could try using this library, we try to handle the encoding for you.

https://googlecloudplatform.github.io/google-cloud-python/stable/speech-usage.html

**Comment by jello2545** [comment]
Looking into that, thank you again !

**Comment by jello2545** [comment]
Hi @daspecster 

Got my answer, like you suggested to look with json options.  I actually had to add ensure_ascii=False to the json.dumps, then everything printed correctly. 

print(json.dumps(response, **ensure_ascii=False**).encode('utf8'))

Thanks !

**Comment by daspecster** [comment]
Glad to hear!
