### ISSUE TITLE
BigQuery: support labels field of Datasets and Table resources

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#2931]
Docs (talks about datasets, but tables can have labels, too):
https://cloud.google.com/bigquery/docs/labeling-datasets

API references:
https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets#labels
https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#labels

**EDIT: I see that patch is supported already.** ~~If the `patch` request is not yet supported, this will be needed, too.
https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets/patch
https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/patch~~

**Comment by lukesneeringer** [comment]
@tswast What actually needs to be done on this?

**Comment by tswast** [comment]
I believe the labels property needs to be added to both Dataset and Table.

**Comment by tswast** [comment]
Fixed by https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4245
