### ISSUE TITLE
CloudLoggingHandler disregards contextual information

### ISSUE THREAD

**Issue by Gennady-Andreyev** [GoogleCloudPlatform/google-cloud-python#2932]
## Context

Python logging provides useful facilities to inject arbitrary contextual information into log records. I.e. the core logger's methods like `debug`, `info`, etc. can be provided with an optional parameter called `extra`. [Reference to the doc](https://docs.python.org/3/library/logging.html#logging.Logger.debug). There are also [more sophisticated techniques](https://docs.python.org/3/howto/logging-cookbook.html#adding-contextual-information-to-your-logging-output). It sounds extremely useful given stackdriver is quite friendly to structured data. 

## Problem

Unfortunately, `google.cloud.logging.handlers.CloudLoggingHandler` (or, strictly saying, underlying transports) disregards whatever is passed in `extra` parameter and sends further only `message`. Code reference [1](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging/handlers/transports/background_thread.py#L139) and [2](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging/handlers/transports/sync.py#L42). This is quite sad since `log_struct` does let us pass arbitrary structured entries.

## Proposed solution

Although a bit hacky, it would probably be the easiest to pass the whole `__dict__` of `LogRecord` object to `log_struct` [here](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging/handlers/transports/background_thread.py#L139). I mean smth. like this:

```
self.batch.log_struct(record.__dict__, severity=record.levelname)
```

A property called `message` will automatically be there as well ([LogRecord attributes](https://docs.python.org/3/library/logging.html#logrecord-attributes)).

Ideally, such useful `log_struct`'s parameters as `labels`, `insert_id`, etc. should be recognized as well.

```
self.batch.log_struct(
    record.__dict__, 
    severity=record.levelname,
    labels=getattr(record, 'labels', None),
    insert_id=getattr(record, 'insert_id', None)
)
```

**Comment by waprin** [comment]
Thanks for raising this.

I think what you're referring to is similar to this PR:

https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2045

Unfortunately the author disappeared before we finished review.

I really don't love blindly copying the dict. Explicit is better than implicit, so just explicitly copy all the data we think should go in there.

If you want to make a PR, happy to review it. Otherwise this is a low-priority nice to have for me to do myself.

**Comment by Gennady-Andreyev** [comment]
@waprin , thanks, I'm glad you've found this interesting!

Yes, the problem is the same as @vmarkovtsev pointed out.

Solution-wise, I totally agree blind usage of `__dict__` would be rather dirty. If it is handler that's responsible for shaping the data to be pushed to stackdriver (so that underlying transports are unaware of that and just ingest whatever they're provided with), the puzzle will be put together much nicer. Actually #2045 was doing exactly that. 

I'm ready to help with implementation, but please advise what's the best way to proceed. Is there a way I can follow up #2045 or I'd better make my own fix form scratch?

**Comment by waprin** [comment]
@Gennady-Andreyev I think it's better if you try to start from scratch since I don't think we ever got a CLA from the previous author.

**Comment by vmarkovtsev** [comment]
I would be more than happy to give CLA if the system allowed me to.

**Comment by daspecster** [comment]
@vmarkovtsev, AFAICT the reason CLA is failing is because there are multiple committers in your PR. I *think* if you rebase your PR on the latest master then CLA should clear up.

**Comment by lukesneeringer** [comment]
Hi all,
I am going to go ahead and close this ticket, as it does not represent active work for us. If you decide to open a PR, we would be happy to work to get it in! :-)
