### ISSUE TITLE
Cloud Speech veneer should not throw an exception if there is more than one result.

### ISSUE THREAD

**Issue by pbogle** [GoogleCloudPlatform/google-cloud-python#2947]
I believe this code in the veneer is incorrect because it throws if there is more than one result.

https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/speech/google/cloud/speech/_gax.py#L263

As documented in the proto, the results contain a sequential list of transcription results corresponding to sequential portions of audio.

**Comment by daspecster** [comment]
Thanks @pbogle!

For `sync_recognize` I was unable to produce any tests that had more than one result.

I was able to confirm tests with multiple results with the other methods. Do you have an example I could try?

**Comment by pbogle** [comment]
Thank you for your help.  This will be a beta blocker.

In general, please check with a cloud speech team member before making any assumptions that aren't explicitly documented in the API.  (Feel free to contact me, I'm tech lead for the team.) Even if we didn't return multiple results today, we might start doing so tomorrow if allowed by the specification. 

An example of a file that results in multiple results is this onegs://pbogle-speech-test/calleng.raw   (8khz en-US LINEAR16) 

Could you help me identify other places where the veener simplifies or flattens results in ways that aren't explicitly guaranteed to by the spec?  We should look at those as potential sources of bugs.

**Comment by daspecster** [comment]
Awesome! Thanks!

I'll see if I can find other places that flatten out the data. There may be one or two.

Do you happen to know who your Vision API counterpart would be?

**Comment by pbogle** [comment]
The same issue exists here: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/speech/google/cloud/speech/operation.py#L63

**Comment by lukesneeringer** [comment]
@daspecster I am unable to change assignment on this issue, but am currently handling it.

**Comment by daspecster** [comment]
Thanks @lukesneeringer! I cleared the assignees but I can't assign you. Must be a permissions thing for your account?

**Comment by lukesneeringer** [comment]
PR is #2962, waiting on CI and approval.

**Comment by daspecster** [comment]
This is actually pretty broken now.

The system tests exhibit the issues.
I'm working on a PR to resolve now.

**Comment by lukesneeringer** [comment]
This has since been dealt with by other PRs; re-closing. :-)
