### ISSUE TITLE
Documentation for BigQuery base class for Jobs missing

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-python#2953]
I was reading the documentation for google.cloud.bigquery.job.CopyJob (and a few other classes).  Some of the important methods are in the base class google.cloud.bigquery.job._AsyncJob.  That class is not documented, it is private.

I think either the inherited methods should be documented in the derived class, or the private class should be documented too.  Reading the code to find all methods is a bit painful.

**Comment by dhermes** [comment]
> Reading the code to find all methods is a bit painful.

Definitely not our intention :grinning: Thanks for filing.

@tseaver @daspecster I think an easy fix is to use `:inherited-members:`, but would need to double check.

**Comment by daspecster** [comment]
@dhermes I can take a look into this in a few hours if @tseaver doesn't beat me to it.
