### ISSUE TITLE
Vision client's annotate method fails on expected image input

### ISSUE THREAD

**Issue by scottcode** [GoogleCloudPlatform/google-cloud-python#2982]
# Description

An instance of `google.cloud.vision.Client` has method annotate, which the docstring says should take `image` and `features` parameters. The `image` parameter is described to be a string which should represent either a URL, a Google Cloud Storage path, or a byte stream of the image. However, trying to use the method in this way yields an error. It seems to expect the `image` parameter to have an `as_dict` method. 

# Docstring

```
Signature: vis_client.annotate(image, features)
Docstring:
Annotate an image to discover it's attributes.

:type image: str
:param image: A string which can be a URL, a Google Cloud Storage path,
              or a byte stream of the image.

:type features:  list of :class:`~google.cloud.vision.feature.Feature`
:param features: The type of detection that the Vision API should
                 use to determine image attributes. Pricing is
                 based on the number of Feature Types.

                 See: https://cloud.google.com/vision/docs/pricing
:rtype: dict
:returns: List of annotations.
```

# Reproducing the error

The code to reproduce the error is below. It assumes you already have `PROJECT_ID` and `CREDENTIALS` necessary to create a vision client.

```
import google.cloud.vision

vis_client = google.cloud.vision.Client(
    project=PROJECT_ID, 
    credentials=CREDENTIALS
)

img_url = "https://i0.wp.com/evobsession.com/wp-content/uploads/2016/09/Chevy-Jolt.png"
label_feature = google.cloud.vision.feature.Feature('LABEL_DETECTION', max_results=10)

img_annotations = vis_client.annotate(img_url, [label_feature])
```

The error that results is as below. The fact that it tries to call `as_dict` suggests to me that there is a mismatch between input type that the docstring suggests and what the implementation actually expects.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-45-9c772d0bfc29> in <module>()
      2 label_feature = google.cloud.vision.feature.Feature('LABEL_DETECTION', max_results=10)
      3 
----> 4 img_annotations = vis_client.annotate(img_url, [label_feature])

/Users/shajek/anaconda/lib/python2.7/site-packages/google/cloud/vision/client.pyc in annotate(self, image, features)
    101         request = VisionRequest(image, features)
    102 
--> 103         data = {'requests': [request.as_dict()]}
    104         response = self._connection.api_request(
    105             method='POST', path='/images:annotate', data=data)

/Users/shajek/anaconda/lib/python2.7/site-packages/google/cloud/vision/client.pyc in as_dict(self)
     45         """Dictionary representation of Image."""
     46         return {
---> 47             'image': self.image.as_dict(),
     48             'features': [feature.as_dict() for feature in self.features]
     49         }

AttributeError: 'str' object has no attribute 'as_dict'
```

**Comment by daspecster** [comment]
@scottcode sorry for the confusion. The docs have been updated since, but Vision hasn't been released yet.

`image` should not be a string. It should be an instance of `google.cloud.vision.image.Image`.

Also, the library doesn't yet support URLs for image sources.

To fix you could download the image with [`requests`](http://requests.readthedocs.io/en/master) and then pass the content to Vision.

```python
image = client.image(content=image_content)
results = client.annotation(image, [feature])
```

Or you can do single annotations on an image like so.
```python
image = client.image(content=image_content)
results = image.detect_labels()
```

Some significant changes are coming in the next release, so you may want to pin the version of Vision you're using.

**Comment by scottcode** [comment]
Thanks for the clarification, @daspecster. I got it to work with both your suggestions, with the slight change to `client.annotate(image, [feature])` for the first option.

**Comment by daspecster** [comment]
Great to hear! Sorry for my typo.
