### ISSUE TITLE
would like to be able to specify timeout for get_bucket and download_to_file

### ISSUE THREAD

**Issue by pdudnik** [GoogleCloudPlatform/google-cloud-python#2988]
I am using some methods from this file gcloud/storage/client.py

Specifically, get_bucket and list_bucket.

I am struggling to figure out how I should set timeouts on these methods. I am worried about them being stuck.

**Comment by daspecster** [comment]
Hello @pdudnik!

Currently I don't think there is a way to set the timeout for storage operations directly.
However you may be able to [pass in your own HTTP client](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/4d2a7d170ad1fb0f5dd70caae6eb5cae9497bd6b/core/google/cloud/client.py#L104-L109) with a [timeout set](http://httplib2.readthedocs.io/en/latest/libhttplib2.html#httplib2.Http).

Also, I noticed that you're using `gcloud`. I would recommend that you update to the `google-cloud` package.

**Comment by lukesneeringer** [comment]
Note: Related to #2993.

**Comment by tseaver** [comment]
Exposing timeouts as arguments to API-invoking methods is a thing we have done piecemeal to date, with incomplete efforts across multiple APIs.  I wonder if there is a more satisfactory solution using a policy on the API-invoking object (usually the client via one of its helpers).

**Comment by lukesneeringer** [comment]
Closing as being handled by @jonparrott's retry strategy.

**Comment by glarrain** [comment]
@lukesneeringer could you please re-open this issue? AFAIK it has not been addressed although I may be wrong. In that case, would you mind telling us where in the code, docs or commits/PRs can we find out the solution to this issue?
