### ISSUE TITLE
Storage: add support for Per-Object Storage Class

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-python#2991]
We need to add support for Per-Object Storage Class (POSC).

Here some extra information to help:

- [POSC info from Cloud Storage documentation](https://cloud.google.com/storage/docs/per-object-storage-class)
- [POSC example with JSON API](https://cloud.google.com/storage/docs/changing-storage-classes)
- [Storage Class info from Cloud Storage documentation](https://cloud.google.com/storage/docs/storage-classes)

On top of that, google-cloud-dotnet has made an implementation which can be used as reference. 

- [Please view the Pull Request to understand the changes](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/pull/766)

If you have any implementation questions, please direct them at jskeet

/cc @jskeet @danoscarmike

**Comment by lukesneeringer** [comment]
@tseaver Is this something you would be able to take on?

**Comment by tseaver** [comment]
Wrinkles on the per-object API:

- The `storageClass` property can only be "set" during object creation.
- "Updating" a blob's storage class cannot be done via `PATCH`:  instead, one must perform a `rewrite`, passing the `storageClass` property dict in the body.

To handle this properly, we can't just re-use the `Bucket.storage_class` setter:  we should only allow setting the value if the object does not already exist (e.g., has no `createdTime`).  We will need to provide another API-invoking method, `update_storage_class`, which performs the `POST` request to the appropriate `rewriteTo` URL, passing the new property in the body.

**Comment by tseaver** [comment]
Because we don't send along blob properties during `upload_*` operations (#754, #1660), there is no point in adding a `storage_class` setter at all.

**Comment by lukesneeringer** [comment]
@tseaver This change is purely additive, correct? I can cut a `storage 0.23.1` safely?

**Comment by tseaver** [comment]
@lukesneeringer Sorry for the lag:  yes, it is purely additive.

**Comment by lukesneeringer** [comment]
@tseaver No worries, and thanks. I will probably cut minor updates to things on Monday morning.

**Comment by tseaver** [comment]
@lukesneeringer It occurs to me that calling the release `0.23.1` is actually a semver violation:  it isn't a bugfix, but a feature addition.

**Comment by lukesneeringer** [comment]
My understanding is that semver is picky about that post `1.0`, but less so in the `0` phase.
I have basically been using the middle-number bump for breaking changes, because we version using `>=0.23.x, <0.24`, and for these types of changes, my goal is to opt people in automatically.

Open to another approach.

**Comment by daspecster** [comment]
I talked to @lukesneeringer a tiny bit about this offline. I think we don't have a solid plan of how versioning should work since we split out the services from `gcloud`. I could be wrong but I think the umbrella package should be incrementing a lot faster and be at a higher number now?
