### ISSUE TITLE
Bigtable and operations_grpc are failing unit tests in travis.

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#2994]
Possibly other services as well.

```
>   from google.longrunning import operations_grpc
E   ImportError: cannot import name operations_grpc
```

See: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/200057226#L9600

**Comment by daspecster** [comment]
@lukesneeringer did something change with the longrunning packages?

**Comment by dhermes** [comment]
@daspecster The issue is a bad release of `protobuf` (3.2.0)

**Comment by lukesneeringer** [comment]
I fixed this by releasing a new version of `googleapis-common-protos` (1.5.1) this morning, which solves the problem that `protobuf` is complaining about (it requires any module creating a Descriptor to end in `_pb2`.

**Comment by dhermes** [comment]
@lukesneeringer `grpc-google-cloud-datastore-v1` will also need a new release, it ships the following files:

```
datastore_pb2_grpc.py
datastore_pb2.py
entity_pb2_grpc.py
entity_pb2.py
__init__.py
query_pb2_grpc.py
query_pb2.py
```

Is there a rollback planned for `protobuf`?

**Comment by lukesneeringer** [comment]
None that I know of.
Regenerating `grpc-google-cloud-datastore-v1` would actually be pretty consequential because of other changes made since then. However, we could potentially make a hand update to it that version-pins `protobuf` to `>=3.0.0, <3.2.0`, which would buy time.

We will need to update all of the gapic/grpc libraries shortly; I have been eyeing next week for that task.

**Comment by jgeiger** [comment]
I think you've got the wrong person...

**Comment by lukesneeringer** [comment]
I do. I meant @geigerj. My apologies.

**Comment by lukesneeringer** [comment]
Actually I think the `datastore` package might be fine. I do not see any `Descriptor` instances made there (or in any of the other packages I have spot checked).

**Comment by dhermes** [comment]
Gotcha
