### ISSUE TITLE
pubsub emulator project settings don't work

### ISSUE THREAD

**Issue by ensonic** [GoogleCloudPlatform/google-cloud-python#2996]
According to  `/usr/lib/google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --help`:
```
--projects: A comma-separated list of all valid project names. If unspecified, all projects are valid.
```
When I start it, no `--projects` are given:
```
gcloud beta emulators pubsub startExecuting: /usr/lib/google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=localhost --port=8847
...
```
Setting up the env:
```
$ gcloud beta emulators pubsub env-init
export PUBSUB_EMULATOR_HOST=localhost:8847
$ export PUBSUB_EMULATOR_HOST=localhost:8847
$ gcloud beta pubsub --project="test" topics create "foo"
ERROR: Failed to create topic [foo]: Requested project not found or user does not have access to it (project=test). Make sure to specify the unique project identifier and not the Google Cloud Console display name.
```

**Comment by dhermes** [comment]
@ensonic ISTM this is an issue solely with the `gcloud` CLI tool, is that correct?

**Comment by ensonic** [comment]
Yes, I now added some test setup to pre-create the topic. If there is a way to make the gcloud tool use the emulator, it would be nice to document it.

**Comment by dhermes** [comment]
This repo is a Python library for

@jonparrott What would be the best place to file a bug against the `gcloud` CLI Pub/Sub components?

**Comment by jonparrott** [comment]
@dhermes https://code.google.com/p/google-cloud-sdk/issues/list

**Comment by dhermes** [comment]
Thanks @jonparrott

**Comment by ensonic** [comment]
FYI: https://code.google.com/p/google-cloud-sdk/issues/detail?id=1539

**Comment by BrunoQuaresma** [comment]
@ensonic how do you the pre-create topic?

**Comment by softprops** [comment]
I fell into this trap as well. I'm trying to write a component tests for an integration with pubsub I don't control. It assumes pubsub and the emulator seemed like a nice fit except that I couldn't pre-create the topic before running the tests because the gcloud tooling doesn't seem to honor the env variable for the emulator host.
