### ISSUE TITLE
BigQuery properties issues in query.py

### ISSUE THREAD

**Issue by amirshavit** [GoogleCloudPlatform/google-cloud-python#3001]
(1) When I run a long, non-cached, sync query --
```
query_job = bq_client.run_sync_query(query_string)
query_job.run()
```
... it often returns without being complete. I call `query_job.fetch_data(page_token=None)` to try and get the result. If the query finished by that time -- all is well, however if doesn't, the server response doesn't include the job's name (`jobReference.jobId`); since the state is being completely erased/rewritten, following calls to `fetch_data` fail with `ValueError("Query not yet executed:  call 'run()'")`.

(2) The `run` method checks `if self._job is not None:` to prevent a double invocation. It should however run that check with `self.job` instead (no underscore), as `self._job` is only set if you previously used `self.job`.

(3) It would be 'nicer' if the total_rows property return an integer (or None) rather than a string.

**Comment by tseaver** [comment]
@amirshavit Thanks for the report!  I've set the `back-end` label because the [API docs for `jobs/getQueryResults`](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/getQueryResults) say that the resource returned from that API **must** include the `jobReference.jobId` subkey.

I've split out your second and third points into separate issues (#3002, #3003).

**Comment by lukesneeringer** [comment]
I will reroute this to the BigQuery folks.

**Comment by jcondit** [comment]
The OP is correct that these are issues in the design of the current library API. We're working on a revised version that will make the long-running query flow more convenient to execute.

**Comment by aschmolck** [comment]
What's the status of this? Does 0.26.x fix the problem?

**Comment by amirshavit** [comment]
Seems like it's not fixed; almost 6 months :disappointed:

**Comment by tswast** [comment]
The redesign will not have a separate "sync" query versus "async" query. To get the behavior of what the query method will be, use the async query method. With the [0.26.0 release](github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/bigquery-0.26.0) the QueryJob class follows the [PEP 3148 Futures API](https://www.python.org/dev/peps/pep-3148/).

```
    import uuid
    from google.cloud import bigquery

    client = bigquery.Client()
    query_job = client.run_async_query(str(uuid.uuid4()), query)
    query_job.begin()

    query_job.result()  # Wait for job to complete
    destination_table = query_job.destination
    destination_table.reload()
    for row in destination_table.fetch_data():
        print(row)
```

**Comment by lukesneeringer** [comment]
@tswast Closing this as your redesign supercedes it. Reopen if you disagree.
