### ISSUE TITLE
Ensure that libraries are designated alpha.

### ISSUE THREAD

**Issue by lukesneeringer** [GoogleCloudPlatform/google-cloud-python#3010]
As part of the refresh for `core>=0.23.0` and HTTP headers, please also ensure that all client libraries are designated alpha in `setup.py` _except_ the following, which are beta:

  * BigQuery
  * Datastore
  * Logging
  * Storage

This should be altered as part of the umbrella release (should be trivial).

Thank you. :-)

**Comment by dhermes** [comment]
IIRC we took the Google "alpha / beta" labels to mean something different than the PyPI. Though I don't really have an opinion here.

**Comment by lukesneeringer** [comment]
I am in the same boat. I do not think most people pay much attention to the PyPI labels.
That said, I cannot think of any reason for them to be out of sync, and "while we are doing a big umbrella release anyway" is the right time to fix it.
