### ISSUE TITLE
There is no possibility to extract or run project/saved queries

### ISSUE THREAD

**Issue by ToGoBananas** [GoogleCloudPlatform/google-cloud-python#3013]
Not a bug or issue, but it nice to have ability to extract SQL or run project query from python client

**Comment by daspecster** [comment]
@ToGoBananas is this for BigQuery?

**Comment by ToGoBananas** [comment]
@daspecster yes

**Comment by daspecster** [comment]
@ToGoBananas ok thanks!

I'm not sure that is available through the [REST API](https://cloud.google.com/bigquery/docs/reference/rest/v2/). @tseaver might have some ideas though.

**Comment by tseaver** [comment]
@ToGoBananas can you point out docs for the feature you are describing?

**Comment by ToGoBananas** [comment]
@tseaver https://cloud.google.com/bigquery/docs/saving-sharing-queries#sharing_queries_with_project_members
Seems like this feature are not available via REST api

More likely I need to create feature request here https://code.google.com/p/google-bigquery

Sorry for trouble, close issue?

**Comment by daspecster** [comment]
@ToGoBananas I think you're right.  If it gets added to the REST/gRPC API's let us know!
Thanks for looking into this!
