### ISSUE TITLE
Add system tests for spanner datatypes

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#3016]
Show inserting / reading all the datatypes supported by spanner, particularly:

- Special-case floats (`nan`, `+inf`, `-inf`).
- Arrays of all scalar types.

**Comment by dhermes** [comment]
Working on this right now.

**Comment by tseaver** [comment]
Fix released:

- https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/spanner-0.24.2
- https://pypi.python.org/pypi/google-cloud-spanner/0.24.2
