### ISSUE TITLE
Add system tests which exercise stream chunking / resume

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#3019]
The Java system tests do this by populating the database with:

- 1000 rows of size 4 KB
- 100 rows of size 40 KB
- 25 rows of size 400KB
- 10 rows of size 4 MB

And then reading all this data back.

**Comment by tseaver** [comment]
Implementation note:  the `setupClass` for this test should check for the existence of a specially-named database within its instance, and [raise a `unittest.SkipTest` exception](https://docs.python.org/2/library/unittest.html#setupclass-and-teardownclass) if it is not there.  This will allow developers to run the system tests without needing an expensive-to-build-and-maintain pre-populated database.

**Comment by dhermes** [comment]
:+1:

**Comment by tseaver** [comment]
@dhermes BTW, where did the script go which pre-populates the datastore indexes for system testing?
