### ISSUE TITLE
Remove '_BrokenOperationFuture' workaround

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#3020]
`google.cloud.spanner.databse._BrokenOperationFuture` is a subclass of `google.gax._OperationFuture` which attempts to work around the fact that the spanner back-end sometimes returns metadata instead of the expected empty response, which causes the normal future to blow up.

Once the back-end is updated to fix this, remove `_BrokenOperationFuture`.

**Comment by vkedia** [comment]
@tseaver @lukesneeringer 
Backend has been fixed to return empty response. You should be able to remove BrokenOperationFuture now.

**Comment by lukesneeringer** [comment]
@vkedia Thanks!
