### ISSUE TITLE
Add a convenience method to fetch data for a single row

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#3021]
@jonparrott would prefer:

```python
row = database.read_row(table='Albums', columns=('MarketingBudget',), key=[1, 1]))
```

**Comment by tseaver** [comment]
@jonparrott `read` takes a keyset and returns a sequence of row tuples.  If we implement `read_rows` as a thin wrapper around `read`, what semantics should we have for a read which returns no rows?  Raise a `NotFound`?  Return `None`?

**Comment by jonparrott** [comment]
I'm leaning towards `NotFound` (like datastore), but @vkedia should weigh in.

**Comment by mcurtiss** [comment]
It would be great for query iterators also to have a `get_one` or `one` method that returns the single row yielded by the query, else throwing an exception.

Note that SQLAlchemy has a similar `one` method: http://docs.sqlalchemy.org/en/latest/orm/query.html#sqlalchemy.orm.query.Query.one

**Comment by vkedia** [comment]
Regarding https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3021#issuecomment-317859229 it is definitely valid for the read to not return any row at all. User might just be checking for the existence of row. So `None` seems better.

Regarding https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3021#issuecomment-320546633 I agree it would be useful to have this and some of the other methods like `one_or_none`, `first`. Is there no common Python library that exposes these type of methods for an arbitrary iterator.  Similar to [this](https://github.com/google/guava/blob/fce5e62628a1eb3eab4dfdb7b6f2ce7fa3567557/android/guava/src/com/google/common/collect/Iterators.java#L313) in Java.

**Comment by lukesneeringer** [comment]
> Regarding https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3021#issuecomment-317859229 it is definitely valid for the read to not return any row at all. User might just be checking for the existence of row. So `None` seems better.

I would prefer empty list, I think.

> Regarding https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3021#issuecomment-320546633 I agree it would be useful to have this and some of the other methods like `one_or_none`, `first`. Is there no common Python library that exposes these type of methods for an arbitrary iterator.  Similar to [this](https://github.com/google/guava/blob/fce5e62628a1eb3eab4dfdb7b6f2ce7fa3567557/android/guava/src/com/google/common/collect/Iterators.java#L313) in Java.

I am not aware of any such animal (nor have I ever wanted one).

**Comment by lukesneeringer** [comment]
What semantics would we want for a read that returns _more than one_ row? We could have it send `limit=1` to `read`, but both SQLAlchemy and Django raise exceptions in this case.
