### ISSUE TITLE
Map Spanner DB-API onto a SQLAlchemy dialect

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#3023]
Blocked on #3022.

Relevant SQLAlchemy docs:

- [Dialect interface spec](http://docs.sqlalchemy.org/en/latest/core/internals.html#sqlalchemy.engine.interfaces.Dialect)
- [Existing dialects](http://docs.sqlalchemy.org/en/latest/dialects/index.html)

**Comment by lukesneeringer** [comment]
In an effort to get my project management to be a bit more sane, I am going to try something else in lieu of single issues that represent large projects.

I have referenced this on a [wiki page devoted to our significant feature backlog][1]. Discussion of this particular feature is still welcome here, although I am going to close this issue until such time as this is something we take on.

  [1]: https://github.com/GoogleCloudPlatform/google-cloud-python/wiki/Feature-Backlog

**Comment by cookie223** [comment]
Hopefully comments are welcomed here. It would be great to have this and hopefully I can use Spanner as airflow backend.

**Comment by ryan-lane** [comment]
Has there been any work on this? It's a major blocker for using spanner in python.

**Comment by s5** [comment]
This is a significant blocker for me as well.

**Comment by jonparrott** [comment]
@cookie223, @ryan-lane, @s5 we can't provide a full dialect until the backend service provides DML support. How useful would a read-only dialect be for your use cases?

**Comment by chemelnucfin** [comment]
Hello, feature requests will now be tracked in the project [Feature Requests](https://github.com/GoogleCloudPlatform/google-cloud-python/projects/5#card-6867160).  I will close this issue now, please feel free to continue to address any issues/concerns here.
