### ISSUE TITLE
Documentation Issue: Environment Variables Section is Not Complete

### ISSUE THREAD

**Issue by speedplane** [GoogleCloudPlatform/google-cloud-python#3030]
The [section in the documentation that describes environment variables](https://googlecloudplatform.github.io/google-cloud-python/stable/google-cloud-api.html#module-google.cloud.environment_vars) does not list all of them. In particular, it misses all of the environment variables defined in `google.auth.environment_vars` ([file here](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/master/google/auth/environment_vars.py)). Even though this is a separate project, it is packaged with and relied upon by google-cloud-python. These settings are pretty important.

**Comment by dhermes** [comment]
@speedplane `google.auth` is not part of this library. We do list `GOOGLE_APPLICATION_CREDENTIALS` in https://googlecloudplatform.github.io/google-cloud-python/stable/google-cloud-auth.html

Anything else that can be done? (Preemptively closing out.)
