### ISSUE TITLE
Cleanup duplicated "credentials can not sign" error

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#3031]
Context: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2998#discussion_r100650121

**Comment by lukesneeringer** [comment]
@jonparrott Is this still a thing?

**Comment by jonparrott** [comment]
Good question - @dhermes is it?

**Comment by dhermes** [comment]
We still have duplicated code:

```
$ git log -1 --pretty=%H
d750a1394781dbe33679057c02233d2dfc2540e1
$ git grep -n 'you need a private key to sign'
storage/google/cloud/storage/_signing.py:51:        raise AttributeError('you need a private key to sign credentials.'
storage/google/cloud/storage/bucket.py:1121:                'you need a private key to sign credentials.'
```

Now that `google.cloud.storage._signing` exists, you could probably move the check from `Bucket.generate_upload_policy()` into the `_signing` module.

**Comment by lukesneeringer** [comment]
Meta-comment: This is a really good example of an issue where a `TODO` in the code would have served a lot better than an issue does.
