### ISSUE TITLE
Remove dead branches

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3032]
@tseaver Are these all good to be deleted?

- https://github.com/GoogleCloudPlatform/google-cloud-python/tree/0.18-deprecation
- https://github.com/GoogleCloudPlatform/google-cloud-python/tree/spanner-release
- https://github.com/GoogleCloudPlatform/google-cloud-python/tree/0.18.4-prep

**Comment by tseaver** [comment]
> Are these all good to be deleted?
> - https://github.com/GoogleCloudPlatform/google-cloud-python/tree/0.18-deprecation

That one was yours, preparing the 0.18.3 release.

> - https://github.com/GoogleCloudPlatform/google-cloud-python/tree/spanner-release

I deleted it.

> - https://github.com/GoogleCloudPlatform/google-cloud-python/tree/0.18.4-prep

That one is the base for the open #2889 PR.

**Comment by dhermes** [comment]
OK cool. I just deleted `0.18-deprecation` as well.

IMO we don't need to release `0.18.4`, and it's possible that the warning I added to https://pypi.python.org/pypi/gcloud/0.18.3 is sufficient?

**Comment by daspecster** [comment]
I think we should atleast change the classifier to [`Development Status :: 7 - Inactive`](https://pypi.python.org/pypi?%3Aaction=list_classifiers). (it is currently still set to `Development Status :: 4 - Beta`)

Also, I wen to https://pypi.python.org/pypi/gcloud/0.18.3 after not seeing it for a while and I didn't even notice the warning. Just my $0.02.

**Comment by tseaver** [comment]
> IMO we don't need to release 0.18.4, and it's possible that the warning I added to https://pypi.python.org/pypi/gcloud/0.18.3 is sufficient?

Fine by me.  I deleted that branch after you closed #2899.
