### ISSUE TITLE
[pubSub] tell when to use subscription.reload()

### ISSUE THREAD

**Issue by ensonic** [GoogleCloudPlatform/google-cloud-python#3037]
The [api docs](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/pubsub/google/cloud/pubsub/subscription.py#L217) don't mention when one should use this api (when is my local config out of sync), e.g. is there are exception I should react to?

**Comment by tseaver** [comment]
@ensonic Thanks for the report!

The two bits of state which `Subscription.reload()` fetches from the server are the `ack_deadline` and `push_endpoint` attributes.  "Normal" use of the subscription (pulling events) isn't affected by those variables.  Any time your app *does* need to know their values for some reason (e.g., before calling `modify_push_endpoint()` to see what the current state is), then it is best to call `reload()` first.

**Comment by ensonic** [comment]
Thanks for the info. The reason I looked at the API was that I wonder if a subscription can go 'stale'. I have a case where a subscriber seems to be getting 'old' messages. The subscriber is ack'ing the messages. By 'old', I mean the message.service_timestamp is e.g. 3 hours behind. E.g.
```
[2017-02-22 14:13:14,361] INFO:root:msg-id: 110510709003979, ts: 2017-02-22T11:42:14.299000Z, topic: topic1
[2017-02-22 14:13:16,981] INFO:root:msg-id: 110519798495214, ts: 2017-02-22T14:11:24.310000Z, topic: topic1
```
Each topic is published by a gke instance. When I log into each instance the clock is looking alright. The service_timestamp is set here:
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/pubsub/google/cloud/pubsub/message.py#L90
