### ISSUE TITLE
Missing GQL support

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#304]
The [protobuf spec](https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/v1beta2-rev1-2.1.0/proto/datastore_v1.proto#L480) for queries suggests that queries should support [GQL](https://cloud.google.com/appengine/docs/python/datastore/gqlreference), but that support is missing.  Do we need to add support?

**Comment by dhermes** [comment]
Re-closing per discussion in meeting today with @jgeewax

**Comment by pcostell** [comment]
Can you provide the rational for not providing GQL?

**Comment by jgeewax** [comment]
I think the logic was "we should encourage people to use the ORM-ish thing we put together" -- and if someone wants to send a GQL query... it shouldn't be impossible, but I don't think it's a good idea...

Any rationale for why we'd want to expose the two different ways @pcostell ?

**Comment by pcostell** [comment]
Sometimes I feel that it's easier and cleaner to write a GQL query. More of an open question though -- if our client libraries aren't going to expose it, is it worth having in the Datastore API.

**Comment by jgeewax** [comment]
This actually is a great question... I don't know whether it's worthwhile -- and if it was, I'd expect it at a different endpoint ...

**Comment by dhermes** [comment]
@pcostell is my original comment incorrect?

> GQL is an artifact of days gone by, i.e. what people thought was useful when the datastore was initially created.

**Comment by pcostell** [comment]
Yes, I believe that original comment is incorrect. I think we'll see some major changes in GQL over the next year which will make it more useful for customers.

Just as an FYI, GQL in Cloud Datastore was redesigned and isn't compatible with the GQL in the App Engine python SDKs. So when Cloud Datastore was introduced an explicit decision was made to provide GQL support even though it wouldn't be backwards compatible (thus not an artifact of initial Datastore).

/cc @Alfus

**Comment by dhermes** [comment]
Gotcher, thanks. Re-opening.

We (maybe just me?) were under the impression that GQL was past its usefulness. If that isn't the case, we're happy to implement. Do you see a library implementing all of the associated nouns/verbs or just supporting text queries? (It seems the `GqlQueryArg` will require special support.)

**Comment by pcostell** [comment]
Datastore RunQueryRequest has a GqlQuery argument. This argument takes a string which is the entire query. GqlQueryArg is just used to fill into the string any parameters (by number or by name). So I could imagine an API that looks like:

    GqlQuery("SELECT * FROM MyKind WHERE a = @1 OFFSET @cursor", "myAValue", cursor=a_cursor)

Note the *args for numbered parameters and **kwargs for named parameters. These can get sent directly (+ some translation to proto) to Datastore.

**Comment by jgeewax** [comment]
The bigger concern for me was that we wanted to keep people focused on our abstraction rather than writing GQL, so at best this is a "low priority" item -- but if you disagree, let me know.

I think it'd be a bad idea to encourage people to build apps that rely on writing lots of GQL queries -- the same way we encourage people to use an ORM rather than write SQL queries.

**Comment by Fkawala** [comment]
Hello, 

_\<disclaimer\> I'm quite new to noSQL matters, hence I might lack of common-sense on the matter. I didn't found a better place to ask the question. \</disclaimer\>_

I have a collection of Entities of one *kind*. I need to extract the distinct values of one property, named *p*, of these Entities. In GQL, I would do "SELECT DISTINCT p from kind". How should I do that with the tools currently available in gcloud-python ? 

Apologies for highjacking this thread. 
Thanks
F.

**Comment by jgeewax** [comment]
Hi @Fkawala  You should probably post this over on StackOverflow to get help since this is really about the Python client library code.

**Comment by Fkawala** [comment]
@jgeewax that's done. Any ideas on that matter ?

**Comment by jgeewax** [comment]
Let's open a new issue for this -- this thread really isn't the right spot.

**Comment by dhermes** [comment]
Will go from [`v1beta2`][1] to [`v1beta3`][2], with the key distinction that in `proto3` we can use a map for the named arguments.

I think we can make a subclass of `datastore.Query` and implement this pretty swiftly.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/f220a36f129f35731de4aee25e7032f5b58db4a6/gcloud/datastore/_datastore_v1.proto#L319-L336
[2]: https://github.com/google/googleapis/blob/12dd2eafc6ba6d011c4079cbfb246b60f9fdc28d/google/datastore/v1beta3/query.proto#L205-L229

**Comment by dhermes** [comment]
I planned on doing this as part of #1288 and will tackle it soon

**Comment by danigosa** [comment]
Well it's ok to just use the ORM, our team we could not find a way to do a "like" operation using just query filters on string properties, that's why we looked for GQL, so if an Entity have a property name with values "name%d"%num how do we add filters to get name% queries?

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
