### ISSUE TITLE
Make Django Error Reporting Helper

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/google-cloud-python#3041]
Tracking issue for a low priority nice to have feature.

Create a helper so that when an unhandled exception is thrown in a Django app, make the stack trace show up in Stackdriver Error Reporting.

See the Flask helper as en example.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!

**Comment by therefromhere** [comment]
I've created a package that handles this - see https://github.com/prismaticd/dj-cloud-error
