### ISSUE TITLE
GAX headers

### ISSUE THREAD

**Issue by lukesneeringer** [GoogleCloudPlatform/google-cloud-python#3049]
This is a tracking meta-issue for adding the `gccl` header to the GAX side of each API client library:

Each PR should:

  * Add the `lib_name` and `lib_version` keyword arguments to the GAPIC client.
  * Bump the version of the client library to 0.23.0
  * Bump the GAPIC dependency to 0.15.0

Completion List:

  * [ ] ~Datastore~ (Putting this off.)
  * [x] Error Reporting (#3055)
  * [x] Logging (#3054)
  * [x] PubSub (#3052)
  * [x] Spanner (#3045)
  * [x] Speech (#3048)
  * [x] Vision (#3050)

**Comment by bjwatson** [comment]
@lukesneeringer Logging and Datastore are most urgent to complete, since they're Beta already.

@dhermes What's the status of https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2746? If we don't have the manual layer ported onto GAPIC, we're going to have to implement the full custom header (`x-goog-api-client`) in the manual layer.

**Comment by tseaver** [comment]
Datastore is still not GAPIC (although we've added the dependency).

```bash
$ git grep gapic datastore/
datastore/setup.py:    'gapic-google-cloud-datastore-v1 >= 0.14.0, < 0.15dev',
```

**Comment by tseaver** [comment]
@lukesneeringer has `pubsub` in work.  I will tackle `logging` and `error_reporting` bits today.

**Comment by dhermes** [comment]
#2746 was my next priority after this issue. Since @lukesneeringer is taking the GAPIC ones to the finish line I can work on that now?

**Comment by lukesneeringer** [comment]
Yeah.

**Comment by bjwatson** [comment]
Thanks @dhermes!

**Comment by lukesneeringer** [comment]
> @lukesneeringer Logging and Datastore are most urgent to complete, since they're Beta already.

@omaray told us the exact opposite on Datastore; that it was _least_ urgent because they are not in Concord yet. Based on that, I was actually intending to let it wait until @dhermes did #2746.

**Comment by bjwatson** [comment]
Ok, I would go with what @omaray said. :)

**Comment by lukesneeringer** [comment]
All items complete except Datastore. Closing this issue and tracking Datastore separately.

**Comment by bjwatson** [comment]
Thanks @lukesneeringer, @dhermes, and @tseaver! Can you let me know when packages are published with these updates? I assume that will be sometime today, due to the RTD issues.
