### ISSUE TITLE
Streaming download for the storage API?

### ISSUE THREAD

**Issue by protoforge** [GoogleCloudPlatform/google-cloud-python#3060]
I'm only seeing methods for downloading a blob to a file or string. Is there a stream method? This might be used for handling web requests or adding files to a zip archive.

**Comment by daspecster** [comment]
@protoforge I believe downloading [does support](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/d4d0abcab27b3f1aba9b56db4d643d5692230bd5/storage/google/cloud/storage/blob.py#L331) streaming.

Here's the [`download_to_file`](https://googlecloudplatform.github.io/google-cloud-python/stable/storage-blobs.html#google.cloud.storage.blob.Blob.download_to_file) docs.

I don't think that returns a stream object though. The downloading is handled by the library.

**Comment by protoforge** [comment]
Thanks - Is there anything ill-advised in direct use of the Download class?

google.cloud.streaming.transfer -> Download

**Comment by dhermes** [comment]
Nothing really ill-advised but we won't really be supporting it / may be subject to change (in the near future)

**Comment by danoscarmike** [comment]
Closing issue as resolved.
