### ISSUE TITLE
Bigtable operation never completes after error in grpc._cython.cygrpc.plugin_get_metadata

### ISSUE THREAD

**Issue by garye** [GoogleCloudPlatform/google-cloud-python#3061]
I'm working with a user to debug an issue in the following code:
https://gist.github.com/garye/1c273182ff7a27881396cd12931236a4

Once in a while when this code runs, the `read_rdc_item_data` function seems to hang at the `table.read_rows` call on line 94. It does not seem to be related to a particular query and no issue is visible on the bigtable server side. It does not seem easily reproducible on demand. The potentially interesting logging around when the incident occurs is:

```
Exception socket.error: error(101, 'Network is unreachable') in 'grpc._cython.cygrpc.plugin_get_metadata' ignored
```
and also
```
Exception oauth2client.client.HttpAccessTokenRefreshError: HttpAccessTokenRefreshError('Invalid response 502.',) in 'grpc._cython.cygrpc.plugin_get_metadata’ ignored
```

Because of concerns around [thread safety](https://developers.google.com/api-client-library/python/guide/thread_safety) of the client a new one is created before each request. More efficient solutions are under consideration.

**Comment by jonparrott** [comment]
The use of oauth2client indicates an older library, can you share which version is being used?

**Comment by garye** [comment]
Here's the output of `pip freeze`, looks like version 3.0.0
```
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
certifi==2016.2.28
docutils==0.12
enum34==1.1.6
future==0.15.2
futures==3.0.5
gapic-google-longrunning==0.11.2
gax-google-logging-v2==0.8.1
gax-google-pubsub-v1==0.8.1
google-api-python-client==1.5.5
google-cloud-bigquery==0.20.0
google-cloud-bigtable==0.20.0
google-cloud-core==0.20.0
google-cloud-happybase==0.20.0
google-cloud-storage==0.20.0
google-gax==0.15.0
googleapis-common-protos==1.5.0
grpc-google-logging-v2==0.8.1
grpc-google-pubsub-v1==0.8.1
grpcio==1.0.0
httplib2==0.9.2
lockfile==0.12.2
MySQL-python==1.2.5
numpy==1.11.1
oauth2client==3.0.0
ply==3.8
protobuf==3.0.0
pyasn1==0.1.9
pyasn1-modules==0.0.8
python-daemon==2.1.1
requests==2.12.4
retrying==1.3.3
rsa==3.4.2
simplejson==3.8.2
singledispatch==3.4.0.3
six==1.10.0
teradata==15.10.0.16
tornado==4.3
uritemplate==3.0.0
```

**Comment by jonparrott** [comment]
So two issues up front:

1. They shouldn't be using oauth2client, they should be using google-auth. This is handled automatically by the client library, so they can just remove their credentials logic and it should work.
2. They're 2 versions behind, the latest google-cloud-bigtable is 0.22.

**Comment by garye** [comment]
Thanks a lot, Jon. The user is going to upgrade to google-auth and google-cloud-bigtable 0.22 and attempt to reproduce in the next day or two.

**Comment by lukesneeringer** [comment]
@garye Closing this for now; feel free to re-open if upgrading does not solve your problem.

**Comment by craigtb** [comment]
Hi - It seems this issue has cropped back up again. The application seems to hang and never make it to our retry logic.  Here are the relevant logs.  Please let me know if you have any questions or suggestions.

```[ 2017-03-16 18:11:07,051 ] OF-SIM-PROC-LOG INFO     ### [SIM : 771 & SKU : 323399] SIMULATION PROCESS STARTED.
[ 2017-03-16 18:11:07,189 ] OF-SIM-PROC-LOG INFO     ### [SIM : 771 & SKU : 323399] Started reading LOC_ITEM data.
[ 2017-03-16 18:11:07,313 ] OF-SIM-PROC-LOG INFO     ### [SIM : 771 & SKU : 323399] Calling the Read Operation.
[ 2017-03-16 18:11:07,544 ] oauth2client.transport INFO     Attempting refresh to obtain initial access_token
[ 2017-03-16 18:11:07,406 ] OF-SIM-PROC-LOG INFO     ### [SIM : 771 & SKU : 323399] Returned from the Read Operation.
….
Exception google.auth.exceptions.RefreshError: RefreshError(u'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 502 (Server Error)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>502.</b> <ins>That\u2019s an error.</ins>\n  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That\u2019s all we know.</ins>\n', u'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 502 (Server Error)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>502.</b> <ins>That\u2019s an error.</ins>\n  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That\u2019s all we know.</ins>\n') in 'grpc._cython.cygrpc.plugin_get_metadata’ ignored```

**Comment by garye** [comment]
@lukesneeringer: unfortunately I don't seem to have permissions to re-open this but it does look like a similar issue has occurred even with the library updates.

**Comment by dhermes** [comment]
This is probably a `google-auth-library-python` issue? The error there is a 502 for the OAuth service. However, users can avoid talking to the service if they use JWT tokens. @jonparrott we resolved that issue, right?

**Comment by dhermes** [comment]
@garye We never made any particular update to fix or address this issue. This is a transient service error so it's tough to detect.

**Comment by jonparrott** [comment]
> users can avoid talking to the service if they use JWT tokens.

We haven't actually started promoting service account credentials to jwt credentials in this library yet.

> This is probably a google-auth-library-python issue? The error there is a 502 for the OAuth service. 

It's an issue with the oauth service. If we were using the urllib3/requests transport, we could do retries, but we're not, so we can't.

**Comment by garye** [comment]
@craigtb, just to confirm it looks like the library hangs after it receives that error? Is it possible that whatever error gets returned doesn't trigger retry logic for another reason?

I think failing and retrying (which they have logic for) is acceptable, but I believe the assertion was that the library hangs.

**Comment by dhermes** [comment]
Yeah gRPC's hangy-ness is a mystery to me at this point. I spent like an hour debugging a refresh error that gRPC swallowed and then the process just stared at me (i.e. hung) after.

**Comment by jonparrott** [comment]
Summoning @nathanielmanistaatgoogle

**Comment by nathanielmanistaatgoogle** [comment]
This isn't ringing any bells with respect to known issues.

Is this being observed with `grpcio` 1.1.3 or later? If so, what is a sequence of the calls and returns across the gRPC Python API leading up to the problem?

**Comment by craigtb** [comment]
@garye yes, it looks like its hanging at that error and holding the thread.  It seems to happen in this code block:
```while True:
            try:
                data.consume_next()
            except StopIteration:
                break```
We are adding another except block to try and catch any error and raise it.  This will hopefully push it into our retry logic.

**Comment by dhermes** [comment]
@craigtb Are you referring to [that block][1] in source, or elsewhere?

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/97379fcba1eced243eb2f0bee00c41b6344c7264/bigtable/google/cloud/bigtable/row_data.py#L322-L325

**Comment by craigtb** [comment]
@dhermes In our code where we are using the BigTable library.
https://gist.github.com/garye/1c273182ff7a27881396cd12931236a4

**Comment by garye** [comment]
Not sure who can best answer this, but does the python API expose a deadline that could be set and turn this hang into a `DEADLINE_EXCEEDED` error and leave it up to the client to retry?

**Comment by tseaver** [comment]
@garye We don't expose a "universal" way to set timeouts on operations:  we've added them to specific API wrapper methods (e.g., deca383ae3a6901064cb16fdba6d31259b36980c for `google.cloud.pubsub.topic.Topic.publish`).

**Comment by lukesneeringer** [comment]
@tseaver Any concerns about adding something similar here?

**Comment by tseaver** [comment]
My only concern is that this is whack-a-mole salad:  adding timeout support on an ad-hoc basis feels vaguely wrong, but I'm not sure that the Right Thing (TM) would be.

**Comment by lukesneeringer** [comment]
That sounds right to me. If we move HTTP support into GAX, we could likely unify it; until then, probably whack-a-mole is the right answer.

**Comment by garye** [comment]
What's the best way for @craigtb to make progress here? Adding a deadline whack-a-mole style requires a release, is there a short-term workaround?

**Comment by lukesneeringer** [comment]
Yeah, let's do that for now.

**Comment by garye** [comment]
Ok, do we think the deadline mechanism will actually work around whatever hang we're seeing?

**Comment by lukesneeringer** [comment]
Oh, I just re-read this. I am not sure.
On a separate note, can you upgrade to `grpcio` 1.2.0 (released last week)? There was a fix to a hanging issue in there.

**Comment by craigtb** [comment]
Hey - We updated `grpcio` and have pushed it out to our users.  We will monitor once they start using.

**Comment by lukesneeringer** [comment]
Let us know, thanks!

**Comment by garye** [comment]
@craigtb, any luck with this yet?

**Comment by craigtb** [comment]
@garye We haven't had any hangups since we got this updated.  We are going to let things run for a few more days to make sure the issue doesn't reappear.  Thanks for following up.

**Comment by lukesneeringer** [comment]
@craigtb Huzzah.

I am going to close this issue since it is probably resolved, but please feel free to reopen if that turns out not to be true.

**Comment by craigtb** [comment]
@lukesneeringer @garye Looks like we ran into this issue again last night.  It seems like its hanging before it ever does anything within the consume_next function.  We put some logging inside that function and we did not see any of it for this unit of work.

**Comment by garye** [comment]
@craigtb Out of curiosity, does the CPU of your VM spike while there is a hang?

**Comment by craigtb** [comment]
@garye No we haven't seen anything strange with that.
