### ISSUE TITLE
storage get_blob very frequent exception '503 Service Unavailable'

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/google-cloud-python#3072]
If you can provide us with as much of the following information as possible it
will help us identify the cause of your issue more quickly.

1. GCP VM: `Linux ptk-parsing2 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
2. Python: `3.5.2`
3. google-cloud-python version `0.23.0`
4. Stacktrace:
```
blob = bucket.get_blob(file_name)
  File "/home/vvesselinov/.local/lib/python3.5/site-packages/google/cloud/storage/bucket.py", line 233, in get_blob
    method='GET', path=blob.path, _target_object=blob)
  File "/home/vvesselinov/.local/lib/python3.5/site-packages/google/cloud/_http.py", line 335, in api_request
    error_info=method + ' ' + url)
google.cloud.exceptions.ServiceUnavailable: 503 Service Unavailable (GET https://www.googleapis.com/storage/v1/b/xxx/yyy.zzz)
```
5. Steps to reproduce: create a program that is reading a lot of files (e.g. 100'000) and writing them back with some transformation, randomly the program is crashing

https://cloud.google.com/storage/docs/json_api/v1/status-codes

Suggestion to follow the GCP recommendations:
https://cloud.google.com/storage/docs/exponential-backoff

**Comment by VelizarVESSELINOV** [comment]
Same for `InternalServerError`. It will be nice if you can catch your internal errors and retry instead to propagate the error to the external user of the library

**Comment by daspecster** [comment]
@VelizarVESSELINOV thanks for the report!

I referenced this issue in #2694. I'm going to close this for now and track over there unless you feel the need to open it again.
