### ISSUE TITLE
RetryErrors obscure actual errors.

### ISSUE THREAD

**Issue by lukesneeringer** [GoogleCloudPlatform/google-cloud-python#3083]
@daspecster Please take a look at [this issue][1].

Instead of raising a retry error saying that we got an error that was not classified as transient, can we just re-raise the original error? What is there now is a nightmare for debugging.

  [1]: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/833

**Comment by daspecster** [comment]
Interesting, I'll see if I can track it down.

**Comment by lukesneeringer** [comment]
This never happened, but Vision has been moved to autogen, so this issue is more or less obselete.

**Comment by mr-ubik** [comment]
I am having the exact issue but with the google-cloud-language package. I am streaming tweets (working with Apache Beam) to the Language Sentiment Analysis API but some of them seem to break it.
```python
class SentimentAnalyzerDoFn(beam.DoFn):
    def process(self, element):
        """Takes a parsed tweet as input and add to it its sentiment score and values"""
        from google.cloud import language
        client = language.LanguageServiceClient()
        document = language.types.Document(
            content=element['tweet'].encode('utf-8'),
            type='PLAIN_TEXT')
        response = client.analyze_sentiment(
            document=document,
            encoding_type='UTF8')
        sentiment = response.document_sentiment
        element['sentiment_score'] = sentiment.score
        element['sentiment_magnitude'] = sentiment.magnitude
        yield element
```

The error I am getting is this: 
```python
RetryError: Exception occurred in retry method that was not classified as transient [while running 'SentimentAnalasys']
```
Is there a way to investigate it?

**Comment by ensonic** [comment]
@lukesneeringer this is not specific to the API, it is a general problem
