### ISSUE TITLE
How should we pass options for http clients in service client creation?

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#3109]
In order to address #2988, where timeouts are not a service option, but need to be handled by the HTTP client.

How should we handle passing arguments like `timeout` when creating a service client?

```python
client = someservice.Client(timeout=10)
```

This value could then be passed [here](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/14c250316aeef72b7f951a0959c46855948bd2b7/core/google/cloud/client.py#L118-L139) but we would need to assume the argument was available.

In this case [`google_auth_httplib2.AuthorizedHttp`](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/d840beceafacd37a6abf993cd1fb8039eb3b6864/httplib2_transport/google_auth_httplib2.py#L147) doesn't take the argument but rather an already created http client.

We could make another mixin class for `Client` I suppose that supports setting `timeout`?

**Comment by lukesneeringer** [comment]
This question should likely be informed by #1998, since how that implementation is done may affect this.

I would also be okay with only supporting a situation like a custom timeout if they use our default objects.

**Comment by dhermes** [comment]
I am :+1: on the idea to make it configurable, but I really wish we had an easier way of passing in custom transport objects. For example

```python
import urllib3
pool_manager = urllib3.PoolManager(timeout=10)
```

**Comment by jonparrott** [comment]
This is probably an artifact of httplib2, all other transports can accept a timeout per-request.

**Comment by daspecster** [comment]
So is this something that should wait, and maybe focus on #1998 first?

**Comment by lukesneeringer** [comment]
Defer to @dhermes, but that is my take on it.

**Comment by jonparrott** [comment]
So many things will be easier once we nail #1998.

**Comment by lukesneeringer** [comment]
Closing for now. #1998 is in progress.

**Comment by glarrain** [comment]
Hi @lukesneeringer. I wonder if you could explain how #1998 solves the problems raised in this issue.

From what I've been able to dig up, there is no way to set up a timeout/retries for a client in a simple and clean way (i.e. not involving private APIs nor deprecated parameters). The closest would be the timeout decorators (defined in `google.api_core.timeout`) but those are only of some use if the caller has access to the function with an arg named `timeout` but in that case they are barely helpful.
