### ISSUE TITLE
Set x-goog-api-client header for Spanner rpcs

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-python#3123]
I believe this has been done so far for Bigtable and Datastore. We should do the same for spanner as well since we use it for internal metrics.

**Comment by dhermes** [comment]
This is [done][1] and has been released in `0.23.1`.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/c43e8f1e59477a5f94996b0a10b6bacc483e4183/spanner/google/cloud/spanner/client.py#L152-L170

**Comment by vkedia** [comment]
The code you pointed to is for the admin APIs. Is this also being done for the data API?
Our backend logs do not show any requests where x-goog-api-client contains "python" string (or similar) in it. At the very least we should be seeing some requests from the integration tests?

**Comment by tseaver** [comment]
@vkedia the non-admin APIs have the [same configuration in `database.py`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/c43e8f1e59477a5f94996b0a10b6bacc483e4183/spanner/google/cloud/spanner/database.py#L179-L185).

**Comment by vkedia** [comment]
@tseaver What would be the exact value of "x-goog-api-client"? I wonder why are we not seeing anything in our logs in that case. Maybe I am looking for the wrong string.

**Comment by tseaver** [comment]
The header is generated by `google.gax.api_callable`.  I'm not sure of the format, but it should start with `gl-python` and the Python version;  it should inclue `gccl` and the version of `google-cloud-spanner`, and tokens for the `gax` and `gapic` versions.

@lukesneeringer could probably point you to the spec for the header contents.

**Comment by vkedia** [comment]
@tseaver @lukesneeringer There must be some bug somewhere because I am not finding any requests where the x-goog-api-client looks like that. I did find requests where the UserAgent was "grpc-python/1.3.3 grpc-c/3.0.0 (manylinux; chttp2; gentle),gzip(gfe)". I am guessing these requests came from python library? x-goog-api-client was empty on these.
Is it possible to dump the headers of outgoing requests on the client side and confirm that the header is being set?

**Comment by tseaver** [comment]
Here is what the `kwargs['metadata']` looks like in the run up to the call:

```python
(Pdb) pp kwargs
{u'metadata': [(u'x-goog-api-client',
                'gl-python/2.7.12 gccl/0.24.1 gapic/0.15.3 gax/0.15.13 grpc/1.3.3')]}
```

**Comment by tseaver** [comment]
The code which actually generates the gRPC header from that metadata is buried too deep inside the gRPC stack for me to find.

I would say the bug is not in this library, unless it turns out that *every* place where we set up the call optoins metadata is borked the same way.

**Comment by vkedia** [comment]
Is there a way to make gRPC dump headers it is sending out?

**Comment by vkedia** [comment]
You can turn on GRPC tracing to look at the actual headers being sent. I did that and I con confirm that x-goog-api-client header is not being set atleast for the data api. Here is a handy command:

`GRPC_TRACE=http GRPC_VERBOSITY=DEBUG python quickstart.py 2>&1 | grep SEND_INITIAL_METADATA | egrep '(user-agent|x-goog-api-client)'`

**Comment by tseaver** [comment]
I think this has to be an issue in https://github.com/googleapis/gax-python, rather than here:  that library is responsible for generating that header.

**Comment by vkedia** [comment]
Possibly though in that case it should manifest in other libraries as well and not just spanner.

**Comment by vkedia** [comment]
@lukesneeringer I think I found the issue. The issue is really in gax that it does not merge the metadata given while creating the callable correctly with extra metadata given while making the call. In that case it will just use the metadata given later. You pass the "google-cloud-resource-prefix" header here:
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/391c6fd807f5f4c0ea7066ec086cfa67b47a637e/spanner/google/cloud/spanner/_helpers.py#L271

This ends up overwriting the metadata which contained "x-goog-api-client" header since gax just calls update on the dictionary kwargs which overwrites existing keys:
https://github.com/googleapis/gax-python/blob/master/google/gax/__init__.py#L159

**Comment by danoscarmike** [comment]
Ping @tseaver can you review latest update from @vkedia?

**Comment by tseaver** [comment]
@danoscarmike AFAICT this is an issue for https://github.com/googleapis/gax-python, where I am not a maintainer.

**Comment by danoscarmike** [comment]
Thanks Tres.  @lukesneeringer can you verify Tres' suspicion?  If true let's link to an issue in that repo.

**Comment by bjwatson** [comment]
@vam-google @lukesneeringer This is fixed now, correct?

**Comment by tseaver** [comment]
@bjwatson I don't see anything in the gax-python repository which would have fixed the issue, which is why I opened https://github.com/googleapis/gax-python/issues/198

**Comment by bjwatson** [comment]
@tseaver This was fixed by @vam-google in https://github.com/googleapis/gax-python/pull/193. He might have independently discovered the same underlying bug.

**Comment by tseaver** [comment]
Great, now we just need a released version which incorporates that fix.

**Comment by bjwatson** [comment]
@lukesneeringer Can you publish an updated GAX?

**Comment by vkedia** [comment]
Any updates on this?

**Comment by lukesneeringer** [comment]
[gax 0.15.14 is released](https://pypi.org/project/google-gax/0.15.14/)
