### ISSUE TITLE
What SO tag to use

### ISSUE THREAD

**Issue by xmedeko** [GoogleCloudPlatform/google-cloud-python#3131]
When I open a new issue here the text says to use SO tag `google-cloud-python`:

If you are reporting  .... to see if there is already work being done.
- http://stackoverflow.com/questions/tagged/google-cloud-python

The SO tag `google-cloud-python` has no guidance, to icon. However, the SO tag `gcloud-python` has a guidance and a nice Google Cloud logo. Which one is right? If the `google-cloud-python`, may you polish it? Thanks.

**Comment by daspecster** [comment]
Thanks for the report @xmedeko!

@lukesneeringer or @omaray, do you have access to the StackOverflow account to update this?

**Comment by lukesneeringer** [comment]
I do not. @omaray?

**Comment by omaray** [comment]
Hello xmedeko. Thanks for pointing out that gcloud-python has a logo next to it. We'll make sure to remove it.

Regarding what tag to use - we normally recommend using a double tag system: [python][product]. So for bigquery for instance, you could use [python][google-bigquery].

**Comment by xmedeko** [comment]
@omaray What if a want to address this library in general? When I open a new issue here the text says to use SO tag `google-cloud-python` - is that the right tag? What about `gcloud-python` is it the wrong tag? If I look into the SO questions, many users use both of them, i.e. they are confused like me.

**Comment by omaray** [comment]
To clarify: the `gcloud-python` tag should not be sponsored with a logo anymore. I made a request and waiting for a response. Thank you for pointing that out.

Then the fact that the text says to use "google-cloud-python" is actually something that was debated (whether we should use it or not). Meaning,  when people use a client library, it's usually "in a **language** and for a **product**". Therefore, they'll want to tag their language and the actual product. So expecting to have 2 tags also make sense.

But that being said, what would be your expectations here? Would you expect to use a single tag, like `[google-cloud-python]`, or use two tags such `[python][google-bigquery]` if you used the bigquery library?

**Comment by xmedeko** [comment]
The `[python]` tag and the product tag are too broad. So I vote for both `[google-cloud-python]` and the product tag:
- The problem may not be related to any particular product, just to the `[google-cloud-python]` library itself.
- When the problem is related to a particular product, it should be tagged with both `[google-cloud-python][google-bigquery]`.

Note: there is also a tag [`google-api-python-client`](http://stackoverflow.com/tags/google-api-python-client/info) for the old Python client library, too.

**Comment by omaray** [comment]
Yes, I'm indeed aware of these other google-api-* tags. 

Thanks for the feedback xmedeko. We'll consider strongly.

**Comment by lukesneeringer** [comment]
Regardless of the final decision, closing this issue.
