### ISSUE TITLE
Vision support ImageContext throughout all detection types.

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#3132]
I think the reason this wasn't supported before was because it wasn't supported on all the detection types.

Right now it's only really in [`Crop Hints`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/7ba4d7a211e19d2a3fe8641ce3443e30a34ae4da/vision/google/cloud/vision/image.py#L164).

If someone can confirm that this is supported on everything else, I can start adding it.

**Comment by lukesneeringer** [comment]
Huh?

**Comment by daspecster** [comment]
[This](https://cloud.google.com/vision/docs/reference/rpc/google.cloud.vision.v1#google.cloud.vision.v1.ImageContext) might explain a bit better.

I've abstracted the usage away from the user and just allowed them to pass in values that coincide with the API they're using, but my question is maybe I should expose that for all the detection types if it's used by all the detection types? But I don't know if they all use it or not?

**Comment by lukesneeringer** [comment]
All this code is gone. Closing.
