### ISSUE TITLE
how to import LogSeverity in python

### ISSUE THREAD

**Issue by daiyueweng** [GoogleCloudPlatform/google-cloud-python#3143]
Hi, is there a way to import `LogSeverity` in `Python` using the client library. I can only find it in [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#logseverity). I couldn't find it in [Entries](https://googlecloudplatform.github.io/google-cloud-python/stable/logging-entries.html) for `Python`.

I am wondering do I need to take a reference to the LogEntry rest API to define the `severity` for each `log_text` or `log_struct` call. Or I can define my own `severity` levels. 

thanks

**Comment by Fkawala** [comment]
If you want your log to be displayed properly in the Cloud Platform Console Logging page [1] you'll have to use the standard python log levels names (ie. 'INFO', ..., 'CRITICAL'). The `logging.LogRecord` instances have their log level name available in their levelname attribute.

[1] https://cloud.google.com/logging/docs/view/logs_viewer_v2
