### ISSUE TITLE
Language: support mention type in Entity.mentions.

### ISSUE THREAD

**Issue by landrito** [GoogleCloudPlatform/google-cloud-python#3149]
[Currently](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/language/google/cloud/language/entity.py#L79) the mentions property of an entity is only a list of strings whereas it should be a list of objects containing the mention text and mention type.

Furthermore, this change should add mention_type information to the mention documentation.

**Comment by lukesneeringer** [comment]
Adding the release blocking tag; this is a beta blocker.
