### ISSUE TITLE
Batch upload fails when messages exceed API limit

### ISSUE THREAD

**Issue by quom** [GoogleCloudPlatform/google-cloud-python#3154]
1. OS type and version
All OS and all versions supporting topic.Batch
2. Steps to reproduce
Create a batch context & publish messages to it
On batch commit an API failure occurs due to batch size being too large

Suggestion:
In the publish function check the serialised size of the message does not exceed 10MB and that the number of messages doesn't exceed 1000. If it does then commit the batch prematurely and clear the batch queue.

I've crudely implemented it in my own project (just for size, not quantity):
```
class SizedBatch(topic.Batch):
    def __init__(self, topic, client):
        super(SizedBatch, self).__init__(topic, client)
        self.messages_size = 0

    def publish(self, message, **attrs):
        self.topic._timestamp_message(attrs)
        item = {'data': message, 'attributes': attrs}
        self.messages.append(item)
        self.messages_size += len(base64.b64encode(json.dumps(item, ensure_ascii=False).encode('utf-8')))
        if self.messages_size > 95e5:
            self.commit()
            self.messages_size = 0
```
Of course this adds the published message to the queue before checking, allowing a case in which the message creates the API violation but from my own observations the API accepts messages of 15MB and sometimes of 20MB. This also does not take into account the other aspects of the message (which are largely insignificant compared to the message content). Another issue with this snippet is that self.messages_size is not reset if performing a manual commit() on the batch.

**Comment by tseaver** [comment]
@quom Thanks for the report!

**Comment by lukesneeringer** [comment]
This exact implementation will not work well because of strings vs. bytes in Python 3. I am working on something that will be compatible though.

**Comment by quom** [comment]
Does encoding the string as utf-8 bytes & then base64 encoding it not produce the correct format?

**Comment by lukesneeringer** [comment]
It is a little tricker than that because `json.dumps` does not accept bytestrings in Python 3.

**Comment by lukesneeringer** [comment]
@quom Can you check out the #3157 pull request and verify that it meets your use case?

**Comment by tseaver** [comment]
@tmatsuo Can you confirm whether the 10MB limit, as mentioned in the [pubsub docs](https://cloud.google.com/pubsub/docs/publisher#publish), is per-message or per batch?

**Comment by quom** [comment]
@lukesneeringer Yep this solves my case.

I don't quite fully understand your point here though:
> It is a little trickier than that because json.dumps does not accept bytestrings in Python 3.
I'm creating a dict (containing strings), calling json.dumps (i.e. not calling it with byte strings) and then taking the length of the utf8 encoded output. In your pull request it looks like you ignore the additional punctuation of how the message is stored in the request and are just adding up the data length (which is a reasonable approximation to make).

@tseaver https://cloud.google.com/pubsub/quotas#other_limits states that it is a 10MB limit per publish request (so batch or single message).

**Comment by lukesneeringer** [comment]
> I'm creating a dict (containing strings), calling json.dumps (i.e. not calling it with byte strings) and then taking the length of the utf8 encoded output.

Exactly, and that is not an assumption that we can make. We might be getting _bytes_ rather than strings as the message, and we can not send that to `json.dumps`.

> In your pull request it looks like you ignore the additional punctuation of how the message is stored in the request and are just adding up the data length (which is a reasonable approximation to make).

Yeah, that was where I landed. Since `attrs` is consistently JSON-serializable and `message` is not, I just coerced `message` to bytes, JSON-dumped the `attrs`, and ignored the punctuation, deciding it was "good enough".

**Comment by tseaver** [comment]
@lukesneeringer Published messages *must* be bytes, on either Python2 or Python3.

**Comment by lukesneeringer** [comment]
Correct, we convert them to `bytes` later, regardless of what they come in as. However, they might _come in as_ bytes, and we cannot send that to `json.dumps` (nor can we safely assume utf-8).

**Comment by tseaver** [comment]
We [document](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/1bd4f11166c102a97b5a2bdd1fd6026e26493cf5/pubsub/google/cloud/pubsub/topic.py#L239) [that](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/1bd4f11166c102a97b5a2bdd1fd6026e26493cf5/pubsub/google/cloud/pubsub/topic.py#L481) they *must* be bytes, and we do not coerce them (we call `base64.b64encode()` on the message, which would fail for non-bytes on Py3k).

**Comment by tseaver** [comment]
Checking closer, the `google.cloud.pubsub._gapic` module *does* coerce before assigning the message to the protobuf, but the `_http` module does not:  it encodes the bytes using `b64encode` and then *decodes* them to Unicode as `ascii`.

**Comment by lukesneeringer** [comment]
Aha, I had only looked at the `_gapic` module. We should decide on a consistent mechanism.

I would probably prefer that text strings raise an exception, but that bugfix would be a pretty drastic backwards-incompatible change. It might be better to go the forgiving route at this point

**Comment by tseaver** [comment]
I'd say we've documented the `bytes` requirement all along:  we could just enforce it.
