### ISSUE TITLE
"Client GRPC deadline too short" for speech streaming_recognize + cannot override defaults

### ISSUE THREAD

**Issue by cgratie** [GoogleCloudPlatform/google-cloud-python#3165]
There is currently no way to override default configuration parameter values when using **google.cloud.speech.Client**. Support is available in **google.cloud.gapic.speech.v1beta1.speech_client.SpeechClient** via the **client_config** constructor argument. However, this is not used in **google.cloud.speech._gax.GAPICSpeechAPI**, where a **SpeechClient** instance is constructed without making use of **client_config**.

This means, among other things, that I cannot set the GRPC deadline myself. On the other hand, the default value for timeout present in the configuration file as **"timeout_millis"** under **"StreamingRecognize"** is **190000**, which should be perfect for a call that needs to be shorter than 1 minute anyway (required deadline is 3 * duration + 5, so 185 should already be enough). However, it looks like the actual value that is sent as a deadline comes from **"initial_rpc_timeout_millis"** field from **"retry_params"** in the configuration file (I have actually changed that value to 185000 and the error disappeared). I'm not sure why this is the case and I could not figure out where it happens in the code.

I am experiencing the issue while using the following versions of Python packages:
* gapic-google-cloud-speech-v1beta1 (0.15.3)
* google-auth (0.8.0)
* google-auth-httplib2 (0.0.2)
* google-cloud-core (0.23.1)
* google-cloud-speech (0.23.0)
* google-gax (0.15.8)
* googleapis-common-protos (1.5.2)
* grpcio (1.1.3)

**Comment by daspecster** [comment]
@cgratie thanks for reporting!

The limit for streaming detection [is 1 minute](https://cloud.google.com/speech/limits).
However if the GAPIC code isn't using the `timeout_millis` argument there may be a bug there.

I will look into that and also see about passing that config to the GAPIC API constructor.

**Comment by cgratie** [comment]
So the code I am running it the following.
```
    client = speech.Client(use_gax=True)
    stream = open("sample.raw", "rb")
    sample = client.sample(
        stream=stream, encoding=speech.Encoding.LINEAR16, sample_rate=16000)
    responses = client.speech_api.streaming_recognize(
        sample, language_code="en-GB", max_alternatives=30, interim_results=True)
```
The audio "sample.raw" is 25 seconds long. The error I get when running without changing defaults is:
```
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 367, in next
    return self._next()
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 358, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Client GRPC deadline too short. Should be at least: 3 * audio-duration + 5 seconds. Current deadline is: 59.499317329144105 second(s). Required at least: 60 second(s).)>
```
I also ran a new test, seeing that the deadline is so close to what the server expects: I changed **"initial_rpc_timeout_millis"** from the config file to **61000**. What I got is:
```
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Client GRPC deadline too short. Should be at least: 3 * audio-duration + 5 seconds. Current deadline is: 60.594876442104578 second(s). Required at least: 61 second(s).)>
```
If I change **"initial_rpc_timeout_millis"** from the config file to **185000**, everything works just fine and I get no error.

Hope this helps.

**Comment by daspecster** [comment]
@cgratie is there anyway way that your sample.raw could have been recorded at a different bitrate than 16,000?

**Comment by cgratie** [comment]
@daspecster It is very unlikely, the result is actually piped from **ffmpeg** with **-ar 16000**. Also, if the actual rate was, say, 44100, the duration would go beyond the 1 minute limit and the file would not go through regardless of the timeout setting.

**Comment by lukesneeringer** [comment]
You said the audio is 25 seconds long? Because 25 * 3 + 5 is equal to 80.
What happens if you try something that is >= 81 seconds? (I say 81 since obviously the `float` conversion is causing issues at the exact level.)

Could you try that?

Obviously this error message is lousy either way, and we want to improve that. :-) But for now, let's see if we can get you working...

**Comment by daspecster** [comment]
@lukesneeringer I think @cgratie is up and running right?

>If I change "initial_rpc_timeout_millis" from the config file to 185000, everything works just fine and I get no error.

But this definitely weird.

**Comment by cgratie** [comment]
**Update:** I can no longer reproduce the issue. I've checked the package versions I had before (good thing I had posted that) and the only change seems to be **grpcio 1.1.3** to **grpcio 1.2.0**. So maybe the problem was there and it was fixed?

It would still be nice to have more control over configuration options when creating a Client instance, but now at least it works fine with the default configuration so I'm happy.

**Comment by cgratie** [comment]
@daspecster Yes, I am up and running, by hacking the config file.
@lukesneeringer Indeed, changing **"initial_rpc_timeout_millis"** to 81000 was enough to make it work. Setting it to 79000 gives
```
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Client GRPC deadline too short. Should be at least: 3 * audio-duration + 5 seconds. Current deadline is: 78.5995279023191 second(s). Required at least: 79 second(s).)>
```

**Comment by lukesneeringer** [comment]
Okay, so the _formula_ in the error message is correct, but the _time target_ in the error message is bogus.

We should make it so that you do not have to outright hack the config file; the auto-generated `SpeechClient` [does take a `client_config` object][1] that we should actually expose in the manual layer.

  [1]: https://github.com/googleapis/api-client-staging/blob/master/generated/python/gapic-google-cloud-speech-v1beta1/google/cloud/gapic/speech/v1beta1/speech_client.py#L62

**Comment by lukesneeringer** [comment]
Another thing to consider: Perhaps we should change those default timeouts for speech. It seems like `initial_rpc_timeout_millis` might just be too low for speech.

So, the limit for audio is one minute, which means we should probably have an initial timeout setting of at least 185 seconds (actually 186 seconds due to the float thing). That is an easy change to just make and then generate a new auto-gen layer. You would get the change as soon as you upgraded the dependency.

**Comment by lukesneeringer** [comment]
We decided not to expose the client config just yet (pending some design questions), but I am still hoping to get the default config changed to avoid this error.

**Comment by cgratie** [comment]
@lukesneeringer What I wonder is why `initial_rpc_timeout_millis` is used for timeout, and not `timeout_millis`, under `StreamingRecognize` in the config file. The latter has a value of 190 seconds, which seems just right. Is that value used anywhere?

**Comment by lukesneeringer** [comment]
>  Is that value used anywhere?

Yes, in the streaming methods. (See the discussion on googleapis/googleapis#297 where this was brought up.)

**Comment by lukesneeringer** [comment]
The new `google-cloud-speech` exposes the GAPIC directly, so this parameter can now be passed.
