### ISSUE TITLE
Text Detection Client Not Synched Up to Server Update _KEY_MAP values Missing

### ISSUE THREAD

**Issue by yatuzhang** [GoogleCloudPlatform/google-cloud-python#3174]
Hi,

There seems to be some changes in JSON response returned from the server, but the client library is not up-to-date.

The issue seems to be from an outdated [annotations.py](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/8f3881adb20e0783599add7a3528e7aa69e1093e/vision/google/cloud/vision/annotations.py)

For instance, I see that there is now a key called fullTextAnnotation returned by the server when calling detect_text(), but the corresponding _KEY_MAP is missing this key in the client library I installed from pip, causing KeyError.  The latest commit from your repository does have this key, but as far as I understand these changes are not released yet?

Would there be a possibility of cross checking the versions in the future so that when the server changes it is still backwards compatible and doesn't just break the client?

**Comment by daspecster** [comment]
@yatuzhang thanks for reporting!

Actually `fullTextAnnotation` is in the current released version ([0.23.3](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/vision-0.23.3/vision/google/cloud/vision/annotations.py#L31)).

What version does your `pip freeze` say is installed?

**Comment by lukesneeringer** [comment]
I also see an `if feature_type in _KEY_MAP` check, so new keys should not just break the client.

**Comment by lukesneeringer** [comment]
Closing this for now. Feel free to re-open if there is new information.
