### ISSUE TITLE
More secure Docker support

### ISSUE THREAD

**Issue by kevhill** [GoogleCloudPlatform/google-cloud-python#3179]
From the documentation, it looks like you need to include the service account .json file with the private key into any code repo/docker image that you use to develop. Obviously, this is not the most secure practice, nor the most flexible in developing in multiple environments.

Is there any way to pass the client id and private key used to go through the service account OAuth flow directly through environmental variables?

**Comment by daspecster** [comment]
Docker has some support for managing secrets.

https://blog.docker.com/2017/02/docker-secrets-management

You can override the path to the credentials with
```
export GOOGLE_APPLICATION_CREDENTIALS=/path/to/your/credentials.json
```

Let me know if that helps!

**Comment by kevhill** [comment]
Thanks for the link @daspecster I hadn't seen that new feature in docker. However, it looks like it is part of swarm right? I don't see how you'd, say use that for local development and then deploy on Google Container Engine.

Directly loading the needed data through 3-4 environmental variables works in all circumstances.

**Comment by jonparrott** [comment]
@kevhill you can also mount the file using docker volumes. Kubernetes / Container engine can do this with secrets and config maps.

**Comment by lukesneeringer** [comment]
>  I don't see how you'd, say use that for local development and then deploy on Google Container Engine using kubernetes.

You can set the environment variable in Kubernetes.
