### ISSUE TITLE
Chaining ACL grants on Storage does not work.

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#3181]
So from what I can tell [this](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/ce6756fbe3633c74fd742567654565147628f4ba/storage/google/cloud/storage/acl.py#L56) doesn't work.

Example:
```python
acl.all().grant_read().revoke_write()
```

None of the grant methods return an object to chain to.
See:  https://github.com/GoogleCloudPlatform/google-cloud-python/blob/486163e5378897961bc3cf367062c8b10cf7ce3e/storage/google/cloud/storage/acl.py#L148-L170

Should I just take this out of the docs?

**Comment by lukesneeringer** [comment]
I would rather fix the code to match the docs.

**Comment by daspecster** [comment]
SGTM, I'll get a PR together.

**Comment by tseaver** [comment]
Those docs may be leftovers from some early development:  we've mostly avoided the `return self` chaining thing on purpose.

**Comment by lukesneeringer** [comment]
Based on feedback to #3183, please change the docs. :-)

**Comment by daspecster** [comment]
👍

**Comment by lukesneeringer** [comment]
Has this been done?
