### ISSUE TITLE
CONTRIBUTING.rst out of date since the switch to nox from tox.

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#3205]
Since we're using nox now, we should update the CONTRIBUTING.rst to show users how to run docs/lint/unit/system tests.

**Comment by tswast** [comment]
Looks like the files were reorganized too. The CONTRIBUTING.md still talks about the `system_tests` directory, which looks to have been split into the various subpackages.

**Comment by dhermes** [comment]
@lukesneeringer Are you still ["on the hook for this"][1]?

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3300#issuecomment-294181684
