### ISSUE TITLE
Error in NL API, 'Sentiment' object has no attribute 'score'

### ISSUE THREAD

**Issue by PrasenjitGiri** [GoogleCloudPlatform/google-cloud-python#3208]
Upon executing the following code on GCE & locally I'm getting 'score' not found error locally while it works on GCE.

```
def analyze_text(text):
    language_client = language.Client()
    document = language_client.document_from_text(text)
    annotations = document.annotate_text(include_sentiment=True)
    print(annotations.sentiment.score)
    print (annotations.sentiment.magnitude)
```

Only difference I can find is on GCE, the gcloud version is different than the local
**GCE gcloud**
gcloud --version
Google Cloud SDK 145.0.0
alpha 2017.02.21
app-engine-python 1.9.50
beta 2017.02.21
bq 2.0.24
bq-nix 2.0.24
core 2017.02.21
core-nix 2017.02.21
gcloud 
gcloud-deps 2017.02.21
gcloud-deps-linux-x86_64 2017.02.21
gsutil 4.22
gsutil-nix 4.22

**Local gcloud**
gcloud --version
Google Cloud SDK 148.0.1
bq 2.0.24
bq-nix 2.0.24
core 2017.03.24
core-nix 2016.11.07
gcloud 
gcloud-deps 2017.03.17
gcloud-deps-darwin-x86_64 2017.02.21
gsutil 4.23
gsutil-nix 4.19

Debugging locally, the response from NL API consist of polarity property and not score.

<img width="761" alt="image" src="https://cloud.githubusercontent.com/assets/1888535/24331449/62cbdbee-1252-11e7-9d29-8699df078fcf.png">

**Comment by PrasenjitGiri** [comment]
So, any idea about this?

**Comment by lukesneeringer** [comment]
That most likely means that the API is inconsistent. I can make it not `KeyError`; you will just get a `None`. I will do that now while I am thinking about it.
