### ISSUE TITLE
feature request: query without having to provide a jobid ?

### ISSUE THREAD

**Issue by c0b** [GoogleCloudPlatform/google-cloud-python#3209]
i'm reading the `google-cloud-python` docs and the bigquery rest api reference [2], the job insert api is the async query job, I wonder why the python api is designed to have to provide a jobid? since bigquery server side is archiving the job id for a long time can't re-use same id, that has imposed client side a burden to maintain every jobid to be unique, although that can be easily archived by a time and random based id generator, but the point is: if the bottom layer rest api reference [2] doesn't require jobid to be provided, in the case when jobid is omitted, bigquery server will allocate a unique jobid; why the Python api becomes requiring a jobid?

1. https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-usage.html#querying-data-asynchronous
2. https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs

**Comment by tseaver** [comment]
@c0b thanks for the report.  AFAICT, the [docs for the `jobReference` element of a job resource](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#jobReference) say that `jobId` is a required field.  The ["managing jobs" docs](https://cloud.google.com/bigquery/docs/managing_jobs_datasets_projects#generate-jobid) state that supplying a job ID is best practice:

>  If you call jobs.insert without specifying a job ID, BigQuery will create a job ID for you, but you will not be able to check the status of that job until the call returns. Moreover, it may be difficult to tell whether the job was successfully inserted or not. If you use your own job ID, you can check the status of the job at any time and you can retry on the same job ID to ensure that the job starts exactly one time.

**Comment by lukesneeringer** [comment]
The client library can totally solve for this by generating a job ID (e.g. `str(uuid.uuid4())`), saving it to the object, and using it.

**Comment by c0b** [comment]
> the docs for the jobReference element of a job resource say that jobId is a required field.

the jobId is only required if `jobReference` is present; but the `jobReference` itself is optional;

<img src="https://cloud.githubusercontent.com/assets/14798161/24433372/f98547ba-13dc-11e7-9b47-2502e2254adb.png" width="480">

**Comment by tswast** [comment]
Tracking this internally as part of GA redesign.
