### ISSUE TITLE
Support for GCS Cloud Pub/Sub Notifications

### ISSUE THREAD

**Issue by BrandonY** [GoogleCloudPlatform/google-cloud-python#3216]
GCS has a new feature (currently in private alpha) wherein buckets can be configured to send object change notifications to Cloud Pub/Sub topics, rather than as push notifications to HTTPS endpoints.

For gcloud-python, I imagine such a feature might look like this:

    from gcloud import pubsub
    from gcloud import storage

    storage_client = storage.Client()
    pubsub_client = pubsub.Client()
    bucket = storage_client.get_bucket(BUCKET_ID)
    topic = pubsub_client.topic(TOPIC_ID)
    notification_config = bucket.send_notifications_to(topic)

This feature was previously filed as https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2768, but that one was closed because the feature was still in private alpha. However, today the feature is now in public beta.

**Comment by lukesneeringer** [comment]
Thanks for reporting. This seems like a useful feature request that we will definitely consider.

**Comment by lukesneeringer** [comment]
Hi @BrandonY,
This issue did not come up in the Pub/Sub redesigns here, and I am not sure what the status on it is. I am willing to consider it after the new library goes beta, but it seems out of scope for now.
