### ISSUE TITLE
Storage document upload policy snippet

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#3222]
Storage [snippet for generate_upload_policy](https://googlecloudplatform.github.io/google-cloud-python/stable/storage-buckets.html#google.cloud.storage.bucket.Bucket.generate_upload_policy) seems to be broken. I looked at [the docs](https://cloud.google.com/storage/docs/xml-api/post-object#policydocument) but I don't see where the breakdown is.

Here's the output when trying to upload with the generated HTML form.

```xml
<Error>
<Code>InvalidArgument</Code>
<Message>Invalid argument.</Message>
<Details>Cannot create buckets using a POST.</Details>
</Error>
```

```python
bucket = client.bucket('my-bucket24356uytrew')
conditions = [
    ['starts-with', '$key', ''],
    {'acl': 'public-read'}]

policy = bucket.generate_upload_policy(conditions)

# Generate an upload form using the form fields.
policy_fields = ''.join(
    '<input type="hidden" name="{key}" value="{value}">'.format(
        key=key, value=value)
    for key, value in policy.items()
)

upload_form = (
    '<form action="http://{bucket_name}.storage.googleapis.com"'
    '   method="post" enctype="multipart/form-data">'
    '<input type="text" name="key" value="">'
    '<input type="hidden" name="bucket" value="{bucket_name}">'
    '<input type="hidden" name="acl" value="public-read">'
    '<input name="file" type="file">'
    '<input type="submit" value="Upload">'
    '{policy_fields}'
    '<form>').format(bucket_name=bucket.name, policy_fields=policy_fields)

print(upload_form)
```

**Comment by jonparrott** [comment]
@daspecster this works fine, however, two things:

1. The closing form tag is `<form>` instead of `</form>`. My bad.
2. You'll get the 'Cannot create buckets using a POST.' if you fail to put a value into the `key` input field. Granted, the sample outputs a form that doesn't have a label on that field so it's easy to miss.

**Comment by dhermes** [comment]
Re-opening issue until the snippet is restored in source

**Comment by daspecster** [comment]
@jonparrott, ah thanks. Sorry I missed that.
