### ISSUE TITLE
Core Exception Rename for 308?

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3228]
We [currently][1] name our 308 exception `ResumeIncomplete` because that is how Google Cloud Storage resumable uploads [use the status code][3].

But the [RFC][2] officially defines it as `308 Permanent Redirect`. Seems like people [are mad][4] about this?

Also, in Python through 3.4, 308 isn't even around

```python
$ python2.7
Python 2.7.13 (default, Jan  5 2017, 18:58:25) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import httplib
>>> import six
>>> six.moves.http_client is httplib
True
>>> httplib.responses[200]
'OK'
>>> httplib.responses[308]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 308
$ python3.4
Python 3.4.5 (default, Jan  5 2017, 19:30:46) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import http.client
>>> import six
>>> six.moves.http_client is http.client
True
>>> http.client.responses[200]
'OK'
>>> http.client.responses[308]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 308
```

but it made it's way into Python 3.5:

```python
$ python3.5
Python 3.5.2 (default, Jan  5 2017, 19:32:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import http.client
>>> import six
>>> six.moves.http_client is http.client
True
>>> http.client.responses[200]
'OK'
>>> http.client.responses[308]
'Permanent Redirect'
```

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/29d18bc837b39fd74445b57c5eb55965fded78b3/core/google/cloud/exceptions.py#L97-L99
[2]: https://tools.ietf.org/html/rfc7538#section-3
[3]: https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload#example_uploading_the_file
[4]: http://insanecoding.blogspot.co.il/2014/02/http-308-incompetence-expected.html

**Comment by jonparrott** [comment]
From what I can tell from internal code, Google services consistently use 308 as `Resume Incomplete`. Our client library should keep that, even if the RFC disagrees. We should properly document this, though.

**Comment by lukesneeringer** [comment]
> Which is used by Google, king of the Internet

LOLOLOLOLOL

**Comment by jonparrott** [comment]
Yeah that blog was a fun read.

**Comment by lukesneeringer** [comment]
My philosophy tends to be that you try as hard as you can to follow the spec, but I agree with @jonparrott in this case. I agree with documentation pointing out the differing behavior though, although sadly for reasons of professionalism we should avoid linking to the epic rant. ;-)
