### ISSUE TITLE
Add unit tests for superset of expected responses.

### ISSUE THREAD

**Issue by lukesneeringer** [GoogleCloudPlatform/google-cloud-python#3240]
There was [a bug][] in the Node.js Vision client which was effectively that the client raised an exception if it ever got a key that it did not expect. This is relatively easy to do for any number of reasons:

```python
# `raw_response` is a dict that came back from the API.
key_map = {
    'alphaObject': 'alpha_object',
    'betaObject': 'beta_object',
}
new_response = {}
for k, v in raw_response.iteritems():
    new_response[key_map[k]] = v
```

This is an anti-pattern, because it strongly assumes that you will never get a new key that is not already in your key map. If the API adds a `gammaObject` key and this (Python) code were to run, suddenly what used to work now raises `KeyError`.

The solution: Add unit tests in each spot where we transform an API response into a custom object to ensure that unexpected key-value pairs are either passed through or dropped.

  [a bug]: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2034

**Comment by lukesneeringer** [comment]
@dhermes It came up in Vision, but nothing about the potential issue is Vision-specific.

**Comment by dhermes** [comment]
Ah gotcha. This seems like a pretty beefy issue then.

Personally, it seems like a nasty trick for a versioned API to start returning things it didn't used to, but that's already happened to us (with BigQuery, maybe others), so it seems like we can't pretend it won't.

**Comment by lukesneeringer** [comment]
The contract is basically that additive changes are in bounds and should not break the client.

Additionally, remember that it is common practice at Google to whitelist people for particular additional fields, and while we may not support those additional fields, we need the client not to barf completely.

I do not think we have any instances of the error that Node had, but we should add some tests to applicable objects to be sure. (And, yes, this is a solid day's work. This is a reason to move away from writing such objects when possible.)

**Comment by lukesneeringer** [comment]
We are on GAPIC now. No longer concerned.
