### ISSUE TITLE
Auto-cancelled builds will skip cleanup in system tests

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3247]
This results in orphaned resources, e.g. a [recent build][1] was pre-empted and a bucket created in the BQ tests is still around an hour later

![screenshot from 2017-03-30 11-40-14](https://cloud.githubusercontent.com/assets/520669/24520541/b2ec1718-153d-11e7-8050-ce6ab1dc0796.png)

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1448

**Comment by lukesneeringer** [comment]
I can turn off auto-cancelation. Should I?

**Comment by dhermes** [comment]
@lukesneeringer I don't think so? We could do what `node` does and have an "eager cleanup"?

**Comment by lukesneeringer** [comment]
How does that work?

**Comment by dhermes** [comment]
I'm not sure, I've just heard talk. e.g. at the beginning `list_buckets()` and delete any that don't belong.

**Comment by tseaver** [comment]
FWIW, it sounds like a likely source of the "running out of spanner instances" flakiness.

**Comment by dhermes** [comment]
@tseaver It's possible, though not likely since most of our builds were DOA at `logging`

**Comment by lukesneeringer** [comment]
> FWIW, it sounds like a likely source of the "running out of spanner instances" flakiness.

Yeah, I was thinking that too.

**Comment by stephenplusplus** [comment]
Eager cleanup is right. In Node, each system test suite starts with a cleanup task, where we generally use a prefix to fetch and delete all resources that match. Each API might look a bit differently, but using GCE as an example:

- [How we create all resource names](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/7b3042afc2185aa14d461b76bc7b644b75eb1b6c/packages/compute/system-test/compute.js#L1398). `generateName('network')` will get back `gcloud-tests-network-{{uuid}}`.
- [How we remove all created resources from the `before` and `after` hooks](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/7b3042afc2185aa14d461b76bc7b644b75eb1b6c/packages/compute/system-test/compute.js#L1408). It will get, then delete each resource type using the filter: `'name eq gcloud-tests.*'`.

Hope this is useful!

**Comment by chemelnucfin** [comment]
Cleanups will now be tracked in [Cleanup](https://github.com/GoogleCloudPlatform/google-cloud-python/projects/9)
