### ISSUE TITLE
App Engine Standard and Flexible Environments

### ISSUE THREAD

**Issue by jmgirven** [GoogleCloudPlatform/google-cloud-python#3265]
I am trying to create a Python application that uses both App Engine Standard and Flexible environments for different components. I need a worker to utilise tools not available in the standard environment. The majority of my code can run on the standard environment. The two should ideally: share a common database, share common file storage, and have a way of communicating (TaskQueue / PubSub). I was thinking I could use Google Cloud [Datastore][1], [Storage][2] and [PubSub][3], respectively. I could put everything on the flexible environment, but this seems overly complicated and I lose the benefits of the standard environment. Is mixing environments like this relatively simple? Or does it introduce problems?

  [1]: https://cloud.google.com/datastore/docs/reference/libraries#client-libraries-install-python
  [2]: https://cloud.google.com/storage/docs/reference/libraries#client-libraries-install-python
  [3]: https://cloud.google.com/pubsub/docs/reference/libraries#client-libraries-install-python

**Comment by lukesneeringer** [comment]
Hi @jmgirven,
It is hard to be able to give specific advice on a broad question like that -- whether GAE standard or flex is right for you will depend a lot on your circumstances.

I will mention that the gRPC transport does not work on GAE standard, so you will be limited to the HTTP transport on those services if you house your code there.

**Comment by jmgirven** [comment]
Thanks @lukesneeringer. You are right about it being too broad. A marginally better set of questions would be:

- Is google.cloud.datastore designed to function normally on GAE standard (with the gRPC exception you mention above)?
- Is there any extra set up required over the documented process? I.e. `gcloud init` presumably doesn't get transferred to the GAE instance.
- Assuming google.cloud.datastore is set up correctly on both a flex and standard environment, can the two share the same underlying data? Presumably so.

Similar questions would also apply for PubSub and storage, but would presumably have the same answers.

To answer these questions myself, I will try and implement the system I have in mind, and return with specific programming questions if I encounter problems.
