### ISSUE TITLE
[Vision] No Exceptions raised for non-existent gcs uri's    

### ISSUE THREAD

**Issue by sprakash3** [GoogleCloudPlatform/google-cloud-python#3268]
Hi,

Google Vision python package doesn't raise exceptions for non-existent gcs uri resources, instead returns an annotation object with empty list for texts. This makes it harder to tell if the resource doesn't exist or if the vision api failed to detect any text. 

1. OS type and version: macOS Sierra 10.12.3
2. Python version: Python 2.7.10
3. google-cloud-python version: Version: 0.23.0
4. Code example -  relevant code snippets
```python
from google.cloud import storage, vision
from google.cloud.storage import Blob
from google.cloud.vision.image import Feature
from google.cloud.vision.image import FeatureTypes

features = [Feature(FeatureTypes.TEXT_DETECTION)]
vision_client = vision.Client()
image = vision_client.image(source_uri="<gcs uri>")
annotations = image.detect(features)
if annotations:
    annotation = annotations[0]
        if annotation.texts:
            text = annotation.texts[0].description
else:
    text = None

print(text)
```

**Comment by dhermes** [comment]
Thanks for reporting! ISTM this is a bug in the API itself, because for us to detect it in the client we'd need to make two round trips (which is a nontrivial penalty).

We **could** add a check locally, maybe with an optional `verify=False` flag, but I think we should try to discuss with the Vision API team first. @lukesneeringer WDYT?

**Comment by lukesneeringer** [comment]
I would rather not, because then six other languages have to do that, too. This is an API bug.

**Comment by sprakash3** [comment]
Thanks. Is there a place to report this ?

**Comment by lukesneeringer** [comment]
I have been pointing folks [here](https://cloud.google.com/support/).
