### ISSUE TITLE
No way to override default deadlines in Spanner API

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-python#3269]
Currently none of the Spanner APIs expose a way to override default deadline. This is especially important for read and query apis since people can use those APIs to stream millions of rows and the default deadline (which I think is [30 seconds](https://github.com/googleapis/googleapis/blob/master/google/spanner/v1/spanner_gapic.yaml#L109)) is just too small for those cases.
One way of doing this would be to allow users to pass in gax CallOptions.

**Comment by lukesneeringer** [comment]
We talked about this in the context of #3204, and decided that while this is something we want to do, there is some design work involved.

**Comment by vkedia** [comment]
So is there some ETA for this? Can we do something in the short term till we figure out a common solution for all the libraries. This seems important to me especially for long running streaming apis which would be the most widely used apis in Spanner.

**Comment by lukesneeringer** [comment]
There is not an ETA right now. It is something we do want to do.
I do not want to put a stopgap solution in Spanner only.

**Comment by lukesneeringer** [comment]
@vkedia We have this ability on a per-method basis now. Which methods need longer timeouts?

**Comment by vkedia** [comment]
So do you mean users of spanner library can specify the deadline on a per method basis?

**Comment by chemelnucfin** [comment]
@lukesneeringer So can this be closed since you can specify timeout_secs on run_in_transaction in session and apparently database (which passes the keyword into session)?

**Comment by lukesneeringer** [comment]
If we need smarter defaults, we should change those. Users can also override them in the meantime.

**Comment by vkedia** [comment]
@lukesneeringer @chemelnucfin Can you give me some examples of how I would override the timeout for things like read/query/batch?

**Comment by chemelnucfin** [comment]
Hello, feature requests will now be tracked in the project [Feature Requests](https://github.com/GoogleCloudPlatform/google-cloud-python/projects/5#card-6867160).  I will close this issue now, please feel free to continue to address any issues/concerns here.
