### ISSUE TITLE
Unable to import `google-cloud-storage`

### ISSUE THREAD

**Issue by isdefic** [GoogleCloudPlatform/google-cloud-python#3274]
Hi,

We're looking to create a Lambda function that leverages the Google Cloud Storage SDK (`google-cloud-storage`) to pull down files.

We're following this guide to create .zip packages to deploy our code to Lambda: http://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html

When we run the Lambda function, it errors saying that it's unable to import the package. However, we can successfully run code that imports a number of other popular Python dependencies such as `requests`.

We've looked around here to see if we can find the solution. We tried the suggestions we found from people with similar issues with no luck.

I've attached a screenshot of the code we are attempting to run and of the error we are getting.

Any help would be greatly appreciated.

Thanks,
Isaura
![screen shot 2017-04-05 at 15 56 43](https://cloud.githubusercontent.com/assets/8737575/24712308/6eaac6f8-1a1a-11e7-8841-d5022077910c.png)
![screen shot 2017-04-05 at 15 57 00](https://cloud.githubusercontent.com/assets/8737575/24712317/73135cf0-1a1a-11e7-9e73-4cf03388d8d0.png)

**Comment by dhermes** [comment]
It's almost certainly related to namespace packages.

**Comment by lukesneeringer** [comment]
Yeah, that is my guess also. We try to be good Python citizens and use the `google.cloud` namespace, but namespace packages are imperfect, particularly in older versions of Python.

Assuming the obvious things (e.g. you have `google-cloud-storage` in your `requirements.txt` file) are sanity checked, your best bet is probably to ask the Lambda folks. Sorry. :-/

**Comment by jonparrott** [comment]
@isdefic I'd recommend you take a look at [darth-vendor](https://github.com/jonparrott/Darth-Vendor), which we originally created for App Engine but is also highly applicable to this situation.

What you'd need to do is:

1. Instead of `pip install -t your/project/dir` you'd do `pip install -t your/project/dir/lib`. Separating the third-party packages into a 'lib' sub-folder.
2. Place `darth.py` in `your/project/dir`.
3. In your `main.py` (or whatever) before you do _anything_ else, do `import darth; darth.vendor('lib')`.

**Comment by isdefic** [comment]
Thank you guys for the reply.
@lukesneeringer yes, I do have `google-cloud-storage` in my `requirements.txt`. We did raise a case with the AWS too as I wasn't sure who to 'blame' for this :). Waiting for a reply.

@jonparrott I was hopping for something a little bit different. I'll let you know if I can apply this solution for my case and if works.

Thank you all ;)

**Comment by lukesneeringer** [comment]
Today I learned that there is a Python package named Darth Vendor. That is amazing.

**Comment by isdefic** [comment]
At the end, I had create a separated virtualenv for the installation and add the init file to the package before zipping it all.

Thank you all.

**Comment by Maskey71098** [comment]
@isdefic hello, im facing a similar problem. Can you please be more specific to what tou did to solve this issue?

**Comment by jonaser06** [comment]
I also have the same problem, it would be good to explain the solution

**Comment by adecchi-2inno** [comment]
Same problem here
