### ISSUE TITLE
Missing "Using the API" section for Cloud Storage

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#3275]
I'd like a page that tells you how to get started with the API.

![image](https://cloud.githubusercontent.com/assets/247555/24724049/95f89b8e-19fe-11e7-9a14-e7f9f3e71800.png)

I know I can go to https://cloud.google.com/storage/docs/reference/libraries#client-libraries-usage-python but most people who arrive on the page won't know that.

**Comment by dhermes** [comment]
Thanks for filing @tswast. We've already got an open issue for this (I'll try to hunt it down right now, but have spotty internet)

**Comment by dhermes** [comment]
#1037. Shall we close as duplicate?

**Comment by tswast** [comment]
Ah, thanks. Wasn't labeled with storage, so I didn't find it.

**Comment by dhermes** [comment]
Totes. My bad.
