### ISSUE TITLE
pageSize vs. maxResults

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3277]
What is the point of the two arguments? For old-style APIs (i.e. discovery based), JSON paging is done via `maxResults`.

For new-style APIs (i.e. those with gRPC support), paging is done via `pageSize` (both in JSON and gRPC).

Currently our iterator takes `maxResults` to mean a maximum **over many pages** while `pageSize` (at least in terms of the two english words put together) means **the size of one page**.
- Is it worth offering distinct `page_size` and `max_results` keyword params?
- @lukesneeringer, is there an equivalent concept of max results vs. page size in GAX?
- When no `pageSize` is used in a new-style API what happens? Some of our GAX helper docstrings say "If not passed, defaults to a value set by the API."

/cc @bjwatson @tseaver @jonparrott 

Relevant to https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3270#discussion_r110059932

**NOTE**: This is copied mostly verbatim from an old email thread.

**Comment by lukesneeringer** [comment]
Yes, both of these arguments make sense and have distinct meaning.

GAX has a page token argument in [CallOptions](http://gax-python.readthedocs.io/en/latest/generated/google.gax.html#google.gax.CallOptions) but nothing for page size. I assume @jonparrott could easily add `page_size` when he ports that.

Also, closing this, as the question is answered.

**Comment by jonparrott** [comment]
Please leave this open, assign to me, and add it to the API.core project.

**Comment by lukesneeringer** [comment]
Fair! :-)

**Comment by jonparrott** [comment]
So far I'm leaning on this as our "decision" for this:

Core iterators will use `max_results` to mean the maximum about of items that can be returned by the iterator over several pages. Core iterators will use `page_size` to determine how many results to fetch per page.

If an API uses parameters that differ from this, our iterators will need to adapt them.

**Comment by dhermes** [comment]
@jonparrott SGTM. The original reason I opened it was because `max_results` was being used to mean `page_size` in some places. The fact that they both exist is the solution I had hoped for.
