### ISSUE TITLE
Client library incorrectly returns error when FLAC is used with long-running-recognize

### ISSUE THREAD

**Issue by pbogle** [GoogleCloudPlatform/google-cloud-python#3285]
The client library incorrectly returns an error when anything other than LINEAR16 is used for a long-running recognize request:

[https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/speech/google/cloud/speech/sample.py#L173][1]

The v1 server support all encodings so this breaks functionality.

In general, the client library should almost never do it's own validation; it should always delegate to the server to be sure that that behavior and error messages are consistent across APIs.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/46e417e838001f4d1eb13f5e3fc2a54d390dd5db/speech/google/cloud/speech/sample.py#L173

**Comment by dhermes** [comment]
> In general, the client library should almost never do it's own validation; it should always delegate to the server to be sure that that behavior and error messages are consistent across APIs.

I am +(a million) on this.
