### ISSUE TITLE
Client library incorrectly throws exception if alternative does not have confidence

### ISSUE THREAD

**Issue by pbogle** [GoogleCloudPlatform/google-cloud-python#3287]
I believe the code below will throw an exception if the API representation doesn't include a confidence value.  This is incorrect because alternative don't always have a confidence; it should supply a default of None.

        return cls(alternative['transcript'], alternative.get('confidence'))

https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/speech/google/cloud/speech/alternative.py#L41

**Comment by lukesneeringer** [comment]
This is fine; `dict.get('key')` returns `None` if the key is unset:

```
$ python
Python 3.6.0 (default, Jan  5 2017, 10:44:51) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> d = {'a': 'b'}
>>> d.get('a')
'b'
>>> d.get('c')
>>> 
```

**Comment by pbogle** [comment]
That's not true for Python 2.7.  I assume we're not requiring Python 3?
  
$ python
Python 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> d = {'a': 'b'}
>>> d['a']
'b'
>>> d['b']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'b'

**Comment by dhermes** [comment]
@pbogle The `__getitem__` syntax isn't used for `confidence`, for that value, we allow a fallback to `None`:

```python
alternative.get('confidence')
```

**Comment by pbogle** [comment]
Sorry I reveal my lack of knowledge of Python here; you are correct and there is no issue.
