### ISSUE TITLE
encoding.py missing OGG_OPUS and SPEEX_WITH_HEADER_BYTE encodings

### ISSUE THREAD

**Issue by pbogle** [GoogleCloudPlatform/google-cloud-python#3288]
The new encodings  OGG_OPUS and SPEEX_WITH_HEADER_BYTE are missing.

[https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/speech/google/cloud/speech/encoding.py][1]

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/46e417e838001f4d1eb13f5e3fc2a54d390dd5db/speech/google/cloud/speech/encoding.py

**Comment by dhermes** [comment]
@lukesneeringer Are these in some `pb2` module?

**Comment by lukesneeringer** [comment]
https://github.com/googleapis/api-client-staging/blob/master/generated/python/gapic-google-cloud-speech-v1/google/cloud/gapic/speech/v1/enums.py#L66-L67

**Comment by dhermes** [comment]
So shouldn't we just use those values?

**Comment by pbogle** [comment]
Just a note that we will be adding additional new encodings in Q2.  So +1
on Danny's suggestion: it's highly desirable to expose the autogenerated
values directly to reduce the manual changes needed as we add new features.

**Comment by dhermes** [comment]
@lukesneeringer Can we re-open this / file a new issue to discuss a plan of attack to dump the hand-crafted enums?

**Comment by lukesneeringer** [comment]
The latter, please.

**Comment by dhermes** [comment]
Filed #3296
