### ISSUE TITLE
zero mirror visibility

### ISSUE THREAD

**Issue by lifeofguenter** [GoogleCloudPlatform/google-cloud-python#3294]
on some of my nodes I am getting the following error:

```
curl -I https://packages.cloud.google.com/apt/dists/cloud-sdk-jessie/main/binary-amd64/Packages
HTTP/1.1 403 Forbidden
Content-Type: text/html; charset=UTF-8
Content-Length: 1632
Date: Thu, 13 Apr 2017 09:43:45 GMT
Alt-Svc: quic=":443"; ma=2592000; v="37,36,35"
```

unfortunately there is zero visibility/transparency on who is maintaining the mirror, nor any (findable) option on rsync'ing it on-premise to avoid such IP based blocks.

**Comment by dhermes** [comment]
@lifeofguenter This repository is not for the `gcloud` SDK, it's for Python packages for interacting with Google cloud APIs.

See: https://cloud.google.com/support/docs/issue-trackers
