### ISSUE TITLE
Stop hard-coding protobuf enums in speech Encoding

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3296]
See #3288

/cc @pbogle

**Comment by lukesneeringer** [comment]
Really we should make this change everywhere that we surface a GAPIC enum.

**Comment by pbogle** [comment]
Can you help me understand why we don't simply expose the underlying GAPIC enum??

(If the challenge is to come up with the equivalent string representation for error messages, there are definitely ways to do that programatically.)

**Comment by dhermes** [comment]
@pbogle Looking at [the class][1] there is absolutely no reason.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/24e603c377e8276dd79e202668b14bb6f5cff94f/speech/google/cloud/speech/encoding.py#L18-L44

**Comment by lukesneeringer** [comment]
We now expose the GAPIC enum. Problem solved. :tada:
