### ISSUE TITLE
BigQuery dataset.table("TABLE_NAME").exists() fails frequently

### ISSUE THREAD

**Issue by rishsriv** [GoogleCloudPlatform/google-cloud-python#3298]
The following snippet has been failing frequently in the past 12 hours:

```
client = bigquery.Client(project='PROJECT_ID')
dataset = client.dataset('DATASET_ID')
dataset.table(table_name).exists()
```

System specs are:
OS: Ubuntu 16.10
Python 2.7.12, google-cloud version: 0.23.0
The request is made from a GCP instance in the Asia region, while the BigQuery dataset is in the North America region.

I get either a 500 error or a 503 error. The error stacktraces are:

```
File "/path/to/file.py", line 56, in FUNCTION_NAME
    if not dataset.table(table_name).exists():
File "/usr/local/lib/python2.7/dist-packages/google/cloud/bigquery/table.py", line 515, in exists
    query_params={'fields': 'id'})
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/connection.py", line 350, in api_request
    error_info=method + ' ' + url)
InternalServerError: 500 An internal error occurred and the request could not be completed. (GET https://www.googleapis.com/bigquery/v2/projects/PROJECT_ID/datasets/DATASET_ID/tables/TABLE_NAME?fields=id)
```

OR

```
File "/path/to/file.py", line 56, in FUNCTION_NAME
    if not dataset.table(table_name).exists():
File "/usr/local/lib/python2.7/dist-packages/google/cloud/bigquery/table.py", line 515, in exists
    query_params={'fields': 'id'})
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/connection.py", line 350, in api_request
    error_info=method + ' ' + url)
ServiceUnavailable: 503 Error encountered during execution. Retrying may solve the problem. (GET https://www.googleapis.com/bigquery/v2/projects/PROJECT_ID/datasets/DATASET_ID/tables/TABLE_NAME?fields=id)
```

[This](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2491) might be a related issue.

**Comment by dhermes** [comment]
@tswast Have you seen 500s and 503s like this before?

**Comment by tswast** [comment]
I'll check with the BigQuery backend folks.

**Comment by tswast** [comment]
@rishriv Are you still having trouble with this API giving frequent errors?

If so, the BigQuery team needs a project, dataset, and table name to debug. You can send an email to me with the details if you'd like them to check it out.

Closing this issue here since I don't believe this is due to the client libraries.

**Comment by rishsriv** [comment]
@tswast Seems like its fixed now. I couldn't find an issue on the [Google Cloud Status Dashboard](https://status.cloud.google.com/), though. Sending you an email with your more details.

**Comment by dhermes** [comment]
Thanks guys!
