### ISSUE TITLE
503 (flaky) in language system test

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3304]
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1628

The error happened during [teardown][1] (a `DELETE` request) of the [`test_analyze_entities_from_blob`][2] case though I doubt the error is linked to which case spawned it.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/138f59fc1795e1e433822bdd62d927762fd8f2e2/language/tests/system.py#L64-L66
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/138f59fc1795e1e433822bdd62d927762fd8f2e2/language/tests/system.py#L107

**Comment by lukesneeringer** [comment]
Hello! 
We have done a less-than-great job of dealing with issues in this repository. Sorry about that. :-(

In this case, we have released an entirely different version of `google-cloud-language`, which is very likely to have solved this issue, so I am going and closing language-related issues _en masse_ to try and regain sanity and ability to tackle things.

Please upgrade to the newest version of `google-cloud-language` and use `LanguageServiceClient`. Note that this will require a code change. If your issue persists, feel free to reopen. :-)
