### ISSUE TITLE
Exponential backoff failed on monitoring test_write_point system test

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3306]
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1630

It [looks like][1] the intent is 10 retries but this one failed after 4 retries.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/3b8c9f60097b3160feb881673c143e2a72b5b8ff/monitoring/tests/system.py#L205

**Comment by chemelnucfin** [comment]
Cleanups will now be tracked in [Cleanup](https://github.com/GoogleCloudPlatform/google-cloud-python/projects/9)
