### ISSUE TITLE
log_text freezes in my Django project

### ISSUE THREAD

**Issue by hangll** [GoogleCloudPlatform/google-cloud-python#3310]
I have this piece of code in my Django project and 'start' is printed but I never see 'end'.

```
from google.cloud import logging
logging_client = logging.Client()
log_name = 'frontend'
logger = logging_client.logger(log_name)
print 'start'
print logger.project
logger.log_text('test')
print 'end'
````

Also, if I set
```
logging_client._use_grpc = False
```
~It won't freeze, but I don't see my log in stackdriver.~
It will work!

BTW, I also see this error in test cases but not in production env:
```
RetryError: GaxError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded)>)
```

[UPDATE] It works fine locally, but when I deploy everything to kubenetes with Apache, I keep getting the same problem (log_text freezes).
[UPDATE] With `logging_client._use_grpc = False`, it just works for me on kubenetes. It seems the grpc call will just freeze.

**Comment by hangll** [comment]
Hi,

Has anyone looked into this problem? We really want to have this implemented but can't figure out the issue.

**Comment by dhermes** [comment]
@waprin Can you take a look?

**Comment by hangll** [comment]
Friendly ping?

**Comment by waprin** [comment]
@hangll was largely away for a few weeks but I'm back today, will try to repro this in a bit.

**Comment by lukesneeringer** [comment]
It looks like #3088 might have been fixed (it is not clear to me whether it was fixed or closed as a duplicate).

@hangll If you are still having this issue, feel free to reopen this.
