### ISSUE TITLE
StackDriver Error reporting payload key is wrong

### ISSUE THREAD

**Issue by bmorgan21** [GoogleCloudPlatform/google-cloud-python#3315]
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/0.24.0/error_reporting/google/cloud/error_reporting/client.py#L227

I believe this like should set the payload context key to httpRequest and NOT httpContext.  This would make it match the spec.

https://cloud.google.com/error-reporting/docs/formatting-error-messages

Right now the report_exception call is throwing an error when using grpc and not populating the data with the http api usage.

google.protobuf.json_format.ParseError: Message type "google.devtools.clouderrorreporting.v1beta1.ErrorContext" has no field named "httpContext".

**Comment by bmorgan21** [comment]
here is a code snippet that at least gets the data to show up.

```    class MyClient(error_reporting.Client):

        def _build_error_report(self, *args, **kwargs):
            payload = super(MyClient, self)._build_error_report(*args, **kwargs)

            if 'context' in payload:
                data = payload['context'].pop('httpContext', None)
                if data:
                    payload['context']['httpRequest'] = data

            return payload

```

**Comment by dhermes** [comment]
Thanks for reporting @bmorgan21, this was fixed in #3299. It seems we should get a release out soon?

**Comment by bmorgan21** [comment]
thanks.

is there a dev build I can use?  vs having to patch the broken code?

**Comment by lukesneeringer** [comment]
@dhermes Go ahead and cut a release. Thanks!

**Comment by dhermes** [comment]
@bmorgan21 Kicked off a build

https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1652

that will push the new release to

https://pypi.python.org/pypi/google-cloud-error-reporting/0.24.1

**Comment by bmorgan21** [comment]
@dhermes thank you for the quick turnaround.
