### ISSUE TITLE
timeout_ms docs are misleading

### ISSUE THREAD

**Issue by roscoejp** [GoogleCloudPlatform/google-cloud-python#3317]
Docs reference timeout_ms as being the 'time to wait for the query to complete':
[https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/query.py#L386][1]

This is contradictory to the actual use of timeout_ms as the API docs describe it as the request timeout:
https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query#timeoutMs

TimeoutMS is distinctly NOT the time 'to wait for query to complete'. The docs should be more explicit since query vs request timeout are vastly different things.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/5878b78025eb039a95e5f42a61572c448aadc97c/bigquery/google/cloud/bigquery/query.py#L386

**Comment by lukesneeringer** [comment]
Hi @roscoejp,
Thanks for reporting. I agree that this is in error.

**Comment by roscoejp** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3320 to update the docs.

**Comment by lukesneeringer** [comment]
#3320 was merged; closing this.
