### ISSUE TITLE
Can't install Speech API Python client on Raspberry Pi 3

### ISSUE THREAD

**Issue by aazimh** [GoogleCloudPlatform/google-cloud-python#3321]
1. OS type and version - **Raspbian Pixel** 
2. Python version and virtual environment information `python --version` - **2.7.9**

Hi guys,

Trying to install the Speech API Python client on my Raspberry Pi 3 but running into installation issues. When I try 

`pip install --upgrade google-cloud-speech`

it starts the install process, but hangs when it comes to building the **grpcio** dependency and doesn't move forward until I cancel. Exact line is:

`Running setup.py bdist_wheel for grpcio ...`

and that's where it gets stuck. I did some Googling and it looks like there's a problem with grpc on ARM processors, so is there any way to get around this and have the Python client installed on my Pi? Would appreciate any help! I understand the library is in Alpha so this issue may not even have a fix, but just wanted to see if there might be.

Thanks,
Aazim.

**Comment by tseaver** [comment]
While it is possible to disable the library's use of GRPC (via setting the `GOOGLE_CLOUD_DISABLE_GRPC` environment variable), we don't support installing without the `grpcio` library.  Please [open an issue against the gprc repository](https://github.com/grpc/grpc/issues) requesting raspbian wheels for the Python `grpcio` library.

**Comment by dhermes** [comment]
@aazimh I'm fairly certain you'll be able to get it installed from source via:

```bash
$ git clone https://github.com/GoogleCloudPlatform/google-cloud-python/
$ cd google-cloud-python/speech
$ virtualenv ${VENV}
$ source ${VENV}/bin/activate
(...VENV...) $ ${VENV}/bin/python setup.py install
```

But that command **may** stall `grpcio`. I suppose in that case you could always install a fake `grpc` package.

**Comment by aazimh** [comment]
@dhermes Would that not do the same thing as installing via pip? If not, I'm willing to give it a shot.

Have no idea how I would go about installing a fake package :) for now, I'm going to go the long way around and try and use REST calls via the requests module in Python.

**Comment by dhermes** [comment]
`setup.py` will use `setuptools` directly, which can have different behavior than `pip` (a not so fun quirk, packaging is no fun sometimes).

`pip install --no-deps` would (probably) also do the trick for you

**Comment by lukesneeringer** [comment]
> I'm fairly certain you'll be able to get it installed from source

On a RaspPi? Sure, but it will be 2019 before it completes. ;-)

**Comment by lukesneeringer** [comment]
For tracking purposes: @aazimh did open an issue on GRPC: https://github.com/grpc/grpc/issues/10793

**Comment by aazimh** [comment]
And it worked! I was just being impatient :) thanks for pointing me in the right direction guys!

**Comment by hack-r** [comment]
@aazimh So what exactly did you did to get it to work? I'm having the same issue

**Comment by skumarlabs** [comment]
> I am facing the same issue while installing firebase-admin.
> I am trying to install firebase-admin package in my raspberry pi zero w.
> While I used command sudo pip install firebase-admin, it is stuck on below line,
> `running setup.py bdist_wheel for grpcio ...`
> 
> @aazimh as you have mentioned it was completed after waiting a long... how much time would it take to complete... any idea?
> 
> Appreciate your help.

For anyone else facing the issue, for me, it took ~58 minutes on raspberry pi 3B+ on desktop boot..

**Comment by surak** [comment]
Raspbian has a python-grpcio package, which is older than 1.29.x, so that won't work:

```Collecting grpcio<2.0dev,>=1.29.0; extra == "grpc" (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-vision)```

Turns out that compiling from source always fail on a raspberry pi zero as of december 2020
