### ISSUE TITLE
Bigtable system test has a "race condition" if run simultaneously on same project

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3333]
Two builds ([1682][1] and [1683][2]) were happening simultaneously and this caused a [Bigtable system test check][3] to fail in the second build (1683)

```python 
>       self.assertEqual(len(instances), len(EXISTING_INSTANCES) + 1)
E       AssertionError: 2 != 3
```

This is because `EXISTING_INSTANCES` is set at module setup time while the test case is run later.

I'm not sure what a realistic fix should be?

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1682
[2]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1683
[3]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/ce043bba2883588a89b5c4c9ad34c2af64287d5e/bigtable/tests/system.py#L145

**Comment by lukesneeringer** [comment]
I think the correct answer to this is "do nothing". If it happens more frequently, we can address it.

**Comment by dhermes** [comment]
I agree @lukesneeringer, though I've seen ~5 such failures in the last two days
