### ISSUE TITLE
Method list_tables does not return table schemas

### ISSUE THREAD

**Issue by leonardoam** [GoogleCloudPlatform/google-cloud-python#3341]
I am trying to use the bigquery python API to do a migration program (to create and update table schemas), but when I try to retrieve the current schemas from a dataset, I can't get the table schema because the array that is supposed to return the list of SchemaFields is always empty.

See the folow snippet:

```python
# get a dataset from project
dataset = [db for db in client.list_datasets() if db.name == 'datasetname'][0]

# get a table from dataset
[table.__dict__ for table in dataset.list_tables()][0]
```

It returns the following data:

```python
{
    'name': 'tablename',
    '_dataset': <google.cloud.bigquery.dataset.Dataset object at 0x7fd50c154048>,
    '_properties': {
        'kind': 'bigquery#table',
        'id': 'projectname:datasetname.tablename',
        'tableReference': {
            'projectId': 'projectname',
            'datasetId': 'datasetname',
            'tableId': 'tablename',
        },
        'type': 'TABLE',
    },
    '_schema': (),
}
```

I am using Python 3.6.1 in Antergos, google-cloud-python version 0.24.0.

I would expect the field `_schema` to show the current fields in the dataset, once the table 'tablename' already exists.

**Comment by dhermes** [comment]
@leonardoam Unfortunately the schema is not part of the response for `tables.list`, see the [docs][1].

I am pre-emptively closing, but we can re-open if there is anything that can be done.

@tswast Can you confirm my observation about the API spec?

[1]: https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/list

**Comment by tswast** [comment]
Yeah, unfortunately to get all the data it looks like you have to do a subsequent get. I'll pass this on to the eng team.

**Comment by tswast** [comment]
Or, actually @leonardoam would you mind filing this as feedback for the BigQuery backend API using the Google Issue Tracker? https://issuetracker.google.com/issues/new?component=187149&template=0
