### ISSUE TITLE
Allow Creation of HDD Instance in Bigtable APi

### ISSUE THREAD

**Issue by NarekA** [GoogleCloudPlatform/google-cloud-python#3344]
Currently the Bigtable API does not have a parameter for node_type and defaults to SSD.

**Comment by dhermes** [comment]
Define in [`common.StorageType`][1].

@NarekA IIRC when this package was originally implemented there was no support for HDD, but maybe that has changed.

[1]: https://github.com/googleapis/googleapis/blob/3ed5397c0214913a8f37994164652bc70dfa6619/google/bigtable/admin/v2/common.proto#L29-L38

**Comment by NarekA** [comment]
See `cluster-storage-type` in [gcloud](https://cloud.google.com/sdk/gcloud/reference/beta/bigtable/instances/create)

**Comment by lukesneeringer** [comment]
HDD is present in master; `common_pb2.py`, line 44 (my apologies to anyone who actually goes and tries to read that file).
