### ISSUE TITLE
Add Parameter for Instance Type in Bigtable API

### ISSUE THREAD

**Issue by NarekA** [GoogleCloudPlatform/google-cloud-python#3345]
Currently the Bigtable API only supports production instances, I would like to be able to create development instances in using the API.

**Comment by dhermes** [comment]
@NarekA I'm not sure what feature you're referring to, there is no sign of development vs. production in the [proto][1].

[1]: https://github.com/googleapis/googleapis/blob/3ed5397c0214913a8f37994164652bc70dfa6619/google/bigtable/admin/v2/bigtable_instance_admin.proto#L87-L107

**Comment by NarekA** [comment]
See the `instance-type` parameter in [gcloud](https://cloud.google.com/sdk/gcloud/reference/beta/bigtable/instances/create)

Here it is in the GUI too:
![screen shot 2017-04-28 at 4 39 20 pm](https://cloud.githubusercontent.com/assets/737367/25550889/08f4134e-2c32-11e7-9742-4111ca234f6f.png)

**Comment by dhermes** [comment]
@garye Any comments on this feature?

**Comment by garye** [comment]
We should allow this, but we need to release the new protos first. Assign it to me and I'll make sure the protos get committed here.

**Comment by garye** [comment]
@NarekA - There are certainly valid reasons to create development instances programmatically, but I also wanted to make sure you were aware of the [Bigtable Emulator](https://cloud.google.com/bigtable/docs/emulator) in case what you had was an automated integration/system test use case. In general we'd recommend using the emulator *if possible* for automated testing.

**Comment by dhermes** [comment]
@garye I can't assign you (I think it's because you aren't in the right org / group).

Also, we **can** commit the protos here and regenerate directly from them, but wouldn't you rather update the ["official" source of truth][1]?

[1]: https://github.com/googleapis/googleapis/tree/master/google/bigtable

**Comment by garye** [comment]
yup the protos will go there first, do we have a separate copy in google-cloud-python?

**Comment by dhermes** [comment]
@garye Yes in the [`_generated`][1] package. At some point this will go away (i.e. once a GAPIC autogenerated library exists on PyPI).

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/892e997e9aeee17ffed2c985326ff09a4e1219ce/bigtable/google/cloud/bigtable/_generated

**Comment by chemelnucfin** [comment]
Hello, feature requests will now be tracked in the project [Feature Requests](https://github.com/GoogleCloudPlatform/google-cloud-python/projects/5#card-6867160).  I will close this issue now, please feel free to continue to address any issues/concerns here.
