### ISSUE TITLE
limit has no effect on image features

### ISSUE THREAD

**Issue by pdknsk** [GoogleCloudPlatform/google-cloud-python#3347]
```Python
>>> client = vision.Client()
>>> image = client.image(source_uri = uri)
>>> properties = image.detect_properties(limit = 1)
>>> len(properties.colors)
10
>>> hints = image.detect_crop_hints(aspect_ratios = [1, 2, 3], limit = 2)
>>> len(hints)
3
```

**Comment by pdknsk** [comment]
This is, if at all, a bug in the API. I used *google-api-python-client* directly, and manually crafted a request in the *API Explorer*. In both cases 10 colors are returned, regardless of what `maxResults` is set to.

**Comment by dhermes** [comment]
Sorry @pdknsk, thanks for digging on your own.

**Comment by pdknsk** [comment]
Where would I file an API bug? I'm not sure it is, but it could be.

**Comment by dhermes** [comment]
@lukesneeringer @jonparrott Do you know of an API owner here?
