### ISSUE TITLE
Issue when inserting Stackdriver sink identity in Bigquery dataset

### ISSUE THREAD

**Issue by WillFuks** [GoogleCloudPlatform/google-cloud-python#3351]
Hello,

I was going through the [documentation](https://googlecloudplatform.github.io/google-cloud-python/stable/logging-usage.html) for setting up a Stackdriver sink using the python API and had some issues so I decided to ask here if I did something wrong (I got the answer already in [SO](http://stackoverflow.com/questions/43688393/bigquery-not-accepting-stackdrivers-sink-writer-identity?noredirect=1#comment74430872_43688393) but I'm not sure what happened yet).

The code I used:

```python
from google.cloud.logging.client import Client as lClient
from google.cloud.bigquery.client import Client as bqClient
from google.cloud.bigquery.dataset import AccessGrant

import os
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'path_to_json.json'

lc = lClient()
bqc = bqClient()

ds = bqc.dataset('working_dataset')
acc = ds.access_grants
#this is the service account that is shown in our Exports tab in GCP.
acc.append(
    AccessGrant('WRITER', 'groupByEmail', 'cloud-logs@system.gserviceaccount.com'))
ds.access_grants = acc
ds.update()

```

I followed the docs but then I got the error when trying to update Bigquery's dataset:

```
NotFound: 404 Not found: Email cloud-logs@system.gserviceaccount.com (PUT 
https://www.googleapis.com/bigquery/v2/projects/[project-id]/datasets/[working-dataset])
```

As Xuejian helped me, this account is not a _group_ one but rather a _user_ one. I tried changing it but then got the error:

```
BadRequest: 400 Cannot remove all owners from a dataset.
```

So I decided to create a brand new access_grants for my dataset object and this time I put all accounts related to it, something like:

```python
acc = [
    AccessGrant('OWNER', 'userByEmail', 'owner who created dataset email'),
    AccessGrant('WRITER', 'userByEmail', 'cloud-logs@system.gserviceaccount.com'),
]
```

And this time it worked. So I was wondering, when we run `ds.access_grants` shouldn't it already bring all accesses related to this dataset? Also should the documentation be updated with **userByEmail** instead of **groupByEmail** when creating the access of the sink's writer?

My setup was Python 3.6. from latest jessie docker image

Thanks,

**Comment by dhermes** [comment]
@WillFuks Sorry for the confusion, you'll want to actually load the dataset from the server before appending to the grants list:

```python
ds = bqc.dataset('working_dataset')
ds.reload()  # THIS IS WHAT WAS MISSING
acc = ds.access_grants
acc.append(
    AccessGrant('WRITER', 'groupByEmail', 'cloud-logs@system.gserviceaccount.com'))
ds.access_grants = acc
ds.update()
```

I am pre-emptively closing this, but am happy to re-open if you think there is more to be done / be said.

We are open to suggestions on how to improve this siutation, e.g. suggestions on where/what to add to documentation.
