### ISSUE TITLE
Explicitly depend on setuptools

### ISSUE THREAD

**Issue by lukesneeringer** [GoogleCloudPlatform/google-cloud-python#3356]
Context: #3295

We should explicitly depend on a minimum version of setuptools to get around problems installing our packages if setuptools is too old.

**Comment by dhermes** [comment]
This is just like a CYA? Isn't this kind of the chicken or the egg, like `setup.py` doesn't work because of an old version of `setuptools`, so we are going to require a newer version in `setup.py`?

**Comment by ndenny** [comment]
I've hit this problem in the past few days - google-cloud-* modules can't be installed on clean Python environments installed using PyEnv, so had to use pip to upgrade setuptools first. Seems reasonable that you add a include the requirement so you can be installed seamlessly: it's not an obvious error, and quite hard to find this issue to find the answer.

**Comment by dhermes** [comment]
@ndenny I've had the same issue with "fresh-ish" `pyenv` environments, thanks for pointing this out.
