### ISSUE TITLE
Build failed due to protobuf shared object file access

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3360]
Probably due to the fact that [`protobuf==3.3.0`][1] was just released. ([Failed build][2], [another][3])

[1]: https://pypi.python.org/pypi/protobuf/3.3.0
[2]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1726
[3]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1727

**Comment by lukesneeringer** [comment]
I did not see this, but I hit the same issue on Artman.
I filed an issue with them, and they fixed it: https://github.com/google/protobuf/issues/3042

**Comment by dhermes** [comment]
Builds looks to have gone back to green: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1729
