### ISSUE TITLE
add row to BQ from a dictionary

### ISSUE THREAD

**Issue by patitonav** [GoogleCloudPlatform/google-cloud-python#3368]
I am having trouble inserting a single JSON row into a BQ table from the API. I can get it done with bq-command-line or using `table.upload_from_file()` method. But when i am trying to do it with `table.insert_data(json_dic) ` the method takes everything in the dictionary as a value instead of insert every value in the corresponding key of the table.
There is a way of insert a json object without passing it as a file, or declare the schema (witch is huge and can change)?

Thank you very much

**Comment by tseaver** [comment]
`Table.insert_data` takes as its `rows` argument a list of tuples.  To insert a single row, you need to map your from-JSON dict onto a tuple using the table's underlying schema.  E.g., something like:

```python
table = client.table('my-table-name')
table.reload()  # fetch the table's schema
row = tuple([
    my_json_dict[field.name] for field in table.schema
])
table.insert_data([row])
```

**Comment by tseaver** [comment]
#3396 is tracking a feature request for a new convenience method to `Table` for this usecase.

**Comment by patitonav** [comment]
`row = tuple([
    my_json_dict[field.name] for field in table.schema
])`

This works fine for a simple dictionary but it think we need a strong solution for nested structures (a idctionary inside a dictionary)

thanks
