### ISSUE TITLE
Implement monitored resource for logging client

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#3377]
Log entries can have a monitored resource associated with them as of v2 of the logging API.

* entries.write documentation: https://cloud.google.com/logging/docs/reference/v2/rest/v2/entries/write
* MonitoredResource reference: https://cloud.google.com/logging/docs/reference/v2/rest/v2/MonitoredResource
* Existing tiny resource class in monitoring: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/monitoring/google/cloud/monitoring/resource.py#L159

Essentially, the `_BaseEntry` class should be extend to accept a `resource`. Helper methods such as `log_text` and `log_struct` should likely be extended to accept the resource as well.

This'll need to work with http and gax.

**Comment by jaitaiwan** [comment]
We discovered this today in production when moving from using the app log to request_log in google app engine. Is there any way to get the resource information per ProtobufEntry even without it being part of the _BaseEntry?

**Comment by jonparrott** [comment]
@jaitaiwan not without using the gapic layer directly.

**Comment by duggelz** [comment]
Do we have documentation anywhere of the mapping from MonitoredResource type to list of labels used?

**Comment by jonparrott** [comment]
> Do we have documentation anywhere of the mapping from MonitoredResource type to list of labels used? Or perhaps we don't need it, we just copy whatever we find.

It's here: https://cloud.google.com/logging/docs/api/v2/resource-list

We don't need to include in the client library, as it'll very quickly get out of date. We just need to accept a string and let the backend do the validation.
