### ISSUE TITLE
language: annotate_text method doc says it returns 4-tuple when it returns 5-tuple.

### ISSUE THREAD

**Issue by jerjou** [GoogleCloudPlatform/google-cloud-python#3389]
The [doc for natural-language](https://googlecloudplatform.github.io/google-cloud-python/stable/language-document.html#google.cloud.language.document.Document.annotate_text) says that the annotate_text method returns a 4-tuple of "sentences, tokens, sentiment and entities." However, when trying to use the library, it appears to actually return a 5-tuple:

```sh
>>> from google.cloud import language
>>> client = language.Client()
>>> document = client.document_from_text('everyone shall sit under their own vine and fig tree', language='en', encoding=language.Encoding.UTF32)
>>> result = document.annotate_text(include_syntax=True, include_entities=False, include_sentiment=False)
>>> len(result)
5
```
The tuple appears to contain:
1. Sentence
1. Tokens
1. Sentiment
1. empty? I assume entities
1. Language code

-------

1. OS type and version - **Ubuntu 14.04**
2. Python version and virtual environment information `python --version` - **2.7.6**
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze` - **google-cloud-language==0.24.1**

**Comment by tseaver** [comment]
The same text is present on both `stable` and `latest` versions of the docs.

**Comment by dhermes** [comment]
The [returned type][1] is a named tuple with

```
sentences, tokens, sentiment, entities, language
```

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/e3fecf121f5306ebea3c0e76e8a6f1de9b383ae0/language/google/cloud/language/document.py#L30-L33

**Comment by lukesneeringer** [comment]
Hello! 
We have done a less-than-great job of dealing with issues in this repository. Sorry about that. :-(

In this case, we have released an entirely different version of `google-cloud-language`, which is very likely to have solved this issue, so I am going and closing language-related issues _en masse_ to try and regain sanity and ability to tackle things.

Please upgrade to the newest version of `google-cloud-language` and use `LanguageServiceClient`. Note that this will require a code change. If your issue persists, feel free to reopen. :-)
