### ISSUE TITLE
500 Error during `list_entries()` in logging

### ISSUE THREAD

**Issue by tartavull** [GoogleCloudPlatform/google-cloud-python#3391]
```python
for entry in logger.list_entries():
  print(entry)
```
raises 

```python
InternalServerError: 500 Internal error encountered. (POST https://logging.googleapis.com/v2/entries:list)
```

**Comment by dhermes** [comment]
@tartavull Thanks for filing. That just means a request failed. You can add in exception handling to retry? (Though while paging through an [iterator][1] I realize that is a bit painful.)

@lukesneeringer Do we have a retry plan that we are tracking?

[1]: https://googlecloudplatform.github.io/google-cloud-python/stable/iterators.html

**Comment by chemelnucfin** [comment]
@lukesneeringer @dhermes Is the retry working now for this?

**Comment by dhermes** [comment]
There is support for retries on iterators in `api_core`, but I'm not sure if the logging client has used the new code generator.

**Comment by chemelnucfin** [comment]
I believe #4692 also has something to do with this.

**Comment by chemelnucfin** [comment]
@tartavull Hello, is this issue still a problem for you?

**Comment by tartavull** [comment]
I left the project which was using the library 5 months ago. I'm sorry I
can't answer.

**Comment by chemelnucfin** [comment]
@tartavull Thank you for your response.  Hopefully with all the code changes that has happened this problem has been resolved for that project.

Please consider trying our library again if it suits your needs.  
Thanks.

**Comment by chemelnucfin** [comment]
If it is still a problem for anyone else, please feel free to reopen this ticket or to create a new issue.
