### ISSUE TITLE
(google-cloud-vision) enum34 should not be installed on Python 3.4+

### ISSUE THREAD

**Issue by matrixl** [GoogleCloudPlatform/google-cloud-python#3398]
The enum34 breaks my code (python3.6), it is a known issue that enum34 doesn't work on Python 3.4+

Please refer to the discussion over here:
[https://bitbucket.org/stoneleaf/enum34/issues/5/enum34-incompatible-with-python-35#comment-19462547](https://bitbucket.org/stoneleaf/enum34/issues/5/enum34-incompatible-with-python-35#comment-19462547)

suggested fix in vision/setup.py

```python
REQUIREMENTS = [
-    'enum34',
    'google-cloud-core >= 0.24.0, < 0.25dev',
    'gapic-google-cloud-vision-v1 >= 0.90.3, < 0.91dev',
]

+if sys.version_info < (3, 4):
+    # Backport of Python 3.4 enums to earlier versions
+   REQUIREMENTS.append('enum34')

setup(
    name='google-cloud-vision',
    version='0.24.0',
    description='Python Client for Google Cloud Vision',
    long_description=README,
    namespace_packages=[
        'google',
        'google.cloud',
    ],
    packages=find_packages(exclude=('tests*',)),
    install_requires=REQUIREMENTS,
    **SETUP_BASE
)
```

**Comment by dhermes** [comment]
@matrixl Can you link to the known issue? Our unit tests run in Python 3.4, 3.5, 3.6 and our system tests run in 3.6 without **any issue** at all.

**Comment by matrixl** [comment]
Here is the issue reported in other project.
[https://github.com/donnemartin/saws/issues/55](https://github.com/donnemartin/saws/issues/55)

Also some discussion over here.
[https://bitbucket.org/stoneleaf/enum34/issues/5/enum34-incompatible-with-python-35#comment-19462547](https://bitbucket.org/stoneleaf/enum34/issues/5/enum34-incompatible-with-python-35#comment-19462547)

**Comment by dhermes** [comment]
Both of this indicate that the incompatibility was resolved 2 years ago. Am I somehow misreading?

**Comment by matrixl** [comment]
Yes, those issues have been fixed, but the way they fixed it is to only install enum34 with Python < 3.4.

[https://github.com/donnemartin/saws/commit/f109bc8f534905797ee44239cb766ea3de4ceb5d](https://github.com/donnemartin/saws/commit/f109bc8f534905797ee44239cb766ea3de4ceb5d)

Here is the latest post in 2017.
[https://bitbucket.org/stoneleaf/enum34/issues/19/enum34-isnt-compatible-with-python-36](https://bitbucket.org/stoneleaf/enum34/issues/19/enum34-isnt-compatible-with-python-36)

>Issue #19 **WONTFIX**
>enum34 isn't compatible with python 3.6

It was tagged as "WONTFIX", so the only way to fix it is to only require it with Python < 3.4

**Comment by dhermes** [comment]
Gotcha, thanks for digging @matrixl. So the issue isn't that our code is broken on it's own, just that it steps in front of `import enum` and stops you from using the newest features of `enum`?

@jonparrott WDYT of adding `enum34;python_version<"3.4"` in our requirements?

**Comment by jonparrott** [comment]
@dhermes I'm fine with that.

**Comment by tseaver** [comment]
@matrixl If what you report is true, I don't understand how our system and unit tests could be working with `enum34` unconditionally installed.

**Comment by dhermes** [comment]
@tseaver He didn't say it doesn't work with **our** code, he said: "enum34 breaks my code (python3.6)".

The point is that `enum34` steps in front of the native `import enum` and so users and up with the wrong package, and the backport one has fewer features.
