### ISSUE TITLE
Add support for Compute Engine

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-python#34]
Compute Engine: https://developers.google.com/compute/docs/reference/latest/
Python Compute Engine: https://developers.google.com/compute/docs/api/python-guide
Boto EC2: https://github.com/boto/boto/tree/develop/boto/ec2
Boto EC2 tutorial: https://boto.readthedocs.org/en/latest/ec2_tut.html
Boto EC2 API docs: https://boto.readthedocs.org/en/latest/ref/ec2.html

**Comment by jeffgodwyll** [comment]
This would be really cool, just like [google-cloud-node](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.45.0/compute).

Is this still planned?

**Comment by daspecster** [comment]
@jeffgodwyll I think so. Not sure when though?

@omaray I wouldn't mind taking an initial run at this if it's a priority.

**Comment by jeffgodwyll** [comment]
Yeah this will be awesome. It's not fun using the regular google api client libraries anymore after using this library 😜.

I wouldn't mind taking a stab at it either.

**Comment by lukesneeringer** [comment]
Hey all,
Closing this issue as it is going to be handled by auto-gen soon.

**Comment by thefirstofthe300** [comment]
Is this still on the roadmap for implementation? The google-api-python-client library is in maintenance mode with no new features being added.

**Comment by dinvlad** [comment]
Are there any updates on this?
