### ISSUE TITLE
Should system tests be parametrized to run under both HTTP and gRPC?

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/google-cloud-python#3403]
Some google-cloud-* libraries have both gRPC (gax) transports and HTTP transports. Logging, Datastore, Error Reporting, Pub/Sub at least. The clients generally try to use gRPC unless there's an ImportError (no gRPC support) ,or it's explicitly disabled by `google.cloud.environment_vars.DISABLE_GRPC` or a constructor argument to the client.

As far as I can tell most system tests just instantiate a client, so the tests only use one of these transports. On the CI systems gRPC is supported and so I think the HTTP paths are less tested.

@jonparrott  asked about this in #3386, it seemed a reasonable thing to give some thought to, so just wanted to create a discussion tracking issue.

I think this would be somewhat straightforward to do with nox, so main question is probably whether it's worth doing. Making the CI build slower is probably the biggest negative.

**Comment by dhermes** [comment]
Yes they should, but on a cron basis.

**Comment by dhermes** [comment]
@waprin #2658 already exists. Shall we close this one or that one?

**Comment by waprin** [comment]
Ah sorry, didn't search enough.
