### ISSUE TITLE
Write correlation-id in log entry metadata

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-python#3409]
By writing a correlation-id into the logging metadata, users can get request-correlated logs in pantheon.  See https://gist.github.com/JustinBeckwith/43dd04cfbc4551ddd8996a5b803da0b0 for details.

**Comment by lukesneeringer** [comment]
@JustinBeckwith The majority of people who will read this ticket (including the people who will most likely service it) are unable to follow internal links.

**Comment by JustinBeckwith** [comment]
Fixed :)

**Comment by duggelz** [comment]
Issue #3359 tracks writing the trace id to logs, so I think this is a duplicate.

**Comment by jonparrott** [comment]
Closing, duplicate of #3359, but thanks for the extra context, @JustinBeckwith! I'll update that issue with it.
