### ISSUE TITLE
Python3 HTTP Proxy support, moving to URLLib3

### ISSUE THREAD

**Issue by supercharger** [GoogleCloudPlatform/google-cloud-python#3411]
HttpLib2 has two code bases for python 2 and python 3. The Python 3 version of httplib2 is not implemented with socks/proxy support. Please refer to [here](has two code bases for python 2 and python 3. The Python 3 version of httplib2 is not implemented with socks/proxy support. Please refer to https://github.com/httplib2/httplib2/blob/43ff2654ad4f1c90cfb44b8c9bfa9090c0d502a1/python3/httplib2/init.py#L821).

I do see some discussion over moving to google-auth and urllib3, but the issues are closed.  Is there a temporary solution I can use ?

**Comment by jonparrott** [comment]
You can try using httplib2shim, but there's nothing we can do in this project to get httplib2 to support proxies.
