### ISSUE TITLE
BigQuery builds seem to be very broken

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3440]
e.g.

- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1960
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1963

There are many more in the last 48 hours (sorry I don't have time to gather them all right now).

We should diagnose and fix ASAP.

**Comment by dhermes** [comment]
This somehow fixed itself like magic (I made a small PR #3468 that doesn't seem big enough to have fixed these breakages)

**Comment by tseaver** [comment]
#3468 explicitly fixed the breakage in `test_dump_table_w_public_data`.  The one in `test_list_tables` might be an eventual-consistency issue?
