### ISSUE TITLE
No option to specify a custom nullMarker while using table.upload_from_file method

### ISSUE THREAD

**Issue by HassanJaveed84** [GoogleCloudPlatform/google-cloud-python#3449]
We have source data where Null values are represented by \N. 

However, we're unable to use table.upload_from_file method as there is no parameter to specify a custom null marker(configuration.load.nullMarker).

**Comment by tseaver** [comment]
@HassanJaveed84 Thanks for the report.  If you would care to prepare a pull request patching the `table.py` module, it would land more quickly.  Looking at the code, it would need a new `null_marker` argument to `Table.load_from_file`, which would then get passed down to the `_configure_job_metadata` helper.  The PR would also need to update one of the tests to demonstrate passing the value.

**Comment by HassanJaveed84** [comment]
@tseaver I'll go ahead and create a PR, thanks!

**Comment by HassanJaveed84** [comment]
@tseaver I tried following the instructions for local development on:
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/CONTRIBUTING.rst

However, I'm unable to run the tests using the given instructions. 
"To run all tests for google-cloud-python on a single Python version, run py.test from your development virtualenv "

Not sure about py.test ?

**Comment by dhermes** [comment]
@HassanJaveed84 sorry `CONTRIBUTING` is very out of date (/cc @lukesneeringer).

Instead, install `nox` via:

```
pip install --upgrade nox-automation
```

then run `nox` in the `bigquery` directory:

```
$ cd path/to/git/repo/
$ cd bigquery/
$ nox -l  # list of tests
$ nox -s "unit_tests(python_version='3.6')"  # One test
$ nox  # All tests, though you probably don't want system tests
```

**Comment by HassanJaveed84** [comment]
Thanks @dhermes. 
I'll let you know if I run into problems again.
