### ISSUE TITLE
Documentation on creating container optimized VM

### ISSUE THREAD

**Issue by munsanje** [GoogleCloudPlatform/google-cloud-python#3456]
I've searched high and low through the docs as well as open source code for documentation on how to create a Container Optimized VM using the python api, but to no avail. Could someone help me?

**Comment by dhermes** [comment]
@jonparrott Could you help redirect to the proper place?

**Comment by jonparrott** [comment]
Container-optimized VM has been replaced by Container Optimized OS. Based on the documentation [here](
https://cloud.google.com/container-optimized-os/docs/how-to/create-configure-instance), you can create this using the API by specifying the cos image and the configuration using [cloud-init](https://cloud.google.com/container-optimized-os/docs/how-to/create-configure-instance#using_cloud-init) with the `user-data` metadata fieldas documented [here](https://cloud.google.com/container-optimized-os/docs/how-to/create-configure-instance#using_cloud-init).

Additionally, you can follow the instructions for creating this through the UI and use the link at the bottom to see the equivalent REST api call.
