### ISSUE TITLE
incorrect beta note on Python Client library for Cloud Natural Language

### ISSUE THREAD

**Issue by merla18** [GoogleCloudPlatform/google-cloud-python#3462]
# Thank you for reporting an issue to google-cloud-python!

If you are reporting an issue or requesting a feature, please search the
existing open and closed issues to see if there is already work being done.

There is a warning about the NL API being beta on https://googlecloudplatform.github.io/google-cloud-python/stable/language-usage.html

"This is a Beta release of Google Cloud Natural Language API. This API is not intended for real-time usage in critical applications." 

This note needs to be removed as Google Cloud Natural Language API has been released GA since November 2016

**Comment by dhermes** [comment]
@merla18 Our client library is what's beta, not the actual backend API.

Does that make sense?

**Comment by merla18** [comment]
Could we update the verbiage of the Note to make it clearer. For instance:
"This is a Beta release of Google Cloud Natural Language Client Library. This Client library is not intended for real-time usage in critical applications."

**Comment by dhermes** [comment]
I'll defer to @lukesneeringer and @jonparrott and that language (though what you've written seems perfectly reasonable).

**Comment by lukesneeringer** [comment]
Florence, pretty sure I made this better awhile back based on a separate poke. Let me know if I did not. :-)
