### ISSUE TITLE
stackdriver logging logger delete is bugged

### ISSUE THREAD

**Issue by daiyueweng** [GoogleCloudPlatform/google-cloud-python#3465]
I tried to delete logs using the latest `python api` for `stackdriver logging`.

```python
from google.cloud import logging

from google.cloud.logging.resource import Resource


class StackdriverLogging:
    def __init__(self, resource=Resource(type='project', labels={'project_id': 'my_project'}), project_id='my_project'):
        
        self.resource = resource
        self.client = logging.Client(project=project_id)

    def delete_logger(self, logger_name):
        
        logger = self.client.logger(logger_name)

        logger.delete()

stackdriver_logger = StackdriverLogging()

stackdriver_logger.delete_logger('my_log_name')
```
I got the following errors,

```python
Traceback (most recent call last):
  File "/home/user_name/.local/lib/python3.5/site-packages/google/gax/retry.py", line 120, in inner
    return to_call(*args)
  File "/home/user_name/.local/lib/python3.5/site-packages/google/gax/retry.py", line 68, in inner
    return a_func(*updated_args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.NOT_FOUND, Requested entity was not found.)>
```

it is constantly showing up, when I tried to delete some logs.

**Comment by tseaver** [comment]
Hmm, are you sure there are actual log entries with that name?  Try the following:

```python
entries = list(stackdriver_logger.list_entries())
```

Is that list empty?

**Comment by daiyueweng** [comment]
No, the list is not empty. The code I have tried is,

```python
from google.cloud import logging

from google.cloud.logging.resource import Resource

import threading



class Severity(Enum):
    DEFAULT = 0
    DEBUG = 1
    INFO = 2
    NOTICE = 3
    WARNING = 4
    ERROR = 5
    CRITICAL = 6
    ALERT = 7
    EMERGENCY = 8


class StackdriverLogging:
    def __init__(self, resource=Resource(type='project', labels={'project_id': 'my_project'}), project_id='my_project'):

        self.resource = resource
        self.client = logging.Client(project=project_id)

    def delete_logger(self, logger_name):

        logger = self.client.logger(logger_name)

        logger.delete()

    def async_log(self, logger_name, sev, msg):

        t = threading.Thread(target=self.log, args=(logger_name, sev, msg,))
        t.start()

    def log(self, logger_name, sev, msg):
        logger = self.client.logger(logger_name)

        if isinstance(msg, str):
            logger.log_text(msg, severity=sev.name, resource=self.resource)
        elif isinstance(msg, dict):
            logger.log_struct(msg, severity=sev.name, resource=self.resource)


stackdriver_logger = StackdriverLogging()

stackdriver_logger.async_log("async_simple_text_log_test", Severity.WARNING, msg="Warning")
stackdriver_logger.async_log("async_simple_text_log_test", Severity.INFO, msg="Info")
stackdriver_logger.async_log("async_simple_text_log_test", Severity.WARNING, msg="Debug")

stackdriver_logger.delete_logger('async_simple_text_log_test')

```
It just could not let me delete the logger.

**Comment by liyanhui1228** [comment]
You might just need to wait a few seconds before deleting the logger, it takes some time for logs to be sent to stackdriver logging. This might be the reason why you got 'request entity not found'. I have tried your code and wait before deleting the logger, and it works. Hope this could help :)

**Comment by dhermes** [comment]
@daiyueweng This API (and most Google APIs) are "eventually-consistent", which might explain what @liyanhui1228 just said.

@liyanhui1228 Do you guys have a page in your docs explaining which operations are eventually-consistent and which are strongly-consistent?

**Comment by liyanhui1228** [comment]
@dhermes I haven't seen it in the logging docs. Maybe we need to consider add this part to our docs.

**Comment by dhermes** [comment]
@liyanhui1228 The [storage][1] doc on consistency may serve as a guide.

[1]: https://cloud.google.com/storage/docs/consistency

**Comment by liyanhui1228** [comment]
Thanks!

**Comment by daiyueweng** [comment]
The thing is that I created some sample logs yesterday and tried to delete them today and yesterday (only delete operations been executed), I am getting the same errors stated in the OP, and yet the logs are not deleted. 

I copied the `google-cloud-python/logging` on `github` into my project root, and then use the `logging`, do you think it might be the source that caused the issue? I am doing this because I want to use `Resource` and newly updated `log_xxxx` methods in `logger`. I am really asking is that is there some lower level `google cloud API` changes that caused this issue due to not using the latest `google cloud` code base?

**Comment by chemelnucfin** [comment]
We have deprecated the gax library and retrying with api_core.  If this is still a problem with the latest versions, could you please open a new issue and reference this?  

Thanks.
