### ISSUE TITLE
Wikipedia URL seems to have disappeared from Language API results

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3481]
See:

- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2105
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2108
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2110
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2111

```
    def _check_analyze_entities_result(self, entities):
        from google.cloud.language.entity import EntityType
    
        self.assertEqual(len(entities), 3)
        entity1, entity2, entity3 = entities
        # Verify entity 1.
        self.assertEqual(entity1.name, self.NAME1)
        self.assertEqual(entity1.entity_type, EntityType.PERSON)
        self.assertGreater(entity1.salience, 0.0)
        # Other mentions may occur, e.g. "painter".
        self.assertIn(entity1.name, [str(i) for i in entity1.mentions])
>       self.assertEqual(entity1.metadata['wikipedia_url'],
                         'http://en.wikipedia.org/wiki/Caravaggio')
E       KeyError: 'wikipedia_url'
```

**Comment by tseaver** [comment]
We need clarification from the back-end team that this feature will / won't be present for known images previously identified with it.

**Comment by dhermes** [comment]
Sure thing, though I am going to send a PR to fix this right now.

**Comment by dhermes** [comment]
OK I'm running locally and seeing no failures.

Both `test_analyze_entities` and `test_analyze_entities_from_blob` pass, and when printing the values the metadata is as expected:

```
entity1.metadata: {
    'mid': '/m/020bg',
    'wikipedia_url': 'http://en.wikipedia.org/wiki/Caravaggio',
}
entity2.metadata: {
    'mid': '/m/03rjj',
    'wikipedia_url': 'http://en.wikipedia.org/wiki/Italy',
}
entity3.metadata: {
    'mid': '/m/085_p7',
    'wikipedia_url': 'http://en.wikipedia.org/wiki/The_Calling_of_St_Matthew_(Caravaggio)',
}
```

**Comment by dhermes** [comment]
OK WAT?!? Since my [last comment ][2], a [build][1] has failed.

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2111
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3481#issuecomment-306906262

**Comment by adriansoghoian** [comment]
Yesterday, wikipedia and 'mid' has also suddenly disappeared from all entity results for me as well, affecting a production service. 

Any idea if this is a permanent or temporary disappearance?

**Comment by adriansoghoian** [comment]
My tests show that this appears to be magically resolved. Is that what you're seeing as well?

**Comment by dhermes** [comment]
@adriansoghoian Locally, yes. I just restarted the last failed build, so we'll see if it's true on CI: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2119

**Comment by lukesneeringer** [comment]
I have an open channel to the backend team. I will have an answer as soon as they arrive in the office (probably in about an hour).

**Comment by dhermes** [comment]
Thanks @lukesneeringer, note that the build spawned above (2119) has passed `language` without issue.

**Comment by lukesneeringer** [comment]
Yeah, and my build for speech did also. My guess is that they fixed it, but waiting on Mona to confirm before I close this issue.

**Comment by dhermes** [comment]
@lukesneeringer It seems to have re-disappeared: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2142

**Comment by danoscarmike** [comment]
Ping.  Did we get a response from the backend team?

**Comment by lukesneeringer** [comment]
We did, and it had disappeared, and should have now reappeared. Also, language is now GAPIC only. Closing.
