### ISSUE TITLE
API documentation for bigquery client load_table_from_storage incorrectly implies parameter is list.

### ISSUE THREAD

**Issue by greghecht** [GoogleCloudPlatform/google-cloud-python#3482]
OS: N/A
google-cloud version: 0.25.0

**Description:**
The google.cloud.bigquery client api includes this function:
 `load_table_from_storage(job_name, destination, *source_uris)`

The [documentation](https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-client.html#google.cloud.bigquery.client.Client.load_table_from_storage) for the 'source_uris' parameter says:
*source_uris (sequence of string) – URIs of data files to be loaded in format gs://<bucket_name>/<object_name_or_glob>.*

This seems to imply that one should pass in a list of URIs, each of which would be loaded. 

**Issue:**
The parameter is not a list nor a sequence. It's a string. The API takes only a single string URI. It does support glob file-paths, but this is different than supporting multiple arbitrary files. 

I believe the documentation should read:
*source_uri (string) -- URI of data file to be loaded, or glob pattern to load multiple files. In format gs://<bucket_name>/<object_name_or_glob>.*

**Other References:**
* This [StackOverflow](https://stackoverflow.com/questions/41272298/bigquery-load-table-from-storage-wont-recognize-uri) identifies the issue and is what I stumbled upon to solve my code problem.
* This [Code Sample](https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-client.html) is correct.

**Comment by tseaver** [comment]
`Client.load_table_from_storage` takes *one or more* source URIs (that is what `*soure_uris` means in python). E.g.:

```python
job = client.load_table_from_storage(
    'load-job-123', my_table_object,
    'gs://my-bucket-name/table_one',
    'gs://my-bucket-name/table_two')
```

**Comment by greghecht** [comment]
Doh! Sorry about that, thank you.
