### ISSUE TITLE
Allow returning values from transactional functions

### ISSUE THREAD

**Issue by waw-google** [GoogleCloudPlatform/google-cloud-python#3493]
Somebody asks in the Slack:

> Question about spanner python APIs, specifically transactions. 
> In a read-write transaction, is it possible to return the updated
> value without hitting the database again?
> 
> let's say I have the following transaction (pretty much the example from the docs)
> ```def f(transaction):
>     second_album_result = transaction.read(
>             table='Albums', columns=('MarketingBudget',),
>             keyset=second_album_keyset, limit=1)
>     second_album_row = list(second_album_result)[0]
>     second_album_budget = second_album_row[0]
>     second_album_budget += 10000000
>     transaction.update(table=mytable, columns=('MarketingBudget'),
>                         keyset=second_album_keyset, values=[(second_album_budget)]
>                     )  
>     return second_album_budget
> database.run_in_transaction(f)
> ```
> is the `return` at all possible?

I believe that this is currently not possible in the Python library, because when you pass a closure to `run_in_transaction`, the return value always gets ignored, and it just returns the commit timestamp.

However this _is_ possible in the Cloud Spanner Java library, and being be able to return whatever you want from the body of a transactional function in the case that a transaction successfully commits is extremely useful.

**Comment by bjwatson** [comment]
@vkedia @lukesneeringer This sounds useful, but IIUC it sounds like it could be done post-Beta since changing `database.run_in_transaction(f)` from returning _nothing_ to returning _something_ is not a breaking change.

**Comment by lukesneeringer** [comment]
It is _technically_ breaking because we do return the commit timestamp, but given that the commit timestamp is pretty useless, I am inclined to agree.

**Comment by bjwatson** [comment]
Thanks, @lukesneeringer. A meaningless breaking change seems fine for a Beta->GA fix, but we want to avoid _any_ breaking changes post-GA. So before GA we need to:
- fix this for real, 
- remove the useless commit timestamp return value, or 
- turn the return value into a dict to allow for future expansion (which seems like it might be over-engineering for this use case).

**Comment by bjwatson** [comment]
Nevermind, just saw that you fixed this for real. Thanks, @lukesneeringer!

**Comment by tseaver** [comment]
@lukesneeringer FWIW, the major use for the `committed` timestamp is in setting up subsequent snapshots using `request_timestamp`.
