### ISSUE TITLE
Blob.download_to_filename eating lots of RAM

### ISSUE THREAD

**Issue by tweeter0830** [GoogleCloudPlatform/google-cloud-python#3494]
I have a large ~4 GB binary file on GCS. When I use blob.download_to_filename, my RAM usage goes increases by 3 GB temporarily. Thus behavior goes away if I explicitly set a chunk size for the blob.

This seems like bad default behavior.

**Comment by dhermes** [comment]
@lukesneeringer @jonparrott WDYT about modifying the default? Also, IIUC if we use `requests` / `urllib3` by default we can still stream the entire payload (i.e. no chunking) into a file without having to put the whole thing in RAM first.

**Comment by jonparrott** [comment]
Seems reasonable to me. A default of a few megabytes hopefully won't hurt performance for small files. Can you do some benchmarks?

**Comment by dhermes** [comment]
Fixed in #3713

**Comment by eddie-scio** [comment]
Resurrecting this -- would you expect that the streaming solution in #3713 wouldn't work if the file were a `tmpfs` volume?  That's what I'm seeing
