### ISSUE TITLE
Add support for Cloud SQL

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-python#35]

**Comment by dhermes** [comment]
@jgeewax Do we want to wrap these into #558 or make milestones or something else? Ditto on #34

**Comment by gpopovic** [comment]
Any ETA for this?

**Comment by dhermes** [comment]
@jgeewax?

**Comment by ollikaven** [comment]
Any updates?

**Comment by dhermes** [comment]
@omaray or @jgeewax any thoughts?

**Comment by ojengwa** [comment]
any updates on this?

**Comment by ojengwa** [comment]
I can send in a PR over the weekend

**Comment by omaray** [comment]
Hello ojengwa.

Thank you for the message. We have other plans for Cloud SQL - and won't be doing any manual work. We don't have an ETA quite yet but we want to cover it in 2017.  In the meantime we do have the older client library at: 

https://developers.google.com/api-client-library/python/apis/sqladmin/v1beta4

I hope this helps.

**Comment by ZackTherrien** [comment]
Using an official client package for this instead of the api would be great! The API changes too rapidly for production use...
