### ISSUE TITLE
v0.26 Release Date?

### ISSUE THREAD

**Issue by william-silversmith** [GoogleCloudPlatform/google-cloud-python#3507]
Hi, I was wondering when v0.26 will be released on PyPI? There's a fix for setting the content encoding of an uploaded file in a single request (rather than uploading then patching) which decreases the error rate over hundreds of thousands to millions of calls. 

I tried installing via a github clone, but there were several layers of references to PyPI and I gave up after fighting with it for a few hours. It's not a rush, but it would make my team's data pipeline more efficient and less error prone.

Thanks for all the good work you guys do. 

edit: content type -> content encoding

**Comment by tseaver** [comment]
I'm presuming that your question refers to the `google-cloud-storage` release.  Just for clarity, the latest release is 1.1.1:

-  https://pypi.python.org/pypi/google-cloud-storage/1.1.1

Which PR added the fix you needed?

**Comment by william-silversmith** [comment]
Hi Tres,

Thanks for responding. I believe the functionality I'm looking for is in:

https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3362
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/754

The storage-1.1.1 was tagged May 2, while this functionality was introduced within the last 30 days if my understanding is correct.

Will

**Comment by dhermes** [comment]
Yes `google-cloud-storage==1.1.1` had the `google-resumable-media` changes for downloads, but not uploads.

**Comment by tseaver** [comment]
@william-silversmith I will be making a 1.2 release of storage this week.

**Comment by william-silversmith** [comment]
Thank you!!!!!
