### ISSUE TITLE
Consider replacing "manual" mock classes with 'unittest.mock' versions

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#3509]
From discussion on #3500.

There are a *bunch* of manually-defined stub classes in place throughout the codebase.  Suggested pros for replacement:

- `mock.Mock` confines to the test what the expectation is, using a format that contributors are going to be familiar with. Having to look up <local stub class> should not be necessary.
- Improved / standardized assertions (`assert_called_once_with` and friends).

Cons:

- Lots of churn, potentially introducing bugs.
- DRYing out frequently-used mock setups means that users still have to go look up the helper, rather than a class:  the class can be more "transparent" than the imperative setup (e.g., just add a class-scope attribute, rather than adjusting both the value passed to the mock and its `scope`).

**Comment by lukesneeringer** [comment]
I want to do this, but do not particularly want to keep an open issue for it at this time.
If we want to discuss _whether_ to do it, let's use e-mail.
