### ISSUE TITLE
Pub / Sub snapshot system test has started failing

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3510]
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2166
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2168
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2193

@tseaver Do you mind looking into this?

**Comment by tseaver** [comment]
@dhermes Given that the snapshot feature is still an invite-only alpha-level feature, two months after adding provisional support here, my first inclination is just to remove the feature altogether until it actually "exists," as a public feature of the API.

@lukesneeringer, @geigerj Can you please comment?

**Comment by geigerj** [comment]
I'm going defer to @pongad and @bjwatson here. (Note: @lukesneeringer is OOO.)

**Comment by dhermes** [comment]
@tseaver Has the `test_create_snapshot` system test passed before? (I think it has.)

**Comment by tseaver** [comment]
@dhermes Hell, I don't know.  AFAICT, the feature doesn't exist. :)

**Comment by bjwatson** [comment]
@pongad This does not sound Python-specific. How are we handling this in other languages?

**Comment by pongad** [comment]
I believe this is the eventual consistency problem: you might not see the snapshot immediately after creating it. Go gets around this by [retrying](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/4ba0c16dbf9d04d2dd3f98a6ea9b113cf17718ef/pubsub/integration_test.go#L159) for up to a minute before giving up. I don't think we saw this specific flake since then.

**Comment by dhermes** [comment]
Good info, thanks @pongad

**Comment by dhermes** [comment]
Just got another flake, @tseaver do you think you can tackle this?

**Comment by tseaver** [comment]
I'd say we should disable the system tests for the not-yet-released-two-months-later-and-flaky feature.  Frankly, it makes no sense at all to merge support for such a feature before it becomes GA.

**Comment by dhermes** [comment]
But we already have the retry helpers in place, it should be a few lines

**Comment by bjwatson** [comment]
@tseaver We need to keep this feature in the client library. The method documentation should address that it's Alpha quality and requires whitelisting. Is that accurate, @pongad?

Why aren't we getting the retry logic for free with GAPIC? Is this flakiness happening on the HTTP/JSON transport path?

**Comment by dhermes** [comment]
@bjwatson It's not about connection failures, it's about eventual consistency of the response

**Comment by bjwatson** [comment]
Oh, right. So it's a test-specific form of retry.

**Comment by pongad** [comment]
@bjwatson I don't feel strongly against keeping the feature in the library. If it goes in a branch and can be merged when the feature comes off whitelist, I think that's OK. I think the decision belongs to Python TL.

**Comment by tseaver** [comment]
My issue is that system tests on the trunk for a whitelist-only feature are inherently flaky:  anybody running the tests from a non-whitelisted account is going to see spurious failures, since we cannot detect that state in order to skip those tests.

From that perspective. moving the code off onto a branch until the feature is GA on the back-end would be ideal.

**Comment by bjwatson** [comment]
Ok, SGTM if that's what @lukesneeringer wants to do.

**Comment by dhermes** [comment]
Now that we have banished the logging failures, this is keeping our builds from being green. Though the discussion is potentially interesting, it'll be quite easy (for someone who has spare cycles) to just add the retry in the appropriate place to account for the eventual-consistency

[Recent failure][1]

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2675

**Comment by bjwatson** [comment]
Adding P1 label, since this is all that's standing between us and a green board. Feel to reprioritize as you see fit @lukesneeringer.

**Comment by bjwatson** [comment]
CC @timeburks
