### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by parthea** [GoogleCloudPlatform/google-cloud-python#3516]
Hello,

I found that the link at [https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/core/google/cloud/client.py#L33][1] is broken.

https://google-cloud-python.readthedocs.io/en/latest/google-cloud-auth.html

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/661816540f1387bcc6e08b0fd722f4abae585b37/core/google/cloud/client.py#L33

**Comment by parthea** [comment]
Potential replacement candidate: http://google-auth.readthedocs.io/en/latest/

**Comment by dhermes** [comment]
Thanks for filing @parthea!

This is the new location: https://google-cloud-python.readthedocs.io/en/latest/core/auth.html

Would you like to send a PR to get credit for your find? It will be super easy, no unit tests needed :grinning:

**Comment by parthea** [comment]
Done. Thanks @dhermes !
