### ISSUE TITLE
Autodetect schema option is missing from `google.cloud.bigquery.job.LoadTableFromStorageJob`

### ISSUE THREAD

**Issue by azymnis** [GoogleCloudPlatform/google-cloud-python#3521]
This seems to be related to issue #2926 but is not exactly related. There does not seem to be a way to set `configuration.load.autodetect` to `True` for `LoadTableFromStorageJob`. Are there any plans to add it? It would be a pretty straightforward pull request and I would be happy to do it if nobody else has done it.

**Comment by tseaver** [comment]
@azymnis I'm pretty sure that this is the same issue as #2926:  our library doesn't expose that API feature yet.  Please feel free to submit a PR adding that support!
