### ISSUE TITLE
Increment threadsafety on BigQuery DB-API interface when httplib2 is removed

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#3522]
From https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2921/files/5b29a9e42a40f7c74ced0b7a7e9db0add52a20a1#r123596828

Blocked by https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1998

**Comment by dhermes** [comment]
I would love to finish the work fro #1998!

It's right now blocked on BigQuery's usage of `google.cloud.streaming`, which I've actually **finished** ripping out in https://github.com/dhermes/google-cloud-python/tree/bigquery-remove-streaming. Alas, the unit tests will be a hard days slog!

**Comment by jonparrott** [comment]
@tswast this is now possible since #1998 has been resolved.

**Comment by dhermes** [comment]
Yay! (If only GitHub had a "blocked by" feature with nice notifications.)
