### ISSUE TITLE
Raise more specific DB-API exceptions for database errors

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#3523]
Follow-up to https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2921/files/5b29a9e42a40f7c74ced0b7a7e9db0add52a20a1#r116762868

For example, if a query fails due to a syntax error, a `ProgrammingError` could be raised.

**Comment by tswast** [comment]
The BigQuery docs have a page on specific errors that could occur.  https://cloud.google.com/bigquery/troubleshooting-errors

**Comment by chemelnucfin** [comment]
Hello, feature requests will now be tracked in the project [Feature Requests](https://github.com/GoogleCloudPlatform/google-cloud-python/projects/5#card-6867160).  I will close this issue now, please feel free to continue to address any issues/concerns here.
