### ISSUE TITLE
BigQuery DB-API: Support struct and repeated query parameter

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#3524]
Follow-up to https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2921

The query parameter conversion code in `google.cloud.bigquery.dbapi._helpers` will need to be somewhat recursive, I think.

**Comment by chemelnucfin** [comment]
Hello, feature requests will now be tracked in the project [Feature Requests](https://github.com/GoogleCloudPlatform/google-cloud-python/projects/5#card-6867160).  I will close this issue now, please feel free to continue to address any issues/concerns here.
