### ISSUE TITLE
speech/operation.py docstring incorrect, pointless exception raised

### ISSUE THREAD

**Issue by dw** [GoogleCloudPlatform/google-cloud-python#3525]
speech/operation.py::Operation._update_state() docstring specifies ValueError as being raised if any result exists, which is the opposite of reality. Additionally, raising ValueError is all but redundant, there is simply no reason to raise it, ignoring the use of a built-in exception type from deeply nested code.

Can we at least fix the docstring, or better yet, just remove the silly exception?

**Comment by dhermes** [comment]
@dw Thanks for filing. We're happy to help make the docs/docstrings better, but I'm having a hard time understanding this one. Maybe you are looking at an out-of-date version of this module?

The current version [says][1]

> :raises ValueError: If there are no ``results`` from the operation.

and the code [raises][2] when

```python
if len(pb_results) == 0:
    raise ValueError('Speech API returned no results.')
```

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/cbf073bc5469bac9398a5bf7aa5e93e6cb637211/speech/google/cloud/speech/operation.py#L53
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/cbf073bc5469bac9398a5bf7aa5e93e6cb637211/speech/google/cloud/speech/operation.py#L63-L65

**Comment by dw** [comment]
Hi @dhermes, looks like it must have been fixed on master. The docstring is not correct for the currently released google-cloud-speech==0.25.1 on PyPI.

Regarding the exception, I cannot fathom what it is for in the first place. The operation is succeeding in this case, but recognition failed to find any valid alternative. My code was already prepared for this scenario, but was tripped up by the needless exception.

Further regarding the exception, it is inconsistent with the regular synchronous version of recognize(), which returns an empty list as expected in this case.

**Comment by dhermes** [comment]
Thanks for the update. It's probably human error, i.e. `Operation` was probably written before the synchronous version?

If you'd like, you can send a PR just deleting those 2 lines which check for length 0 and raise? Then in the PR, we'll find out which unit test fails as a result and you can delete that too?

**Comment by lukesneeringer** [comment]
Hi @dw,
Since the time that you wrote this, we have released a pretty substantial update to the Speech library, with an entirely new surface. If you do not mind, please upgrade, and I believe this problem should be addressed.

Since this is now an issue against an older version, I am going to close it for now, but feel free to re-open if needed.
