### ISSUE TITLE
autodetect schema for avro file is not enabled

### ISSUE THREAD

**Issue by gyangscrf** [GoogleCloudPlatform/google-cloud-python#3539]
#3513 

configuration.load.autodetect
https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load.autodetect
is not included in google.cloud.bigquery.job

**Comment by tseaver** [comment]
Thanks for the report, which duplicates #2926.

I'm not sure what #3513 has to do with it:  that issue is about the `google-cloud-trace` library.  Did you mean perhaps #3521, which was another duplicate?

**Comment by gyangscrf** [comment]
Hi tseaver, 

I think I added #3513 by accident, yes, you are right, #3521 is a duplicate.
