### ISSUE TITLE
Morphology in language API

### ISSUE THREAD

**Issue by ericmarkmartin** [GoogleCloudPlatform/google-cloud-python#3553]
Hi.

I was playing around with the language API through the REST API, but when I switched over to the python library, I noticed that my responses were missing the morphology data that is available through REST. I couldn't find anything on it in any pending PR's or issues, so I was wondering what the status was vis-a-vis this issue.

Thanks

**Comment by tseaver** [comment]
Thanks for the report!  `google-cloud-language-0.25.0`, just released yesterday, added support for the full "parts of speech" data (added in PR #3457).

Please reopen if that support doesn't meet your needs.
