### ISSUE TITLE
No way to provide speech context through client interface

### ISSUE THREAD

**Issue by ChanganVR** [GoogleCloudPlatform/google-cloud-python#3558]
I've tried to provide google speech recognizer with speech context and found there is no context parameter to specify in client.sample API. And below are declarations of initialization and recognition function of Sample class. And obviously they are not consistent.

    def __init__(self, content=None, source_uri=None, stream=None,
                 encoding=None, sample_rate_hertz=None, client=None):

    def long_running_recognize(self, language_code, max_alternatives=None,
                               profanity_filter=None, speech_contexts=()):

**Comment by ChanganVR** [comment]
I just found the speech_context is provided through long_running_recognize() funtion in running time and is not provided when initializing the sample object. This question is so stupid... I'm closing it now.

**Comment by dhermes** [comment]
No worries, thanks for coming back to close it. Cheers
