### ISSUE TITLE
Linter False Positives When Importing google.cloud Modules

### ISSUE THREAD

**Issue by hiranya911** [GoogleCloudPlatform/google-cloud-python#3564]
An import statement like `from google.cloud import storage` will trigger a linter error on most platforms:

```
E: 21, 0: No name 'cloud' in module 'google' (no-name-in-module)
E: 21, 0: Unable to import 'google.cloud' (import-error)
```

Environment:
```
pylint 1.6.4, 
astroid 1.4.9
Python 2.7.6 (default, Mar 17 2017, 18:16:39) 
[GCC 4.8.4]
```

**Comment by hiranya911** [comment]
Possible fix: Add an empty `__init__.py` file to the google/cloud directory of the codebase.

**Comment by hiranya911** [comment]
It looks like the file exists in google-cloud-core, but some reason it doesn't get installed. Here are the installed contents:

```
$ ls /usr/local/lib/python2.7/dist-packages/google/cloud/
client.py   credentials.py   environment_vars.py   exceptions.py   _helpers.py   _http.py   iam.py   iterator.py   operation.py   storage    _testing.py
client.pyc  credentials.pyc  environment_vars.pyc  exceptions.pyc  _helpers.pyc  _http.pyc  iam.pyc  iterator.pyc  operation.pyc  streaming  _testing.pyc
```

**Comment by tseaver** [comment]
@hiranya911 This is an [issue with how pylint attempts to emulate Python's own import semantics in the face of namespace packages](https://github.com/PyCQA/pylint/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20namespace).  As a check, try:

```bash
$ /usr/local/bin/python2.7 -c "from google.cloud import storage"
```

which won't raise an exception.
