### ISSUE TITLE
Is MergeFrom used by accident (instead of CopyFrom) in bigtable.Table.create?

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3571]
See [source][1]. As an example of why `MergeFrom` instead of `CopyFrom` can be a bug:

```python
>>> from google.protobuf.timestamp_pb2 import Timestamp
>>> from google.cloud.bigtable._generated.bigtable_instance_admin_pb2 import (
...     CreateInstanceMetadata)
>>>
>>> metadata1 = CreateInstanceMetadata(request_time=Timestamp(nanos=100))
>>> metadata2 = CreateInstanceMetadata(request_time=Timestamp(nanos=100))
>>> t = Timestamp(seconds=1000)
>>> metadata1
request_time {
  nanos: 100
}

>>> metadata2
request_time {
  nanos: 100
}

>>> t
seconds: 1000

>>>
>>> metadata1.request_time.MergeFrom(t)
>>> metadata2.request_time.CopyFrom(t)
>>>
>>> metadata1
request_time {
  seconds: 1000
  nanos: 100
}

>>> metadata2
request_time {
  seconds: 1000
}
```

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/2d81f88454724f0a672b453c994413c3cf1110c7/bigtable/google/cloud/bigtable/table.py#L184

**Comment by dhermes** [comment]
@tseaver I assigned to you but a `git blame` reveals I am the last one to touch that line.

**Comment by tseaver** [comment]
In that particular case, the target starts as an empty `Table` protobuf.  Unless the `column_families` argument contains entries with duplicate `column_family_id` values, there won't be any effective difference between `CopyFrom` and `MergeFrom`.

**Comment by dhermes** [comment]
In other words, we aren't **relying** on `MergeFrom`, but (assuming users don't pass in duplicate names with different settings) the code "works fine"?

In that case, ISTM that we should

- Switch from `CopyFrom` (since it will be the same in the "safe case" and is it what we intend)
- Add a guard that a key can't be written over

WDYT?
