### ISSUE TITLE
Is there any way to generate transcription with time label

### ISSUE THREAD

**Issue by ChanganVR** [GoogleCloudPlatform/google-cloud-python#3572]
Is it possible for google speech API to transcribe a long audio and return the transcription with time label of each word or time label of each sentences?   
If not, any idea of how to do that? For example, I have thought about slicing long audio into fixed length short segment with overlapping and transcribe those short audios and then eliminate those overlapped texts. Another possible way to do that is to break long audio into meaningful sentences using some segmentation technique and then combine them. By the way, the audio I want to transcribe is 110 minutes long sports video commentary. Transcribing the whole audio and generating a long messy paragraph is not what I want. Thanks for those who're willing to give help.

**Comment by lukesneeringer** [comment]
Hi @ChanganVR,
Thanks for asking. This is actually a question about the API, not the client library, but I am going to see if I can get the right person to come provide an answer.

**Comment by danaharon** [comment]
Stay tuned - we will have support for this soon!

**Comment by lukesneeringer** [comment]
Thanks @danaharon.

@ChanganVR Since this is a repo for _the client libraries_, rather than the API, I am going to go ahead and close this issue. (It just is not the canonical place to track this thing.) Obviously, if you have any other issues, feel free to re-open or file a new issue.

**Comment by ChanganVR** [comment]
Thanks! Looking forward to this new feature @lukesneeringer @danaharon
