### ISSUE TITLE
No parameter available to specify a jobId to Table.upload_from_file()

### ISSUE THREAD

**Issue by mackenzieATA** [GoogleCloudPlatform/google-cloud-python#3574]
There is no way to send a `jobId` to the `upload_from_file` function.

My motivation is that I've had issues with uploading the same file twice, duplicating data in the target table.  A suggested solution was to specify my own `jobId` as a hash of the file contents. That way, duplicate uploads would be rejected as having the same `jobId`. Without modifying the library, there is no ability to do this.

**Comment by tseaver** [comment]
This should be pretty straightforward:

- Update `Table.upload_from_file` to take an optional `job_name` property and pass it through to `_configure_job_metadata`, along with the table's `project`.
- Update `_configure_job_metadata` to set the top-level `jobReference` IFF the `job_name` is not None.
- Add test coverage.
