### ISSUE TITLE
Docstrings from fetch_data method needs to be updated

### ISSUE THREAD

**Issue by WillFuks** [GoogleCloudPlatform/google-cloud-python#3576]
Hello,

Recently a [question](https://stackoverflow.com/questions/44895829/bigquery-async-query-job-the-fetch-results-method-returns-wrong-number-of-va) was posted in SO asking about the return params of the `fetch_data` method of `QueryResults' in BigQuery client.

As it seems, the return is no longer a tuple with 3 values but rather an object of the class `HTTPIterator`. Looks like the docstrings needs to be updated (if it could describe some quick example of how to use the iterator it'd be quite helpful :)!)

Thanks,

**Comment by lukesneeringer** [comment]
Hi @WillFuks,
Thank you for reporting this. We will get that updated.

**Comment by ryan-schroeder** [comment]
Thanks!  I was about to post a question regarding this as well, cheers! =)  Thanks for all your work on this
