### ISSUE TITLE
Expose error handling in speech client

### ISSUE THREAD

**Issue by jerjou** [GoogleCloudPlatform/google-cloud-python#3582]
Pasted from [python-docs-samples#963](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/963), filed by @datspike 

Hello. While using speechv1beta I was able to catch grpc error such as OUT_OF_RANGE and others simply with 
```python
for resp in recognize_stream:
    if resp.error.code != code_pb2.OK:
        print(resp.error.message)
```
With introducing of speechv1 actual grpc resposces are getting handled inside the `speech` module, and I can only get `alternatives` 
```python
alternatives = self.audio_sample.streaming_recognize(
    self.language, interim_results=True,
    profanity_filter=True)
```

How can I catch grpc errors in new API?

Thanks!

**Comment by dhermes** [comment]
1. @datspike Can you provide some example text so we can reproduce the error codes?
1. If there are two questions, let's make two issues

**Comment by jerjou** [comment]
Moved cancellation functionality to #3583

**Comment by dhermes** [comment]
Thanks @jerjou.

@datspike Can you help with a reproduction?

**Comment by lukesneeringer** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
