### ISSUE TITLE
Expose stream cancellation in speech streaming generator

### ISSUE THREAD

**Issue by jerjou** [GoogleCloudPlatform/google-cloud-python#3583]
Originally from [python-docs-samples#963](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/963), filed by @datspike 

How do you stop recognition correctly in the new client?

With the GRPC client, you can do

```python
recognize_stream = service.StreamingRecognize(
    requests, self.DEADLINE_SECS)
...
recognize_stream.cancel()
```

But this client lib only exposes the `streaming_recognize` call as a [generator of alternatives](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/f621d17ed5cb982d388011be3deff604f589121c/speech/google/cloud/speech/sample.py#L249). It would be useful to be able to cancel the stream from another thread, eg in case you need to close the stream before a response is returned.

**Comment by dhermes** [comment]
@lukesneeringer WDYT? In the linked code:

```python
responses = api.streaming_recognize(...)
```

the `responses` variable is a `_Rendezvous`, which is a mega-class provided by gRPC. Among other things, it can be cancelled.

**Comment by lukesneeringer** [comment]
The change to "mostly auto-gen" will just do this, right?

**Comment by dhermes** [comment]
I don't have a clear picture what the change will look like, so you tell me?

**Comment by lukesneeringer** [comment]
Yeah, fairly certain this should just be done now.
Happy to have this re-opened if not.

**Comment by Tadly** [comment]
Parden my intrusion but I'm kind of stuck on this.

As far as I can tell, `streaming_recognize` straight up blocks if the backend can't resolve a anything from the given stream (e.g. mic is muted, no one is speaking etc.).

As I'm trying to get this implemented in an `asyncio` environment this is kind of bad.
Even if I'd add threading (which I'd like to prevent) I'd still have the issue of it blocking -> no `_Rendezvous` instance.

Am I missing something obvious here?

**Comment by tseaver** [comment]
@Tadly Can you please open a new issue?  This one is a) long-closed, and b) only tangentially related to the problem you are experiencing.
