### ISSUE TITLE
Map BigQuery DB-API onto a SQLAlchemy dialect

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#3603]
This would allow BigQuery to be used from the BI tool, [Superset](https://github.com/apache/incubator-superset), among other places.

Relevant SQLAlchemy docs:

- [Dialect interface spec](http://docs.sqlalchemy.org/en/latest/core/internals.html#sqlalchemy.engine.interfaces.Dialect)
- [Existing dialects](http://docs.sqlalchemy.org/en/latest/dialects/index.html)

**Comment by lukesneeringer** [comment]
In an effort to get my project management to be a bit more sane, I am going to try something else in lieu of single issues that represent large projects.

I have referenced this on a [wiki page devoted to our significant feature backlog][1]. Discussion of this particular feature is still welcome here, although I am going to close this issue until such time as this is something we take on.

  [1]: https://github.com/GoogleCloudPlatform/google-cloud-python/wiki/Feature-Backlog
