### ISSUE TITLE
BigQuery does not support table-valued functions when using query_parameters

### ISSUE THREAD

**Issue by liyanhui1228** [GoogleCloudPlatform/google-cloud-python#3606]
I found that when I use query_parameters to run a query, it would not support table-valued functions. Code is like below:
```
query = """
    SELECT
        something
    FROM
        TABLE_DATE_RANGE(table,
			 DATE_ADD(TIMESTAMP(@timestamp), -1, "day"),
			 TIMESTAMP(@timestamp))
    WHERE
        something IN UNNEST(@client_libs)
"""
client = bigquery.Client()
query_job = client.run_async_query(str(uuid.uuid4()), query,
                               query_parameters=(
				   bigquery.ScalarQueryParameter('timestamp', 'STRING', "20170708"),
                                   bigquery.ArrayQueryParameter(
                                       'client_libs', 'STRING',
                                       client_libs)
                               ))

# If I do not explicitly set use_legacy_sql to False, an error would occur.
query_job.use_legacy_sql = False
query_job.begin()
wait_for_job(query_job)
```

Error message is:
```
RuntimeError: [{u'reason': u'invalidQuery', u'message': u'Table-valued functions are not supported at [6:9]', u'location': u'query'}]
```

And if I do not use query_parameters to substitute the parameters, it would support table-valued functions. Not sure what's the relationship between them.

**Comment by tseaver** [comment]
@tswast Can you comment here?

**Comment by tswast** [comment]
Definitely a backend issue. I'll ask a query parameters expert.

**Comment by tswast** [comment]
The [TABLE_DATE_RANGE](https://cloud.google.com/bigquery/docs/reference/legacy-sql#table-date-range) is a function from legacy SQL. The equivalent for standard SQL is to use [wildcard tables](https://cloud.google.com/bigquery/docs/wildcard-tables).

Unfortunately I don't think you can use query parameters to specify a wildcard table.

For this query, it looks like if you [convert these tables to partitioned tables](https://cloud.google.com/bigquery/docs/creating-partitioned-tables#converting_dated_tables_into_a_partitioned_table) using the `bq partition` command. Then you could use query parameters with to [query partitions](https://cloud.google.com/bigquery/docs/querying-partitioned-tables) using the `_PARTITIONTIME` pseudo-column.

**Comment by duggelz** [comment]
Is using query parameters the wrong thing to do?  Is there something else we should be doing instead?  If not, we need to question why we're making it easy to write insecure code that's vulnerable to SQL Injection, and hard to write secure code.

**Comment by liyanhui1228** [comment]
@tswast I used wildcard tables to get the tables for a list of dates as a work around like this:

```
query = """
            SELECT
                something
            FROM
                `table*`
            WHERE
                file.project IN UNNEST(@client_libs)
                AND
                _TABLE_SUFFIX IN UNNEST(@week_dates)
        """
    client = bigquery.Client()
    query_job = client.run_async_query(
        str(uuid.uuid4()),
        query,
        query_parameters=(
            bigquery.ArrayQueryParameter(
                'client_libs', 'STRING',
                client_libs),
            bigquery.ArrayQueryParameter(
                'week_dates', 'STRING',
                week_dates)
        ))
```
But it would be nicer and easier to have the query support table-valued functions when using query parameters. I will try the table partitions, thanks!

**Comment by tswast** [comment]
You're right. Using `_TABLE_SUFFIX` is your best option for securely allowing user input to select which tables to scan.
