### ISSUE TITLE
big query documentation link broken

### ISSUE THREAD

**Issue by davidraleigh** [GoogleCloudPlatform/google-cloud-python#3610]
Steps to reproduce:
Click on link in README.md for bigquery at this line:
https://github.com/GoogleCloudPlatform/google-cloud-python/blame/master/bigquery/README.rst#L12

That line points to this link which is broken:
https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-usage.html

**Comment by dhermes** [comment]
Fixed by #3611
