### ISSUE TITLE
Linter wishlist

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3624]
This is a wishlist for features of a fantasy linter that we wish existed:

-   Enforce one import per line (added by @dhermes)
-   Enforce importing modules / packages only (rather than members) (added by @dhermes)
-   Yell about spec-less mocks. (added by @jonparrott)
-   Trailing commas in all relevant data structures and fn. calls (added by @dhermes)
-   Uniform line continuation (added by @dhermes)
    -   In lists:
        ```python
        luke_says_no = ['a', 'b',
                        'c']
        luke_says_yes1 = [  # Which one?
            'a', 'b', 'c']
        luke_says_yes2 = [  # Which one?
            'a', 
            'b', 
            'c', 
        ]
        ```
-  [Controversial] Enforce importing module-under-test **at runtime** and all other modules at global scope (added by @dhermes)
-   [Probably Controversial] Require all string literals to be `u'...'` or `b'...'` (added by @dhermes)
-   [Probably Controversial] Disallow chained assignment, e.g. `a = b = True` (added by @dhermes)

**Comment by jonparrott** [comment]
* Yell about spec-less mocks.

**Comment by lukesneeringer** [comment]
I am going to move this to a Google Doc. This is not a particularly good venue. :-)

**Comment by lukesneeringer** [comment]
Document created and shared with contributors.
