### ISSUE TITLE
Datastore: Return values from delete()

### ISSUE THREAD

**Issue by umutberkbilgic** [GoogleCloudPlatform/google-cloud-python#3638]
I love Google Cloud Datastore for Python, after  7-8 hours of fiddling around with it, it finally works as I want it to. However one quick thing that could make life easier is if there was a return flag from functions (such as client.delete(key)) as front end could save a lot of time (both during execution and while developing). It seems to return, well, nothing at the mean time unlike client.get(key) which has a return that can be used as a simple flag. Serverless architecture is awesome but latency can be a real issue (although Google is pretty good, it is still noticable). Every line of code matters (efficieny-wise) and overall I feel more returns would allow frontend developers more tools while decreasing overall server pokes. Sorry if this should not go here by the way.

Cheers.

**Comment by dhermes** [comment]
@umutberkbilgic I'm not sure I understand the request. `Client.delete()` doesn't return because there is nothing to return. "Success" is just indicated by the fact that the `delete()` didn't throw an exception.

**Comment by umutberkbilgic** [comment]
Makes a ton of sense, looking more into the source I was able to figure it out thank you.
