### ISSUE TITLE
Document Storage.Blob setter for metadata

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-python#3645]
Hi! 

Based on other methods that have a getter and setter for example [bucket.cors](https://googlecloudplatform.github.io/google-cloud-python/stable/storage/buckets.html#google.cloud.storage.bucket.Bucket.cors).

I have a request to document the metadata setter found [here](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/ffd7cca2c1bbcf71b753913eab4d95ec0ca04f8a/storage/google/cloud/storage/blob.py#L1408) to documentation found [here]( https://googlecloudplatform.github.io/google-cloud-python/stable/storage/blobs.html#google.cloud.storage.blob.Blob.metadata). 

Thank you!

**Comment by frankyn** [comment]
Thanks @dhermes!

**Comment by dhermes** [comment]
Thanks for filing @frankyn!
