### ISSUE TITLE
Returned entities from "Query.fetch()" have random property order.

### ISSUE THREAD

**Issue by umutberkbilgic** [GoogleCloudPlatform/google-cloud-python#3649]
**SYSTEM:**
1.Ubuntu 17.04
2. Python 2.7.13 / virtualenv 15.1.0
3. Google Cloud Datastore version 1.1.0

**ISSUE:**
When the following Python code is executed a bunch of times, the properties of entities vary from execution to execution:

```python
from google.cloud import datastore

datastore_client = datastore.Client()
datastore_query = datastore_client.Query(kind = "users") 

query.add_filter("id", ">", 0) # in my case, all the users have id's bigger than 0, so this filters out nothing
result = list(datastore_query.fetch())

print result

```

Here are some untouched/parsed data from the server, I will add a new (press enter) before"Entity" for readability purposes.

```
[<Entity(u'users', u'Hemet Nesingwary') {u'id': 1L, u'updated': datetime.datetime(2017, 7, 21, 11, 17, 31, 529889, tzinfo=<UTC>), u'email': u'beastybeast@peta.org', u'pass': u'doggydogggg'}>, 

<Entity(u'users', u'Tirion Fordring') {u'updated': datetime.datetime(2017, 7, 20, 14, 16, 49, 972246, tzinfo=<UTC>), u'pass': u'damnyouarthas', u'id': 1L, u'email': u'argentcrusader@hotmail.com'}>,

 <Entity(u'users', u'David Davenport') {u'updated': datetime.datetime(2017, 7, 20, 14, 17, 16, 708237, tzinfo=<UTC>), u'pass': u'ilovejava8', u'id': 2L, u'email': u'ddavenport@bilkent.edu.tr'}>,

 <Entity(u'users', u'Lorewolker Cho') {u'id': 2L, u'updated': datetime.datetime(2017, 7, 21, 11, 19, 4, 820946, tzinfo=<UTC>), u'email': u'chi@sha.com', u'pass': u'garroshbae'}>, 

<Entity(u'users', u'Magni Bronzebeard') {u'id': 3L, u'updated': datetime.datetime(2017, 7, 20, 14, 18, 7, 588154, tzinfo=<UTC>), u'email': u'threehammer@ironforge.net', u'pass': u'dwarvenpower666'}>, 

<Entity(u'users', u'Lord Jaraxxus') {u'id': 7L, u'updated': datetime.datetime(2017, 7, 20, 14, 38, 46, 853036, tzinfo=<UTC>), u'email': u'eredarlove@legion.edu.com', u'pass': u'tremblingGnom3'}>]
```

Notice that for the first user the property order is "name(key) -> id -> updated -> email -> password"
and in the second one it is completely different "name(key) -> updated -> password -> id -> email". Additionally, the propery order is consistent around %60 of the time and for the 40%; the entities that are messed up and the order of their property is completely random. 

EDIT: styling
EDIT 2: derp, styling

**Comment by dhermes** [comment]
@umutberkbilgic This is a symptom of `dict` ordering in Python, which is **intentionally** not deterministic. The ordering of the dictionary is not specified by the backed, it's just a `key->value` mapping.

(I'll try to track down a reference about dictionary ordering in Python.)

**Comment by dhermes** [comment]
See:

- https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED
- https://docs.python.org/3/using/cmdline.html#cmdoption-R
