### ISSUE TITLE
blob.upload_from_file does not support files that are transformed with Pillow and then saved into a file.

### ISSUE THREAD

**Issue by nanomosfet** [GoogleCloudPlatform/google-cloud-python#3655]
## Issue:
After converting file from upload using Pillow bucket shows an empty file for the uploaded image

## Documentation
[Using cloud storage for Python Flexible Environment](https://cloud.google.com/appengine/docs/flexible/python/using-cloud-storage)

## Steps to reproduce:
1. Post form with enctype of multipart/form-data with file upload to server
2. Handle request with Flask and retrieve file
3. Convert file with pillow
4. Save converted file into file object
5. Use `upload_from_file` to  upload blob to cloud storage
6. Note the empty file in cloud storage bucket

## Code Example:
```python
@app.route('/upload', methods=['POST'])
def upload():
    """Process the uploaded file and upload it to Google Cloud Storage."""
    uploaded_file = request.files.get('file')

    if not uploaded_file:
        return 'No file uploaded.', 400
     
    # Open Image with Pillow   
    image = images.open(uploaded_file)

    # Resize image with Pillow (Problem still occurs without this step)
    image.resize((300,300))

    # Create Filestorage object (This is the wrapper Flask uses for their file uploads)
    fs = FileStorage()

    # Save image with Pillow into FileStorage object.
    image.save(fs, format='JPEG')

    # Verify that image was resized and works
    Image.open(fs).show()
    
    # Create a Cloud Storage client.
    gcs = storage.Client()

    # Get the bucket that the file will be uploaded to.
    bucket = gcs.get_bucket(CLOUD_STORAGE_BUCKET)
    
    # Create a new blob and upload the file's content.
    blob = bucket.blob(uploaded_file.filename)
    
    blob.upload_from_file(fs)

    # The public URL can be used to directly access the uploaded file via HTTP.
    return blob.public_url
```

## Environment Information:
OS: Windows 10
Python Version: 2.7.13
Virtualenv version: 15.1.0
Flask Version: 0.12.2
Pillow Version: 4.2.1
google-cloud-storage version: 1.2.0

**Comment by dhermes** [comment]
@nanomosfet What doesn't work about it? Can you provide a stacktrace?

I'd guess the issue is that `fs` is not "at the beginning", i.e. `fs.tell() != 0`. If `FileStorage` implements the `file` interface, then you should be able to just call `fs.seek(0)` before uploading.

**Comment by nanomosfet** [comment]
@dhermes That was exactly it. Thank you.

**Comment by dhermes** [comment]
Well that was easy! Great news, glad I could help :grinning:
