### ISSUE TITLE
Question about `Table.upload_from_file` method

### ISSUE THREAD

**Issue by WillianFuks** [GoogleCloudPlatform/google-cloud-python#3660]
Hello,

This is just a quick question about something that got me confused. I was recently searching for uploading media content for bigquery and found that it should be used with the method `Table.upload_from_file`. I was wondering, shouldn't this method be located in the job.py module, something like `LoadTableFromMediaJob`? (similar to `LoadTableFromStorageJob`).

Maybe this would even remove some code duplication when building the resource for the api call as both methods share the same schema definition for the `load` configuration.

Thanks!

**Comment by tseaver** [comment]
@WillianFuks The rationale for having this method on `Table` is that it doesn't involve "jobs" at all:  it uses the "media upload" interface against a required-to-exist table.

**Comment by WillianFuks** [comment]
Hi @tseaver , thanks for the reply!

I considered this as a Job because it's defined as a [job.insert](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/insert) method with the same [load.configuration](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load) as `LoadTableFromStorageJob` (main difference been the post URL that is `upload/bigquery/v2/projects/projectId/jobs` alongside the media for uploading and `bigquery/v2/projects/projectId/jobs` for just metadata).

The reason I decided to ask after all was that I was wondering if there could be some advantage for having this method defined as a job and then have some class that defines a load configuration schema that could be used either in `LoadTableFromStorageJob` and also `LoadTableFromMediaJob`.

As an example, recently I made a PR adding support for the feature schema auto-detection for `LoadTableFromStorageJob`. Now I wanted to add the same feature for `Table.upload_from_file`. But both share the same `load.configuration` schema, so if both had access to some (maybe) class such as `LoadConfigurationSchemaDefinition` where we could add the feature `autodetect` already, we wouldn't have to implement it in two distinct places.

Maybe end result would be something like (just quick example to illustrate):

    class LoadConfigs():
        @property
        def autodetect(self):
             return self._autodetect
    
        @autodetect.setter       
        def autodetect(self, value):
            if not self.schema:
                self._autodetect = value

        (other load configuration objects)

    class LoadTableFromStorageJob(Job, LoadConfigs):
        (...)
    class LoadTableFromMediaJob(Job, LoadConfigs):
        (...)

So we would have to define it in just one place and unit test just one module, not two.

Notice also that the table does not have to exist beforehand then (if one uses schema auto-detection then the table is created automatically).

And probably the `job.begin()` for this new method would be responsible then for using the media upload interface.

Well hopefully I wasn't too confusing. I wonder what you think :)!

**Comment by jonparrott** [comment]
This is interesting feedback. The last time I touched the table class
during the resumable upload changes I noticed it was fairly large (pylint
is also not happy with it). I couldn't think of a good way to break it up,
but perhaps this makes sense?

/cc @swast as well.

**Comment by tswast** [comment]
+1 to having a common `LoadConfigurationSchemaDefinition` and similar shared objects for the requests. I'm starting to compile a design doc for a redesign/refactoring of the BigQuery client libraries and will take this into account.
