### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'r' Google-cloud-sdk

### ISSUE THREAD

**Issue by mianasbat** [GoogleCloudPlatform/google-cloud-python#3676]
I am trying to setup google-cloud-sdk on Centos 6.6 Final. I installed Python 2.7.6 along with default 2.6.6. I am sure that the install.sh is using python2.7 because I tried python3.2 and python2.6 in which case it gives an error that you need python2.7. 

What I assume is that google-cloud-sdk is not compatible with Centos 6.6. However I couldnt find any evidence in favour or against on google.

I tried both tar file and running ./install.sh and the binary (kind of) but I get the same error.

```
/data/Install//google-cloud-sdk/install.sh
Welcome to the Google Cloud SDK!
Traceback (most recent call last):
  File "/data/Install//google-cloud-sdk/bin/bootstrapping/install.py", line 8, in <module>
    import bootstrapping
  File "/data/Install/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 18, in <module>
    from googlecloudsdk.core import config
  File "/data/Install/google-cloud-sdk/lib/googlecloudsdk/core/config.py", line 160, in <module>
    INSTALLATION_CONFIG = InstallationConfig.Load()
  File "/data/Install/google-cloud-sdk/lib/googlecloudsdk/core/config.py", line 85, in Load
    return InstallationConfig(**non_unicode_data)
TypeError: __init__() got an unexpected keyword argument 'r'
```

**Comment by dhermes** [comment]
@mianasbat This is a repository for the Python client library for Google Cloud APIs.

@jonparrott Could you help redirect for where to file issue for the Google Cloud SDK?

**Comment by jonparrott** [comment]
https://issuetracker.google.com/issues/new?component=187143&template=800102

**Comment by mianasbat** [comment]
Thank you guys. I posted it on the mentioned website :)
