### ISSUE TITLE
Add support for Dataflow job status and monitoring

### ISSUE THREAD

**Issue by dirtytrashgirl** [GoogleCloudPlatform/google-cloud-python#3684]
There is a [dataflow REST API](https://cloud.google.com/dataflow/docs/reference/rest/) which can  monitor jobs and get job status. These would be useful methods to have support for here.

**Comment by lukesneeringer** [comment]
Hi @dirtytrashgirl,
Thanks for requesting this.

We are hard at work hoping to add support for more and more APIs here. While I can not commit to an exact timeline for Dataflow specifically, we do hope to eventually support as many APIs as is feasible.

As this is not technically an issue with existing code in this repository, I am going to go ahead and close this, but I very much appreciate your taking the time to put in the request.
