### ISSUE TITLE
Speech system test are broken

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3690]
This likely occurred in #3607.

https://gist.github.com/dhermes/82fd3e231cd1abc7670f25a74e2626ab

Failure is:

```
AttributeError: 'Client' object has no attribute '_connection'
```

**Comment by jonparrott** [comment]
@lukesneeringer this is occurring only with the http fallback. I thought we were looking to delete that for speech?

**Comment by lukesneeringer** [comment]
We are, it is deprecated now. We could just remove the applicable system test.

**Comment by tseaver** [comment]
Current builds (e.g. https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/4061) have them passing.
