### ISSUE TITLE
How to retrieve 'totalBytesBilled'

### ISSUE THREAD

**Issue by sschatts** [GoogleCloudPlatform/google-cloud-python#3706]
1. OS type and version: Mac OS Sierra
2. Python version and virtual environment information `python --version`: Python 2.7.13
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`: google-cloud-bigquery==0.25.0 and google-cloud-core==0.25.0

Issue: Trying to monitor costs of queries on BigQuery by accessing the 'totalBytesBilled' field which is available through the HTTP API (jobs[].statistics.query.totalBytesBilled, https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/list). Is there a way to get this statistic through the Python Client? I've found you can access this through job._properties and was curious if there is a public API to access this. 

Thank you!

**Comment by tseaver** [comment]
@sschatts Thanks for the question:  it looks like that feature got smuggled into the V2 API after our implementation (there are other new query statistics, too!).

@tswast Can you confirm?

**Comment by tseaver** [comment]
To my eye, it appears that `all` the `query`--specific statistics fields are unmapped, as well as `extract.destinationUriFileCounts`.

**Comment by tseaver** [comment]
- `query`-specific staticstics support should be added to `job.QueryJob`, but might also need to be plumbed through to `query.QueryResults`.
- The `extract.destinationUriFileCounts` statistic should be added to `job.ExtractTableToStorageJob`.

**Comment by tseaver** [comment]
`query`-specific statistics:

- `query_plan` (maps `"queryPlan"`; return as list of dict)
- `total_bytes_processed` (maps `"totalBytesProcessed"`; int)
- `total_bytes_billed` (maps `"totalBytesBilled"`: int)
- `billing_tier` (maps `"billingTier"`: int)
- `cache_hit` (maps `"cacheHit"`: bool)
- `referenced_tables` (maps "referencedTables"; return list of `Table` instances?)
- `schema` (maps `"schema"; return list of `SchemaField`)
- `num_dml_affected_rows` (maps `"numDmlAffectedRows"`: int)
- `undeclared_query_paramters` (maps `"undeclaredQueryParameters"`;  return list of dict?)
- `statement_type` (maps `"statementType"; str)

**Comment by tseaver** [comment]
Via #3800.
