### ISSUE TITLE
Storage: bucket.labels surprisingly returns a deepcopy

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#3710]
I expected this to work:

```python
    bucket = storage_client.get_bucket(bucket_name)
    bucket.labels['example'] = 'label'
    bucket.patch()
```

Turns out `bucket.labels` returns a deepcopy, so I have to do this instead:

```python
    bucket = storage_client.get_bucket(bucket_name)
    labels = bucket.labels
    labels['example'] = 'label'
    bucket.labels = labels
    bucket.patch()
```

**Comment by dhermes** [comment]
I'm not sure what the right move is. There are definitely pros and cons here, i.e. I can imagine a user surprised they mutated the `Bucket` when they didn't intend to.

**Comment by jonparrott** [comment]
Yeah I agree. Could we at least document it better? The docstring for labels is actually totally wrong: https://google-cloud-python.readthedocs.io/en/latest/storage/buckets.html#google.cloud.storage.bucket.Bucket.labels

**Comment by dhermes** [comment]
Copy-pasta strikes again!

**Comment by tseaver** [comment]
The other properties which contain non-scalar values (`cors`, `lifecycle_rules`) also return copies.  I'm working on a PR which adds the following note (modified to use values appropriate to each one):

```rst
        .. note::

           The getter for this property returns a list which contains 
           *copies* of the bucket's CORS policy mappings.  Mutating the list
           or one of its dicts has no effect unless you then re-assign the
           dict via the setter.  E.g.:

           >>> cors = bucket.cors
           >>> cors.append({'origin': '/foo', ...})
           >>> del policies[0]
           >>> bucket.cors = cors
```
