### ISSUE TITLE
BigQuery: expose public helper method to convert a list of schema fields to/from a list of schema dictionaries (JSON)

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#3723]
I've received some feedback asking how to take a schema from the client library and save it to a JSON file. One reason to do this is the [`bq` command-line tool](https://cloud.google.com/bigquery/bq-command-line-tool#creatingtablefromfile) accepts a schema file, formatted like

```
[
  {"name": "name", "type": "string", "mode": "required"},
  {"name": "gender", "type": "string", "mode": "nullable"},
  {"name": "count", "type": "integer", "mode": "required"}
]
```

Note: this format is the same as the API representation.

It would be great if our client libraries could read/write in this format.

**Comment by tseaver** [comment]
We already have non-public helper methods which [render](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/3e8d53c02ec658faa0b72667cbd2cff492ee3278/bigquery/google/cloud/bigquery/table.py#L1188) / [parse](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/3e8d53c02ec658faa0b72667cbd2cff492ee3278/bigquery/google/cloud/bigquery/table.py#L1188) schemas to / from a format like:

```json
{"fields": [
  {"name": "name", "type": "string", "mode": "required"},
  {"name": "gender", "type": "string", "mode": "nullable"},
  {"name": "count", "type": "integer", "mode": "required"}
]}
```

It would be pretty trivial to adapt them to skip / overlook the missing `fields` key.  How would you envision this for the library API surface?  Methods on the `Table` class to load / store the schema to a file?  What about schema for e.g. `query` jobs?

**Comment by tswast** [comment]
There are two main use cases that I've head about

- at table creation/load time, being able to load schema from a file.
- after a query so that they can serialize the schema from the stats to then use to create other table.

**Comment by tswast** [comment]
Since this is something that would act on lists, it doesn't really correspond to an existing resource representation that we have. Do we put static helper functions in the top-level `google.cloud.apiname` package, generally?

**Comment by tswast** [comment]
Going through the issues I see that this is a duplicate of https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3419.

Closing this issue in favor of that one.
