### ISSUE TITLE
job.py in bigquery does unnecessary client-side validation of data formats

### ISSUE THREAD

**Issue by jtigani** [GoogleCloudPlatform/google-cloud-python#3725]
The BigQuery engineering team may decide to expand the allowed formats for import and export, but the allowed values are hard-coded client side. Imports are limited to CSV, DATASTORE_BACKUP, NEWLINE_DELIMITED_JSON, AVRO, for example.

This means that if the BigQuery starts to allow other formats, users will be unable to use those new formats without updating their client. Moreover, there is no way for BigQuery to roll out new formats to a whitelisted set of users. 
(note this is not mere idle speculation and is currently impacting real users alpha testing a new format)

See code here:
[https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/job.py#L116][1]
and 
[https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/job.py#L139][2]

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/6d7fae96d25a0a468683a5ab25a2f48014a16378/bigquery/google/cloud/bigquery/job.py#L116
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/6d7fae96d25a0a468683a5ab25a2f48014a16378/bigquery/google/cloud/bigquery/job.py#L139

**Comment by dsouzarc** [comment]
@jtigani @lukesneeringer Thank you both for your help and quick response :)
