### ISSUE TITLE
view.query property not exposed by Bigquery API

### ISSUE THREAD

**Issue by nicku33** [GoogleCloudPlatform/google-cloud-python#3754]
```
OS X 10
Python 2.7.10
Name: google-cloud Version: 0.24.0
```

To reproduce, make a view. In our case it was existing.
`! bq show --format=json nytdata:audit_et.audit_ab_alloc_view`

Note that the property view.query is present in the json:

```
{"kind":"bigquery#table","creationTime":"1471555852846",
...
"view":{"query":"with date_range a ... REDACTED ...",
"useLegacySql":false},"type":"VIEW","id":"nytdata:audit_et.audit_ab_alloc_view","selfLink":"https://www.googleapis.com/bigquery/v2/projects/nytdata/datasets/audit_et/tables/audit_ab_alloc_view","
...
}
```

But if I try to get it from the API, nothing:

```
from google.cloud import bigquery

project="nytdata"
dataset="audit_et"
table="audit_ab_alloc_view"

bigquery_client = bigquery.Client(project=project)
dataset_temp = bigquery_client.dataset(dataset)
t=dataset_temp.table(table)
t=dataset_temp.table(u'audit_ab_alloc_view')

t.exists()
>> True

t.view_query == None
>> True
```

**Comment by lukesneeringer** [comment]
@tseaver Is this something that can reasonably be done alongside #3746?

**Comment by tseaver** [comment]
@nicku33 Can you try running `t.reload()` and see if the `view_query` is populated?  We don't automagically fetch the server-side properties when creating the client-side table instance.

**Comment by nicku33** [comment]
Oh wow, that worked. I suppose I assumed that 
``` dataset_temp.table( TABLE_NAME ) ```
did an API fetch. Did I miss something in docs ?

**Comment by tseaver** [comment]
@nicku33 I agree that the docs don't highlight it, but we explicitly avoid making back-end API calls during instance construction.

**Comment by lukesneeringer** [comment]
Something @tswast recommends elsewhere is that we make it such that the first time you do a call or property check that would require this, that we just do the `.reload` behind the scenes.

I am going to actually close this since that is tracked elsewhere.
