### ISSUE TITLE
[Vision]  add a new function 'detect_all' in image.py

### ISSUE THREAD

**Issue by bryanyang0528** [GoogleCloudPlatform/google-cloud-python#3771]
There is a function `detect` in image.py for detecting multiple feature types. Could we add a function called `detect_all` to detect all feature types at one time? This is my proposal:

```python
    def detect_all(self, limit=10):
        """Detect multiple feature types.

        :type limit: int
        :param limit: The number of faces to try and detect.

        :rtype: list
        :returns: List of
                  :class:`~google.cloud.vision.entity.EntityAnnotation`.
        """

        features = [Feature(x, limit) for x in FeatureTypes.__dict__.keys() if x[:1] != '_']
        annotations = self.detect(features)
        return annotations[0]
```

**Comment by lukesneeringer** [comment]
Hi @bryanyang0528,
Thanks for reporting.

I have good news. :-) This exists (in the newest version), and it is spelled `annotate_image`. Just send a request with `features` unspecified, and we specify the list of "all of them" for you.

Thanks for using the Vision API!

**Comment by bryanyang0528** [comment]
Hi @lukesneeringer  Thank you for quick reply. Looking forward to see the new version :)
