### ISSUE TITLE
operation.done() doesn't return True when annotations complete

### ISSUE THREAD

**Issue by odoric27** [GoogleCloudPlatform/google-cloud-python#3778]
```
OS VERSION
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
```
`PYTHON VERSION == 3.6.2`

```
GOOGLE SERVICE VERSION
Name: google-cloud-videointelligence
Version: 0.25.0
Summary: Python Client for Google Cloud Video Intelligence
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.6/site-packages
Requires: six, google-gax, googleapis-common-protos
```

After calling `annotate_video`, I'm checking `operation.done()` every 15 seconds before processing the annotation results. I set an arbitrary timeout of 120 seconds, which when reached will call `operation.cancel()`.

However, I'm finding that some annotations actually do complete, which I can confirm by checking the json results uploaded to the designated `output_uri`. How is it that the annotations will complete, but `operation.done()` never returns True?

**Comment by lukesneeringer** [comment]
@jonparrott This would be using the old Operation. I assume this is just gated on a toolkit change to use the new one in autogen?

**Comment by jonparrott** [comment]
Yep.

**Comment by chemelnucfin** [comment]
@lukesneeringer @jonparrott May I asked if this has been fixed?

**Comment by jonparrott** [comment]
should be, video intel uses api_core now instead of gax.
