### ISSUE TITLE
gcloud==0.18.3 and google-cloud-datastore==1.2.0 run into dependency conflicts

### ISSUE THREAD

**Issue by Gwildor** [GoogleCloudPlatform/google-cloud-python#3807]
Hello,

I'm working on a large project with a lot of history that's using some Google Cloud services. We use [pip-compile](https://github.com/jazzband/pip-tools) for generating our requirements file. I installed google-cloud-datastore==1.2.0, which worked fine, but after adding it in my requirements file and running `pip-compile`, I'm running in a quagmire of dependency conflicts. I've looked at #3579, but that didn't enlighten me much.

This is the error that `pip-compile` generates:

```
$ pip-compile --verbose --output-file requirements.txt requirements.in | grep ' requires .* google-gax'
  gcloud==0.18.3            requires gax-google-logging-v2<0.9dev,>=0.8.0, gax-google-pubsub-v1<0.9dev,>=0.8.0, google-gax<0.13dev,>=0.12.3, googleapis-common-protos, grpc-google-logging-v2<0.9dev,>=0.8.0, grpc-google-pubsub-v1<0.9dev,>=0.8.0, grpcio>=1.0rc1, httplib2>=0.9.1, oauth2client>=2.0.1, protobuf!=3.0.0.b2.post1,>=3.0.0b2, six
  google-cloud-datastore==1.2.0 requires gapic-google-cloud-datastore-v1<0.16dev,>=0.15.0, google-cloud-core<0.27dev,>=0.26.0, google-gax<0.16dev,>=0.15.7
Could not find a version that matches google-gax<0.13dev,<0.16dev,>=0.12.3,>=0.15.7
```

As you can see, the problem is trying to determine the correct version of google-gax, which gcloud requires to be <0.13dev,>=0.12.3, while google-cloud-datastore requires to be <0.16dev,>=0.15.7. Obviously, this results in an error.

I'm not sure what the steps forward are here. I'm surprised that pip allowed installing and using google-cloud-datastore at all. I'm assuming that in itself broke the usage of gcloud, but that is used in a lot of different places in the code that I can't test now to verify that it broke.

**Comment by dhermes** [comment]
@Gwildor `gcloud==0.18.3` has been deprecated since about September 2016 (when [`google-cloud=0.19.0`][1] came out)

[1]: https://pypi.org/project/google-cloud/#history

**Comment by dhermes** [comment]
Closing because it doesn't seem there is much to do here. `gcloud` and `google-cloud` aren't meant to be used together.

I'm happy to re-open if I'm mistaken.
