### ISSUE TITLE
google-cloud-core incompatible with App Engine (py27)

### ISSUE THREAD

**Issue by msuozzo** [GoogleCloudPlatform/google-cloud-python#3815]
The polling library in google-cloud-core contains an indirect native dependency (`ctypes`) via the `tenacity` library. This has the unfortunate consequence of causing import failures on App Engine because the GAE runtime restricts the use of native dependencies.

To clarify the dependency chain causing the problem:

| Project | Description | Relevant Import Site
|--------|------------|-------------
|`google-cloud-core`||[`core/google/api/core/future/polling.py`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/0723a9cb802a08c828af83049c80b68036fcfc3c/core/google/api/core/future/polling.py#L23)
|[`tenacity`](https://github.com/jd/tenacity)|General-purpose retry library|[`monotonic` import](https://github.com/jd/tenacity/blob/319168f18ecb7d95ead91f3d7aaada23dabe1161/tenacity/__init__.py#L28)
|[monotonic](https://github.com/atdt/monotonic)|py27 backport of py33 `time.monotonic`|[`ctypes` import](https://github.com/atdt/monotonic/blob/5c0322dc559bf961f7e111d97cd3ed9ab5c1a73b/monotonic.py#L41)|

I couldn't think of a particularly easy fix.

One wacky idea that might work would be to write a monotonic-like function/class that faked monotonicity by storing some fixed number of recent calls to the non-monotonic function (e.g. `time.time()`). When a new call came in, it would call the time function and instead of returning that value straight away, it would calculate and return the max of the value and the cached previous calls (and, to be definitionally correct, add an epsilon). Given the constraints of tenacity, this might suffice but a simpler solution would obviously be preferred.

Thanks :)

**Comment by jonparrott** [comment]
Unfortunately, App Engine standard does not support these client libraries yet. We are working on it and you can follow https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1893#issuecomment-322512490 for updates and more details.
