### ISSUE TITLE
Colour scheme of Python logo makes it look like Nazi flag

### ISSUE THREAD

**Issue by inglesp** [GoogleCloudPlatform/google-cloud-python#3820]
Thanks for a great library.  I'm sure it's accidental, but the colour scheme of the Python logo at https://googlecloudplatform.github.io/google-cloud-python/ makes it look like the flag of the Third Reich.

![image](https://user-images.githubusercontent.com/28734/29352337-49b27696-825e-11e7-86b4-2be0f319893e.png)

![image](https://user-images.githubusercontent.com/28734/29352359-581ea8f8-825e-11e7-812b-982ce77362aa.png)

Would you consider changing it?

**Comment by lukesneeringer** [comment]
We should just make it blue.

**Comment by jonparrott** [comment]
Yeah, agreed. I'll send a PR when I'm at a keyboard.

**Comment by lukesneeringer** [comment]
Great, I am sure you can get to it quicker. Ping me in real-time for a review.

**Comment by lukesneeringer** [comment]
And the button is green now. Thanks @inglesp. :-)

**Comment by jonparrott** [comment]
Yep, thanks for bringing this to our attention @inglesp.
