### ISSUE TITLE
It is not obvious what library version the docs are for

### ISSUE THREAD

**Issue by inglesp** [GoogleCloudPlatform/google-cloud-python#3824]
In the documentation at https://googlecloudplatform.github.io/google-cloud-python/latest/index.html, it is not clear (to me -- maybe I'm missing something) what version of the library the documentation is for.

I know the URL says "latest", but an explicit version number somewhere would be very useful.

**Comment by lukesneeringer** [comment]
I agree that this would be nice to tweak. (Honestly that entire page could use some love.)

**Comment by jonparrott** [comment]
Once we split the repo I can put the library version in the footer.

**Comment by lukesneeringer** [comment]
Yeah, that was my thinking also.

**Comment by dhermes** [comment]
It'd be nice if the repo split happened sooner rather than later :+1:

**Comment by lukesneeringer** [comment]
I have to finish the Node one first. I am working on it as fast as I can.

**Comment by chemelnucfin** [comment]
Hello, feature requests will now be tracked in the project [Feature Requests](https://github.com/GoogleCloudPlatform/google-cloud-python/projects/5#card-6867160).  I will close this issue now, please feel free to continue to address any issues/concerns here.
