### ISSUE TITLE
Cause for this error?

### ISSUE THREAD

**Issue by lukesneeringer** [GoogleCloudPlatform/google-cloud-python#3833]
_From @jyc979 on August 16, 2017 23:5_

I keep getting the following error

"RetryError: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Invalid audio channel count)>)"

When trying to use the Google Cloud Speech API, I'm trying to use the sample audio file saved on my local computer. But it works fine with cloud-sample-test audio file given by google. Any possible fixes?

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#2539_

**Comment by lukesneeringer** [comment]
_From @stephenplusplus on August 17, 2017 2:52_

Hey @jyc979, sorry for the trouble. Could you paste the code you're using to make the API call that is failing? Additionally, the version of the Speech module that you are using.

**Comment by lukesneeringer** [comment]
_From @jyc979 on August 17, 2017 3:38_

```

import os
 import io
def transcribe_file(speech_file):
    """Transcribe the given audio file."""
    from google.cloud import speech
    from google.cloud.speech import enums
    from google.cloud.speech import types
    client = speech.SpeechClient()

    with io.open(speech_file, 'rb') as audio_file:
        content = audio_file.read()

    audio = types.RecognitionAudio(content=content)
    config = types.RecognitionConfig(
        encoding='FLAC',
        sample_rate_hertz=44100,
        language_code='en-US')

    response = client.recognize(config, audio)
    alternatives = response.results[0].alternatives

    for alternative in alternatives:
        print('Transcript: {}'.format(alternative.transcript))
```

Speech module was v1. I passed in the path of an audio file on my machine

**Comment by lukesneeringer** [comment]
Moving this over to google-cloud-python.

**Comment by lukesneeringer** [comment]
Hi @jyc979,
I think the most likely cause of this problem is that the encoding you are declaring does not match the encoding of the actual file. Are you sure you have a FLAC file?

**Comment by jyc979** [comment]
@lukesneeringer Hey, I figured out the issue. I was not using the mono audio file as an input. Also a quick question while we're at it, how can I set to show the confidence levels of the non-top results? It says on the documentation [https://cloud.google.com/speech/reference/rest/v1beta1/speech/syncrecognize](url)

here that for non top results, it shows 0.0 for sentinel values, but it seems like there's a way to show the levels of non top results, is there a way?

**Comment by lukesneeringer** [comment]
@jyc979: Excellent, glad to hear it.

Regarding alternatives, the there is a `confidence` value on [SpeechRecognitionAlternative](http://google-cloud-python.readthedocs.io/en/latest/speech/gapic/types.html#google.cloud.speech_v1.types.SpeechRecognitionAlternative), which is what you need.

Thanks!
