### ISSUE TITLE
run_async_query on version 0.26.0

### ISSUE THREAD

**Issue by fcaldas** [GoogleCloudPlatform/google-cloud-python#3839]
Hi,

  I had some python scripts using this library to do requests on BigQuery but  after updating google-cloud-bigquery to version 0.26 I am having some issues executing these scripts.

  I am currently running Fedora 25, with python 2.7 and google.cloud.bigquery is on version 0.26.0, my script looks like this at the moment:

```
    client = bigquery.Client(project='myprojectid')

    q = """
           SELECT co.w, 
                  co.n n_now, 
                  po.n n_prv, 
                  ROUND(((co.n) / po.n * 100),1) increase_rate 
             FROM trends.CurrentYearOccurrences_all co 
        LEFT JOIN trends.PreviousYearsOccurences_all po 
               ON co.w = po.w 
              AND co.n > 5 
         ORDER BY increase_rate DESC 
            LIMIT 20
        """

    d = client.run_async_query( ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(12)),
                                q)
    d.use_legacy_sql = False
    d.begin()

    while(d.state != "DONE"):
        time.sleep(1)
        d.reload()

```

So previously I then was able to access the object ```d``` like this:

```
   for row in d.results().fetch_data()[0]:
```

But it seems like ```d.results()``` is now ```d.result()``` and executing a ```fetch_data()``` returns a ```google.cloud.bigquery.query.QueryResults``` object but I can't access the rows on this object (returns an empty set) and all properties on this object seems to be equal to ```None```.

Thanks,

**Comment by lukesneeringer** [comment]
Hi @fcaldas,
You are correct, we made some changes to that interface. In particular, the new thing that is returned is a [Future](https://docs.python.org/3/library/concurrent.futures.html#future-objects).

The `.result()` method should block until the result actually comes back, but it sounds like you are not getting that behavior? I am looking at the code, and it seems like there might be an error.

@jonparrott Can you confirm that [this code](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/core/google/api/core/future/polling.py#L76-L77) is erroneous? I am pretty sure it short-circuits the polling entirely and gives exactly the behavior that @fcaldas describes.

**Comment by lukesneeringer** [comment]
@fcaldas This is still a bug we need to fix, but in the immediate term you can work around it with:

```python
while not result.done():
    time.sleep(5)
for row in d.result().fet...
```

**Comment by jonparrott** [comment]
> @jonparrott Can you confirm that this code is erroneous? I am pretty sure it short-circuits the polling entirely and gives exactly the behavior that @fcaldas describes.

That's correct, it prevents the repeated calls to `result()` from re-polling if the operation is already done. I'll take a look and see what's up here.

**Comment by jonparrott** [comment]
@fcaldas I would recommend looking at this sample [here ](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/query.py) which I just confirmed works. @tswast might be able to give more advice, but as far as I can tell futures are working as intended.

**Comment by lukesneeringer** [comment]
Ah, early morning mis-read. I thought it read `if not self._result_set`
