### ISSUE TITLE
Enable billing for a GCP project which has been created by resource manager api

### ISSUE THREAD

**Issue by arycloud** [GoogleCloudPlatform/google-cloud-python#3847]
I'm trying to setup gcp project using google cloud api python client and I have managed project creation successfully but nothing find any source on how to enable billing for that project?

**Comment by chemelnucfin** [comment]
Hello,
  I believe this may be the API you are looking for.
https://cloud.google.com/billing/reference/rest/

I will also close this issue.  Please feel free to reopen if this is still a concern.
