### ISSUE TITLE
How to do batch image processing (object detection) in cloud vision?

### ISSUE THREAD

**Issue by tianqig** [GoogleCloudPlatform/google-cloud-python#3852]
I am using a Firebox browser to access Cloud vision api, I have manually submitted requests for object detection through a remote shell.

Now I would like to automate the submission process, say, 200 images/match so that I can do **batch processing to the images** at Google storage, say, detect objects in the images.

Seems to me the process just does two functions for a list of image files:
1.  put the image name into request.json
2. put the image name into the following submission command:

`$ gsutil acl ch -g AllUsers:R gs://my-storage-bucket/donuts.jpeg`

3. save the response into a file for further processing

I searched for demos of batch processing, could not find any. Please help or point me to right sites.

Thanks for your help

**Comment by lukesneeringer** [comment]
Hi @tianqig,
This issue tracker is for tracking issues with the Python client libraries specifically, which to the best of my assessment, you do not seem to be using.

_However_, good news; you can do exactly what you want with the Python client library! We have the [annotate_image](http://google-cloud-python.readthedocs.io/en/latest/vision/index.html#annotate-an-image) method in our Vision library, but there is also [batch_annotate_image](http://google-cloud-python.readthedocs.io/en/latest/vision/gapic/v1/api.html#google.cloud.vision_v1.ImageAnnotatorClient.batch_annotate_images) which takes a list of the same request types, and will do exactly what you want.

**Comment by tianqig** [comment]
Great and thanks for your help! This is exact what I was looking for.
