### ISSUE TITLE
Integers get truncated when using insert_data

### ISSUE THREAD

**Issue by JamesCLloyd** [GoogleCloudPlatform/google-cloud-python#3854]
Hello,

When using insert_data with a dummy row of data it seems to truncate the integers.

```
from google.cloud import bigquery

client = bigquery.Client(project='xxx')
dataset = client.dataset('xxx')

pk = bigquery.SchemaField('sales_order_header_id','INTEGER','REQUIRED')
table = dataset.table('sales_order_header', schema=[pk])

rows = [('100'),('6'),('7'),('9')]

result = table.insert_data(rows)
```

This would end up as **1**, 6, 7, 9 in BQ.

Is this a rookie Python error or is something else going on? 
Any ideas most welcome.

**Comment by lukesneeringer** [comment]
Hi @JamesCLloyd,
First of all, I am not a BigQuery expert and have only passing familiarity with that library. I will do my best to help you, but I know who to poke if I am unable.

I think, however, this _might_ be a rookie Python error. The code `('100')` looks like tuple, but it is actually a string; tuples with one element require a trailing comma, such as `('100',)`. In the absence of such a comma, I bet the library is splitting on the string itself, which would yield `('1', '0', '0')`.

Could you try replacing your `rows` line with: 

```python
rows = [('100',),('6',),('7',),('9',)]
```

...and tell me if it gives you the result you expect?

Thanks!

**Comment by JamesCLloyd** [comment]
That works - thanks!
