### ISSUE TITLE
Pubsub basic API broken

### ISSUE THREAD

**Issue by kardamom** [GoogleCloudPlatform/google-cloud-python#3875]
In 0.28.1:
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import pubsub
>>> cl = pubsub.Client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'google.cloud.pubsub' has no attribute 'Client'

In 0.27:
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import pubsub
>>> cl = pubsub.Client()
>>> quit()

**Comment by lukesneeringer** [comment]
Actually, this is not an error. We made a very sweeping change to the API (primarily at the request of the Pub/Sub team), as noted in the [release notes](https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/pubsub-0.28.0).

**Comment by lukesneeringer** [comment]
Hey @kardamom, I saw you made a comment in #3863 that the API was ahead of the docs -- did I miss a link somewhere?

**Comment by lukesneeringer** [comment]
Sure enough, I missed one. #3876 filed to update it, will merge when CI goes green.
