### ISSUE TITLE
ImportError: cannot import name datastore

### ISSUE THREAD

**Issue by synaqvi** [GoogleCloudPlatform/google-cloud-python#3878]
Hi
I have just installed google-cloud and try to run the following command on python console:

`from google.cloud import datastore`

But it gives me following error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name datastore
```

Few details are as follow:

1. OS version and type:
macOS Sierra Version 10.12.6 (16G29)

2. Python version:
Python 2.7.13 :: Anaconda 4.4.0 (x86_64)

3. google-cloud-python version:
Name: google-cloud
Version: 0.27.0
Summary: API Client library for Google Cloud
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: googleapis-publisher@google.com
License: Apache 2.0
Location: /Users/synaqvi/anaconda/lib/python2.7/site-packages
Requires: google-cloud-videointelligence, google-cloud-bigquery, google-cloud-dns, google-cloud-translate, google-cloud-logging, google-cloud-monitoring, google-cloud-bigtable, google-cloud-core, google-cloud-runtimeconfig, google-cloud-resource-manager, google-cloud-error-reporting, google-cloud-speech, google-cloud-language, google-cloud-spanner, google-cloud-pubsub, google-cloud-storage, google-cloud-datastore, google-cloud-vision

Please help.
Thanks in advance.

**Comment by lukesneeringer** [comment]
Hi @synaqvi,
I just made a new Python 2.7 virtualenv and did the same thing without incident. Can you post a full stacktrace, if one exists? Also, what happens if you install `google-cloud-datastore` directly?

**Comment by synaqvi** [comment]
Hi @lukesneeringer

As I am new to Python therefore, please let me know how to do following:

How to capture complete stacktrace?
How to install google-cloud-datastore directly? 

Thanks in advance.

**Comment by lukesneeringer** [comment]
I would expect a full stacktrace to just print. There is nothing special.

Installing Datastore alone is just `pip install google-cloud-datastore`. You should probably make sure you are using a [virtualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/).

**Comment by synaqvi** [comment]
I checked the same in a new virtual environment and found it working fine. Hopefully, some issues with my local environment.
Thanks for your prompt support.
