### ISSUE TITLE
How to create new Configs & Variables ?

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/google-cloud-python#3897]
The service supports and the documentation suggests that Configs and Variables resources creates methods (should) exist. Reviewing the documentation, I'm unable to find (expected?) create methods for these and reviewing the sources, it's unclear how these could be constructed.

Is it me? Or, are these methods missing?

"Create / interact with ... configs"
https://googlecloudplatform.github.io/google-cloud-python/latest/runtimeconfig/config.html

"Create / interact with ... variables"
https://googlecloudplatform.github.io/google-cloud-python/latest/runtimeconfig/variable.html

### Confirm
```
gcloud beta runtime-config configs list \
--project=${PROJECT}
```
```
NAME      DESCRIPTION
exists    Description
```
```
gcloud beta runtime-config configs variables list \
--config-name=exists \
--project=${PROJECT}
```
```
NAME       UPDATE_TIME
exists     2017-08-29T15:03:26.359064036Z
```

### Getters

```python
from google.cloud import runtimeconfig
client = runtimeconfig.Client()

config = client.config("exists")
print (config.exists())
print (config.get_variable("exists").exists())
```
Results:
```
True
True
```
### Setters?
```python
config = client.config("create")
print (config.exists())
config.create()
print (config.exists())

```
Results:

```
    config.create()
AttributeError: 'Config' object has no attribute 'create'
```
```python
print (config.exists())
variable = config.variable("test")
variable.create()
```
Results:
```
    variable.create()
AttributeError: 'Variable' object has no attribute 'create'
```

**Comment by chemelnucfin** [comment]
@DazWilkin Hello, I apologize for the late response.

I looked over the issue, and the create functions are intended not to be there.  
You can use 
`config = client.config('config_name')`  to create a configuration 
https://googlecloudplatform.github.io/google-cloud-python/latest/runtimeconfig/client.html
and `variable = config.variable('variable_name')` to create a variable
https://googlecloudplatform.github.io/google-cloud-python/latest/runtimeconfig/config.html

Please feel free to reopen if you have any more questions.

**Comment by kw** [comment]
Those will create the local object, not the config/variable in the cloud. The exists() methods of the created objects will return False if they haven't been created using `gcloud` or direct HTTP calls. Likewise, Variable doesn't expose any way to set the variable's value in the cloud.

To put it another way, there's no way to achieve `gcloud beta runtime-config configs variables set <NAME> <VALUE> --config <CONFIG>` using the Python API.

**Comment by chemelnucfin** [comment]
@kw Thanks, I misunderstood.  So it seems like these are just not implemented features in the client and not that it shouldn't be there.  I will reopen this.

**Comment by chemelnucfin** [comment]
See #4926
