### ISSUE TITLE
Problems accessing Variables properties

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/google-cloud-python#3898]
using Cloud SDK, I'm able to construct a Configs resource, a Variables resource in it and set a text value but, when I try to access these properties through Cloud Client Libraries for Python, I'm unable to get the values:

```
gcloud beta runtime-config configs variables get-value my-variable \
--config-name=${CONFIG} \
--project=${PROJECT}
```
Returns:
```
my-value
```
```
gcloud beta runtime-config configs variables describe my-variable  \
--config-name=${CONFIG} \
--project=${PROJECT}
```
Returns:
```
atomicName: projects/$PROJECT/configs/$NAME/variables/my-variable
name: my-variable
text: my-value
updateTime: '2017-08-29T15:03:26.359064036Z'
```
And:
```python
from google.cloud import runtimeconfig

client = runtimeconfig.Client()

config = client.config(CONFIG)
print (config.exists())
print(config.get_variable(VARIABLE).exists())
print(config.get_variable(VARIABLE).full_name)
```
Returns:
```
True
True
projects/$PROJECT/configs/$NAME/variables/$VARIABLE
```
But:
```

print(config.get_variable(VARIABLE).state)
print(config.get_variable(VARIABLE).value)
```
Returns:
```
None
None
```

**Comment by chemelnucfin** [comment]
I made a pull request that should address the state returning `None`.  However, I believe value returning None is the correct behavior until you set the variable to something.  Please let me know if you have any more questions.

**Comment by kw** [comment]
While your patch probably covers the state, the value is still an issue.

In this case, the missing bit of information is how the variable was set in the first place. If the gcloud ... set command is run using the `--is-text` flag, the resource returned will have a `text` field instead of a `value` field. The current implementation ignores the possibility of the `text` field. The `value` getter should check for it and return it unmodified if it's present. Alternatively, could add a `Variable.text` getter and make the user figure it out.

**Comment by chemelnucfin** [comment]
@kw Thanks, so to make it consistent with the others, it seems like it would be better to have these two fields as oneof's (and therefore separate) instead of just using `Variable.value` for both.  Am I correct?

**Comment by kw** [comment]
That seems internally consistent with the resource, yet also inconvenient and confusing for an end user. For comparison, using the gcloud `get-value` command on this resource will return either `value` or `text`, whichever is present.

A nice middle ground might be to add an extra property or method that returns whichever type of value is present. But the important thing is making them accessible at all.

**Comment by chemelnucfin** [comment]
@kw As I mentioned in the PR, I have assumed that `value` always holds `base64 decodable bytes` and also that either `value` or `text` is set at any time.  If my assumptions are wrong, python2 and python3 may need to be treated differently.

**Comment by chemelnucfin** [comment]
See #4926
