### ISSUE TITLE
Writing to BlobProperty

### ISSUE THREAD

**Issue by thinrhino** [GoogleCloudPlatform/google-cloud-python#3902]
Hello, 
we are trying to write to a `BlobProperty` via the gcloud datastore api.
From what I have read, I understand that if I send `str` using python 2.7, data is stored as blob_type in datastore. To store a string, I need to convert it to unicode.

Now I have very large string, which crosses the 1500 bytes limit, as a `BlobProperty`.

Would be great if you can let me know how I can do that?
Cheers...

**Comment by dhermes** [comment]
@thinrhino As you pointed out, just make sure it's type if `bytes`, then it'll be stored as a blob.

Maybe I'm misunderstanding though. Could you provide a code snippet of what you tried and how it fails?

**Comment by tseaver** [comment]
@thinrhino Please feel free to reopen if @dhermes reply didn't answer your question.
