### ISSUE TITLE
BigQuery job.results() still in usage doc

### ISSUE THREAD

**Issue by leo-thumbtack** [GoogleCloudPlatform/google-cloud-python#3907]
**Edit by @dhermes**: The [`bigquery/usage.rst`][1] doc is out-of-date. We **really** need to run [those samples][2] on CI on a regular basis.

----

**Original**: Following https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery/usage.html#querying-data-asynchronous

it worked perfectly with 0.25, with latest version I get exception saying that 
`QueryJob` doesnt have a `results()` method anymore. 

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/48c37f2ddef0b9a38cb78d908dec90122de2e391/docs/bigquery/usage.rst
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/48c37f2ddef0b9a38cb78d908dec90122de2e391/docs/bigquery/snippets.py

**Comment by leo-thumbtack** [comment]
I think that the method changed name ? https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/job.py#L1282

**Comment by dhermes** [comment]
Thanks for the concern, the interface has indeed changed.

If you check out the release notes:

https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/bigquery-0.26.0
https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/bigquery-0.27.0

you can keep track of the changes.

For example

> Removing `results()` method from the `QueryJob` class. Use `query_results()` instead.

I am going to preemptively close this issue, but let me know if you think there is more to discuss?

**Comment by leo-thumbtack** [comment]
maybe update the readme i liked in my first message ?

**Comment by bits01** [comment]
Please also see #4153

**Comment by tswast** [comment]
This will be closed by https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4245.
