### ISSUE TITLE
File Upload With Share Public Permisssion

### ISSUE THREAD

**Issue by BHushanRathod** [GoogleCloudPlatform/google-cloud-python#3909]
I'm uploading a file to my bucket in django rest app, and want to give permission to the file as "share public", how can set permission? 
Thanks in advance...

**Comment by lukesneeringer** [comment]
Hi @BHushanRathod,
Thanks for asking. You can use the [make_public](http://google-cloud-python.readthedocs.io/en/latest/storage/buckets.html#google.cloud.storage.bucket.Bucket.make_public) method.

**Comment by BHushanRathod** [comment]
Thanks a lot bro, its working... is it possible to give permission on existing bucket which contains files?
When I tried, it gave following error:
`google.api.core.exceptions.Conflict: 409 POST https://www.googleapis.com/storage/v1/b?[project-name]: You already own this bucket. Please select another name.`
