### ISSUE TITLE
page_token parameter documentation is misleading

### ISSUE THREAD

**Issue by mackenzieATA** [GoogleCloudPlatform/google-cloud-python#3928]
The `page_token` parameter to several api functions such as `list_projects` and `list_jobs` is documented as follows:
> opaque marker for the next "page" of projects. If not passed, the API will return the first page of projects.

This is very misleading, as these functions return an `HTTPIterator` which if iterated on will seamlessly return multiple pages of results.
Only though experimentation did I determine that multiple pages of results are returned and that if I did want to make use of `page_token` I'd need to access it at the `next_page_token` of the  `HTTPIterator`.

I think the documentation should be updated to better reflect that multiple pages can be fetched without touching the `page_token` and possibly include where to access `page_token` if someone does need to use it.

**Comment by dhermes** [comment]
@mackenzieATA Can I safely assume you're referring to BigQuery?

Regarding documentation, @jonparrott I can't seem to find where the iterators doc is. IIRC when it moved to `google.api.core`, it became undocumented, to be re-documented at a later date?

**Comment by mackenzieATA** [comment]
Sorry, yes, BigQuery. In particular I'm reading the parameter documentation in google/cloud/bigquery/client.py

**Comment by jonparrott** [comment]
@dhermes it's here: http://google-cloud-python.readthedocs.io/en/latest/core/page_iterator.html
