### ISSUE TITLE
Cannot set billingTier in synchronous query

### ISSUE THREAD

**Issue by bwcho75** [GoogleCloudPlatform/google-cloud-python#3929]
This is not bug reporting, but enhancement request.

When user tries to change billing tier, it can be done when they call query with async:

```python
job = client.run_async_query('<random_jobID>', QUERY)
job.maximum_billing_tier = 3
```

but in case of `client.run_sync_query`. it returns query instead of job. It cannot change biling tier.
Can we add biling tier parameter in Query class?

**Comment by tswast** [comment]
This issue will be addressed in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4245, where both the asynchronous (now called `query`) and synchronous (now called `query_rows`) both accept a `QueryJobConfig` class for configuring optional properties of the query.
