### ISSUE TITLE
BigQuery: Streaming inserts

### ISSUE THREAD

**Issue by fcaldas** [GoogleCloudPlatform/google-cloud-python#3935]
Hi,

  We are using BigQuery as a backend for analytics and our main database is Google Datastore. Once a day we have a script that streams the latest updates from Datastore into BigQuery and we are noticing a massive number of duplicates after running the application for a few months:

    @staticmethod
    def saveToBigQuery(trademark_list):
        if(len(trademark_list) == 0):
            return
        tm_keys = []
        tm_docs = []
        bigquery_client = bigquery.Client()
        dataset = bigquery_client.dataset("uptodate")
        table = dataset.table("Trademarks")
        table.reload()

        for tm in trademark_list:
            if(tm is None):
                continue
            tm_keys.append(tm.key.id())
            tm_docs.append(tm.getBigQueryEntity())

        try:
            table.insert_data(tm_docs, row_ids=tm_keys)
            logging.debug(tm_keys)
        except Exception, e:
            logging.error("Error while inserting Trademarks in BigQuery: " + str(e))
            time.sleep(30)
            Trademark.saveToBigQuery(trademark_list)

On `google.cloud.bigquery.Table.insert_data.` we have:

    def insert_data(self,
                    rows,
                    row_ids=None,
                    skip_invalid_rows=None,
                    ignore_unknown_values=None,
                    template_suffix=None,
                    client=None):
        """API call:  insert table data via a POST request

        See
        https://cloud.google.com/bigquery/docs/reference/rest/v2/tabledata/insertAll

        :type rows: list of tuples
        :param rows: Row data to be inserted. Each tuple should contain data
                     for each schema field on the current table and in the
                     same order as the schema fields.

        :type row_ids: list of string
        :param row_ids: Unique ids, one per row being inserted.  If not
                        passed, no de-duplication occurs.

Assuming the `row_ids` for my entities are unique, there should not be any duplicates right?

**Comment by tswast** [comment]
`row_ids` only de-duplicate within the streaming buffer (from a few minutes up to 90 minutes), not once they are in the table.

It is documented at https://cloud.google.com/bigquery/streaming-data-into-bigquery#dataconsistency that BigQuery remembers `row_ids` for at least one minute.
