### ISSUE TITLE
Getting 401 errors after one hour of client usage

### ISSUE THREAD

**Issue by mikelambert** [GoogleCloudPlatform/google-cloud-python#3937]
So I was wrong at the bottom of https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3259 , this problem has not gone away for me. I'm starting a new Issue to track my particular problem here, instead of conflating things.

After my GAE Flex server (and datastore client) has been running for an hour, I get the following error message from my datastore usage (and the errors continue until I re-push my server and re-create clients):
```
Unauthorized: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
```

I am running `google-auth==1.0.2` and `google-cloud==0.27.0`, though it's the same error that's happened on older versions of this client.

The exact error is:
```
  File "/home/vmagent/app/services/ip_geolocation.py", line 47, in _get_cache
    obj = client.get(_dbkey(ip))
  File "/env/local/lib/python2.7/site-packages/google/cloud/datastore/client.py", line 309, in get
    deferred=deferred, transaction=transaction)
  File "/env/local/lib/python2.7/site-packages/google/cloud/datastore/client.py", line 356, in get_multi
    transaction_id=transaction and transaction.id,
  File "/env/local/lib/python2.7/site-packages/google/cloud/datastore/client.py", line 138, in _extended_lookup
    project, read_options, key_pbs)
  File "/env/local/lib/python2.7/site-packages/google/cloud/datastore/_gax.py", line 115, in lookup
    return super(GAPICDatastoreAPI, self).lookup(*args, **kwargs)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/env/local/lib/python2.7/site-packages/google/cloud/datastore/_gax.py", line 82, in _catch_remap_gax_error
    six.reraise(error_class, new_exc, sys.exc_info()[2])
  File "/env/local/lib/python2.7/site-packages/google/cloud/datastore/_gax.py", line 74, in _catch_remap_gax_error
    yield
  File "/env/local/lib/python2.7/site-packages/google/cloud/datastore/_gax.py", line 115, in lookup
    return super(GAPICDatastoreAPI, self).lookup(*args, **kwargs)
  File "/env/local/lib/python2.7/site-packages/google/cloud/gapic/datastore/v1/datastore_client.py", line 204, in lookup
    return self._lookup(request, options)
  File "/env/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 452, in inner
    return api_caller(api_call, this_settings, request)
  File "/env/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 438, in base_caller
    return api_call(*args)
  File "/env/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)
  File "/env/local/lib/python2.7/site-packages/google/gax/retry.py", line 127, in inner
    ' classified as transient', exception)
Unauthorized: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."   
```

The ip_geolocation.py code is [here](https://github.com/mikelambert/dancedeets-monorepo/blob/master/server/services/ip_geolocation.py) if you are curious. I basically construct a `datastore.Client('dancedeets-hrd')` at app startup, and re-use it on all requests thereafter. It works for an hour before getting it "breaks" and starts spewing 401s on every usage.

I had a previous workaround attempt, to construct a new client on every request. But this caused latency issues for me, as the overhead of the first db query seemed to take awhile.

I suppose the best workaround is to recreate the client everytime I time I get a 401, though obviously this feels like something the client should handle for me.

**Comment by mikelambert** [comment]
You can see a graph of my errors here, including the one-hour cessation of errors after I pushed:
<img width="1884" alt="2017-09-08 16 49 48" src="https://user-images.githubusercontent.com/7953259/30233436-9799dcf6-94c3-11e7-962e-ec7f2b571ed9.png">

**Comment by dhermes** [comment]
@mikelambert It's possible that or gRPC/GAX/GAPIC wrapper doesn't bubble up the exception in quite the right way, so the actually credential never gets refreshed.

/cc @jonparrott

**Comment by jonparrott** [comment]
Hrm. For gRPC and GCE-based credentials it should just pre-emptively refresh the credentials before they expire.

@mikelambert it'd be useful if you could print the credential's `expires` as well as `datetime.datetime.utcnow()` when this error occurs.

**Comment by mikelambert** [comment]
Okay, and by `expires`, I assume you mean `expiry`?

**Comment by jonparrott** [comment]
Yes. :)

(you'd think I'd know that considering I wrote it...)

**Comment by mikelambert** [comment]
It'll take an hour or so to get the results, but I'm assuming I will just discover that `expiry is None`. Is there anything else you'd like me to debug/print if that's true?

I'm running in GAE Flex with `python-compat` and `enable_app_engine_apis: true`. So not sure if that means I'm pulling from `auth/app_engine.py` or `auth/compute_engine/credentials.py`.

**Comment by jonparrott** [comment]
`expiry` shouldn't be None, both GAE and GCE both return the token lifetime.

> I'm running in GAE Flex with python-compat and enable_app_engine_apis: true. So not sure if that means I'm pulling from auth/app_engine.py or auth/compute_engine/credentials.py.

:O yikes. That should end up being `app_engine.py`.

**Comment by mikelambert** [comment]
Looks like you're right!

Instance 1:
```
utc:    2017-09-12 00:42:09.259202
expiry: 2065-05-24 01:05:08.266728
```

Instance 2:
```
utc:    2017-09-12 00:42:10.156797
expiry: 2065-05-24 01:05:18.414722
```

For instance 1's client:
```
{
  '_base_url': 'https://datastore.googleapis.com',
  '_batch_stack': <google.cloud._helpers._LocalStack object at 0x7fd595845ae0>,
  '_credentials': <google.auth.app_engine.Credentials object at 0x7fd59586a4d0>,
  '_datastore_api_internal': <google.cloud.datastore._gax.GAPICDatastoreAPI object at 0x7fd590b42d10>,
  '_http_internal': None,
  '_use_grpc': True
  'namespace': None,
  'project': u'dancedeets-hrd',
}
```

And instance 1's client credentials:
```
{
  '_scopes': ('https://www.googleapis.com/auth/datastore',),
  '_service_account_id': None,
  '_signer': <google.auth.app_engine.Signer object at 0x7fd5957f33d0>,
  'expiry': datetime.datetime(2065, 5, 24, 1, 5, 8, 266728)
  'token': 'XXX (let me know if you need it)',
}
```

**Comment by dhermes** [comment]
@mikelambert What's it like in the future? Is there still ice cream?

**Comment by jonparrott** [comment]
2065? What on Earth. There's the problem. I'm gonna see if I can track it
down, it's likely app engine is just returning it as a different unit than
what we expect.

**Comment by mikelambert** [comment]
@dhermes Do they have Dippin Dots back in your time? It's what we eat for ice cream every day. Sadly it makes for really messy ice cream sandwiches...

**Comment by lukesneeringer** [comment]
That looks like something is returning milliseconds instead of seconds.

**Comment by jonparrott** [comment]
I just tracked it down - app engine returns seconds since epoch and we are treating it as seconds from now. Easy fix. I'll grab it as soon as I can.

**Comment by mikelambert** [comment]
Awesome to hear! I appreciate you fixing my time machine so I can properly enjoy ice cream sandwiches again!

Slightly curious why I seem to have been the only one reporting this issue for so long in the original thread? Is it just that `google.cloud.datastore` isn't too popular on GAE given to the existence of DB/NDB? Or was I hitting a edge case by using long lived connections in a GAE environment?

**Comment by jonparrott** [comment]
These client libraries aren't support on App Engine standard (even though google-auth is), so it's just likely that no one is using this on standard. You're using `python-compat` so you're in the fun gray area. :)
