### ISSUE TITLE
__exit__ without further info when doanloading gzipped file

### ISSUE THREAD

**Issue by deepdad** [GoogleCloudPlatform/google-cloud-python#3939]
def download_blob(bucket_name, source_blob_name, destination_file_name):
    #Downloads a blob from the bucket.
    storage_client = storage.Client()
    bucket = storage_client.get_bucket(bucket_name)
    blob = bucket.blob(source_blob_name)
    print(bucket.exists(client=storage_client))
    print(bucket.get_blob(blob_name=source_blob_name))
    with open(destination_file_name, 'wb') as file_obj:
        blob.download_to_file(file_obj=file_obj)
    #blob.download_to_filename(destination_file_name)

    print('Blob {} downloaded to {}.'.format(
        source_blob_name,
        destination_file_name))

download_blob('test-ml-storage', 'deepdad/sample.tar.gz', './sample.tar.gz')

AttributeErrorTraceback (most recent call last)
<ipython-input-55-3365475d0a28> in <module>()
     20         destination_file_name))
     21 
---> 22 download_blob('test-ml-storage', 'deepdad/sample.tar.gz', './sample.tar.gz')

<ipython-input-55-3365475d0a28> in download_blob(bucket_name, source_blob_name, destination_file_name)
     13     print(bucket.get_blob(blob_name=source_blob_name))
     14     with open(destination_file_name, 'wb') as file_obj:
---> 15         blob.download_to_file(file_obj=file_obj)
     16     #blob.download_to_filename(destination_file_name)
     17 

/opt/conda/envs/py27/lib/python2.7/site-packages/google/cloud/storage/blob.pyc in download_to_file(self, file_obj, client)
    462 
    463         try:
--> 464             self._do_download(transport, file_obj, download_url, headers)
    465         except resumable_media.InvalidResponse as exc:
    466             _raise_from_invalid_response(exc)

/opt/conda/envs/py27/lib/python2.7/site-packages/google/cloud/storage/blob.pyc in _do_download(self, transport, file_obj, download_url, headers)
    416         if self.chunk_size is None:
    417             download = Download(download_url, stream=file_obj, headers=headers)
--> 418             download.consume(transport)
    419         else:
    420             download = ChunkedDownload(

/opt/conda/envs/py27/lib/python2.7/site-packages/google/resumable_media/requests/download.pyc in consume(self, transport)
     99 
    100         if self._stream is not None:
--> 101             self._write_to_stream(result)
    102 
    103         return result

/opt/conda/envs/py27/lib/python2.7/site-packages/google/resumable_media/requests/download.pyc in _write_to_stream(self, response)
     60             response (~requests.Response): The HTTP response object.
     61         """
---> 62         with response:
     63             body_iter = response.iter_content(
     64                 chunk_size=_SINGLE_GET_CHUNK_SIZE, decode_unicode=False)

AttributeError: __exit__

**Comment by dhermes** [comment]
@deepdad Sorry this issue occurred for you. See #3841 for an explanation of why it's happening.

Simply upgrade to `requests >= 0.18.0` and the error will be resolved.

**Comment by ryancbuckley** [comment]
Hi there,
I seem to be seeing a similar error with gzipped files, despite having an up-to-date `requests`.

The error:
```python
>>> from google.cloud import storage
>>> gcs_client = storage.client.Client(myproj)
>>> bucket = gcs_client.bucket(bucket_name)
>>> for blob in bucket.list_blobs(prefix='idk'): x = blob.download_as_string()
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/name/.virtualenvs/newenv/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 502, in download_as_string
    self.download_to_file(string_buffer, client=client)
  File "/Users/name/.virtualenvs/newenv/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 464, in download_to_file
    self._do_download(transport, file_obj, download_url, headers)
  File "/Users/name/.virtualenvs/newenv/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 418, in _do_download
    download.consume(transport)
  File "/Users/name/.virtualenvs/newenv/lib/python2.7/site-packages/google/resumable_media/requests/download.py", line 101, in consume
    self._write_to_stream(result)
  File "/Users/name/.virtualenvs/newenv/lib/python2.7/site-packages/google/resumable_media/requests/download.py", line 62, in _write_to_stream
    with response:
AttributeError: __exit__
```

Below is the output of `pip freeze`:
```
cachetools==2.0.1
certifi==2017.7.27.1
chardet==3.0.4
dill==0.2.7.1
enum34==1.1.6
future==0.16.0
futures==3.1.1
gapic-google-cloud-datastore-v1==0.15.3
gapic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3
gapic-google-cloud-pubsub-v1==0.15.4
gapic-google-cloud-spanner-admin-database-v1==0.15.3
gapic-google-cloud-spanner-admin-instance-v1==0.15.3
gapic-google-cloud-spanner-v1==0.15.3
google-auth==1.0.2
google-cloud==0.27.0
google-cloud-bigquery==0.26.0
google-cloud-bigtable==0.26.0
google-cloud-core==0.26.0
google-cloud-datastore==1.2.0
google-cloud-dns==0.26.0
google-cloud-error-reporting==0.26.0
google-cloud-language==0.27.0
google-cloud-logging==1.2.0
google-cloud-monitoring==0.26.0
google-cloud-pubsub==0.27.0
google-cloud-resource-manager==0.26.0
google-cloud-runtimeconfig==0.26.0
google-cloud-spanner==0.26.0
google-cloud-speech==0.28.0
google-cloud-storage==1.3.2
google-cloud-translate==1.1.0
google-cloud-videointelligence==0.25.0
google-cloud-vision==0.26.0
google-gax==0.15.14
google-resumable-media==0.2.3
googleapis-common-protos==1.5.2
grpc-google-iam-v1==0.11.1
grpcio==1.6.0
httplib2==0.10.3
idna==2.6
monotonic==1.3
oauth2client==3.0.0
ply==3.8
proto-google-cloud-datastore-v1==0.90.4
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3
proto-google-cloud-pubsub-v1==0.15.4
proto-google-cloud-spanner-admin-database-v1==0.15.3
proto-google-cloud-spanner-admin-instance-v1==0.15.3
proto-google-cloud-spanner-v1==0.15.3
protobuf==3.4.0
pyasn1==0.3.4
pyasn1-modules==0.1.4
requests==2.18.4
rsa==3.4.2
six==1.10.0
src==1.0
tenacity==4.4.0
urllib3==1.22
```

Thank you

**Comment by deepdad** [comment]
#3841 has no explanation and requests is up to date

​import requests
print (requests.__version__)

2.14.2

**Comment by dhermes** [comment]
Sorry, I mistyped, the minimum version is `2.18.0`, not `0.18.0`. "Up-to-date" would be the [latest version][1] on PyPI right now (`2.18.4`).

Sorry for the lack of information in #3841, I had to click my way through to find the real issue (#3736).

The issue is caused by [using][2] a `requests.Response` object as a context manager.

[1]: https://pypi.org/project/requests/2.18.4/
[2]: https://github.com/GoogleCloudPlatform/google-resumable-media-python/blob/0.2.3/google/resumable_media/requests/download.py#L62

**Comment by deepdad** [comment]
thank you
