### ISSUE TITLE
copy to reopen __exit__ without further info when downloading gzipped file #3939

### ISSUE THREAD

**Issue by deepdad** [GoogleCloudPlatform/google-cloud-python#3940]
#3841 has no explanation and requests is up to date, I can't reopen that issue

​import requests
print (requests.version)

2.14.2

I don't have access permissions to the Google Cloud, just through some IPython notebooks, so the trace is all I can see. The error also occurs with binary data files
In fact that may be the poblem, that I do not have storage.objects.get access to object my-data-test-bucket/ts.5year/5c/5c90dc6b6fc0207d.bin.
Although, I can print met data and check the blob and bucket through bucket.exists and bucket.get_blob: does it throw any permissions exceptions?
Or else, do I need to format the slashes in the blob name?

blob_metadata('my-data-test-bucket', 'ts.5year/5c/5c90dc6b6fc0207d.bin')

Blob: ts.5year/5c/5c90dc6b6fc0207d.bin
Bucket: my-data-test-bucket
Storage class: REGIONAL
ID: machina-data-test-bucket/ts.5year/5c/5c90dc6b6fc0207d.bin/1499701351330529
Size: 3907680 bytes
Updated: 2017-07-10 15:42:31.320000+00:00
Generation: 1499701351330529
Metageneration: 1
Etag: COHlwvKG/9QCEAE=
Owner: None
Component count: None
Crc32c: MNc7Ew==
md5_hash: NFfBComp7fHP/5b31dgu5g==
Cache-control: None
Content-type: application/octet-stream
Content-disposition: None
Content-encoding: None
Content-language: en
Metadata: None

def download_blob(bucket_name, source_blob_name, destination_file_name):
#Downloads a blob from the bucket.
storage_client = storage.Client()
bucket = storage_client.get_bucket(bucket_name)
blob = bucket.blob(source_blob_name)
print(bucket.exists(client=storage_client))
print(bucket.get_blob(blob_name=source_blob_name))
with open(destination_file_name, 'wb') as file_obj:
blob.download_to_file(file_obj=file_obj)
#blob.download_to_filename(destination_file_name)

print('Blob {} downloaded to {}.'.format(
    source_blob_name,
    destination_file_name))

download_blob('test-ml-storage', 'deepdad/sample.tar.gz', './sample.tar.gz')

AttributeErrorTraceback (most recent call last)
in ()
20 destination_file_name))
21
---> 22 download_blob('test-ml-storage', 'deepdad/sample.tar.gz', './sample.tar.gz')

in download_blob(bucket_name, source_blob_name, destination_file_name)
13 print(bucket.get_blob(blob_name=source_blob_name))
14 with open(destination_file_name, 'wb') as file_obj:
---> 15 blob.download_to_file(file_obj=file_obj)
16 #blob.download_to_filename(destination_file_name)
17

/opt/conda/envs/py27/lib/python2.7/site-packages/google/cloud/storage/blob.pyc in download_to_file(self, file_obj, client)
462
463 try:
--> 464 self._do_download(transport, file_obj, download_url, headers)
465 except resumable_media.InvalidResponse as exc:
466 _raise_from_invalid_response(exc)

/opt/conda/envs/py27/lib/python2.7/site-packages/google/cloud/storage/blob.pyc in _do_download(self, transport, file_obj, download_url, headers)
416 if self.chunk_size is None:
417 download = Download(download_url, stream=file_obj, headers=headers)
--> 418 download.consume(transport)
419 else:
420 download = ChunkedDownload(

/opt/conda/envs/py27/lib/python2.7/site-packages/google/resumable_media/requests/download.pyc in consume(self, transport)
99
100 if self._stream is not None:
--> 101 self._write_to_stream(result)
102
103 return result

/opt/conda/envs/py27/lib/python2.7/site-packages/google/resumable_media/requests/download.pyc in _write_to_stream(self, response)
60 response (~requests.Response): The HTTP response object.
61 """
---> 62 with response:
63 body_iter = response.iter_content(
64 chunk_size=_SINGLE_GET_CHUNK_SIZE, decode_unicode=False)

AttributeError: exit

**Comment by deepdad** [comment]
sorry, seems to be a permissions result

**Comment by dhermes** [comment]
See my comment: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3939#issuecomment-328362875

**Comment by deepdad** [comment]
thank you, I will ask the admin to update it
the file was not downloaded, just created
