### ISSUE TITLE
google.cloud.datastore Hanging During Iteration After Dockerfile Update

### ISSUE THREAD

**Issue by speedplane** [GoogleCloudPlatform/google-cloud-python#3946]
The datastore library hangs while iterating through results obtained using the `fetch` function. 

This started occuring after I rebuilt my app's Docker image from scratch by adding a new base package. This caused the whole Dockerfile to rebuild, likely causing several packages to update. It's possible that in this time the datastore API changed or perhaps there is a versioning issue on my part. Any assistance would be appreciated.

My Dockerfile in relevant parts contains the following:

```
FROM library/ubuntu:xenial
# I added this line towards the top of my Dockerfile, which caused everything to rebuild.
RUN apt-get -y install tor
# ... then everything after it rebuilt...
RUN pip install google-cloud
# Install and Configure Google Cloud SDK
RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
  echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
  curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
  apt-get update && apt-get install -y google-cloud-sdk
```

The code I am executing is relatively straightforward:
```
# ... Setup query ...
results = query.fetch(limit = 0, offset = 0)
# Hangs on this line
for entity in results:
            # Never reaches this line
            key = entity if isinstance(entity, datastore.key.Key) else \
# Never completes loop.
```
Any idea why the iterator would hang? 

A few additional potentially relevant points:
* I'm using the `GCD_DATASET` environment variable to target a project other than the project this is running on. 
* I am running within a `celery` scheduler. When I run these commands from the command line outside of this scheduler, it works just fine.
* `google.cloud.datastore.__version_` = `1.2.0`
* `google.cloud.datastore` = `<module 'google.cloud.datastore' from '/usr/local/lib/python2.7/dist-packages/google/cloud/datastore/__init__.pyc'>`

**Comment by lukesneeringer** [comment]
You are actually the second person that mentioned an issue with celery in the past week (the other was in email), but they provided a [repro case](https://github.com/mlucas-NU/celery_issue) that I have been intending to look into.

Could you do me a favor and downgrade `grpcio` from 1.6.0 to 1.4.x and tell me if that fixes the problem? That was one of the solutions that was discussed in the email chain I was on, but I have yet to get a solid yes or no on it. And, could you let me know if it helps or not?

**Comment by lukesneeringer** [comment]
P. S. This is a model case for a good bug report. Thanks.

**Comment by speedplane** [comment]
I will try doing just that. In the meantime, I was able to pull the old working Docker image from the container registry, and using `pip freeze` did a diff on the packages in the older (working) and the newer (broken) system. A screenshot of the diff is below. Indeed, `grpcio` was upgraded from 1.4.0 to 1.6.0 (as well as a lot of other packages).

![image](https://user-images.githubusercontent.com/671052/30382411-04d902f4-986d-11e7-8c76-495805ac9fd8.png)

**Comment by speedplane** [comment]
Just tried downgrading `grpcio` to 1.4.0, that fixed it.

**Comment by nathanielmanistaatgoogle** [comment]
(This smells like [issue 12455](https://github.com/grpc/grpc/issues/12455); do you think that it is?)

**Comment by lukesneeringer** [comment]
@nathanielmanistaatgoogle Yes, that is exactly what I think it is. :-)

**Comment by lukesneeringer** [comment]
@nathanielmanistaatgoogle grpc/grpc#12455 and grpc/grpc#12489 are likely to be duplicates. The latter has a lot of useful information lacking in the former.
