### ISSUE TITLE
Spanner should know how to merge chunk data of TIMESTAMP and DATE type

### ISSUE THREAD

**Issue by yixizhang** [GoogleCloudPlatform/google-cloud-python#3981]
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/spanner/google/cloud/spanner/streamed.py#L300

The dict doesn't cover `type_pb2.TIMESTAMP` and `type_pb2.DATE`, the fix is actually easy because both type is passed in string_value.

**Comment by vkedia** [comment]
Thanks for filing this. This indeed looks like a bug.
@tseaver @lukesneeringer please take a look.
