### ISSUE TITLE
Is Google Cloud Storage required for the asynchronous transcriptions?

### ISSUE THREAD

**Issue by NathanWailes** [GoogleCloudPlatform/google-cloud-python#3987]
I want to get the word time offsets for audio files that are longer than one minute (as described [here](https://cloud.google.com/speech/docs/async-time-offsets)), and when reading the docs it said *"Use asynchronous speech recognition to recognize audio that is longer than a minute and stored in Google Cloud Storage."* [Source](https://cloud.google.com/speech/docs/async-recognize)

It sounds like that means that using Google Cloud Storage is required. Is that right?

**Comment by tseaver** [comment]
@NathanWailes You can pass either the audio content or the URI when constructing the `RecognitionAudio` instance passed to `Client.long_running_recognize`.
