### ISSUE TITLE
Documentation Unclear: "If the property is not set locally, returns None."

### ISSUE THREAD

**Issue by speedplane** [GoogleCloudPlatform/google-cloud-python#3989]
The [Google Storage Blob documentation](https://googlecloudplatform.github.io/google-cloud-python/latest/storage/blobs.html) says that almost all properties return the value `None` if the "property is not set locally." However, there is no documentation explaining how properties are set/unset locally or when that occurs. 

This is confusing, there should be a preamble explaining when local Blob properties are set locally.

### Motivation

I ran into this because I started seeing some of these values return `None` in my project in unexpected circumstances (there may be another bug there), but when I went to the documentation, it did not shed much light on why or when these properties should be returning `None`.

**Comment by laldonza** [comment]
It happens to me that all the blob properties return `None`, except if I call the method `update()` first, then I've got the whole properties set (`updated` property is set to actual `datetime`), but this properties are accessible only during the execution.

**Comment by tseaver** [comment]
@laldonza the behavior you are seeing is by design:  the blob instance does not make an API request to load the property values implicitly.

**Comment by laldonza** [comment]
@tseaver Ok, thanks for the explanation. What about the `updated` property? It gets the time when the `update()` method is called, wouldn't be better to be the last_modified time?

**Comment by tseaver** [comment]
@laldonza `Blob.updated` is fetched from the JSON resource returned by the server.  If the blob has never loaded that resource (newly constructed instance, no `reload` or other API call made), its `updated` property returns `None`, like most of the others based on the JSON resource.
