### ISSUE TITLE
gRPC connection pool

### ISSUE THREAD

**Issue by garye** [GoogleCloudPlatform/google-cloud-python#4002]
I'm interested in adding a gRPC connection pool to the Bigtable client. In the Go client, we implement this using the client-side load balancing infrastructure of gRPC . Is this accessible via python? Alternatively, do you have any better ideas for how to add this feature?

**Comment by garye** [comment]
FWIW [this](https://github.com/google/google-api-go-client/blob/master/internal/pool.go) is what we do in Go.

**Comment by nathanielmanistaatgoogle** [comment]
I believe client-side load balancing will become available at some point in gRPC Python, but because it's another feature to be inherited from the gRPC Core rather than implemented in Python I have less of a handle on it. @markdroth, do you have more knowledge of the time frame?

**Comment by hsaliak** [comment]
Is a round_robin policy, configured via service config not sufficient for this?
https://github.com/grpc/grpc/blob/master/doc/service_config.md
/cc @nathanielmanistaatgoogle @markdroth

**Comment by chemelnucfin** [comment]
Hello, feature requests will now be tracked in the project [Feature Requests](https://github.com/GoogleCloudPlatform/google-cloud-python/projects/5#card-6867160) linked.  I will close this issue now, please feel free to continue to address any issues/concerns here.

**Comment by markdroth** [comment]
Sorry, I didn't notice this earlier.

FYI, the client-side LB policy is settable via a channel arg, not just via the service config.

**Comment by keeth** [comment]
I was wondering about this too.  The BigTable docs state:

> Some Cloud Bigtable client libraries let you configure the number of gRPC channels in a client's connection pool, also known as a channel pool.

> The number of connections in each pool is configurable in your code only when you use the Go, C++, or Java client libraries for Cloud Bigtable.

Is this on the roadmap for the Python client?
