### ISSUE TITLE
Bigtable / happybase usage from a background thread.

### ISSUE THREAD

**Issue by subusc** [GoogleCloudPlatform/google-cloud-python#4005]
Folks,

  I have an issue with happbase/bigtable client usage in GCE. I have reproed the same in the following script - could one of you please take a look? This is blocking our fleet from talking to BigTable. 

  FWIW the script runs fine as far as the scan from current thread (The base table has two rows that match if it matters). Right afterwards when I try to run it from a background thread (pool) using map, this hangs for ever.

  Let me know if you need more details! 

NOTE: The issue could be something basic in my python as well, am not well versed there. Thx for the time! 

Thanks, Subu

---
```
import os
import sys
import time
from multiprocessing import Pool
from google.cloud import bigtable
from google.cloud import happybase

def _scan_table(t):
  print ("_scan_table: %s" % t)

  start_key = "local"
  end_key = "myLast"

  print ("_scan_table, start_key: %s, end_key: %s" % (start_key, end_key))

  btClient = bigtable.Client(project="<PROJECTID>",admin=True)
  instance = btClient.instance("<INSTANCEID>")
  client = happybase.Connection(table_prefix="test",instance=instance)

  print ("_scan_table: starting scan")
  rows = []
  for row in client.table(t['name']).scan(row_start=start_key,
                                         row_stop=end_key):
    print("_scan_table, row: %s from table %s" % (row, t['name']))
    rows.append(row)

  print("_scan_table: done")
  return rows


table_config = [{'name' : "tblSuffix"}]

print("SUBU: fetch, table_Config: %s" % table_config)

results = []
for t in table_config:
  results.append(_scan_table(t))
print results

print "SUBU: Trying pool - HANGS after this"
threads = Pool(4)
threadResults = threads.map(_scan_table, table_config)
threads.close()
threads.join()
print threadResults
```
---
1. OS type and version: Ubuntu 14.04.5 LTS
2. Python version and virtual environment information `python --version`
Python 2.7.6
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`

google-auth==1.1.0
google-cloud-bigtable==0.26.0
google-cloud-core==0.26.0
google-cloud-happybase==0.26.0
google-compute-engine==2.4.1
google-gax==0.15.14
googleapis-common-protos==1.5.2

4. Stacktrace if available
5. Steps to reproduce
6. Code example
See repro above.

**Comment by dhermes** [comment]
@subusc Could you also provide your version of `grpcio`?

**Comment by subusc** [comment]
grpcio==1.6.0 @dhermes  thx.

**Comment by dhermes** [comment]
@subusc Can you trying pinning to an earlier version of `grpcio` (e.g. `grpcio==1.4.0`)? We've had reports that `grpcio==1.6.0` is breaking `multiprocessing`.

**Comment by subusc** [comment]
Oh my that was indeed the issue, it worked! Thanks again!

**Comment by dhermes** [comment]
FYI @nathanialmanistaatgoogle @lukesneeringer another one here.

Sorry for the problem @subusc, we hope to be able to get it resolved so you don't need to worry about the dependencies of your dependencies!

**Comment by lukesneeringer** [comment]
I hereby coin the term "grand-dependencies".
