### ISSUE TITLE
datastore.Batch doesn't have get method

### ISSUE THREAD

**Issue by pdknsk** [GoogleCloudPlatform/google-cloud-python#4007]
I noticed when I tried this.
```Python
with client.transaction() as transaction:
  item = transaction.get(key)
  item['key'] = value
  transaction.put(item)
```
I know `client.get` works, but couldn't help notice that all languages operate on a `transaction` object in the [documentation examples](https://cloud.google.com/datastore/docs/concepts/transactions#datastore-transactional-update-python), with the exception of *Python*.

**Comment by chemelnucfin** [comment]
Hello, feature requests will now be tracked in the projects linked in the above.  I will close this issue now, please feel free to continue to address any issues/concerns here.
