### ISSUE TITLE
Some API documentation is blank (PubSub, Datastore, others)

### ISSUE THREAD

**Issue by robhaswell** [GoogleCloudPlatform/google-cloud-python#4017]
Some of the API documentation pages are blank:

* http://google-cloud-python.readthedocs.io/en/latest/pubsub/publisher/api/client.html
* http://google-cloud-python.readthedocs.io/en/latest/pubsub/subscriber/api/client.html
* http://google-cloud-python.readthedocs.io/en/latest/datastore/client.html
* http://google-cloud-python.readthedocs.io/en/latest/monitoring/client.html

This makes it time consuming to develop with this SDK as one must drop into a `pdb` and inspect the objects you have in your hand.

**Comment by dhermes** [comment]
Thanks for letting us know @robhaswell, that certainly is not the intention, it seems something is going wrong with our Read the Docs build.

Check out our `gh-pages` version of the docs:
https://googlecloudplatform.github.io/google-cloud-python/latest/pubsub/publisher/api/client.html

/cc @lukesneeringer

**Comment by tseaver** [comment]
Those pages are all rendering correctly now.  Please feel free to reopen if you discover any others.
