### ISSUE TITLE
autodetect schema parameter in Table.upload_from_file

### ISSUE THREAD

**Issue by aovlexus** [GoogleCloudPlatform/google-cloud-python#4024]
I think it's necessary to add parameter autodetect_chema to function upload_from_file of Table class, this is done by writing corresponding parameter to the matadata dict in this function. But I do not have enough experience to write this code in accordance with the project architecture and tests for this function.

**Comment by tseaver** [comment]
@aovlexus Thanks for the report!  @tswast is in the middle of a redesign of the API, which should accomplish your goal.

**Comment by tswast** [comment]
Fixed by https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4136 where the load function now takes an optional `job_config` parameter, where this property can be populated.

To be merged to master in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4245.
