### ISSUE TITLE
Spelling Error (_medical_likeliehood)

### ISSUE THREAD

**Issue by jnhasty** [GoogleCloudPlatform/google-cloud-python#4058]
_medical_likeliehood -> _medical_likelihood

https://github.com/GoogleCloudPlatform/google-cloud-python/blob/b28a4eb667ae08c3f4dcf9af891ed4931884989c/vision/google/cloud/vision/safe_search.py#L43

**Comment by tseaver** [comment]
@jnhasty Thank you for the report!
