### ISSUE TITLE
Use POST with Translate API

### ISSUE THREAD

**Issue by ppawiggers** [GoogleCloudPlatform/google-cloud-python#4062]
I try to translate a piece of text that's more than 2000 characters. The limit of a GET request to the translate API is 2000 characters. So my idea was to POST instead of GET, but that does not seem to be configurable, see https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/translate/google/cloud/translate_v2/client.py#L234 .

Is it possible to use POST with Translate?

**Comment by tseaver** [comment]
Thanks for the report.  According to the [REST API docs](https://cloud.google.com/translate/docs/reference/translate), the `translate` API is *supposed* to be invoked with `POST`:  I am surprised that it works at all with `GET`.

However, that same API doc requires that all parameters to the `translate` method be passed in the query string, which means that the limit is probably not any different for `POST`.

**Comment by lukesneeringer** [comment]
This seems to be a limitation of the underlying API. There is not really anything the client libraries can do about this. Sorry. :-(

**Comment by dhermes** [comment]
@tseaver Have you tried sending the query parameters in the body?

**Comment by tseaver** [comment]
@lukesneeringer Our implementation is still contra-spec (sending a `GET` vs a `POST` request).

**Comment by tseaver** [comment]
@dhermes I haven't poked at anything:  I just looked at the [`translate` API docs](https://cloud.google.com/translate/docs/reference/translate), which mandate query parameters and a body-less `POST` (absurd, I know).

**Comment by ppawiggers** [comment]
It now uses POST, but still sending the parameters in the URL, so it's now useful. Second, now I sometimes get this error:

    <p>POST requests require a <code>Content-length</code> header.  <ins>That’s all we know.</ins>

I think POST is only useful if we send the data in the body, not as query parameters.

**Comment by dhermes** [comment]
@ppawiggers Do you sometimes get that error in a stacktrace? Is it with a query that succeeds sometimes?

**Comment by ppawiggers** [comment]
@dhermes , wat I usually to is limit the string that needs to be translated to 1000 chars:

    s = "Hallo ik kom uit Nederland"  # Dutch for 'Hello, I'm from the Netherlands'
    client.translate(s[:1000])

This works fine. The error occurs when I try to translate a longer Chinese text. I think the issue is that a Chinese characters converts to a string consisting of ASCII characters, where every Chinese characters converts to multiple ASCII characters. The 1000-character limitation is performed on the original string, and thus way longer in the query sent to Google. Limiting the `unquote`'d string on 1000 characters seems to work:

    # This can fail; a Chinese 100-character string becomes way longer when `unquote`'d:
    body = "chinese string here"[:1000]
    client.translate(body)

    # This works
    body = unquote(quote("chinese string here")[:1000])
    client.translate(body)

So I think the issue was that a 1000-character limited Chinese string converts to a string that exceeds the maximum limit for a URL. Hence the need to POST the string in the body instead of the URL.

**Comment by ppawiggers** [comment]
@dhermes can this issue be re-opened?
