### ISSUE TITLE
projects.models.versions.setDefault() requires empty body parameter

### ISSUE THREAD

**Issue by rasmi** [GoogleCloudPlatform/google-cloud-python#4063]
When calling [projects.models.versions.setDefault](https://cloud.google.com/ml-engine/reference/rest/v1/projects.models.versions/setDefault):
```
credentials = GoogleCredentials.get_application_default()
ml = discovery.build('ml', 'v1', credentials=credentials)
ml.projects().models().versions().setDefault(
        name=model_version,
        body={} # Must be set, even if empty.
    )
```
It seems that body must be passed even if it is empty. In other methods, body is simply omitted if it is not required, but in setDefault, omitting the body parameter gives an error:
```
/Projects/pythonenv/lib/python3.6/site-packages/googleapiclient/discovery.py in method(self, **kwargs)
    734         if name not in _PAGE_TOKEN_NAMES or _findPageTokenName(
    735             _methodProperties(methodDesc, schema, 'response')):
--> 736           raise TypeError('Missing required parameter "%s"' % name)
    737 
    738     for name, regex in six.iteritems(parameters.pattern_params):

TypeError: Missing required parameter "body"
```

**Comment by dhermes** [comment]
@rasmi You're looking for https://github.com/google/google-api-python-client

Sorry for the confusion. Let us know if there's anything else we can help with.

**Comment by rasmi** [comment]
Thanks! Issue has been reported already here: https://github.com/google/google-api-python-client/issues/416
