### ISSUE TITLE
NDB JsonProperty and Cloud Datastore library compatibility

### ISSUE THREAD

**Issue by cpavon** [GoogleCloudPlatform/google-cloud-python#4077]
I have code running on Standar GAE using NDB and code running in flexible env using google cloud datastore library. Both accessing to the same entities.

I have problems dealing with ndb.JsonProperty. As far as I read those properties are stored as blob, so I tried to simulate that property using cloud library. Before store the value I do the following:

```
value_to_store = json.dumps(value)
value_to_store = base64.b64encode(value_to_store)
```
And the opposite when I read a property:
```
read_value = base64.b64decode(from_db_value)
read_value = json.loads(read_value)
```

Everything works fine in this situations:
  - Insert using NDB --->  Read using Cloud Library
  - Insert using Cloud Library ---> Read using Cloud Library

But fails when:
  - Insert using Cloud Library --> Read using NDB

What's the right way to store those kind of properties to make them compatibles with NDB?

**Comment by cpavon** [comment]
Ok, it seems that the value inserted using Cloud Library is saved as String while the one inserted using NDB is a Blob.

So I just need to figure out how to store the value as Blob using cloud datastore library

**Comment by dhermes** [comment]
@cpavon Sorry for the confusion. We upload as bytes if the type is `bytes` (also `str` in Python 2) and as unicode/string if the type is `unicode` (which is `str` in Python 3).

In Python 2, the default string literal `'abc'` is `bytes` but in Python 3 it's unicode. If you want a consistent bytes literal, use `b'abc'` and if you want a consistent unicode literal, use `u'abc'` or `from __future__ import unicode_literals` at the top of your modules.

**Comment by dhermes** [comment]
@cpavon Note the return types of `json.dumps` and `base64.b64encode` in Python 2 and 3:

```
$ python2
>>> import base64
>>> import json
>>> d = json.dumps({})
>>> d
'{}'
>>> (d, type(d))
('{}', <type 'str'>)
>>> s = base64.b64encode(d)
>>> (s, type(s))
('e30=', <type 'str'>)
```

vs.

```
$ python3
>>> import base64
>>> import json
>>> d = json.dumps({})
>>> (d, type(d))
('{}', <class 'str'>)
>>> s = base64.b64encode(d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
>>> s = base64.b64encode(d.encode('ascii'))
>>> (s, type(s))
(b'e30=', <class 'bytes'>)
```

**Comment by cpavon** [comment]
Thanks @dhermes 
I'm working with python2 so it seems that just removing the base64 encoding/decoding the value is stored as blob and NDB is reading the value without problems.

**Comment by dhermes** [comment]
That's correct.
