### ISSUE TITLE
Install broken due to dependency on tenacity/pbr

### ISSUE THREAD

**Issue by mixmastamyk** [GoogleCloudPlatform/google-cloud-python#4080]
The install bug does not appear in this lib but in a dependency, this is just a courtesy issue to inform.  Going back to "gcloud" does work in the meantime.

- ImportError: No module named 'tasks'
- Py 3.5
- Ubuntu Zesty

Details:

- https://github.com/jd/tenacity/issues/90

**Comment by mixmastamyk** [comment]
I was able to get past this by removing cli_helpers:

    ⏵ sudo -H pip3.5 uninstall cli_helpers

**Comment by dhermes** [comment]
Thanks for closing, it seems unrelated to the current version of this library.
