### ISSUE TITLE
pubsub: streaming pull needs keepalive

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-python#4083]
With default configuration, streaming pull will hang if the stream is idle for a few minutes. This usually happens when the subscription has no more messages. In Go, we set gRPC keepalive to 5 minutes [(CL)](https://code-review.googlesource.com/#/c/gocloud/+/17070/). A similar option should be available in Python, though I'm not sure what the code to pass in the option looks like.

**Comment by lukesneeringer** [comment]
Does the stream _hang_ or _drop_? If the stream drops, we do not care.

**Comment by pongad** [comment]
I'm not certain what the differences between "hang" and "drop" are, but I'll describe the symptoms in more detail.

In both Java and Go (and probably others) without keepalive, the stream just never give us new message or notify us of any errors.
In Java, where we give gRPC callbacks (`onNext`, `onError`, and `onCompleted`) to handle events, none of the callbacks are ever called.
In Go, where we call `msg, err = stream.Recv()` the method never returns, giving us neither messages nor errors.

With keepalive configured, we'll eventually get an error (from experience, either `UNAVAILABLE` or `INTERNAL`) and then we can re-create the stream.

**Comment by makrusak** [comment]
I have the same problem with latest python pub/sub library.
If there are no new messages on topic during 2-3 minutes, all hangs and callback doesn't trigger more.
I'm searching for solution

**Comment by makrusak** [comment]
@lukesneeringer Still have problem with a hanging connection. Few minutes after starting the subscriber it stops producing any "debug" logs (in case of absence of messages).
You can view all debug logs here:
https://pastebin.com/wCCCh5Fy
