### ISSUE TITLE
GCS notification convenience methods, pubsub dependency

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#4097]
In #4021, @BrandonY asked for convenience wrapprer(s) for the following:

- Create the user-supplied topic
- Set the appropriate IAM policy needed to support bucket notifications
- Create a subscription to the topic

Adding this support would make `storage` depend on `pubsub` (at least optionally), and would complicate our testing story (system tests already add it).  Ruby just documents what is required.

@danoscarmike, @lukesneeringer nominated you as the arbitrator for the issue.

**Comment by BrandonY** [comment]
Without this convenience function, everyone who wants to use notifications will have to write a function that invokes around 4 calls:

* Call GCS to request the name of the appropriate permission for your GCS bucket.
* Call Pub/Sub to create a topic
* Call Pub/Sub's IAM interface to add publish permission to the robot that was the response to the first RPC.
* Call GCS to add notifications to a bucket.

With a convenience method, the whole thing can be shortened to `bucket.sendNotifications(topic)`.

**Comment by danoscarmike** [comment]
Ack.  @BrandonY I'll reach out to you offline.

**Comment by lukesneeringer** [comment]
This was decided. We are not doing it.
