### ISSUE TITLE
Firestore: Use simple types for cursors

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#4109]
i.e.

```python
db = firestore.Client()
query = db.collection('cities').order_by('population').start_at(1000000)
```

rather than the current

```python
db = firestore.Client()
query = db.collection('cities').order_by('population').start_at({'population': 1000000})
```

/cc @samtstern @jonparrott

**Comment by dhermes** [comment]
If I was to implement this I could, by accepting `*values` and then making sure either

1. `len(values) == len(self._orders)`
1. `len(values) <= len(self._orders)`

then we could just match each value with the corresponding order. It's documented that subsequent calls to `start_at()` just **RESET** the start point wholesale (and `start_after()` also wipes it, and similar for `end_before()` / `end_at()`).

Also the question would be if we should still accept a dictionary or `DocumentSnapshot` (which IMO is a "saner" interface). @jonparrott indicates yes.

----

From @samtstern:

Cursors can be on multiple fields but you have to specify each one.  Here are some Android snippets to demonstrate:

```java
// Will return all Springfields
db.collection("cities")
        .orderBy("name")
        .orderBy("state")
        .startAt("Springfield");

// Will return "Springfield, Missouri" and "Springfield, Wisconsin"
db.collection("cities")
        .orderBy("name")
        .orderBy("state")
        .startAt("Springfield", "Missouri");
```

**Comment by schmidt-sebastian** [comment]
Firestore should also accept DocumentSnapshot cursors similar to https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2768

**Comment by chemelnucfin** [comment]
I'm going to put this in the back log for now and track it through here:
[Feature Requests](https://github.com/GoogleCloudPlatform/google-cloud-python/projects/5#card-6867156)

**Comment by schmidt-sebastian** [comment]
@chemelnucfin I don't see an issue for DocumentSnapshot cursors. The issue that I see in `Feature Request` (https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4109) cleans up the cursor API, which is a precursor for GoogleCloudPlatform/google-cloud-java#2768
