### ISSUE TITLE
Consider adding a `desc` or `descending` keyword argument to `Query.order_by`

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#4110]
From Google internal bug 65127895 (intentionally not providing a URL).

----

Currently the sort order should be specified as a string:

```python
query = cities_ref.order_by('name', direction='DESCENDING').limit(3)
```

This is error prone, since a user may make a typo while typing the
string out. The following would be much simpler:

```python
cities_ref.order_by('name', desc=True)
```

We (the Firestore team) don't have a strong opinion on this. Note that the Java SDK uses an Enum, the JS SDK uses the string and the iOS SDK uses a boolean. So feel free to do what you think is more idiomatic.

/cc @schmidt-sebastian

**Comment by dhermes** [comment]
ISTM the original requester didn't realize that the value was accessible as a constant rather than being fully "stringly typed"

```python
query = cities_ref.order_by('name', direction=cities_ref.DESCENDING).limit(3)
query = cities_ref.order_by('name', direction=Query.DESCENDING).limit(3)
```

----

From @schmidt-sebastian

I think this is a good simplification but would not treat this as blocking.

**Comment by dhermes** [comment]
@jonparrott and @lukesneeringer Can you weigh in here?

**Comment by tseaver** [comment]
I'm -0 on the "convenience" spelling myself.

**Comment by chemelnucfin** [comment]
I'm just going to say we should just leave it using direction since it's what is used here in the documentation
https://cloud.google.com/firestore/docs/query-data/order-limit-data

Please feel free to reopen if anyone else thinks otherwise.
