### ISSUE TITLE
How asynchronous should the Firestore API be?

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#4113]
This is very much related to @jonparrott's GAX/GAPIC overhaul. #4692

> APIs that involve network operations should follow the language’s common pattern for async requests. Synchronous wrappers can be provided where applicable.

Most methods return a JavaScript Promise, and we could use a `Future` as return values. However, the current implementation is fully synchronous.

----

From @jonparrott 

gRPC supports non-blocking calls. I'm not sure if gax exposes those? If it doesn't it shouldn't be too horribly difficult to do so.

```python
feature_future = stub.GetFeature.future(point)
feature = feature_future.result()
```

**Comment by dhermes** [comment]
```python
>>> from google.cloud import firestore
>>> client = firestore.Client()
>>> gapic_client = client._firestore_api
>>> gapic_client.firestore_stub
<google.cloud.proto.firestore.v1beta1.firestore_pb2.FirestoreStub at 0x7f3c98a70ba8>
>>> gapic_client.firestore_stub.Commit.future
<bound method _UnaryUnaryMultiCallable.future of <grpc._channel._UnaryUnaryMultiCallable object at 0x7f3c98a70160>>
>>>
>>> help(gapic_client.commit)
Help on method commit in module google.cloud.gapic.firestore.v1beta1.firestore_client:

commit(database, writes, transaction, options=None) method of google.cloud.gapic.firestore.v1beta1.firestore_client.FirestoreClient instance
    Commits a transaction, while optionally updating documents.
...
```

`google.gax.CallOptions` doesn't have a "future" option (that is part of @jonparrott's project)

**Comment by tseaver** [comment]
I'm going to assume that the API surface reviews done this spring make this question moot.
