### ISSUE TITLE
Python logging page missing usage examples

### ISSUE THREAD

**Issue by stew-r** [GoogleCloudPlatform/google-cloud-python#4118]
This page (https://googlecloudplatform.github.io/google-cloud-python/latest/logging/usage.html) does not provide any information on using the TextEntry objects returned by the logger's list_entries() method. I could not find any other documentation online to describe the attributes or methods for this object. Would it be possible to flesh out the documentation to include an example or two related to the logging entries?

**Comment by dhermes** [comment]
@waprin Do you know if there are docs for this?

**Comment by waprin** [comment]
@stew-r @dhermes is this helpful? https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry

**Comment by stew-r** [comment]
That matches up pretty closely with the attributes of the TextEntry object, though not perfectly (e.g., "insertId" vs. "insert_id"). My point was simply regarding capturing a common use case in documentation.
