### ISSUE TITLE
google-cloud (umbrella release) needs to be updated

### ISSUE THREAD

**Issue by kbl** [GoogleCloudPlatform/google-cloud-python#4121]
Commit tagged as 0.27.0 contains google-cloud-core dependency in version >= 0.27.0, < 0.28dev (
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/vision-0.27.0/pubsub/setup.py#L54). 

While 0.27.0 version hosted on pypi depends on google-cloud-core <0.27dev, >=0.26.0.

Seems like dependencies for that package hosted on pypy are prior this commit: https://github.com/GoogleCloudPlatform/google-cloud-python/commit/4a8e155c0e85bf80edbf2e5f1e9342bc3f571acb#diff-9ac0acbbb2af86fcf2d25000c371de7dL53

With such situation installing multiple google-cloud-* packages in version 0.27.0 along with google-cloud-pubsub would end with "pythonpath hell".

**Comment by dhermes** [comment]
Thanks for commenting @kbl.

As a short-term fix (and as general advice) I recommend against using the `google-cloud` umbrella package, since it brings in **every** package. Instead target the subpackages you explicitly need, like `google-cloud-pubsub`.

**Comment by dhermes** [comment]
@kbl Are you indicating that the "latest" version of some subpackage (e.g. `vision`) does **not** depend on the "latest" version of `google-cloud-core`?

**Comment by kbl** [comment]
@dhermes I'm not using google-cloud package. I'd like to use google-cloud-pubsub, google-cloud-biguery in the same virtualenv. I'd like to have both libraries in the same version. It's not possible to have them both as: 
- google-cloud-pubsub 0.27.0 depends on google-cloud-core <0.27dev, >=0.26.0,
- google-cloud-bigquery 0.27.0 depends on google-cloud-core <0.28dev, >=0.27.0.

According to my understading google-cloud-core dependency is "consistent" with its version, while google-cloud-pubsub isn't.

**Comment by lukesneeringer** [comment]
Use google-cloud-pubsub 0.28.0. :-)

(Separate comment: Having all of these packages that _almost_ track each other but do not completely is really confusing. We should have either made them all strictly track or not had them even remotely close to one another.)

**Comment by kbl** [comment]
Yes, I know that it's completly rewritten. And for that reason I don't want to use it for now. I wouldn't like to change the code depending on previously used API.

**Comment by tseaver** [comment]
Umbrella is now at [0.29.0](https://pypi.python.org/pypi/google-cloud/0.29.0).
