### ISSUE TITLE
ImportError: No module named iterator for <= 0.27.0

### ISSUE THREAD

**Issue by ensonic** [GoogleCloudPlatform/google-cloud-python#4122]
Since the modules are release without semantic versions, rebuilding my stack picked up 0.28.X and fall apart since the api changes. Before I wanted to migrate I need to get it up and running again and tried to pin to google-cloud-pubsub==0.27.0 or even google-cloud-pubsub==0.26.0 but with that I get:
```
2017-10-05T07:56:21.388141836Z Traceback (most recent call last):
2017-10-05T07:56:21.388206827Z   File "main.py", line 17, in <module>
2017-10-05T07:56:21.388256917Z     from google.cloud import pubsub
2017-10-05T07:56:21.388262369Z   File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub/__init__.py", line 30, in <module>
2017-10-05T07:56:21.388268557Z     from google.cloud.pubsub.client import Client
2017-10-05T07:56:21.388271207Z   File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub/client.py", line 21, in <module>
2017-10-05T07:56:21.388274841Z     from google.cloud.pubsub._http import Connection
2017-10-05T07:56:21.388277731Z   File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub/_http.py", line 25, in <module>
2017-10-05T07:56:21.388345257Z     from google.cloud.iterator import HTTPIterator
2017-10-05T07:56:21.388354853Z ImportError: No module named iterator
```

Any ideas?

**Comment by ensonic** [comment]
This combination seems to work:
"google-cloud-core==0.25.0 google-cloud-logging==0.24.0 google-cloud-pubsub==0.26.0"

Any tips for how to figure out which api combination work, other than trial and error?

**Comment by dhermes** [comment]
First: apologies. We are aware of the pain that breaking `google-cloud-core` has caused (both for us and users) and are trying hard to get it stable. (Thanks @jonparrott!)

----

To give a practical answer to your question. You can actually see the dependencies [on PyPI][1] (but not on [warehouse][2]):

![screenshot from 2017-10-05 08-24-39](https://user-images.githubusercontent.com/520669/31235564-ad5b0216-a9a6-11e7-8b36-7c65936821e6.png)

You can also see them in the source [at the tag][3] corresponding to the [release][4].

[1]: https://pypi.python.org/pypi/google-cloud-pubsub/0.28.3
[2]: https://pypi.org/project/google-cloud-pubsub/0.28.3
[3]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/pubsub-0.28.3/pubsub/setup.py#L53-L60
[4]: https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/pubsub-0.28.3

**Comment by Marigold** [comment]
Is there any ETA on fixing this? This is a major blocker for us as we have been using new pusub api everywhere and now can't use google storage. Thanks!

**Comment by dhermes** [comment]
@Marigold Can you be more specific about what you'd like to see fixed? (The output of `pip freeze` would be helpful.)

**Comment by Marigold** [comment]
Sorry @dhermes, I couldn't get it working on GCP yesterday, but the following req seems to be working after starting with fresh instance
```
google-auth==1.1.1
google-cloud-core==0.27.1
google-cloud-pubsub==0.28.3
google-cloud-storage==1.4.0
google-gax==0.15.15
google-resumable-media==0.2.3
googleapis-common-protos==1.5.3
grpc-google-iam-v1==0.11.4
```
thanks!

**Comment by lukesneeringer** [comment]
Closing as working then. :-)

**Comment by mike-seekwell** [comment]
I'm stilling getting this error on GAE, here's my requirement file:

psq==0.6.0

google_auth_oauthlib==0.2.0
oauth2client==4.1.2
google==1.9.3
google-api-python-client==1.6.4
google-auth==1.1.1
google-cloud==0.27.0
google-cloud-core==0.27.1
google-cloud-pubsub==0.28.3
google-cloud-storage==1.4.0
google-gax==0.15.15
grpc-google-iam-v1==0.11.4
gapic-google-cloud-datastore-v1==0.15.3
gapic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3
gapic-google-cloud-pubsub-v1==0.15.4
gapic-google-cloud-spanner-admin-database-v1==0.15.3
gapic-google-cloud-spanner-admin-instance-v1==0.15.3
gapic-google-cloud-spanner-v1==0.15.3
google-cloud-bigquery==0.26.0
google-cloud-bigtable==0.26.0
google-cloud-datastore==1.2.0
google-cloud-dns==0.26.0
google-cloud-error-reporting==0.26.0
google-cloud-language==0.27.0
google-cloud-logging==1.3.0
google-cloud-monitoring==0.26.0
google-cloud-resource-manager==0.26.0
google-cloud-runtimeconfig==0.26.0
google-cloud-spanner==0.26.0
google-cloud-speech==0.28.0
google-cloud-translate==1.1.0
google-cloud-videointelligence==0.25.0
google-cloud-vision==0.26.0
google-resumable-media==0.2.3
googleapis-common-protos==1.5.3
proto-google-cloud-datastore-v1==0.90.4
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3
proto-google-cloud-pubsub-v1==0.15.4
proto-google-cloud-spanner-admin-database-v1==0.15.3
proto-google-cloud-spanner-admin-instance-v1==0.15.3
proto-google-cloud-spanner-v1==0.15.3

**Comment by chemelnucfin** [comment]
Hello, I'm not sure if this is the best answer or if it would solve your problem, but some of the requirements are fairly old.
Will you be able to try the versions here?
https://pypi.python.org/pypi?%3Aaction=search&term=google-cloud&submit=search
