### ISSUE TITLE
unclear docs on https://googlecloudplatform.github.io/google-cloud-python/latest/pubsub/#publishing

### ISSUE THREAD

**Issue by ensonic** [GoogleCloudPlatform/google-cloud-python#4123]
The docs have this example:
```python
publisher = pubsub.PublisherClient()
topic = 'projects/{project_id}/topics/{topic}'.format(
    project_id=os.getenv('GOOGLE_CLOUD_PROJECT'),
    topic='MY_TOPIC_NAME',  # Set this to something appropriate.
)
publisher.create_topic()
publisher.publish(topic, b'My first message!', spam='eggs')
```
should it be:
```python
publisher = pubsub.PublisherClient()
topic_path = 'projects/{project_id}/topics/{topic}'.format(
    project_id=os.getenv('GOOGLE_CLOUD_PROJECT'),
    topic='MY_TOPIC_NAME',  # Set this to something appropriate.
)
topic = publisher.create_topic(topic_path)
publisher.publish(topic, b'My first message!', spam='eggs')
```
main questions:
* how does publisher.create_topic() know what topic if we don't tell it
* is there still a a topic object as there was before 0.28.0?
* can we just create a topic regardless whether it is already there? The old code (pre 0.28.0) was doing:
```python
client = pubsub.Client()
topic = client.topic(topic_name)
if not topic.exists():
    topic.create()
```

**Comment by tseaver** [comment]
> How does publisher.create_topic() know what topic if we don't tell it?

Thanks for pointing this out:  `Client.create_topic` definitely requires the `name` argument.

> Is there still a a topic object as there was before 0.28.0?

No, the redesigned API dropped the `Topic`, `Subscription`, and `Snapshot` classes.

> Can we just create a topic regardless whether it is already there?

No:  that would raise a `Conflict` exception.

**Comment by ensonic** [comment]
Thanks for the quick update. So how do I now check if a topic already exists? Create it and handle the exception?
