### ISSUE TITLE
'objects.rewrite' incompatible with 'user_project'

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#4125]
Our library functions which use the [`objects.rewrite` endpoint](https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite) cannot currently be used with `user_project` set on the object's bucket:  the back-end returns errors for such requests.

@frankyn reports that the issue is known, and that a fix is pending review / release by the back-end team.

**Comment by tseaver** [comment]
Affected methods;

- `Blob.rewrite`
- `Blob.update_storage_class`

**Comment by tseaver** [comment]
@frankyn Can you please update?

**Comment by frankyn** [comment]
This should have been resolved. Are you still seeing this error @tseaver?

**Comment by tseaver** [comment]
@frankyn We haven't enabled the tests which exercise the `requester_pays` / `user_project` features (#4126).  I tried just now and *none* of those tests are working when using my "personal" project as the "user project".

**Comment by tseaver** [comment]
I of course had lost the thread on how to enable RP/UP permissions.  Once I set up the permissions, they run locally without errors, including the two rewrite-based tests.

**Comment by frankyn** [comment]
Great! Thanks for picking it up so quickly!
