### ISSUE TITLE
Core test failure on AppVeyor

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#4128]
From https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-python/build/1.0.2336.storage-requester_pays-feature/job/9utfru14kenb40tr

```python
_______________ test_wrap_method_with_overriding_retry_deadline _______________
Traceback (most recent call last):
  File "C:\projects\google-cloud-python\core\tests\unit\api_core\gapic\test_method.py", line 159, in test_wrap_method_with_overriding_retry_deadline
    assert timeout_args == [5, 10, 20, 29]
AssertionError: assert [5.0, 10.0, 20.0, 30.0] == [5, 10, 20, 29]
  At index 3 diff: 30.0 != 29
  Full diff:
  - [5.0, 10.0, 20.0, 30.0]
  + [5, 10, 20, 29]
```

**Comment by dhermes** [comment]
Seems like a float / int division error?

**Comment by tseaver** [comment]
The assertion itself is problematic:  those numbers look suspiciously like "copy what the code actually output," rather than being intrinsically meaningful.

**Comment by dhermes** [comment]
(ASIDE: @tseaver I'm not sure if the AppVeyor folks are brits, but I changed the spelling from Appveyour 😉)
