### ISSUE TITLE
psqworker hangs at datastore client.get(key) or client.put(key)

### ISSUE THREAD

**Issue by FlapperDoodlez** [GoogleCloudPlatform/google-cloud-python#4132]
1. OS type and version
   Using Google Container Engine to create the "Bookshelf" sample app following this link https://cloud.google.com/python/tutorials/bookshelf-on-container-engine
2. Python version and virtual environment information `python --version`
   Python 3.4 or Python 2.7, doesn't matter, I've experienced this issue on either version.
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
Name: google-cloud
Version: 0.27.0
4. Stacktrace if available
5. Steps to reproduce
  Follow this tutorial: https://cloud.google.com/python/tutorials/bookshelf-on-container-engine
  You'll notice nothing gets executed after a client.get() or client.put() if they're executed on a worker.
6. Code example
Edit bookshelf/model_datastore.py, replacing read() with:

```python
  def read(id):
    ds = get_client()
    key = ds.key('Book', int(id))
    print("WAH")
    results = ds.get(key)
    print("WOMP")
    return from_datastore(results)
```
And you'll notice that "WOMP" is never printed.

Please let me know if I've created the issue in the wrong repo, thank you.

### Edit
What's interesting is that client.put() and get() work perfectly fine if they're being executed on the bookshelf-frontend instances.

**Comment by jonparrott** [comment]
Hey @FlapperDoodlez, could you tell use which version of grpcio is installed?

**Comment by FlapperDoodlez** [comment]
@jonparrott 

Hi, thank you for your response.
I've got version 1.6.3 of grpcio.

I don't see grpcio in the requirements.txt or requirements-dev.txt, for what it's worth.

**Comment by jonparrott** [comment]
Can you try adding `grpcio>=1.4.0, <1.6.0` to your `requirements.txt` file (and recreating your virtualenv if necessary) and seeing if that fixes it?

**Comment by FlapperDoodlez** [comment]
@jonparrott 
That fixed it 👍
