### ISSUE TITLE
Implement page size for core.Iterator to control batch size for performance reasons

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-python#4134]
__Background__

Google RPCs that enumerate a collection page by page support a request field we'll call "page size," which is the maximum number of items to return in the call. (Confusingly, the older HTTP-based APIs call this query parameter `maxResults`, a fact you're better off forgetting for the remainder of this issue.)

The `google.api.core.page_iterator.Iterator` class abstracts over paging RPCs, allowing item-by-item iteration while performing RPCs as needed. For users of `Iterator`, page size is an implementation detail; it only affects performance.

`Iterator` can be initialized with `max_results`, which is the maximum number of results to return. This is mostly a convenience feature: one could always just stop iterating after the desired number of items have been retrieved. There is also a small performance benefit available, in that the iterator could adjust the page size so that no more than `max_results` values are ever returned. (The `HTTPIterator` subclass of `Iterator` does in fact do this; the other subclasses do not set the page size.)

__Question__

How should methods that use `Iterator` handle page size?

Possibilities:

1. They should not support it. This is the current situation, at least in the `bigquery` module.

2. The `max_results` parameter that these methods accept should be re-interpreted as page size, instead of meaning the maximum number of results for the entire iteration.

3. Both `max_results`, with its current meaning, and `page_size` should be supported. (This would entail modifications to `Iterator`.)

/cc @tswast @lukesneeringer @dhermes @jonparrott @tseaver

**Comment by dhermes** [comment]
@jba I've actually brought his up before (#3277). @jonparrott Seemed to have a clear conclusion in that issue.

**Comment by tswast** [comment]
Sounds like we should do (3) and support both.

**Comment by dhermes** [comment]
I personally am on team (3) as well.

**Comment by jonparrott** [comment]
From #3277 

> Core iterators will use max_results to mean the maximum about of items that can be returned by the iterator over several pages. Core iterators will use page_size to determine how many results to fetch per page.

So yeah, 3 is where it's at. Not sure how core's `Iterator` would need to be modified- typically the page size is bound at request time, eg:

```python
def list_stuff(self, page_size):
    params = {'page_size': page_size'}
    return HTTPIterator(..., extra_params=params)
```

**Comment by jba** [comment]
@jonparrott The problem happens when you provide `max_results` too. I guess it's not a big deal, but because of [this code](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/core/google/api/core/page_iterator.py#L362)
```python
    if self.max_results is not None:
        result[self._MAX_RESULTS] = self.max_results - self.num_results
    result.update(self.extra_params)
```
you could fetch more than you need on the last page.

**Comment by jonparrott** [comment]
I'm okay with that.

**Comment by jonparrott** [comment]
I guessing this is good to close. Feel free to comment if it was in error.

**Comment by tswast** [comment]
Reopening, as I don't see `page_size` in the page iterator.

https://github.com/GoogleCloudPlatform/google-cloud-python/blob/a2efd96a107dc19756dbc8bf71691f6cc2f53331/api_core/google/api_core/page_iterator.py#L252-L302

**Comment by jonparrott** [comment]
Again, page_size is not a parameter to the iterator, it's parameter to the API method. 

For HTTP clients:

```python
def list_stuff(self, page_size):
    params = {'page_size': page_size'}
    return HTTPIterator(..., extra_params=params)
```

For gRPC clients:

```python
def list_stuff(self, page_size):
    request = stuff_pb2.ListStuffRequest(page_size=page_size)
    return GRPCIterator(method, request)
```
