### ISSUE TITLE
The commands shown in the commands on the page yield errors.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-python#4138]
https://googlecloudplatform.github.io/google-cloud-python/latest/language/usage.html

**Comment by udasahai** [comment]
document = language.types.Document( content = 'I am going from las vegas to los Angeles', type=language.enums.Type.PLAIN_TEXT,)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Type'

**Comment by lukesneeringer** [comment]
Sure enough. It is `language.enums.Document.Type.PLAIN_TEXT`.
