### ISSUE TITLE
Service Account Key Fails w/ Big Query

### ISSUE THREAD

**Issue by jfmyers** [GoogleCloudPlatform/google-cloud-python#4140]
I'm having an issue authenticating to Google Big Query. I have created a service account key (json file) and have set this as an environment variable. The service account key has project owner priveleges. The Google Big Query API is also enabled.

I have been playing with this now for the past 4 hours to no avail, creating new projects, new service account keys, even attempting all the various ways to pass credentials into `bigquery.Client`.

This has been extremely frustrating. I'd been very grateful for any ideas/help. 

1. OS type and version: **4.9.41-moby (Docker)** running on Mac OSX 10.12.2
2. Python version and virtual environment information `python --version`: **2.7.10**
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`: **0.27.0**
4. Stacktrace if available
```
google.cloud.exceptions.Forbidden: 403 Access Not Configured. BigQuery API has not been used in project <project_id> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/bigquery.googleapis.com/overview?project=<project_id> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. (GET https://www.googleapis.com/bigquery/v2/projects/<project_id>/datasets)
```
5. I'm calling the following code:
```
from google.cloud import bigquery
bigquery_client = bigquery.Client()
buckets = list(bigquery_client.list_datasets())
```

Thanks!

Jim

**Comment by dhermes** [comment]
@jfmyers You need to enable BigQuery in the Cloud Console for your project.

I also recommend checking out http://google-cloud-python.readthedocs.io/en/latest/core/auth.html

I am pre-emptively closing because it seems the 403 error message fully captures the problem. We're happy to continue discussing here / re-open if need be.
