### ISSUE TITLE
BigQuery json upload

### ISSUE THREAD

**Issue by jwcook23** [GoogleCloudPlatform/google-cloud-python#4165]
Sorry, newb here. I can't figure out how to stream json data (a dictionary) correctly into BigQuery. The closest I can get is below. This works except 'Name', 'Time', and 'Value' are inserted into the table, instead of their corresponding values. Really appreciate any help.

data = {'Name':'test1',
        'Time':'test',
        'Value':'test3'}
    rows = [data]
    errors = table.insert_data(rows)

**Comment by lukesneeringer** [comment]
Hi @jwcook23,
As the schema is specified in advance (see [the quickstart](https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/bigquery#load-data-from-csv)), `insert_data` takes a list rather than a dictionary. Provide a list (or tuple) and you should get the results you want.

**Comment by jwcook23** [comment]
@lukesneeringer Thanks for the response. I should have provided more information.

My ultimate goal is to publish a message using PubSub, and have Dataflow insert the data into BigQuery. My understanding is the Published message must be JSON. To test before implementing the Dataflow, I wanted to directly put JSON into BigQuery. It's difficult for me to comprehend what the table schema should look like when I have to jump from using a list, to publishing a JSON object.
