### ISSUE TITLE
ML engine takes an abnormally long time to prepare the job 

### ISSUE THREAD

**Issue by sonlac** [GoogleCloudPlatform/google-cloud-python#4171]
Right now (Oct 12, 2017, 2:48:39 PM GMT+2), i tried to launch my ML job many times. It took too much time (30 minutes still **preparing**) than normal and it was always at preparing stage. I had to cancel them.
It takes normally around 5 minutes in the queue and then lanches the job. Today, it seems unusually. 
I am wondering if there is some problems today for ML engine?

I always got the error: 

`Internal error occurred for the current attempt.`

The details:
```
15:06:40.326
Internal error occurred for the current attempt.
{
 insertId: "opin1mfr8uv7p"  
 logName: "projects/[my-project-id]/logs/ml.googleapis.com%2Fjob_mlengine_[hidden]_20170429__20171012_144837_098147"  
 receiveTimestamp: "2017-10-12T13:06:40.326451581Z"  
 resource: {
  labels: {
   job_id: "job_mlengine_[hidden]_20170429__20171012_144837_098147"    
   project_id: "my-project-id"    
   task_name: "service"    
  }
  type: "ml_job"   
 }
 severity: "ERROR"  
 textPayload: "Internal error occurred for the current attempt."  
 timestamp: "2017-10-12T13:06:40.326451581Z"  
}
```

![screenshot from 2017-10-12 15-59-36](https://user-images.githubusercontent.com/5931124/31500569-06392cde-af68-11e7-93ab-4eca855ba547.png)

**Comment by sonlac** [comment]
![screenshot from 2017-10-12 15-45-21](https://user-images.githubusercontent.com/5931124/31501308-2f579e82-af6a-11e7-867a-89e76a7430fc.png)

**Comment by dhermes** [comment]
@sonlac This doesn't seem to be related to the `google-cloud-python` libraries?

**Comment by sonlac** [comment]
So, where should I report this problem? Thanks.

**Comment by dhermes** [comment]
Here is a list of cloud related issue trackers:

- https://cloud.google.com/support/docs/issue-trackers

However I don't see ML engine on there. @jonparrott @waprin Would you happen to know?

----

@sonlac Feel free to keep commenting but I'm closing out this issue before I forget (since it isn't an issue in our libraries).

**Comment by sonlac** [comment]
@dhermes ML engine is "Cloud Machine Learning Platform" :) https://issuetracker.google.com/issues?q=componentid:187220%20status:open
In fact, it was just an intermittent issue. It worked the day after. Thanks.
