### ISSUE TITLE
Database().snapshot.read() function does not return an error when it should

### ISSUE THREAD

**Issue by malusdei** [GoogleCloudPlatform/google-cloud-python#4204]
What happens is an empty result set is returned - there is no error - when I have intentionally misspelled / misnamed table and column.

What should happen is that I get an error/exception saying that something has gone wrong with the function call, preferably in detail that the table or field could not be found.

This bug found on:

- OSX Sierra 10.12.6
- Python version is 3.6.3
- Google Cloud version 0.27

There is no stack trace.

To Reproduce, run:

```python
with database.snapshot() as snapshot:
    result = snapshot.read(
        table='Aggfobblebobble', columns=['TotallyNonexistentColumn', 'Balance'],
        keyset=spanner.KeySet(all_=True))
    for row in result.rows:
        print(row)
```

(...where database is a working database instance set up in a typical Python to Cloud Spanner session)

**Comment by chemelnucfin** [comment]
This error is because rows should not be allowed to be used.
#4492 will remove this error and you can just iterate over the result.
Please feel free to reopen if there are other concerns.
Thank you for reporting.
