### ISSUE TITLE
Add `.devN` suffixes to all version numbers

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#4208]
I propose we add `.devN` suffixes to all version numbers. This way we can accurately reflect, e.g. that `google-cloud-pubsub` depends on `google-cloud-core >= 0.28.0.dev1` rather than a released version of `google-cloud-core`.

Ref: https://snarky.ca/how-i-manage-package-version-numbers/

----

From https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4186#issuecomment-336531198

**Comment by lukesneeringer** [comment]
I suggested something similar to @jonparrott in chat, although I discussed doing a 1.0 release candidate series.

Let's discuss more tomorrow. I really want to avoid "release the world" pain for customers.

**Comment by duggelz** [comment]
Could we add the blog link and/or explanantion to CONTRIBUTING.rst?  I was looking for this explanation, and it took a bit of googling based on half-remembered commit messages.  CC @liyanhui1228

**Comment by dhermes** [comment]
Sure thing @duggelz. You want to send a PR or you want me, @tseaver, @chemelnucfin or somebody else to send it?

**Comment by duggelz** [comment]
Since I asked for this, I can write something up, sometime next week.
