### ISSUE TITLE
Problem importing google.cloud.gapic.pubsub.v1 in dev_appserver.py

### ISSUE THREAD

**Issue by patitonav** [GoogleCloudPlatform/google-cloud-python#4218]
Hello i am testing my app engine application locally on my Ubuntu 16.04 , I recently remove and reinstall all the packages using pip. I am working on a virtualenv with all the dependencies installed. But I have problems to do this:

 `from google.cloud.gapic.pubsub.v1 import publisher_client` 

> from google.cloud.gapic.pubsub.v1 import publisher_client
INFO     2017-10-18 18:10:59,703 module.py:821] icm: "POST /api/announce HTTP/1.1" 500 37
  File "/home/pato/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py", line 1132, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named google.cloud.gapic.pubsub.v1

`pip install grpc-google-cloud-pubsub-v1`
` pip show google-cloud`
>Name: google-cloud
Version: 0.26.0
Summary: API Client library for Google Cloud
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: jjg+google-cloud-python@google.com
License: Apache 2.0
Location: /home/pato/.virtualenvs/google_projects/lib/python2.7/site-packages
Requires: google-cloud-storage, google-cloud-vision, google-cloud-pubsub, google-cloud-monitoring, google-cloud-runtimeconfig, google-cloud-bigquery, google-cloud-dns, google-cloud-videointelligence, google-cloud-logging, google-cloud-datastore, google-cloud-bigtable, google-cloud-core, google-cloud-resource-manager, google-cloud-translate, google-cloud-speech, google-cloud-language, google-cloud-error-reporting, google-cloud-spanner

If i open a python terminal theres is no problem importing the module

> (google_projects) pato@pato-Inspiron:$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
 \>>> from google.cloud.gapic.pubsub.v1 import publisher_client
 \>>>
 

But on the dev_appserver console, i get this:

```
import os
import sys

from google.cloud.gapic import pubsub
from google.cloud import gapic
print pubsub.__path__

from google.cloud.gapic.pubsub.v1 import publisher_client
```

> ['/home/pato/.virtualenvs/google_projects/local/lib/python2.7/site-packages/google/cloud/gapic/pubsub', '/home/pato/.virtualenvs/google_projects/lib/python2.7/site-packages/google/cloud/gapic/pubsub', '/home/pato/Proyectos/nodus2020/icm/lib/google/cloud/gapic/pubsub']
Traceback (most recent call last):
  File "/home/pato/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/request_handler.py", line 232, in handle_interactive_request
    exec(compiled_code, self._command_globals)
  File "<string>", line 8, in <module>
  File "/home/pato/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py", line 1132, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named google.cloud.gapic.pubsub.v1

I have no idea what is going on, if somebody can help i will appreciate

**Comment by cthrax** [comment]
I had something similar happen that might help you.

I couldn't use any of the new google cloud tools in appengine standard because both the appengine standard sdk and google cloud tools use the package "google" If one is on the python path, the other isn't and vice versa. Aside from doing my own file copying to the appengine standard SDK, I haven't figure out a way to get this to work. Let me know if you manage, but I ended up going back to the google-api-python-client for these sorts of features (in my case cloud storage).

**Comment by patitonav** [comment]
I think i can't do the same becouse my problem is with pubsub which isn't in google-api-python-client

**Comment by patitonav** [comment]
Is there a way to use pubsub library in a dev_appserver.py enviroment?

**Comment by dhermes** [comment]
@patitonav Possibly? Check out https://github.com/dhermes/google-cloud-python-on-gae to see some of the struggle I went through to get `google-cloud-language` working on GAE (both dev and prod).

**Comment by lukesneeringer** [comment]
I am 99% sure you will be unable to use the library in dev_appserver (or production GAE). :-(

**Comment by patitonav** [comment]
@cthrax What do you mean by "I ended up going back to the google-api-python-client for these sorts of features"?

**Comment by cthrax** [comment]
There are two python libraries floating around out there for working with google cloud storage. One is google-cloud-storage (the newest that has the namespacing issues) and GoogleCloudStorage (no namespacing issues, but doesn't offer functionality like resumable uploads). I had to go back to GoogleCloudStorage, which I found documentation for as google-api-python-client.

**Comment by patitonav** [comment]
I tried by uninstalling some python libraries in the virtualenv (all related with pubsub and google-gax). And then when i run dev_appserver.py i get this error:
```
import multiprocessing as mp
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 65, in <module>
    from multiprocessing.util import SUBDEBUG, SUBWARNING
  File "/usr/lib/python2.7/multiprocessing/util.py", line 41, in <module>
    from subprocess import _args_from_interpreter_flags
ImportError: cannot import name _args_from_interpreter_flags

```

**Comment by dhermes** [comment]
@patitonav In the repo I linked to, there are hacks for working around standard library packages that aren't available on GAE (such as `subprocess`).

**Comment by jonparrott** [comment]
Unfortunately, App Engine standard does not support these library at this time. We are working on making this happen, but it is a lot of work. You can follow #1893 for updates.

In the meantime, you can use the `google-api-python-client`, `requests`, or `grpc` directly on App Engine standard to communicate with Cloud Pub/Sub.

(Closing this issue as a duplicate).

**Comment by patitonav** [comment]
OK, Does anybody have an example of pubsub using `google-api-python-client` I can't find one.

Thanks

**Comment by anguillanneuf** [comment]
@patitonav You have probably figured this out a long time ago, but I'm posting some code here anyway in case someone else is also looking for the answer. Remember to replace `{PROJECT_NAME}` and `{TOPIC_NAME}` in the code below. 

```python
from googleapiclient.discovery import build

# Publisher.
service = build('pubsub', 'v1')
mytopic = 'projects/{PROJECT_NAME}/topics/{TOPIC_NAME}'
data = 'hello, world!'
service.projects().topics().publish(topic=mytopic, body={
      "messages":
        [{
         "data": base64.b64encode(data.encode('utf-8'))
        }]
    }).execute()
print("Published message.")
```

**Comment by pilipenok** [comment]
>          "data": base64.b64encode(data.encode('utf-8'))
Hello @anguillanneuf ,
Thank you for the advice but I'm getting error "Object of type bytes is not JSON serializable" here.

The reason to use discovery is Import Error "cannot import name pubsub from google.cloud (unknown location)". 
2.1.0 is the last for now.
