### ISSUE TITLE
[Question] Can't find documentation on whether any functions require active internet connection, or if all functions can be performed entirely offline

### ISSUE THREAD

**Issue by joshjacobson** [GoogleCloudPlatform/google-cloud-python#4219]
Quite a basic question... I just can't find any reference in the documentation as to what aspects of this function offline, and which require a connection.

**Comment by dhermes** [comment]
@joshjacobson Can you be more specific?

In general, constructors and factory methods that **call** constructors don't require network. In addition setting and getting attributes won't surprise you by making an API call. Essentially every other method will talk to the network.

`Client` constructors may perform disk I/O to determine your default credentials. On GCE, they may actually perform local network I/O to talk to the metadata server.

**Comment by tseaver** [comment]
@joshjacobson The `google-cloud-<api>` libraries are entirely aimed at providing access from Python to the various Google Cloud APIs.  There is pretty much no value in them for apps which run unconnected.
