### ISSUE TITLE
service-management in Python

### ISSUE THREAD

**Issue by leeparayno** [GoogleCloudPlatform/google-cloud-python#4223]
I found this in the gcloud SDK docs:

https://cloud.google.com/sdk/gcloud/reference/service-management/list

Is there an equivalent service-management in the Google Cloud Python project?

**Comment by lukesneeringer** [comment]
I do not believe so. /cc @jonparrott as a sanity check.

**Comment by jonparrott** [comment]
Not at this time. You may be able to interact with the API using the google-api-python-client.
