### ISSUE TITLE
PubSub: New pubsub not compatible with psq

### ISSUE THREAD

**Issue by shumin** [GoogleCloudPlatform/google-cloud-python#4224]
I'm using google-cloud=0.27.0 currently and now trying to use latest google-cloud-pubsub=0.28.4

But its break with current `psq` implementation. Any workaround so `psq` can work with latest pubsub?

Code snippet for existing implementation (works):
> client = pubsub.Client(project=current_app.config['PROJECT_ID'])
> psq.Queue(client, 'feed_queue', extra_context=current_app.app_context)

New implementation (breaks):

> client = pubsub.SubscriberClient()
> psq.Queue(client, 'feed_queue', extra_context=current_app.app_context)
> (Error msg: AttributeError: 'Client' object has no attribute 'topic')

Thanks

**Comment by jonparrott** [comment]
> Any workaround so psq can work with latest pubsub?

Nope, I need to either update or deprecate PSQ. Most of the features that PSQ has are now incorporated into the Pub/Sub library.

**Comment by mohammad-haque** [comment]
@jonparrott Thanks. Although Pubsub does offer many features but it doesn't completely replace the need of some queue based task processing, in this case PSQ. It would be really helpful to keep the PSQ as a supported option, not deprecating it.

**Comment by jonparrott** [comment]
For sure- really psq isn't a very big library. It shouldn't be too hard (if you want to take a stab at a PR go for it.)

**Comment by jonparrott** [comment]
This is fixed in the latest release of psq.
