### ISSUE TITLE
bucket.enable_logging should use bucket.name as default prefix

### ISSUE THREAD

**Issue by pdknsk** [GoogleCloudPlatform/google-cloud-python#4228]
It matches [`gsutil`](https://cloud.google.com/storage/docs/access-logs#delivery) and is probably what most users want by default.
> By default, the object prefix is the name of the bucket for which the logs are enabled.

Currently it sets an [empty prefix](https://googlecloudplatform.github.io/google-cloud-python/latest/_modules/google/cloud/storage/bucket.html#Bucket.enable_logging).

If someone stores logs from multiple buckets in a common *logs-bucket*, without explicitly setting a prefix, they can overwrite each other.

**Comment by tseaver** [comment]
Seems reasonable.  Changing the default might qualify as a "breaking change".  @lukesneeringer do you have an opinion on that?  ISTM we would need to document explicitly that users could restore the old behavior by passing an explicit `prefix=''`.

**Comment by chemelnucfin** [comment]
@lukesneeringer it seems like per our conversation this issue should be closed unless we decide to change it for future releases?
