### ISSUE TITLE
Please update README to indicate Firestore release/support level

### ISSUE THREAD

**Issue by danoscarmike** [GoogleCloudPlatform/google-cloud-python#4229]
cc/ @lukesneeringer

**Comment by dhermes** [comment]
@danoscarmike Could you give an example of what you'd like to see from the README of a different package?

**Comment by dhermes** [comment]
Or are you referring to the README for the entire project?

**Comment by danoscarmike** [comment]
Hi @dhermes, yes, referring to the project [README](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/README.rst)
