### ISSUE TITLE
Vision: Single feature functions generated by cloud vision client library does not support parameter max_results

### ISSUE THREAD

**Issue by michaelawyu** [GoogleCloudPlatform/google-cloud-python#4272]
As specified in [the gRPC reference](https://cloud.google.com/vision/docs/reference/rpc/google.cloud.vision.v1#google.cloud.vision.v1.AnnotateImageRequest), AnnotateImageRequest message have three fields, _image_, _features[]_ and _image_context_, in which the _features[]_ field determines what feature user is request (_type_) and max number of returned results (_max_results_). The code for generating single-feature functions (for example, _face_detection()_), however, does not allow user to specify _max_results_:

```
feature_value = {'type': enum.__dict__[feature]}
def inner(self, image, options=None, **kwargs):
        request = dict(
            image=image,
            features=[feature_value],
            **kwargs
        )
        return self.annotate_image(request, options=options)
```

Reported in https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1173

**Comment by chemelnucfin** [comment]
See PR #4817
