### ISSUE TITLE
Speech: Deprecated doc!

### ISSUE THREAD

**Issue by alaxa27** [GoogleCloudPlatform/google-cloud-python#4275]
Hello,
I was using cloud speech and therefore reading the docs when I came across a problem:
```python
operation = client.long_running_recognize(audio, config)
```
it returns an _OperationFuture object from python Gax Library. Here is the [source code](http://gax-python.readthedocs.io/en/latest/_modules/google/gax.html?highlight=_operation).
But the attributes the documentation tells this object has are untrue. Indeed operation.complete really is operation.done().
And operation.poll() really is operation._poll() but isn't necessary here because operation.results became the method operation.result() which blocks untils operation.complete() is True.
The documentation that needs an update is here:
https://googlecloudplatform.github.io/google-cloud-python/latest/speech/index.html

Kind regards :dango:

**Comment by lukesneeringer** [comment]
Thanks for reporting that! I shall fix it. :-)
