### ISSUE TITLE
google.gax.errors.RetryError: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Invalid resource name given (name=projects/insights-sandbox-153010/topics/harsh). Refer to https://cloud.google.com/pubsub/overview#names for more information.)>) please help me to solve it

### ISSUE THREAD

**Issue by HarshCHhz** [GoogleCloudPlatform/google-cloud-python#4276]
# Thank you for reporting an issue to google-cloud-python!

If you are reporting an issue or requesting a feature, please search the
existing open and closed issues to see if there is already work being done.

- https://github.com/GoogleCloudPlatform/google-cloud-python/issues
- http://stackoverflow.com/questions/tagged/google-cloud-python

If you can provide us with as much of the following information as possible it
will help us identify the cause of your issue more quickly.

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version
3. Python version and virtual environment information `python --version`
4. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
5. Stacktrace if available
6. Steps to reproduce
7. Code example

Using GitHub flavored markdown can help make your request clearer.
See: https://guides.github.com/features/mastering-markdown/

**Comment by sagarrakshe** [comment]
@HarshCHhz It's not clear from your title what exactly do you need. Can you please elaborate on the issue and show us your code what you tried?

**Comment by HarshCHhz** [comment]
@sagarrakshe here i am sending the code 
rom google.cloud import pubsub_v1

subscriber =pubsub_v1.SubscriberClient()

topic_name = 'projects/topics/'
sub_name = 'projects/subscriptions/'
subscriber.create_subscription(topic_name, sub_name)

# now pulling the subscription
subscription = subscriber.subscribe(
    'projects/subscriptions/'
)
print'', subscription

**Comment by dhermes** [comment]
@HarshCHhz It appears you are using an invalid `topic`. IIUC you shouldn't be using `projects/topics/` in your topic name.

**Comment by dhermes** [comment]
@HarshCHhz I am going to pre-emptively close as the error message

```
Invalid resource name given (name=projects/insights-sandbox-153010/topics/harsh)
```

seems to be clear.

**Comment by dhermes** [comment]
The error is that the name is wrong. The `topic_name` and `sub_name` should not contain `'projects/...`, just the name part.

**Comment by HarshCHhz** [comment]
i have tried it still it not working 
@dhermes

**Comment by dhermes** [comment]
@HarshCHhz Sorry about that. Could you provide the code you are using? Any "private data" you can just replace with `<REDACTED>`?

**Comment by HarshCHhz** [comment]
from google.cloud import pubsub_v1

subscriber =pubsub_v1.SubscriberClient()

topic_name = 'projects/<REDACTED>/topics/harsh'
sub_name = 'projects/<REDACTED>/subscriptions/harshsub'
subscriber.create_subscription(topic_name, sub_name)

# now pulling the subscription
subscription = subscriber.subscribe(
    'projects/<REDACTED>/subscriptions/harshsub'
)
print'', subscription

**Comment by dhermes** [comment]
@HarshCHhz Sorry I didn't catch this earlier, but you have the arguments to [`create_subscription`][1] out of order. The first is the subscription name, the second is the topic name.

```python
import google.auth
from google.cloud import pubsub_v1

_, project = google.auth.default()
topic_name = subscriber.topic_path(project, 'harsh')
sub_name = subscriber.subscription_path(project, 'harshsub')
response = subscriber.create_subscription(sub_name, topic_name)
```

[1]: https://googlecloudplatform.github.io/google-cloud-python/latest/pubsub/subscriber/api/client.html#google.cloud.pubsub_v1.subscriber.client.Client.create_subscription

**Comment by HarshCHhz** [comment]
@dhermes i am still facing the same probelm. I think there is somefault in my google.cloud package

**Comment by dhermes** [comment]
@HarshCHhz Is it the same fault? Could you post a stacktrace?

**Comment by HarshCHhz** [comment]
yes it is the same fault @dhermes

**Comment by dhermes** [comment]
Can you double-check that you've switched the arguments to `create_subscription()`? I'm able to reproduce the "Invalid resource name given" error when using them in the wrong order:

```python
>>> import google.auth
>>> from google.cloud import pubsub_v1
>>>
>>> _, project = google.auth.default()
>>> subscriber = pubsub_v1.SubscriberClient()
>>> topic_name = subscriber.topic_path(project, 'harsh')
>>> sub_name = subscriber.subscription_path(project, 'harshsub')
>>> response = subscriber.create_subscription(topic_name, sub_name)
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/google/gax/retry.py", line 121, in inner
    return to_call(*args)
  File ".../lib/python3.6/site-packages/google/gax/retry.py", line 68, in inner
    return a_func(*updated_args, **kwargs)
  File ".../lib/python3.6/site-packages/grpc/_channel.py", line 492, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File ".../lib/python3.6/site-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Invalid resource name given (name=projects/{PROJECT}/topics/harsh). Refer to https://cloud.google.com/pubsub/overview#names for more information.)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.6/site-packages/google/cloud/pubsub_v1/_gapic.py", line 42, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)
  File ".../lib/python3.6/site-packages/google/cloud/gapic/pubsub/v1/subscriber_client.py", line 445, in create_subscription
    return self._create_subscription(request, options)
  File ".../lib/python3.6/site-packages/google/gax/api_callable.py", line 452, in inner
    return api_caller(api_call, this_settings, request)
  File ".../lib/python3.6/site-packages/google/gax/api_callable.py", line 438, in base_caller
    return api_call(*args)
  File ".../lib/python3.6/site-packages/google/gax/api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)
  File ".../lib/python3.6/site-packages/google/gax/retry.py", line 127, in inner
    ' classified as transient', exception)
google.gax.errors.RetryError: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Invalid resource name given (name=projects/{PROJECT}/topics/harsh). Refer to https://cloud.google.com/pubsub/overview#names for more information.)>)
```

**Comment by HarshCHhz** [comment]
yes i have switch the create_subscription arguement
