### ISSUE TITLE
Storage: Provide credential-free access to public-access buckets

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#4279]
Per the [GCS authentication doc](https://cloud.google.com/storage/docs/authentication):

> Objects are anonymously accessible if the `allUsers` group has `READ` permission.

Add support for such access to the storage client.  Two strategies seem possible:

- Add a classmethod factory to the `Client` class which bypasses inferring credentials from the user environment.
- Add a custom `AnonymousCredentials` singleton which can be passed to the `Client` constructor.

We don't need to enforce any limits on the access to buckets / objects retrieved from the "anonymous" client:  the back-end will return `UNAUTHORIZED`.

System tests can use the `gcp-public-data-landsat` bucket, if desired (hopefully CI throttling won't be an issue).

**Comment by tseaver** [comment]
Notes:

- The core `Client` class insists that the `credentials` passed to it be either a) `None` (in which case it infers a set from the environment), or b) an instance of `google.auth.credentials.Credentials` (or a subclass).
- We probably have to pass in a custom `_http` instance, which will otherwise default to a lazily-created `google.auth.transport.requests.AuthorizedSession` instance.
- OTOH, it looks as though the `AuthorizedSession` class just wants the `credentials` object to have a `before_request()` method, which we could stub out as a no-op for the anonymous case, and a `refresh()` method, which shouldn't be needed, and could just raise.

**Comment by jonparrott** [comment]
I'm totally open and +1 to the idea of "Null/Anonymous Credentials" in google.auth.

We could then make a nice helper constructor for storage:

```
storage_client = google.cloud.storage.Client.create_anonymous_client()
```

**Comment by tseaver** [comment]
@jonparrott I'm working on the `AnonymousCredentials` bit right now.

**Comment by jonparrott** [comment]
Sweet.

**Comment by tseaver** [comment]
@jonparrott Is the classmethod-factory the surface you'd prefer?

**Comment by jonparrott** [comment]
passing in anonymouscredentials should work, ofc, but I think if this is a common enough use case we should either (a) explicitly document how to do this and/or (b) provide a helper constructor.

**Comment by tseaver** [comment]
Awaiting release of (merged) https://github.com/GoogleCloudPlatform/google-auth-library-python/pull/206

**Comment by tseaver** [comment]
@chemelnucfin We don't really need the API name in the issue title for issues which have labels.  Non-maintainers cannot assign labels, so we have started asking them to include the API name.

**Comment by chemelnucfin** [comment]
OK, I just figured it would be easier for everyone to see and use a similar
format in the issues page if everything was more standardized.
