### ISSUE TITLE
What is recommended pubsub version to use in production?

### ISSUE THREAD

**Issue by ilyanesterov** [GoogleCloudPlatform/google-cloud-python#4286]
I'm using quite old pubsub version on my  production system google-cloud-pubsub==0.24.0 , I tried to update it and seems there were redesign on the API, which is has much more features now, I'm kinda playing with it on staging environment, but it seems every time I update pubsub it gets a new issues. 
So what is a most stable version here or should I stay on 0.24.0 ?

**Comment by lukesneeringer** [comment]
I would probably recommend using the newest version. It is still in beta, but it is much more feature-rich and we are actively working to address any issues found.

There is one large outstanding issue, related to problems where flow control causes acks not to go through correctly: we are in the process of getting that issue fixed.

**Comment by ilyanesterov** [comment]
Yeah I figured last night that if I don't use flow control than it much more stable, but still waiting a fix for #4234 which seems will resolve everything I need at this moment. Though working flow control will definitely will be useful.
