### ISSUE TITLE
BigQuery - doc is not in line with latest release 0.27.0

### ISSUE THREAD

**Issue by andrewsmartin** [GoogleCloudPlatform/google-cloud-python#4289]
Hi, the doc for the BigQuery API seems to reflect an upcoming 0.28.0 release but 0.27.0 is still the latest release, is it possible to revert the docs back? Or will the 0.28.0 be cut very soon?

**Comment by dhermes** [comment]
@andrewsmartin Hopefully #4258 will be merged today and the release will go out.

I am going to pre-emptively close this, but thanks for noticing and thanks for filing! If you think we should re-open I'm happy to discuss.
