### ISSUE TITLE
BQ snippets tests may have "collision" problems

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#4292]
They may benefit from using `unique_id()`?

See: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3964

**Comment by tswast** [comment]
I don't think that error is a collision problem. I'm seeing

> google.api_core.exceptions.InternalServerError: 500 POST https://www.googleapis.com/bigquery/v2/projects/precise-truck-742/datasets: An internal error occurred and the request could not be completed.

This usually indicates a transient error on the backend. If anything, I'd say this indicates we might need more aggressive retries.

**Comment by tswast** [comment]
Is there any action to take here?

**Comment by dhermes** [comment]
I think I was just basing it on the fact that it failed:

```
nox > * unit_tests(python_version='2.7'): passed
nox > * unit_tests(python_version='3.4'): passed
nox > * unit_tests(python_version='3.5'): passed
nox > * unit_tests(python_version='3.6'): passed
nox > * system_tests(python_version='2.7'): passed
nox > * system_tests(python_version='3.6'): passed
nox > * snippets_tests(python_version='2.7'): passed
nox > * snippets_tests(python_version='3.6'): failed
nox > * lint: passed
nox > * lint_setup_py: passed
nox > * cover: passed
```

(i.e. I never actually looked at the failure when filing, may have been in a hurry).
