### ISSUE TITLE
Packaging: "Guard" calls to `setuptools.setup()` behind `if __name__ == '__main__'`

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#4295]
This way our `setup.py` files could be imported (for example).

This is low-priority, but an easy change to make.

**Comment by tseaver** [comment]
I'm a pretty big -1 on the idea that `setup.py` should ever be importable.

**Comment by dhermes** [comment]
@tseaver I don't actually mind if it's import-able, but that was just an example. It's more just like good hygiene to have `if __name__ == '__main__'` in all scripts.

**Comment by duggelz** [comment]
+1 on `__main__` hygiene across the board.

**Comment by jonparrott** [comment]
`setup.py`, like `nox.py`, is a configuration file for a specific tool. We should not treat it as a Python module.
