### ISSUE TITLE
BigQuery: remove circular imports in helper functions that use Row class

### ISSUE THREAD

**Issue by alixhami** [GoogleCloudPlatform/google-cloud-python#4305]
With https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4291 the `Row` class was moved from `_helpers.py` to `table.py`. This caused circular references between the two files, because `_helpers.py` imports `Row` from `Table` and `table.py` imports multiple helper functions from `_helpers.py`.

To temporarily resolve the import errors, the `Row` class was imported within the individual helper functions where it was needed. The circular import issue needs to be resolved so that Row does not have to be imported inside functions.

**Comment by tseaver** [comment]
#5550 moved the `_item_to_row` and `_rows_page_start` to the `table` module (their only uses were there).
