### ISSUE TITLE
BigQuery Python Client v0.28.0: Can't recover {Dataset,Table}References from Dataset or Table objects

### ISSUE THREAD

**Issue by robfraz** [GoogleCloudPlatform/google-cloud-python#4327]
Hello,

In v0.28.0 of the BigQuery Python Client, it doesn't seem possible to recover the original `DatasetReference` or `TableReference` used to create the the `Dataset` or `Table`, thus preventing any part of the API (or a user's application) that requires a reference to also take the Dataset or Table object.  It seems the reference used in creating the Dataset or Table is lost on object creation [1][2].

For example, in the `client.load_table_from_file()` function [3], a `table_ref` is expected; it seems logically unreasonable that a full Table object can't be used to fulfil the need for a table reference.

Cheers,
Rob

[1] https://github.com/GoogleCloudPlatform/google-cloud-python/blob/0.28.0/bigquery/google/cloud/bigquery/table.py#L170-L177
[2] https://github.com/GoogleCloudPlatform/google-cloud-python/blob/0.28.0/bigquery/google/cloud/bigquery/dataset.py#L204-L208
[3] https://github.com/GoogleCloudPlatform/google-cloud-python/blob/0.28.0/bigquery/google/cloud/bigquery/client.py#L692-L706

**Comment by dhermes** [comment]
@tswast Can you lend a hand here?

**Comment by tswast** [comment]
This is a good feature request. I agree that such a change would improve usability.

I see two ways to address this:
1. To allow either `Table` or `TableReference` for operations such as `client.load_table_from_file()`. Likewise for `Dataset` and `DatasetReference`.
2. Add a helper method to get the `TableReference` from a `Table` object. Likewise for `Dataset` and `DatasetReference`.

In the meantime, the workaround is to create a [`TableReference`](https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/reference.html#google.cloud.bigquery.table.TableReference) manually from a `Table`.

```
dataset_ref = DatasetReference(table.project, table.dataset_id)
table_ref = TableReference(dataset_ref, table.table_id)
```

My preference would be for (2). Something like the following code:

```
table_ref = table.reference
```

**Comment by robfraz** [comment]
@tswast Sounds good.  You want me to throw up a pull request, or is this something that you'll add yourselves?

**Comment by tswast** [comment]
Contributions welcome. :-)

**Comment by tswast** [comment]
I've got a PR pending #4405
