### ISSUE TITLE
BigQuery: doesn't declare dependency on concurrent.futures

### ISSUE THREAD

**Issue by drigz** [GoogleCloudPlatform/google-cloud-python#4337]
[bigquery/client.py imports concurrent.futures](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/09897f31f83023ae9059a0eb4296b15d4785678d/bigquery/google/cloud/bigquery/client.py#L20) but it doesn't declare the dependency in [setup.py](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/09897f31f83023ae9059a0eb4296b15d4785678d/bigquery/setup.py#L53). It should have a declaration like [the one from google-cloud-core==0.27.1](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/bee32c0ae68b1e6cf224f9017c758a8e31e8be83/core/setup.py#L63) (removed in 0.28.0).

Currently this is doesn't break anything because [api-core depends on futures](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/09897f31f83023ae9059a0eb4296b15d4785678d/api_core/setup.py#L62), but if that dependency disappears it will break.

This may be true for other clients, I haven't checked. I ran into it when looking at bazelbuild/rules_python#14.

**Comment by dhermes** [comment]
@jonparrott (our resident packaging expert) WDYT here?

I am inclined to say this is "working as intended".

**Comment by jonparrott** [comment]
Yes, I consider this working as intended. BigQuery *does* directly import concurrent.futures, so an argument could be made for having a direct dependency.

**Comment by lukesneeringer** [comment]
Hold on: `concurrent.futures` is not in the standard library in Python 2.7.

That means that either the BigQuery library only supports 3.4+, or we do need this, yes?

```
$ python2.7
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from concurrent.futures import Future
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named concurrent.futures
>>> ^D
```

**Comment by lukesneeringer** [comment]
Oh wait, I spoke too soon. Transitive dependency.

I do not love this generally, but considering _we_ control `google.api_core` and our tests will fail if we ever make a change, yes this is fine.

If we did not control the dependency, it would not be fine.
