### ISSUE TITLE
Datastore: please support specifying read consistency

### ISSUE THREAD

**Issue by rvandegrift** [GoogleCloudPlatform/google-cloud-python#4340]
According to the Cloud Datastore docs, the python client does not support setting the read consistency of a query:
https://cloud.google.com/datastore/docs/concepts/structuring_for_strong_consistency#datastore-eventual-consistent-query-python

Any chance this could be implemented?

**Comment by dhermes** [comment]
Yes, and it would only need to be changed in [one place][1] for the underlying implementation.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/e12372db34b6202d8c4f6e50d0e8b8c047f30d9d/datastore/google/cloud/datastore/client.py#L583-L611
