### ISSUE TITLE
PubSub: Synchronous pull

### ISSUE THREAD

**Issue by mwilliammyers** [GoogleCloudPlatform/google-cloud-python#4344]
After the API redesign it no longer seems possible to perform a synchronous pull on a PubSub subscription. Is the recommended way of accomplishing this in `google-cloud-pubsub` `v0.29.0` to use [`PublisherClient`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/8806a6a64c2a7f5f38a7c17de30621d6c37201ad/pubsub/google/cloud/gapic/pubsub/v1/subscriber_client.py#L47) via the [`pull`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/8806a6a64c2a7f5f38a7c17de30621d6c37201ad/pubsub/google/cloud/gapic/pubsub/v1/subscriber_client.py#L662) method directly or to write my own [`Policy`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/8806a6a64c2a7f5f38a7c17de30621d6c37201ad/pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py#L32), or some other way?

**Comment by tseaver** [comment]
@mwilliammyers The API is now [async/callback based](http://google-cloud-python.readthedocs.io/en/latest/pubsub/subscriber/index.html):  the intended usage is for the app developer to write a callback function which handles each message.

**Comment by tseaver** [comment]
Duplicate of #4338.
