### ISSUE TITLE
Bazel Build Files

### ISSUE THREAD

**Issue by justinwp** [GoogleCloudPlatform/google-cloud-python#4351]
It would be useful if this repository provided its own BUILD file to be imported into Bazel based projects. See issue in https://github.com/bazelbuild/rules_python/issues/14

**Comment by dhermes** [comment]
@justinwp AFAIK, none of the maintainers have any direct experience with Bazel. I personally used `BUILD` files **inside** Google, but that was 4+ years ago, so my experience is stale.

**Comment by lukesneeringer** [comment]
I do not really think it is incumbent on libraries to provide tooling for any build tool (other than pip). That is not something that most libraries do, and I do not really want the precedent of being on the hook for that.

I also see @duggelz is involved in the issue in Bazel itself. For now, I think the answer is a "no" here, but happy to reconsider if there is a reason I missed.
