### ISSUE TITLE
Trace: unit tests are non-deterministically broken on Windows

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#4366]
[e.g.][1]:

```
================================== FAILURES ===================================
__________________ Test__TraceAPI.test_list_traces_no_paging __________________
Traceback (most recent call last):
  File "C:\projects\google-cloud-python\trace\tests\unit\test__gax.py", line 215, in test_list_traces_no_paging
    _rfc3339_to_datetime(span['startTime']),
  File "c:\projects\google-cloud-python\.nox\default\lib\site-packages\google\cloud\_helpers.py", line 274, in _rfc3339_to_datetime
    dt_str, _RFC3339_MICROS).replace(tzinfo=UTC)
  File "c:\python27\Lib\_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '2017-11-08T21:41:48Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
1 failed, 15 passed in 0.48 seconds
```

I think this is related to #4323. I had to make changes there because of `.isoformat()` quirks on Windows. It looks like the `.00000` seems to be truncated in `.isoformat()`?

[1]: https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-python/build/1.0.2537.datastore-gapic/job/6908efk6fqr6mxc0

**Comment by duggelz** [comment]
isoformat() docs say: "Return a string representing the date and time in ISO 8601 format, YYYY-MM-DDTHH:MM:SS.mmmmmm or, if microsecond is 0, YYYY-MM-DDTHH:MM:SS"

So probably need:

```
try:
    return datetime.datetime.strptime(
        dt_str, _RFC3339_MICROS).replace(tzinfo=UTC)
except ValueError:
    return datetime.datetime.strptime(
        dt_str, _RFC3339_NO_FRACTION + 'Z').replace(tzinfo=UTC)
```

The unit test for `Test__rfc3339_to_datetime` should also manually construct some of these troublesome dates and test various round-trips.

It might not hurt to check leap-seconds either, since they will almost certainly fail.

**Comment by chemelnucfin** [comment]
Since this is from the gax library, and I do not see any `test_list_traces_no_pages` in the current library, I'm going to close this.  I have also looked at `test_list_traces` and `test_list_traces_exception` and see nothing similar.

Please open a new issue if this comes up again.
