### ISSUE TITLE
Google Speech API: Inline audio exceeds duration limit.

### ISSUE THREAD

**Issue by The-Gupta** [GoogleCloudPlatform/google-cloud-python#4384]
`transcribe_file(outputFilePath)`
Traceback (most recent call last):

  File "<ipython-input-33-4ff61ce32554>", line 30, in <module>
    transcribe_file(outputFilePath)

  File "<ipython-input-33-4ff61ce32554>", line 13, in transcribe_file
    operation = client.long_running_recognize(config, audio)

  File "D:\Anaconda3\envs\audioModule\lib\site-packages\google\cloud\gapic\speech\v1\speech_client.py", line 250, in long_running_recognize
    options), self.operations_client,

  File "D:\Anaconda3\envs\audioModule\lib\site-packages\google\gax\api_callable.py", line 452, in inner
    return api_caller(api_call, this_settings, request)

  File "D:\Anaconda3\envs\audioModule\lib\site-packages\google\gax\api_callable.py", line 438, in base_caller
    return api_call(*args)

  File "D:\Anaconda3\envs\audioModule\lib\site-packages\google\gax\api_callable.py", line 380, in inner
    gax.errors.create_error('RPC failed', cause=exception))

  File "D:\Anaconda3\envs\audioModule\lib\site-packages\future\utils\__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)

  File "D:\Anaconda3\envs\audioModule\lib\site-packages\google\gax\api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)

  File "D:\Anaconda3\envs\audioModule\lib\site-packages\google\gax\retry.py", line 68, in inner
    return a_func(*updated_args, **kwargs)

  File "D:\Anaconda3\envs\audioModule\lib\site-packages\grpc\_channel.py", line 492, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)

  File "D:\Anaconda3\envs\audioModule\lib\site-packages\grpc\_channel.py", line 440, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)

InvalidArgumentError: InvalidArgumentError(RPC failed, caused by <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, **Inline audio exceeds duration limit.** Please use a GCS URI.)>)

**CODE:**

```
import subprocess, os, io
from google.cloud import speech
from google.cloud.speech import enums
from google.cloud.speech import types

def audioToRaw(inputFilePath, tempFilePath, outputFilePath):
    try:
        os.remove(tempFilePath)
        os.remove(outputFilePath)
    except: pass    
        
    subprocess.call(['ffmpeg', '-i', inputFilePath, tempFilePath])
    
    command = "sox " \
    + tempFilePath \
    + " -t raw --channels=1 --bits=16 --rate=16000 --encoding=signed-integer --endian=little " \
    + outputFilePath  
    
    subprocess.call(command, shell=True)

def transcribe_file(speech_file):
    client = speech.SpeechClient()

    with io.open(speech_file, 'rb') as audio_file:
        content = audio_file.read()

    audio = types.RecognitionAudio(content=content)
    config = types.RecognitionConfig(
        encoding=enums.RecognitionConfig.AudioEncoding.LINEAR16,
        sample_rate_hertz=16000,
        language_code='en-US')

    operation = client.long_running_recognize(config, audio)

    print('Waiting for operation to complete...')
    response = operation.result(timeout=900)

    for result in response.results:
        print('Transcript: {}'.format(result.alternatives[0].transcript))
        print('Confidence: {}'.format(result.alternatives[0].confidence))

inputFilePath = r'C:\Users\vishal.gupta33\Desktop\TONE_ANALZER\3.mp3'
tempFilePath = r'C:\Users\vishal.gupta33\Desktop\TONE_ANALZER\temp.wav'
outputFilePath = r'C:\Users\vishal.gupta33\Desktop\TONE_ANALZER\async3_1.raw'

audioToRaw(inputFilePath, tempFilePath, outputFilePath)

transcribe_file(outputFilePath)

```

**Audio Length:** 207 seconds

Suggest the fix.

**Comment by The-Gupta** [comment]
I still don't know how to make it work for an Inline async. requests, but I found an alternative here - [https://cloud.google.com/speech/docs/async-recognize](url)

> Use asynchronous speech recognition to recognize audio that is longer than a minute and **stored in Google Cloud Storage.**

I converted (mp3) audio files to raw and uploaded to Google Cloud Storage.


Here's the code - 


```
import subprocess, os, io
from google.cloud import speech
from google.cloud.speech import enums
from google.cloud.speech import types


def transcribe_gcs(gcs_uri):
    client = speech.SpeechClient()

    audio = types.RecognitionAudio(uri=gcs_uri)
    config = types.RecognitionConfig(
        encoding=enums.RecognitionConfig.AudioEncoding.LINEAR16,
        sample_rate_hertz=16000,
        language_code='en-US')

    operation = client.long_running_recognize(config, audio)

    print('\n\n\n')
    response = operation.result(timeout=9000)

    for result in response.results:
        print('{}'.format(result.alternatives[0].transcript))

import time
t = time.time()
gcs_uri = 'gs://voicedatainfy/async7.raw'
transcribe_gcs(gcs_uri)
print("TOTAL TIME TAKEN: ", time.time()- t)

```

**Take care** while 
- passing arguments to config - encoding and sample_rate_hertz, and
- gcs_uri.

**Comment by chemelnucfin** [comment]
Thank you for posting your solution.  Please feel free to reopen this issue should the need arise.
