### ISSUE TITLE
BigQuery: add keyword arguments to job configuration constructors

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#4396]
A feature request for the BigQuery library, add keyword arguments to the job configuration constructors, like QueryJobConfig.

This will make it a bit nicer to set just one (or a few) optional parameter when starting the job.

**Comment by chemelnucfin** [comment]
@tswast what do you want to do with the kwargs?

**Comment by tswast** [comment]
This request is to make the constructors of objects in the library take in kwargs to set additional properties at initialization time.

Example:

```python
job_config = bigquery.QueryJobConfig(
    write_disposition='WRITE_TRUNCATE', destination=table_ref)
```

would be equivalent to

```python
job_config = bigquery.QueryJobConfig()
job_config.write_disposition = 'WRITE_TRUNCATE'
job_config.destination = table_ref
```

**Comment by tswast** [comment]
I've done some more thought on this one. I'm closing this as it conflicts with the Python philosophy that there should only be one way to do things.
