### ISSUE TITLE
Spanner: Python Cloud spanner read / write transactions documentation is outdated

### ISSUE THREAD

**Issue by Alan502** [GoogleCloudPlatform/google-cloud-python#4409]
# Thank you for reporting an issue to google-cloud-python!

If you are reporting an issue or requesting a feature, please search the
existing open and closed issues to see if there is already work being done.

- https://github.com/GoogleCloudPlatform/google-cloud-python/issues
- http://stackoverflow.com/questions/tagged/google-cloud-python

If you can provide us with as much of the following information as possible it
will help us identify the cause of your issue more quickly.

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
Cloud Spanner

2. OS type and version
---
3. Python version and virtual environment information `python --version`
2.7.6
4. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
0.30.0
5. Stacktrace if available
---
6. Steps to reproduce
---
7. Code example
---

The documentation on how to do read / write transactions on [this page](https://googlecloudplatform.github.io/google-cloud-python/stable/spanner/transaction-usage.html) is outdated. The [github readme](https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/spanner) has the updated documentation, but the github.io pages should also be updated.

Using GitHub flavored markdown can help make your request clearer.
See: https://guides.github.com/features/mastering-markdown/

**Comment by chemelnucfin** [comment]
@dhermes @tseaver When do the changes in transaction-usage get reflected?

**Comment by chemelnucfin** [comment]
Duplicates #3740.  Also, conversation with @dhermes says that the stable branch is not easily found.  Can be followed in #4611.

**Comment by chemelnucfin** [comment]
Thank you for reporting.
