### ISSUE TITLE
BigQuery - Table Properties are None

### ISSUE THREAD

**Issue by anshulg03** [GoogleCloudPlatform/google-cloud-python#4421]
OS : Ubuntu
google-cloud==0.30.0
google-cloud-bigquery==0.28.0
python 2.7.12

```python
dataset = bigquery_client.dataset('xxxx')

table_ref = dataset.table('xxxxxxxxx')

table = bigquery.Table(table_ref)

print table.created
```

**Comment by dhermes** [comment]
@anshulg03 So you're saying that `table.created` is `None`?

@tswast This is expected until something has been fetched, right?

**Comment by tswast** [comment]
@dhermes Yes, this is expected.

@anshulg03 I assume you are trying to create a new table? We have an example of doing this using `client.create_table()`.

https://github.com/GoogleCloudPlatform/google-cloud-python/blob/ce96e85c29e6c1af1ca0910400d92dd57cd2e496/docs/bigquery/snippets.py#L231-L239

This example is included in the [usage page of the documentation](https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/usage.html#tables).

To get a table that already exists, use `client.get_table()`.
