### ISSUE TITLE
memcache python 3.6

### ISSUE THREAD

**Issue by jorjun** [GoogleCloudPlatform/google-cloud-python#4424]
Will this library become available? Or can I use pylibmc? If so, what is the host name? I can see memcache available in all flexible environment projects, but I can't access it via localhost. Nor find any current documentation on the subject.

**Comment by dhermes** [comment]
@jorjun This repo is not for the Google App Engine libraries, sorry you've end up in the wrong place.

I'll provide some links in a follow-up to help redirect.

**Comment by dhermes** [comment]
Here is the App Engine issue tracker and related:

- https://issuetracker.google.com/issues/new?component=187191&template=1010814
- https://issuetracker.google.com/savedsearches/559750
- https://cloud.google.com/support/docs/issue-trackers

**Comment by EngineerCoding** [comment]
More specifically:
https://issuetracker.google.com/u/1/issues/73857736

One can star the issue to show that people want/need this, even though Google makes clear that one can use an external Redis server.[1]

[1]: https://cloud.google.com/appengine/docs/standard/python3/python-differences
