### ISSUE TITLE
Language API: Analyze Syntax is returning -1 for all Being Offsets on TextSpans

### ISSUE THREAD

**Issue by dvaldivia** [GoogleCloudPlatform/google-cloud-python#4425]
1. Language API
2. Linux + macOS
3. 3.6.2
4. google-cloud-language==1.0.0

After going from `google-cloud-language==0.27.0` to `google-cloud-language==1.0.0`, all the begin offset attributes are returned as `-1` instead of the proper value. So far this is reproducible by going to version 1.0.0 of the library and analyzing the syntax of a sentence using the sample code provded by https://cloud.google.com/natural-language/docs/analyzing-syntax#language-syntax-string-python.

**Comment by dhermes** [comment]
Thanks for reporting @dvaldivia!

**Comment by lukesneeringer** [comment]
You need to send the encoding type to get the offsets you want. (In Python, you usually want `utf-32`.)

We are working with the API team to auto-detect this so you do not have that annoying need.

**Comment by jicardu** [comment]
Hi, I have the same problem. But, how can I send the encoding_type in a ruby request?
I wrote:
`syntax = language.analyze_syntax content: text, type: :PLAIN_TEXT, encoding_type: 'UTF8'`
but is returning:
**Unknown field name 'encoding_type' in initialization map entry.**
can you tell me how is the correct syntax? Thank you in advance.

**Comment by chemelnucfin** [comment]
@jicardu Hi, please file your issue with the Ruby team at 
https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues
