### ISSUE TITLE
Bigquery: Permission denied with create_dataset

### ISSUE THREAD

**Issue by adampackets** [GoogleCloudPlatform/google-cloud-python#4450]
Dear devs,

I'm having an issue with the bigquery library and I'm not quite sure I understand what is happening. 

What I'm trying to achieve is deploy a Flask API to on GAE standard. The API receives JSON data and writes it to a given dataset. 

When I debug my Python script from within the shell, it all works normally. But as soon as I use 
`dev_appserver.py app.yaml --log_level debug `
I start getting `permission denied` exceptions. 

Below you can find all the information needed.

2. OS type and version
Mac OSX
3. Python version and virtual environment information `python --version`
Python 2.7.14
4. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
google-cloud==0.30.0
google-cloud-bigquery==0.28.0
5. Stacktrace if available
I only get a permission deined
7. Code example
```
from google.cloud import bigquery
from google.cloud.bigquery.schema import SchemaField

project_id = ""
client = bigquery.Client(project=project_id)
client = client.from_service_account_json("service_account.json")
dataset_ref = client.dataset("test")
dataset = bigquery.Dataset(dataset_ref)
client.create_dataset(dataset)
```

I also tried setting up the `_http` key for `bigquery.Client` to `urlfetch` but it didn't help.

I get the same error when I try to create table, or stream data to an existing table.

Thanks for your help!

**Comment by dhermes** [comment]
@adampackets The issue is your usage of `from_service_account_json`. It is a **class method**, not an instance method. So when you use

```python
client = client.from_service_account_json("service_account.json")
```

You are losing the `project_id` that you had manually set. Instead:

```python
client = bigquery.Client.from_service_account_json("service_account.json", project=project_id)
```

**Comment by dhermes** [comment]
Let us know if this doesn't solve it and we can re-open / continue discussing.

**Comment by adampackets** [comment]
Hi @dhermes, thank you for your quick reply!

Unfortunately, this does not fix the issue. I'm still getting the following exception

`('Connection aborted.', error(13, 'Permission denied'))`

when I call `client.create_dataset(dataset)`

I also tried to remove the `project_id` thinking the service account JSON already contains it but this doesn't seem to help.

Would you have any other ideas I could try?

Thanks!

**Comment by dhermes** [comment]
@adampackets Before debugging within App Engine (prod or dev server), can you use the same JSON key to create a dataset in your local console? (The reason I say this is that the dev appserver mangles outputs quite a bit.)

**Comment by jonparrott** [comment]
Also, in the interest of transparency these libraries are currently not supported on App Engine standard. They might work if you hold it *just* right, but official support is still a little ways off. You can follow #1893 for updates.

**Comment by adampackets** [comment]
Hello there,

sorry for the late reply, been busy with other stuff.

I put up a quite easy and short code to reproduce the issue:

```
from google.cloud import bigquery
client = bigquery.Client(project=project).from_service_account_json("service_account.json")
        try:
            print(list(self.client.list_datasets()))
        except Exception as ex:
            print (ex)
```

This code works fine from the local shell but does not run on either the dev or prod servers.

@jonparrott Thanks for the info, I will move to finding another solution until official support is present.

Adam.

**Comment by adampackets** [comment]
Just found out that the client doesn't actually get a access token when run from the dev server. The following shows it

```
client = bigquery.Client(project=project).from_service_account_json("service_account.json")
print(client._credentials.token)
```

From my terminal, this returns an access token while from the dev server it returns None.

I hope this helps

**Comment by dhermes** [comment]
@adampackets A credentials object will get a token only after refresh is called.

**Comment by adampackets** [comment]
That's what I was trying to do at the moment with the following

```
from google.auth.transport.requests import Request
request = Request()
  try:
            client._credentials.refresh(request)
            print ("Token after refresh {}".format(.client._credentials.token))
except Exception as ex:
            print ("Token refresh doesn't work")
            print (ex)
```

But I still get a permission denied...

**Comment by dhermes** [comment]
@adampackets See https://github.com/dhermes/google-auth-on-gae for an example of how `google-auth` works on App Engine.
