### ISSUE TITLE
BigQuery snippets have started failing "consistently"

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#4457]
See the 3 most recent BigQuery builds on `master`:

- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/4382
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/4388
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/4390

**Comment by tswast** [comment]
Yeah, that looks pretty consistent. Investigating.

**Comment by tswast** [comment]
I think BigQuery may have started validating access entry updates recently. I'll see if I can dig up a valid domain / email we can use for a sample.
