### ISSUE TITLE
PubSub: (Python)  How to use JSON string as the credential  for Client initialization instead of the filepath

### ISSUE THREAD

**Issue by reselbob** [GoogleCloudPlatform/google-cloud-python#4477]
Is it possible to use just the JSON authentication credentials instead of a declaring the path to the file the contains the JSON, like so with the Python SDK library:

```python
import os
from google.cloud import pubsub
json_string = os.environ['PUBSUB_JSON']
creds = json.loads(json_string)
client = pubsub.PublisherClient(credentials=creds)
```

I can do this  technique in Node, but I am having trouble figuring out how to do the JSON only initialization in Python.

Thanks in advance.

**Comment by dhermes** [comment]
@reselbob Thanks for asking, here is how you'd accomplish that:

```python
import json
from google.oauth2 import service_account

info = json.loads(json_string)
credentials = service_account.Credentials.from_service_account_info(info)
```

Though rather than setting the `PUBSUB_JSON` environment variable, you could just set the`GOOGLE_APPLICATION_CREDENTIALS` environment variable and then

```python
import google.auth

credentials, project = google.auth.default()
```

will do exactly what you want.

In general, future questions like this may be better asked on https://github.com/GoogleCloudPlatform/google-auth-library-python/.

**Comment by dhermes** [comment]
I have closed the issue since (AFAICT) I have answered your question. If this is not the case, I'm happy to continue discussing and / or re-open.

**Comment by reselbob** [comment]
Help?

Set GOOGLE_APPLICATION_CREDENTIALS to what, the JSON?

**Comment by dhermes** [comment]
See: https://googlecloudplatform.github.io/google-cloud-python/latest/core/auth.html

I now realize you had set `PUBSUB_JSON` to the string itself rather than to a file containing the string.

**Comment by reselbob** [comment]
Right, I just want to use the JSON string, not the file path. I looked at the link you provided. Seeing a lot of language about using the file path. Can't seem to locate an example about how to use the JSON string. But,  might be missing something.

**Comment by dhermes** [comment]
My first example (with `from_service_account_info()`) should work just fine if you already have the key file loaded as a JSON string.

**Comment by reselbob** [comment]
I am having a problem
       ` json_string = os.environ['PUBSUB_JSON']`
       ` info = json.loads(json_string)`
        `creds = service_account.Credentials.from_service_account_info(info)`
` `
        `client = pubsub.PublisherClient(credentials=creds)` 
        `topic_path = client.topic_path(os.getenv('GOOGLE_CLOUD_PROJECT'), 'cron_job_topic')`
       ` data = data.encode('utf-8')`
       ` future = client.publish(topic_path, data=data)`

gives me an error:

`google.auth.exceptions.RefreshError: ('invalid_scope: Empty or missing scope not allowed.', '{\n  "error" : "invalid_scope",\n  "error_description" : "Empty or missing scope not allowed."\n}')`

The JSON in question works fine when loaded from file.

**Comment by dhermes** [comment]
See my answer in https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/225. Also note that you may have discovered a "bug" in Pub / Sub (#4479).

**Comment by itsPav** [comment]
Is using env variables safer/more secure than using the json file?
What difference does it really make?

**Comment by ethagnawl** [comment]
> What difference does it really make?

When using environment variables, you never have to worry about credentials mistakenly being leaked via VCS.

**Comment by aaronamm** [comment]
@dhermes Thank you so much.
