### ISSUE TITLE
Pub/Sub Subscriber Client.subscribe() may drop callback on the floor

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#4487]
From [source][1]

```python
    def subscribe(self, subscription, callback=None, flow_control=()):
        ...
        if callable(callback):
            subscr.open(callback)
```

Instead it should be something like:

```python
if callback is not None:
    if callable(callback):
        subscr.open(callback)
    else:
        raise TypeError('Hey man, that is not, like, callable, man.')
```

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/cc7da65b4a31d7a33055afe0bd6dc9855c3d6493/pubsub/google/cloud/pubsub_v1/subscriber/client.py#L130-L131

**Comment by chemelnucfin** [comment]
class A:
  def __init__(self):
    pass
a=A()
Seems like callable(None), callable(345) and callable(a) all return False?
