### ISSUE TITLE
Storage: Expose preconditions via the google-cloud-storage API

### ISSUE THREAD

**Issue by brennie** [GoogleCloudPlatform/google-cloud-python#4490]
It would be very useful if google-cloud-storage exposed a way to set preconditions on upload. I am currently hacking around this by replacing `google.cloud.storage.blob. _MULTIPART_URL_TEMPLATE` and `google.cloud.storage.blob._RESUMABLE_URL_TEMPLATE` with versions that have the precondition I require, e.g.

```python
from google.cloud import storage as gcs

gcs.blob._MULTIPART_URL_TEMPLATE = (
    f'{gcs.blob._MULTIPART_URL_TEMPLATE}&ifGenerationMatch=0'
)
gcs.blob._RESUMABLE_URL_TEMPLATE = (
    f'{gcs.blob._RESUMABLE_URL_TEMPLATE}&ifGenerationMatch=0'
)
```

Luckily I am only uploading blobs that I do not want to exist beforehand. It would be great if there were a way to programmatically do this, but I could not find anything after pouring over the documentation and source code.

I hope you'll implement this in a future version.

Thanks for your time!

**Comment by dhermes** [comment]
Thanks for the request @brennie this is definitely something worth adding!

**Comment by bits01** [comment]
Thanks for posting the hack, very useful until the feature is implemented.

**Comment by tseaver** [comment]
For uploads, there are three cases:

- Do not pass the `ifGenerationMatch` query string parameter (this would need to be the default for backward-compatibility)
- Pass `&ifGenerationMatch=0` if there is no generation set on the blob resource.
- Pass `&ifGenerationMatch=<current-generation>` if there is a generation set.

After a chat with @frankyn, I'm closing this issue:  he will be working with the GCS team to prioritize more complete precondition support in our feature backlog.

**Comment by amygdala** [comment]
Is there an ETA for this?
