### ISSUE TITLE
Monitoring: sending metrics in a non-blocking/buffered way

### ISSUE THREAD

**Issue by gciotta** [GoogleCloudPlatform/google-cloud-python#4491]
Hi there!

We're considering using this library to send metrics to Stackdriver monitoring.

I'm a bit concerned because the monitoring library seems to send metrics with a [synchronous HTTP connection](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/monitoring/google/cloud/monitoring/client.py#L66), thus coupling our services very tightly to Stackdriver and requiring a round-trip for each metric being sent.

In the the logging library, a [background thread](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging/handlers/transports/background_thread.py#L17) seems to be used in order to buffer data locally before flushing it asynchronously.

Is there a built-in/suggested way to achieve a similar behaviour with metrics? I was considering subclassing the [Client](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/monitoring/google/cloud/monitoring/client.py#L52) class to do it.

**Comment by dhermes** [comment]
@waprin Do you know the right person to direct this to?

**Comment by waprin** [comment]
The monitoring library is being deprecated (despite my objections) and will be deleted so I would not recommend using it.

**Comment by waprin** [comment]
I wanted to add the background thread transport but the higher level decision was to move forward with the autogen GAPICs.

**Comment by gciotta** [comment]
@waprin is the alternative you're mentioning already in a usable state? Thanks!

**Comment by waprin** [comment]
https://pypi.python.org/pypi/gapic-google-monitoring-v3 AFAIK it's still missing docs/samples and has some rough edges but should be usable.

**Comment by gciotta** [comment]
We'll have a look at it. I'm closing the issue in the meantime. Thanks for your help.
