### ISSUE TITLE
Is HTTP/2 Supported?

### ISSUE THREAD

**Issue by william-silversmith** [GoogleCloudPlatform/google-cloud-python#4505]
Hi,

My lab is using Google Storage as a large image server, and we cut out the images into lots of chunks to fetch. I wrote a multithreaded client that can grab the chunks, but when the chunks are small enough, it seems the HTTP/1.1 overhead starts to become a significant issue and download speed falls dramatically. This is a classic use case for HTTP/2. Is there a way to fetch files using HTTP/2 streams that I'm not aware of? 

I did some searching around and it seems that grpc might already support HTTP/2. https://www.slideshare.net/GuoJing8/http2-and-grpc. I am also investigating using hyper to create requests session objects ((https://hyper.readthedocs.io/en/latest/quickstart.html#requests-integration) to pass into Client (https://googlecloudplatform.github.io/google-cloud-python/latest/storage/client.html).

Thanks again for your help @dhermes and co. :)

Will

**Comment by dhermes** [comment]
@william-silversmith As far as I know, the only server APIs for Storage are over HTTP/1.1.

gRPC is HTTP/2 **only** and all APIs with protobuf definitions in https://github.com/googleapis/googleapis will have gRPC server APIs (defined by those `.proto` files).

Sorry the answer couldn't be yes.

I am going to close this out, as the question seems to be answered. I'm happy to re-open / continue discussing if I'm mistaken.
