### ISSUE TITLE
Firestore DocumentReference.get NotFound error should be configurable

### ISSUE THREAD

**Issue by sourcec0de** [GoogleCloudPlatform/google-cloud-python#4530]
### Firestore 

`DocumentReference.get` throws an error instead of returning a `DocumentSnapshot` that has a property of `exists`.

This seems inconsistent with the other firebase firestore clients in that if you call `.get` it returns a snapshot where you can check the `exists` property rather than having to wrap it in a `try:catch`.

Is this something the library plans to support?

**Comment by chemelnucfin** [comment]
Hi, I'm going to take a stab at this question.  I think that using `try except` is just as preferable or even more so than using `if else`.  From the standard docs 
https://docs.python.org/3.6/glossary.html#term-eafp

> EAFP
> Easier to ask for forgiveness than permission. This common Python coding style assumes the existence of valid keys or attributes and catches exceptions if the assumption proves false. This clean and fast style is characterized by the presence of many try and except statements. The technique contrasts with the LBYL style common to many other languages such as C..
> 

Please feel free to reopen if you'd like to discuss further.

**Comment by dhermes** [comment]
@sourcec0de We are not opposed to it, but as @chemelnucfin notes we felt the extra wrapping was unnecessary / not Pythonic. The current interface isn't something that we refuse to change though.

**Comment by sourcec0de** [comment]
I want to say great work first and foremost.
Thank you for giving me an opportunity to just raise some questions. 

I realize the firebase client libraries are really designed to be idiomatic. However, after using some of the other SDK's with similar APIs it was a little unexpected to see an exception here.

I would agree that in python raising an exception is the standard idiom and `EAFP` is a good method to live by if the code you're executing is prone to `exceptions`. But if we know there is only a single possible error `NotFound` then it feels a little heavy handed to wrap in a `try:catch`.

`LBYL` feels like the better option here.

But I'm not proposing you change the default behavior, I'm simply asking if it makes sense to add a keyword argument to `ignore_notfound`

I would expect an example like this to work well if we simply returned a `document snapshot` that contained an empty dictionary and `exists: False`. Pythons `dictionary.get` allows me to set the default value without throwing an exception.

Having to introduce a `try:catch` also introduces a write really early on in a transaction that doesn't support read after write.

```python
@firestore.transactional
def debit_account(tx, account, amount):
    walletRef = wallets.document(account)
    walletSnap = walletRef.get(transaction=tx, ignore_notfound=True)
    wallet = walletSnap.to_dict()
    tokens = wallet.get('tokens', 0)

    if amount < 0 and tokens < abs(amount):
        return WalletCodes.INSUFFICIENT_FUNDS

    tokens += amount

    tx.set(walletRef, {
        'tokens': tokens
    }, firestore.CreateIfMissingOption(True))

    return WalletCodes.SUCCESSFUL_DEBIT
```


## Examples from other libraries

### JS
`docsnap` has a property `exists`

```js
let docsnap = await cityRef.get()
```

### Java
`docsnap` has a method `exists` 
```java
DocumentSnapshot docsnap = future.get()
```

### Go
`docsnap` is an empty interface and `err` can be simply ignored
```go
docsnap, _ := client.Doc("Wallets/{UID}").Get(ctx)
```

**Comment by chemelnucfin** [comment]
@sourcec0de I'm all for having consistent behavior across languages.  But there doesn't seem to be much interest at #4531 at this time, unfortunately.

**Comment by sourcec0de** [comment]
@chemelnucfin not a problem. Just something I thought would be interesting to have a conversation about.

In the end, I decided it would be better to ensure those documents existed before trying to run transactions anyway. The `try:catch` method isn't cumbersome.

Thank you guys for reviewing my comments.
I appreciate your candor.
