### ISSUE TITLE
Datastore: what does it take to explicitly rollback a transaction?

### ISSUE THREAD

**Issue by rvandegrift** [GoogleCloudPlatform/google-cloud-python#4541]
What does it take to explicitly rollback a transaction?  For instance, I'm surprised that this doesn't work:

```python
>>> from google.cloud import datastore
>>> db = datastore.Client()
>>> e = datastore.Entity(db.key('Thingy'))
>>> with db.transaction() as t:
...     t.put(e)
...     t.rollback()
...
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/ross/.local/lib/python3.5/site-packages/google/cloud/datastore/batch.py", line 301, in __exit__
    self.commit()
  File "/home/ross/.local/lib/python3.5/site-packages/google/cloud/datastore/transaction.py", line 233, in commit
    super(Transaction, self).commit()
  File "/home/ross/.local/lib/python3.5/site-packages/google/cloud/datastore/batch.py", line 270, in commit
    raise ValueError('Batch must be in progress to commit()')
ValueError: Batch must be in progress to commit()

```

Replacing `t.rollback()` with `raise Exception` works - but I don't always want to raise an unhandled exception to end a transaction.

I'm using `google-cloud-datastore` 1.4.0 with python 3.5.3.

**Comment by chemelnucfin** [comment]
Do you have an example of when you would explicitly call rollback?  I think the context manager is there to make sure that you rollback a transaction if an exception happens.  Once the transaction is rolled back it cannot be used again.  It might be the best solution to raise an Exception if you do want to roll it back.

Otherwise you can do
`t.begin()`
`t.put(e)`
`t.rollback()`

Did I miss anything @dhermes @tseaver?

**Comment by rvandegrift** [comment]
Raising an exception will  work, but requires an external try/except block:
```python
try:
    with db.transaction() as t:
       # do stuff, encounter a failure
       raise Exception
except Exception:
    pass
```
That could be avoided if I could call `t.rollback()`.

But if this breaks because it's reusing the transaction object, it'd be sufficient to document that if you use the context manager, you shouldn't mess with the transaction object.

There's also a minor confusion caused by the Google Cloud Datastore docs.  They imply that all consumers should explicitly rollback their own transactions in case of failure.  From https://cloud.google.com/datastore/docs/concepts/transactions:
```
Note that in order to keep our examples more succinct we sometimes omit the rollback if the transaction fails. In production code it is important to ensure that every transaction is either explicitly committed or rolled back.
```
I guess that's probably false in this case, since the SDK is doing it for me.

**Comment by tseaver** [comment]
@rvandegrift If you want to explicitly call `Transaction.rollback` (and likely also `Transaction.commit`), then don't use the context manager.  E.g.:

```python
from google.cloud import datastore
db = datastore.Client()
e = datastore.Entity(db.key('Thingy'))
t = db.transaction()
t.begin()
t.put(e)
if something_is_wrong():
    t.rollback()
else:
    t.commit()
```
