### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in C:\Users\esmer\AppData\Local\Temp\pip-build-spxq918q\Twisted\

### ISSUE THREAD

**Issue by aldaaga** [GoogleCloudPlatform/google-cloud-python#4547]
Hi,
I'm trying to install to install Scrapy on Python 3.6.3 and I already installed Anaconda.
I'm receiving an error as below:
Command "python setup.py egg_info" failed with error code 1 in C:\Users\esmer\AppData\Local\Temp\pip-build-spxq918q\Twisted\

I'm not sure what's the problem as didn't do anything rather than that.
I have had installed and uninstalled Python, Anaconda & Scrapy though.

Does anyone have any clue? Thank you!

**Comment by chemelnucfin** [comment]
Hello, I believe you are at the wrong repo.  Here is Scrapy's repo.
https://github.com/scrapy/scrapy/issues
