### ISSUE TITLE
Unable to load utf-8 data to cloud storage: blob.upload_from_filename('jsonfile')

### ISSUE THREAD

**Issue by jaehancrate** [GoogleCloudPlatform/google-cloud-python#4555]
Hello, 
OS: WINDOWS
PYTHON VERSION: PYTHON 2.7

I am having issues loading a json file to Google Cloud Storage. When I view the file itself I can see that the JSON file contains the correct representation of the image. 

Here is an excerpt of my code:
```python
storage_client = storage.Client(project=projectID)
print('Creating a storage client via Python SDK for BQ')

bucket_name = 'product_temp_bucket'
source_file_name = 'data.json'
destination_blob_name = 'ProductTemp'

bucket = storage_client.bucket(bucket_name)
print('Bucket {} accessed.'.format(bucket.name))

blob = bucket.blob('ProductTemp')
blob.upload_from_filename('data.json')
```
Has anyone else had this issue before? I am confused because the source files that I use to create data.json as well as the output file both have utf-8 encoding... and it looks fine when I view the product myself. 

I thought initially it was my system having issues parsing the data... but I can see that the file shows the correct encoding for the characters. 

![image](https://user-images.githubusercontent.com/20776752/33741533-6026ad92-db6a-11e7-9ebd-de2ed0760e0e.png)

**Comment by dhermes** [comment]
@jaehancrate Could you upload a snippet of the file and provide a stacktrace? We open files as raw bytes, so the encoding shouldn't matter.

**Comment by jaehancrate** [comment]
Sure thing. Here you go. To be clear no errors were thrown in the process.. it just shows up jumbled in the BQ UI. 
[data_sample.txt](https://github.com/GoogleCloudPlatform/google-cloud-python/files/1540857/data_sample.txt)

**Comment by dhermes** [comment]
@jaehancrate You probably need to set the content type before uploading:

```python
blob.upload_from_filename('data.json', content_type='text/plain')
```

If that doesn't work, one of `text/plain; charset=utf-8` or `application/json` may be the content type you need.

**Comment by dhermes** [comment]
@jaehancrate I am going to close this issue since there isn't any issue with the library.

I'm happy to continue discussing here though.

**Comment by jaehancrate** [comment]
Got it sounds good, I appreciate your help!

**Comment by dhermes** [comment]
I'm curious which `content_type` is the correct one, if you don't mind sharing

**Comment by jaehancrate** [comment]
@dhermes So that definitely worked.. I can see that the values are populated properly when I download the file from GCS. 

However, when I try to push from GCS to BigQuery I get stuck in the RUNNING state for the job. 

`
bigquery_client = bigquery.Client(project=projectID).from_service_account_json(
    r"key.json")


dataset = bigquery_client.dataset('base_data')
table = dataset.table('Product')

job = bigquery_client.load_table_from_storage('FINALPUSH', table, 'gs://product_temp_bucket/ProductTemp')
job.source_format = 'NEWLINE_DELIMITED_JSON'

print('Starting: {} '.format(job.name))
job.begin()
`

Has this been deprecated? I am no longer seeing load_table_from_storage on the API

**Comment by jaehancrate** [comment]
![image](https://user-images.githubusercontent.com/20776752/33774033-8a5768aa-dbff-11e7-8f5e-c82df751f999.png)


That is what I used per the [python doc samples](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/load_data_from_gcs.py)

This is the response I get

![image](https://user-images.githubusercontent.com/20776752/33774056-a183fc46-dbff-11e7-841b-9a9f355a6580.png)


Any idea what's going on?

**Comment by dhermes** [comment]
@jaehancrate The BigQuery API surface has changed a great deal. I'd recommend starting with the [docs][1]. (I'm not very familiar with the API surface, sorry.)

@tswast Can you point to the migration doc?

[1]: https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/usage.html

----

PS The following code doesn't do what you think it does:

```python
bigquery.Client(project=project_id).from_service_account_json('key.json')
```

Calling `bigquery.Client(project=project_id)` constructs an **instance** with the `project` set so `project_id`, but then using `from_service_account_json` on that instance **still** calls the factory constructor from the **class** (a so-called `@classmethod`). This means the output of `from_service_account_json()` will not incorporate the `project_id` (unless that project ID is also part of `key.json`, which would just be a coincidence).

```python
>>> import json
>>> with open('key.pem', 'r') as file_obj:
...     private_key = file_obj.read()
... 
>>> json_key = {
...     'project_id': 'a-different-one',
...     'private_key': private_key,
...     'client_email': 'name@example.com',
...     'token_uri': 'https://example.com',
... }
>>> with open('key.json', 'w') as file_obj:
...     json.dump(json_key, file_obj)
... 
>>> from google.cloud import bigquery
>>> client1 = bigquery.Client(project='right-here')
>>> client2 = client1.from_service_account_json('key.json')
>>> client1.project
'right-here'
>>> client2.project
'a-different-one'
```

**Comment by tswast** [comment]
The relevant section in the migration guide is here:
https://cloud-dot-devsite.googleplex.com/bigquery/docs/python-client-migration#loading_data_from_google_cloud_storage

You're right that `load_table_from_storage()` was renamed to `load_table_from_uri()` in version 0.28.0. Perhaps you aren't using the latest version of the `google-cloud-bigquery` library?

The reason for the rename is that according to the [REST docs](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load.sourceUris) for `configuration.load.sourceUris`, Bigtable URIs are also supported (though I haven't tried those yet).
