### ISSUE TITLE
Pub/Sub user-visible retryable errors

### ISSUE THREAD

**Issue by mdietz94** [GoogleCloudPlatform/google-cloud-python#4571]
User reports seeing 503 (UNAVAILABLE) errors surface in version 0.30.0 even though retryable error codes (such as this one) should not be surfaced to the user. See the below link for more details from the StackOverflow post.

https://stackoverflow.com/questions/47673193/google-pubsub-message-duplication

**Comment by dhermes** [comment]
I'm inclined to say that the 503 issue is one resolved in the [`0.29.1`][1] (partially) and [`0.29.2`][2] releases of `google-cloud-pubsub`. The `google-cloud==0.30.0` release mentioned in the SO question doesn't narrow it down much.

Even though the question was asked December 6, which is 6 days after `0.29.2` was released, I'm inclined to guess that the user had an older version.

As for the duplicate messages, I'm still trying to make a simple but "correctly reproduced" case in https://github.com/dhermes/google-cloud-pubsub-performance

@mdietz94 I think we should close this issue as the actual report here is just the 503. WDYT?

[1]: https://pypi.org/project/google-cloud-pubsub/0.29.1/
[2]: https://pypi.org/project/google-cloud-pubsub/0.29.2/

**Comment by mdietz94** [comment]
Seems fair to me if earlier than 0.29.2 was in the 0.30.0 google-cloud release. If it appears again we can investigate further.

The duplicate part of the question is relatively well understood, and several mitigations may help over the next month or so.

**Comment by dhermes** [comment]
Indeed, the [whole `0.29.x` series][1] is in the `0.30.0` release.

For anyone reading this (Max included), I recommend **explicitly** using the `google-cloud-{PKG}` packages directly rather than using the massive umbrella package `google-cloud`.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/0.30.0/setup.py#L63
