### ISSUE TITLE
Logging: expose "uniqueWriterIdentity" for creating sinks

### ISSUE THREAD

**Issue by polleyg** [GoogleCloudPlatform/google-cloud-python#4578]
Derived from SO question [here](https://stackoverflow.com/questions/47769820/how-to-set-uniquewriteridentity-true-on-sink-create).

To create sinks cross-project, `uniqueWriterIdentity` (see [here](https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.sinks/create)) needs to be set to `true`, otherwise the following error is thrown:

`google.gax.errors.RetryError: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, The destination project must be the same as the sink's project. Use uniqueWriterIdentity=true to allow cross project exports.)>)`

Currently this is not supported by the SDK. Coalescing logs/sinks to a single (admin) project is common pattern, so it should be available.

Until it's supported, it should also be clearly documented that it's not possible to use this SDK to create sinks cross-project.

**Comment by dhermes** [comment]
Closed by #4595.
