### ISSUE TITLE
Bad links in the Monitoring "usage.html" doc

### ISSUE THREAD

**Issue by mtabasko** [GoogleCloudPlatform/google-cloud-python#4593]
I ran a link-checker program over our Cloud Monitoring docs, and I got back notes saying that this document, https://googlecloudplatform.github.io/google-cloud-python/latest/monitoring/usage.html, has bad links into our Monitoring docs.

E,https://cloud.google.com/monitoring/api/ref_v3/rest/v3/%20projects.metricDescriptors,https://googlecloudplatform.github.io/google-cloud-python/latest/monitoring/usage.html,404 Not Found
E,https://cloud.google.com/monitoring/api/ref_v3/rest/v3/%20projects.groups,https://googlecloudplatform.github.io/google-cloud-python/latest/monitoring/usage.html,404 Not Found
E,https://cloud.google.com/monitoring/api/ref_v3/rest/v3/%20projects.groups.members,https://googlecloudplatform.github.io/google-cloud-python/latest/monitoring/usage.html,404 Not Found

The problem appears to be a space (%20 in the URLs) in the links to the cloud.google.com/monitoring/api/ref_v3/rest/v3/ documents.

When I look at the Github document, I can definitely see the space in the links. Just wanted to let you know!

**Comment by dhermes** [comment]
Thanks for reporting.

This issue is actually caused by backslash continuations adding spaces to the links, e.g.:

```
.. _custom metrics: https://cloud.google.com/monitoring/custom-metrics/
.. _Metric Descriptors:
    https://cloud.google.com/monitoring/api/ref_v3/rest/v3/\
    projects.metricDescriptors
```

I have run into this issue recently in another project of mine and haven't found a satisfying fix. @jonparrott and I had previously understood the continuation to "just work" but unfortunately it works by adding a single space.

**Comment by jonparrott** [comment]
Aww man. I'm not sure what to do here.

**Comment by mtabasko** [comment]
Me either. That's certainly a common-enough continuation convention. I
would have expected that to work, too.

On Thu, Dec 14, 2017 at 3:44 PM, Jon Wayne Parrott <notifications@github.com

**Comment by dhermes** [comment]
I think many browsers and / or basic HTML / content servers just ignore the space? That's why it seems to work most of the time?

In the case of monitoring, these long lines are in an RST file, so going over 80 chars won't break the lint bank.

**Comment by tmatsuo** [comment]
Unfortunately the link is broken with chrome. Yeah can you just have a long single line for an easy fix?

**Comment by jonparrott** [comment]
since its in the RST, yeah, I'm wondering if any inline comments are different.
