### ISSUE TITLE
Mismatches of properties between Table obtained from Client.list_tables and TableReference obtained from QueryJob.destination

### ISSUE THREAD

**Issue by AbdouSeck** [GoogleCloudPlatform/google-cloud-python#4605]
### Background:

I was trying to answer this [stackoverflow question](https://stackoverflow.com/questions/47838558/how-to-get-saved-query-from-view-in-bigquery) whose goal is to try and obtain the query that created a particular view. As such, my line of thinking was to find the `QueryJob` object whose `destination` attribute yields a `TableReference` pointing to the view whose sql statement I am after. Once the `QueryJob` object is found, then I can use its `query` attribute to get the sql statement.

### Code:

```python
from google.cloud import bigquery

my_view_id = 'view_table_id'
my_project = 'my project'
bq_client = bigquery.Client(my_project)

for job in bq_client.list_jobs():
    if job.destination.table_id == my_view_id and job.destination.project == my_project:
        print(job.query)
        break
```

### First Issue:

The snippet above does not yield anything. This is because `job.destination` returns a `TableReference` object whose `table_id` attribute yields something completely different from the actual view's `table_id`. This got me thinking that perhaps this is because `job.destination` is just a `TableReference` and therefore does not have all the necessary properties. As a result, I decided that I should get the actual table and try making the comparison again.

### Attempted fix:

```python
from google.cloud import bigquery

my_view_id = 'view_table_id'
my_project = 'my project'
bq_client = bigquery.Client(my_project)

for job in bq_client.list_jobs():
    try:
        actual_table = bq_client.get_table(bigquery.Table(job.destination))
    except:
        continue
    if actual_table.table_id == my_view_id and actual_table.project == my_project:
        print(job.query)
        break
```

### Second Issue:

This snippet also fails to get the query for my targeted view. Even getting the `Table` object does not refresh the `table_id` attribute.

### Questions:

1. How do we go about refreshing the `table_id` attribute to make sure we can find the `QueryJob` that created our targeted view?

2. Is there a better way of getting the query without having to rely on finding the job that created the view?

Thank you,

Abdou

**Comment by tswast** [comment]
I believe this was answered in the [StackOverflow question](https://stackoverflow.com/a/47842039/101923).

Summarizing here:

> How do we go about refreshing the table_id attribute to make sure we can find the QueryJob that created our targeted view?

The `destination` property refers to where the query results *go*. All queries write to a table: if a destination is not specified at query time, a temporary table is created.

To create a TableReference to your view, create one the same way you do any other TableReference.

```
dataset_ref = client.dataset('my_dataset', project='optional_project_id')
view_table_ref = dataset_ref.table('my_view_id')
```

> Is there a better way of getting the query without having to rely on finding the job that created the view?

Get the table with [`Client.get_table(table_ref)`](https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/reference.html#google.cloud.bigquery.client.Client.get_table) and get the original query with the [`Table.view_query` property](https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/reference.html#google.cloud.bigquery.table.Table.view_query)
