### ISSUE TITLE
extract_table does not check that the job config is an ExtractJobConfig

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#4622]
See: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1281

    bigquery_client = bigquery.Client()
    dataset_ref = bigquery_client.dataset(dataset_id)
    table_ref = dataset_ref.table(table_id)

    job_config = bigquery.LoadJobConfig()
    job_config.source_format = 'NEWLINE_DELIMITED_JSON'

    job = bigquery_client.extract_table(table_ref, destination, job_config=job_config)

    job.result()  # Waits for job to complete

    print('Exported {}:{} to {}'.format(
        dataset_id, table_id, destination))

Fails with an error

```
google.api_core.exceptions.BadRequest: 400 Operation cannot be performed on a nested schema
```

Whereas it should fail because the `job_config` argument is a `LoadJobConfig`, not a `ExtractJobConfig`.

**Comment by tswast** [comment]
Note, this issue likely applies to the other methods on `Client` that have a `job_config` argument.

/cc @alixhami

**Comment by tswast** [comment]
My thought on this: we should change how we convert to/from the [Load/Query/Copy/Extract]JobConfig classes' API representation.

The current way is to return the `job.configuration.[load|query|copy|extract]` dictionary 

```
{ 'writeDispostion': 'WRITE_TRUNCATE', ... }
```

Currently the Job class add the [load|query|copy|extract] key (plus moves up shared options such as `dryRun` to the `configuration` dictionary. I propose we return the whole configuration dictionary.

```
{ 'load': { 'writeDispostion': 'WRITE_TRUNCATE', ... }}
```

Then the BigQuery backend can complain when it gets two job types in the same resource. Also, it will make it easier to implement new properties that are shared among all job configuration types such as 'labels'.

**Comment by jonparrott** [comment]
Can we make that change without breaking the interface? If not, we should do that ASAP

**Comment by tswast** [comment]
There's gonna be some slight breakage that I know will bubble up to `pandas-gbq`. That's why it's on my mind today.

Yep, let's do it ASAP. Starting on it now.

**Comment by tswast** [comment]
Got the LoadJob done. In the branch at https://github.com/tswast/google-cloud-python/tree/issue-4622-bq-api-repr

I think it'll make sense to get the other job types done before mailing the PR.
