### ISSUE TITLE
Inconsistent nox session names

### ISSUE THREAD

**Issue by duggelz** [GoogleCloudPlatform/google-cloud-python#4645]
These three nox.py files have not been updated to use the new session names like `unit(py='2.7')`, and still use the old names like `unit_tests(py='2.7')`

- bigquery_datatransfer/nox.py
- container/nox.py
- dataproc/nox.py

**Comment by dhermes** [comment]
@lukesneeringer This is also a de-facto bug report for the generator.

**Comment by chemelnucfin** [comment]
The manual change is done, the autogenerator change is here
https://github.com/googleapis/toolkit/issues/1768

**Comment by chemelnucfin** [comment]
Since this is now tracked in [Cleanup](https://github.com/GoogleCloudPlatform/google-cloud-python/projects/9#card-6868229) and also is reported in the toolkit repository, I will close this issue.
