### ISSUE TITLE
attempting to run Quickstart.py

### ISSUE THREAD

**Issue by BardiaAfshin** [GoogleCloudPlatform/google-cloud-python#4649]
Downloaded the latest google-cloud-python and followed the instructions to run Quickstart.py. 

```
GOOGLE_APPLICATION_CREDENTIALS=/my/secret/key.json python quickstart.py

```

I get error
```
ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE
```

help?

**Comment by dhermes** [comment]
@BardiaAfshin Could you point out where you've gotten `quickstart.py`?

**Comment by chemelnucfin** [comment]
Hello, is this issue still a problem for you?

**Comment by chemelnucfin** [comment]
Please let us know if there are still problems.  Thanks!
