### ISSUE TITLE
BigQuery: How to write results to a partitioned table?

### ISSUE THREAD

**Issue by zero-master** [GoogleCloudPlatform/google-cloud-python#4659]
BigQuery APIs enables writing to a partitioned table, see: https://cloud.google.com/bigquery/docs/creating-partitioned-tables

```
{ // Job resource
  ...
  "configuration" : {
    ...
    "query" : {
      ...
      "destinationTable": {
        "projectId": "myproject",
        "datasetId": "mydataset",
        "tableId": "new_table"
      },
      "timePartitioning": {
        "type": "DAY"
      }
    }
  }
}
```

How can specify a partitioning scheme as above:

``` python
    job_config = bigquery.QueryJobConfig()
    # Set configuration.query.destinationTable
    dest_dataset = 'YOUR_DATASET'
    dest_table_name = 'YOUR_TABLE'
    destination_dataset = client.dataset(dest_dataset)
    destination_table = destination_dataset.table(dest_table_name)
    job_config.destination = destination_table
    # Set configuration.query.createDisposition
    job_config.create_disposition = 'CREATE_IF_NEEDED'
    # Set configuration.query.writeDisposition
    job_config.write_disposition = 'WRITE_APPEND'
    # Start the query
    job = client.query(query, job_config=job_config)
    # Wait for the query to finish
    job.result()
```

**Comment by tswast** [comment]
To write to a specific query partition, use the full partition name as the table name. In your example,

    dest_dataset = 'YOUR_DATASET'
    dest_table_name = 'YOUR_TABLE$20180103'
    destination_dataset = client.dataset(dest_dataset)
    destination_table = destination_dataset.table(dest_table_name)

FYI: this kind of question could be better suited for [StackOverflow using the google-cloud-bigquery tag](https://stackoverflow.com/questions/tagged/google-bigquery).
