### ISSUE TITLE
Bigtable: how to simplify the retry pattern 

### ISSUE THREAD

**Issue by zakons** [GoogleCloudPlatform/google-cloud-python#4660]
For PR #4662, we want to find a concise way of retrying any gRPC request, based on the receipt of a previous exception.  This was done for row.commit() by creating a RetryCommit class to 1) retain state information for retrying the request and 2) provide a `__call__()` method which will actually retry the request:
```
class RetryCommit:
    def __init__(self, table, request_pb):
        """
        :param table:
        :param request_pb:
        """
        self.table = table
        self.request_pb = request_pb

    def __call__(self):
        """
        :return: raise exception for MutateRow
        """
        client = self.table._instance._client
        client._data_stub.MutateRow(self.request_pb)
```
In DirectRow.commit(), 1) create the request, 2) create the retry, identifying the exceptions for which to retry, 3) start the retry code (including first request), 4) catch timeouts on the retry, as below:

```
        request_pb = messages_v2_pb2.MutateRowRequest(
            table_name=self._table.name,
            row_key=self._row_key,
            mutations=mutations_list,
        )

        retry_commit = RetryCommit(self._table, request_pb)
        retry_ = retry.Retry(
            predicate=retry.if_exception_type(exceptions.GrpcRendezvous),
            deadline=30)

        try:
            retry_(retry_commit)()
        except exceptions.RetryError:
            raise concurrent.futures.TimeoutError(
                'Operation did not complete within the designated '
                'timeout.')
```

What other ways can retry for a request be expressed to make this more concise?  It  needs to support 1-4 above.  Can more functionality be moved into the Retry? How?

The result should ideally be a pattern which can be used to implement retries for a wide range of gRPC requests.  Note that cloud bigquery client methods all have an optional retry argument of type `google.api_core.retry.Retry`.

**Comment by sduskis** [comment]
@lukesneeringer, how is the retry framework supposed to be used?  We're trying to get basic retries working for mutate_row, and the approach in this issue is the result.  I think that we're missing something about how the retry framework is supposed to be used.

Since we need retries, does it make sense to bite the bullet and use GAPIC under the covers?

**Comment by zakons** [comment]
As an improvement over using a class to store state and to provide a callable interface, a Python function is also callable and can be used for the Retry:

```
def call_mutate_row(table, request_pb):
    """Call the MutateRow"""
    client = table._instance._client
    client._data_stub.MutateRow(request_pb)
```

Using this in a Retry looks like the following:

```
        retry_commit = wrapped_partial(call_mutate_row,
                                       self._table,
                                       request_pb)
        retry_ = retry.Retry(
            predicate=retry.if_exception_type(exceptions.GrpcRendezvous),
            deadline=30)

        retry_(retry_commit)()
```

**Comment by dhermes** [comment]
@jonparrott Care to weigh in? (Jon is the author of the retry stuff.)

**Comment by jonparrott** [comment]
@zakons you have the right idea. See the similar usage in [BigQuery](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/client.py#L268-L290).

**Comment by sduskis** [comment]
zakons@: Can we close this?
