### ISSUE TITLE
PubSub: pull doesn't return messages on non-empty subscription

### ISSUE THREAD

**Issue by tcroiset** [GoogleCloudPlatform/google-cloud-python#4673]
pubsub: 0.27.0

Our pubsub puller process encounters erratic behavior since beginning of December.

It runs a loop which looks like:
```python
while True:
      pulled = subscription.pull(return_immediately=False, max_messages=1)
      process_messages(pulled)
```

It used to work perfectly, but for a few weeks pull() sometimes returns, after ~600s, an empty list while there are still tens of messages on the subscription (as stated by stackdriver monitoring). 
At some points, it can take hours, the messages end up processed.
New incoming messages are sometimes pulled directly while old ones are still not delivered.

We didn't change anything in our code (same Docker image) for two months.

**Comment by chemelnucfin** [comment]
Hello,
  I'm relatively new here and not too familiar with the pubsub library.  However, I know that there have been lots of development in pubsub lately.  Could you try using the latest version 0.30.2.dev1 and see if 
your issue improves?

Otherwise @dhermes may be able to give you a better answer.  Thank you for your patience.

**Comment by chemelnucfin** [comment]
It also seems like pull is not being recommended for use any more.

For more information, please see this thread #4338

**Comment by chemelnucfin** [comment]
I will close this issue now, since the API used is outdated.  Please feel free to open another case should you run into problems.  Thank you.

**Comment by dhermes** [comment]
@tcroiset I can echo a bit about what @chemelnucfin said about us not supporting outdated versions.

However, the backend behavior changing out from under you seems to be a bug. It might be worth [filing an issue][3] with the backend team (from the issue trackers [page][1], also see the [list][2] of existing issues).

/cc @kir-titievsky

[1]: https://cloud.google.com/support/docs/issue-trackers
[2]: https://issuetracker.google.com/savedsearches/559741
[3]: https://issuetracker.google.com/issues/new?component=187173&template=0
