### ISSUE TITLE
Bucket is requester pays bucket but no user project provided.

### ISSUE THREAD

**Issue by Cadmus** [GoogleCloudPlatform/google-cloud-python#4674]
While Try to upload CSV file to the google storage using google.cloud python packages, it's throwing *google.api_core.exceptions.BadRequest: 400 GET https://www.googleapis.com/storage/v1/b/<<bucket_name>>t?projection=noAcl: Bucket is requester pays bucket but no user project provided.
Process finished with exit code 1
*  
from google.cloud import storage

client = storage.Client("project_name")
bucket = client.get_bucket('bucket_name')
blob = bucket.blob('  test_re.csv')
blob.upload_from_string('this is test content!')

please do help me

**Comment by chemelnucfin** [comment]
Hello, I wasn't able to reproduce the issue.  Could you tell me more about the python version and the google storage version?

**Comment by Cadmus** [comment]
python 3 version.

**Comment by Cadmus** [comment]
Hi Please close this issue, I have figure out why this issue happening, for my bucket "request pays" status is on.  but I try to access the bucket with member email id which does not have the association with the billing. The conclusion is if we access the bucket with member email the request pays should be in off status.

**Comment by chemelnucfin** [comment]
Glad to know!  Thank you for stopping by.
