### ISSUE TITLE
Datastore query offsets are not working as it supposed to 

### ISSUE THREAD

**Issue by ibrahim-abuelalaa** [GoogleCloudPlatform/google-cloud-python#4675]
This is a weird behaviour when setting the offset parameter so I have 9825 entities and 
```python
len(list(client.query(kind="Foo").fetch()))
```
Will yield 9825, but
```python
len(list(client.query(kind="Foo").fetch(offset=1)))
```
will yield 9808

**Comment by chemelnucfin** [comment]
Hello, I wasn't able to reproduce the behavior, but I only tested it with a smaller test case.

Do you have more information you can give me?  Does it happen with other queries?

**Comment by ibrahim-abuelalaa** [comment]
hello, thanks for your response. Yes it is like that with others queries the only thing that I could add is that the number of returned entities increase when I use 
```python
query.keys_only()
```
so it is 9815 instead of 9808

**Comment by ibrahim-abuelalaa** [comment]
it works for small test case. But not for large one

**Comment by bmclean** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1922

**Comment by blowmage** [comment]
I have a fix for the Ruby library here: GoogleCloudPlatform/google-cloud-ruby#1930

**Comment by tseaver** [comment]
@mcdonc Reference this bug in your PR.

**Comment by ibrahim-abuelalaa** [comment]
@tseaver how to get this fix?should we wait to the next release?

**Comment by tseaver** [comment]
@ibrahim-abuelalaa I've asked for a `google-cloud-datastore 1.7.0` release in #5680.
