### ISSUE TITLE
PubSub: StatusCode.UNAUTHENTICATED, Deadline Exceeded while on App Engine

### ISSUE THREAD

**Issue by sx5640** [GoogleCloudPlatform/google-cloud-python#4676]
Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/env/local/lib/python2.7/site-packages/google/cloud/pubsub_v1/publisher/batch/thread.py", line 212, in monitor
        return self._commit()
      File "/env/local/lib/python2.7/site-packages/google/cloud/pubsub_v1/publisher/batch/thread.py", line 173, in _commit
        self.messages,
      File "/env/local/lib/python2.7/site-packages/google/cloud/gapic/pubsub/v1/publisher_client.py", line 314, in publish
        return self._publish(request, options)
      File "/env/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 452, in inner
        return api_caller(api_call, this_settings, request)
      File "/env/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 438, in base_caller
        return api_call(*args)
      File "/env/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 376, in inner
        return a_func(*args, **kwargs)
      File "/env/local/lib/python2.7/site-packages/google/gax/retry.py", line 127, in inner
        ' classified as transient', exception)
    RetryError: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.UNAUTHENTICATED, Deadline Exceeded)>)

I'm running a Pubsub publisher in an App Engine Flexible environment, and for some instance, the above error is logged from time to time. While the application is running on 6+ instances, it usually happens only to one of the instance. I can't find a way to reproduce it locally, but it has been triggered several time on App Engine on different instances.

The python version is 2.7, and pubsub client version is 0.29.0. The following is my implementation:

    class PubSubClient(object):
        """
        creates an interface for PubSub client
        """
        pubsub_publisher_client = None
        pubsub_topic = ''
    
        pubsub_subscriber_client = None
        pubsub_subscription = None
        subscription_name = ''
        config = None
    
        def init_publisher(self, config):
            """
            :param config: configuration objected passed down by app
            Used mostly for tests and running locally (using BigTable emulator)
            For cloud runs, the table should already exist w/ proper setup.
    
            Set PubSub topic and initialize client. In Local env, create topic if it does not exit
            """
            self.config = config
    
            if self.config.LOCAL:
                os.environ['PUBSUB_EMULATOR_HOST'] = self.config.pubsub_emulator_host
                os.environ['GOOGLE_CLOUD_PROJECT'] = self.config.project_id
    
            self.pubsub_publisher_client = pubsub.PublisherClient()
            self.pubsub_topic = 'projects/{project_id}/topics/{topic}'.format(
                project_id=self.config.project_id,
                topic=self.config.PUBSUB_TOPIC
            )
    
            if self.config.LOCAL:
                try:
                    self.pubsub_publisher_client.get_topic(self.pubsub_topic)
                except:
                    self.pubsub_publisher_client.create_topic(self.pubsub_topic)
then:

    ps = PubSubClient()
    message = json.dumps(ids).encode()
    ps.pubsub_publisher_client.publish(ps.pubsub_topic, message)

**Comment by dhermes** [comment]
@sx5640 I've seen `UNAUTHENTICATED: Deadline Exceeded` as well, but it occurred as a result of bad auth due to a programming error on my part.

On GAE, you could end up in a "bad auth" state if the `app_identity` library fails to get a valid access token (which is possible).

I don't think there's much we can do to address this other than suggest a retry.

I am going to pre-emptively close this since it seems to be a transient issue. If you think you can narrow it down more, I'm happy to continue discussing.
