### ISSUE TITLE
BigTable: PatialRowsData must have a "length" attribute

### ISSUE THREAD

**Issue by mayurjain0312** [GoogleCloudPlatform/google-cloud-python#4711]
2. Ubuntu 16.04
3. Python version and virtual environment information `python --version` - python 2.7.12

```
    start_key = 'CAM-TFM50~mkz1.2017_12_08_0800.805_demo_day.trifocal.1hr'
    end_key = 'CAM-TFM50~mkz1.2017_12_08_0800.805_demo_day.trifocal.1ht'

    partial_rows = table.read_rows(start_key=start_key, end_key=end_key)
```

No way to get the number of items inside partial_rows.

**Comment by dhermes** [comment]
@mayurjain0312 I'm having a hard time understanding what issue you're having. Can you give an example of something you'd like to do with `partial_rows` and how it fails?

**Comment by mayurjain0312** [comment]
It's not failing. But, I was expecting to get the total number of result rows by calling partial_rows.length().

**Comment by mayurjain0312** [comment]
I want to cache some query results, in order to do that if I knew beforehand the size of results I got from table.read_rows(start_key=start_key, end_key=end_key), it would help in determing if it is super large to hold in memory or now.

Something similar to what mongodb provides. https://docs.mongodb.com/manual/reference/method/cursor.count/

**Comment by zakons** [comment]
In Python you may get the length of a dictionary as follows:

```rows_read = len(partial_rows.rows)```

See also: [dictionary len method](https://www.tutorialspoint.com/python3/dictionary_len.htm)

**Comment by dhermes** [comment]
Using this value may be somewhat problematic because `len(partial_rows.rows)` will change as `PartialRowsData.consume_next()` / `.consume_all()` is called. Since these methods consume chunks from a stream of unknown length, the length also can't be determined beforehand. I would just say "beware" when using the length of the dictionary.

I am going to close this since `len(PartialRowsData.rows)` will do the job for you. I'm happy to re-open and discuss if you'd like.

**Comment by sduskis** [comment]
@mayurjain0312, if you want just a count of rows that are returned, you need to do the same query with a `RowFilterChain()` containing a `CellsRowLimitFilter(1)` and a `StripValueTransformerFilter()`.  That combination will return rows that have 1 cell with an empty value.  You'll be able to do `PartialRowsData.consume_all()` and then `rows_read = len(partial_rows.rows)` to get a row count.

Cloud Bigtable does not provide a way to get a total record count within a single request.
