### ISSUE TITLE
BigQuery: Challenged enumerating tables

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/google-cloud-python#4712]
I'm writing a script with the Python Library and would like to programmatically enumerate tables in a dataset. I'm reviewing the documentation but unable to get these to work:

https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/usage.html#tables

```
python --version
Python 2.7.13

pip --version
pip 9.0.1

virtualenv --version
15.1.0
```

`requirements.txt`:
```
google-cloud-bigquery==0.28.0
six==1.11.0
```
I'm running in virtualenv.

I'm able to connect a client to a project, enumerate datasets, set dataset expiration, create/delete tables and set table expiry. I'm unable to enumerate the tables in a dataset. In the project I'm using below, there's only one dataset.

```python
PROJECT=[[MY-PROJECT-ID]]
DATASET=[[MY-DATASET-ID]]

client = bigquery.Client(project=PROJECT)

for dataset in client.list_datasets():
        print("Dataset: {}".format(dataset.dataset_id))
        print("\tDescription: {}".format(dataset.description))
        print(type(dataset))

dataset_ref = client.dataset(DATASET)
    print(type(dataset_ref))

```
This outputs:
```
<class 'google.cloud.bigquery.dataset.Dataset'>
<class 'google.cloud.bigquery.dataset.DatasetReference'>
```
I'm doing this because the [code](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/e9a53475957b06dc88d3a7f146d17536b075d773/bigquery/google/cloud/bigquery/client.py#L396) suggests that I should be able to provide either a Dataset or a DatasetReference to client to `list_tables` but neither of these works.

Augmenting the code (retaining `dataset` and `dataset_ref`):

```
client.list_tables(dataset)
AttributeError: 'Client' object has no attribute 'list_tables'
```
```
client.list_tables(dataset_ref)        
AttributeError: 'Client' object has no attribute 'list_tables'
```

I'm auth'ing with ADCs and I'm able to access tables using `bq` I am able to enumerate tables
```bash
bq ls --project_id=dazwilkin-180105-bq-expiration test_03

  tableId   Type    Labels   Time Partitioning  
 --------- ------- -------- ------------------- 
  a         TABLE                               
  b         TABLE                               
  c         TABLE                               
```

**Comment by tseaver** [comment]
@DazWilkin Thanks for pointing out this error in the docs!  `google.cloud.bigquery 0.28.0` moved the `dataset.list_tables()` method to `client.list_dataset_tables(dataset)`, but the usage docs show it as `client.list_tables(dataset)`.

**Comment by tseaver** [comment]
@DazWilkin But in `0.29.0` (released last week), `Client.list_dataset_tables(dataset)` has been deprecated in favor of `Client.list_tables(dataset)`.
