### ISSUE TITLE
Spanner: How to run the Google Cloud Python Unit tests?

### ISSUE THREAD

**Issue by Alan502** [GoogleCloudPlatform/google-cloud-python#4720]
How can I run the unit tests for the Cloud Spanner python client libraries?

**Comment by jonparrott** [comment]
@Alan502 you can do so using `nox` as described [here](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/CONTRIBUTING.rst#using-nox).

I'm closing this, but feel free to comment if you have any issues getting that to work.
