### ISSUE TITLE
BigQuery: add schemaUpdateOptions to LoadJobConfig

### ISSUE THREAD

**Issue by yiga2** [GoogleCloudPlatform/google-cloud-python#4728]
Python 2.7 - Client lib 0.29

`Java` [has it ](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1647) and `Go` has [open request](https://github.com/GoogleCloudPlatform/google-cloud-go/issues/823).

As a workaround, one can do as following as the http request is constructed off `_properties`:
`LoadJobConfig()._properties.__setitem__('schemaUpdateOptions', [...])`

Consider adding to `QueryJobConfig` too.

**Comment by chemelnucfin** [comment]
@tseaver wrote this answer

@yiga2 FWIW, that feature is marked "experimental" in the docs.

The workaround you propose won't work: instead, I would use:

    job_config._properties['schemaUpdateOptions'] = ['ALLOW_FIELD_ADDITION']

**Comment by tswast** [comment]
I broke the workaround at https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4728#issuecomment-356857745 in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5036.

The way to workaround after that change is released will be
```python
job_config._properties['load']['schemaUpdateOptions'] = ['ALLOW_FIELD_ADDITION']
```

**Comment by alixhami** [comment]
Added in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5415
