### ISSUE TITLE
BigQuery: Allow creation of a table with partition

### ISSUE THREAD

**Issue by chemelnucfin** [GoogleCloudPlatform/google-cloud-python#4752]
From #4746. I didn't see a clear way to do it, but maybe I just missed it.

> @chemelnucfin how to we can create a partition table using API?
> currently I am using bq mk --time_partitioning_type=DAY <table name>

**Comment by chemelnucfin** [comment]
Tracking this in [Feature Requests](https://github.com/GoogleCloudPlatform/google-cloud-python/projects/5#card-6867100)

**Comment by tswast** [comment]
Duplicate of https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4658
