### ISSUE TITLE
Firebase Firestore: RPC Deadline Exceeded

### ISSUE THREAD

**Issue by kevmo314** [GoogleCloudPlatform/google-cloud-python#4769]
Running on Windows 10, python 3.5.2

I also posted to [StackOverflow](https://stackoverflow.com/questions/48241016/firestore-get-resulting-in-deadline-exceeded) but got no response...

Running the following code from the documentation:

```
docs = db.collection(u'cities').get()

for doc in docs:
    print(doc.id)
```

Results in the following unhelpful error 100% of the time:

```
Traceback (most recent call last):
  File "...", line 74, in <module>
    main()
  File "...", line 53, in main
    for doc in docs:
  File "/usr/lib/python2.7/site-packages/google/cloud/firestore_v1beta1/query.py", line 588, in get
    for index, response_pb in enumerate(response_iterator):
  File "/usr/lib/python2.7/site-packages/grpc/_channel.py", line 347, in next
    return self._next()
  File "/usr/lib/python2.7/site-packages/grpc/_channel.py", line 338, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded)>
```

To reproduce, create a new firestore database and just run that code.

**Comment by kevmo314** [comment]
Also, writes seem to be working correctly, but all reads end up with that error message.

**Comment by kevmo314** [comment]
Turns out this code works correctly on Linux. Was this even tested on Windows? It would at least have been worth a mention on the documentation that it doesn't work as it would've saved me a few hours of debugging...

**Comment by kevmo314** [comment]
Seems like this issue is related: https://github.com/Microsoft/WSL/issues/2657

I managed to successfully run the code on a real linux machine and in the native windows shell, but in WSL it fails miserably.

**Comment by jonparrott** [comment]
Yeah, I would guess that it's an issue with WSL. I'm going to go ahead and close this since it works on Linux and Windows, but feel free to comment or let us know if there's anything else we can do.
