### ISSUE TITLE
Spanner: database.ddl_statements is not working as expected

### ISSUE THREAD

**Issue by pascaldelange** [GoogleCloudPlatform/google-cloud-python#4781]
Hello,
I am using the python API for google spanner. 
In a project I'm working on, I need to obtain the DDL statements of a database.

However, "database.ddl_statements" returns only the DDL statements of the database object, and not of the actual online database.

I was wondering if it would be possible to have a database.ddl_statements() method, that would return a list of DDL statements. I suppose that this should not be too complicated, since the relevant information is already available (from the console or https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances.databases/getDdl).

Thanks

**Comment by chemelnucfin** [comment]
Hello, I believe you need to use the DatabaseAdminClient from here:
[DatabaseAdminClient](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/spanner/google/cloud/spanner_admin_database_v1/gapic/database_admin_client.py) and then use the function get_database_ddl.

Please let me know if this doesn't solve your problem.
Thanks.

**Comment by tseaver** [comment]
The `Database` instance has a local copy of the DDL, but that copy may need to be loaded / refreshed from the server.  Call `db.reload()` to refresh it via an API call.

**Comment by pascaldelange** [comment]
Thanks a lot !
