### ISSUE TITLE
Runtimeconfig: Update time fails to parse

### ISSUE THREAD

**Issue by kw** [GoogleCloudPlatform/google-cloud-python#4807]
OS: Linux (Debian 4.9.65)
Python: 3.5.3 / 2.7.13
Version: google-cloud-runtimeconfig==0.28.0, google-cloud==0.32.0

Steps to reproduce:
1. Using gcloud, set a runtimeconfig variable.
2. In Python, load that variable
3. Try to access its update_time property.

```pycon
>>> from google.cloud import runtimeconfig
>>> client = runtimeconfig.Client()
>>> config = client.config('testconfig')
>>> var = config.get_variable('foo')
>>> var.update_time
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/redacted/lib/python3.5/site-packages/google/cloud/runtimeconfig/variable.py", line 160, in update_time
    value = _rfc3339_to_datetime(value)
  File "/redacted/lib/python3.5/site-packages/google/cloud/_helpers.py", line 274, in _rfc3339_to_datetime
    dt_str, _RFC3339_MICROS).replace(tzinfo=UTC)
  File "/usr/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data '2018-01-22T21:39:44.095040522Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
>>> var._properties
{'text': '43', 'updateTime': '2018-01-22T21:39:44.095040522Z'}
```

Observation: The `%f` format accepts microseconds, not fractions of arbitrary precision. That means six digits at most, but I see nine in the data.

**Comment by tswast** [comment]
Interesting. RuntimeConfig must have started recording nanoseconds somewhat recently.

@jonparrott It seems [Python only supports microsecond precision, not nanoseconds](https://stackoverflow.com/a/10612166/101923).

I'm guessing we should modify the parsing to discard nanoseconds when present.

**Comment by tseaver** [comment]
@tswast FWIW, spanner has a non-public [`TimestampWithNanoseconds`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/4867ac328269c969d520bea64d0d9893bb5257cb/spanner/google/cloud/spanner_v1/_helpers.py#L33) (derived from `datetime.datetime`).  We could promote it if that would be useful.

**Comment by jonparrott** [comment]
promote it into api_core? It might be useful because many APIs do expose nanosecond precision.

**Comment by tswast** [comment]
The from_rfc3339 function there looks very useful. I would bet that more GCP products will be doing nanoseconds.

**Comment by tseaver** [comment]
@jonparrott see #4829.

**Comment by tseaver** [comment]
PR #4979 moved that class into API core, so we should be able to fix this issue using it.
