### ISSUE TITLE
Firestore: DocumentSnapshot copies data twice

### ISSUE THREAD

**Issue by schmidt-sebastian** [GoogleCloudPlatform/google-cloud-python#4808]
The constructor for DocumentSnapshot makes a defensive copy of its data before we do this again in https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/firestore/google/cloud/firestore_v1beta1/document.py#L588

We should remove the latter copy.

**Comment by chemelnucfin** [comment]
@schmidt-sebastian But don't we want the snapshot to have immutable data as well?  Otherwise the data in the snapshot can be changed.

**Comment by schmidt-sebastian** [comment]
Yes, we do. Does the backing data for a DocumentSnapshot change over the lifetime of a client?

**Comment by chemelnucfin** [comment]
The backup data inside the `DocumentSnapshot` should not change because it is copied when created.  Once it's created, it also shouldn't be changed.  The original data could be changed, but it wouldn't affect the snapshot.

I think that's what you are trying to ask?

**Comment by chemelnucfin** [comment]
I guess what I mean is that if you remove the latter copy from your original post, then you can change the data in the snapshot through that method.  (Though it might be user error to do so)

**Comment by schmidt-sebastian** [comment]
If that's the case, then we should keep both defensive copies. Thanks for pointing out all the edge cases here.
