### ISSUE TITLE
Firestore: Non-existing Documents

### ISSUE THREAD

**Issue by schmidt-sebastian** [GoogleCloudPlatform/google-cloud-python#4809]
Calls to `DocumentSnapshot.to_dict()` for non-existing documents should return `None` and not an empty dictionary.

**Comment by chemelnucfin** [comment]
Hi Sebastian,
  The DocumentSnapshot should have already raised an exception on creation if the document is not found.  So I believe that returning None would be extraneous.  Please let me know if you don't think that's the case.

**Comment by schmidt-sebastian** [comment]
We should no longer raise exceptions for missing documents, but instead return None/Null for any getData() call.
