### ISSUE TITLE
google.gax.errors.RetryError: RetryError with pubsub

### ISSUE THREAD

**Issue by vkoppaka** [GoogleCloudPlatform/google-cloud-python#4812]
I am running into the following error when using Google PubSub in a Kubernetes Container recently (it was working fine until a week back).
Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.UNAUTHENTICATED, Deadline Exceeded)

What could I do to debug what is causing this behavior?

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types: Pubsub
2. OS type and version: GKE Ubuntu, 16.04
3. Python version and virtual environment information `python --version`: 2.7.12
4. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
**Google cloud version**: 0.29.0

**Pip freeze:**
```
Flask==0.11.1
gapic-google-cloud-datastore-v1==0.15.3
gapic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3
google-api-core==0.1.4
google-auth==1.2.0
google-cloud==0.29.0
google-cloud-bigquery==0.28.0
google-cloud-bigtable==0.28.1
google-cloud-core==0.28.0
google-cloud-datastore==1.4.0
google-cloud-dns==0.28.0
google-cloud-error-reporting==0.28.0
google-cloud-firestore==0.28.0
google-cloud-language==0.31.0
google-cloud-logging==1.4.0
google-cloud-monitoring==0.28.0
google-cloud-pubsub==0.29.0
google-cloud-resource-manager==0.28.0
google-cloud-runtimeconfig==0.28.0
google-cloud-spanner==0.29.0
google-cloud-speech==0.30.0
google-cloud-storage==1.6.0
google-cloud-trace==0.16.0
google-cloud-translate==1.3.0
google-cloud-videointelligence==0.28.0
google-cloud-vision==0.28.0
google-gax==0.15.16
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3
grpc-google-iam-v1==0.11.4
grpcio==1.8.6
gunicorn==19.7.1
honcho==1.0.1
proto-google-cloud-datastore-v1==0.90.4
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3
protobuf==3.5.1
psq==0.5.0
psutil==5.4.3
requests==2.18.4
retrying==1.3.3
rsa==3.4.2
six==1.11.0
ssdeep==3.2
urllib3==1.22
webencodings==0.5.1
Werkzeug==0.14.1
zope.interface==4.4.3
```

5. Stacktrace if available
```
| worker.1 stopped (rc=1)
| TransportError: HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: /o/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdba405ff90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
| raise exceptions.TransportError(exc)
| File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/requests.py", line 115, in __call__
| method='POST', url=token_uri, headers=headers, body=body)
| File "/usr/local/lib/python2.7/dist-packages/google/oauth2/_client.py", line 104, in _token_endpoint_request
| response_data = _token_endpoint_request(request, token_uri, body)
| File "/usr/local/lib/python2.7/dist-packages/google/oauth2/_client.py", line 143, in jwt_grant
| request, self._token_uri, assertion)
| File "/usr/local/lib/python2.7/dist-packages/google/oauth2/service_account.py", line 322, in refresh
| self.refresh(request)
| File "/usr/local/lib/python2.7/dist-packages/google/auth/credentials.py", line 121, in before_request
| headers)
| File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/grpc.py", line 61, in _get_authorization_headers
| callback(self._get_authorization_headers(context), None)
| File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/grpc.py", line 73, in __call__
| context, _AuthMetadataPluginCallback(callback_state, callback))
| File "/usr/local/lib/python2.7/dist-packages/grpc/_plugin_wrapping.py", line 74, in __call__
| Traceback (most recent call last):
| [2018-01-30 16:42:15] AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fdba50aca90>" raised exception!
| google.gax.errors.RetryError: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.UNAUTHENTICATED, Deadline Exceeded)>)
| ' classified as transient', exception)
| File "/usr/local/lib/python2.7/dist-packages/google/gax/retry.py", line 127, in inner
| return a_func(*args, **kwargs)
| File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 376, in inner
| return api_call(*args)
| File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 438, in base_caller
| return api_caller(api_call, this_settings, request)
| File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 452, in inner
| return self._pull(request, options)
| File "/usr/local/lib/python2.7/dist-packages/google/cloud/gapic/pubsub/v1/subscriber_client.py", line 706, in pull
| response = client.pull(subscription, _MAX_MESSAGES_TO_PROCESS)
| File "/app/main.py", line 72, in process_queue
process_queue()
```

**Note**: We had to use pull vs the new async callback in pubsub due to the nature of worker we are running, as it requires to be on the main thread.

The error also appears to be transient in nature where one every few pulls seem to go fine and then they break again.

**Comment by jonparrott** [comment]
Unfortunately we aren't supporting the previous versions of this library (we are pushing towards v1.0.0 and having consistent support). If you can reproduce this with the latest version (0.30.1) then I'll be glad to re-open.

**Comment by vkoppaka** [comment]
I upgraded to 0.30.1 and still see this issue. Herei s what I see in our logs, when we try to do a Pull -

"
21:59:53 worker.1 \| TransportError: HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: /o/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5dcf9ecb10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
--
"

**Comment by jonparrott** [comment]
Looks like your machine can't resolve `google.com`/`accounts.google.com`. Can you verify network connectivity?

**Comment by vkoppaka** [comment]
This error occurs in a Pod on Kubernetes engine, not on my local machine.

**Comment by vkoppaka** [comment]
@jonparrott any suggestions on things I can try to debug why this is happening?

**Comment by jonparrott** [comment]
Not off the top of my head - can you otherwise connect to googleapis.com from your Pod?

**Comment by vkoppaka** [comment]
Yes. Like I mentioned, the error is transient. The pod works fine today when I checked, but I see the error every so often.

**Comment by jonparrott** [comment]
Sounds like it just might be intermittent network issues. Maybe the Pod's host is overwhelming and dropping packets?

I am not a k8s expert, but I do not think this issue is with the client libraries.
