### ISSUE TITLE
google.cloud.storage: weird crash with nltk under ProcessPool

### ISSUE THREAD

**Issue by yipjustin** [GoogleCloudPlatform/google-cloud-python#4814]
API: google.cloud.storage
osx 10.11.6
python 3.5

Hello,

I experienced some weird error when using `nltk` and `google.cloud.storage` under `ProcessPool`. 

After `import nltk`, I tried to extract data from google storage from the main process, it works fine. See `first_main_then_pool()` below.

However, when I extract data from a process pool executor directly after `import nltk`, See `only_pool()`, I get the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/yipjustin/tmp/a.py", line 29, in <module>
    only_pool()
  File "/Users/yipjustin/tmp/a.py", line 25, in only_pool
    print(executor.submit(get, 'b.txt').result())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

I am curious to see if anyone has experienced similar issue. Thanks!

Code:

```
import concurrent.futures
from google.cloud import storage

def get(path):
	bucket_name = 'yipjustin-a'
	client = storage.Client()
	bucket = client.lookup_bucket(bucket_name)
	blob = bucket.get_blob(path)
	return blob.download_as_string()

def first_main_then_pool():
	# GOOD
	import nltk
	print(get('a.txt'))
	with concurrent.futures.ProcessPoolExecutor() as executor:
		print(executor.submit(get, 'b.txt').result())

def only_pool():
	# BAD
	import nltk
	with concurrent.futures.ProcessPoolExecutor() as executor:
		print(executor.submit(get, 'b.txt').result())
```

**Comment by chemelnucfin** [comment]
Hello, I was unable to reproduce your problem, however I'm not on a Mac and here is another known issue that seem to only affect Macs and not Linux [grpc](https://github.com/grpc/grpc/issues/12455#issuecomment-348578950).  But I'm not sure it's relevant to your case.

Also, approximately how big are your a.txt and b.txt files and are there special characters in them?
Thanks.

**Comment by yipjustin** [comment]
Both files have only few bytes:

https://storage.googleapis.com/yipjustin-a/a.txt
https://storage.googleapis.com/yipjustin-a/b.txt

**Comment by chemelnucfin** [comment]
@yipjustin 
  Would this work to solve your case?  Using a `if __name__=='__main__':` https://stackoverflow.com/questions/15900366/all-example-concurrent-futures-code-is-failing-with-brokenprocesspool

Thanks.

**Comment by yipjustin** [comment]
Tried. Saw that thread too. That's an unrelated bug.

**Comment by tseaver** [comment]
I just tried to reproduce via [this gist](https://gist.github.com/tseaver/19a643712e3c6a0ecd4b6aeb952adfc6), where I added a setup operation to make it obvious how to create and populate the bucket.

I tried it in a fresh virtual environment.  Whether or not I comment out the `import nltk` lines, the operations are fine.

Please reopen if you can suggest more information to help us reproduce.
