### ISSUE TITLE
Promote 'TimestampWithNanos' from 'spanner' to 'api_core'

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#4829]
It would be useful for other services as they begin to render nanosecond-resolution timestamps.

See: #4807

**Comment by tseaver** [comment]
Nothing but the `spanner` version preserves nanoseconds in the derived datetime instance.

**Comment by jonparrott** [comment]
Who wants to take this on? I'm happy to do it but if someone else is eager...
