### ISSUE TITLE
BigQuery: Add support for BigQuery customer-managed encryption keys

### ISSUE THREAD

**Issue by choenden** [GoogleCloudPlatform/google-cloud-python#4842]
BigQuery customer-managed encryption keys allow users to specify a Cloud KMS key to protect their BigQuery table.

API:
Jobs: https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs
In a job, there is a destinationEncryptionConfiguration field, which indicates which Cloud KMS key should be used for the destination.

Tables: https://cloud.google.com/bigquery/docs/reference/rest/v2/tables
In a table, there is a encryptionConfiguration field, which indicates which Cloud KMS key protects (or should protect in case of CreateTable) a BigQuery table.

These are the main APIs that are required for day-to-day interaction.
With lower priority, support for getServiceAccount would also be nice: https://cloud.google.com/bigquery/docs/reference/rest/v2/projects/getServiceAccount
Note that unlike the other methods mentioned above, this would generally only be called once and the resulting value (the email address) does not change - so it can easily also be called from UI/API/CLI without much hindrance (hence lower priority).

**Comment by choenden** [comment]
FYI that BQ team is trying to get a pull request ready

**Comment by tswast** [comment]
I see there is only one property, `"kmsKeyName": string`, in the encryption configuration type. We could make a new class for the encryption configuration, but do we need too?

Regarding `destinationEncryptionConfiguration` in the Jobs, it appears that these properties are in the job-type specific configurations, such as `configuration.copy` and `configuration.query`. That fits well with the current structure of the client library. See: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4786 for an example of how to handle properties with custom types in the XJobConfig classes.

**Comment by tswast** [comment]
@choenden are you a Googler? If so, you should register at go/github and familiarize yourself with go/github-docs

**Comment by tswast** [comment]
The jobs and tables APIs are complete. We are still missing getServiceAccount.

**Comment by tswast** [comment]
Just got word that some customers desire `getServiceAccount` support in this library. I propose we do something similar to the Ruby implementation: https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/2040

That is, make a `Client.get_service_account_email()` method which makes the GET request and returns the service account email as a string.

**Comment by tswast** [comment]
Yes, fixed by #5203.
