### ISSUE TITLE
Logging: Release new version of google-cloud-logging

### ISSUE THREAD

**Issue by snehashankarnarayan** [GoogleCloudPlatform/google-cloud-python#4861]
Hello,

The latest version of Google cloud logging is https://pypi.org/project/google-cloud-logging/#history, in October 2017. We wanted a PyPi release with the latest changes with respect to creating sinks with `unique_writer_identity` set. 

We really would prefer not using the latest google-cloud module as we want to use different versions of various google cloud services.

Thanks,
Sneha

**Comment by chemelnucfin** [comment]
Closed via #4901
