### ISSUE TITLE
Python issue

### ISSUE THREAD

**Issue by kprovance** [GoogleCloudPlatform/google-cloud-python#4866]
Good evening,

A few days ago, our VM instance began maxing out at 100%, even though our site has decent speed.  I was able to find this in the serial port console log (just the last bit where the trouble seems to be):

```
Ubuntu 14.04.5 LTS redux ttyS0

redux login: Can not apply stage final, no datasource found! Likely bad things to come!

------------------------------------------------------------

Traceback (most recent call last):

 File "/usr/bin/cloud-init", line 318, in main_modules

   init.fetch()

 File "/usr/lib/python2.7/dist-packages/cloudinit/stages.py", line 308, in fetch

   return self._get_data_source()

 File "/usr/lib/python2.7/dist-packages/cloudinit/stages.py", line 236, in _get_data_source

   pkg_list)

 File "/usr/lib/python2.7/dist-packages/cloudinit/sources/__init__.py", line 263, in find_source

   raise DataSourceNotFoundException(msg)

DataSourceNotFoundException: Did not find any data source, searched classes: ()

------------------------------------------------------------
```

We are running an Ubuntu 14.04.5 box.  I'm not altogether sure what this means or why it began happening.  Is there a solution, or any suggests one could offer?  We'd like to get our CPU usage back to something under 100%  :)

Also, if this is the incorrect place to ask for help on this issue, could someone let me know where I might go for assistance on fixing this?

Thank you.

**Comment by chemelnucfin** [comment]
I believe that you might be looking for [cloud-init](https://github.com/cloud-init/cloud-init).

Please do let us know if we can be of more help.

**Comment by kprovance** [comment]
Turns out the google computer engine software needed updating, which fixed it.  Thanks for replying.  :)

**Comment by GenslerEric** [comment]
@kprovance 
> Turns out the google computer engine software needed updating, which fixed it.

Can you explain what you needed to / how you accomplished this? I'm seeing this same error in my Python stack trace of an Ubuntu 14.04 box:

```
DataSourceNotFoundException: Did not find any data source, searched classes: ()
------------------------------------------------------------
* Starting Handle applying cloud-config                                 [fail]
```

**Comment by kprovance** [comment]
Dude, this was three years ago.  Stop assigning it to me!

**Comment by JustinBeckwith** [comment]
Hah, sorry it's an automated script 🤖
