### ISSUE TITLE
firestore, bigquery, Others? ('_RSAPrivateKey' object has no attribute 'sign')

### ISSUE THREAD

**Issue by fgervais** [GoogleCloudPlatform/google-cloud-python#4867]
It looks like the new version of google-auth released 2 days ago is causing an issue with at least firestore and bigquery which is the ones I've tested.

Here's the stack trace for firestore:

> File "/home/fgervais/tensorflow_21_nov_2017/lib/python3.5/site-packages/google/cloud/firestore_v1beta1/query.py", line 588, in get
    for index, response_pb in enumerate(response_iterator):
  File "/home/fgervais/tensorflow_21_nov_2017/lib/python3.5/site-packages/grpc/_channel.py", line 347, in __next__
    return self._next()
  File "/home/fgervais/tensorflow_21_nov_2017/lib/python3.5/site-packages/grpc/_channel.py", line 341, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Getting metadata from plugin failed with error: '_RSAPrivateKey' object has no attribute 'sign')>

`pip3 install google-auth==1.3.0` solves the problem.

It might be specific to the way I instantiate the client I'm not sure.
I'm using:

```python
db = firestore.Client.from_service_account_json(
    "firebase-adminsdk.json")

**Comment by jonparrott** [comment]
It's because the new release of google-auth tries to use the cryptography
library if it's available. I'll investigate this soon. Can you tell me
which version of cryptography you have?

**Comment by fgervais** [comment]
cryptography==1.2.3

**Comment by jonparrott** [comment]
That's pretty old. Can you try a version > 2.0? It seems we need to add an
additional check and not use old versions of cryptography.

**Comment by fgervais** [comment]
Good call. I did a pip upgrade which installed cryptography version 2.1.4.

With that version google-auth 1.4.0 works fine.

**Comment by jonparrott** [comment]
Closed by https://github.com/GoogleCloudPlatform/google-auth-library-python/pull/243
