### ISSUE TITLE
Multiple clients receiving all the messages for the same subscription_path

### ISSUE THREAD

**Issue by kudhru** [GoogleCloudPlatform/google-cloud-python#4868]
Hi

I am trying to run GCP PubSub emulator on my local machine. If I want multiple clients to receive all the messages for the same topic_path (subscription_path), is there any way to do so? Currently, if multiple clients subscribe to same topic_path, the messages get delivered only to one of the clients. Sending messsages only to one of the clients seems to be in line with the [documentation](http://google-cloud-python.readthedocs.io/en/latest/pubsub/subscriber/index.html#creating-a-subscription). But I am surprised why is this the case? Is it not possible in real life that multiple clients may want to subscribe to the same topic/subscription?

**Comment by Spriithy** [comment]
Did you create a subscription for each of the clients ?

**Comment by kudhru** [comment]
Since all of my clients try to subscribe for the same topic (subscription path ), the subscription gets created only when the first time a client calls the below line of code
`subscriber.create_subscription(subscription_path, topic_path)`

For rest of the clients, the above line fails which I catch in try-except block.

After this, the client calls the below line of code:
`subscription = subscriber.subscribe(subscription_path, callback)`

This is successful for all the clients but only one of them receive the published message.

Complete code:
`def subscribe(topic, project_id):
    formatted_topic = 'projects/{0}/topics/{1}'.format(project_id, topic)
    formatted_subscription = 'projects/{0}/subscriptions/{1}'.format(project_id, topic)
    try:
        subscriber.create_subscription(formatted_subscription, formatted_topic)
    except Exception as e:
        print e

    try:
        def callback(message):
            print message.data
            message.ack()
        subscription = subscriber.subscribe(
            formatted_subscription,
        )
        subscription.open(callback)
    except Exception as e:
        print e
    return`

**Comment by jonparrott** [comment]
@kudhru that's how it works: if your processes all share the same subscription, then the messages will be distributed among them. If each of your processes has their own subscription, they will receive a copy of each message. See https://cloud.google.com/pubsub/architecture#the_basics_of_a_publishsubscribe_service

(Closing for now)

**Comment by kudhru** [comment]
Oh!
Now, I understand. Basically, Google PubSub has an extra layer of 'subscription' between 'topic' and 'subscribers'. So, multiple subscribers can still get the messages of the same topic but via different subscriptions. Makes sense!

thanks a lot @jonparrott @Spriithy

**Comment by jonparrott** [comment]
Happy to help (this was a bit surprising to me at first, too). :)
