### ISSUE TITLE
[Core] Authentication broken when using GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by jaitaiwan** [GoogleCloudPlatform/google-cloud-python#4869]
When attempting to authenticate using a application credential file from a service account `auth.json` the authentication process will fail to detect the project specified in the credentials file under the key `project_id` when specifying the credentials file location using an environment variable.

**System:** Ubuntu 17.10 Python 3.6 google-cloud-storage==1.7.0

### Example:
```
$ export GOOGLE_APPLICATION_CREDENTIALS='auth.json'
$ python test.py
Traceback (most recent call last):
  File "test.py", line 19, in __main__
    gcs = storage.Client()
  File "/usr/local/lib/python3.6/site-packages/google/cloud/storage/client.py", line 71, in __init__
    _http=_http)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/client.py", line 211, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/client.py", line 167, in __init__
    raise EnvironmentError('Project was not passed and could not be '
OSError: Project was not passed and could not be determined from the environment.
```
### Working:
```
storage.Client.from_service_account_json('auth.json')
```

### Fails
```
client = storage.Client()
```

**Comment by jonparrott** [comment]
Hi @jaitaiwan, this is pretty weird. :) Can you tell me the output of this *with* and *without* the environment variable set:

```python
import google.auth
credentials, project = google.auth.default()
print(type(credentials))
print(project is not None)
```

**Comment by chemelnucfin** [comment]
@jonparrott I wasn't able to reproduce it last night, but wasn't sure maybe if I was missing something.

**Comment by jaitaiwan** [comment]
Thanks folks, I can't seem to replicate it locally either, only inside a gitlab runner. So I'll open a ticket there.

**Comment by jonparrott** [comment]
Cool, feel free to cc me in over there, I might be able to help debug.

**Comment by Neptune998** [comment]
\image_annotator_client.py", line 151, in __init__
    address=self.SERVICE_ADDRESS, channel=channel, credentials=credentials
