### ISSUE TITLE
google.gax.errors.GaxError

### ISSUE THREAD

**Issue by abhibeta** [GoogleCloudPlatform/google-cloud-python#4885]
# Thank you for reporting an issue to google-cloud-python!

If you are reporting an issue or requesting a feature, please search the
existing open and closed issues to see if there is already work being done.

- https://github.com/GoogleCloudPlatform/google-cloud-python/issues
- http://stackoverflow.com/questions/tagged/google-cloud-python

If you can provide us with as much of the following information as possible it
will help us identify the cause of your issue more quickly.

1.Speech-Recognization
2. Ubunto 16.04
3. Python 2.7
4.  Python 2.7
5. Waiting for operation to complete...
Traceback (most recent call last):
  File "transcribe_async.py", line 100, in <module>
    transcribe_gcs(args.path)
  File "transcribe_async.py", line 81, in transcribe_gcs
    response = operation.result(timeout=None) #90
  File "/usr/local/lib/python2.7/dist-packages/google/gax/__init__.py", line 596, in result
    raise GaxError(self._operation.error.message)
google.gax.errors.GaxError
6. use https://storage.googleapis.com/staging.deeplearning-193422.appspot.com/test1.mp3 in transcribe_async.py
7. Run from google cloud shell  python transcribe_async.py gs://staging.deeplearning-193422.appspot.com/test1.mp3

Using GitHub flavored markdown can help make your request clearer.
See: https://guides.github.com/features/mastering-markdown/

**Comment by chemelnucfin** [comment]
Hello, you did not mention the version number of speech that you are using.  However, we are trying to get rid of the gax library and you may be able to fix this error using the latest version.

Please try upgrading by using `pip install -- upgrade`.  Please let us know if you encounter any more questions.

**Comment by abhibeta** [comment]
I am using 0.3 version for speech .
I ran upgrade , but still same error

Waiting for operation to complete...Traceback (most recent call last): File
"transcribe_async.py", line 100, in <module> transcribe_gcs(args.path) File
"transcribe_async.py", line 81, in transcribe_gcs response =
operation.result(timeout=90) #90 File
"/usr/local/lib/python2.7/dist-packages/google/gax/__init__.py", line 596,
in result raise GaxError(self._operation.error.message)
google.gax.errors.GaxError

**Comment by abhibeta** [comment]
Even if I use sample file i get same error

python transcribe_async.py resources/audio.rawWaiting for operation to
complete...Traceback (most recent call last): File "transcribe_async.py",
line 102, in <module> transcribe_file(args.path) File
"transcribe_async.py", line 52, in transcribe_file response =
operation.result(timeout=90) File
"/usr/local/lib/python2.7/dist-packages/google/gax/__init__.py", line 596,
in result raise GaxError(self._operation.error.message)
google.gax.errors.GaxError

**Comment by jonparrott** [comment]
@abhibeta we've completely removed gax from the latest version of the speech client, so it's very unusual that you're still getting that error with an update version. Can you give us the output of `pip freeze`?

**Comment by abhibeta** [comment]
apic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3google==2.0.1google-api-core==0.1.4
google-api-python-client==1.6.5google-auth==1.4.1google-cloud==0.32.0
google-cloud-bigquery==0.28.0google-cloud-bigquery-datatransfer==0.1.0
google-cloud-bigtable==0.28.1google-cloud-container==0.1.0
google-cloud-core==0.28.0google-cloud-datastore==1.4.0
google-cloud-dns==0.28.0google-cloud-error-reporting==0.28.0
google-cloud-firestore==0.28.0google-cloud-language==1.0.0
google-cloud-logging==1.4.0google-cloud-monitoring==0.28.0
google-cloud-pubsub==0.30.1google-cloud-resource-manager==0.28.0
google-cloud-runtimeconfig==0.28.0google-cloud-spanner==0.29.0
google-cloud-speech==0.30.0google-cloud-storage==1.6.0
google-cloud-trace==0.17.0google-cloud-translate==1.3.0
google-cloud-videointelligence==1.0.0google-cloud-vision==0.29.0
google-gax==0.15.16google-resumable-media==0.3.1
googleapis-common-protos==1.5.3grpc-google-iam-v1==0.11.4grpcio==1.9.1
httplib2==0.10.3idna==2.6oauth2client==3.0.0ply==3.8
proto-google-cloud-datastore-v1==0.90.4
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3protobuf==3.5.1psutil==5.4.3
pyasn1==0.4.2pyasn1-modules==0.2.1pytz==2018.3requests==2.18.4rsa==3.4.2
six==1.11.0uritemplate==3.0.0urllib3==1.22

On Fri, Feb 16, 2018 at 8:49 PM, Jon Wayne Parrott <notifications@github.com

**Comment by jonparrott** [comment]
I see. Can you run `pip install --upgrade google-cloud-speech` and try again?

@lukesneeringer more fuel for that "remove the umbrella package" fire.

**Comment by abhibeta** [comment]
Got upgraded to 0.32 version from 0.30.

but getting different error from same line

python transcribe_async.py gs://
staging.deeplearning-193422.appspot.com/test1.mp3Waiting for operation to
complete...Traceback (most recent call last): File "transcribe_async.py",
line 100, in <module> transcribe_gcs(args.path) File "transcribe_async.py",
line 81, in transcribe_gcs response = operation.result(timeout=90) #90 File
"/home/geek_abhishek/python-docs-samples/speech/cloud-client/env/lib/python3.5/site-packages/google/api_core/future/polling.py",
line 111, in result raise
self._exceptiongoogle.api_core.exceptions.GoogleAPICallError:
None Unexpected state: Long-running operation had neither response nor
error set.(env)
geek_abhishek@deeplearning-193422:~/python-docs-samples/speech/cloud-client$
python transcribe_async.py resources/audio.rawWaiting for operation to
complete...Traceback (most recent call last): File "transcribe_async.py",
line 102, in <module> transcribe_file(args.path) File
"transcribe_async.py", line 52, in transcribe_file response =
operation.result(timeout=90) File
"/home/geek_abhishek/python-docs-samples/speech/cloud-client/env/lib/python3.5/site-packages/google/api_core/future/polling.py",
line 111, in result raise
self._exceptiongoogle.api_core.exceptions.GoogleAPICallError:
None Unexpected state: Long-running operation had neither response nor
error set.



On Fri, Feb 16, 2018 at 8:54 PM, Jon Wayne Parrott <notifications@github.com

**Comment by abhibeta** [comment]
Is sample code working for you
running  python transcribe_async.py resources/audio.raw from gcloud.

**Comment by jonparrott** [comment]
@chemelnucfin can you investigate?

**Comment by chemelnucfin** [comment]
@abhibeta I am running on python2.7 and I'm able to run on the local file 
`python transcribe_async.py resources/audio.raw`

I will try gs in a moment.  However, it seems inconsistent with what you are seeing.  I'm wondering if it's some package collision.

**Comment by chemelnucfin** [comment]
@abhibeta I do see the error in gs.  Looking into it.

**Comment by chemelnucfin** [comment]
@abhibeta I think it might have to do with the encoding of the file.  Using audio.raw on gs, the encoding was set to enums.RecognitionConfig.AudioEncoding.FLAC, but the local file used LINEAR16.  When I changed the code to the following, it worked on gs.  
 
```
 config = types.RecognitionConfig(
        encoding=enums.RecognitionConfig.AudioEncoding.LINEAR16,
        sample_rate_hertz=16000,
        language_code='en-US')
```

**Comment by abhibeta** [comment]
Thanks  @chemelnucfin
Seems some where some code got edited , I copied and replaced
transcribe_async.py


I am getting output for both local and gs in python 2.7 and 3.5 for sample
files
I* will try my files now and update you *

python 2.7

python transcribe_async.py gs://cloud-samples-tests/speech/vr.flacWaiting
for operation to complete...Transcript: it's okay so what am I doing here
why am I here at GDC talking about VR video it's because I believe my
favorite games I love games I believe in games my favorite games are the
ones that are all about the stories I love narrative game design I love
narrative based games and I think that when it comes to telling stories in
VR bring together capturing the world with narrative based games and
narrative base game design is going to unlock some of the killer apps and
killer stories of the mediumConfidence: 0.94491559267Transcript: so I'm
really here looking for people who are interested in telling us or two
stories that are planning projects around telling those types of stories
and I would love to talk to you so if this sounds like your project if
you're looking at blending VR video and interactivity to tell a story I
want to talk to you I want to help you so if this sounds like you please
get in touch please come find me I'll be here all week I have pink hair I
work for Google and I would love to talk with you further about VR video
interactivity in storytellingConfidence: 0.943127572536

python 3.5

python transcribe_async.py gs://cloud-samples-tests/speech/vr.flacWaiting
for operation to complete...Transcript: it's okay so what am I doing here
why am I here at GDC talking about VR video it's because I believe my
favorite games I love games I believe in games my favorite games are the
ones that are all about the stories I love narrative game design I love
narrative based games and I think that when it comes to telling stories in
VR bring together capturing the world with narrative based games and
narrative based game design is going to unlock some of the killer apps and
killer stories of the mediumConfidence: 0.9730620384216309Transcript: so
I'm really here looking for people who are interested in telling us or two
stories that are planning projects around telling those types of stories
and I would love to talk to you so if this sounds like your project if
you're looking at blending VR video and interactivity to tell a story I
want to talk to you I want to help you so if this sounds like you please
get in touch please come find me I'll be here all week I have been care I
work for Google and I would love to talk with you further about VR video
interactivity and storytellingConfidence: 0.965194821357727

**Comment by abhibeta** [comment]
Thanks.

Recommend 2 edits

1. in requirement.txt change google-cloud-speech==0.30.0 to 0.32.0
2. Is there any way to handle encoding error better  , error thrown was
quite generic.

Now I am going go try with my own file

**Comment by chemelnucfin** [comment]
@abhibeta Are you able to get the transcription working for your file?

**Comment by abhibeta** [comment]
Yes I am , thanks a lot.
Wondering if we have a way out to transcript a 2 channel file like a audio
from call center .
Splitting in 2 channels breaks the conversation .

**Comment by chemelnucfin** [comment]
@abhibeta I have opened some issues which relates to the problems that you are having now.  I will now close this original issue which is now resolved.  Please do let me know if you have some other concerns.
Thanks.
