### ISSUE TITLE
Using a static json file for GOOGLE_APPLICATION_CREDENTIALS is insecure

### ISSUE THREAD

**Issue by bugeats** [GoogleCloudPlatform/google-cloud-python#4886]
Forcing the client to reference a physical, static JSON file for secrets is insecure. It forces those secrets to be included in every bundle and on every app server. It temps developers to keep the secrets in version control. All around bad practice. 

Instead, this project should be able to use an individual environment variable for each key found in the JSON file. Those environment variables can be set securely, just for the process that is using them.

**Comment by jonparrott** [comment]
This just isn't correct. Environment variables are less secure than files. See [here](https://diogomonica.com/2017/03/27/why-you-shouldnt-use-env-variables-for-secret-data/). 

> It forces those secrets to be included in every bundle and on every app server

It does not. It instead allows you to specify secrets using whichever secrets management system you have. Almost all of them support or even prefer exposing secrets in the filesystem, see Kubernetes secrets for example.

**Comment by ttfreeman** [comment]
Why is this issue close? Does it mean there is no problem leaving the json file for  GOOGLE_APPLICATION_CREDENTIALS in the project folders? No security risk to our google cloud project? No other workaround?
