### ISSUE TITLE
streaming_recognize result blocking

### ISSUE THREAD

**Issue by Tadly** [GoogleCloudPlatform/google-cloud-python#4891]
As of @tseaver request, here's a new issue.

I've already opened a [issue](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1364) in the python-docs-samples repository only later realizing this here would be a better place later.

To summarize the other issue:
`grpc._channel._Rendezvous` (the result of `SpeechClient.streaming_recognize`) is blocking if nothing can be transcribed (e.g. mic is muted, nothing is being spoken, etc.).

In an `asyncio` environment this is really bad.

What I was hoping for was something like:
```python
...
responses = client.streaming_recognize(config, requests)
while True:
    if not responses.has_result():
        continue

    response = next(responses)
```
This is just a quick draft but would allow proper integration into an `asyncio` environment as I control the loop.

I did try `grpc._channel._Rendezvous.result` with a `timeout` but I've only been getting `FutureTimeoutError` without any result (obviously I was speaking at this time).

I hope I got my issue across ':D

**Comment by jonparrott** [comment]
The problem with your proposal is that it causes us to unnecessarily eat up CPU time.

At this time, "playing nice with asyncio" isn't an explicit goal of this library- mostly because we have a large number of users to support on Python 2.7. We're happy to revisit that int he future.

**Comment by Tadly** [comment]
I see.
I also assume there aren't any easy (not supported) ways to work around this for the time being?

**Comment by jonparrott** [comment]
I'm not well-versed enough to really say. I would suspect that using asyncio's functionality to trigger callbacks in other threads and running this in another thread would be the right way to work around.

I'm going to close this for now, but I'm happy to keep discussing.

**Comment by Tadly** [comment]
I have actually already started to put the `streaming_recognize` part into a separate thread while having the async eventloop kind of monitor it.
By that I mean:
 * No `is_final` within _n_ seconds -> cancel
 * No result at all for the first _n_ seconds -> cancel
 * Actually a `is_final` result -> :tada: 

However...
Occasionally the second thread segfaults the whole program after I `_Rendezvous.cancel` and the other times it doesn't throwing the expected exception.
So that's quite puzzling.

A proper multi-threaded example with which allows cancellation etc. isn't available I assume? (I'm sure I'd have come across one by now)

**Comment by jonparrott** [comment]
Summoning the grpc folks @nathanielmanistaatgoogle @kpayson64 @mehrdada

**Comment by Tadly** [comment]
Alright...
2 days later and I kind of found the reason for the segfault.

It's because my microphone stream implementation (using python-sounddevice instead of pyaudio) didn't use an internal buffer.
`streaming_recognize` than manages to fuck up somewhere (which I didn't investigate further).

For now the threaded implementation (ugly as it is) does seem to work.

**Comment by HerrHerklotz** [comment]
Because the Python 2.7 support will be removed on January 1, 2020. I just want to ask if this topic will be reactivated?

For my implementation I need a stable solution which allows an user to answer with his voice or by pressing a button.
