### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by JonathanSFalk** [GoogleCloudPlatform/google-cloud-python#4894]
Installing SDK I get the following response:
I checked, and C:\Users\jonat\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython
does indeed lead to a python 2.7 that runs fine.

Output folder: C:\Users\jonat\AppData\Local\Google\Cloud SDK
Downloading Google Cloud SDK core.
Extracting Google Cloud SDK core.
Create Google Cloud SDK bat file: C:\Users\jonat\AppData\Local\Google\Cloud SDK\cloud_env.bat
Installing components.
Welcome to the Google Cloud SDK!
ERROR: gcloud failed to load: 'module' object has no attribute 'openssl_md_meth_names'
    gcloud_main = _import_gcloud_main()
    import googlecloudsdk.gcloud_main
    from googlecloudsdk.calliope import base
    from googlecloudsdk.calliope import arg_parsers
    from googlecloudsdk.core import log
    from googlecloudsdk.core import properties
    from googlecloudsdk.core import config
    from googlecloudsdk.core.util import files as file_utils
    import hashlib
    _hashlib.openssl_md_meth_names)
This usually indicates corruption in your gcloud installation or problems with your Python interpreter.
Please verify that the following is the path to a working Python 2.7 executable:
    C:\Users\jonat\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\python.exe
If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 executable.
If you are still experiencing problems, please reinstall the Cloud SDK using the instructions here:
    https://cloud.google.com/sdk/
Traceback (most recent call last):
  File "C:\Users\jonat\AppData\Local\Google\Cloud SDK\google-cloud-sdk\\bin\bootstrapping\install.py", line 8, in <module>
    import bootstrapping
  File "C:\Users\jonat\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\bootstrapping\bootstrapping.py", line 15, in <module>
    from googlecloudsdk.core import config
  File "C:\Users\jonat\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\core\config.py", line 27, in <module>
    from googlecloudsdk.core.util import files as file_utils
  File "C:\Users\jonat\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\core\util\files.py", line 22, in <module>
    import hashlib
  File "C:\Users\jonat\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\hashlib.py", line 138, in <module>
    _hashlib.openssl_md_meth_names)
AttributeError: 'module' object has no attribute 'openssl_md_meth_names'
Failed to install.

**Comment by chemelnucfin** [comment]
Hello, I believe that this is the wrong location to ask about the Google Cloud SDK.  
You can try to look for support here in the left menu.
[Google SDK](https://cloud.google.com/sdk/docs/resources).
