### ISSUE TITLE
BigQuery: Table.full_table_id docstring incorrect

### ISSUE THREAD

**Issue by pumpikano** [GoogleCloudPlatform/google-cloud-python#4900]
It appears to me that the id string format returned by `Table.full_table_id` is actually of the form `project_id:dataset_id.table_id`, contrary to the purported format in the [docstring](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/bae0f754f65afeff8e25b3e2aac86ef671f8ed18/bigquery/google/cloud/bigquery/table.py#L453).

**Comment by jonparrott** [comment]
@pumpikano is it just a canse of the last `:` being a `.`? If so, you're welcome to send a PR to fix this!

**Comment by pumpikano** [comment]
Sure thing!

**Comment by chemelnucfin** [comment]
Closed via #4906
