### ISSUE TITLE
Pubsub docs should have copy-paste-able code samples

### ISSUE THREAD

**Issue by jadekler** [GoogleCloudPlatform/google-cloud-python#4918]
https://googlecloudplatform.github.io/google-cloud-python/latest/pubsub/ has code samples, but when I copy paste them I get gook like the following:

```
topic = 'projects/{project_id}/topics/{topic}'.format(
...     project_id=os.getenv('GOOGLE_CLOUD_PROJECT'),
...     topic='MY_TOPIC_NAME',  # Set this to something appropriate.
... )
```

(note the ellipses all over)

**Comment by jonparrott** [comment]
This is intentional, it's to show what to expect when executing that code in a Python shell.

**Comment by jadekler** [comment]
Are people using pubsub and so on in a shell? Shouldn't we optimize for the application developers?

**Comment by jonparrott** [comment]
We don't have strict guidelines on that sort of thing (or really any sort of thing for client library docs). Instead of ad-hoc making changes, I'd like to work out our overall documentation strategy before making sweeping changes.

**Comment by jadekler** [comment]
👍  sg
