### ISSUE TITLE
BigTable: Cannot get admin access when using from_service_account_json method

### ISSUE THREAD

**Issue by drghifari** [GoogleCloudPlatform/google-cloud-python#4920]
I can't get admin access when i create `bigtable.Client` object using `from_service_account_json`, although the option `admin` already set to `True`. It works well without `from_service_account_json`.

```
>>> client = bigtable.Client(admin=True)
>>> client._admin
True
>>> cred_path = "cred.json"
>>> client = bigtable.Client(admin=True).from_service_account_json(cred_path)
>>> client._admin
False
```
I use `python 2.7.12` and `google-cloud-bigtable==0.28.1`

**Comment by chemelnucfin** [comment]
@drghifari So actually from_service_account_json is a classmethod, which means you should do
`client = bigtable.Client.from_service_account_json(cred_path, admin=True)`

Please let us know if this doesn't solve your problem.
