### ISSUE TITLE
dlp/nox.py is using the old session names

### ISSUE THREAD

**Issue by duggelz** [GoogleCloudPlatform/google-cloud-python#4924]
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/dlp/nox.py

Session names are `unit_test`, `system_test` etc, instead of `unit`, `system`.

**Comment by chemelnucfin** [comment]
Looks like it's been fixed here though: [nox.py.snip](https://github.com/googleapis/toolkit/blob/master/src/main/resources/com/google/api/codegen/py/nox.py.snip)

**Comment by chemelnucfin** [comment]
Looks like it's fixed here in the autogen, so I'm going to close this issue.
https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5049/files/8fd05cf67ae92412aeba8dcc8129add2eafeb52d#diff-29df13b604302b1bdff4f81b6d6ac496R28
