### ISSUE TITLE
Speech: Way to transcribe 2 channel audio file

### ISSUE THREAD

**Issue by chemelnucfin** [GoogleCloudPlatform/google-cloud-python#4927]
Wondering if we have a way out to transcript a 2 channel file like a audio
from call center .
Splitting in 2 channels breaks the conversation .

#4885 for background information.

**Comment by chemelnucfin** [comment]
@abhibeta Currently it seems that the speech api only handles one channel

See [channel](https://cloud.google.com/speech/docs/support)
`The Cloud Speech API service currently supports only one audio channel.`

Also here for some [best practices.](https://cloud.google.com/speech/docs/best-practices)

Just out of curiousity, could you merge the audio channels before processing?  (I'm not sure if this will help or not, but just a suggestion)

Please let us know if you come across any other issues.

**Comment by abhibeta** [comment]
I did that I had 2 channel video departed them and got response .
But then relation ship , sequence of conversation is broken.
Anyways I am doing few more excitements will keep u posted.
