### ISSUE TITLE
Bigtable systests not cleaning up instance

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#4935]
I had an unrelated storage PR fail today due to quota exhaustion, due to 10 existing Bigtable instances already on the CI account.

**Comment by tseaver** [comment]
After clearing out the ten instances, I just ran the system tests locally -- they pass, and do not leave an instance undeleted.

**Comment by jonparrott** [comment]
I suppose we can just close this then? It may have just been due to some weirdness?

**Comment by tseaver** [comment]
@jonparrott I'd rather leave it open for a bit, for reference if it shows up again -- that is the utility of the "flaky" label.

We've had the suspicion that "abrupt" shutdowns on the CI system could explain this kind of thing (e.g., if they `kill -9` the process when a new commit is pushed to the same branch).

**Comment by jonparrott** [comment]
Yeah, maybe we should move to "defensively" cleaning up things - clean up *before* tests run?

**Comment by tseaver** [comment]
How can we know that an instance is not being used by another active CI run?  There is no metadata available (via API queries) to let us list "old" ones (I was verifying them by eye in the console today before deleting them).

**Comment by jonparrott** [comment]
Hrm. Great question. :/

**Comment by tseaver** [comment]
Seems weird that the back-end doesn't expose a `createdTimestamp` metadata field for instances:  that would help us with cleanup.

We could roll our own using `Instance.labels`, but then we would need to add support for that field.

**Comment by sduskis** [comment]
Our HBase Java client tests run on Jenkins, although we only run them against master.  We opted to use a single instance for most of our table admin and data tests.  We run a separate test for instance / cluster operations.

Bigtable cells have a timestamp.  You can create a marker table called "created_date" or something like that, which contains a single row with a single cell which either contains a date in the value and/or in the cell's timestamp.

**Comment by tseaver** [comment]
FTR, I cleaned out four "old" instances this morning (created with the `g-c-p-#####' ids more than a week ago).

**Comment by sduskis** [comment]
@tseaver: Is this still a problem?

**Comment by tseaver** [comment]
I don't see any leaked instances on our CI account today.  However, the problem with test failures that we mark `flaky` is that they tend to come and go:  unless we think we've found and fixed the root cause, I'm reluctant to close the issue.

**Comment by sduskis** [comment]
Can we please define the problem?

My understanding: Tests fail half way, and leave instances are not cleaned up.  Multiple tests may run concurrently, so one test can't easily clean up previously other instances.

Is my understanding correct?

**Comment by tseaver** [comment]
My suspicion is that our system tests run can be terminated "hard" in ways that defeat our normal teardown / cleanup (e.g., CircleCI cancels a job when a new commit is pushed to its branch, via something like `kill -9`).

You are correct that we cannot just remove all instances at the start of a system test run, because of concurrent runs.  If we had a way to filter for "old" instances, e.g. via metadata, lables, etc., then we could remove those at the start of any system test run.

**Comment by sduskis** [comment]
Instances do have labels, and we can add a timestamp label.  However, I found a problem while looking at the `instance.py` [`create()`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/5a79d5dfee95a37501e8d9296775ddbb69984c31/bigtable/google/cloud/bigtable/instance.py#L175).  It looks like that code is not up to date.  I opened #5454 which blocks this issue as well as creating a python sample that looks like our [node.js instance sample](https://github.com/googleapis/nodejs-bigtable/tree/master/samples#instances).

**Comment by sduskis** [comment]
On second thought labels are not the only way of marking an instance.  We can create a table called `create_time` which contains a single row with the key `create_time` with a single family and a single cell containing the creation time.  I don't think that it's as elegant of a solution as labels, but it would be a workable solution to unblock this issue, if we can't fix #5454 quickly.

**Comment by tseaver** [comment]
I believe that we have addressed this issue:  I haven't seen stray CI-generated instances for several months.

**Comment by tseaver** [comment]
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/8110 shows quota exhaustion for the module teardown in both python2.7 and 3.7.
