### ISSUE TITLE
Is it expected for 1 word speech not to be transcribed?

### ISSUE THREAD

**Issue by akmalhakimi1991** [GoogleCloudPlatform/google-cloud-python#4940]
Is it expected for a speech containing 1 short word not being transcribed? For example, if the user only says "no", the API didn't return anything but it has no problem with "no thanks". Is this expected behaviour?

**Comment by jonparrott** [comment]
@dizcology could you take a look at this?

**Comment by crwilcox** [comment]
@akmalhakimi1991, I just tried this with a recording of just 'no' and it seems to output correctly. I ran https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe.py as follows
`
$ python transcribe.py "no.wav"
Transcript: no
`

**Comment by akmalhakimi1991** [comment]
@crwilcox It didn't happen all the time. Maybe it happens in 5 out of 20 times. Maybe you can have 20 different "no" recording and run the test again.

**Comment by chemelnucfin** [comment]
@akmalhakimi1991 I'm going to close this issue as we can't do anything in our client.  The transcription takes place on the backend.  Please let us know if there are anything more we can do.
