### ISSUE TITLE
Please release new pip version of google-cloud-monitoring

### ISSUE THREAD

**Issue by kenashcraft** [GoogleCloudPlatform/google-cloud-python#4942]
Please release a new version of google-cloud-monitoring via pip.  The most recent version is 0.28.0 from Oct 31, 2017.  I'd like to pick up recent bug fixes (e.g. #4910).
https://pypi.org/project/google-cloud-monitoring/#history

**Comment by jonparrott** [comment]
0.28.1 has been released, enjoy!
