### ISSUE TITLE
pubsub: memory leak

### ISSUE THREAD

**Issue by jadekler** [GoogleCloudPlatform/google-cloud-python#4978]
1. Specify the API at the beginning of the title (for example, "BigQuery: ...")

Pubsub

2. OS type and version

alpine 3.6

3. Python version and virtual environment information `python --version`

3.6.1

4. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`

```
google-api-core (0.1.4)
google-auth (1.4.1)
google-cloud-pubsub (0.31.0)
googleapis-common-protos (1.5.3)
grpc-google-iam-v1 (0.11.4)
```

5. Stacktrace if available
6. Steps to reproduce

Stick code provided below on a k8s pod, spam pubsub with messages, watch memory eventually top out at 2.5G and crash the pod.

7. Code example

https://gist.github.com/jadekler/99524a3a8425c45e9299948032dd4e71

<img width="683" alt="screen shot 2018-02-28 at 2 13 00 pm" src="https://user-images.githubusercontent.com/3584893/36816083-9d1b7a12-1c91-11e8-92f1-6f538e6abe25.png">

(pink is python, green is go - python crashes the pod at 2.5gb, go continues at around 30mb as expected)

**Comment by jonparrott** [comment]
@jadekler your sample keeps a dictionary of seen messages - it expect this is at least contributing to memory growth. Can you remove it or use a bloom filter instead?

**Comment by jadekler** [comment]
I bet you're right! I shall do so, sorry for the dummy mistake :)

**Comment by jadekler** [comment]
Ill remove it entirely in fact; it's testing something out of scope for this issue.

**Comment by jonparrott** [comment]
It's fine, I don't think it's the sole cause but definitely will contribute to it.

**Comment by jadekler** [comment]
Happy to report that using grpcio (1.10.0rc2), I'm not seeing any memory leaks.

Full list of deps:

google-api-core (0.1.4)
google-auth (1.4.1)
google-cloud-pubsub (0.32.0)
googleapis-common-protos (1.5.3)
grpc-google-iam-v1 (0.11.4)
grpcio (1.10.0rc2)

<img width="691" alt="screen shot 2018-03-02 at 7 34 49 am" src="https://user-images.githubusercontent.com/3584893/36903935-6544c9fc-1dec-11e8-9ffe-b0b255b4a7ba.png">
