### ISSUE TITLE
Language API not returning begin_offset for entities found.

### ISSUE THREAD

**Issue by Marvincorp** [GoogleCloudPlatform/google-cloud-python#4982]
# Begin offset empty
Language API not returning begin_offset for entities found.

**python version**
Python 3.6.2

**google-cloud-language version:**
Name: google-cloud-language
Version: 1.0.1
Summary: Google Cloud Natural Language API client library
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.6/site-packages
Requires: google-api-core

**Code example**
```
from google.cloud import language_v1beta2 as language
# Also tried:
# from google.cloud import language

language_client = language.LanguageServiceClient()
response = language_client.analyze_entities(document=[MY_DOCUMENT])
```
**Problem description**
language_client will find the the entities, but response.entities will give -1 as begin offset for all entities found.

**Comment by chemelnucfin** [comment]
Hello, could you try adding an encoding type to `analyze_entities`?

Otherwise, If EncodingType is not specified, encoding-dependent information (such as beginOffset) will be set at -1 from 
[here](https://cloud.google.com/natural-language/docs/reference/rest/v1/EncodingType)

**Comment by chemelnucfin** [comment]
Please let us know if you encounter any more problems.
