### ISSUE TITLE
PubSub: Batching / Duplicates issue when consuming messages sequentially.

### ISSUE THREAD

**Issue by ph1l337** [GoogleCloudPlatform/google-cloud-python#4984]
## Env Info 
python 3.5.3
google-cloud-pubsub==0.32.0
macOS 10.13.3

## Problem
I’m currently dealing with a weird issue on PubSub. In the video in the link there are two subscribers that process messages from the same subscription sequentially with thread.Lock and flow_control = 1. The ack deadline of the topic is 10s. 

With a publisher I first send 300 messages (just the number i) to the topic in one batch. The subscribers print the message.

As you can see in the beginning only one of the subscribers starts to receive messages. After some number of messages the second one kicks in (it seems to be number of messages not time - I tried it with adding a sleep in processing the messages). But both subscribers are processing the same messages.

After I clear the buffer I sent the same number of messages again with a batch_size of only 20. Then the two subscribers act as expected. They start at the same time and don’t process duplicate messages.

I assume the problem has to do with how the python consumers pull and caches messages. 

Here's the video:
https://www.useloom.com/share/0b1299d4961b46cd83efc3c13f2a414a

And code to reproduce the issue:
[batching_issue_publisher_and_subscriber.zip](https://github.com/GoogleCloudPlatform/google-cloud-python/files/1775064/batching_issue_publisher_and_subscriber.zip)

**Comment by chemelnucfin** [comment]
@jonparrott this might be related to part of the code on what I'm working on.  Let's coordinate if you will be working on this also.  But I'll be also taking a look at the issue.

**Comment by jonparrott** [comment]
This is likely due to message hoarding. @ph1l337 can you try doing this with flow_control's max_messages set to 100? 

Note that each subscriber will *always* get around 100 messages at a time, regardless of if `max_messages` is less than that due to how the server batches messages. `max_messages` determines how small the local backlog needs to be before getting more messages from the server.

**Comment by ph1l337** [comment]
@jonparrott Thanks for commenting on this issue. Unfortunately changing to 100 messages makes it even worse. In that case *all* messages are processed more than once.

**Comment by ph1l337** [comment]
I did try it with a new topic / subscription and it showed the same behavior.

**Comment by theacodes** [comment]
Hi there, this is part of fundamental limitations of pubsub's streaming implementation. For more details and for potential solutions, see https://cloud.google.com/pubsub/docs/pull#streamingpull.
