### ISSUE TITLE
Please do not use private gRPC API.

### ISSUE THREAD

**Issue by fengli79** [GoogleCloudPlatform/google-cloud-python#4985]
Here's an example:
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/api_core/google/api_core/grpc_helpers.py#L84

_next is not a public API of gRPC python lib, it's subjected to change and there's no guarantee to support it.

**Comment by jonparrott** [comment]
This is intentional.

**Comment by fengli79** [comment]
@jonparrott Again, it's private API and subject to change, you are intentionally ask to be broken when using it.
