### ISSUE TITLE
Monitoring TimeSeries.Query docs: broken links

### ISSUE THREAD

**Issue by mtabasko** [GoogleCloudPlatform/google-cloud-python#5010]
Today (9 March), I received a notice from a link checker that the file at [http://gcloud-python.readthedocs.io/en/latest/monitoring/query.html](http://gcloud-python.readthedocs.io/en/latest/monitoring/query.html) had two bad links to the Stackdriver Monitoring API reference.

Here are two warnings I found:

W,https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list#Aligner,http://gcloud-python.readthedocs.io/en/latest/monitoring/query.html,Anchor: Aligner not found.
W,https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list#Reducer,http://gcloud-python.readthedocs.io/en/latest/monitoring/query.html,Anchor: Reducer not found.

The Aligner and Reducer tags are no longer in the monitoring/api/ref_v3/rest/v3/projects.timeSeries/list.html file. This is a generated file, and in the most recent regeneration of the API (published on 8 March), these two tags and the content associated with them was moved (by the generating tool) to monitoring/api/ref_v3/rest/v3/projects.alertPolicies.html. 
Here's the [alertPolicies](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies) page.

I apologize for this. I was able to pre-emptively fix the links in my own docs that this change would break, but I had no way to know from where else these anchors might be linked to. And I cannot "fix" this with the usual URL redirects mechanism we use when pages move. This is content in a page.

I have filed a bug against the generator for this behavior.

**Comment by jonparrott** [comment]
@chemelnucfin can you take care of this?
