### ISSUE TITLE
ImportError: No module named moves in importing google.cloud.datastore

### ISSUE THREAD

**Issue by vinitpayal** [GoogleCloudPlatform/google-cloud-python#5012]
# Exception getting generated on import google.cloud.datastore

**Versions** :- 

- **OS** : mac(10.13.3) & ubuntu(16.04) [tried on both]
- **Python** : 2.7.14
- **six** : 1.9.0 & 1.11.0(tried on both)
- **google-cloud-datastore** : 1.6.0
- **virtualenv** : 15.1.0

**Stacktrace**  :  

>  from google.cloud.datastore import helpers
 File "/opt/tribes-backend/denv/local/lib/python2.7/site-packages/google/cloud/datastore/helpers.py", line 27, in <module>
 from google.cloud._helpers import _datetime_to_pb_timestamp
 File "/opt/tribes-backend/denv/local/lib/python2.7/site-packages/google/cloud/_helpers.py", line 30, in <module>
 from six.moves import http_client
 ImportError: No module named moves

**What I tried** :- 

Tried printing `dir(six)` after importing in `google/cloud/_helpers.py` line number 30 in output of which I was able to find `moves` package inside six and even if I am importing http_client in my virtual environment using `from six.moves import http_client` it's getting imported correctly but it's just not getting imported inside  `google/cloud/_helpers.py` file.

I have already added `six` in libraries in `appengine_config.py` as suggested in documentation at https://cloud.google.com/appengine/docs/standard/python/tools/built-in-libraries-27.

This issue is getting generated only after latest update in `google-cloud-sdk-app-engine-python-extras` earlier it was working fine.

**Comment by tseaver** [comment]
@jonparrott ISTM that this must be a GAE issue -- if so, please close.

**Comment by jonparrott** [comment]
Yep.

@vinitpayal unfortunately these libraries are not yet supported on GAE standard. Please follow this bug for updates: #1893

**Comment by vinitpayal** [comment]
@jonparrott If I have understood correct you are saying we can't use datastore in GAE standard because I am not including `six` it's being used by datastore. And that's the origin of exception.

Am I understanding something wrong here  ?

**Comment by jonparrott** [comment]
@vinitpayal it's more than just that, there are several things we need to do to make these libraries work on standard. Please keep an eye on #1893 for more updates.
