### ISSUE TITLE
pubsub publisher sometimes fails with StatusCode.UNAUTHENTICATED, Deadline Exceeded

### ISSUE THREAD

**Issue by gcbirzan** [GoogleCloudPlatform/google-cloud-python#5014]
```
Exception in thread Thread-16514:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/google/gax/retry.py", line 121, in inner
    return to_call(*args)
  File "/usr/local/lib/python3.6/site-packages/google/gax/retry.py", line 68, in inner
    return a_func(*updated_args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/newrelic/api/external_trace.py", line 40, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 492, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAUTHENTICATED, Deadline Exceeded)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/publisher/batch/thread.py", line 212, in monitor
    return self._commit()
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/publisher/batch/thread.py", line 173, in _commit
    self.messages,
  File "/usr/local/lib/python3.6/site-packages/google/cloud/gapic/pubsub/v1/publisher_client.py", line 314, in publish
    return self._publish(request, options)
  File "/usr/local/lib/python3.6/site-packages/google/gax/api_callable.py", line 452, in inner
    return api_caller(api_call, this_settings, request)
  File "/usr/local/lib/python3.6/site-packages/google/gax/api_callable.py", line 438, in base_caller
    return api_call(*args)
  File "/usr/local/lib/python3.6/site-packages/google/gax/api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/google/gax/retry.py", line 127, in inner
    ' classified as transient', exception)
google.gax.errors.RetryError: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.UNAUTHENTICATED, Deadline Exceeded)>)
```
```
$ pip freeze | grep google-
gapic-google-cloud-logging-v2==0.91.3
google-api-core==0.1.4
google-api-python-client==1.5.5
google-auth==1.4.1
google-cloud-core==0.28.0
google-cloud-logging==1.4.0
google-cloud-pubsub==0.29.0
google-cloud-trace==0.17.0
google-gax==0.15.16
grpc-google-iam-v1==0.11.4
proto-google-cloud-logging-v2==0.91.3
```
and 1.7.0 grpcio.

There was #4676, but that was closed because it's on appengine. We're on GKE, using a service account with a JSON file.

Our API dashboard shows no errors. To give you an idea of the frequency: http://i.imgur.com/IGkOo1o.png (no idea how to count log entries, not gonna do it by hand) this is for an average of 10 messages per minute (almost none outside of US business hours, peaks at ~.5/second).

**Comment by jonparrott** [comment]
Hi @gcbirzan, it seems you're using an older client. Does this appear with the latest client?

**Comment by gcbirzan** [comment]
Sorry for the delay, the issue seems to come and go randomly. We've updated to `0.32.1` on the 14th and the issue remains: http://i.imgur.com/8AoDhiz.png . While I cannot really confirm it happens less because of the update since after I reported the issue we had a few days with no errors without updating, we do seem to get less of these nowadays. 

However, there's nothing I can correlate these errors to on our side. No changes in usage patterns, no code changes, the issue simply seems to appear and disappear randomly. 

Other things we noticed: When it happens, all our workers are affected, on different pods running on different nodes, though not all at the same time. Generally, the issue goes away after a few hours and only a minority of push operations are affected - subsequent batches go through.

**Comment by jonparrott** [comment]
Does it happen in an interval of about an hour?

(I wonder if #5054 fixes this)

**Comment by gcbirzan** [comment]
It doesn't. Over the past week we had it happen twice. Once started on the 15th at 18:07 UTC and happened again at 18:41 UTC (so just twice). The second started on the 16th at 14:00 UTC and continued until 17:51 UTC, with about 25 occurrences. During that interval, our single worker pod had it happen three times. 14:39:25, 17:37:59, and 16:09:36. 

Between us initiating the publish and the error we had 20, 20, and 13 seconds, and we had tens of successful publishes between the errors. That's relatively weird, I thought the access token expires in an hour?

There's also no correlation between the number of messages we publish, we did 7, 1, 1.

**Comment by jonparrott** [comment]
Ah I see. This is on the publisher side of things. Hrm.

**Comment by gcbirzan** [comment]
Yup. Sorry, I thought starting the ticket name with 'pubsub publisher' gave that away. :)

Not sure how to categorize this ticket. The failures are so rare that one could say we should build our system around handling these failures, but give the architecture of the client that's a bit awkward. Also, since getting the control back is hard, I was hoping that at least the client would take care of some of the retries.

I mean, obviously, it'd be great if we could fix this, but at the end of the day, it might end up that we'll re-do our whole flow around pubsub to survive transient errors like these. I miss ndb/taskqueue's transactional stuff... :(

**Comment by jonparrott** [comment]
Do *do* retry, this is just one of the errors we don't retry on (`UNAUTHENTICATED` should be a terminal state).

**Comment by gcbirzan** [comment]
Well, yeah. But the fact that the error occurs is a bug, still.

**Comment by jonparrott** [comment]
Right yeah, no doubt. :)

**Comment by jonparrott** [comment]
For my own reference - internal bug number for the upstream API issue is 76018588.

**Comment by gcbirzan** [comment]
While internally we're discussing better ways to handle this, is there any update on this, or suggestions on what to try?

**Comment by tseaver** [comment]
@gcbirzan Any more recent sightings from you?

@theacodes Is the upstream ticket still open?

**Comment by theacodes** [comment]
The upstream issue is still open

**Comment by gcbirzan** [comment]
The last error we got on the 17th of June. I'd say this can be closed, but not sure if it's just not a period in which we got lucky.

**Comment by theacodes** [comment]
Cool, let's close for now. We can always re-open. Thanks, @gcbirzan!
