### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'before_request'

### ISSUE THREAD

**Issue by itafras** [GoogleCloudPlatform/google-cloud-python#5015]
I am trying to connect to the cloud Natural Language API.

However when  Iuse analyze_sentiment() it returns the following error: 
`AttributeError: 'unicode' object has no attribute 'before_request'
`

I am trying to connect by passing the credentials explicitly such as described here: 
https://googlecloudplatform.github.io/google-cloud-python/latest/language/usage.html#authentication-and-configuration

To do so I have copied the json file downloaded from my service account keys and copied it in my variable such as : 

```json
creds = {
  "type": "service_account",
  "project_id": "my-project-359380",
  "private_key_id": "83210cd...",
  "private_key": "-----BEGIN PRIVATE KEY-----\nIIgIBjjjhkAD...",
  "client_email": "...",
  "client_id": "114759",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/144462-compute%40developer.gserviceaccount.com"
}


```
and define my client : 
```

# Instantiates a client
client = language.LanguageServiceClient(
    credentials = creds
)
```
then my document to analyze: 
```
document = types.Document(
     content="Testing text analysis",
     language='en',
     type=enums.Document.Type.PLAIN_TEXT,
)

```

but the error is returned after  Icall for the response : 

```
response  = client.analyze_sentiment(
    document = document
)
```

I am running with python 2.7 on a mac OS. with the following package versions: 
google-api-core==1.0.0
google-auth==1.4.1
google-cloud-language==1.0.1
googleapis-common-protos==1.5.3

Full stack trace file is attached
[stacktrace.txt](https://github.com/GoogleCloudPlatform/google-cloud-python/files/1803852/stacktrace.txt)

**Comment by tseaver** [comment]
@itafras The `credentials` argument you are passing to the `LanguageServiceClient` constructor is meant to be an instance of `google.auth.credentials.Credentials`.  Please see the [`google.auth` docs](https://google-auth.readthedocs.io/en/latest/user-guide.html#obtaining-credentials) for how to create that instance from the values in your mapping.
