### ISSUE TITLE
logging: RequestMiddleware not compatible with Django 2

### ISSUE THREAD

**Issue by tcroiset** [GoogleCloudPlatform/google-cloud-python#5024]
@liyanhui1228 we really appreciated the trace context feature to group logs by request.
Unfortunately, it looks broken with Django 2.

Django 1.10 introduced a new middleware style ( https://docs.djangoproject.com/en/1.10/releases/1.10/#new-style-middleware )

The old style, used by google.cloud.logging.handlers.middleware.request.RequestMiddleware, support was removed with Django 2.

**Comment by jonparrott** [comment]
@liyanhui1228 Can you take this on?

**Comment by tseaver** [comment]
Via #5504.
