### ISSUE TITLE
Release spanner 1.2.0

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#5028]
Batch query support is merged.

Note that `development_status` is still showing beta.

**Comment by jonparrott** [comment]
On it.

**Comment by jonparrott** [comment]
Need to release api_core first: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5029

**Comment by jonparrott** [comment]
Updated api-core version: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5030

**Comment by jonparrott** [comment]
Fixed release status in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5031
