### ISSUE TITLE
'_load_credentials_from_file' not finding file on Windows

### ISSUE THREAD

**Issue by EmilianoCervantes** [GoogleCloudPlatform/google-cloud-python#5039]
I followed the Sentiment Analysis tutorial: https://cloud.google.com/natural-language/docs/sentiment-tutorial

I set up a Cloud Natural Language API project, the credentials.

Next I run "pip install --upgrade virtualenv" and finally I installed Google Cloud Client Library for Python with "pip install --upgrade google-cloud-language".

I copy-pasted the first code """Demonstrates how to make a simple call to the Natural Language API."""
It immediately marked an error.
![image](https://user-images.githubusercontent.com/11279332/37434533-7c36e6e6-27a5-11e8-8260-c1d4f69dc831.png)

And it was the only one. Does anyone know if I have to upgrade something? (Although I would find it strange as I just installed everything the tutorial asked for)

I'm currently on Windows 10, the other imports seem fine, I don't get errors from anything else.

**Comment by EmilianoCervantes** [comment]
I think is more of a problem with Visual Studio Code. Originally I ran it with the debug function of VSC, now I'm trying with the cmd and it executes the sentiment-analysis.py.
(Although I have now this issue, but I don't know if this is the place to put it jeje)
![image](https://user-images.githubusercontent.com/11279332/37436700-cfa43fdc-27ae-11e8-8bc8-4b4472fac16f.png)

**Comment by EmilianoCervantes** [comment]
About that, I discovered it was because I was missing the argument.

**Comment by EmilianoCervantes** [comment]
I think is more of a problem with Visual Studio Code. Originally I ran it with the debug function of VSC, now I'm trying with the cmd and it executes the sentiment-analysis.py.

**Comment by EmilianoCervantes** [comment]
But now that I run my app.

I opened a terminal, then run "gcloud auth activate-service-account --key-file="C:\...\credentialsFile.json"
Next "set GOOGLE_APPLICATION_CREDENTIALS="C:\...\credentialsFile.json"
And then I ran the app but got this new issue:

File "C:\Users\ovman\anaconda3\lib\site-packages\google\auth\_default.py", line 67, in _load_credentials_from_file
    'File {} was not found.'.format(filename))

google.auth.exceptions.DefaultCredentialsError: File "C:\...\credentialsFile.json" was not found.

**Comment by chemelnucfin** [comment]
Does this help?
[credentials from file](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4787#issuecomment-360347124)

**Comment by chemelnucfin** [comment]
Hello, I'm going to close this issue.  If you are still encountering problems, please do let us know.

Thanks.
