### ISSUE TITLE
[speech] Random crash with message "assertion failed: pthread_mutex_lock(mu) == 0"

### ISSUE THREAD

**Issue by akmalhakimi1991** [GoogleCloudPlatform/google-cloud-python#5041]
Hi. I have a program that use `arecord `module to stream audio to google-cloud-speech API. The module is called by `os.popen`. Sometime, the program crash with this error:  `assertion failed: pthread_mutex_lock(mu) == 0`. It happened randomly and I didn't notice any pattern. I run a stress test on the program without google-cloud-speech and it didn't happen.   
  
Note that, previously `arecord `module was called by `subprocess.Popen`. I never see this mutex error at the time. However, after I updated google-cloud-speech (sadly I can't remember which version to which version), it stop working. I raised this issue [here](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1265). It started working again after speech 0.32.0 but sadly that version is unusable for me since it's causing memory leak.

**Comment by tseaver** [comment]
This pretty much has to be a bug in `gRPC`, likely [this one](https://github.com/grpc/grpc/issues/13873).  That bug was just recently closed, and points to this [fork support status](https://github.com/grpc/grpc/blob/master/doc/fork_support.md) doc.

In the bug I linked, they state that forking only works if the `fork` call (which `subprocess.Popen` makes) occurs before any gRPC connections have been established.  Can you show us your code?

**Comment by akmalhakimi1991** [comment]
@tseaver PFA the code that I'm using. 
[sample_code_arecord.txt](https://github.com/GoogleCloudPlatform/google-cloud-python/files/2061369/sample_code_arecord.txt)

**Comment by tseaver** [comment]
The gRPC docs I linked above seem to say that your code will trigger the gRPC issue, as your application forks a new process each time you loop over `stt_client.listenSpeech()`.  I have no idea why the `os.popen` version would work, but not the `subprocess.Popen` one.  I know that `os.popen2` (and `popen3` and `popen4`) are just wrappers around `subprocess.Popen`:  they end up passing `shell=True` for a string command, which might make a difference.

I'm going to close the issue, as I don't believe there is anything in `google-cloud-speech` which is causing the problem.  Please feel free to keep discussing the issue:  if we do discover a bug here, we can reopen.

**Comment by akmalhakimi1991** [comment]
If thats the case, do you have any suggestion on what I should from on my side?

**Comment by keshav-zoop** [comment]
> If thats the case, do you have any suggestion on what I should from on my side?

Did you solve the issue ?
