### ISSUE TITLE
Migrating google-cloud-pubsub based code from 0.25 to 0.32

### ISSUE THREAD

**Issue by riklaunim** [GoogleCloudPlatform/google-cloud-python#5052]
I have some code that uses google-cloud-pubsub in version 0.25 and is run on Kubernetes and minikube locally. I'm trying to update the code to be compatible with latest package version  but I have some problems with configuration when running in minikube.

Old version created the pubsub client in development like this:
```
with utils.EnvironmentContext('PUBSUB_EMULATOR_HOST', 'dev-pubsub:8042'):
    return pubsub.Client(_http=httplib2.Http(), _use_grpc=False)
```
But in 0.32 PublisherClient nor SubscriberClient don't have those kwargs. There is GOOGLE_CLOUD_DISABLE_GRPC env variable that can be set (to a string and not a bool?) but still when I try to use my service it looks like it's trying to authenticate via gRPC:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/grpc/_plugin_wrapping.py", line 77, in __call__
    callback_state, callback))
  File "/usr/local/lib/python3.6/site-packages/google/auth/transport/grpc.py", line 77, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/usr/local/lib/python3.6/site-packages/google/auth/transport/grpc.py", line 65, in _get_authorization_headers
    headers)
  File "/usr/local/lib/python3.6/site-packages/google/auth/credentials.py", line 121, in before_request
    self.refresh(request)
  File "/usr/local/lib/python3.6/site-packages/google/oauth2/service_account.py", line 322, in refresh
    request, self._token_uri, assertion)
  File "/usr/local/lib/python3.6/site-packages/google/oauth2/_client.py", line 145, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/usr/local/lib/python3.6/site-packages/google/oauth2/_client.py", line 111, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/usr/local/lib/python3.6/site-packages/google/oauth2/_client.py", line 61, in _handle_error_response
    error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_client: The OAuth client was not found.', '{\n  "error" : "invalid_client",\n  "error_description" : "The OAuth client was not found."\n}')
```
What's the correct way to handle dev configuration for 0.32? (was working ok for 0.25)

**Comment by tseaver** [comment]
Both the [publisher client](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/cd067f6325dc0ef575d12e7003f48a14eb0e4583/pubsub/google/cloud/pubsub_v1/publisher/client.py#L66) and the [subscriber client](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/cd067f6325dc0ef575d12e7003f48a14eb0e4583/pubsub/google/cloud/pubsub_v1/subscriber/client.py#L59) should bypass credentials altogether if the `PUBSUB_EMULATOR_HOST` environment variable is set.

I'm not familiar with `utils.EnvironmentContext`.  Can you add an assertion inside your `with` block to check that `os.environ['PUBSUB_EMULATOR_HOST']` is set as expected?

**Comment by gcbirzan** [comment]
As a note, everything after `0.28.0` requires GRPC so those arguments don't make any sense. But, the emulator (if recent enough, I guess?) should work with the new version.

**Comment by riklaunim** [comment]
I've did some debugging and the PUBSUB_EMULATOR_HOST was set within the with block, but wasn't set when the client was actually used - when I fixed that it works.

Notices I can't do future.result() due to NotImplemented exception.

**Comment by riklaunim** [comment]
pubsub is working locally after updates aside of subscriptions callbacks. `future = subscription.open(callback)` returns a Future that is `.running()` for a moment. Callback doesn't seems to be called while using `future.result()` throws `google.api_core.exceptions.MethodNotImplemented: 501 Method not found: google.pubsub.v1.Subscriber/StreamingPull` which I found to be described at: https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.proto#L128 - how to handle this?

**Comment by jonparrott** [comment]
It seems the emulator doesn't support streaming pull.

**Comment by riklaunim** [comment]
Yep, emulator was quite old as the docker image wasn't versioned in any way. Bumping to 2018.02 solved that problem. Moving forward :)

**Comment by jonparrott** [comment]
Cool, it seems we can close this. Let me know if there's anything else to be done.
