### ISSUE TITLE
container: operation status inconsistent

### ISSUE THREAD

**Issue by hawksight** [GoogleCloudPlatform/google-cloud-python#5053]
When using the API for list operations, the status is returning differently when you full output and when you specifically select the status field.

See examples below bullets.

1. `google-cloud-container` 
2. OS type and version - MacOS High Sierra - 10.13.3
3. Python 3.6.4 - venv
4.  `pip3 freeze`
```
google-api-core==1.0.0
google-auth==1.3.0
google-cloud-container==0.1.1
googleapis-common-protos==1.5.3
```
5. Stacktrace if available - N/A
6. Steps to reproduce - See 7
7. Code example
```
from google.cloud import container_v1
client = container_v1.ClusterManagerClient()
project_id = ''
zone = ''
output = client.list_operations(project_id, zone)

# Outputs as expected
print(output)

# Try and get status for each operation - returns int rather than string
for i in output.operations:
     print(i.status)
```

### Example of what it looks like from `print(output)`
```
operations {
  name: "operation-1521202221403-23e4f4c7"
  zone: "us-central1-a"
  operation_type: CREATE_CLUSTER
  status: DONE
  self_link: "some-link
  target_link: "some-link"
  start_time: "2018-03-16T12:10:21.403482789Z"
  end_time: "2018-03-16T12:13:48.507570177Z"
}
```

### Example when getting each status `i.status`
```
3
```

I would have expected `DONE` to be output as it was in the first output.

Is there a reference to what these numbers represent? i.e is 3 always "DONE".
What would be the number for "RUNNING". Or could the outputs be made to be consistent please?

I checked other fields and they output the same type / response:
### Example of calling name or zone
```
# without status
In [15]: for i in output.operations:
    ...:     print(i.name, i.zone)
    ...:
operation-1521202221403-23e4f4c7 us-central1-a
operation-1521202436016-5517e589 us-central1-a
operation-1521202763615-dad7af1f us-central1-a

# with status
In [16]: for i in output.operations:
    ...:     print(i.name, i.zone, i.status)
    ...:
operation-1521202221403-23e4f4c7 us-central1-a 3
operation-1521202436016-5517e589 us-central1-a 3
operation-1521202763615-dad7af1f us-central1-a 3
```

**Comment by tseaver** [comment]
What you are seeing here is "normal" for protobuf messages:  the first example prints the whole `Operation` protobuf, and uses its `__repr__`, which applies the decoding of the integer status using the enum.  The second pulls out the integer value.

**Comment by chemelnucfin** [comment]
As for the enum mapping, that can be found here
[enums](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/speech-0.32.1/container/google/cloud/container_v1/gapic/enums.py#L70)

The link points to an irrelevant tag, but it's an old one that won't get changed.

**Comment by hawksight** [comment]
Thanks for the pointers, that was a learning experience for me. 

Just a handy helper for anyone else... if you want to get the status, here's an example that worked for me:
```
from google.cloud.container_v1.types import Operation
Operation.Status.Name(i.status)
```
