### ISSUE TITLE
pubsub: long-running app falls over after couple minutes

### ISSUE THREAD

**Issue by jadekler** [GoogleCloudPlatform/google-cloud-python#5058]
1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types

pubsub

2. OS type and version

`alpine:3.6` docker image

3. Python version and virtual environment information `python --version`

3.6.1

4. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`

```
google-cloud-pubsub (0.32.1)
googleapis-common-protos (1.5.3)
grpc-google-iam-v1 (0.11.4)
grpcio (1.10.0rc2)
```

5. Stacktrace if available

(see image below)

6. Steps to reproduce

- [Code here](https://gist.github.com/jadekler/f71bf7fd8443bbe1e28b08f4036524a9)
- [Dockerfile here](https://gist.github.com/jadekler/0a857a84554c092f44ffe7c4b6a54cef)

Build the docker image, stick on GKE, check that it's receiving a couple of times, then wait until you see:

<img width="1602" alt="screen shot 2018-03-16 at 12 45 04 pm" src="https://user-images.githubusercontent.com/3584893/37541491-0ef51a02-2918-11e8-8f54-1b52bffd7ecb.png">

<img width="1353" alt="screen shot 2018-03-16 at 12 45 26 pm" src="https://user-images.githubusercontent.com/3584893/37541496-12653776-2918-11e8-82e2-cbc058c90d9b.png">

<img width="1336" alt="screen shot 2018-03-16 at 12 45 33 pm" src="https://user-images.githubusercontent.com/3584893/37541498-14d7e774-2918-11e8-976f-ebdaa25e3acf.png">

<img width="1330" alt="screen shot 2018-03-16 at 12 45 40 pm" src="https://user-images.githubusercontent.com/3584893/37541500-175b8cbc-2918-11e8-89e9-1c75b0de3b79.png">

**Comment by jadekler** [comment]
ping @jonparrott @lukesneeringer

**Comment by jadekler** [comment]
Redeploying (no code/docker changes) to see if I can replicate.

**Comment by jadekler** [comment]
I can confirm that this happens within a couple of minutes of starting. It has happened twice in a row now.

**Comment by jonparrott** [comment]
@jadekler can you try with #5054?

**Comment by jadekler** [comment]
Hey @jonparrott - I probably won't be able to get to today, but the provided repro code above should be complete if you want to give it a spin. Give a shout if you have troubles, I'll asynchronously check back in on this issue.

**Comment by ppawiggers** [comment]
I can confirm this bug, I experience the same issue. First couple of minutes it runs fine, then it crashes.

**Comment by lukesneeringer** [comment]
I am working on reproducing this with a #5054 fork, _hopefully_ to help establish that it works. :-)

**Comment by lukesneeringer** [comment]
@jadekler Do I need to do anything other than `docker run [image]` and wait?

**Comment by jonparrott** [comment]
you shouldn't need to.

**Comment by jadekler** [comment]
Hi @lukesneeringer - as @jonparrott mentioned, this occurs to me within in the first few minutes. I just double checked, and can confirm.

ps sorry for the very late reply!

**Comment by Lawouach** [comment]
I am noticing the same issue here as well.

**Comment by Lawouach** [comment]
Trying that PR, I don't see the error anymore. At least, in the past, it was fairly quick to be triggered. I don't know if this is the appropriate fix but it seems to help @jonparrott :)

**Comment by jonparrott** [comment]
That's great news. @lukesneeringer, what do you think about getting that merged? :)

**Comment by Lawouach** [comment]
Out of curiosity, what's the release process like? Just to know if I will have to depend on a commit from this repo (once it's merged) or hope for a fast release? :)

**Comment by jonparrott** [comment]
I want to cut a new release after that PR is merged. Should be relatively short.

**Comment by Lawouach** [comment]
Wow! Awesome :) Thank you! :)

**Comment by lukesneeringer** [comment]
I also ran it for multiple hours with no issues. Let's get it merged.

**Comment by jonparrott** [comment]
Can you expand thos exceptions so I can see the full traceback?

**Comment by jadekler** [comment]
<img width="1570" alt="screen shot 2018-03-23 at 5 47 27 pm" src="https://user-images.githubusercontent.com/3584893/37839115-51c0c048-2ec2-11e8-8298-06598aa89790.png">

<img width="1569" alt="screen shot 2018-03-23 at 5 47 32 pm" src="https://user-images.githubusercontent.com/3584893/37839124-5940dfd8-2ec2-11e8-85c4-6ec07fa5ceda.png">

<img width="1577" alt="screen shot 2018-03-23 at 5 47 46 pm" src="https://user-images.githubusercontent.com/3584893/37839132-5d556fa8-2ec2-11e8-855d-baded982587f.png">

**Comment by jonparrott** [comment]
Hrm, `Invalid Argument` is a new one. Does this happen immediately or after some time?

**Comment by jadekler** [comment]
~5m

**Comment by jonparrott** [comment]
I've yet to be able to reproduce the invalid argument thing. :/

**Comment by jadekler** [comment]
@jonparrott I'm unable to duplicate the error (just tried now). I'll keep watching the logs. Are the memory problems (inclusive of grpc) resolved, or are we still waiting for releases? Sorry I'm behind the times!

**Comment by jonparrott** [comment]
still waiting on releases but you can try with 1.10.1rc1. Also, before you retry wait for https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5136 (unless you're testing with HEAD).

**Comment by jadekler** [comment]
@jonparrott Using `1.10.1rc1`, I get very weird results. My logs are showing reception and acking of messages, but my stackdriver graphs are showing 0 acked messages (and Undelivered Messages stays constant).

**Comment by jadekler** [comment]
Current problem, the following error occurs after 5-120s:

![screen shot 2018-04-03 at 10 15 44 am](https://user-images.githubusercontent.com/3584893/38264994-806a1812-3729-11e8-87f7-063cdccb5689.png)

**Comment by jonparrott** [comment]
The root cause of this is that gRPC is rejecting our request because it's larger than the default flow control limits at the _grpc_ level.

The actual error message (from the trailing metadata) is `Message size exceed the limitation of byte based flow control.`.

This is because Jean's example does not have pub/sub-level flow control enabled which leads to message hoarding (a large backlog of local messages pending processing) so when the stream is closed and resumed the client will attempt to modack all currently held messages, leading to a very large initial request.

It is my hunch that reasonable pub/sub-level flow control will prevent this from ever occurring, so @jadekler is going to re-test this with flow control enabled. 

If it does not, we should consider a helper method to split requests as needed (such as in [go](
 https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/service.go#L81). Node.js took the route of [disabling the max message size](
Related: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1991) which I do not think is the appropriate fix.

**Comment by jadekler** [comment]
Closing this, since grpc=1.10.1 and above seem to work without problems.
