### ISSUE TITLE
Re-do fix to run only affected systests on CircleCI

### ISSUE THREAD

**Issue by theacodes** [GoogleCloudPlatform/google-cloud-python#5083]
It seems #5018 broke our tests, and now circle is skipping stuff.

See https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5079

**Comment by chemelnucfin** [comment]
temporary fix in #5092

**Comment by tseaver** [comment]
Tweaked after merge of #5092.

**Comment by tseaver** [comment]
#5487 *seems* to be the right fix:  the clue was to do the `git merge-base --fork-point` test against `baseline/master` (the local master is in some weird state).
