### ISSUE TITLE
PubSub blocking consumer falls after several minutes 

### ISSUE THREAD

**Issue by NuwanSameera** [GoogleCloudPlatform/google-cloud-python#5087]
1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
               pubsub
2. OS type and version
               launcher.gcr.io/google/python:latest

3. Python version and virtual environment information `python --version`
              Python 3.4.2

4. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
        google-api-core==1.1.0
        google-auth==1.4.1
        google-cloud-pubsub==0.32.1
        googleapis-common-protos==1.5.3
        grpc-google-iam-v1==0.11.4
        grpcio==1.10.0
        protobuf==3.5.2.post1

5. Stacktrace if available
![image](https://user-images.githubusercontent.com/11611868/37702718-730f5854-2d19-11e8-88f8-da153a013b5a.png)

![image](https://user-images.githubusercontent.com/11611868/37702772-97ea83b0-2d19-11e8-9478-6845c70b86a3.png)

![image](https://user-images.githubusercontent.com/11611868/37702807-b3ec3e32-2d19-11e8-959f-ab1a04817203.png)

6. Steps to reproduce
       
[deployment.yaml.txt](https://github.com/GoogleCloudPlatform/google-cloud-python/files/1832735/deployment.yaml.txt)
[Dockerfile.txt](https://github.com/GoogleCloudPlatform/google-cloud-python/files/1832736/Dockerfile.txt)
[server.py.txt](https://github.com/GoogleCloudPlatform/google-cloud-python/files/1832737/server.py.txt)

**Comment by jonparrott** [comment]
@NuwanSameera I believe this is solved by #5054 and should be in Pubsub `0.33.0`. Closing this for now assuming that this is the same issue. Let me know if you can reproduce on the latest version and we can re-open.
