### ISSUE TITLE
Storage - High Memory Usage (6-7GB) uploading large file compared to gsutil

### ISSUE THREAD

**Issue by family-guy** [GoogleCloudPlatform/google-cloud-python#5088]
similar to https://github.com/GoogleCloudPlatform/google-cloud-node/issues/397 (the 'Shutting these off' link is unfortunately broken)
1.
Storage

2.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

`Linux guy-xps-13-9360 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

16GB RAM

3.
Python 3.6.4 :: Anaconda, Inc.
ipython 6.2.1
conda 4.4.7
  - pip:
    - cachetools==2.0.1
    - dill==0.2.7.1
    - future==0.16.0
    - gapic-google-cloud-datastore-v1==0.15.3
    - gapic-google-cloud-error-reporting-v1beta1==0.15.3
    - gapic-google-cloud-logging-v2==0.91.3
    - google-api-core==0.1.4
    - google-auth==1.4.1
    - google-cloud==0.32.0
    - google-cloud-bigquery==0.28.0
    - google-cloud-bigquery-datatransfer==0.1.1
    - google-cloud-bigtable==0.28.1
    - google-cloud-container==0.1.1
    - google-cloud-core==0.28.1
    - google-cloud-datastore==1.4.0
    - google-cloud-dns==0.28.0
    - google-cloud-error-reporting==0.28.0
    - google-cloud-firestore==0.28.0
    - google-cloud-language==1.0.1
    - google-cloud-logging==1.4.0
    - google-cloud-monitoring==0.28.1
    - google-cloud-pubsub==0.30.1
    - google-cloud-resource-manager==0.28.1
    - google-cloud-runtimeconfig==0.28.1
    - google-cloud-spanner==0.29.0
    - google-cloud-speech==0.30.0
    - google-cloud-storage==1.6.0
    - google-cloud-trace==0.17.0
    - google-cloud-translate==1.3.1
    - google-cloud-videointelligence==1.0.1
    - google-cloud-vision==0.29.0
    - google-gax==0.15.16
    - google-resumable-media==0.3.1
    - googleapis-common-protos==1.5.3
    - grpc-google-iam-v1==0.11.4
    - grpcio==1.10.0
    - httplib2==0.10.3
    - oauth2client==3.0.0
    - ply==3.8
    - proto-google-cloud-datastore-v1==0.90.4
    - proto-google-cloud-error-reporting-v1beta1==0.15.3
    - proto-google-cloud-logging-v2==0.91.3
    - protobuf==3.5.2.post1
    - psutil==5.4.3
    - pyasn1==0.4.2
    - pyasn1-modules==0.2.1
    - rsa==3.4.2

4.
Name: google-cloud
Version: 0.32.0

6.
Save a large file (in my case, ~3GB mp4) to disk and upload to google cloud using python client lib. During upload, in bash run `top`, locate the PID, `top -p <pid>` and check `%MEM` column. I was seeing an average of ~40% whereas doing the same thing using `gsutil cp` averaged maybe <1%

![screenshot from 2018-03-21 16-00-54](https://user-images.githubusercontent.com/8340336/37722271-78be85c2-2d23-11e8-9e7e-034085f634fa.png)

7.
```
from google.cloud import storage
import os

client =storage.Client()
path = '~/Downloads/large.mp4'
bucket = client.get_bucket('my-bucket')
dest_file_path = os.path.join('media', 'large-video.mp4')
blob=storage.Blob(dest_file_path, bucket)
mime_type='video/mp4'
with open(path, 'rb') as f:
    blob.upload_from_file(f, content_type=mime_type)
```

**Comment by tseaver** [comment]
For large file uploads, you need to set a chunk size on the blob, e.g.:

```python
from google.cloud import storage

CHUNK_SIZE = 128 * 1024 * 1024  # season to taste

client = storage.Client()
bucket = client.bucket('your-bucket-1234')
blob = bucket.blob('really-big-blob', chunk_size=CHUNK_SIZE)
blob.upload_from_filename('/path/to/really-big-file')
```
