### ISSUE TITLE
Excluded indexes from nested Array

### ISSUE THREAD

**Issue by duyphuong13** [GoogleCloudPlatform/google-cloud-python#5111]
Hi team, 
Currently I couldn't exclude indexs of properties inside array when using google-cloud-python 

My model is quite complex,1 flow contains many flow childs and each child could contains other flow childs as well

Flow model: 
```javascript
{
  title: 'name',
  description: 'LONG_TEXT_HERE',
  flow_children: [ 
      {
        title: 'name',
        description: 'LONG_TEXT_HERE',
        flow_children: []
    }
   ] 
}
```

Im trying to follow document to exclude indexs by several way but it didnt work.
```python
task = datastore.Entity(key=key, exclude_from_indexes=['consideration','description','flow_children','flow_children[].description'])
```

Still get below error 
`google.api_core.exceptions.BadRequest: 400 The value of property "description" is longer than 1500 bytes.`

Then I try to use google cloud console to update entity with value and index directly, it works.
```javascript
{
  "values": [
    {
      "entityValue": {
        "properties": {
          "flow_children": {
            "arrayValue": {
              "values": [
                {
                  "entityValue": {
                    "properties": {
                      "description": {
                        "stringValue":"LONG_TEXT_HERE",
                       "excludeFromIndexes": true
          },
          "type": {
            "stringValue": "flowstep"
          },
          "title": {
            "stringValue": "Go to back yard"
          }
        }
      }
    }
  ]
}
```

Anyone could help me with this case please :(

Thanks
My envs:
python 3.6.4
google-cloud-datastore 1.4.0
Macosx High Serria

**Comment by chemelnucfin** [comment]
Hello, it seems like from this:

**Comment by chemelnucfin** [comment]
Hello, it seems like [this](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1206)
is similar to your issue?  Could you reproduce the problem with the code sample there?

**Comment by duyphuong13** [comment]
Thanks for your reply @chemelnucfin 

I already read the issue about but it's apply for embedded entity. 
My situation is array
I put  my sample code here
```python
@app.route('/')
def partner():
    ds = datastore.Client()

    data = {
        'timestamp': datetime.datetime.utcnow(),
        'test1': 'test 111',
        'test2': 'test 2',
        'long_text': 'LONG_TEXT_HERE',
        'flow_children':  [
            {
                'long_text': 'LONG_TEXT_HERE'
            }
        ]
    }

    _id = str(uuid.uuid4())

    key = ds.key('Test', _id)
    entity = datastore.Entity(key=key,exclude_from_indexes=["long_text", "flow_children", "flow_children[].long_text"])
    entity.update(data)
    ds.put(entity)
    data['partner_id'] = _id
    output = jsonify(data)
`

**Comment by chemelnucfin** [comment]
@tseaver @jonparrott so it seems like exclude_from_indexes does not propagate down to dictionaries inside a list.  

Do we want the full path of exclude_from_indexes (as in splitting on dots or something) or does just the name of the index anywhere?
As in my first example, exclude `'long_text'` or `'long.long_text'` or `long[long_text]`, or something else?

**Comment by euri10** [comment]
seems like it's fixed in the node client https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1916

**Comment by tseaver** [comment]
@duyphuong13 For nested values to be excluded, they must be created as `Entity` instances, rather than bare `dict`s.  So, for your example, I wrote [this gist](https://gist.github.com/tseaver/196a26f3ebeaa08e9f63260e39e6843b).

**Comment by tseaver** [comment]
I'm going to close preemptively.  Please feel free to follow up / reopen if my answer above doesn't work for you.

**Comment by brunoais** [comment]
@tseaver If I do as you mention, I get:

> ValueError: Entity must have a key

What I'm doing is translatable to this code:

```
entity = datastore.Entity()
entity['small_val'] = small_val
entity['sub_dict'] = datastore.Entity()
entity['sub_dict'].update(has_large_values)

if len(entity['sub_dict']['maybe_large_value']) > large_value:
    entity['sub_dict'].exclude_from_indexes.add('maybe_large_value')

client.put(entity)
```

How do I solve this, then?

**Comment by paddie** [comment]
For anyone else struggling with this one and landing on this page, much like myself, here's a snippet that is a bit more comprehensible than the one above IMO:

```python
key = client.key("MyKind", f"{account_id}_{integration_id}")
# this is not enough to not index the secret
integration = datastore.Entity(key=key, exclude_from_indexes=["secret"])

# ensure that nested fields are not indexed - *le sigh*
keys = secret.keys()
secret_entity = datastore.Entity(exclude_from_indexes=list(keys))
secret_entity.update(secret)


record = {
    "integration_id": integration_id,
    "account_id": account_id,
    "secret": secret_entity,
    "created_at": datetime.utcnow(),
    "updated_at": datetime.utcnow(),
    "visible_fields": visible_fields or [],
}
integration.update(record)

client.put(integration)
```
