### ISSUE TITLE
bigquery parquet loading code not available on pypi, please push dev release

### ISSUE THREAD

**Issue by bmabey** [GoogleCloudPlatform/google-cloud-python#5132]
I'm evaluating the BigQuery new support for loading from parquet files and following the code samples from:

https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-parquet

The above uses code that is not yet on pypi. I can build it locally but for rolling out our real tests it would be convenient if a release could be made.  It doesn't have to be an offical release, just pushing the dev release would be enough: https://github.com/GoogleCloudPlatform/google-cloud-python/commit/fc91c877eb6aee2a8edfd5a8950bc5ca51e8255c

/cc @tswast

**Comment by tseaver** [comment]
I'm reluctant to push out dev releases to PyPI, but will defer to @jonparrott.

**Comment by bmabey** [comment]
nm, I found the how to install the package via a github url (I didn't realize you could specify a subpackage in the URL): https://github.com/pydata/pandas-gbq/pull/152/files#diff-354f30a63fb0907d4ad57269548329e3R33

**Comment by bmabey** [comment]
@tswast you just saved me hours of python dep yak shaving, thank you! Using the string is working fine with my current version of the client.
