### ISSUE TITLE
pubsub_v1.types segmentation fault (low priority)

### ISSUE THREAD

**Issue by dmsolow** [GoogleCloudPlatform/google-cloud-python#5152]
Calling `help` on `pubsub_v1.types` causes a segfault:

```
Python 3.6.5 (default, Mar 29 2018, 03:28:50) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import pubsub_v1
>>> help(pubsub_v1.types)
Segmentation fault (core dumped)
```
google.cloud version is 0.33.0. OS is ubuntu 16.04

Not a high priority issue, but I thought it was odd.

**Comment by jonparrott** [comment]
This should be fixed in the latest protobuf: https://github.com/google/protobuf/issues/2974
