### ISSUE TITLE
No Error: File uploaded not found on the google-cloud-storage

### ISSUE THREAD

**Issue by santhoshdc1590** [GoogleCloudPlatform/google-cloud-python#5161]
1. Google Cloud Storage
2. MacOS Sierra
3. Python version 3.6 
4. google-cloud-python version 0.32.0

Trying to upload a `tempfile` in jpeg format onto `Google-Cloud-Storage`

Here's the code

```
from google.cloud import storage
import cv2
from tempfile import NamedTemporaryFile
import os
from matplotlib import pyplot as plt

client = storage.Client()

bucket = client.get_bucket('document')

image = cv2.imread('15.png')

with NamedTemporaryFile() as temp:
    print(type(temp.name)," ",temp.name)
    iName = "".join([str(temp.name),".jpg"])
    print(iName)
    cv2.imwrite(iName,image)

    print(os.path.exists(str(iName)))
    blob = bucket.blob('document/Test15.jpg')
    blob.upload_from_filename(iName,content_type='image/jpeg')

    im1 = cv2.imread(iName)
    plt.subplot(111), plt.imshow(cv2.cvtColor(im1, cv2.COLOR_BGR2RGB))
    plt.title('15.jpg'), plt.xticks([]), plt.yticks([])
    plt.show()

```

No error 

> <class 'str'>   /var/folders/5j/bqk11bqj4r55f8975mn__72m0000gq/T/tmptt6p2uqi
> /var/folders/5j/bqk11bqj4r55f8975mn__72m0000gq/T/tmptt6p2uqi.jpg
> True
> 
> Process finished with exit code 0

Can anyone tell where and what is going wrong?

**Comment by crwilcox** [comment]
Hi @santhoshdc1590 , 

I just ran the code you have provided and it did what I expected. I have a png saved in google cloud in a bucket as 'document/Test15.png'. I created a miniconda3 environment (python 3.6.5), installed google-cloud==0.32.0, opencv, and matplotlib.

Something interesting about your code though, You aren't reading the file from your google cloud storage bucket. You are just showing it from the disk storage. If you are trying to show that your file was in storage you could do the following.

'''
from google.cloud import storage
from tempfile import NamedTemporaryFile
import os
import filecmp

PROJECT='crwilcox-test'
BUCKET='crwgoog-test-bucket'
FILENAME='15.png'

client = storage.Client(PROJECT)
bucket = client.get_bucket(BUCKET)


blob = bucket.blob('document/Test15.jpg')
blob.upload_from_filename(FILENAME,content_type='image/jpeg')

with open('fromBlob.png', 'wb') as f:
    blob.download_to_file(f)

print(f"These files appear to be the same?: {filecmp.cmp(FILENAME, 'fromBlob.png')}")
'''

**Comment by crwilcox** [comment]
Closing as not reproducible. Feel free to re-open this if you have additional information.
Thanks!

**Comment by santhoshdc1590** [comment]
@crwilcox 
Thank You for the response.

I am processing the image and then am trying to store the `image` onto `google bucket`.

This was a silly error from my end.

> bucket = client.get_bucket('document') #points to the bucket

when a specify where and what name to store the `temp file` using the command below

> blob = bucket.blob('document/Test15.jpg') #points to the location inside the bucket

This is how, it's stored
`document/document/Test15.jpg`

This is how, I though the location would be
`/document/Test15.jpg`
