### ISSUE TITLE
Spanner: TypeError: '' has type str, but expected one of: bytes

### ISSUE THREAD

**Issue by yixizhang** [GoogleCloudPlatform/google-cloud-python#5164]
OS type and version: ubuntu xenial

Python version and virtual environment information `python --version`: python 3.6

google-cloud-python version: https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/spanner-1.3.0

Stacktrace if available:
```
  File "/tmp/par__22_www_server.par/__main__/third_party/google_cloud/current/xenial/google/cloud/spanner_v1/streamed.py", line 140, in __iter__
    self._consume_next()  # raises StopIteration
  File "/tmp/par__22_www_server.par/__main__/third_party/google_cloud/current/xenial/google/cloud/spanner_v1/streamed.py", line 114, in _consume_next
    response = six.next(self._response_iterator)
  File "/tmp/par__22_www_server.par/__main__/third_party/google_cloud/current/xenial/google/cloud/spanner_v1/snapshot.py", line 51, in _restart_on_unavailable
    iterator = restart(resume_token=resume_token)
  File "/tmp/par__22_www_server.par/__main__/third_party/google_cloud/current/xenial/google/cloud/spanner_v1/gapic/spanner_client.py", line 662, in execute_streaming_sql
    partition_token=partition_token,
TypeError: '' has type str, but expected one of: bytes
```

**Comment by chemelnucfin** [comment]
Are you iterating over your own data?
Could you convert `''` to `b''`?

**Comment by yixizhang** [comment]
which param for that method i should convert `''` to `b''`?

the only thing changed recently is the `partition_token`, whose type is `byte` but i don't use that one. https://github.com/GoogleCloudPlatform/google-cloud-python/blame/spanner-1.3.0/spanner/google/cloud/spanner_v1/gapic/spanner_client.py#L662

**Comment by jabubake** [comment]
@jsimonweb FYI

**Comment by tseaver** [comment]
@yixizhang We need enough information to be able to reproduce the issue.  Can you post a snippet / gist of your code, with any sensitive data redacted / replaced?

**Comment by danoscarmike** [comment]
@yixizhang can you confirm if you are still experiencing this issue? Thanks!

**Comment by yixizhang** [comment]
I can't reproduce it and I haven't experienced the same error ever since.  But by reading the code the other I think this line could be buggy.

https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/spanner/google/cloud/spanner_v1/snapshot.py#L39

That the default value should not be a str, but rather `b''`.  

Hope that helps.

**Comment by tseaver** [comment]
@yixizhang Thanks very much for the follow-up:  I can confirm that the initial `resume_token` should be bytes, rather than text.
