### ISSUE TITLE
Error Reporting: Docs for HTTPContext incorrect

### ISSUE THREAD

**Issue by foresmac** [GoogleCloudPlatform/google-cloud-python#5168]
The [documentation](https://googlecloudplatform.github.io/google-cloud-python/latest/error-reporting/usage.html) for `error_reporting.client.HTTPContext` gives the wrong parameter names.

```python
>>> from google.cloud import error_reporting
>>> client = error_reporting.Client()
>>> user = 'example@gmail.com'
>>> http_context = HTTPContext(method='GET', url='/', userAgent='test agent',
...                            referrer='example.com', responseStatusCode=500,
...                            remote_ip='1.2.3.4')
>>> try:
>>>     raise NameError
>>> except Exception:
>>>     client.report_exception(http_context=http_context, user=user))
```

Reading the code, it's clear that the camel-cased names are internally used to match expected JSON keys for the underlying API call, but the [actual parameter names are properly snake-cased](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/error_reporting/google/cloud/error_reporting/client.py#L64-L74). Oddly, the docs _do_ show the correct parameter name for `remote_ip`, but not `user_agent` or `response_status_code`.

I couldn't figure out which file to edit to fix, otherwise I would have just submitted a PR.

**Comment by foresmac** [comment]
Can do, thanks.

**Comment by tseaver** [comment]
@foresmac Thanks for the report!
