### ISSUE TITLE
Cloud Storage: Overflow error: Python int too large to convert to C long from blob.py

### ISSUE THREAD

**Issue by Osiris1975** [GoogleCloudPlatform/google-cloud-python#5172]
# Thank you for reporting an issue to google-cloud-python!

If you are reporting an issue or requesting a feature, please search the
existing open and closed issues to see if there is already work being done.

- https://github.com/GoogleCloudPlatform/google-cloud-python/issues
- http://stackoverflow.com/questions/tagged/google-cloud-python

If you can provide us with as much of the following information as possible it
will help us identify the cause of your issue more quickly.

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types

2. OS type and version 
Microsoft Windows [Version 6.1.7601]

3. Python version and virtual environment information `python --version`
2.7.13

4. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`

google-cloud-storage==1.8.0

5. Stacktrace if available
```
Traceback (most recent call last):
  File "C:/Dev/Python/widdler/widdler.py", line 605, in <module>
    sys.exit(main())
  File "C:/Dev/Python/widdler/widdler.py", line 593, in main
    result = args.func(args)
  File "C:/Dev/Python/widdler/widdler.py", line 408, in call_upload
    uploaded_files = b.upload_workflow_input_files(args.wdl, args.json)
  File "C:\Dev\Python\widdler\src\SingleBucket.py", line 189, in upload_workflow_input_files
    self.upload_files(files_to_upload)
  File "C:\Dev\Python\widdler\src\SingleBucket.py", line 107, in upload_files
    self.upload_file(f, f.replace('\\', '/'))
  File "C:\Dev\Python\widdler\src\SingleBucket.py", line 91, in upload_file
    blob.upload_from_filename(source_file_name)
  File "C:\Miniconda3\envs\Widdler\lib\site-packages\google\cloud\storage\blob.py", line 992, in upload_from_filename
    size=total_bytes)
  File "C:\Miniconda3\envs\Widdler\lib\site-packages\google\cloud\storage\blob.py", line 946, in upload_from_file
    client, file_obj, content_type, size, num_retries)
  File "C:\Miniconda3\envs\Widdler\lib\site-packages\google\cloud\storage\blob.py", line 867, in _do_upload
    client, stream, content_type, size, num_retries)
  File "C:\Miniconda3\envs\Widdler\lib\site-packages\google\cloud\storage\blob.py", line 676, in _do_multipart_upload
    data = stream.read(size)
OverflowError: Python int too large to convert to C long
```
Also, additional output from my debug console window:

```
Connected to pydev debugger (build 173.4674.37)
Error while evaluating expression: if (size == 3799968885)
Traceback (most recent call last):
  File "_pydevd_bundle\pydevd_cython_win32_27_64.pyx", line 172, in _pydevd_bundle.pydevd_cython_win32_27_64.handle_breakpoint_condition
  File "<string>", line 1
    if (size == 3799968885)
     ^
SyntaxError: invalid syntax
Error while evaluating expression: if (size == 3799968885)
Traceback (most recent call last):
  File "_pydevd_bundle\pydevd_cython_win32_27_64.pyx", line 172, in _pydevd_bundle.pydevd_cython_win32_27_64.handle_breakpoint_condition
  File "<string>", line 1
    if (size == 3799968885)
     ^
SyntaxError: invalid syntax
2018-04-09 14:49:38,200 - widdler.SingleBucket.SingleBucket - CRITICAL - Python int too large to convert to C long
```

6. Steps to reproduce

Use blob.upload_from_filename(source_file_name) to upload a file that's 3.8GB in size. Guessing anything
larger than 2.1 GB will do as this appears to be an issue of the file size being handled as an int when it should be handled as a long. 

7. Code example

This is my function:
```
    def upload_file(self, source_file_name, destination_blob_name):
        """
        Upload a file to a bucket. Once they are in the bucket, they are called blobs.
        :param source_file_name: Full path and name of source file.
        :param destination_blob_name: name to give file in bucket.
        :return:
        """
        blob = self.bucket.blob(destination_blob_name)

        try:
            blob.upload_from_filename(source_file_name)
        except Exception as e:
            print_log_exit(str(e))
```
It is part of a class I made for implementing various cloud storage functionality for a single bucket. When attempting to upload a large file (3.8GB in size), I get the overflow error in the stack trace above. While tracking it down in debugger, the error appears to be caused by line 676 of blob.py in the google cloud storage library:

`            data = stream.read(size)
`

**Comment by jonparrott** [comment]
@Osiris1975, hrm, I wonder if this happens in Python 3 as well?

**Comment by jonparrott** [comment]
@crwilcox want to take point on fixing this?

**Comment by Osiris1975** [comment]
@jonparrott and @crwilcox thanks for jumping on this so quickly. Hopefully a quick and easy fix. Once fixed will you be releasing a new version anytime soon?

**Comment by meirelesmj** [comment]
Hi Crwilcox

I installed the latest version of google cloud storage I think 1.10 and this error still to happen.

Is this already fixed in the code ?

Thanks

**Comment by tseaver** [comment]
@meirelesmj The fix from PR #5187 was released in `google-cloud-storage 1.9.0`.  If you can reproduce with version `1.10.0`, please follow up here with a recipe, and we will investigate / reopen.

**Comment by meirelesmj** [comment]
HI @tseaver 

Thanks for the help

There is a print of the error. Can I give you any additional information that could help ?

 
<img width="948" alt="capture" src="https://user-images.githubusercontent.com/33875177/43138520-0c0e82d4-8f47-11e8-92c8-90f1d56d855b.PNG">

**Comment by tseaver** [comment]
@meirelesmj What is the architecture of your Python?  E.g.:

```python
>>> import platform
>>> platform.architecture()
('64bit', 'ELF')
```

If the first item is `32bit`, we may not be able to do anything in `google-cloud-storage` to fix the issue.

**Comment by meirelesmj** [comment]
>>> import platform
>>> platform.architecture()
('64bit', 'WindowsPE')
>>>

Sorry for the delay. It's running locally for now in my machine, then probably will be running in Google Cloud infrastructure
