### ISSUE TITLE
Bigtable system tests fail creating tables with 503

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#5179]
CI failures for changes unrelated to Bigtable:

- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/6267
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/6268

**Comment by sduskis** [comment]
@zakons, FYI

**Comment by sduskis** [comment]
@tseaver, Do these tests go against the Cloud Bigtable service itself or against an emulator?

**Comment by jonparrott** [comment]
production

**Comment by sduskis** [comment]
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/6268 is a transient networking problem that occurred to mutate rows.  It does indeed need to be retried.

https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/6267 is a transient networking problem that occurred in a column admin api.  We can't retry those.

We should look into https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/6268.

**Comment by zakons** [comment]
I will take a close look at how our retry is handling (or not) the exception in 6268. Thanks.
    On Friday, April 27, 2018, 9:46:50 AM EDT, Solomon Duskis <notifications@github.com> wrote:  
 
 
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/6268 is a transient networking problem that occurred to mutate rows. It does indeed need to be retried.

https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/6267 is a transient networking problem that occurred in a column admin api. We can't retry those.

We should look into https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/6268.

**Comment by sduskis** [comment]
Is this still a problem?

**Comment by tseaver** [comment]
@sduskis FWIW, both of the failures in [CircleCI 6267](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/6267) are 503s during `CreateTable` requests (one is in the setup for a column family test).

#5421 modified the system tests to ensure that they didn't share a common table name, which seems to have made the 503s go away.y working theory is that the same-name table created and deleted in an earlier test sometimes "hangs around" (like a ghost -- due to eventual consisency?), triggering the 503 error (which should maybe have been a 409?).

All but one of the failures in [CircleCI 6268](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/6268) are likewise 503s during `CreateTable`.  The assertion error in the one is due to unexpected tables returned from `ListTables`: maybe related to the eventual consistency problem?

**Comment by tseaver** [comment]
I believe 76552b2e1900799d811cada0f05cf471a94c6c14 resolved the `CreateTable` issue by making each table-creating system test use a distinct table name.
