### ISSUE TITLE
BigQuery: to_dataframe not working

### ISSUE THREAD

**Issue by chengvt** [GoogleCloudPlatform/google-cloud-python#5192]
OS: Ubuntu 14.04.5
Python 3.5.2 :: Anaconda custom (64-bit)
google-api-core==0.1.4
google-auth==1.4.1
google-auth-httplib2==0.0.2
google-auth-oauthlib==0.1.0
google-cloud==0.32.0
google-cloud-bigquery==0.29.0
google-cloud-bigquery-datatransfer==0.1.1
google-cloud-bigtable==0.28.1
google-cloud-container==0.1.1
google-cloud-core==0.28.1
google-cloud-datastore==1.4.0
google-cloud-dns==0.28.0
google-cloud-error-reporting==0.28.0
google-cloud-firestore==0.28.0
google-cloud-happybase==0.22.0
google-cloud-language==1.0.1
google-cloud-logging==1.4.0
google-cloud-monitoring==0.28.1
google-cloud-resource-manager==0.28.1
google-cloud-runtimeconfig==0.28.1
google-cloud-storage==1.6.0

# Problem
After upgrading google-cloud yesterday, `to_dataframe` could no longer be found.

```python
client.query(query).result().to_dataframe()
```
Error message:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-11-5fdf6f279053> in <module>()
      1 client.query(query)
      2 client.query(query).result()
----> 3 client.query(query).result().to_dataframe()

AttributeError: 'HTTPIterator' object has no attribute 'to_dataframe'
```
It seems that the output of `result()` became `google.api_core.page_iterator.HTTPIterator` instead of `google.cloud.bigquery.table.RowIterator `
```python
client.query(query)
client.query(query).result()
```
output:
```
<google.cloud.bigquery.job.QueryJob at 0x7f51f9d0c470>
<google.api_core.page_iterator.HTTPIterator at 0x7f51f9d0c860>
```

I looked up past issue and found that [the issue has been fixed](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4677) in bigquery 0.29.0, which is the version I am currently using. Would appreciate any comments.

**Comment by tswast** [comment]
What version of `google-cloud-bigquery` are you using? Note that the version included in the `google-cloud` package is out-of-date.

**Comment by chengvt** [comment]
@tswast Thank you so much! Installing `google-cloud-bigquery==1.0.0` works. Will be careful when upgrading `google-cloud` bundle from now.
