### ISSUE TITLE
New subscribers don't see messages

### ISSUE THREAD

**Issue by james-woods** [GoogleCloudPlatform/google-cloud-python#5196]
2. OS type and version: GKE / COS
3. Python version and virtual environment information: 3.5 running on Kubernetes Engine
4. google-cloud-python version: google-cloud-pubsub==0.30.1
6. Steps to reproduce: When running workers in GKE to process items (cloud storage blob paths) from PubSub and scaling them (by scaling a Kubernetes Job), new workers don't pick any work. To have workers distribute the work among them they have to be present when the work gets produced. Later joining workers just sit and idle.
7. Code example

```python
def receive_messages():
    def callback(message):
        logging.info("Message {} acknowledged".format(message.data.decode()))
        # It's fine for me to ack fast, as the state of the import gets written 
        # into the metadata of the blob
        message.ack()
        do_hard_work(message.data.decode())
     
    flow_control = pubsub_v1.types.FlowControl(max_messages=2)
    executor = futures.ThreadPoolExecutor(max_workers=1)
    policy = pubsub_v1.subscriber.policy.thread.Policy(SUBSCRIBER, 
                                                       SUBSCRIPTION_PATH, 
                                                       executor=executor,
                                                       flow_control=flow_control)
    policy.open(callback)

    sleep_cycles = 0
    while True:
        time.sleep(60)
        sleep_cycles += 1
        logging.info("slept, cyles: {:d} ".format(sleep_cycles))

```

If I start 5 workers, then publish some GCS blob names onto the topic, the workers are happily doing their thing. If I then scale them to 10, the new 10 workers just sleep and seem to not be getting any message.

My use case is exactly the same one as described [here](https://www.bountysource.com/issues/55374604-flowcontrol-max_messages-is-not-working-as-expected) - an embarrassingly parallel task, download a GCS blob, convert it, upload it again and it ususally consumes the entire CPU of my worker machines. So I was hoping to get it working with these flow-control settings.
It seems like maybe pulling messages from workers would fix this, but the python library seems not to support this.

**Comment by james-woods** [comment]
Actually after waiting one hour the new workers pick up work, but it still feels weird that this takes so long. I think i might be better off using something like the ruby implementation that supports pulling (?)

**Comment by jonparrott** [comment]
@james-woods `0.30.1` has known issues. If you can reproduce with `0.33.1` let me know and we'll re-open.

**Comment by james-woods** [comment]
Tried with `0.33.1` - the issue is the same, one consumer is listening and getting messages, the other one joins and sits idle.

``` python
def receive_messages():
    def callback(message):
        logging.info("Message {} acknowledged".format(message.data.decode()))
        # set ack deadline to 600 seconds, so we are done before the deadline occurs
        do_hard_work(message.data.decode())
        message.ack()
     
    flow_control = pubsub_v1.types.FlowControl(max_messages=1)
    executor = futures.ThreadPoolExecutor(max_workers=1)
    policy = pubsub_v1.subscriber.policy.thread.Policy(SUBSCRIBER, 
                                                       SUBSCRIPTION_PATH, 
                                                       executor=executor,
                                                       flow_control=flow_control)
    policy.open(callback)
    future.result()
```

**Comment by kerighan** [comment]
Same problem for me. I can only get one worker to work with about the same code as yours.

**Comment by james-woods** [comment]
@theacodes how should I reopen?

**Comment by theacodes** [comment]
This is due to known, unchangeable behavior in the way gRPC handles message buffers. I'm working on providing documentation that describes exactly how this occurs and ways to mitigate it.
