### ISSUE TITLE
BigTable Float values incompatible with BigQuery?

### ISSUE THREAD

**Issue by achachet** [GoogleCloudPlatform/google-cloud-python#5200]
Hi, 

As recommended in issue [2614](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2614), I stored a timestamp in BigTable rows using the following python code: 

```python
row = table.row(some_key)
timestamp = 1523212084.35388
byte_data = struct.pack('>d', timestamp) 
row.set_cell(column_family.encode('utf-8'), # column_family
                    column_name.encode('utf-8'),  # column
                    byte_data                                    # value
                    )
row.commit()
```
It works fine and I am able to retrieve the value and unpack it. 

However, I use BigQuery to query the same table - and the values encoded this way completely prevent querying the table, although the column names in question are not even part of the table definition: 
```sql
SELECT * FROM `my_project.my_dataset.the_bigtable_table` LIMIT 1000
```

Error: Error while reading table: my_project.my_dataset.the_bigtable_table, error message: Invalid utf-8 encoding found At row:f68001aa9c573a1e920a4f908d27bb03392ea3cf, column_family:metadata, column:P1_end_walltime

The only workaround I could find is to scan all rows containing these columns, unpack them, convert them to string and re-encode them as utf-8. (Hope this will work)

Is that a bug or am I doing something wrong?

Thanks!

**Comment by tswast** [comment]
Per https://cloud.google.com/bigquery/external-data-bigtable#value_encoding BigQuery assumes two types, either text or [HBase Bytes.toBytes()](https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/util/Bytes.html). From the error, it seems BigQuery is trying to interpret this column as strings.

**Comment by achachet** [comment]
Very clear, I missed that, thanks!
