### ISSUE TITLE
'module' object has no attribute 'Client'

### ISSUE THREAD

**Issue by ragul-sky** [GoogleCloudPlatform/google-cloud-python#5205]
Have installed required python libraries:
1) pip install google-cloud
2) pip install --upgrade google-cloud-logging

Output of pip show google-cloud_:

Name: google-cloud                                                                                                                                           Version: 0.32.0                                                                                                                                              Summary: API Client library for Google Cloud                                                                                                                 Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python                                                                                        Author: Google Cloud Platform                                                                                                                                Author-email: googleapis-publisher@google.com                                                                                                                License: Apache 2.0                                                                                                                                          Location: c:\python27\lib\site-packages                                                                                                                      Requires: google-cloud-spanner, google-cloud-error-reporting, google-cloud-monitoring, google-cloud-storage, google-cloud-translate, google-cloud-container, google-cloud-logging, google-cloud-dns, google-cloud-videointelligence, google-cloud-firestore, google-cloud-bigtable, google-api-core, google-cloud-resource-manager, google-cloud-bigquery-datatransfer, google-cloud-speech, google-cloud-trace, google-cloud-core, google-cloud-vision, google-cloud-pubsub, google-cloud-bigquery, google-cloud-runtimeconfig, google-cloud-language, google-cloud-datastore

Output of pip show google-cloud-logging:

Name: google-cloud-logging
Version: 1.6.0
Summary: Stackdriver Logging API client library
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: c:\python27\lib\site-packages
Requires: google-api-core, google-cloud-core

Standard Code executed from Google  Stackdriver Logging Documentation:

from google.cloud import logging
logging_client = logging.Client()
log_name = 'my-log'
logger = logging_client.logger(log_name)
text = 'Hello, world!'
logger.log_text(text)
print('Logged: {}'.format(text))

Error - 'module' object has no attribute 'Client'

Please do help :)

**Comment by tseaver** [comment]
I can't reproduce this with up-to-date versions of `setuptools` / `pip` / `wheel` in a clean virtualenv:

```bash
$ /opt/Python-3.6.3/bin/python3 -m venv /tmp/gcp-5205
$ /tmp/gcp-5205/bin/pip install --upgrade setuptools pip wheel
Collecting setuptools
...
Successfully installed pip-10.0.0 setuptools-39.0.1 wheel-0.31.0
$ /tmp/gcp-5205/bin/pip install google-cloud
Looking in links: file:///home/tseaver/.pip/wheels
Collecting google-cloud
...
Successfully installed cachetools-2.0.1 certifi-2018.4.16 chardet-3.0.4 dill-0.2.7.1 future-0.16.0 gapic-google-cloud-datastore-v1-0.15.3 gapic-google-cloud-error-reporting-v1beta1-0.15.3 gapic-google-cloud-logging-v2-0.91.3 google-api-core-0.1.4 google-auth-1.4.1 google-cloud-0.32.0 google-cloud-bigquery-0.28.0 google-cloud-bigquery-datatransfer-0.1.1 google-cloud-bigtable-0.28.1 google-cloud-container-0.1.1 google-cloud-core-0.28.1 google-cloud-datastore-1.4.0 google-cloud-dns-0.28.0 google-cloud-error-reporting-0.28.0 google-cloud-firestore-0.28.0 google-cloud-language-1.0.1 google-cloud-logging-1.4.0 google-cloud-monitoring-0.28.1 google-cloud-pubsub-0.30.1 google-cloud-resource-manager-0.28.1 google-cloud-runtimeconfig-0.28.1 google-cloud-spanner-0.29.0 google-cloud-speech-0.30.0 google-cloud-storage-1.6.0 google-cloud-trace-0.17.0 google-cloud-translate-1.3.1 google-cloud-videointelligence-1.0.1 google-cloud-vision-0.29.0 google-gax-0.15.16 google-resumable-media-0.3.1 googleapis-common-protos-1.5.3 grpc-google-iam-v1-0.11.4 grpcio-1.11.0 httplib2-0.11.3 idna-2.6 oauth2client-3.0.0 ply-3.8 proto-google-cloud-datastore-v1-0.90.4 proto-google-cloud-error-reporting-v1beta1-0.15.3 proto-google-cloud-logging-v2-0.91.3 protobuf-3.5.2.post1 psutil-5.4.5 pyasn1-0.4.2 pyasn1-modules-0.2.1 pytz-2018.4 requests-2.18.4 rsa-3.4.2 six-1.11.0 urllib3-1.22
$ /tmp/gcp-5205/bin/pip install --upgrade google-cloud-logging
Looking in links: file:///home/tseaver/.pip/wheels
Collecting google-cloud-logging
...
google-cloud 0.32.0 has requirement google-api-core<0.2.0dev,>=0.1.2, but you'll have google-api-core 1.1.0 which is incompatible.
google-cloud 0.32.0 has requirement google-cloud-logging<1.5dev,>=1.4.0, but you'll have google-cloud-logging 1.6.0 which is incompatible.
google-cloud-vision 0.29.0 has requirement google-api-core<0.2.0dev,>=0.1.0, but you'll have google-api-core 1.1.0 which is incompatible.
google-cloud-trace 0.17.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.1.0 which is incompatible.
google-cloud-storage 1.6.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.1.0 which is incompatible.
google-cloud-speech 0.30.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.1.0 which is incompatible.
google-cloud-spanner 0.29.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.1.0 which is incompatible.
google-cloud-pubsub 0.30.1 has requirement google-api-core[grpc]<0.2.0dev,>=0.1.3, but you'll have google-api-core 1.1.0 which is incompatible.
google-cloud-firestore 0.28.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.1.0 which is incompatible.
google-cloud-error-reporting 0.28.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.1.0 which is incompatible.
google-cloud-error-reporting 0.28.0 has requirement google-cloud-logging<1.5dev,>=1.4.0, but you'll have google-cloud-logging 1.6.0 which is incompatible.
google-cloud-dns 0.28.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.1.0 which is incompatible.
google-cloud-datastore 1.4.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.1.0 which is incompatible.
google-cloud-bigtable 0.28.1 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.1.0 which is incompatible.
google-cloud-bigquery 0.28.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.1.0 which is incompatible.
Installing collected packages: google-api-core, google-cloud-logging
  Found existing installation: google-api-core 0.1.4
    Uninstalling google-api-core-0.1.4:
      Successfully uninstalled google-api-core-0.1.4
  Found existing installation: google-cloud-logging 1.4.0
    Uninstalling google-cloud-logging-1.4.0:
      Successfully uninstalled google-cloud-logging-1.4.0
Successfully installed google-api-core-1.1.0 google-cloud-logging-1.6.0
$ /tmp/gcp-5205/bin/python 
Python 3.6.3 (default, Oct  4 2017, 16:14:25) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import logging
>>> logging.Client
<class 'google.cloud.logging.client.Client'>
>>> 
```

First, note the warnings about incompatible versions for all the `google-cloud-*` packages *except* `google-cloud-logging`.  Those got installed because you installed the `google-cloud` umbrella package, but you almost certainly don't need all of them. I would avoid installing `google-cloud` at all -- it is an attractive nuisance at this point:  instead, just install the `google-cloud-*` subpackage(s) that you need.

Second, I would avoid installing into your "base" Python's `site-packages`, and instead use a virtualenv.

@jonparrott What if we just deprecate `google-cloud` and release a version with *no* pins at all (or even no dependencies?)

**Comment by jonparrott** [comment]
> What if we just deprecate google-cloud and release a version with no pins at all (or even no dependencies?)

Yep, that's the plan. I just have to write a formal doc before I do it.

**Comment by ragul-sky** [comment]
Just found out that this error happens when I have both gcloud and  google-cloud installed.
1) pip install gcloud
2) pip install google-cloud

**Comment by tseaver** [comment]
@ragul-sky Actually, you shouldn't need to install *either* of those two:  `gcloud` is a long-deprecated early version of `google-cloud`.  Just install `google-cloud-logging` (or any of the other API-specific packages you need).

**Comment by ragul-sky** [comment]
Thanks for the help :)

**Comment by Hillary-K** [comment]
@ragul-sky So it worked for you when you uninstalled either of them? And which one?
