### ISSUE TITLE
Narrow screen width rendering issue on github.io page

### ISSUE THREAD

**Issue by crwilcox** [GoogleCloudPlatform/google-cloud-python#5213]
At narrow screen widths https://googlecloudplatform.github.io/google-cloud-python/ is rendering poorly.
<img width="663" alt="screen shot 2018-04-19 at 3 49 58 pm" src="https://user-images.githubusercontent.com/638797/39022217-59f79246-43e9-11e8-9da1-9a159de9cbff.png">

**Comment by tseaver** [comment]
Via #5214.
