### ISSUE TITLE
ERROR: (gcloud.app.deploy) Error Response: [13] An internal error occurred during deployment. [Python-edition]

### ISSUE THREAD

**Issue by bcreane** [GoogleCloudPlatform/google-cloud-python#5218]
This seems to be the same issue as reported by GoogleCloudPlatform/getting-started-java#281 as well as GoogleCloudPlatform/nodejs-getting-started#153, however since I'm using python runtime I didn't want to piggyback on the Java and nodejs issues.

We see the internal error intermittently while our CI (Jenkins) attempts to publish the website deployment. 

We're running the latest Google cloud SDK:
```
 Google Cloud SDK 198.0.0
 bq 2.0.32
 core 2018.04.13
 docker-credential-gcr
 gsutil 4.3
```

Versions Info:
```
OS: Debian 9
Python: Python 2.7.13
```

In terms of reproducing the issue, we're currently just pushing a static website, so the deployment yaml is fairly straight forward.

**Comment by bcreane** [comment]
ah, just noticed the work-around posted in GoogleCloudPlatform/getting-started-java#281:
`gcloud config  set app/use_deprecated_preparation True`

We'll give this a try and re-open this issue if we continue to see app deployment failures.

**Comment by glinskyc** [comment]
For others that may stumble upon this, my issue was fixed by updating the Cloud SDK from v209 to v211.0.0.  See here for instructions:

https://cloud.google.com/sdk/docs/#install_the_latest_cloud_tools_version_cloudsdk_current_version

**Comment by FightWithCode** [comment]
gcloud config set app/use_deprecated_preparation True
This is not helping me
Gives this error
ERROR: (gcloud.config.set) Section [app] has no property [use_deprecated_preparation].

**Comment by ronlee123** [comment]
> gcloud config set app/use_deprecated_preparation True
> This is not helping me
> Gives this error
> ERROR: (gcloud.config.set) Section [app] has no property [use_deprecated_preparation].
> 
> EDIT:
> Looks like I solved the error. I was passing a wrong parameter in app.yaml

Would you mind further describing on how you solved that error? what was the wrong parameter in app.yaml that you passed? Really appreciate your help.

**Comment by PlatypusTechUK** [comment]
In our case the issue involved having the wrong default application set.  If you get this issue check "gcloud config get-value project" and make sure it is what you expect.

**Comment by as3eem** [comment]
For nodejs deployment, change app.yaml and make it just include 

`runtime: nodejs10`

and remove env: flex 
This will make your deployment move from a flexible plan to a standard plan but will do the work. The problem arises due to the unavailability of resources in several locations. They don't have enough VMs to provide stable flexible deployment.

**Comment by ahsetiaki** [comment]
@as3eem I want to say thank you to notice to remove the flex, I wont recognize that and I tried to fix other things in many several days
