### ISSUE TITLE
BigQuery: resource['configuration'] can raise KeyError in job_from_resource

### ISSUE THREAD

**Issue by hokumski** [GoogleCloudPlatform/google-cloud-python#5238]
Hello!

in /bigquery/google/cloud/bigquery/client.py, **job_from_resource**,

Recently I've got _resource_ dict without '_configuration_' key, it looked like some kind of dump (can show it, I have a copy).

So, it was permanent error on _list_jobs_, and I had nothing to do with it except to modify client.py:

```
config = resource.get('configuration', None)
if not config:
           return None
```

**Comment by tseaver** [comment]
@hokumski Thanks for the report!  It duplicates #5220, so I'm closing this one -- please follow there for resolution.
