### ISSUE TITLE
Bigtable: reports of transient failures in long running scans

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/google-cloud-python#5239]
Long running scans fail in a variety of ways due to transient networking issues.  These are completely recoverable.  While there are retries under the covers, they don't seem to be robust enough over long scans over time.  We need to add long running tests (multiple hours) of running these types of reads, and make sure that we catch all of the various conditions in which this can 

> File "/env/lib/python3.6/site-packages/google/cloud/bigtable/table.py", line 353, in yield_rows for row in generator.read_rows(): 
> File "/env/lib/python3.6/site-packages/google/cloud/bigtable/row_data.py", line 298, in read_rows response = six.next(self._response_iterator) 
> File "/env/lib/python3.6/site-packages/grpc/_channel.py", line 347, in __next__ return self._next() File "/env/lib/python3.6/site-packages/grpc/_channel.py", line 330, in _next raise self grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, OS

**Comment by tseaver** [comment]
I wonder if either of the two "flaky" Bigtable system test issues (#4935, #5179) are related.

**Comment by sduskis** [comment]
Reads rows now do automated retries.  I don't think that this is a problem anymore.  There's nothing actionable here, so I'll close this issue.  If something like this happens again, I'll open a new issue.
