### ISSUE TITLE
BigQuery: add ddl_operation_performed property to QueryJob stats

### ISSUE THREAD

**Issue by yiga2** [GoogleCloudPlatform/google-cloud-python#5241]
See https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#statistics.query.ddlOperationPerformed

Very useful to branch code (for us, in Airflow).

Btw, there is also an issue with the documentation - see discrepancy @ https://google-cloud-python.readthedocs.io/en/latest/bigquery/reference.html#google.cloud.bigquery.job.ExtractJob.destination_uri_file_counts

**Comment by tseaver** [comment]
@yiga2 Thanks for the report.  I'm not sure what the discrepancy is -- can you please elaborate?  Ideally we would have the feature request (adding support for the `ddlOperationPerformed` field) separate from the documentation bug report.

**Comment by shollyman** [comment]
Added in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/538

**Comment by shollyman** [comment]
5382 that is.
https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5382
