### ISSUE TITLE
BigQuery 1.2.0 release

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#5287]
The big new feature is https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5267 which adds support for column-based time partitioning.

**Comment by crwilcox** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5297

**Comment by tseaver** [comment]
The release deployment failed.

**Comment by tseaver** [comment]
@crwilcox The [tag exists](https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/bigquery-1.2.0), but there is no corresponding distribution on [the cheeseshop](https://pypi.org/project/google-cloud-bigquery/#history).  I'm guessing the "deploy" bit failed to to some other flaking test.

Do you want to push it manually?

**Comment by crwilcox** [comment]
I can do a manual push of this. that is likely what happened

**Comment by crwilcox** [comment]
I have pushed a manual release. Something very odd is going on here though. GitHub knows about this tag, but any attempt to fetch it fails. I was able to release using the SHA though. The new version is available on PyPI.
