### ISSUE TITLE
List links to other language doc pages in alphabetical order

### ISSUE THREAD

**Issue by danoscarmike** [GoogleCloudPlatform/google-cloud-python#5290]
Please update drop down menu of [Python docs page(s)](https://googlecloudplatform.github.io/google-cloud-python/)

### Expected Behavior

.NET, C++, Go, Java, Node.js , PHP, Python, Ruby

### Actual Behavior

C++, .NET, Go, Java, Node.js, PHP, Python, Ruby

**Comment by tseaver** [comment]
@crwilcox I'm not sure of the procedure for updating it, but the list in question is in `index.html` on the `gh-pages` branch.

**Comment by crwilcox** [comment]
I had matched CPP when I last did it. Looks like they made this change themselves a bit back. Going to match everyone else now :)

**Comment by crwilcox** [comment]
Fixed by cec07b9
