### ISSUE TITLE
[Monitoring] cannot be used with Python 3.7 (Pandas)

### ISSUE THREAD

**Issue by crwilcox** [GoogleCloudPlatform/google-cloud-python#5293]
Pandas/Cython doesn't currently support 3.7. Once it does we need to enable 3.7 testing on Monitoring. 

Collecting pandas>=0.17.1 (from google-cloud-monitoring==0.29.0)
  Using cached https://files.pythonhosted.org/packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz
  Could not find a version that satisfies the requirement Cython (from versions: )
No matching distribution found for Cython

**Comment by tseaver** [comment]
Pandas 0.23.3 [claims (working) support for Python 3.7](http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#v0-23-3-july-7-2018).

The release page also notes Pandas will be [dropping Python 2.7 support](http://pandas.pydata.org/pandas-docs/stable/install.html#install-dropping-27) for new feature releases as of 2019-01-01.
