### ISSUE TITLE
Logging: parse entries created by bigquery_resource

### ISSUE THREAD

**Issue by yiga2** [GoogleCloudPlatform/google-cloud-python#5313]
`client_logging.list_entries()` on **BigQuery** log entries renders a list of `ProtobufEntry` objects. 

Unfortunately there is no documentation on how to read ("unpack" ?) the `payload_pb` property, for instance to retrieve the `jobId`.

Request to extent the documentation beyond retrieving entries that were written to a logger, and include snippets on how-to parse `protoPayload` messages like those created by GCP services.

**Comment by tseaver** [comment]
@yiga2 We don't have any visibility here as to what kind of message has been passed by the originator as the `proto_payload` (gRPC) or `protoPayload` (HTTP):  handling them requires knowledge of the protobuf message schema.  Can you point to docs for the entries you are trying to parse?

**Comment by yiga2** [comment]
Understood. I have a hard time getting the `list_entries` as expected for the below - no issue using the API (explorer) but here how to reproduce.
To get the log entries from biquery (used https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/simple_app.py):
```
from google.cloud import bigquery
bq = bigquery.Client()
query_job = bq.query("""
        SELECT
          CONCAT(
            'https://stackoverflow.com/questions/',
            CAST(id as STRING)) as url,
          view_count
        FROM `bigquery-public-data.stackoverflow.posts_questions`
        WHERE tags like '%google-bigquery%'
        ORDER BY view_count DESC
        LIMIT 10""")
```
then here to retrieve the log entries (I am project owner)
```
from google.cloud import logging
log= logging.Client()
filter = """
resource.type="bigquery_resource" 
and protoPayload.serviceData.jobCompletedEvent.eventName="query_job_completed"
and timestamp >= "%s"
""" % query_job.started.isoformat() 
res = list(log.list_entries(filter_=filter))   
```
`res` should return the job_completed entry, with the `payload_pb`. Somehow I don't get anything even with playing with the filter.

**Comment by tseaver** [comment]
@yiga2 I've found the [docs for the `AuditLog` message type](https://cloud.google.com/logging/docs/audit/api/ref/rest/Shared.Types/AuditLog).

**Comment by tseaver** [comment]
@yiga2 If you know / expect that the log entry contains an `AuditLog` instance, you can unmarshall it using `ProtobufEntry.parse_message`, e.g.:

```python
from google..... import AuditLog  # I don't know the path of the proto-generated module

def unmarshall_audit_log(entry):
    if entry.payload_pb.Is(AuditLog.DESCRIPTOR):
        message = AuditLog()
        protobuf_entry.parse_message(message)
        return message
```

**Comment by yiga2** [comment]
Not sure why it gets closed as what seems to be missing is the module compiled from proto, as per https://stackoverflow.com/questions/50301632/using-python-to-query-gcp-stackdriver-logs

Instead of each of us compiling a python module for it, it would make sense to have a new google.cloud.audit package containing, at a minimum, the AuditLog module. After that, I agree @tseaver's code makes it straightforward to parse.

**Comment by snarfed** [comment]
as a fully fleshed out example, here's how i generated my own `request_log_pb2.py` file based on `request_log.proto`to parse `google.appengine.logging.v1.RequestLog` serialized protobufs: https://stackoverflow.com/a/59414384/186123. more background in #2572.

@yiga2 is right, though, Google should ideally maintain official versions of these Python protobuf bindings instead.
