### ISSUE TITLE
Please restore "google.cloud.monitoring.Client'

### ISSUE THREAD

**Issue by michaelsafyan** [GoogleCloudPlatform/google-cloud-python#5326]
I understand that this code was hand-generated. Rather than deleting this code, though, it would be ideal if its creation were simply automated. Breaking existing code that references this library is not ideal.

Code that previously used:
`from google.cloud import monitoring

client = monitoring.Client()
# ...
`

... shouldn't be broken when upgrading to newer versions. Ideally, the definition of "monitoring.Client" should simply be auto-generated so that it is not additional, manually-maintained code. But it should still be there as an interface to simplify the usage of the API.

**Comment by theacodes** [comment]
Hi @michaelsafyan, unfortunately, we can't commit to stable interfaces until v1.0.0

 The whole purpose of this change was to make it much easier for us to make the monitoring library v1.0.0. I understand this isn't ideal, but we have to make sure that the code we take to v1.0.0 is something we're ready to commit to.

I *highly* recommend that you pin your package versions, especially before v1.0.0.

**Comment by michaelsafyan** [comment]
We have pinned package versions, but we need new functionality added in later versions; it's a little unfortunate that the upgrade involves rewriting existing code so significantly; we are ending up creating our own "Client" class in our code that wraps this interface to make it less breaking. It would have been better to leave the "Client" as-is and to make the means of contribution to the hand-written code more scalable (e.g. us contributing the additional methods to the "Client" class to wrap the added functions).

**Comment by michaelsafyan** [comment]
I understand that <1.0 isn't stable, but it seems like this is putting implementation before interface and choosing a less ideal API to make it easier to implement, rather than picking the interface, first, and then figuring out how to manage implementation better. This new approach is significantly less usable.
