### ISSUE TITLE
Documentation not updated?

### ISSUE THREAD

**Issue by talonx** [GoogleCloudPlatform/google-cloud-python#5327]
Your documentation link points to https://google-cloud-python.readthedocs.io/en/latest/monitoring/index.html . The Stackdriver examples there do not work with 0.29.0. Specifically, I am looking for API documentation/examples for fetching time series data for Stackdriver agent metrics.

Elsewhere, I have run into cases where the documentation is marked as Alpha whereas the product is marked as beta.

I'm using google-cloud-monitoring 0.29.0

**Comment by tseaver** [comment]
@talonx Thanks for the report!  

For the record, `google.cloud.monitoring` *is* [still in alpha status](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/monitoring-0.29.0/monitoring/setup.py#L30) as of the 0.29.0 release.

**Comment by tseaver** [comment]
@crwilcox Can we call this good with the redirect to `https://googlecloudplatform.github.io/google-cloud-python/`?

**Comment by crwilcox** [comment]
@tseaver , these automagically redirect to github.io so this issue should be resolved

@talonx if you still have issues feel free to reopen.
