### ISSUE TITLE
Document _AsyncJob in BigQuery documentation

### ISSUE THREAD

**Issue by bencaine1** [GoogleCloudPlatform/google-cloud-python#5328]
_AsyncJob contains several important properties, e.g. the errors property, but it does not show up in the python documentation at https://google-cloud-python.readthedocs.io/en/latest/bigquery/reference.html and is only visible if you look at the source code. It would be great if it were visible on the documentation page!

**Comment by tswast** [comment]
+1 to showing inherited members and not documenting a private base class.

**Comment by tswast** [comment]
Closed by https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5340 which does include inherited members in the class documentation.
