### ISSUE TITLE
General -  google-api-core dependency is out of date.

### ISSUE THREAD

**Issue by eavaria** [GoogleCloudPlatform/google-cloud-python#5329]
If you are reporting an issue or requesting a feature, please search the
existing open and closed issues to see if there is already work being done.

OS: `Linux localhost 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Python: `Python 3.6.3`

```
Name: google-cloud
Version: 0.32.0
```

When using `pipenv` to manage dependencies, the following `Pipfile`:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
google-cloud= "~=0.32.0"
google-cloud-bigquery = "~=0.30"

[requires]
python_version = "3.6.3"
```

It gives the following output:

```
$ pipenv install
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches google-api-core<0.2.0dev,<2.0.0dev,>=0.1.2,>=1.0.0
Tried: 0.1.0, 0.1.0, 0.1.1, 0.1.1, 0.1.2, 0.1.2, 0.1.3, 0.1.3, 0.1.4, 0.1.4, 1.0.0, 1.0.0, 1.1.0, 1.1.0, 1.1.1, 1.1.1, 1.1.2, 1.1.2
There are incompatible versions in the resolved dependencies.
```

This is the outdated line IMO:
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/1b76727be16bc4335276f793340bb72d32be7166/setup.py#L52

that is in conflict with:
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/1b76727be16bc4335276f793340bb72d32be7166/bigquery/setup.py#L33

Is this somehow expected? Should I test the `api-core=1.0.0` on General and open a PR?

**Comment by crwilcox** [comment]
Hi @eavaria, Thanks for the feedback. We are in the process of deprecating the `google-cloud` package as we think it is better to install the specific library you wish to use. For your case I believe that is `google-cloud-bigquery`.
