### ISSUE TITLE
paginate through queries

### ISSUE THREAD

**Issue by khieu** [GoogleCloudPlatform/google-cloud-python#5335]
I want to run a paginate query through bigquery client. However, it doesn't seem to be possible as `QueryJob` results function does not take `max_results` or ` page_token` to pass down to `list_rows` call. I want to ask if there's a way to run a paginate query with this BigQuery Client ?

Thank you.

**Comment by tswast** [comment]
The BigQuery client library automatically paginates through all pages automatically. You do not need to supply a `page_token` parameter.

**Comment by tswast** [comment]
P.S. It's a generator, so you can loop through the rows without creating a complete list if you are concerned about them fitting in memory.
