### ISSUE TITLE
pubsub ImportError on MLEngine

### ISSUE THREAD

**Issue by Nycroth** [GoogleCloudPlatform/google-cloud-python#5341]
When using the Python google-cloud-pubsub library within the Google Cloud ML Engine v1.7 runtime utilizing Python 3.5, attempting to import the library results in a module not found error. This ticket follows up on an issue opened with Google Cloud Support (Case#15774813) which has been passed along to the ML Engine team as far as I was told.

Notably, not all versions of the library are affected. Known broken versions include 0.32.1, 0.33.1, and 0.34.0. However, version 0.33.0 is known not to be broken. Additionally, it only appears to be this library affected as other third party libraries have no issue. Finally, this issue is not reproducible locally. Using Python version 3.5 in my local environment the below sample works without incident.

Traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.local/lib/python3.5/site-packages/trainer/task.py", line 1, in <module>
    import google.cloud.pubsub
ImportError: No module named 'google.cloud.pubsub'
```

To demo the problem, the following code can be used. To use, run the Makefile using `make LOCATION=gs://...` configuring the LOCATION variable to a Google Cloud Storage location you wish to upload the package to. You can also use `make clean LOCATION=gs://...` to remove the packaging artifacts and the file from the LOCATION you specify.

./Makefile
```make
.POSIX:
.PHONY: run clean

LOCATION = gs://YOUR_BUCKET_HERE/demo.tar.gz

run: TRAINING_ARGS  = demo_$(shell date +%Y_%m_%d__%H_%M_%S)
run: TRAINING_ARGS += --module-name trainer.task
run: TRAINING_ARGS += --package-path trainer
run: TRAINING_ARGS += --packages $(LOCATION)
run: TRAINING_ARGS += --staging-bucket $(shell dirname $(LOCATION))
run: TRAINING_ARGS += --region us-east1
run: TRAINING_ARGS += --config config.yaml
run: TRAINING_ARGS += --runtime-version 1.7
run: ./dist/demo-0.tar.gz
	gsutil cp ./dist/demo-0.tar.gz $(LOCATION)
	gcloud ml-engine jobs submit training $(TRAINING_ARGS)

clean:
	rm -rf dist/ *.egg-info
	-gsutil rm $(LOCATION) 2>/dev/null
	-gsutil rm -r $(shell dirname $(LOCATION))/demo_\* 2>/dev/null

./dist/demo-0.tar.gz: trainer/* setup.py
	python setup.py sdist
```

./config.yaml
```yaml
trainingInput:
  pythonVersion: "3.5"
```

./setup.py
```python
from setuptools import find_packages
from setuptools import setup

setup(
    name='demo',
    version='0',
    # Known broken versions: 0.34.0, 0.33.1, 0.32.1
    # Known working versions: 0.33.0
    install_requires=['google-cloud-pubsub==0.34.0'],
    packages=find_packages(),
    include_package_data=True,
    description='Demo showing broken import.',
)
```

./trainer/

./trainer/__init.py
```
```

./trainer/task.py
```python
import google.cloud.pubsub

print("Hello World")
```

**Comment by tseaver** [comment]
I'm afraid I don't know enough about MLEngine to diagnose this one.  @theacodes can you loop the appropriate person in?

**Comment by theacodes** [comment]
@puneith can you help us out?

**Comment by puneith** [comment]
@tseaver How are you installing the google-cloud-pubsub library on Cloud ML Engine?

**Comment by tseaver** [comment]
@puneith I'm not:  @Nycroth is the OP.

**Comment by Nycroth** [comment]
It gets installed via package dependency. The above code will be packaged into a python sdist when uploaded to the CloudML training server. Once there, it gets installed with pip where the `install_requires` directive in setup will trigger pip to fetch the dependency.

**Comment by Nycroth** [comment]
Quick update, the case was marked closed as apparently the issue vanishes if run within the 1.8 runtime environment. I haven't yet fully tested this, but I'm willing to believe it for now. It's not really an answer, but it is a solution if it works.

**Comment by theacodes** [comment]
@Nycroth should we close this? As far as I can tell, this is an issue with ML Engine so whatever bug is tracking this there should be the one to watch.

**Comment by Nycroth** [comment]
Probably. Best of luck to you all!
