### ISSUE TITLE
Redis Client Reference Docs 404

### ISSUE THREAD

**Issue by danoscarmike** [GoogleCloudPlatform/google-cloud-python#5357]
Link from [Redis README](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/redis/README.rst) to API client reference documentation (https://googlecloudplatform.github.io/google-cloud-python/stable/redis/usage.html) does not resolve (404).

**Comment by tseaver** [comment]
Looks to me as though the CI docs build / publish isn't working (we have other docs bugs open which are likely symptoms of the same problem).

**Comment by theacodes** [comment]
https://github.com/rtfd/readthedocs.org/issues/4127

**Comment by theacodes** [comment]
Redis docs *do* need to be symlinked into the top-level /docs directory.

**Comment by crwilcox** [comment]
It seems maybe our template for the README needs to be updated to use ReadTheDocs links. That said,
http://google-cloud-python.readthedocs.io/en/latest/ should have it but redis isn't there either.

**Comment by danoscarmike** [comment]
Next steps here? We're blocked on inserting links from cloud.google.com.  

@crwilcox #5358 links out to PyPI (I just followed suit, but I agree it would be more meaningful to link to reference docs or both).
