### ISSUE TITLE
Provide wheels for googleapis-common-protos==1.5.3, google-apitools==0.5.21

### ISSUE THREAD

**Issue by melissachang** [GoogleCloudPlatform/google-cloud-python#5393]
While attempting to deploy this [AWS Lambda](https://github.com/HumanCellAtlas/data-store/tree/master/daemons/dss-sync), I get:
```
(data-store) ~/data-store/daemons/dss-sync (master): domovoi deploy 
Creating deployment package.

Could not install dependencies:
future==0.16.0
cloud-blobstore==2.1.1
wrapt==1.10.11
jsonpickle==0.9.6
MarkupSafe==1.0
googleapis-common-protos==1.5.3
httplib2==0.11.0
itsdangerous==0.24
google-apitools==0.5.21
pycparser==2.18
inflection==0.3.1
PyYAML==3.12
You will have to build these yourself and vendor them in
the chalice vendor folder.

Your deployment will continue but may not work correctly
if missing dependencies are not present. For more information:
http://chalice.readthedocs.io/en/latest/topics/packaging.html
```

http://chalice.readthedocs.io/en/latest/topics/packaging.html says: "Specifically all pure python packages as well as all packages that upload wheel files for the manylinux1_x86_64 platform will be automatically installable."

So it appears that googleapis-common-protos==1.5.3, google-apitools==0.5.21 don't have manylinux1_x86_64 wheels.

Please provide these wheels -- it will make deploying AWS Lambda easier for any deployment that uses them.

**Comment by tseaver** [comment]
@melissachang Unfortunately, those projects aren't managed here.  Please create issues in their respective trackers:

- https://github.com/googleapis/googleapis
- https://github.com/google/apitools

Note that both `googleapis-common-protos` and `google-apitools` **are** both pure-Python distributions AFAICT.

**Comment by theacodes** [comment]
/cc @lukesneeringer for the googleapis-common-protos

Also keep in mind apitools is *not* supported at all.
