### ISSUE TITLE
Refresh error on client.recognize(config, audio)

### ISSUE THREAD

**Issue by ishmeetkaur7** [GoogleCloudPlatform/google-cloud-python#5419]
I was running google speech recognition api and was trying out the code in the quickstart : https://cloud.google.com/speech-to-text/docs/quickstart-client-libraries#client-libraries-install-python

But I get this error. Any idea what went wrong?

```python
RefreshError: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000006967F28>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
ERROR:root:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x0000000006548128>" raised exception!
Traceback (most recent call last):
  File "C:\Users\320022735\Desktop\ishi\lib\site-packages\grpc\_plugin_wrapping.py", line 77, in __call__
    callback_state, callback))
  File "C:\Users\320022735\Desktop\ishi\lib\site-packages\google\auth\transport\grpc.py", line 77, in __call__
    callback(self._get_authorization_headers(context), None)
  File "C:\Users\320022735\Desktop\ishi\lib\site-packages\google\auth\transport\grpc.py", line 65, in _get_authorization_headers
    headers)
  File "C:\Users\320022735\Desktop\ishi\lib\site-packages\google\auth\credentials.py", line 122, in before_request
    self.refresh(request)
  File "C:\Users\320022735\Desktop\ishi\lib\site-packages\google\auth\compute_engine\credentials.py", line 96, in refresh
    six.raise_from(new_exc, caught_exc)
  File "C:\Users\320022735\Desktop\ishi\lib\site-packages\six.py", line 737, in raise_from
    raise value
```

**Comment by tseaver** [comment]
This bit seems to indicate a DNS problem:

```
NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000006967F28>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)
```

Can you ping `speech.googleapis.com` from the same box?

**Comment by ishmeetkaur7** [comment]
ping is working fine

Pinging googleapis.l.google.com [216.58.220.42] with 32 bytes of data:
Reply from 216.58.220.42: bytes=32 time=16ms TTL=54
Reply from 216.58.220.42: bytes=32 time=17ms TTL=54
Reply from 216.58.220.42: bytes=32 time=18ms TTL=54
Reply from 216.58.220.42: bytes=32 time=17ms TTL=54

Ping statistics for 216.58.220.42:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 16ms, Maximum = 18ms, Average = 17ms

**Comment by ishmeetkaur7** [comment]
Well, I figured it out. In the google auth, _default.py, it wasn't able to load my json file so i simply put the file there explicitly and it is working fine now :)

**Comment by tseaver** [comment]
Great!  I'm glad it is working for you.
