### ISSUE TITLE
pubsub: publishing message attributes as dictionary fails

### ISSUE THREAD

**Issue by labsnuratech** [GoogleCloudPlatform/google-cloud-python#5437]
it shows publish() take 3 args but 4 were given

**Comment by tseaver** [comment]
@labsnuratech Thanks for the report. Can you please provide the full traceback, plus a snippet of the code where you are calling `PublisherClient.publish`?

**Comment by tseaver** [comment]
Also, what version of `google-cloud-pubsub` are you using?

**Comment by tseaver** [comment]
FWIW, this example from the docs is part of a tested snippet:

```python
>>> from google.cloud import pubsub
>>> import os
>>> publisher = pubsub.PublisherClient()
>>> topic = 'projects/{project_id}/topics/{topic}'.format(
...     project_id=os.getenv('GOOGLE_CLOUD_PROJECT'),
...     topic='MY_TOPIC_NAME',  # Set this to something appropriate.
... )
>>> publisher.create_topic(topic)  # raises conflict if topic exists
>>> publisher.publish(topic, b'My first message!', spam='eggs')
```

Note that the message payload (the bytes literal) is passed as a positional argument, but the message attribute (`spam`) is passed as a keyword argument.  If you have an existing dictionary of message attributes, you can pass it through via Python's `**` syntax, e.g.

```python
>>> publisher.publish(topic, b'My first message!', **message_attributes)
```

**Comment by tseaver** [comment]
Please reopen if you can provide more information to help us reproduce the problem:  the code snippet you are using, stacktrace, etc.
