### ISSUE TITLE
BigQuery build is failing on Windows (AppVeyor)

### ISSUE THREAD

**Issue by theacodes** [GoogleCloudPlatform/google-cloud-python#5441]
https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-python/build/1.0.3624.release-pubsub-0.35.3/job/1i4oi71l3pito40y

**Comment by tswast** [comment]
Looks like PyArrow doesn't build Wheels for Windows Python 2.7. 

> Note: Windows packages are only available for Python 3.5 and higher (this is also true for TensorFlow and any package that is implemented with modern C++).

https://arrow.apache.org/docs/python/install.html#pip

**Comment by tswast** [comment]
Maybe we should exclude pyarrow from all Python 2.7 builds? I don't know how easy it would be to exclude just Windows 2.7.

**Comment by tswast** [comment]
BigQuery tests are now passing: https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-python/build/job/3di3ow4b1xo9te19
