### ISSUE TITLE
language: DefaultCredentialsError: Could not automatically determine credentials

### ISSUE THREAD

**Issue by dapsjj** [GoogleCloudPlatform/google-cloud-python#5449]
I use Google cloud's Natural Language API from this [link](https://cloud.google.com/natural-language/docs/reference/libraries#client-libraries-usage-python):
And I use this command in powershell :

```
 $env:GOOGLE_APPLICATION_CREDENTIALS="D:\analyze_sentiment\MyFirstProject-bbe4f7bccb98.json"
```

Then I use this command in cmd:

```
set GOOGLE_APPLICATION_CREDENTIALS=D:\analyze_sentiment\MyFirstProject-bbe4f7bccb98.json
```

But when I use python code:

```python
from google.cloud import language
from google.cloud.language import enums
from google.cloud.language import types

# Instantiates a client
client = language.LanguageServiceClient()
# The text to analyze
text = u'Hello, world!'
document = types.Document(
    content=text,
    type=enums.Document.Type.PLAIN_TEXT)
# Detects the sentiment of the text
sentiment = client.analyze_sentiment(document=document).document_sentiment
print('Text: {}'.format(text))
print('Sentiment: {}, {}'.format(sentiment.score, sentiment.magnitude))
```

The error message said:

```python
raise exceptions.DefaultCredentialsError(_HELP_MESSAGE) google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://developers.google.com/accounts/docs/application-default-credentials.
```

**Comment by tseaver** [comment]
@dapsjj Thanks for the report.  In order to help us diagnose, can you please provide:

- the full tracebak
- the output of `pip --freeze`

Also, at the top of your script, can you add the following lines, and include the output:

```python
import os

print('Credendtials from environ: {}'.format(
    os.environ.get('GOOGLE_APPLICATION_CREDENTIALS'))
```

**Comment by dapsjj** [comment]
@tseaver  I modify my code as you said.
Now my code:
```
from google.cloud import language
from google.cloud.language import enums
from google.cloud.language import types
import os

print('Credendtials from environ: {}'.format(os.environ.get('GOOGLE_APPLICATION_CREDENTIALS')))
# Instantiates a client
client = language.LanguageServiceClient()
# The text to analyze
text = u'Hello, world!'
document = types.Document(
    content=text,
    type=enums.Document.Type.PLAIN_TEXT)
# Detects the sentiment of the text
sentiment = client.analyze_sentiment(document=document).document_sentiment
print('Text: {}'.format(text))
print('Sentiment: {}, {}'.format(sentiment.score, sentiment.magnitude))
```

The output of the console is like this：

> Credendtials from environ: None
> Traceback (most recent call last):
>   File "E:/test_opencv/test_120.py", line 8, in <module>
>     client = language.LanguageServiceClient()
>   File "E:\Anaconda3\lib\site-packages\google\cloud\language_v1\gapic\language_service_client.py", line 92, in __init__
>     scopes=self._DEFAULT_SCOPES)
>   File "E:\Anaconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 132, in create_channel
>     credentials, _ = google.auth.default(scopes=scopes)
>   File "E:\Anaconda3\lib\site-packages\google\auth\_default.py", line 306, in default
>     raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
> google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://developers.google.com/accounts/docs/application-default-credentials.

**Comment by tseaver** [comment]
This is the clue:

> Credendtials from environ: None

Your script is not running in a context where it has the `GOOGLE_APPLICATION_CREDENTIALS` environment variable set.

**Comment by vroon5** [comment]
@tseaver, on a similar note. I have carried out the same process. My credentials are verified, however, it is not able to locate the service account file

# Imports the Google Cloud client library
from google.cloud import language
from google.cloud.language import enums
from google.cloud.language import types

import os

print('Credendtials from environ: {}'.format(os.environ.get('GOOGLE_APPLICATION_CREDENTIALS')))

# Instantiates a client
client = language.LanguageServiceClient()

# The text to analyze
text = u'Hello, world!'
document = types.Document(
    content=text,
    type=enums.Document.Type.PLAIN_TEXT)

# Detects the sentiment of the text
sentiment = client.analyze_sentiment(document=document).document_sentiment

print('Text: {}'.format(text))
print('Sentiment: {}, {}'.format(sentiment.score, sentiment.magnitude))

print O/P: Credendtials from environ: "C:\Users\varun.mohankumar\amazon-san-review-c82780df4538.json"
Error:
~\AppData\Local\Continuum\anaconda3\lib\site-packages\google\auth\_default.py in _get_explicit_environ_credentials()
    163     if explicit_file is not None:
    164         credentials, project_id = _load_credentials_from_file(
--> 165             os.environ[environment_vars.CREDENTIALS])
    166 
    167         return credentials, project_id

~\AppData\Local\Continuum\anaconda3\lib\site-packages\google\auth\_default.py in _load_credentials_from_file(filename)
     87     if not os.path.exists(filename):
     88         raise exceptions.DefaultCredentialsError(
---> 89             'File {} was not found.'.format(filename))
     90 
     91     with io.open(filename, 'r') as file_obj:

DefaultCredentialsError: File "C:\Users\varun.mohankumar\amazon-san-review-c82780df4538.json" was not found

However, this is where my file is located in my local machine. 

Any help on this is appreciated!

**Comment by tseaver** [comment]
@vroon5 The exception is being raised because the file does not exist:  can you check for a typo in the path?

**Comment by vroon5** [comment]
Thank you for the quick reply @tseaver, that was the first thing I checked. I don't see any typo. 
![capture](https://user-images.githubusercontent.com/40067637/41170118-0b73e910-6b19-11e8-9611-d59519707631.JPG)

**Comment by tseaver** [comment]
@vroon5 Can you try running a Python script which tests each part of the path? There might be escaped characters embedded, somehow.

**Comment by vroon5** [comment]
Hi @tseaver, I tried placing the file in every subpath and running the code again. It is still not working.

 However, I am curious about the step we need perform prior to running this code. While setting up the environment variable for google application credentials, the command prompt does not give any feedback after I set the environment variable, it just moves to the next line. Would that be an issue?

![image](https://user-images.githubusercontent.com/40067637/41173967-b7d98bbc-6b26-11e8-8a61-adbe72e9a643.png)

**Comment by vroon5** [comment]
![image](https://user-images.githubusercontent.com/40067637/41179179-c924e216-6b37-11e8-9467-fbe77abaacc8.png)
 I cannot completely interpret the output of set, but I assume this is your question. It identifies that google application credentials above path.

**Comment by vroon5** [comment]
I did not run the script from the console, but I ran it in jupyter notebook. The error is same as what I posted first.  I try to run from the console and let you know, Thank you once again for your patience @tseaver

**Comment by vroon5** [comment]
Hi @tseaver here is what I tried from the console. The error stays the same! 
![image](https://user-images.githubusercontent.com/40067637/41181230-0ca4359e-6b3f-11e8-951c-61b48ade3722.png)

**Comment by dapsjj** [comment]
I know the error reason,I must use cmd mode to run the code,please do not run the code with pycharm or other IDE.And set this [link ](https://cloud.google.com/natural-language/docs/reference/libraries#client-libraries-usage-python)API "enable".

And then the error disappeared.

**Comment by vroon5** [comment]
The following solution worked. 
: explicitly mentioning the location of the private key
https://google-auth.readthedocs.io/en/latest/user-guide.html#service-account-private-key-files
![image](https://user-images.githubusercontent.com/40067637/41249484-480dbc5a-6d82-11e8-8d40-8889be2b8ccd.png)

**Comment by gsusI** [comment]
> The following solution worked.
> : explicitly mentioning the location of the private key
> https://google-auth.readthedocs.io/en/latest/user-guide.html#service-account-private-key-files
> ![image](https://user-images.githubusercontent.com/40067637/41249484-480dbc5a-6d82-11e8-8d40-8889be2b8ccd.png)

Just sharing it in plain text so it can be easily copied 😄 

`    from google.cloud import language
    from google.cloud.language import enums
    from google.cloud.language import types
    from google.oauth2 import service_account
    import os

    # In this case I'm using a relative path from the the same path where this script is located.
    credentials_path = os.path.dirname(os.path.realpath(__file__)) + os.sep + '[RELATIVE_PATH_TO_JSON_KEY]'


    credentials = service_account.Credentials.from_service_account_file(credentials_path)
    client = language.LanguageServiceClient(credentials=credentials)
`

**Comment by sylwester-prymula** [comment]
> ![image](https://user-images.githubusercontent.com/40067637/41179179-c924e216-6b37-11e8-9467-fbe77abaacc8.png)
> I cannot completely interpret the output of set, but I assume this is your question. It identifies that google application credentials above path.

set path without quotation marks!
`set GOOGLE_APPLICATION_CREDENTIALS=[PATH]`

wrong:
[set GOOGLE_APPLICATION_CREDENTIALS="[PATH]"](url)

**Comment by fbaeumer** [comment]
This one solved it for me on all platforms:

import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "FULLPATH TO JSON"

**Comment by Anagha696** [comment]
> import os
> os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "FULLPATH TO JSON"
@fbaeumer Thankyou .It worked for me

**Comment by vishu002** [comment]
![IMG_20200606_195715](https://user-images.githubusercontent.com/52373276/84416235-8f8d5280-ac31-11ea-9f23-cbe28b4fad99.jpg)
How to solve

**Comment by sergio2526** [comment]
@vishu002 la opción que comenta @fbaeumer a mi me funciono, no me sirvió crear la variable del entorno decargue mi archivo Json como mencionan en la documentación de google  https://cloud.google.com/docs/authentication/getting-started#linux-or-macos y luego agregue en mi archivo:

import os
os.environ ["GOOGLE_APPLICATION_CREDENTIALS"] = "FULLPATH TO JSON"

Todo funciono correcto

**Comment by vishu002** [comment]
My issues already solved

**Comment by sayedfarhanali** [comment]
export GOOGLE_APPLICATION_CREDENTIALS='PATH'

worked for me in Linux.

**Comment by tseaver** [comment]
Please note that the `google-cloud-language` Python client library is no longer maintained in this repository.  Future issues should be reported to the [`python-language` tracker](https://github.com/googleapis/python-language/issues).
