### ISSUE TITLE
TypeError: query() got an unexpected keyword argument 'location'

### ISSUE THREAD

**Issue by VamsidharMuggulla** [GoogleCloudPlatform/google-cloud-python#5462]
Following this documentation to query from a table
**method 1:**
https://google-cloud-python.readthedocs.io/en/latest/bigquery/usage.html#querying-data
**method 2:**
https://google-cloud-python.readthedocs.io/en/latest/bigquery/usage.html#run-a-dry-run-query

either methods throwing the same exception
**TypeError: query() got an unexpected keyword argument 'location'**

without using "location" argument raises the following exception
**NotFound: 404 Not found: Table project-id:data-set.table-name. Please verify that the table exists and the correct location was used for the job.**

**sample code for method 2**
```
from google.cloud import bigquery
client = bigquery.Client(project='xxxxxxxx')
query=('SELECT text, ARRAY(SELECT as struct sentence,sentiment FROM UNNEST(sentences)) AS sentence,sentiment FROM `sa.document` LIMIT 5;')
job_config = bigquery.QueryJobConfig()
job_config.dry_run = True
job_config.use_query_cache = False
query_job = client.query((query),job_config=job_config)
assert query_job.state == 'DONE'
assert query_job.dry_run
print("This query will process {} bytes.".format(query_job.total_bytes_processed))
```

**Comment by tseaver** [comment]
@VamsidharMuggulla What version of `google-cloud-bigquery` are you using?  The `location` parameter was added to `Client.query` in PR #5071, which was part of the `0.32.0` release.

**Comment by VamsidharMuggulla** [comment]
google-cloud-bigquery-1.3.0
by the way, I'm unable to use(couldn't event import) this library in my flask application(running on dev_server) it is throwing an exception. 
**ImportError: No module named google.cloud.bigquery**

whenever I try to this

`from google.cloud import bigquery`

I tried a lot. The library was there where it is needed everything is fine still I couldn't find any solution for that. I'm using googleapiclient for now it is working fine but and not very useful though.

**Comment by tseaver** [comment]
You likely have a broken installation (maybe out-of-date setuptools / pip?).  Try in a fresh virtual environment, e.g.:

```bash
$ python3.6 -m venv /tmp/gcp-5462
$ /tmp/gcp-5462/bin/pip install --upgrade setuptools pip wheel
$ /tmp/gcp-5462/bin/pip install google-cloud-bigquery
$ /tmp/gcp-5462/bin/python -c "import google.cloud.bigquery"
```

Please reopen if you can provide us more information to help reproduce the problem.
