### ISSUE TITLE
Consider use of __slots__ when API is nearing 1.0

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#549]

**Comment by jgeewax** [comment]
@dhermes Are we thinking about this for Datastore? or all of the libraries?

**Comment by dhermes** [comment]
All libraries. Datastore seems more likely to be in a system which will need to be performant, so it's a stronger candidate for "better" gc.

**Comment by lukesneeringer** [comment]
I like the idea of doing this next week as a final step before 1.0.

**Comment by lukesneeringer** [comment]
I have no issue with doing this in the future but do not see the need to hold open an issue for it. Closing.
