### ISSUE TITLE
Allow specifying LogEntry optional parameters in google.cloud.logging.logger

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/google-cloud-python#5505]
Currently, [google.cloud.logging.logger.Logger](https://google-cloud-python.readthedocs.io/en/latest/logging/logger.html)  allows you to submit a log entry with predefined parameter sets:

for example, ```logger.log_text()``` allows you to set
```
log_text(text, labels=None, 
  insert_id=None, 
  severity=None, 
  http_request=None, 
  timestamp=None, 
  resource=Resource(type='global', labels={})
)
```
But  [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) allows you to specify additional settings like ```trace```, ```spanid```, etc.

eg, in the logEntry proto, we've got the traceID already there
- [LogEntry Proto](
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging_v2/proto/log_entry_pb2.py#L165)

FR allow users to specify these settings to match whats in ```LogEntry```

**Comment by salrashid123** [comment]
The ability to inject the ```trace``` parameter into a ```log_entry``` is pretty useful in setting up consolidated logs and grouping in for ```httpRequests```

as an example, here is  sample where you can add on log groups in Flask using a hacked local version overriding ```log_text()``` method to add ```trace=```

```
parent_logger.log_text(TEXT, 
  client=client, 
  labels=LABELS, 
  severity=SEVERITY, 
  http_request=REQUEST, 
  trace=TRACE)
```

(diff file for local overrides included):
-[https://gist.github.com/salrashid123/fca2c58cc8734ab4bd1ecdc24c49a72b](https://gist.github.com/salrashid123/fca2c58cc8734ab4bd1ecdc24c49a72b)

**Comment by brunoais** [comment]
@salrashid123 Why won't you do a PR with such proposal?

**Comment by salrashid123** [comment]
ah.....sorry, i just realized i didn't add on the abiltiy to set the `spanId`  to that PR...

 - [https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging_v2/proto/log_entry_pb2.py#L172](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging_v2/proto/log_entry_pb2.py#L172)

how do you want to handle this?   revert this one or shoul i submit a new issue+PR?  (a new one i guess)

maybe something like
`logger.log_text(TEXT, client=client, labels=LABELS, severity=SEVERITY, trace=TRACE, span=SPAN)`

**Comment by brunoais** [comment]
@salrashid123 new PR
