### ISSUE TITLE
BigTable: Mac/Windows [Feature Request] 

### ISSUE THREAD

**Issue by thakursc1** [GoogleCloudPlatform/google-cloud-python#5510]
According to RCP we can do a increment operation if we have  a `rpc ReadModifyWriteRow`
I have a `CheckandMutateRow` in its true state it needs to be incremented rather than set. Is there already a way to do that ? If yes is it an atomic transaction ? Also if not is there a possibility of adding a `increment` functionality to `CheckandMutateRow` in rpc and Python SDK.

**Comment by tseaver** [comment]
I believe that [`AppendRow.increment_row_value`](http://google-cloud-python.readthedocs.io/en/latest/bigtable/row.html#google.cloud.bigtable.row.AppendRow.increment_cell_value) does the atomic check-and-set that you need:  it treats missing values as 0 before applying the increment.

**Comment by thakursc1** [comment]
@tseaver 
This is what I am trying to achieve in one atomic operation. 
```
if row.val > 0:
     increment by -1
else:
      delete row

```
Is there way to achieve this  ? 
The problem I am facing is : 
Although AppendRow can increment values it cannot check for negatives using row filters and on the other hand CheckAndMutate can check for negatives but it cannot actually increment the value it can only set it to specific value.
