### ISSUE TITLE
BigTable on AppEngineStandard

### ISSUE THREAD

**Issue by klaister** [GoogleCloudPlatform/google-cloud-python#5525]
# Thank you for reporting an issue to google-cloud-python!

If you are reporting an issue or requesting a feature, please search the
existing open and closed issues to see if there is already work being done.

Google Bigtable Python Client Library is not compatible with App Engine's standard hosting environment.

Does anyone know if there is any way to connect to Bigtable from APP ENGINE STANDARD or should i use Flexible ?

Thanks for answering in advance.

**Comment by sduskis** [comment]
@theacodes, do you know about gRPC status with App Engine Standard?

**Comment by theacodes** [comment]
See #1893
