### ISSUE TITLE
Street View Publish: google-gax not found

### ISSUE THREAD

**Issue by Finfa811** [GoogleCloudPlatform/google-cloud-python#5527]
- Windows 10
- Python 2.7.14
- google-cloud==0.33.1
- gapic-google-maps-streetview-publish-v1==0.1.4
- google-gax==0.15.16

### Traceback:

> Traceback (most recent call last):
>   File "C:/streetview/tests/test_upload.py", line 2, in <module>
>     from google.streetview.publish.v1 import street_view_publish_service_client as client
>   File "C:\Users\Finfa811\\.virtualenvs\streetview\lib\site-packages\google\streetview\publish\v1\street_view_publish_service_client.py", line 33, in <module>
>     from google.gax import api_callable
>   File "C:\Users\Finfa811\\.virtualenvs\streetview\lib\site-packages\google\gax\__init__.py", line 47, in <module>
>     __version__ = pkg_resources.get_distribution('google-gax').version
>   File "C:\Users\Finfa811\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\setuptools-0.6c11\pkg_resources.py", line 311, in get_distribution
>     if isinstance(dist,Requirement): dist = get_provider(dist)
>   File "C:\Users\Finfa811\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\setuptools-0.6c11\pkg_resources.py", line 197, in get_provider
>     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
>   File "C:\Users\Finfa811\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\setuptools-0.6c11\pkg_resources.py", line 666, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "C:\Users\Finfa811\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\setuptools-0.6c11\pkg_resources.py", line 565, in resolve
>     raise DistributionNotFound(req)  # XXX put more info here
> pkg_resources.DistributionNotFound: google-gax

### Steps & Code

`pip install gapic-google-maps-streetview_publish-v1`

Tried testing the example in https://developers.google.com/streetview/publish/libraries. Error is raised in the line:

`from google.streetview.publish.v1 import street_view_publish_service_client as client`

**Comment by lukesneeringer** [comment]
Hello @Finfa811,
I am sorry you are having trouble.

One thing I am noticing in your traceback: You are running setuptools 0.6c11. That is about nine years old at this point, and very likely to be the issue. Is it possible for you to upgrade to a modern version? (It looks like you are using something involving App Engine, which I confess I am not familiar with.)

**Comment by Finfa811** [comment]
Thanks @lukesneeringer. 

You are right, the App Engine extension for Python is creating conflicts with the Street View Publish API. When you run `gcloud components install app-engine-python`, several libraries are installed, _setuptools 0.6c11_ among them.

In my _virtualenv_ I have the last version of _setuptools_ (39.2.0), but when running the code, the library is imported from the GAE distribution.

To fix it I just need to disable GAE support.
In any case it is very odd that such an old version of _setuptools_ is installed by default with the App Engine SDK...

**Comment by tseaver** [comment]
The only thing related to this repository in the report is that you appear to have the `google-cloud` umbrella package installed:  that package is deprecated, and also doesn't have anything to do with the reported traceback.

What *is* present in the traceback is libraries from the `Google Cloud SDK` distribution, which is supported [here](https://cloud.google.com/sdk/docs/getting-support).
