### ISSUE TITLE
google-cloud==0.33.1, ttn==2.1.1 with grpcio==1.7.3 hangs in completion_queue.poll() 

### ISSUE THREAD

**Issue by AnilkumarKomanduru** [GoogleCloudPlatform/google-cloud-python#5528]
# Thank you for reporting an issue to google-cloud-python!

Actually when I try use the demo file with No changes ( https://github.com/TheThingsNetwork/python-app-sdk) except app-id and access key, 
Which is getting hung while creating handler i.e. handler = ttn.HandlerClient(app_id, access_key). 

Stack trace:

handler = ttn.HandlerClient(app_id, access_key)
|
handler.py  -- >  self.__open(discovery_address)
|
handler.py  -- >  self.announcement = discovery.get_by_app_id(self.app_id)
|
handler.py  -- > self.client.GetByAppID(req)
|
_channel.py -- >_handle_event(completion_queue.poll(), state, self._response_deserializer)
  Here I’m not getting any return call from this API.

The environment details :

1.	Python 3
2.	No Certificates are used ( Is this mandatory ? )

***3. I'm trying to run above code behind corporate proxy

**Comment by tseaver** [comment]
This issue is unrelated to any of the `google-cloud` API libraries, which are not imported by any of the code in the TTN repository.  Please report it [there](https://github.com/TheThingsNetwork/python-app-sdk/issues/new).
