### ISSUE TITLE
Storage: No module named google.protobuf/google.resumable_media

### ISSUE THREAD

**Issue by kierkegaard13** [GoogleCloudPlatform/google-cloud-python#5537]
OS: Ubuntu 17.10
Python 3.6.0 :: Continuum Analytics, Inc
conda 4.5.4
conda list:
google-api-core           0.1.4                     <pip>
google-api-core           0.1.4                      py_0    conda-forge
google-auth               1.2.1                      py_0    conda-forge
google-auth               1.2.1                     <pip>
google-auth               1.5.0                     <pip>
google-cloud-core         0.28.1                    <pip>
google-cloud-core         0.28.1                     py_0    conda-forge
google-cloud-storage      1.6.0                      py_1    conda-forge
google-resumable-media    0.3.1                     <pip>
google-resumable-media    0.3.1                      py_0    conda-forge
googleapis-common-protos  1.5.3                     <pip>
googleapis-common-protos  1.5.3                    py36_0    conda-forge

I'm having an issue with trying to use gcloud storage in our docker environment (though some fellow devs have been having this issue locally as well lately). Here's an example of what's going on:

```
root@xxx:/# python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import google.protobuf
>>> import google.resumable_media
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.resumable_media'
>>> 
[5]+  Stopped                 python
```

I'll also get another error concerning google.protobuf as well. Here's a partial traceback:
```
    from google.cloud import storage
  File "/opt/conda/lib/python3.6/site-packages/google/cloud/storage/__init__.py", line 37, in <module>
    from google.cloud.storage.batch import Batch
  File "/opt/conda/lib/python3.6/site-packages/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
  File "/opt/conda/lib/python3.6/site-packages/google/cloud/_helpers.py", line 33, in <module>
    from google.protobuf import duration_pb2
ModuleNotFoundError: No module named 'google.protobuf'
```

I install the gcloud libraries with conda (I've tried installing with pip as well, but same issue). Does anyone know what might be causing this issue? Thanks for the help.

**Comment by tseaver** [comment]
Something about how you are installing the various packages is wrecking the `google` namespace setup.  I cannot reproduce in a fresh Python 3.6 virtualenv:

```bash
$ python3.6 -m virtualenv /tmp/gcp-5537
Using base prefix '/opt/Python-3.6.3'
New python executable in /tmp/gcp-5537/bin/python3.6
Also creating executable in /tmp/gcp-5537/bin/python
Installing setuptools, pip, wheel...done.
$ /tmp/gcp-5537/bin/pip install --upgrade setuptools pip wheel
Looking in links: file:///home/tseaver/.pip/wheels
Requirement already up-to-date: setuptools in /tmp/gcp-5537/lib/python3.6/site-packages (39.2.0)
Requirement already up-to-date: pip in /tmp/gcp-5537/lib/python3.6/site-packages (10.0.1)
Requirement already up-to-date: wheel in /tmp/gcp-5537/lib/python3.6/site-packages (0.31.1)
$ /tmp/gcp-5537/bin/pip install google-cloud-storage
Looking in links: file:///home/tseaver/.pip/wheels
Collecting google-cloud-storage
  Downloading https://files.pythonhosted.org/packages/d4/1a/8238dda1547b9b6156f4cfc7923558bb67d6c608a28d677d0dc070babd31/google_cloud_storage-1.10.0-py2.py3-none-any.whl (52kB)
...
Successfully installed cachetools-2.1.0 certifi-2018.4.16 chardet-3.0.4 google-api-core-1.2.1 google-auth-1.5.0 google-cloud-core-0.28.1 google-cloud-storage-1.10.0 google-resumable-media-0.3.1 googleapis-common-protos-1.5.3 idna-2.7 protobuf-3.6.0 pyasn1-0.4.3 pyasn1-modules-0.2.1 pytz-2018.4 requests-2.19.1 rsa-3.4.2 six-1.11.0 urllib3-1.23
$ /tmp/gcp-5537/bin/python
Python 3.6.3 (default, Oct  4 2017, 16:14:25) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import google.protobuf
>>> import google.resumable_media
>>> 
```

Can you import the bare `google` package an report its path?

**Comment by kierkegaard13** [comment]
```
>>> import google
>>> google.__path__
['/opt/conda/lib/python3.6/site-packages/google']
>>> 
```

**Comment by kierkegaard13** [comment]
It also seems like `touch ./opt/conda/lib/python3.6/site-packages/google/__init__.py` fixes the issue, but I'm still wondering if there's a better fix. I've had teammates who continue to run into issues even trying said fix.

**Comment by tseaver** [comment]
Please see the [Namespace packages recipe on conda-forge](https://github.com/conda-forge/staged-recipes/wiki/Namespace-packages).

**Comment by tseaver** [comment]
Please reopen if you can reproduce the issue in a fresh virtual environment (no conda, etc.).  E.g.:

```bash
$ python3.6 -m venv /tmp/gcp-5537
$ /tmp/gcp-5537/bin/pip install --upgrade setuptools pip wheel
$ /tmp/gcp-5537/bin/pip install google-cloud-bigquery
$ /tmp/gcp-5537/bin/python -c "import google.cloud.storage; import google.protobuf; import google.resumable_media"
```
