### ISSUE TITLE
google.cloud.logging.handlers: send messages to stderr

### ISSUE THREAD

**Issue by helen-fornazier** [GoogleCloudPlatform/google-cloud-python#5565]
Would it be ok if we do the print at https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/logging/google/cloud/logging/handlers/transports/background_thread.py#L222
to stderr instead? So it doesn't disturb the output of the software?

Thanks

**Comment by theacodes** [comment]
Definitely!
