### ISSUE TITLE
Type conversion bug in google.cloud.monitoring.timeseries._make_typed_value

### ISSUE THREAD

**Issue by trendelkampschroer** [GoogleCloudPlatform/google-cloud-python#5568]
1. Monitoring
2. macOS high sierra
3. Python 3.6.4 :: Anaconda, Inc.
4. 
google-api-core           0.1.4                      py_0    conda-forge
google-auth               1.5.0                      py_0    conda-forge
google-cloud-core         0.28.1                     py_0    conda-forge
google-cloud-monitoring   0.28.1                    <pip>
google-cloud-storage      1.10.0                     py_0    conda-forge
google-resumable-media    0.3.1                      py_0    conda-forge
googleapis-common-protos  1.5.3                    py36_0    conda-forge

5.
File "", line 9, in <module>
    client.write_point(metric, resource, value)
  File "site-packages/google/cloud/monitoring/client.py", line 603, in write_point
    self.write_time_series([timeseries])
  File "lib/python3.6/site-packages/google/cloud/monitoring/client.py", line 546, in write_time_series
    for timeseries in timeseries_list]
  File "lib/python3.6/site-packages/google/cloud/monitoring/client.py", line 546, in <listcomp>
    for timeseries in timeseries_list]
  File "lib/python3.6/site-packages/google/cloud/monitoring/timeseries.py", line 105, in _to_dict
    'points': [point._to_dict() for point in self.points],
  File "lib/python3.6/site-packages/google/cloud/monitoring/timeseries.py", line 105, in <listcomp>
    'points': [point._to_dict() for point in self.points],
  File "lib/python3.6/site-packages/google/cloud/monitoring/timeseries.py", line 222, in _to_dict
    'value': _make_typed_value(self.value),
  File "lib/python3.6/site-packages/google/cloud/monitoring/timeseries.py", line 170, in _make_typed_value
    type_ = typed_value_map[type(value)]
KeyError: <class 'numpy.float64'> 

6.

7.
```python
import numpy as np
from google.cloud.monitoring import Client
value = np.float64(2.)
client = Client()
resource = client.resource("global", labels={"project_id": client.project})
metric = client.metric(type_=f"custom.googleapis.com/tmp/this_does_not_work", labels={"info": "This is not working"})
client.write_point(metric, resource, value)
```

I think _make_typed_value could be easily fixed, I'd be glad to submit a PR, but I am not sure where in the repository-tree that functionality resides.

**Comment by tseaver** [comment]
I'm afraid `google-cloud-monitoring 0.28.1` is old enough that there is no `timeseries.py` module anywhere, nor is there a `makek_typed_value()` function.

We won't be able to fix your bug, but might be able to get some help on migrating your app to use the latest version (`0.30.0` as of today).  At a guess, it will involve a call to [`MetricServicesClient.create_time_series`](https://googlecloudplatform.github.io/google-cloud-python/latest/monitoring/gapic/v3/api.html#google.cloud.monitoring_v3.MetricServiceClient.create_time_series).
