### ISSUE TITLE
Logging: python handler fails to parse log path when running via bash script

### ISSUE THREAD

**Issue by usul83** [GoogleCloudPlatform/google-cloud-python#5571]
I'm trying to attach a handler to a python logging module, which works as expected when I run the file directly from a [cloud compute engine SSH] terminal, however when I run it via a bash shell script (in the same terminal) it fails with the below traceback.

I tried supplying the project name and credentials explicitly (i.e. using client = logging.Client(project=project_id, credentials=credentials)), but it didn't change the error.

**To reproduce:**
_test_auth.py:_
import google.cloud.logging
import logging, logging.handlers

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(\_\_file\_\_)
cloud_log_client = google.cloud.logging.Client()
cloud_handler = google.cloud.logging.handlers.CloudLoggingHandler(cloud_log_client, name=\_\_file\_\_)
logger.addHandler(cloud_handler)

logger.info('a message')

_test_script.sh:_
#!/bin/bash
python3 data/sales_data/test_auth.py

**Output:**
INFO:data/sales_data/test_auth.py:a message
Waiting up to 5 seconds.
ERROR:google.cloud.logging.handlers.transports.background_thread:Failed to submit 1 logs.
Traceback (most recent call last):
  File "/home/xxxx/.local/lib/python3.5/site-packages/google/api_core/grpc_helpers.py", line 54, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/xxxx/.local/lib/python3.5/site-packages/grpc/_channel.py", line 514, in \_\_call\_\_
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/xxxx/.local/lib/python3.5/site-packages/grpc/_channel.py", line 448, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Received unexpected value: test_auth.py. Expected the form projects/[PROJECT_ID]/logs/[ID]"
        debug_error_string = "{"created":"@1530789317.599740876","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1083,"grpc_message":"Received unexpected value: test_auth.py. Expected the form projects/[PROJECT_ID]/logs/[ID]","grpc_status":3}"
>

**Comment by tseaver** [comment]
Your script is using `file`, but not defining it:  in this case, it will be the Python built-in `file()` function, which is certainly not what you want.  Maybe meant to use something derived from `__name__`, which will be the name of the module / script?

**Comment by usul83** [comment]
Thanks, but that was markdown picking up the \_\_*\_\_ as a bold, I was indeed using \_\_file\_\_, have edited

**Comment by usul83** [comment]
Worked it out, it's because \_\_file\_\_ passes the path from where the the command was run, rather than just the file name. So it must be confusing things at some point having a handler name with "/". Doing \_\_file\_\_.split('/')[-1] works.

**Comment by tseaver** [comment]
@usul83 I think ``__name__`` is probably what you were thinking.  Glad you found an answer.
