### ISSUE TITLE
BigQuery: Partitioning by field attribute in Table class missing

### ISSUE THREAD

**Issue by adri242** [GoogleCloudPlatform/google-cloud-python#5585]
I need to create a table in Bigquery partitioned by a specific field. I have noticed that this is only available via API Rest.

The class missing the attribute in the Python API is: google.cloud.bigquery.table.Table.

In the REST Reference the time partitioning attributes are defined as:
```
"timePartitioning": {
    "type": string,
    "expirationMs": long,
    "field": string,
    "requirePartitionFilter": boolean
  }
```

A new attribute to define the field named **field** above will be required

**Comment by tseaver** [comment]
PR #5267 added support for time partitioning.  That feature was released in [`bigquery-1.2.0`](https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/bigquery-1.2.0).

See the [docs for `Table.time_partitioning`](https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/generated/google.cloud.bigquery.table.Table.time_partitioning.html#google.cloud.bigquery.table.Table.time_partitioning)
