### ISSUE TITLE
Accuracy on Audio to Text Conversion

### ISSUE THREAD

**Issue by Tritrita** [GoogleCloudPlatform/google-cloud-python#5586]
Hi 

We are recording an audio and sending the Audio to Google Speech API-Python for converting to Text,but the conversion is not as expected.
How do we increase the accuracy of the Audio->Text Conversion.?

**For Info:**
The API is Speech API-MacOS-Python 3.6

Thanks,

**Comment by tseaver** [comment]
@Tritrita I'm not sure there is anything we can do in the Python library to help you.  Please see the [Speech-to-Text API Support docs](https://cloud.google.com/speech-to-text/docs/support) for resources.

In particular, the [Best Practices page](https://cloud.google.com/speech-to-text/docs/best-practices) might help.
