### ISSUE TITLE
BigQuery: 'Client.update_dataset' systest error, 412 PreconditionFailed

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#5588]
First error in [this CI run](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/7126):

```python
_______________________ TestBigQuery.test_update_dataset _______________________

self = <tests.system.TestBigQuery testMethod=test_update_dataset>

    def test_update_dataset(self):
        dataset = self.temp_dataset(_make_dataset_id('update_dataset'))
        self.assertTrue(_dataset_exists(dataset))
        self.assertIsNone(dataset.friendly_name)
        self.assertIsNone(dataset.description)
        self.assertEquals(dataset.labels, {})
    
        dataset.friendly_name = 'Friendly'
        dataset.description = 'Description'
        dataset.labels = {'priority': 'high', 'color': 'blue'}
        ds2 = Config.CLIENT.update_dataset(
            dataset,
>           ('friendly_name', 'description', 'labels'))

tests/system.py:189: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
google/cloud/bigquery/client.py:387: in update_dataset
    headers=headers)
...    
        if not 200 <= response.status_code < 300:
>           raise exceptions.from_http_response(response)
E           PreconditionFailed: 412 PATCH https://www.googleapis.com/bigquery/v2/projects/precise-truck-742/datasets/update_dataset_7126_1531263324: Precondition Failed

../.nox/sys-2-7/lib/python2.7/site-packages/google/cloud/_http.py:293: PreconditionFailed
```

**Comment by tseaver** [comment]
Same error occurs in failing snippets test in that CI run.

**Comment by tseaver** [comment]
Same error occurs in failing snippets test in that CI run.

**Comment by tswast** [comment]
I think this is a regression in the backend where the REST call to create table doesn't return the correct etag for the patch call.

**Comment by tswast** [comment]
I've pinged the BigQuery on-call.

**Comment by tswast** [comment]
I thought I might be able to work around this by calling `get_dataset()` before calling `update_dataset()`, but I still have flakes. I'll send a PR to disable these tests until the BQ team pushes a fix.

**Comment by hzitoun** [comment]
Hi, I'm using version google-cloud-bigquery==2.15.0 and still getting the error randomly when updating table description and labels. Any idea please?

**Comment by tseaver** [comment]
@hzitoun The `google-cloud-bigquery` client library for Python is no longer maintained in the repository.  Please report your issue in its [new repository](https://github.com/googleapis/python-bigtable/issues/).
