### ISSUE TITLE
PubSub: Message publish_time return type unexpected

### ISSUE THREAD

**Issue by alexcwatt** [GoogleCloudPlatform/google-cloud-python#5598]
I am working on a PubSub project and was a bit confused about the Message `publish_time`. I expected to get `datetime` per [the docstring](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/1acc8c22664229b6681ff91654932998e611e1c2/pubsub/google/cloud/pubsub_v1/subscriber/message.py#L152) for the method. Instead I got a `Timestamp` that apparently comes from protobuf types. I found there is even a [unit test](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/1acc8c22664229b6681ff91654932998e611e1c2/pubsub/tests/unit/pubsub_v1/subscriber/test_message.py#L49) that verifies that `publish_time` returns a `Timestamp`.

Can we return `datetime`? Or should the docs just be updated to explain what is actually being returned? I'd prefer the former but wanted to ask before submitting a PR, given the inconsistency.

**Comment by tseaver** [comment]
@alexcwatt Thanks for the report!  I believe that updating the implementation / test to convert the integer timestamp to a date time is best.

**Comment by tseaver** [comment]
@theacodes I marked this as `triaged for GA` because the return type of the `publish_time` method property needs to change to match the docstring:  ISTM that is a "surface" change which we might want to fix before GA.

**Comment by tseaver** [comment]
@alexcwatt If you don't already have a PR in hand, I'm going to go ahead this week, so that we can get the change in place before the upcoming GA release.

**Comment by alexcwatt** [comment]
@tseaver Awesome, thanks!
