### ISSUE TITLE
Dataproc: AttributeError: 'module' object has no attribute 'OperationsStub'

### ISSUE THREAD

**Issue by bencaine1** [GoogleCloudPlatform/google-cloud-python#5600]
OS: x86_64 GNU/Linux
Python 2.7.6
google-cloud-dataproc version: 0.1.0
google-cloud version: 0.32.0
google-api-core version: 1.1.2

Getting this error on creating a new ClusterControllerClient. Code to reproduce below.
```
$ python
>>> from google.cloud import dataproc_v1
>>> dataproc_client = dataproc_v1.ClusterControllerClient()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/dataproc_v1/gapic/cluster_controller_client.py", line 101, in __init__
    google.api_core.operations_v1.OperationsClient(channel))
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/operations_v1/operations_client.py", line 59, in __init__
    self.operations_stub = operations_pb2.OperationsStub(channel)
AttributeError: 'module' object has no attribute 'OperationsStub'
```

**Comment by tseaver** [comment]
@theacodes, @crwilcox Looks to be a codegen problem (needs a `synth.py` fixup for the location of the operation stub).  I labelled it `p1` because AFAICT it blocks any use of the library at all -- do we not have system tests?

**Comment by tseaver** [comment]
Looks to be fixed w/ the release of `google-cloud-dataproc 0.1.2`:

```bash
$ /opt/Python-2.7.14/bin/virtualenv /tmp/gcp-5600
New python executable in /tmp/gcp-5600/bin/python
Installing setuptools, pip, wheel...done.
$ /tmp/gcp-5600/bin/pip install --upgrade setuptools pip wheel
Looking in links: file:///home/tseaver/.pip/wheels
Requirement already up-to-date: setuptools in /tmp/gcp-5600/lib/python2.7/site-packages (40.0.0)
Requirement already up-to-date: pip in /tmp/gcp-5600/lib/python2.7/site-packages (10.0.1)
Requirement already up-to-date: wheel in /tmp/gcp-5600/lib/python2.7/site-packages (0.31.1)
$ /tmp/gcp-5600/bin/pip install google-cloud-dataproc
Looking in links: file:///home/tseaver/.pip/wheels
Collecting google-cloud-dataproc
...
Successfully installed cachetools-2.1.0 certifi-2018.4.16 chardet-3.0.4 enum34-1.1.6 futures-3.2.0 google-api-core-0.1.4 google-auth-1.5.0 google-cloud-dataproc-0.1.0 googleapis-common-protos-1.5.3 grpcio-1.13.0 idna-2.7 protobuf-3.6.0 pyasn1-0.4.3 pyasn1-modules-0.2.2 pytz-2018.5 requests-2.19.1 rsa-3.4.2 six-1.11.0 urllib3-1.23
$ /tmp/gcp-5600/bin/pip freeze
-f file:///home/tseaver/.pip/wheels
cachetools==2.1.0
certifi==2018.4.16
chardet==3.0.4
enum34==1.1.6
futures==3.2.0
google-api-core==0.1.4
google-auth==1.5.0
google-cloud-dataproc==0.1.0
googleapis-common-protos==1.5.3
grpcio==1.13.0
idna==2.7
protobuf==3.6.0
pyasn1==0.4.3
pyasn1-modules==0.2.2
pytz==2018.5
requests==2.19.1
rsa==3.4.2
six==1.11.0
urllib3==1.23
$ export GOOGLE_APPLICATION_CREDENTIALS=....
$ /tmp/gcp-5600/bin/python
>>> from google.cloud import dataproc_v1
>>> dataproc_client = dataproc_v1.ClusterControllerClient()
>>> 
```

**Comment by tseaver** [comment]
Hmm, that was a failure to reproduce with `google-cloud-dataproc 0.1.0`. :( -- `0.1.2` is not yet released.

**Comment by tseaver** [comment]
I was able to create an instance of `dataproc_v1.ClusterControllerClient()` using the just-now released `google-cloud-dataproc 0.1.2` release.

Please re-open if you can provide information about reproducing the issue with the current release.

**Comment by bencaine1** [comment]
Thanks so much @tseaver! It works for me now with version 0.1.2.

**Comment by tseaver** [comment]
@bencaine1 Great, I'm glad that works for you!

**Comment by hotstaff** [comment]
Same problem?

Python 2.7.6
google-cloud (0.34.0)
google-cloud-core (0.28.1)
google-cloud-dataproc (0.1.2)
google-cloud-speech (0.35.0)
google-api-core (1.3.0)

hotstaff@emw ~/python-docs-samples/speech/cloud-client $ python2.7 transcribe_streaming_mic.py 
Traceback (most recent call last):
  File "transcribe_streaming_mic.py", line 193, in <module>
    main()
  File "transcribe_streaming_mic.py", line 172, in main
    client = speech.SpeechClient()
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/speech_v1/gapic/speech_client.py", line 112, in __init__
    credentials=credentials,
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/speech_v1/gapic/transports/speech_grpc_transport.py", line 73, in __init__
    self._operations_client = google.api_core.operations_v1.OperationsClient(channel)
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/operations_v1/operations_client.py", line 59, in __init__
    self.operations_stub = operations_pb2.OperationsStub(channel)
AttributeError: 'module' object has no attribute 'OperationsStub'

  File "transcribe_streaming_mic.py", line 193, in <module>
    main()
  File "transcribe_streaming_mic.py", line 172, in main
    client = speech.SpeechClient()
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/speech_v1/gapic/speech_client.py", line 112, in __init__
    credentials=credentials,
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/speech_v1/gapic/transports/speech_grpc_transport.py", line 73, in __init__
    self._operations_client = google.api_core.operations_v1.OperationsClient(channel)
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/operations_v1/operations_client.py", line 59, in __init__
    self.operations_stub = operations_pb2.OperationsStub(channel)
AttributeError: 'module' object has no attribute 'OperationsStub'
