### ISSUE TITLE
Vision: Poor OCR Quality for Tabular Data

### ISSUE THREAD

**Issue by lsimkins** [GoogleCloudPlatform/google-cloud-python#5639]
**OS type and version**
macOS 10.13.5 (alpine linux used in Production)
Python 3.6.4
google-cloud-vision v0.31.1

This issue is specific to the quality of ocr output under a specific circumstance. If there is a more appropriate place to post this issue, please let me know.

**Summary**
The google cloud vision ocr document_text_detection output has a severe drop in quality for tabular data. In some circumstances, it appears to ocr the same text more than once (overlapping text) and in other circumstances misses text altogether. We've only noticed this happen in table cells containing 5 or fewer characters. The results are typically high quality otherwise.

I posted a quick example highlighting the issue. Original document is black. GCV text detection overlain in red.

**Example output.**
Text in original document was rotated 90°. This document was rotated before sending to the api to remove the rotation from the text. Several blocks of text were missed.
<img width="314" alt="screen shot 2018-07-17 at 12 35 50 pm" src="https://user-images.githubusercontent.com/1006600/42837930-17d0c988-89c5-11e8-8ae8-03ac9d1dd282.png">

**Example output**
Text in original document was rotated 90°. This document was **not** rotated before sending to the api, so the text was sent to the api rotated. Several blocks of text were ocr'd twice. (Several T4S cells have overlapping "T4S" and "TAS" text.)
<img width="305" alt="screen shot 2018-07-17 at 12 35 37 pm" src="https://user-images.githubusercontent.com/1006600/42837941-1f031f12-89c5-11e8-9ef4-a87f3279c7df.png">

**Comment by tseaver** [comment]
@lsimkins Thanks for the report.  Unfortunately, I don't think there is anything in the Python client library (`google-cloud-vision`) which could be contributing to the poor OCR quality.

Please check out the [Vision API support document](https://cloud.google.com/vision/docs/support) for ways to ask your question where the back-end team is more likely to hear and respond.

**Comment by lsimkins** [comment]
@tseaver Thank you. I'll post in the the vision google group.
