### ISSUE TITLE
Firestore: ImportError: No module named moves

### ISSUE THREAD

**Issue by pttdev** [GoogleCloudPlatform/google-cloud-python#5681]
1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
Firestore
2. OS type and version
Ubuntu 16.04
3. Python version and virtual environment information `python --version`
Python 2.7.12
4. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
gax-google-logging-v2==0.8.3
gax-google-pubsub-v1==0.8.3
gcloud==0.18.3
google-api-core==1.2.1
google-auth==1.5.0
google-cloud-core==0.28.1
google-cloud-firestore==0.29.0
google-cloud-storage==1.10.0
google-gax==0.12.5
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3
grpc-google-logging-v2==0.8.1
grpc-google-pubsub-v1==0.8.1
5. Stacktrace if available
6. Steps to reproduce
7. Code example
```
import os
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'mxyw6c-9b64d1d.json'

from pprint import pprint
from requests_toolbelt.adapters import appengine

appengine.monkeypatch()
from google.appengine.api import urlfetch

urlfetch.set_default_fetch_deadline(60)

from flask import Flask, render_template, request, jsonify, redirect

app = Flask(__name__)

import firebase_admin
from firebase_admin import credentials, auth
from google.cloud import firestore
import google.cloud.exceptions

cred = credentials.Certificate('firebase-adminsdk.json')
default_app = firebase_admin.initialize_app(cred)
db = firestore.Client()

@app.route('/<id>')
def index(id):
    return render_template('index.html', id=id)

@app.route('/check/<id>', methods=['POST'])
def check(id):
    id_token = request.form.get('token')
    password = request.form.get('pass')
    claims = auth.verify_id_token(id_token)
    pprint(claims)
```

```python
from six.moves import http_client
ImportError: No module named moves
```

**Comment by tseaver** [comment]
@pttdev There shouldn't be any possibility of having `six` without `six.moves`. Can you please provide the full traceback?

**Comment by tseaver** [comment]
@pttdev Also, can you show the full output of `pip freeze`?

**Comment by tseaver** [comment]
Closing due to lack of follow-up on requested information.

**Comment by josephluvanda** [comment]
Error still persist with `google-cloud-firestore.1.4.0`
