### ISSUE TITLE
Document thread-safety of library

### ISSUE THREAD

**Issue by BrandonY** [GoogleCloudPlatform/google-cloud-python#5685]
After reading through the docs, it is unclear to me whether I should expect this code to work:

```
from google.cloud import storage
import thread

client = storage.Client()
for blob in bucket.list_blobs():
  thread.start_new_thread( blob.download_to_filename, '/tmp/' + blob.name)
```

**Comment by tseaver** [comment]
`google-cloud-storage` has been based on `requests` since #3674, released with [`google-cloud-storage 1.3.0`](https://pypi.org/project/google-cloud-storage/1.3.0/) just about a year ago.

I'm leaving this open as a docs bug so that we add a note to that effect.

**Comment by BrandonY** [comment]
Sorry, you last me. Does being based on `requests` imply that `google-cloud-storage` is thread-safe, and the code example above should work fine?

**Comment by tseaver** [comment]
Yes to both questions.

**Comment by tseaver** [comment]
@BrandonY Here is the text I am planning to add to the [`client` page](https://googlecloudplatform.github.io/google-cloud-python/latest/storage/client.html):

```rst
.. note::

   Becuase the :class:`~google.cloud.storage.client.Client` uses the
   third-party :mod:`requests` library by default, it should be safe to
   share instances across threads.  In multiprocessing scenarious, best
   practice is to create client instances *after* 
   :class:`multiprocessing.Pool` or :class:`multiprocessing.Process` invokes
   :func:`os.fork`.
```

Does that address your need?

**Comment by tseaver** [comment]
@BrandonY Please follow up via #5763, if needed.
