### ISSUE TITLE
Bigtable: 'list_instances' systest flakes w/ simultaneous runs

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#5695]
See: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/7441

The fix from #5476 didn't account for the fact that the "other" test run might be deleting instances, too.

**Comment by sduskis** [comment]
We should probably just check to make sure that the instance(s) we know exist are in the list.

**Comment by sduskis** [comment]
@AVaksman, FYI

**Comment by tseaver** [comment]
The `tests/system.py` module computes `EXISTING_INSTANCES` at the beginning of the test run, and expects that those instances will be present for its duration (at least until `test_list_instances` runs).  However, when two CI runs overlap, one can tear down / remove its temporary instance after the other has started, but before the `test_list_instances` run.

We can fix this one of two ways:

- Exclude CI-generated instances from `EXISTING_INSTANCES` (any matching the patterns `g-c-p-{unique_id}`, `new-{unique_id}` or `ndef-{unique_id}`).
- Update `test_list_instances` to assert only that the one instance known to be created (w/ `INSTANCE_ID`) is present.

**Comment by tseaver** [comment]
> Update test_list_instances to assert only that the one instance known to be created (w/ INSTANCE_ID) is present.

#5696 implements the second option.
