### ISSUE TITLE
pkg_resources.UnknownExtra: googleapis-common-protos 1.6.0b4 has no such extra feature 'grpc'

### ISSUE THREAD

**Issue by sadeel** [GoogleCloudPlatform/google-cloud-python#5703]
I am trying to to fetch the following dependencies in my pip virtualenv.

    'pydicom',
    'requests-toolbelt',
    'google-api-python-client',
    'google-api-core',
    'googleapis-common-protos',
    'google-cloud-pubsub',
    'httplib2',
    'oauth2client'

This leads to an error stating: pkg_resources.UnknownExtra: googleapis-common-protos 1.6.0b4 has no such extra feature 'grpc'.

Pinning it to 'googleapis-common-protos==1.5.3' seems to work, anyone know why?

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
General
2. OS type and version
Docker image running google/cloud-sdk
3. Python version and virtual environment information `python --version`
Python 2.7.9 & virtualenv 16.0.0

5. Stacktrace if available
Step #0: Traceback (most recent call last):
Step #0:   File "setup.py", line 35, in <module>
Step #0:     description='Breast Density Classification Inference Module.')
Step #0:   File "/opt/inference_module/venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 131, in setup
Step #0:     return distutils.core.setup(**attrs)
Step #0:   File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
Step #0:     dist.run_commands()
Step #0:   File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
Step #0:     self.run_command(cmd)
Step #0:   File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
Step #0:     cmd_obj.run()
Step #0:   File "/opt/inference_module/venv/local/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
Step #0:     self.do_egg_install()
Step #0:   File "/opt/inference_module/venv/local/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
Step #0:     cmd.run()
Step #0:   File "/opt/inference_module/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 415, in run
Step #0:     self.easy_install(spec, not self.no_deps)
Step #0:   File "/opt/inference_module/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 657, in easy_install
Step #0:     return self.install_item(None, spec, tmpdir, deps, True)
Step #0:   File "/opt/inference_module/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 704, in install_item
Step #0:     self.process_distribution(spec, dist, deps)
Step #0:   File "/opt/inference_module/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 749, in process_distribution
Step #0:     [requirement], self.local_index, self.easy_install
Step #0:   File "/opt/inference_module/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 785, in resolve
Step #0:     new_requirements = dist.requires(req.extras)[::-1]
Step #0:   File "/opt/inference_module/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2618, in requires
Step #0:     "%s has no such extra feature %r" % (self, ext)
**Step #0: pkg_resources.UnknownExtra: googleapis-common-protos 1.6.0b4 has no such extra feature 'grpc'**
Step #0: The command '/bin/sh -c pip install --upgrade pip && pip install --upgrade virtualenv &&     virtualenv /opt/inference_module/venv &&     . /opt/inference_module/venv/bin/activate &&     cd /opt/inference_module/src/ &&     python setup.py install' returned a non-zero code: 1
Finished Step #0
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: exit status 1
Step #0:

**Comment by tseaver** [comment]
(Note similar traceback in #5636, due to a pin in out-of-date `google-cloud-dataproc`.)

I can't reproduce in an empty Python 2.7 virtualenv:

```bash
$ /opt/Python-2.7.14/bin/virtualenv /tmp/gcp-5703
New python executable in /tmp/gcp-5703/bin/python
Installing setuptools, pip, wheel...done.
$ /tmp/gcp-5703/bin/pip install --upgrade setuptools pip wheel
Looking in links: file:///home/tseaver/.pip/wheels
Requirement already up-to-date: setuptools in /tmp/gcp-5703/lib/python2.7/site-packages (40.0.0)
Requirement already up-to-date: pip in /tmp/gcp-5703/lib/python2.7/site-packages (18.0)
Requirement already up-to-date: wheel in /tmp/gcp-5703/lib/python2.7/site-packages (0.31.1)
$ /tmp/gcp-5703/bin/pip install pydicom requests-toolbelt googleapis-common-protos google-api-core googleapis-common-protos google-cloud-pubsub httplib2 oauth2client
...
Successfully installed cachetools-2.1.0 certifi-2018.4.16 chardet-3.0.4 enum34-1.1.6 futures-3.2.0 google-api-core-1.3.0 google-auth-1.5.0 google-cloud-pubsub-0.35.4 googleapis-common-protos-1.5.3 grpc-google-iam-v1-0.11.4 grpcio-1.13.0 httplib2-0.11.3 idna-2.7 oauth2client-4.1.2 protobuf-3.6.0 pyasn1-0.4.4 pyasn1-modules-0.2.2 pydicom-1.1.0 pytz-2018.5 requests-2.19.1 requests-toolbelt-0.8.0 rsa-3.4.2 six-1.11.0 urllib3-1.23
```

The `grpc` extra is not needed / used Maybe you have older versions installed which pin it?  Could you try installing fresh, or with `pip install --upgrade`?

**Comment by joshuahendinata** [comment]
Having the same issue when running on docker container. specifying the googleapis-common-protos==1.5.3 resolve the issue

**Comment by tseaver** [comment]
Please feel free to reopen with fresh information.

**Comment by rapkyt** [comment]
I'm having the same problem:

Docker image of python:2.7.15
```
RUN ["pip", "install", "--upgrade", "pip", "setuptools", "wheel"]
RUN ["python", "setup.py", "install"]
```
and in `python setup.py`:
```
from distutils.core import setup

from setuptools import find_packages

setup(
    name="Some-name",
    version='1',
    description='description',
    author='author',
    author_email='author@email.com',
    url='https://github.com/dowjones',
    packages=find_packages(exclude='tests')
    include_package_data=True,
    install_requires=[
        'google-auth==1.0.2',
        'google-cloud-pubsub==0.38.0',
        'google-cloud-core==0.28.1',
        'mock==2.0.0',
        'oauth2client==3.0.0',
        'requests==2.18.4'
    ],
    classifiers=[
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 3'
    ]
)
```

stacktrace:
```
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    'Programming Language :: Python :: 3'
  File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 415, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 657, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 704, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 749, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2629, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: googleapis-common-protos 1.6.0b6 has no such extra feature 'grpc'
```

the weird thing is that I can install those dependencies through pip install in my virtualenv.

**Comment by michael-erasmus** [comment]
I'm also experiencing this issue, like with @rapkyt this only seems to occur if I include `google-cloud-pubsub` in my `setup.py`, if I run `pip install google-cloud-pubsub` I'm not getting any errors either.

Any chance we can re-open the issue?
