### ISSUE TITLE
Running dev_appserver on remote machine behind a proxy

### ISSUE THREAD

**Issue by ahti-qvik** [GoogleCloudPlatform/google-cloud-python#5722]
I have managed to put myself into a very special circumstance (or maybe OS vendors have), where I can't find a stable project development solution, which I would enjoy; I have been using Chromebook for development with Cloud 9 and alike services. I like the paradigm of developing on remote servers, because you don't have to deal with the bugs and system malfunctions, which tend to plague the virtualization tools on Windows and OS X (people say they work, but I think they haven't tried cloud development paradigm). I have been very happy developer for past three years... until I switched jobs and have to use HTTP development tools like the admin panel of AppEngine.

Some tools bend to my will more easily than others. With AppEngine the problem is, that you are checking the Host headers for security reasons and only allow localhost, I tried overriding that with a header rewrite, but you use relative URIs only, which read the Host header; so either I can not access datastore features or the links do not work, which makes the panel quite useless.

Some other tools, which do bend to my will more easily have solved this issue by allowing you to define root_path variable; so in the admin panel software you will use absolute paths, which can be defaulted to the Host and overridden if such variable is present.

I believe I could also just buy a domain, but some users might not want to do that.

Of course there might already be a solution, but I haven't been able to discover it, so feel free to point me towards right direction.

**Comment by tseaver** [comment]
@ahti-qvik I'm sorry your development experience is less fun now.  Unfortunately, this repository is dedicated to the `google-cloud-<apiname>` client libraries, and is not the right place to report issues or ask for support for AppEngine development.

Please check out the "Support" links on the [Python on Google App Engine](https://cloud.google.com/appengine/docs/python/) page, or maybe the [GAE Python StackOverflow](https://stackoverflow.com/questions/tagged/google-app-engine+python) topic.
