### ISSUE TITLE
Spanner: Improve Doc linking

### ISSUE THREAD

**Issue by crwilcox** [GoogleCloudPlatform/google-cloud-python#5723]
In our spanner docs we have mentions of `client` that don't go anywhere. For instance
https://googlecloudplatform.github.io/google-cloud-python/latest/spanner/usage.html#instantiating-a-client

It may be useful to have them link to https://googlecloudplatform.github.io/google-cloud-python/latest/spanner/client-api.html.

Also https://googlecloudplatform.github.io/google-cloud-python/latest/spanner/client-api.html doesn't seem to be in the nav bar. It may be useful to call out 'client usage' there for discovery

Also, https://googlecloudplatform.github.io/google-cloud-python/latest/spanner/session-api.html may also be a good thing to add to the navbar as well.

**Comment by tseaver** [comment]
@crwilcox 

> In our spanner docs we have mentions of client that don't go anywhere.

Broken by the move of the actual module to `spanner_v1.client` (Sphinx wants the real module, not just any alias).  See 8bd57c5 (PR #5764).

> Also https://googlecloudplatform.github.io/google-cloud-python/latest/spanner/client-api.html doesn't seem to be in the nav bar. It may be useful to call out 'client usage' there for discovery

The spanner docs distinguish between "usage" pages (narrative, with examples). vs "API reference" pages (autogen from docstrings/signatures).  The API reference pages are all linked on the [`api-reference` sub-index](https://googlecloudplatform.github.io/google-cloud-python/latest/spanner/api-reference.html)

> Also, https://googlecloudplatform.github.io/google-cloud-python/latest/spanner/session-api.html may also be a good thing to add to the navbar as well.

The back-end team specifically requested suppressing mentions of direct session API usage:  they want users to invoke session-related stuff via the higher-level `database.snapshot` and `database.run_in_transaction` helpers.
