### ISSUE TITLE
Release BigQuery 1.5.0

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#5726]
For clustering feature.

@alixhami Do you want to try your hand at releasing this one?

**Comment by tswast** [comment]
We might want to wait for https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5711

**Comment by tseaver** [comment]
@tswast We likely also need to fix the missing `bigquery-1.4.0` tag (I don't know if `releasetool` will work without it).

**Comment by tswast** [comment]
Thanks for taking care of the tag.

**Comment by tseaver** [comment]
I think we need to land #5714 first, as it fixes non-flaky BQ system tests.

**Comment by tswast** [comment]
Seth is OOO today, so I'll take a stab at the open comments.

**Comment by chenleiwhu** [comment]
when can I expect new version with clustering?
https://pypi.org/project/google-cloud-bigquery/1.4.0/#description

**Comment by tseaver** [comment]
@chenleiwhu Track PR 5735.

**Comment by tswast** [comment]
The CI for doing the auto-release just failed due to a failure in the spanner tests https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/7549

Assigning to Chris to cut a manual release.

**Comment by tswast** [comment]
The tag build just completed. The package is now live. https://pypi.org/project/google-cloud-bigquery/#history
