### ISSUE TITLE
Unable to List subcollections of the current document in Firestore

### ISSUE THREAD

**Issue by narsariamanu** [GoogleCloudPlatform/google-cloud-python#5730]
As per the documentation:
https://firebase.google.com/docs/firestore/query-data/get-data#list_subcollections_of_a_document
This is not supported on Firestore.

But in the python library codebase:
https://googlecloudplatform.github.io/google-cloud-python/latest/firestore/document.html#google.cloud.firestore_v1beta1.document.DocumentReference.collections
there is a function which can be used and is also present in the codebase.

Link to Codebase implementation:
https://googlecloudplatform.github.io/google-cloud-python/latest/_modules/google/cloud/firestore_v1beta1/document.html#DocumentReference.collections

But when I try to use this function it does not work. Am I missing something here or is this not yet pushed?

**Comment by tseaver** [comment]
@narsariamanu The `Document.collections` method was added in PR #5613, but there has been no release of `google-cloud-firestore` since it was merged.
