### ISSUE TITLE
AttributeError: module 'google.cloud.vision' has no attribute 'Client'

### ISSUE THREAD

**Issue by vashish76** [GoogleCloudPlatform/google-cloud-python#5752]
When i RUN this program on Spyder

```python
client = vision.Client('xx')  - xx = api key
```

I get the following error "AttributeError: module 'google.cloud.vision' has no attribute 'Client'"

Can you please help me resolve this ?  I am working on a time bound project of text detection

**Comment by tseaver** [comment]
Since PR #4493, the client is named `ImageAnnotatorClient`:

```python
>>> from google.cloud.vision import ImageAnnotatorClient
>>> client = ImageAnnotatorClient()
```

**Comment by vashish76** [comment]
Thanks for the help. 

I encountered few more issues but was able to resolve them..

Need few inputs, following is the entire code written in Jupyter.. I want to see the output of all the texts the code had recognized from the image. I am not able to see the o/p on the console. I also tried running it from anaconda prompt by giving following command but still not output (it just executes it) 

python <"full path of the py file" -> Press Return 

Following is the piece of code written for text recognition, appreciate if you point out what is missing in it ? 

import argparse
import io
import re

import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="D:\\Users\\Downloads\\Read Image-xxx.json"

#from google.cloud import storage
from google.cloud import vision
#from google.protobuf import json_format

from google.cloud.vision import ImageAnnotatorClient
client = ImageAnnotatorClient()

path = "D:\\Python\\Image Recognition\\r_001.jpeg"

def detect_text(path):
    with io.open(path, 'rb') as image_file:
        content = image_file.read()

    image = vision.types.Image(content=content)

    response = client.text_detection(image=image)
    texts = response.text_annotations
    print('Texts:')
        
    for text in texts:
       print('\n"{}"'.format(text.description))

    vertices = (['({},{})'.format(vertex.x, vertex.y)
                 for vertex in text.bounding_poly.vertices])

    print('bounds: {}'.format(','.join(vertices)))
   
On the jupyter console, i see the following...
runfile('D:/Python/Image Recognition/Image Recognition.py', wdir='D:/Python/Image Recognition')

**Comment by vashish76** [comment]
My bad... I am sorry.. forgot to call "detect_text" at the end of the program..  

Please ignore the above query.. thanks
