### ISSUE TITLE
Create a new release of the Bigtable library

### ISSUE THREAD

**Issue by mbrukman** [GoogleCloudPlatform/google-cloud-python#5770]
As of 7 Aug 2018, the [latest version of the Bigtable library on PyPi](https://pypi.org/project/google-cloud-bigtable/) is 0.29.0 from 28 Feb 2018. Would it be possible to release a new version (and release new ones regularly) to pick up the latest updates and ongoing feature additions, please?

Thank you!

/cc: @sduskis, @ghaisa

**Comment by sduskis** [comment]
There's one more change we need to make regarding [AppProfile](https://cloud.google.com/bigtable/docs/app-profiles) admin functionality that will be backwards incompatible.  We're aiming to be code complete by Monday.  It would be ideal to release after we commit the AppProfile changes.

**Comment by andyhky** [comment]
Is there any update on this?

**Comment by sduskis** [comment]
Version 0.30.0 was pushed to pypi.  Thanks @tseaver!

https://pypi.org/project/google-cloud-bigtable/
