### ISSUE TITLE
AutoML tutorial - ModuleNotFoundError: No module named 'google.cloud'

### ISSUE THREAD

**Issue by helgasvala** [GoogleCloudPlatform/google-cloud-python#5771]
Hey, I'm trying to go through the google cloud autoML tutorial (https://cloud.google.com/translate/automl/docs/tutorial), running on macOS High Sierra, with python 3.6.5 in Anaconda3.

Already in _step 1_ I'm experiencing issues, with the command:

`python automl_translation_dataset.py create_dataset "en_ru_dataset" "en" "ru"`

It returns `ModuleNotFoundError: No module named 'google.cloud'`

However, I seem to have google cloud installed at the same place as python, `pip show google-cloud` gives me:

`Name: google-cloud
Version: 0.34.0
Summary: API Client library for Google Cloud
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: googleapis-publisher@google.com
License: Apache 2.0
Location: /Users/username/anaconda3/lib/python3.6/site-packages
Requires: 
Required-by: ` 

and `which python` gives me 

`/Users/username/anaconda3/bin/python`

When I run `pip freeze`, I get in the list `gcloud==0.18.3`

The stacktrace when I call `python automl_translation_dataset.py create_dataset "en_ru_dataset" "en" "ru"` is:

`Traceback (most recent call last):
  File "automl_translation_dataset.py", line 268, in <module>
    args.target,
  File "automl_translation_dataset.py", line 37, in create_dataset
    from google.cloud import automl_v1beta1 as automl
ModuleNotFoundError: No module named 'google.cloud'
`
I've tried pip installing and updating google cloud as well as installing it by cloning the github directory. Nothing seems to fix the problem, I would be very thankful for some input to this problem.

**Comment by tseaver** [comment]
@helgasvala Thanks for the report.  You do not need the (outdated) `gcloud` Python library (as opposed to the `gcloud` CLI/SDK) nor the bare `google-cloud` package installed.  Instead, install `google-cloud-automl`, e.g.:

```bash
$ pip uninstall gcloud google-cloud
$ pip install --upgrade google-cloud-automl
```
