### ISSUE TITLE
pubsub: The publisher client API page is empty

### ISSUE THREAD

**Issue by edwardfung123** [GoogleCloudPlatform/google-cloud-python#5788]
The documentation page is empty. https://googlecloudplatform.github.io/google-cloud-python/latest/pubsub/publisher/api/client.html

However, the subscriber page is working.
https://googlecloudplatform.github.io/google-cloud-python/latest/pubsub/subscriber/api/client.html

**Comment by tseaver** [comment]
@edwardfung123 Thanks for the report!
