### ISSUE TITLE
allow compression in the write_to function (Storage)

### ISSUE THREAD

**Issue by ron819** [GoogleCloudPlatform/google-cloud-python#5791]
I'm using the library as follows:

`storage.Bucket('bucket_name').item(path).write_to(df['results'].to_json(), 'application/json')`

It would be nice if the write_to function will also have the ability to do compression.
For example data frame has the ability to :  
```
        df.to_csv(path_or_buf=file_name, index=False, encoding='utf-8',
                  compression='gzip',
                  quoting=QUOTE_NONNUMERIC)
```

However this requires me to save the file locally and only then upload it (same for csv and json)
So as I said, it would be nice if `compression='gzip'` would be av liable in the `write_to` function

**Comment by tseaver** [comment]
The `google-cloud-storage` library doesn't support that kind of access pattern.  The equivalent code there would look like:

```
from google.cloud import storage
client = stroage.Client()
bucket = client.get_bucket('bucket_name')
item = bucket.blob(path)
item.content_type = 'application/json'
item.upload_from_string(df['results'].to_json())
```
