### ISSUE TITLE
Support for Firestore Client on App Engine Standard?

### ISSUE THREAD

**Issue by joelfernandes19** [GoogleCloudPlatform/google-cloud-python#5796]
This is with regard to [#179](https://github.com/firebase/firebase-admin-python/issues/179) on Firebase Admin Python SDK.

Is there a workaround, or any updates on the timeline on when support for Firestore client will be added on App Engine Standard?

**Comment by theacodes** [comment]
These libraries are supported by the Python 3.7 runtime on GAE standard. At this time, we have no plans to support the Python 2.7 runtime.
