### ISSUE TITLE
Google Cloud Functions

### ISSUE THREAD

**Issue by pankajjoshi16** [GoogleCloudPlatform/google-cloud-python#5797]
OS: MACOS

I used following command

gcloud beta functions deploy start --runtime python37 --trigger-http --memory 2048MB --timeout 540s

(gcloud.beta.functions.deploy) OperationError: code=3, message=Build failed: USER ERROR:
`pip_download_wheels` had stderr output:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-wheel-8b_hn74q/PyWavelets/

error: `pip_download_wheels` returned code: 1

While deploying google cloud functions i got this error. I added scikit-image in my requirements.txt which was not added before.  Code was successfully deploying when scikit-image was not added in requirements.txt.

**Comment by tseaver** [comment]
The `google-cloud-python` libraries maintained in this repository are distinct from the `gcloud` CLI, which is part of the [Cloud SDK](https://cloud.google.com/sdk/docs/).  Please see [the support resources page](https://cloud.google.com/sdk/docs/getting-support).
