### ISSUE TITLE
Datastore: Ability to override base URL

### ISSUE THREAD

**Issue by eddavisson** [GoogleCloudPlatform/google-cloud-python#5801]
Seee https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/datastore/google/cloud/datastore/client.py.

It is currently only possible to override the base URL:

`_DATASTORE_BASE_URL = 'https://datastore.googleapis.com'`

by setting the `GCD_HOST` environment variable:

```
        try:
            host = os.environ[GCD_HOST]
            self._base_url = 'http://' + host
        except KeyError:
            self._base_url = _DATASTORE_BASE_URL
```

but this is meant to be used with the emulator and so does not use SSL.

It would be helpful to be able to override base_url to an https address.

**Comment by tseaver** [comment]
@eddavisson Can you please clarify the usecase?  Do you intend to run the emulator behind a proxy addressable via HTTPS (rather than running it on your local machine)?

**Comment by eddavisson** [comment]
@tseaver This would be for contacting an actual deployed instance of the API, either a non-prod environment or the prod environment via an alternative hostname. For example, the Dataflow SDK contacts the prod environment via the `batch-datastore.googleapis.com` hostname:
https://issues.apache.org/jira/browse/BEAM-1387

**Comment by QuantumInformation** [comment]
What was the solution here, would it help my issue?

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/87
