### ISSUE TITLE
datalab.storage.Item - allow to upload file from local disk

### ISSUE THREAD

**Issue by ron819** [GoogleCloudPlatform/google-cloud-python#5804]
according to: http://googledatalab.github.io/pydatalab/datalab.storage.html#
The supported function of `datalab.storage.Item` that allows upload is: `write_to`
this function upload string/stream. there is no way to upload a file.
meaning that if we want to upload a file we need to read it, convert it to stream and then upload it.

Please add function `uploadfile(path,content_type)`
which will allow to upload `json`/`csv` files from the local disk.

**Comment by tseaver** [comment]
Please report this issue to the [`googledatalab` repository](https://github.com/googledatalab/datalab).
