### ISSUE TITLE
[BigQuery] table schema field descriptions do not update

### ISSUE THREAD

**Issue by nicoleeel** [GoogleCloudPlatform/google-cloud-python#5805]
**Bigquery Python API: Updating schema with descriptions for fields / columns does not work**
Using the client API to add descriptions for fields does not work. 

**example code with fake data/query:**
```
def example(name, replace=False):

    client = bigquery.Client()

    query = '''
              SAMPLE QUERY HERE
        '''.format(name=name)
    
    job_config = bigquery.QueryJobConfig()

    job_config.create_disposition = 'CREATE_IF_NEEDED'
    job_config.write_disposition = 'WRITE_TRUNCATE' if replace else 'WRITE_EMPTY'
    
    table_ref = client.dataset("DATASET").table("{}".format(name))
    job_config.destination = table_ref
        
    query_job = client.query(
        query,
        location='COUNTRY'
        job_config=job_config)

    query_job.result()
    
    table = client.get_table(table_ref)
    table.description = 'overall table description works fine'
    table.schema = [bigquery.SchemaField('X', 'STRING', 'NULLABLE', description='DESCRIPTION!!'),
                        bigquery.SchemaField('X', 'DATE', 'NULLABLE', ''),
                        bigquery.SchemaField('X', 'STRING', 'NULLABLE', description='DESCRIPTION')]
    table = client.update_table(table, ['description'])
    table = client.update_table(table, ['schema']) 
```

Table will create successfully, with table description updating successfully, but schema for fields does not update. Have tried this in various methods, but it seems like a bug or lack of the option..

![screen shot 2018-08-15 at 1 43 03 pm](https://user-images.githubusercontent.com/21180332/44163353-279b6e80-a091-11e8-90c5-cf4f2083e533.png)

**Comment by tseaver** [comment]
We have a [passing system test](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/75de6a53c9feee1bc37ee4bfd1369b3010403194/bigquery/tests/system.py#L398) which exercises `Client.update_table`, specifically passing an updated schema.

Can you step into the call to `client.update_table(table, ['schema'])` and examine the `Tables` resource returned by the API call?
