### ISSUE TITLE
'ImageAnnotatorClient' object has no attribute 'safe_search_detection'

### ISSUE THREAD

**Issue by sumerc** [GoogleCloudPlatform/google-cloud-python#5814]
Hi all,

System is Ubuntu 14.04 and python3.4. google-cloud-vision is installed via pip. Here are the versions:
google-api-core==1.3.0
google-auth==1.5.1
google-cloud-vision==0.33.0
googleapis-common-protos==1.5.3

I am getting 'ImageAnnotatorClient' object has no attribute 'safe_search_detection' from the example below:

```python
from google.cloud import vision
from google.cloud.vision import types

client = vision.ImageAnnotatorClient()
image = types.Image(content=img_content)
response = client.safe_search_detection(image=image)
```

In my local dev environment (MACosx) it is working fine, but in this production setup it is not working...

I have tried reinstalling packages but that did not work either. Somehow, the safe_search_detection() method does not get bound to ImageAnnotatorClient object in this setup.

**Comment by sumerc** [comment]
I use following:
pip3 install google-cloud-vision

I reproduced the issue with a fresh install of Python 3.4.3. When I switch to Python 3.6, and run same commands the issue is not reproduced anymore. Below is the dockerfile I used to switch between Python versions with pyenv:

```
FROM ubuntu:14.04


RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install git make build-essential python-dev python-pip libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev curl

RUN git clone git://github.com/yyuu/pyenv.git .pyenv
RUN git clone https://github.com/yyuu/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv

ENV HOME  /
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

RUN pyenv install 3.4.3
#RUN pyenv global 2.7.6

RUN echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.profile
RUN echo '$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH"' >> ~/.profile
RUN echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.profile

RUN apt-get -y install vim 

CMD ["/bin/bash", "-l"]
```
With this pyenv, I run pip install google-cloud-vision, then I tried pip install --upgrade pip and then again upgrade google-cloud-vision without success. Then I install Python3.6 in the same system, then run pip install google-cloud-vision and everything works.

Is there any possibility there is a problem with this specific Python 3.4.3 version?

**Comment by tseaver** [comment]
Thanks for digging further into the problem!

The implementation of the standard library `enum` module in Python 3.4 changed in Python 3.5, and in the (ironically named) `enums34` backward-compatibility library used under Python 2.7, such that the enum type now exposes its members as attributes:  the Python 3.4 version does not.

The introspection code in `google.cloud.vision_helpers` depends on the new implementation.

I have a patch which should make Python 3.4 work, although we are no longer testing by default on 3.4.
