### ISSUE TITLE
Mocking google cloud storage

### ISSUE THREAD

**Issue by skhaz** [GoogleCloudPlatform/google-cloud-python#5816]
Hi,

I'm trying to test a piece of code that uses the google cloud storage, but there's no emulators for that neither something like to the [moto](https://github.com/spulec/moto). How can I mock these component?

Thanks.

**Comment by tseaver** [comment]
As you note, there is no emulator for the GCS service (see #4897, #4840):  constructing one is not within scope for the `google-cloud-storage` library project.

"Mocking" is perhaps ambiguous -- to me it implies more of a unit testing context, e.g.:

```python
from google.cloud import storage
import mock

def test_code_using_gcs():
    client = mock.create_autospec(storage.Client)
    # now set 'return_value', etc. on client's methods.

```
