### ISSUE TITLE
PubSub 0.37.1 Subscription Client is Broken

### ISSUE THREAD

**Issue by niwa-kazutomo** [GoogleCloudPlatform/google-cloud-python#5820]
Hi,

I encountered the following error.

```
  File "/******/PubsubAccessor.py", line 129, in create_subscriber_client
    credentials=credentials,
  File "/******/lib/python2.7/site-packages/google/cloud/pubsub_v1/gapic/subscriber_client.py", line 188, in __init__
    self.iam_policy_stub = (iam_policy_pb2.IAMPolicyStub(channel))
  File "/******/lib/python2.7/site-packages/google/iam/v1/iam_policy_pb2.py", line 344, in __init__
    self.SetIamPolicy = channel.unary_unary(
AttributeError: 'NoneType' object has no attribute 'unary_unary'
```

This problem did not occur in 0.35.4.
I checked the commit log and found a strange part.

https://github.com/GoogleCloudPlatform/google-cloud-python/commit/371333a51165e99d4d02876b1ef133618485b6fc#diff-e221f62050dd418b49b113c7909d0ea2L129

Channel initialization processing has been deleted.

https://github.com/GoogleCloudPlatform/google-cloud-python/commit/371333a51165e99d4d02876b1ef133618485b6fc#diff-e221f62050dd418b49b113c7909d0ea2R188

However, implementations using channel remain.

Thanks,
Kazutomo

**Comment by tseaver** [comment]
@theacodes I believe you have the state to point this issue in the right direction.

**Comment by theacodes** [comment]
@lukesneeringer

**Comment by lukesneeringer** [comment]
Lines 188 and 189 in `subscriber_client.py` should not be there.
As best as I can tell, [gapic-generator does not write them](https://github.com/googleapis/gapic-generator/blob/master/src/main/resources/com/google/api/codegen/py/main.snip#L134-L136), so this was probably an incomplete sync of some kind? If you re-generate, you should get a file without those lines. (A similar edit applies to `publisher_client.py`.)
