### ISSUE TITLE
Python Bitable system test fails with NameError: global name 'enums' is not defined

### ISSUE THREAD

**Issue by suhasm21** [GoogleCloudPlatform/google-cloud-python#5839]
URL: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/bigtable/tests

TestInstanceAdminAPI.test_create_instance_w_two_clusters fails with 
NameError: global name 'enums' is not defined
tests/system.py:312: NameError

Attached is the console output log
[BigtableError.docx](https://github.com/GoogleCloudPlatform/google-cloud-python/files/2311866/BigtableError.docx)

**Comment by tseaver** [comment]
Duplicates #5835
