### ISSUE TITLE
WriteDisposition and SourceFormat in incorrect package.

### ISSUE THREAD

**Issue by guillaumeblaquiere** [GoogleCloudPlatform/google-cloud-python#5845]
Hello

I'm new in python and BigQuery (I prefer Java, but GCF are only in node and python....) So, the code example is wrong for WriteDisposition and SourceFormat. The enumerations are in bigquery.`job`.WriteDisposition.WRITE_APPEND

File with problem (I don't look for others) `google-cloud-python/docs/bigquery/snippets.py`

~~~~
from google.cloud.bigquery.job import WriteDisposition
from google.cloud.bigquery.job import SourceFormat

job_config.write_disposition = WriteDisposition.WRITE_TRUNCATE
job_config.source_format = SourceFormat.CSV
~~~~

There is maybe another issue. I saw only these, linked at my code.

**Comment by tseaver** [comment]
Thanks for the report!  We actually import those types as aliases in `google.cloud.bigquery`, and document that we expect applications to import them from there (the snippets are tested via CI):

- [WriteDisposition](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/ac16d34d2d95d22fdc6228e5ce56c1eeae23f5d5/bigquery/google/cloud/bigquery/__init__.py#L61)
- [SourceFormat](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/ac16d34d2d95d22fdc6228e5ce56c1eeae23f5d5/bigquery/google/cloud/bigquery/__init__.py#L59)
