### ISSUE TITLE
ImportError: cannot import name pem

### ISSUE THREAD

**Issue by shubhamtanwar** [GoogleCloudPlatform/google-cloud-python#5846]
I'm writting test case for my app hosted on Google app engine and when running the following command an import error occurs
`nosetests -w tests --logging-level=ERROR --with-gae --gae-application=path_to_yaml_file --gae-lib-root=path_to_appengine`

### Following is the stacktrace of error message
`Traceback (most recent call last): File "/home/daffodil/Desktop/museconnect/venv/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName addr.filename, addr.module) File "/home/daffodil/Desktop/museconnect/venv/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath return self.importFromDir(dir_path, fqname) File "/home/daffodil/Desktop/museconnect/venv/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir mod = load_module(part_fqname, fh, filename, desc) File "/home/daffodil/Desktop/museconnect/tests/api/test_groups.py", line 8, in <module> from main import app File "/home/daffodil/Desktop/museconnect/main.py", line 5, in <module> from apis import api_blueprint File "/home/daffodil/Desktop/museconnect/apis/__init__.py", line 4, in <module> from .clients import api as clients File "/home/daffodil/Desktop/museconnect/apis/clients.py", line 4, in <module> from model.museconnect import ( File "/home/daffodil/Desktop/museconnect/model/museconnect.py", line 2, in <module> from model.user import User File "/home/daffodil/Desktop/museconnect/model/user.py", line 10, in <module> from google.cloud import storage, exceptions File "/home/daffodil/Desktop/museconnect/venv/local/lib/python2.7/site-packages/google/cloud/storage/__init__.py", line 36,in <module> from google.cloud.storage.client import Client File "/home/daffodil/Desktop/museconnect/venv/local/lib/python2.7/site-packages/google/cloud/storage/client.py", line 19, in <module> from google.cloud.client import JSONClient File "/home/daffodil/Desktop/museconnect/venv/local/lib/python2.7/site-packages/google/cloud/client.py", line 18, in <module> from google.oauth2 import service_account File "/home/daffodil/Desktop/museconnect/appvendor/google/oauth2/service_account.py", line 77, in <module> from google.auth import _service_account_info File "/home/daffodil/Desktop/museconnect/appvendor/google/auth/_service_account_info.py", line 22, in <module> from google.auth import crypt File "/home/daffodil/Desktop/museconnect/appvendor/google/auth/crypt/__init__.py", line 39, in <module> from google.auth.crypt import rsa File "/home/daffodil/Desktop/museconnect/appvendor/google/auth/crypt/rsa.py", line 27, in <module> from google.auth.crypt import _python_rsa File "/home/daffodil/Desktop/museconnect/appvendor/google/auth/crypt/_python_rsa.py", line 25, in <module> from pyasn1_modules import pem ImportError: cannot import name pem`

##### There are two pyasn1_modules... one in the google-cloud-sdk/platform/google_appengine/lib/ folder and other in appvendor folder of my app directory. The later one has pem.py file but the first one doesn't.

Tried to remove `pyasn1_modules` before adding `appvendor` from system path as mentioned in the following issue but this module is not present in `sys.modules`.
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2895

**Comment by theacodes** [comment]
Hi there! These libraries are not supported on the App Engine standard 2.7 runtime. They are supported on the Python 3.7 runtime for standard.
