### ISSUE TITLE
Request to release GCS Python library

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-python#5855]
Hi,

Is it possible to release the Storage client library for Python?

I'd like the new method `get_service_account_email` to be available. Unless there exist concerns.

**Comment by tseaver** [comment]
@frankyn my only current storage-related concern is the flaky KMS system tests (#5852).  We can likely make a release without addressing it.

**Comment by frankyn** [comment]
Let's take a look at the failing tests first. I think it's a permission issue.

**Comment by tseaver** [comment]
@frankyn The failures are flaky:  I presume that means there needs to be some backoff / retry added, or maybe the KMS stuff has a LRO we need to wait on?

**Comment by frankyn** [comment]
KMS has strong consistency for newly created key rings and keys. Are they being disabled in-between?

https://cloud.google.com/kms/docs/consistency#keys

**Comment by tseaver** [comment]
@crwilcox Do you have context for the KMS issue?

**Comment by frankyn** [comment]
The issue is the CI service account requires permission to [cloudkms.keyRings.setIamPolicy](https://cloud.google.com/kms/docs/reference/permissions-and-roles#required_permissions) for it to be able to update the keyRing IamPolicy. The existing roles it exists in are: roles/owner and `roles/cloudkms.admin`, and I think using only `roles/cloudkms.admin` given the service account currently uses Editor would help solve this issue.
