### ISSUE TITLE
Uploaded folders not shown when listing

### ISSUE THREAD

**Issue by carlosV2** [GoogleCloudPlatform/google-cloud-python#5873]
I'm trying to list the items of a bucket but it does not return what I expected.

Here is my setup:
1/ In the web UI, drag & drop a folder into the bucket (f.e. `my_uploaded_folder` with `uploaded1.txt`)
2/ In the web UI, click the button to create a folder (f.e. `my_created_folder`)
3/ Drag & drop a file into `my_created_folder` (f.e. `uploaded2.txt`)

With this setup, I've tried the following:
- `GET <bucket_url>/o?prefix=&delimiter=/`
  It returns:
      - `my_uploade_folder`
      - `my_created_folder`
   It returns it in the prefixes section and nothing in the items section (as expected).
- `GET <bucket_url>/o?prefix=`
   It returns:
      - `my_uploaded_folder/uploaded1.txt`
      - `my_created_folder`
      - `my_created_folder/uploaded2.txt`
   Note that the folder `my_uploaded_folder` does not appear anywhere alone.

I've verified this behaviour with the python library too and also with `gsutil`. For instance, take a look at those `gsutil` outputs:
```bash
$ gsutil ls gs://<bucket>/
gs://<bucket>/my_created_folder/
gs://<bucket>/my_uploaded_folder/

gsutil ls gs://<bucket>/**
gs://<bucket>/my_created_folder/
gs://<bucket>/my_created_folder/uploaded2.txt
gs://<bucket>/my_uploaded_folder/uploaded1.txt

gsutil ls -R gs://<bucket>/
gs://<bucket>/my_created_folder/:
gs://<bucket>/my_created_folder/
gs://<bucket>/my_created_folder/uploaded2.txt

gs://<bucket>/my_uploaded_folder/:
gs://<bucket>/my_uploaded_folder/uploaded1.txt
```

Why I can't get `my_uploaded_folder` as an item alone when returning the items recursively?

Thank you

**Comment by tseaver** [comment]
Folders, per se, don't exist in Google Cloud Storage.  Per the [Object Naming API doc](https://cloud.google.com/storage/docs/naming#object-considerations):

> Object names reside in a flat namespace within a bucket, which means that different buckets can have objects with the same name. It also means that objects do not reside within subdirectories in a bucket. For example, you can name an object `/europe/france/paris.jpg` to make it appear that paris.jpg resides in the subdirectory `/europe/france`, but to Cloud Storage, the object simply exists in the bucket and has the name `/europe/france/paris.jpg`.

The console web UI *synthesizes* folders based on those names, but there is no actual folder to be listed.

**Comment by carlosV2** [comment]
Ah, I think I understand it now. Thanks.
