### ISSUE TITLE
AutoML client : Method not working on automl_v1beta1.PredictionServiceClient

### ISSUE THREAD

**Issue by leolazou** [GoogleCloudPlatform/google-cloud-python#5889]
**Location :** Python client for the AutoML API
**Problem :**
While initializing a `PredictionServiceClient` the methods `from_service_account_file()` and `from_service_account_json()` don't work as described in the [docs](https://googlecloudplatform.github.io/google-cloud-python/latest/automl/gapic/v1beta1/api.html).
Instead of taking the given service account credentials from the indicated json file, the code tries to get the retrieve the credentials from the GOOGLE_APPLICATION_CREDENTIALS environmental variable, and returns an error if it's not set.

**Solution :**
Instead of initializing the client with : 
```python
prediction_client = automl_v1beta1.PredictionServiceClient().from_service_account_file('/path/to/service-account-key.json')
```
One has to create the credentials in an other variable : 
```python
credentials = service_account.Credentials.from_service_account_file("/path/to/service-account-key.json")
prediction_client = automl_v1beta1.PredictionServiceClient(credentials=credentials)
```
Yet it would be great to have these described methods working.

-----
Google Cloud version : 0.34.0
Python version : 3.6.5 & 2.7.15rc1
OS : Ubuntu 18.04.1 & Linux Mint 19

**Comment by tseaver** [comment]
@leolazou Can you please show the traceback from the failing `from_service_account_file` call?

**Comment by tseaver** [comment]
Trying to reproduce:

```bash
$ python3.6 -m venv /tmp/gcp/5889
$ /tmp/gcp/5889/bin/pip install --upgrade setuptools pip wheel
...
Successfully installed pip-18.0 setuptools-40.2.0 wheel-0.31.1
$ /tmp/gcp/5889/bin/pip install google-cloud-automl
...
Successfully installed cachetools-2.1.0 certifi-2018.8.24 chardet-3.0.4 google-api-core-1.3.0 google-auth-1.5.1 google-cloud-automl-0.1.1 googleapis-common-protos-1.5.3 grpcio-1.14.2 idna-2.7 protobuf-3.6.1 pyasn1-0.4.4 pyasn1-modules-0.2.2 pytz-2018.5 requests-2.19.1 rsa-3.4.2 six-1.11.0 urllib3-1.23
$ /tmp/gcp/5889/bin/python
Python 3.6.3 (default, Oct  4 2017, 16:14:25) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud.automl_v1beta1 import PredictionServiceClient
>>> client = PredictionServiceClient.from_service_account_file('/path/to/serviceaccount.json')
>>> 
```

**Comment by leolazou** [comment]
@tseaver I am sorry, it was all a mistake in my code. I'll be more careful next time.
