### ISSUE TITLE
Firestore: Accept non-strings in '*collection_path' parameter of 'Client.collection'

### ISSUE THREAD

**Issue by Hypro999** [GoogleCloudPlatform/google-cloud-python#5892]
Short Explanation:
Hello, this is a small feature request/suggestion, what if we could allow passing any primitive data types or any class instances which can be converted into a string (that is, those which have a __str__(self) method associated with them) to be passed to the *collection_path parameter in the collection (and perhaps even  the document) method of the google.cloud.firestore_v1beta1.client.Client class?

Long Explanation:
The following example should demonstrate a reason as to why this might be worth considering:
Let's say that the firestore user is a server-side developer who uses a web framework like django which has a strong ORM system built-in. The user may want to use firestore as a "realtime database" which he/she could use to provide realtime updates to their client-side counterparts (which could be done via. django signals). To make things easier between the two, the user wants to model the firebase database after their very own MySQL (or other) database on the server. 

Now, instead of having to explicitly convert their object or object's id (an int) into a string, it would be cool if the firestore client API itself would simply do that (at least as a fail-safe even if the user is expected to explicitly provide a string).

As of now, if one accidentally tries to provide an int to the collection parameter, they would get a warning message similar to this:

File "<path>/google/cloud/firestore_v1beta1/client.py", line 172, in collection
    path = collection_path[0].split(_helpers.DOCUMENT_PATH_DELIMITER)
AttributeError: 'int' object has no attribute 'split'

which isn't a big deal, since the user would just realize a string is obviously required, and then explicitly type-cast, but it would be better if we could do that on the library-side.

Think about it, I could also throw my django model instances in as parameters, which sounds kinda nice, especially when firestore will (soon) support nested-collection (subcollection) queries.

Otherwise, maybe we could at least surround that one concerned line (no. 172) with a try and except to return better error messages.

It's a simple change for a simple idea. Could it be useful?

**Comment by Hypro999** [comment]
I'd like to volunteer to make the change, if the idea checks out.

**Comment by tseaver** [comment]
@jba Can you comment on the requested feature?

**Comment by jba** [comment]
I'm influenced by Go, which tries to avoid magic conversions, so I'd say no. But this is Python. @schmidt-sebastian is a better person to ask.

**Comment by schmidt-sebastian** [comment]
I am also leaning towards not supporting this. This is a very slippery slope. We almost have to restrictions on collection names. I would rather make this explicit, to make sure that if someone ends up with JSON or any other data format in their collection names, it really was their choice.

**Comment by Hypro999** [comment]
@JustinBeckwith why was I assigned to this issue 2 years after it was rejected and closed?

**Comment by JustinBeckwith** [comment]
Apologies, robot run amok 🤖
