### ISSUE TITLE
Pub/Sub Releases Page for Google Cloud Client Library for Python Needs An Update

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/google-cloud-python#5894]
The latest release for Pub/Sub is 0.37.2. But the releases page is somewhat behind at 0.30.0.  

Could we update this page? https://google-cloud-python.readthedocs.io/en/stable/pubsub/releases.html

**Comment by tseaver** [comment]
The `stable` tree in the docs should be removed altogether:  it is completely pointless / bogus now that we have deprecated the umbrella package, and is not being updated.

**Comment by tseaver** [comment]
@theacodes I tried to poke into this, but couldn't figure out how the contents of the `stable/` tree are being populated:  `test_utils/scripts/update_docs.sh` doesn't touch that tree at all.

```bash
$ git checkout  gh-pages
Branch gh-pages set up to track remote branch gh-pages from upstream.
Switched to a new branch 'gh-pages'
$ cd stable
$ git log .
commit ec7539ebf717f06f65860b7652031f5a91469741
Author: Christopher Wilcox <git@crwilcox.com>
Date:   Mon Apr 23 16:49:18 2018 -0700

    Redirect all pages of GitHub.io site to RTD (#5225)
    
    * generate redirect md for each file in github pages
    add config file that makes redirects work using jekyll plugin
    
    * delete versions not on RTD
    
    * mirror latest to stable

commit db32b916b3e36242dd1561a81131391dadf65ccd
Author: Danny Hermes <daniel.j.hermes@gmail.com>
Date:   Wed Dec 20 09:59:08 2017 -0800

    Removing `stable/` docs from `gh-pages`. (#4637)
    
    Done via:
    
      $ git rm -fr stable/
    
    Fixes #4611.

```

So, it looks like @crwilcox repopulated the `stable/` branch in #5225 after @dhermes removed it in #4637.  Becuase `stable/` is worthless, I'd rather re-remove it and then fix up any links which still point to it.

**Comment by theacodes** [comment]
Sounds reasonable to me?

**Comment by tseaver** [comment]
@theacodes Should the version trees for `gcloud` stay under `gh-pages`, e,g the [`0.10.0` version](https://google-cloud-python.readthedocs.io/en/0.10.0/).  OTOH, all the `_modules` bits under `gh-pages:0.10.0` are broken.

**Comment by theacodes** [comment]
If the docs are broken, we should drop them.

**Comment by tseaver** [comment]
I don't even know what the `_modules` bits are for. (/me looks).  Hmm, seems to be pages generated for source code.

**Comment by tseaver** [comment]
So, on the `gh-pages` branch, should I:

- `git rm -r stable/ 0.*/`
- Or just leave them as they are.

In addition, should we tweak the RTD config to drop the version-specific and stable builds?  BTW, if you'd like to add me as a maintainer / owner there, I can poke at it.

**Comment by theacodes** [comment]
readthedocs is basically dead for us.

**Comment by tseaver** [comment]
But would it be, post repo-split?  I have a suspicion, for instance, that the ginormous `docs/bigquery/generated` bit (from `autosummary`) may be killing the RTD build.

**Comment by theacodes** [comment]
Maybe, but it's also possible we might switch hosting altogether.

**Comment by tseaver** [comment]
> Maybe, but it's also possible we might switch hosting altogether.

Hmm, too bad we don't know somebody who has a free-to-us place to put static HTML for documentation websites. :)

**Comment by theacodes** [comment]
Haha.

**Comment by tseaver** [comment]
So, should I just remove the stale pages from the `gh-pages` branch?  E.g.:

```bash
$ git fetch --all
$ git checkout gh-pages
$ git merge upstream/gh-pages
$ git rm -r 0.8.0/
$ git rm -r 0.9.0/
$ git rm -r 0.10.0/
$ git rm -r 0.10.1/
$ git rm -r stable/
$ git commit -m "Take out trash."
$ git push upstream gh-pages
```

**Comment by theacodes** [comment]
Sure, but can we make a 404 page that does a JS redirect if some lost soul
finds themselves there?

**Comment by tseaver** [comment]
For my own memory: https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/
