### ISSUE TITLE
`pip install google-cloud==0.34.0` installs a package called `google-cloud` and nothing else

### ISSUE THREAD

**Issue by d-m-h** [GoogleCloudPlatform/google-cloud-python#5906]
As the title states, when I attempt to install the client libraries via PyPi (`pip install --upgrade google-cloud`) as of `0.34.0` this only installs a module called `google-cloud`, yet when I revert to an earlier version (`0.33.1`) all the individual packages come with.

I've tested this on Windows, Mac OS and Debian - I experience the same behaviour for all.

**Comment by di** [comment]
From https://pypi.org/project/google-cloud/:

> WARNING: The google-cloud Python package is deprecated. On June 18, 2018, this package will no longer install any other packages. Please install the product-specific google-cloud-* packages needed for your application.

Here's a list of all the specific packages you may want to install instead: https://github.com/GoogleCloudPlatform/google-cloud-python#google-cloud-python-client

**Comment by d-m-h** [comment]
@di alright, thanks for that, though I do think it is then pertinent to update the [Github.io](https://googlecloudplatform.github.io/google-cloud-python/) page, as it still retains the line `pip install --upgrade google-cloud`.
