### ISSUE TITLE
BigQuery: Add BadGateway to DEFAULT_RETRY predicate

### ISSUE THREAD

**Issue by bencaine1** [GoogleCloudPlatform/google-cloud-python#5918]
OS: Linux dc32b7e8763a 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 x86_64 x86_64 GNU/Linux
Python version: Python 2.7.6
google-cloud-bigquery: 1.5.0

I'm getting BadGateway exceptions periodically when running queries with the default retry object. Here's an example (relevant part of the stack trace):

```
  File "/opt/conda/lib/python2.7/site-packages/google/cloud/bigquery/job.py", line 2605, in done
    location=self.location)
  File "/opt/conda/lib/python2.7/site-packages/google/cloud/bigquery/client.py", line 579, in _get_query_results
    retry, method='GET', path=path, query_params=extra_params)
  File "/opt/conda/lib/python2.7/site-packages/google/cloud/bigquery/client.py", line 331, in _call_api
    return call()
  File "/opt/conda/lib/python2.7/site-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/opt/conda/lib/python2.7/site-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/opt/conda/lib/python2.7/site-packages/google/cloud/_http.py", line 293, in api_request
    raise exceptions.from_http_response(response)
BadGateway: 502 GET https://www.googleapis.com/bigquery/v2/projects/packard-campbell-synth/queries/c4af3c68-d204-455e-877f-9f81e1c77d68?maxResults=0: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>
```

It would be useful to add this to the DEFAULT_RETRY object in https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/retry.py.

**Comment by bencaine1** [comment]
I've patched the library at commit f3e00adb4abec400ecc51636cd2c5632b44af5ea, and we're still getting BadGateways.

I think it's because the BadGateway is raised before the job is done, and therefore looking at the job's errors isn't going to show BadGateway. So I believe you'll need to catch BadGateway using something like the if_exception_type method (https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/api_core/google/api_core/retry.py#L78).

**Comment by tseaver** [comment]
@bencaine1 Thanks for the followup.  The issue is that the `BadGateway` you report is being raised from `Client._get_query_results`, which doesn't take a `retry` argument.

**Comment by tseaver** [comment]
Oops, `Client._get_query_results` **does** [take a `retry` argument](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/64caa5f0a319313ccc5dbe515ae91c4029548447/bigquery/google/cloud/bigquery/client.py#L538), and `QueryJob.result` [passes it](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/64caa5f0a319313ccc5dbe515ae91c4029548447/bigquery/google/cloud/bigquery/job.py#L2647).

**Comment by tswast** [comment]
It could be that `errors` or `reason` isn't getting populated? I think 502 comes from the layer before it actually hit's BigQuery, so maybe the BigQuery team's advice to look at the body rather than error codes shouldn't apply for 502?

**Comment by tswast** [comment]
CC @shollyman

**Comment by shollyman** [comment]
Yes, this is likely a GFE response, which means we're not going to get a structured error back.

**Comment by bencaine1** [comment]
Thanks! We've patched this version and we haven't seen any BadGateways yet. Will keep you posted :)

**Comment by bencaine1** [comment]
@tseaver, PTAL when you get a chance. Thanks!

**Comment by tseaver** [comment]
@bencaine1 is your application passing a non-default `retry` argument to `client.query`?
