### ISSUE TITLE
Please cut new release of Cloud Storage

### ISSUE THREAD

**Issue by danoscarmike** [GoogleCloudPlatform/google-cloud-python#5940]
Please cut a release to include https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5877 (Object Lifecycle Management)

**Comment by tseaver** [comment]
See #5942.

**Comment by danoscarmike** [comment]
Thanks Tres and for pointing that out.

**Comment by tseaver** [comment]
Release is at: https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/storage-1.12.0
