### ISSUE TITLE
Storage: Uploading with signed url from client side returns 404 or 413 errors

### ISSUE THREAD

**Issue by arvindnrbt** [GoogleCloudPlatform/google-cloud-python#5964]
**Our Usecase**
We have thousands of files that needs to be uploaded to GCS and hence we have planned to generate a pre-signed url for each of the file in batches and attempt to upload them directly from the client side.

**Additional Info**
We are uploading files into a folder in GCS bucket which I know is just a prefix to the name of objects that we are uploading (Including this detail to see if it may help).

**Code to generate signed url:**
```google-cloud-storage - 1.10.0```

```
        signed_url = fileblob.generate_signed_url(
           timedelta(hours=6),
            method='PUT',
            content_type='application/pdf')
```
**Problem:**
Once we generate the signed url and send it to the client, we attempt to upload the file from the browser but end up having a 404 for many files out of the lot (Some files do get uploaded).

These files are normal documents with a 2mb size. For files with 25mb+ sizes, we get a 413 (Request entity too large) response.

**Question**
1) why are we getting a 404 error when trying to create a new resource with a 'PUT' request (as in the docs) to the pre-signed url?
2) How do we go about uploading larger files from browser without getting the 413 response?
3) Is there any other way to bulk upload files to a GCS bucket from client side? Something like a folder sync that can be more like a desktop app (So we can stop relying on the browser)? We do hear something about ```gsutil rsync``` but how do we deploy it for the client side securely?

**Comment by tseaver** [comment]
When using `PUT`, you are dealing with the [XML API](https://cloud.google.com/storage/docs/xml-api/put-object), not with the `google-cloud-storage` library.  It looks like you want to use this library just to generate signed URLs, and then upload to those URLs in some other way.

That usage is out-of-scope for `google-cloud-storage`. Please see the [Getting Support page](https://cloud.google.com/storage/docs/getting-support) for Cloud Storage.
