### ISSUE TITLE
Please cut a release of Cloud Asset

### ISSUE THREAD

**Issue by danoscarmike** [GoogleCloudPlatform/google-cloud-python#5985]

**Comment by tseaver** [comment]
Pending fixed codegen in #5987.

**Comment by tseaver** [comment]
@danoscarmike I've got a question about packaging metadata / branding:  at the moment, `setup.py` has the name of the installed package as `google-cloud-cloudasset`, which has two drawbacks:

- It sounds inane when pronounced.
- It doesn't match the package structure (`google.cloud.asset_v1`).

I would prefer just using `google-cloud-asset` as the PyPI name.
