### ISSUE TITLE
Cloud Storage: Bucket.list_blobs returns incomplete set of blobs.

### ISSUE THREAD

**Issue by telenieko** [GoogleCloudPlatform/google-cloud-python#5990]
Hi there,

Tested on MacOS and Google Cloud Functions Python. Package Versions:
```
google-api-core==1.3.0
google-auth==1.5.1
google-auth-oauthlib==0.2.0
google-cloud-bigquery==1.5.0
google-cloud-core==0.28.1
google-cloud-storage==1.12.0
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3
```

I have a bucket full, full of files. When I query it from gsutil I get everything, just fine.
But when using list_bucket I only get a subset of the files.

```
gsutil ls -R gs://imega-v/winges-pdf |grep '.*PDF$'|wc -l
11822 
```
gsutil always gives all results (11822), but my python function only sees 4848 results, always 4848.

```python
    storage_client = storage.Client(project=project)
    bucket = storage_client.get_bucket(bucket)
    blobs = bucket.list_blobs(prefix='base', max_results=999999,
                              fields='items/name,nextPageToken')
    r = [b.name for b in blobs]
    print(len(r))
    return r
```

Sadly I cannot share the bucket as it is company data, but I guess any bucket with that many files may have the same issue.

marc

**Comment by tseaver** [comment]
Passing `prefix=base` limits the results to files whose [names start with `base`](https://cloud.google.com/storage/docs/json_api/v1/objects/list#parameters).  Your `gsutil` command line is not supplying that filter.

Please feel free to reopen if you find an apples-to-apples comparison where `Bucket.list_blobs` is not returning all expected values.

**Comment by telenieko** [comment]
Ok, I feel ashamed now. I was checking different places. Thanks for pointing it out @tseaver ! Fixed the typos and now working perfect

Do not take this into account when I run for President of the Known Universe!

**Comment by tseaver** [comment]
@telenieko No need for shame:  we all overlook stuff like that.  I'm glad the library is working for you!
