### ISSUE TITLE
Storage: please add something like createUploadUrl()  in PHP

### ISSUE THREAD

**Issue by oittaa** [GoogleCloudPlatform/google-cloud-python#5994]
I tried to search from the documentation and the code something similar to PHP's [createUploadUrl()](https://github.com/GoogleCloudPlatform/appengine-php-sdk/blob/6bdf4bcb638782526a6969aa36528ac583cbc3da/google/appengine/api/cloud_storage/CloudStorageTools.php#L161-L249), but I couldn't find anything. Please consider adding that functionality to the Python library.

**Comment by tseaver** [comment]
I think the method you are looking for is [`Blob.generate_signed_url`](https://googlecloudplatform.github.io/google-cloud-python/latest/storage/blobs.html#google.cloud.storage.blob.Blob.generate_signed_url)[https://googlecloudplatform.github.io/google-cloud-python/latest/storage/blobs.html#google.cloud.storage.blob.Blob.generate_signed_url].  To use it for upload:

```python
from google.cloud import storage

client = storage.Client()
bucket = client.bucket('my-bucket-name')
blob = bucket.blob('blob-name')
upload_url = blob.generate_signed_url(method='PUT')
```
