### ISSUE TITLE
Core: Add "deadline per retry" parameter to Retry object

### ISSUE THREAD

**Issue by bencaine1** [GoogleCloudPlatform/google-cloud-python#6009]
OS: Linux dc32b7e8763a 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 x86_64 x86_64 GNU/Linux
Python version: Python 2.7.6
google-cloud: 0.34.0

It would be great if, instead of specifying a deadline and retrying a query until you hit the deadline, you could specify a deadline per retry and a number of retries. For instance, I'd like to retry a query up to 3 times with a deadline of up to 20 minutes per query.

The current workaround in the above example would be to specify a single deadline of an hour. This works fine for now, but if our queries start taking longer than 20 minutes, we'd want to know so that we can refactor the queries or investigate why it's taking so long. So it would be helpful if we could raise a RetryError if each individual retry takes longer than a certain amount of time.

**Comment by theacodes** [comment]
You can subclass `Retry` and provide your own strategy, but we won't be changing our overall deadline pattern as part of the core library.
