### ISSUE TITLE
client.get_bucket() bucket permissions failure

### ISSUE THREAD

**Issue by michaelsmithhx** [GoogleCloudPlatform/google-cloud-python#6092]
Our project would like to use bucket level permissions for service account access.

This would typically involve:

(1) Using a service account that has limited project-wide permissions, e.g. only storage.buckets.list
since some tools need this to navigate the root of the namespace.

(2) Granting appropriate (e.g. Storage Admin and Storage Object Admin) permissions at the bucket level for the above service account.

The above configuration appears to FAIL when the following simple test is run under the service account profile:

```
from google.cloud import storage

client = storage.Client()
bucket = client.get_bucket('a-secure-bucket')
```
Looking at the code /error I'm guessing that the noACL projection forces the SDK to rely upon project level ACLs rather than the bucket level ACL?

This is causing problems for our GCP Dataflow jobs which utilise this lower level call.

**Comment by tseaver** [comment]
> Looking at the code /error I'm guessing that the noACL projection forces the SDK to rely upon project level ACLs rather than the bucket level ACL?

The `noACL` projection keeps the API from *returning* the ACL as part of the bucket resource -- it doesn't change how the backend enforces the ACL.  Within `google-cloud-storage`, we expose the bucket / object ACL via an `acl` attribute, which makes separate API calls to read / write the ACL.

Can you please provide the full traceback (mask out the bucket name).  My guess is that the credentials you are running with (via the environment) are for a service account which doesn't actually have permissions on to read the bucket.

**Comment by michaelsmithhx** [comment]
Hi, thanks for the quick follow up, I reviewed and identified an incorrect access control list entry, the functionality is now working as expected. Apologies for wasting your time.

**Comment by tseaver** [comment]
@michaelsmithhx Glad you were able to dig that up!
