### ISSUE TITLE
Discord.py can't install

### ISSUE THREAD

**Issue by aggz0** [GoogleCloudPlatform/google-cloud-python#6120]
-macOS High Sierra
when i try to run the (pip install discord.py) command on my terminal i get this message here.

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vn/v0ljrfl92tbf3lh6fh1kq6d40000gn/T/pip-install-WLF4ZL/aiohttp/

any way to fix this?

**Comment by tseaver** [comment]
I'm sorry, but you've reached the wrong repository:  you might try https://github.com/pypa/pip/
