### ISSUE TITLE
STORAGE: Bucket.delete_blobs() should use Batch

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#727]
This will also allow `Bucket.delete(force=True)` to use `Batch()`

**Comment by tseaver** [comment]
Ugh!  While conceptually this is a relatively simple change, it is a really messy thing to try to test (batching means kicking down a layer below `api_request`, which makes all the affected tests barf).  I've discarded the branch I started.

**Comment by dhermes** [comment]
Good to know. How do you mean "kicking down"?

**Comment by tseaver** [comment]
`Batch.finish` calls `_make_request` on its connection, rather than `api_request`.  The existing stub connection doesn't have that, and its contract is different enough that I backed off of trying to add it.  It was also going to be tricky to write assertions about the multipart sub-requests (I started factoring out helper methods from `TestBatch`, but dropped that as well).

No reason it couldn't be done:  I just felt like I was down the rabbit hole, and bailed.

**Comment by dhermes** [comment]
Cool. Seems like we could improve the code based on those observations. I'll ping you if I pick this up at some point.

**Comment by elibixby** [comment]
Should this have label: bug? 

The following code:

```
def delete_tmp_files(credentials, tmp_dir):
    logging.info('Deleting temporary files')
    parsed = urlparse.urlparse(tmp_dir)
    client = storage.Client(credentials=credentials)
    bucket = client.bucket(parsed.netloc)
    blobs = bucket.list_blobs(prefix=parsed.path)
    with client.batch():
        bucket.delete_blobs(blobs)
```

raises error `KeyError: "Cannot get('nextPageToken', default=None) on a future"` because the iterator returned by list_blobs is making calls to get the next page in the context of a batch. 

Maybe this is a seperate errors? Seems like the above code should work without encasing `blobs` in `list(blobs)`

**Comment by dhermes** [comment]
It's certainly separate from this issue, but good to know. I recommend against passing an iterator like that to `delete_blobs()` but it is a bug we can try to take a stab at.

**Comment by elibixby** [comment]
Slightly connected to this bug, since that pattern would be unnecessary if `delete_blobs` used a batch. But I agree it is seperate.

**Comment by tseaver** [comment]
Iterating over a collection while mutating it is always problematic, even without adding RPC calls to the mix:  see [PEP 3106](https://www.python.org/dev/peps/pep-3106/).

I would say the `list(blobs)` fix is the Right Thing(TM).

**Comment by elibixby** [comment]
In my mind `delete_blobs` should take an iterator. A `Blob` object's state is not intrinsically tied to the state of a blob in the cloud, therefor deleting a blob isn't (or shouldn't be) a mutation of the state of the blob itself. The blob is just a wrapper for information about how to make the RPC call.

**Comment by elibixby** [comment]
Again, how is this a mutation? `delete_blob` does do any modification of the `Blob` object. You can't infer "No mutation of any state at all" from that PEP, it's mutation of state associated with objects in the iterator?

**Comment by dhermes** [comment]
The state of the iterator depends on the return of API calls to LIST. If you delete things in that putative list of things, then it will have an effect on the overall state of that LIST call.

**Comment by elibixby** [comment]
Oooh, is pagination not fixed regardless of the status of the items on the previous page? I would assume it is? Otherwise I think that's an API bug.

**Comment by dhermes** [comment]
> Oooh, is pagination not fixed regardless of the status of the items on the previous page?

Unclear whether the answer is yes or no, hence the recommendation that you avoid mixing the two.

**Comment by elibixby** [comment]
Given there are performance implications to this: deleting entire pages as they are yielded to is faster than waiting to get through all the pages, I'm not sure that I agree. 

I think it's reasonable to assume that you will never see the same element twice due to pagination (but to be fair I can't find anything guaranteeing this in our API style guidelines)...

Maybe listing elements need to provide a `pages` iterator for clients who want to make batched requests as they receive. So e.g. I could do 
```
pages = bucket.list_blobs().pages
for page in pages:
   for blob in page:
      // Do stuff
```

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!

**Comment by The-Fonz** [comment]
Came here while trying to open a new issue concerning this. My usecase is deleting or moving millions of blobs. Currently I use one main thread that lists all blobs in a bucket and puts the ones to be deleted on a queue. A few dozen worker threads then individually delete each blob. I'm averaging about 60 deletes/sec, adding more threads doesn't help. And that's a bit slow for millions of blobs (takes days to run).

I'm trying to use the `Batch` class for this, but it is not entirely clear to me how to correctly use it and if it even supports deletes, am getting a header parsing error when I try to batch deletes.

It would be great if the `bucket.delete_blobs()` method (and other related methods for that matter) would use a batch by default. The current code is:

```python
    def delete_blobs(self, blobs, on_error=None, client=None):
        """Deletes a list of blobs from the current bucket.

        Uses :meth:`delete_blob` to delete each individual blob.

        If :attr:`user_project` is set, bills the API request to that project.

        :type blobs: list
        :param blobs: A list of :class:`~google.cloud.storage.blob.Blob`-s or
                      blob names to delete.

        :type on_error: callable
        :param on_error: (Optional) Takes single argument: ``blob``. Called
                         called once for each blob raising
                         :class:`~google.cloud.exceptions.NotFound`;
                         otherwise, the exception is propagated.

        :type client: :class:`~google.cloud.storage.client.Client`
        :param client: (Optional) The client to use.  If not passed, falls back
                       to the ``client`` stored on the current bucket.

        :raises: :class:`~google.cloud.exceptions.NotFound` (if
                 `on_error` is not passed).
        """
        for blob in blobs:
            try:
                blob_name = blob
                if not isinstance(blob_name, six.string_types):
                    blob_name = blob.name
                self.delete_blob(blob_name, client=client)
            except NotFound:
                if on_error is not None:
                    on_error(blob)
                else:
                    raise
```

The batch version might look something like (just a draft, not tested):

```python
def delete_blobs(self, blobs, on_error=None, client=None):
    with self.client.batch() as batch:
        for blob in blobs:
            try:
                blob_name = blob
                if not isinstance(blob_name, six.string_types):
                    blob_name = blob.name
                self.delete_blob(blob_name, client=client)
            # Send batch off if full
            if len(batch._requests) > batch._MAX_BATCH_SIZE - 1:
                batch.finish()
```
