### ISSUE TITLE
STORAGE: In _reload_properties, should we raise if _changes is not empty?

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#729]

**Comment by tseaver** [comment]
:-1:  Logging a warning *migh*t be appropriate, but if the user has triggered an API call (the only public way to reach `_reload_properties`), the server-side version of the metadata is always authoritative.

**Comment by tseaver** [comment]
I'm uncertain why we would assign a priority to this, or slot it into a project, given that it is an open question (not a bug, not a requested enhancement).

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
