### ISSUE TITLE
DISCUSSION: Should we reload() ACL info separately from other metadata

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#753]
This is true of both bucket and blob.

It is a bit nuanced since the ACLs can be in both the [bucket resource](https://cloud.google.com/storage/docs/json_api/v1/buckets#resource) / [object resource](https://cloud.google.com/storage/docs/json_api/v1/objects#resource) but can also be ~~retried~~ retrieved directly via [`storage.objectAccessControls.get`](https://cloud.google.com/storage/docs/json_api/v1/objectAccessControls), etc.

(ADDED by DJH): This is even more contrived since the ACL specific API [methods](https://developers.google.com/apis-explorer/#p/storage/v1/storage.objectAccessControls.get) also require an entity. (This especially frustrates @tseaver.)

**Comment by dhermes** [comment]
In #761 I "answer" this question with a "no". The `projection=noAcl` under the covers is ditched and the ACL data is loaded with other metadata.

**Comment by tseaver** [comment]
Again, this is an open question, not an actionable bug / enhancement, so prioritizing it seems misplaced.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
