### ISSUE TITLE
STORAGE: Send blob metadata in upload requests

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#754]
When `self._changes` is not empty, we should upgrade a `media` request to a [multipart upload](https://cloud.google.com/storage/docs/json_api/v1/how-tos/upload#multipart):

> If you have metadata that you want to send along with the data to upload, you can make a single `multipart/related` request. This is a good choice if the data you are sending is small enough to upload again in its entirety if the connection fails.

whereas for resumable uploads, we should

> Make an initial request to the upload URI that includes the metadata, if any.

@craigcitro Is there a way to set the body of the initial request in a resumable upload?

H/T to @pdknsk for #536

**Comment by craigcitro** [comment]
yes -- if you call `upload.ConfigureRequest` with an http request that has a body, it'll go ahead and set up the multipart upload for you:
  https://github.com/google/apitools/blob/master/apitools/base/py/transfer.py#L580

so i remember there was a reason that you guys didn't just want to use a generated storage client (which would handle these sorts of details for you); what was it?

**Comment by dhermes** [comment]
Thanks for the pointer for sending a body.

As for using  generated client, I don't remember there being a reason, but I'd guess it was Python 3 support and `protorpc`.

**Comment by dhermes** [comment]
I expected

```diff
diff --git a/gcloud/storage/blob.py b/gcloud/storage/blob.py
index ac3f9ce..c7e1336 100644
--- a/gcloud/storage/blob.py
+++ b/gcloud/storage/blob.py
@@ -340,7 +340,9 @@ class Blob(_PropertyMixin):
                                         path=self.bucket.path + '/o')
 
         # Use apitools 'Upload' facility.
-        request = http_wrapper.Request(upload_url, 'POST', headers)
+        body = '' if not self._changes else json.dumps(self._properties)
+        request = http_wrapper.Request(url=upload_url, http_method='POST',
+                                       headers=headers, body=body)
 
         upload.ConfigureRequest(upload_config, request, url_builder)
         query_params = url_builder.query_params
```

to handle it, but am getting

```json
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badContent",
    "message": "Unsupported content with type: application/octet-stream"
   }
  ],
  "code": 400,
  "message": "Unsupported content with type: application/octet-stream"
 }
}
```

when setting `content_type` in the upload. This seems to be a [problem][1] with the API, not the code. Am I missing something?

[1]: http://stackoverflow.com/q/22477295/1068170

**Comment by dhermes** [comment]
Also 

```python
upload.ConfigureRequest(upload_config, request, url_builder)
```

fails on a multipart upload because no content type is there:

```
.../gcloud/storage/blob.pyc in upload_from_file(self, file_obj, rewind, size, content_type, num_retri
es)
    345                                        headers=headers, body=body)
    346
--> 347         upload.ConfigureRequest(upload_config, request, url_builder)
    348         query_params = url_builder.query_params
    349         base_url = conn.API_BASE_URL + '/upload'

.../_gcloud_vendor/apitools/base/py/transfer.pyc in ConfigureRequest(self, upload_config, http_request, url_builder)
    533       if http_request.body:
    534         url_builder.query_params['uploadType'] = 'multipart'
--> 535         self.__ConfigureMultipartRequest(http_request)
    536       else:
    537         url_builder.query_params['uploadType'] = 'media'

.../_gcloud_vendor/apitools/base/py/transfer.pyc in __ConfigureMultipartRequest(self, http_request)
    556     # attach the body as one part
    557     msg = mime_nonmultipart.MIMENonMultipart(
--> 558         *http_request.headers['content-type'].split('/'))
    559     msg.set_payload(http_request.body)
    560     msg_root.attach(msg)
```

**Comment by craigcitro** [comment]
is `content-type` in the request headers?

**Comment by dhermes** [comment]
@craigcitro No. This is not an issue when `upload.ConfigureRequest` decides it should be `media` or `resumable`. Only an issue for `multipart`.

**Comment by craigcitro** [comment]
so if we're doing a simple or resumable upload, we just let the content-type be in the headers for the request.

however, for multipart, we need the content-type for the body in order to be able to assemble the whole mime/multipart message. so it's looking in the headers for a content-type, which isn't there.

where are you currently setting the content-type? can we move that up?

**Comment by dhermes** [comment]
It doesn't ever get put in headers. The only place it is used is in the creation of the `Upload` object:

```python
        upload = transfer.Upload(file_obj, content_type, total_bytes,
                                 auto_transfer=False,
                                 chunksize=self.CHUNK_SIZE)
```

**Comment by craigcitro** [comment]
ah -- right, i got confused about which content-type we were looking for.

the upload knows its content-type, and it'll set it. the one we're missing is the content type for the message body, which is just `application/json`. we just need to add that in the headers before we initialize. 

(normally this is done when apitools converts the proto message body into json:
  https://github.com/google/apitools/blob/3ea053daf8108da4d2f8d08243bad9c53656c375/apitools/base/py/base_api.py#L537
)

**Comment by dhermes** [comment]
OK Cool. Pressing pause on wrestling this needlessly. Filed #755.

**Comment by cristicbz** [comment]
Now that the migration to apitools is complete, this should be unblocked, right?

**Comment by tarrencev** [comment]
Would love this functionality

**Comment by tseaver** [comment]
#3362 includes existing blob properties with the initial (or only) upload request.
