### ISSUE TITLE
Add support for Cloud DNS

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-python#77]

**Comment by tseaver** [comment]
At this point, I consider the `gcloud.dns` on master to be "full coverage" of the API.  The only remaining work is to add system tests for it (if those are feasible to run from Travis).

**Comment by dhermes** [comment]
@tseaver What is the issue(s) with system tests?

I'll let @jgeewax weigh in

**Comment by tseaver** [comment]
I don't know of anything particular:  I just haven't investigated whether there are "ownership" or "uniqueness" issues involved in creating a zone.

**Comment by tseaver** [comment]
Ugh.  While trying to write a system test for zone creation:

```
gcloud.exceptions.BadRequest: 400 The 'example.com.' managed zone is not available to be created. (POST https://www.googleapis.com/dns/v1/projects/<project-id>/managedZones)
```

**Comment by dhermes** [comment]
Do we have a Googler API owner that can help? Or chat with the `gcloud-node` guys?

**Comment by tseaver** [comment]
@jgeewax this is the issue for DNS system tests.

**Comment by tseaver** [comment]
@jgeewax If we can get a domain managed within Cloud DNS (e.g., `gcloud-python-testing.com`, and give access to our standard projects[1], I'll get the system tests done.

[1] we need access the same projects as requested for Cloud Search in #1181.

**Comment by tseaver** [comment]
@jgeewax I think you said we had a domain available for system testing?  Can you get "the usual suspects" (@dhermes' project, mine, and the `gcloud-python-regression-tests` one) set up to manage that domain?

**Comment by dhermes** [comment]
@tseaver Send me an email / ping me on Google Hangouts and we can chat about what already exists for `gcloud-python.com`.
