### ISSUE TITLE
Remove datastore.key._dataset_ids_equal and just use string equality check

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#821]
See #528 for some history here.

The issue is that requests made using `foo` instead of `s~foo` fail in [strange ways](https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/59).

So as a result we have to use `datastore.helpers._prepare_key_for_request` to strip dataset IDs from keys that get sent to the server. This has accidental caused bugs in the past (e.g. allowing keys from a different dataset `bar` to be inserted into dataset `foo`)

**Comment by lukesneeringer** [comment]
@dhermes Can you advise on this one?

**Comment by dhermes** [comment]
@tseaver This is no longer relevant (I think because of changes made in the latest version of the API)
