### ISSUE TITLE
Performance test storage uploads and downloads

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#909]
See https://github.com/GoogleCloudPlatform/gcloud-node/issues/397

**Comment by dhermes** [comment]
For reference, we had previously had reports from @mwitkow-io of 100x slowdowns for downloads (vs. just using signed download URLs).

The downloads were for 2GB zip files (to a GCE instance in EU, using the chunked download) doing 1MB/s).

**Comment by tseaver** [comment]
See also #2222, #2927.

**Comment by lukesneeringer** [comment]
Hello,
One of the challenges of maintaining a large open source project is that sometimes, you can bite off more than you can chew. As the lead maintainer of `google-cloud-python`, I can definitely say that I have let the issues here pile up.

As part of trying to get things under control (as well as to empower us to provide better customer service in the future), I am declaring a "bankruptcy" of sorts on many of the old issues, especially those likely to have been addressed or made obsolete by more recent updates.

My goal is to close stale issues whose relevance or solution is no longer immediately evident, and which appear to be of lower importance. I believe in good faith that this is one of those issues, but I am scanning quickly and may occasionally be wrong. If this is an issue of high importance, please comment here and we will reconsider. If this is an issue whose solution is trivial, please consider providing a pull request.

Thank you!
