### ISSUE TITLE
Think about pulling this in for the translate API?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-python#970]
https://github.com/ssut/py-googletrans (or something similar)?

**Comment by dhermes** [comment]
Neat!

As far as calling a discovery-based API, we have all the mechanics in the `JSONConnection` [base class][1].

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/2ebc15a92ac77a6cf40fd6febe50f71001b6ec7c/gcloud/connection.py#L205

**Comment by dhermes** [comment]
@jgeewax Did you want us to try to pull this in? Or emulate it?

AFAICT there are only three methods (two of which will be used by a user):

- `language.detections.list`: Detect the language of text.
- `language.languages.list`: Just list languages supported by the API
- `language.translations.list`: Returns text translations from one language to another.

This should be do-able in a very short amount of work. Maybe @daspecster could get his feet wet here?

/cc @tseaver

**Comment by daspecster** [comment]
Looks like it's kind of in disrepair these days.
https://app.wercker.com/#applications/559a14a31154bc641a014c59

Could be a good starting point though. I'm game either way!

**Comment by dhermes** [comment]
I don't think we should pull in that library just start fresh with a new client / connection and maybe a class or two for the relevant nouns.
